### PR TITLE
Fix memory leak in the SCA decoder when received event with no result

### LINKED ISSUE #16211: Memory leak in the SCA decoder
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.0-RC1 | wazuh-analysisd (SCA) | Manager | All | All |

## Description

After researching the following issue https://github.com/wazuh/wazuh/issues/16189, the memory leak affecting the _wazuh-analysis_ daemon has been found, where you can see how the RSS memory increases until it reaches the limit and causes the daemon to crash.

image

## Memory report

```
==12914== 2,100 bytes in 140 blocks are indirectly lost in loss record 424 of 618
==12914==    at 0x483B7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==12914==    by 0x4979AAC: cJSON_strdup.isra.3.constprop.18 (in /var/ossec/lib/libwazuhext.so)
==12914==    by 0x497AD03: cJSON_CreateString (in /var/ossec/lib/libwazuhext.so)
==12914==    by 0x1807DA: CheckEventJSON (security_configuration_assessment.c:1451)
==12914==    by 0x17DBAE: HandleCheckEvent (security_configuration_assessment.c:768)
==12914==    by 0x17B77F: DecodeSCA (security_configuration_assessment.c:199)
==12914==    by 0x1547A0: w_decode_sca_thread (analysisd.c:1658)
==12914==    by 0x5189608: start_thread (pthread_create.c:477)
==12914==    by 0x52C5292: clone (clone.S:95)
...
==12914== 11,316 (9,216 direct, 2,100 indirect) bytes in 144 blocks are definitely lost in loss record 519 of 618
==12914==    at 0x483B7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==12914==    by 0x49792CD: cJSON_New_Item.isra.2 (in /var/ossec/lib/libwazuhext.so)
==12914==    by 0x497ACEC: cJSON_CreateString (in /var/ossec/lib/libwazuhext.so)
==12914==    by 0x1807DA: CheckEventJSON (security_configuration_assessment.c:1451)
==12914==    by 0x17DBAE: HandleCheckEvent (security_configuration_assessment.c:768)
==12914==    by 0x17B77F: DecodeSCA (security_configuration_assessment.c:199)
==12914==    by 0x1547A0: w_decode_sca_thread (analysisd.c:1658)
==12914==    by 0x5189608: start_thread (pthread_create.c:477)
==12914==    by 0x52C5292: clone (clone.S:95)
...
==12914== LEAK SUMMARY:
==12914==    definitely lost: 9,216 bytes in 144 blocks
==12914==    indirectly lost: 2,100 bytes in 140 blocks
==12914==      possibly lost: 44,064 bytes in 153 blocks
==12914==    still reachable: 24,168,343 bytes in 131,035 blocks
==12914==         suppressed: 0 bytes in 0 blocks
==12914==
==12914== For lists of detected and suppressed errors, rerun with: -s
==12914== ERROR SUMMARY: 23 errors from 23 contexts (suppressed: 0 from 0)
==12914== could not unlink /tmp/vgdb-pipe-from-vgdb-to-12914-by-???-on-6f790cc7af58
==12914== could not unlink /tmp/vgdb-pipe-to-vgdb-from-12914-by-???-on-6f790cc7af58
==12914== could not unlink /tmp/vgdb-pipe-shared-mem-vgdb-12914-by-???-on-6f790cc7af58
```

## Cause
The memory leak is caused when the following string is created, which is not being added to the cJSON object and therefore, at the time of freeing the memory of the cJSON, the memory of this item is not being freed:
https://github.com/wazuh/wazuh/blob/a51720a79b326e8e56f7535292a33330e9f3821b/src/analysisd/decoders/security_configuration_assessment.c#L1451

### PR DESCRIPTION
**Pull request by MarcelKemp**
|Related issue|
|---|
|Fixes #16211|

## Description

This PR aims to fix this memory leak, that appears when received event with no `result`:
```
==12914== 11,316 (9,216 direct, 2,100 indirect) bytes in 144 blocks are definitely lost in loss record 519 of 618
==12914==    at 0x483B7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==12914==    by 0x49792CD: cJSON_New_Item.isra.2 (in /var/ossec/lib/libwazuhext.so)
==12914==    by 0x497ACEC: cJSON_CreateString (in /var/ossec/lib/libwazuhext.so)
==12914==    by 0x1807DA: CheckEventJSON (security_configuration_assessment.c:1451)
==12914==    by 0x17DBAE: HandleCheckEvent (security_configuration_assessment.c:768)
==12914==    by 0x17B77F: DecodeSCA (security_configuration_assessment.c:199)
==12914==    by 0x1547A0: w_decode_sca_thread (analysisd.c:1658)
==12914==    by 0x5189608: start_thread (pthread_create.c:477)
==12914==    by 0x52C5292: clone (clone.S:95)
...
==12914== LEAK SUMMARY:
==12914==    definitely lost: 9,216 bytes in 144 blocks
==12914==    indirectly lost: 2,100 bytes in 140 blocks
==12914==      possibly lost: 44,064 bytes in 153 blocks
==12914==    still reachable: 24,168,343 bytes in 131,035 blocks
==12914==         suppressed: 0 bytes in 0 blocks
```

## Rationale

When an event is received that does not contain a result, a `cJSON` item is created with a string and assigned to `*result`. However, the created item is not being added to the `*result` `cJSON` object, which results in memory not being freed when the `cJSON` structure is freed.

## Proposed fix

Add the item to the `cJSON` object and mark the `check` object as checked, that way we avoid not freeing the memory of the `result` variable.

## Memory report with fix
```
==38918== LEAK SUMMARY:
==38918==    definitely lost: 0 bytes in 0 blocks
==38918==    indirectly lost: 0 bytes in 0 blocks
==38918==      possibly lost: 45,216 bytes in 157 blocks
==38918==    still reachable: 22,149,195 bytes in 120,936 blocks
==38918==         suppressed: 0 bytes in 0 blocks
```

## Tests

- Compilation without warnings in every supported platform
  - [x] Linux
- [x] Source installation
- [x] Package installation
- [x] Source upgrade
- [x] Package upgrade
- [x] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [x] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer

### CODE REVIEW

**Comment by MarcelKemp** [comment]
With the footprint metrics obtained in the following comment, where branch `16189-fix-SCA-decoder-leak` was used, which contains the fix, we can confirm that the memory leak is fixed, and no memory leak problem appears in the plots:
- https://github.com/wazuh/wazuh/issues/16189#issuecomment-1433986976

File: src/analysisd/decoders/security_configuration_assessment.c [hunk 1]
```diff
@@ -1449,6 +1449,8 @@ static int CheckEventJSON(cJSON *event, cJSON **scan_id, cJSON **id, cJSON **nam
 
         if ( *result = cJSON_GetObjectItem(*check, "result"), !*result) {
             *result = cJSON_CreateString("not applicable");
+            cJSON_AddItemToObject(*check, "result", *result);
+            cJSON_ReplaceItemInObject(event, "check", *check);
```
Comment (vikman90) [inline src/analysisd/decoders/security_configuration_assessment.c:1453]: I think this call has no effect.

Comment (chemamartinez) [reply src/analysisd/decoders/security_configuration_assessment.c]: Done https://github.com/wazuh/wazuh/pull/16214/commits/5f73c4022232e6d509b9083abd933589876298fe and tested again:

```
==7759== LEAK SUMMARY:
==7759==    definitely lost: 0 bytes in 0 blocks
==7759==    indirectly lost: 0 bytes in 0 blocks
==7759==      possibly lost: 6,336 bytes in 22 blocks
==7759==    still reachable: 23,628,990 bytes in 128,082 blocks
==7759==         suppressed: 0 bytes in 0 blocks
==7759== Reachable blocks (those to which a pointer was found) are not shown.
==7759== To see them, rerun with: --leak-check=full --show-leak-kinds=all
```

**Review by chemamartinez — APPROVED** [review]

**Review by vikman90 — APPROVED** [review]

**Comment by davidjiglesias** [comment]
:green_circle: [Approved by QA as per Validate Memory leak in the SCA decoder fix #3976](https://github.com/wazuh/wazuh-qa/issues/3976)

**Review by vikman90 — APPROVED** [review]
