### PR TITLE
Fix race condition in syscollector database cleanup

### LINKED ISSUE #6945: Windows Install CI check fail
## Description
This issue only occurs in the first post-installation start, since in the agent registration process there is a time in which there are two same wazuh processes at the same time (The unregistered one is shutting down and the registered one is going up), this requires handling the database cleanup race condition.

Actual Result: process crash
Expected result: no process crash 

```
============================= test session starts =============================
platform win32 -- Python 3.7.4, pytest-5.2.0, py-1.8.0, pluggy-0.13.0 -- c:\python37\python.exe
cachedir: .pytest_cache
metadata: {'Python': '3.7.4', 'Platform': 'Windows-10-10.0.14393-SP0', 'Packages': {'pytest': '5.2.0', 'py': '1.8.0', 'pluggy': '0.13.0'}, 'Plugins': {'html': '2.0.1', 'metadata': '1.8.0'}}
rootdir: C:\install_agent
plugins: html-2.0.1, metadata-1.8.0
collecting ... collected 5 items

install_agent_test.py::test_check_version PASSED                         [ 20%]
install_agent_test.py::test_check_process_ossec_agent FAILED             [ 40%]
install_agent_test.py::test_check_log_errors PASSED                      [ 60%]
install_agent_test.py::test_check_ossec_conf PASSED                      [ 80%]
install_agent_test.py::test_connection_agent PASSED                      [100%]

================================== FAILURES ===================================
_______________________ test_check_process_ossec_agent ________________________
install_agent_test.py:45: in test_check_process_ossec_agent
    assert ossec_agent_process_name in process_list, assert_description['process']['ossec-agent']
E   AssertionError: The ossec-agent service is not running
E   assert 'ossec-agent.exe' in ['System Idle Process', 'System', 'smss.exe', 'dwm.exe', 'svchost.exe', 'csrss.exe', ...]
========================= 1 failed, 4 passed in 0.48s =========================
```

## DoD
- [ ] Modify Code
- [ ] Run RTR
- [ ] PR with Green CI Checks

### PR DESCRIPTION
**Pull request by Dwordcito**
|Related issue|
|---|
|Closes #6945|

## Description
This issue only occurs in the first post-installation start, since in the agent registration process there is a time in which there are two same wazuh processes at the same time (The unregistered one is shutting down and the registered one is going up), this requires handling the database cleanup race condition.

Actual Result: process crash
Expected result: no process crash 

```
============================= test session starts =============================
platform win32 -- Python 3.7.4, pytest-5.2.0, py-1.8.0, pluggy-0.13.0 -- c:\python37\python.exe
cachedir: .pytest_cache
metadata: {'Python': '3.7.4', 'Platform': 'Windows-10-10.0.14393-SP0', 'Packages': {'pytest': '5.2.0', 'py': '1.8.0', 'pluggy': '0.13.0'}, 'Plugins': {'html': '2.0.1', 'metadata': '1.8.0'}}
rootdir: C:\install_agent
plugins: html-2.0.1, metadata-1.8.0
collecting ... collected 5 items

install_agent_test.py::test_check_version PASSED                         [ 20%]
install_agent_test.py::test_check_process_ossec_agent FAILED             [ 40%]
install_agent_test.py::test_check_log_errors PASSED                      [ 60%]
install_agent_test.py::test_check_ossec_conf PASSED                      [ 80%]
install_agent_test.py::test_connection_agent PASSED                      [100%]

================================== FAILURES ===================================
_______________________ test_check_process_ossec_agent ________________________
install_agent_test.py:45: in test_check_process_ossec_agent
    assert ossec_agent_process_name in process_list, assert_description['process']['ossec-agent']
E   AssertionError: The ossec-agent service is not running
E   assert 'ossec-agent.exe' in ['System Idle Process', 'System', 'smss.exe', 'dwm.exe', 'svchost.exe', 'csrss.exe', ...]
========================= 1 failed, 4 passed in 0.48s =========================
```

## RTR

image

### CODE REVIEW

File: src/shared_modules/dbsync/src/sqlite/sqlite_dbengine.cpp [hunk 1]
```diff
@@ -435,25 +436,41 @@ void SQLiteDBEngine::initialize(const std::string& path,
...
-            m_sqliteConnection = m_sqliteFactory->createConnection(path);
-            const auto createDBQueryList { Utils::split(tableStmtCreation,';') };
-            m_sqliteConnection->execute("PRAGMA temp_store = memory;");
-            m_sqliteConnection->execute("PRAGMA synchronous = OFF;");
-            for (const auto& query : createDBQueryList)
+            [this, &tableStmtCreation](const std::string& dbPath) -> bool
             {
-                const auto& stmt { getStatement(query) };
-                stmt->step();
+                bool previousDbRemoved { cleanDB(dbPath) };
```
Comment (konangc87) [inline src/shared_modules/dbsync/src/sqlite/sqlite_dbengine.cpp:445]: const

File: src/shared_modules/dbsync/src/sqlite/sqlite_dbengine.cpp [hunk 2]
```diff
@@ -435,25 +436,41 @@ void SQLiteDBEngine::initialize(const std::string& path,
 {
     if(!path.empty())
     {
-        if (cleanDB(path))
+        const auto MAX_RETRY { 10 };
```
Comment (konangc87) [inline src/shared_modules/dbsync/src/sqlite/sqlite_dbengine.cpp:439]: constexpr

File: src/shared_modules/dbsync/src/sqlite/sqlite_dbengine.cpp [hunk 3]
```diff
@@ -435,25 +436,41 @@ void SQLiteDBEngine::initialize(const std::string& path,
...
+        const auto SECONDS_TO_RETRY { 10 };
```
Comment (konangc87) [inline src/shared_modules/dbsync/src/sqlite/sqlite_dbengine.cpp:440]: ditto

File: src/shared_modules/dbsync/src/sqlite/sqlite_dbengine.cpp [hunk 4]
```diff
@@ -435,25 +436,41 @@ void SQLiteDBEngine::initialize(const std::string& path,
...
+        auto dbInitialization
```
Comment (konangc87) [inline src/shared_modules/dbsync/src/sqlite/sqlite_dbengine.cpp:441]: const

File: src/wazuh_modules/syscollector/src/syscollectorImp.cpp [hunk 5]
```diff
@@ -1120,17 +1115,21 @@ void Syscollector::syncLoop()
...
-    Utils::replaceFirst(rawData, "dbsync ", "");
-    const auto buff{reinterpret_cast<const uint8_t*>(rawData.c_str())};
-    try
-    {
-        m_spRsync->pushMessage(std::vector<uint8_t>{buff, buff + rawData.size()});
-    }
-    // LCOV_EXCL_START
-    catch(const std::exception& ex)
+    std::unique_lock<std::mutex> lock{m_mutex};
+    if (!m_running)
```
Comment (konangc87) [inline src/wazuh_modules/syscollector/src/syscollectorImp.cpp:1119]: this is awkward, name should be m_stopping xD.

File: src/wazuh_modules/syscollector/src/syscollectorImp.cpp [hunk 6]
```diff
@@ -1120,17 +1115,21 @@ void Syscollector::syncLoop()
...
-    auto rawData{data};
-    Utils::replaceFirst(rawData, "dbsync ", "");
-    const auto buff{reinterpret_cast<const uint8_t*>(rawData.c_str())};
-    try
-    {
-        m_spRsync->pushMessage(std::vector<uint8_t>{buff, buff + rawData.size()});
-    }
-    // LCOV_EXCL_START
-    catch(const std::exception& ex)
+    std::unique_lock<std::mutex> lock{m_mutex};
```
Comment (konangc87) [inline src/wazuh_modules/syscollector/src/syscollectorImp.cpp:1118]: why is the lock needed here?

**Review by konangc87 — CHANGES_REQUESTED** [review]

File: src/shared_modules/dbsync/src/sqlite/sqlite_dbengine.cpp [hunk 7]
```diff
@@ -435,25 +436,41 @@ void SQLiteDBEngine::initialize(const std::string& path,
...
+                if (previousDbRemoved)
+                {
+                    m_sqliteConnection = m_sqliteFactory->createConnection(dbPath);
+                    const auto createDBQueryList { Utils::split(tableStmtCreation,';') };
+                    m_sqliteConnection->execute("PRAGMA temp_store = memory;");
+                    m_sqliteConnection->execute("PRAGMA synchronous = OFF;");
+                    for (const auto& query : createDBQueryList)
+                    {
+                        const auto& stmt { getStatement(query) };
+                        stmt->step();
```
Comment (tinachoB) [inline src/shared_modules/dbsync/src/sqlite/sqlite_dbengine.cpp:455]: Shouldn't we need to check if `step()` returns DONE, ROW or ERROR?

File: src/wazuh_modules/syscollector/src/syscollectorImp.cpp (hunk 6 above)
Comment (Dwordcito) [reply src/wazuh_modules/syscollector/src/syscollectorImp.cpp:1118]: This is because you can try to access m_spRsync from another thread, (the one with the push) when the shutdown process has already been done and m_spRsync has been cleaned.

Comment (Dwordcito) [reply src/wazuh_modules/syscollector/src/syscollectorImp.cpp:1118]: image

**Review by tinachoB — APPROVED** [review]
LGTM!

**Review by konangc87 — APPROVED** [review]
