### PR TITLE
Changes in config.c to avoid false warnings in verify-agent-conf

### LINKED ISSUE #28873: [BUG] Cannot override `registry_limit` or `file_limit` with agent.conf
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.11.1 | Wazuh agent | Manager | All  | Windows 10 22H2 |

# Summary

Overriding `registry_limit` or `file_limit` does not work with `agent.conf`, and only works in `ossec.conf`. It should be overridden in `agent.conf` but it is not possible. `verify-agent-conf` command returns a warning as well.

# Steps to reproduce:

## Registry

- In the `agent.conf`, use a value that is not default, and force the limit by providing a root object in Registry.

```xml
<syscheck>
  <windows_registry arch="both">HKEY_LOCAL_MACHINE\*</windows_registry>
  <registry_limit>
    <enabled>yes</enabled>
    <entries>500000</entries>
  </registry_limit>
<syscheck>
```

- Run `verify-agent-conf` on the server.
- Wait until a Windows agent completes the initial syscheck
- Get an alert

## File 

- In the `agent.conf`, use a value that is not default, and force the limit by providing a root object in Registry.

```xml
<syscheck>
  <file_limit>
    <enabled>yes</enabled>
    <entries>500000</entries>
  </file_limit>
<syscheck>
```

- Run `verify-agent-conf` on the server.
- Wait until a Windows agent completes the initial syscheck
- Get an alert

### PR DESCRIPTION
**Pull request by jomafer97**
## Description

This PR closes #28873: [[BUG] Cannot override registry_limit or file_limit with agent.conf](https://github.com/wazuh/wazuh/issues/28873#top)
 by adding some changes to the config.c code.

Previously, if a user executed verify-agent-conf in a linux environment, he would get a missleading warning if the <registry_limit> element was present.

## Proposed Changes

Now the <registry_limit> section in agent.conf is properly verified, so it won't generate a warning without a reason. For this, i 

### Results and Evidence

After configuring the agent.conf file on the manager, the verification process did not produce any warnings.

image

And it was properly sent to the Windows agent:

image

### CODE REVIEW

File: src/config/syscheck-config.c [hunk 1]
```diff
@@ -1845,23 +1846,29 @@ int Read_Syscheck(const OS_XML *xml, XML_NODE node, void *configp, __attribute__
...
+#ifdef WIN32
                     syscheck->db_entry_registry_limit = atoi(children[j]->content);
 
                     if (syscheck->db_entry_registry_limit < 0) {
                         mdebug2("Maximum value allowed for registry_limit is '%d'", MAX_FILE_LIMIT);
+
                         syscheck->db_entry_registry_limit = MAX_FILE_LIMIT;
                     }
+#else
+                    if(atoi(children[j]->content) < 0){
```
Comment (MarcelKemp) [inline src/config/syscheck-config.c]:
```suggestion
                    if (atoi(children[j]->content) < 0) {
```

File: src/config/syscheck-config.c [hunk 2]
```diff
@@ -1845,23 +1846,29 @@ int Read_Syscheck(const OS_XML *xml, XML_NODE node, void *configp, __attribute__
...
+#ifdef WIN32
             if (!syscheck->registry_limit_enabled) {
                 syscheck->db_entry_registry_limit = 0;
             }
-
+#endif
             OS_ClearNode(children);
         }
-#endif
+
```
Comment (MarcelKemp) [inline src/config/syscheck-config.c:1866]: Let's remove this extra line break.

File: src/config/syscheck-config.c [hunk 3]
```diff
@@ -1845,23 +1846,29 @@ int Read_Syscheck(const OS_XML *xml, XML_NODE node, void *configp, __attribute__
                         OS_ClearNode(children);
                         return (OS_INVALID);
                     }
-
+#ifdef WIN32
                     syscheck->db_entry_registry_limit = atoi(children[j]->content);
 
                     if (syscheck->db_entry_registry_limit < 0) {
                         mdebug2("Maximum value allowed for registry_limit is '%d'", MAX_FILE_LIMIT);
+
```
Comment (MarcelKemp) [inline src/config/syscheck-config.c]: Let's remove this extra line break.

**Review by MarcelKemp — APPROVED** [review]

**Comment by jotacarma90** [comment]
## Tested in both Windows and Linux agents


- Agent.conf:
```
<agent_config>
<syscheck>
  <registry_limit>
    <enabled>yes</enabled>
    <entries>22222</entries>
  </registry_limit>
  <file_limit>
    <enabled>yes</enabled>
    <entries>331111</entries>
  </file_limit>
</syscheck>
</agent_config>
```
- Windows agent overwrites both setting correctly:
```
2025/08/04 07:09:51 wazuh-agent[8960] run_check.c:276 at start_daemon(): DEBUG: (6342): Maximum number of files to be monitored: '331111'
2025/08/04 07:09:51 wazuh-agent[8960] run_check.c:283 at start_daemon(): DEBUG: (6370): Maximum number of registry values to be monitored: '22222'
```

- Linux agent overwrite file_limit:

```
2025/08/04 14:09:55 wazuh-syscheckd[52692] run_check.c:276 at start_daemon(): DEBUG: (6342): Maximum number of files to be monitored: '331111'
```

- verify-agent-conf:

```
[root@fedora40 src]# /var/ossec/bin/verify-agent-conf

verify-agent-conf: Verifying [etc/shared/default/agent.conf]
verify-agent-conf: OK
```

**Review by jotacarma90 — APPROVED** [review]
