### PR TITLE
Optimize error handling geoip locator

### LINKED ISSUE #35128: wazuh-engine: Optimize GeoIP Locator, replace error string allocation with lightweight result code
## Description

The current GeoIP module uses a `locator` handler to query data from the GeoIP database. When a lookup fails, the locator returns an **error string**, which is later consumed.

This behavior introduces unnecessary overhead in production:

* **String allocations** per lookup failure
* Increased **memory fragmentation**
* Additional **CPU cost** for formatting error messages

In practice, detailed error messages are only useful in **logtest/debug scenarios**, not in the production pipeline.

This issue proposes replacing error string allocation with a **lightweight return model**, such as an enum-based status code or a structured result type.

---

## Objectives

* Remove dynamic string allocation for error reporting in the GeoIP locator.
* Replace error handling with:

  * an **enum-based error code**, or
  * a lightweight result type (e.g., `expected<T, ErrorCode>` or similar)
* Preserve the ability to produce detailed error messages when needed (e.g., logtest).

---

### 1) Introduce Result Type

Replace current return pattern with something like:

```cpp
Result<GeoData, GeoError>
```

Where:

* `GeoData` → successful lookup result
* `GeoError` → enum representing failure reason

Example:

```cpp
enum class GeoError {
    NotFound,
    InvalidIP,
    DBNotLoaded,
    InternalError
};
```

---

### 2) Avoid String Allocation in Hot Path

* Locator must not allocate strings during normal execution.
* Error messages should only be generated:

  * on demand
  * or in debug/logtest contexts

---

### 3) Optional Error Translation Layer

* Provide a helper to translate `GeoError` → human-readable string when needed.
* Used only in:

  * logtest
  * debugging/logging layers

---

## Requirements

* No behavioral regression in lookup results.
* Production path must avoid heap allocations for errors.
* Ensure thread-safety and compatibility with current locator lifecycle.
* Minimal impact on existing enrichment pipeline.

---

## Deliverables

* Refactored GeoIP locator returning enum-based error codes (or equivalent result type).
* Removal of string allocation in error paths.
* Optional utility for converting error codes to strings.
* Unit tests covering:

  * successful lookups
  * each error condition
  * performance regression check (optional but recommended)

### PR DESCRIPTION
**Pull request by LucioDonda**
## Description

closes #35128 

## Proposed Changes

* [Commit](https://github.com/wazuh/wazuh/pull/35187/changes/1949b65b6897404bb5e141705a5a459a0afd95a5) for fixing metadata simplification
* [commit](https://github.com/wazuh/wazuh/pull/35187/changes/11348d737d066b56c7dbe2e646b6f5f7c16f13b4) for configuration fields fix
* [commit](https://github.com/wazuh/wazuh/pull/35187/changes/cad796ebd746a60b2869547102b72a3e8e1f15ed) for 
copilot skills addition 
* geo benchamr error handling improvement
  * benchmarking

### Results and Evidence

* Metadata evidence:

```console

(venv) ╭─root@927d655b62ac /workspaces/devContainer 
╰─# python3 send_logtest.py --socket /var/wazuh-manager/queue/sockets/analysis \
    --queue 1 \
    --location test \
    --event 'CEF:0|Acme|Demo|1.0|100|Test event|5|' --session "testing"
Error: Request failed: {"status":"ERROR","error":"The 'testing' environment does not exist."}
(venv) ╭─root@927d655b62ac /workspaces/devContainer 
╰─# python3 send_logtest.py --socket /var/wazuh-manager/queue/sockets/analysis \       130 ↵
    --queue 1 \
    --location test \
    --event 'CEF:0|Acme|Demo|1.0|100|Test event|5|' --session "testing" \
    --metadata ''
Error: Request failed: {"status":"ERROR","error":"The 'testing' environment does not exist."}
(venv) ╭─root@927d655b62ac /workspaces/devContainer 
╰─# python3 send_logtest.py --socket /var/wazuh-manager/queue/sockets/analysis \         1 ↵
    --queue 1 \
    --location test \
    --event 'CEF:0|Acme|Demo|1.0|100|Test event|5|' --session "testing" \
    --metadata '{}'
Error: Request failed: {"status":"ERROR","error":"The 'testing' environment does not exist."}
(venv) ╭─root@927d655b62ac /workspaces/devContainer 
╰─# python3 send_logtest.py --socket /var/wazuh-manager/queue/sockets/analysis \         1 ↵
    --queue 1 \
    --location test \
    --event 'CEF:0|Acme|Demo|1.0|100|Test event|5|' --session "testing" \
    --metadata '{"wazuh":{}}'
Error: Request failed: {"status":"ERROR","error":"The 'testing' environment does not exist."}
(venv) ╭─root@927d655b62ac /workspaces/devContainer 
╰─# python3 send_logtest.py --socket /var/wazuh-manager/queue/sockets/analysis \         1 ↵
    --queue 1 \
    --location test \
    --event 'CEF:0|Acme|Demo|1.0|100|Test event|5|' --session "testing" \
    --metadata '{"wazuh":{"agent":{"id":"1234"}}}'
Error: Request failed: {"status":"ERROR","error":"The 'testing' environment does not exist."}
(venv) ╭─root@927d655b62ac /workspaces/devContainer 
╰─# python3 send_logtest.py --socket /var/wazuh-manager/queue/sockets/analysis \         1 ↵
    --queue 1 \
    --location test \
    --event 'CEF:0|Acme|Demo|1.0|100|Test event|5|' --session "testing" \
    --metadata '{"wazuh":{"agent":{"id":1234}}}'
Error: Request failed: {"status":"ERROR","error":"Metadata field 'wazuh.agent.id' doesn't exist or doesn't match the expected one from the schema"}
(venv) ╭─root@927d655b62ac /workspaces/devContainer 
╰─# python3 send_logtest.py --socket /var/wazuh-manager/queue/sockets/analysis \         1 ↵
    --queue 1 \
    --location test \
    --event 'CEF:0|Acme|Demo|1.0|100|Test event|5|' --session "testing" \
    --metadata '{"wazuh":{"agent":{"Randomid":"1234"}}}'
Error: Request failed: {"status":"ERROR","error":"Metadata field 'wazuh.agent.Randomid' doesn't exist or doesn't match the expected one from the schema"}
(venv) ╭─root@927d655b62ac /workspaces/devContainer 
╰─# python3 send_logtest.py --socket /var/wazuh-manager/queue/sockets/analysis \         1 ↵
    --queue 1 \
    --location test \
    --event 'CEF:0|Acme|Demo|1.0|100|Test event|5|' --session "testing" \
    --metadata '{"random":{"agent":{"Randomid":"1234"}}}'
Error: Request failed: {"status":"ERROR","error":"Metadata should contain 'wazuh' as root"}
(venv) ╭─root@927d655b62ac /workspaces/devContainer 
╰─# python3 send_logtest.py --socket /var/wazuh-manager/queue/sockets/analysis \         1 ↵
    --queue 1 \
    --location test \
    --event 'CEF:0|Acme|Demo|1.0|100|Test event|5|' --session "testing" \
    --metadata '{"agent":{"id":"1234"}}'
Error: Request failed: {"status":"ERROR","error":"Metadata should contain 'wazuh' as root"}

```

* Benchmarking of modules

```console
╰─# src/build/engine/source/geo/geo_benchmark
2026-04-07T18:55:16+00:00
Running src/build/engine/source/geo/geo_benchmark
Run on (16 X 3792.84 MHz CPU s)
CPU Caches:
  L1 Data 64 KiB (x16)
  L1 Instruction 64 KiB (x16)
  L2 Unified 512 KiB (x16)
  L3 Unified 16384 KiB (x1)
Load Average: 0.26, 0.14, 0.04
------------------------------------------------------------------------------------------------
Benchmark                                      Time             CPU   Iterations UserCounters...
------------------------------------------------------------------------------------------------
BM_Locator_getString_CacheHit                143 ns          143 ns      4901023 items_per_second=7.00094M/s
BM_Locator_getString_CacheMiss               252 ns          252 ns      2767298 items_per_second=3.97014M/s
BM_Locator_getString_NotFound               27.2 ns         27.2 ns     25745804 items_per_second=36.7893M/s
BM_Locator_getString_FieldNotFound           193 ns          193 ns      3603729 items_per_second=5.17267M/s
BM_Locator_getDouble_CacheHit                103 ns          103 ns      6745508 items_per_second=9.71431M/s
BM_Locator_getDouble_CacheMiss               225 ns          225 ns      3098422 items_per_second=4.44894M/s
BM_Locator_getUint32_CacheHit                183 ns          183 ns      3820174 items_per_second=5.45478M/s
BM_Locator_getUint32_CacheMiss               265 ns          265 ns      2654339 items_per_second=3.7792M/s
BM_Locator_getAsJson_Scalar_CacheHit         204 ns          204 ns      3415637 items_per_second=4.90395M/s
BM_Locator_getAsJson_Scalar_CacheMiss        329 ns          329 ns      2139401 items_per_second=3.04137M/s
BM_Locator_getAll_CacheHit                  2137 ns         2137 ns       327429 items_per_second=467.972k/s
BM_Locator_getAll_CacheMiss                 1459 ns         1459 ns       482944 items_per_second=685.517k/s
BM_Locator_getAll_NotFound                  25.1 ns         25.1 ns     27872164 items_per_second=39.9136M/s
BM_Locator_mapGeoPattern_CacheHit           2263 ns         2263 ns       311278 items_per_second=441.956k/s
BM_Locator_mapGeoPattern_CacheMiss          2123 ns         2123 ns       331608 items_per_second=470.95k/s
BM_Locator_mapASPattern_CacheHit             439 ns          439 ns      1584687 items_per_second=2.27684M/s
BM_Locator_mapASPattern_CacheMiss            490 ns          490 ns      1427913 items_per_second=2.04005M/s
BM_Manager_getLocator                       27.5 ns         27.5 ns     25457761 items_per_second=36.3538M/s
╭─root@927d655b62ac /workspaces/devContainer/wazuh ‹enhancement/35128-wazuh-engine-optimize-error-handling-geoip-locator› 
╰─# src/build/engine/source/builder/builder_benchmark 
2026-04-07T18:55:57+00:00
Running src/build/engine/source/builder/builder_benchmark
Run on (16 X 3792.84 MHz CPU s)
CPU Caches:
  L1 Data 64 KiB (x16)
  L1 Instruction 64 KiB (x16)
  L2 Unified 512 KiB (x16)
  L3 Unified 16384 KiB (x1)
Load Average: 0.28, 0.17, 0.06
-------------------------------------------------------------------------------------------
Benchmark                                 Time             CPU   Iterations UserCounters...
-------------------------------------------------------------------------------------------
BM_GeoAS_KnownIP_NoTrace               3963 ns         3964 ns       177280 items_per_second=252.294k/s
BM_GeoAS_KnownIP_Trace                 4159 ns         4159 ns       171112 items_per_second=240.431k/s
BM_GeoOnly_KnownIP_NoTrace             3552 ns         3552 ns       199358 items_per_second=281.505k/s
BM_ASOnly_KnownIP_NoTrace              1137 ns         1137 ns       610091 items_per_second=879.851k/s
BM_GeoAS_UnknownIP_NoTrace             2101 ns         2101 ns       329508 items_per_second=475.916k/s
BM_GeoAS_UnknownIP_Trace               2172 ns         2172 ns       319954 items_per_second=460.356k/s
BM_GeoAS_MissingIP_NoTrace              495 ns          495 ns      1421150 items_per_second=2.01983M/s
BM_GeoAS_MissingIP_Trace                615 ns          615 ns      1139135 items_per_second=1.62503M/s
BM_EmptyLocators_KnownIP_NoTrace       2030 ns         2030 ns       345166 items_per_second=492.637k/s
BM_GeoAS_ArrayIP_NoTrace               4164 ns         4164 ns       170296 items_per_second=240.134k/s
```

### Manual tests with their corresponding evidence

- Compilation without warnings on every supported platform
  - [ ] Linux
  - [ ] Windows 
  - [ ] MAC OS X
- [ ] Log syntax and correct language review

- Memory tests for Linux
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Coverity
  - [ ] UMDH
- Memory tests for macOS
  - [ ] Leaks
  - [ ] AddressSanitizer

- Decoder/Rule tests _(Wazuh v4.x)_
  - [ ] Added unit testing files ".ini"
  - [ ] `runtests.py` executed without errors

- Engine _(Wazuh v5.x and above)_
  - [ ] Test run in parallel
  - [ ] ASAN for test (utest/ctest)
  - [ ] TSAN for test and wazuh-engine.

- Wazuh server API/Framework
  - [ ] Run API Integration Tests

## Review Checklist

- [ ] Code changes reviewed
- [ ] Relevant evidence provided
- [ ] Tests cover the new functionality
- [ ] Configuration changes documented
- [ ] Developer documentation reflects the changes
- [ ] Meets requirements and/or definition of done
- [ ] No unresolved dependencies with other issues
- [ ] ...

### CODE REVIEW

File: src/engine/source/api/tester/src/handlers.cpp [hunk 1]
```diff
@@ -545,27 +529,41 @@ adapter::RouteHandler publicRunPost(const std::shared_ptr<::router::ITesterAPI>&
...
+            if (!schemaValidatorLocked)
+            {
+                res = adapter::userErrorResponse<ResponseType>("Schema is not available");
+                return;
+            }
 
             std::string badFieldMsg {};
             std::string metadataPath {"wazuh"};
-            if (!validateMetadataLeaves(wazuhMetadataObject, schemaValidatorLocked, metadataPath, badFieldMsg))
+            auto metadataObj = metadata.getJson("/wazuh");
```
Comment (jam300) [inline src/engine/source/api/tester/src/handlers.cpp]: Empty metadata `({}) `is accepted earlier, but this line assumes /wazuh always exists. Calling .value() here can throw and cause the 500 we reproduce on` POST /logtest.`

```bash

(venv) ╭─root@wazuh5x-dev /workspaces/Wazuh_5x/wazuh ‹enhancement/35128-wazuh-engine-optimize-error-handling-geoip-locator●› 
╰─# curl --unix-socket /var/wazuh-manager/queue/sockets/analysis \
  -H 'Content-Type: text/plain' \
  --data '{"queue":1,"location":"/tmp/pr35187.log","metadata":{},"event":"testing","trace_level":"NONE","space":"test"}' \
  http://localhost/logtest

Internal server error#    

```

Other invalid metadata cases return controlled errors, so this looks specific to the empty-metadata path.
It may be worth handling the empty metadata case before calling metadata.getJson("/wazuh").value().

something like that:

```c++
            if (!metadata.isEmpty())
            {
                auto metadataObj = metadata.getJson("/wazuh");
                if (!validateMetadataLeaves(metadataObj.value(), schemaValidatorLocked, metadataPath, badFieldMsg))
                {
                    res = adapter::userErrorResponse<ResponseType>(badFieldMsg);
                    return;
                }
            }
```

File: src/engine/source/main.cpp [hunk 2]
```diff
@@ -402,7 +402,7 @@ int main(int argc, char* argv[])
                 const auto maxQueueSize = confManager.get<size_t>(conf::key::INDEXER_QUEUE_MAX_EVENTS);
                 jsonCnf.setUint64(maxQueueSize, "/max_queue_size");
                 const auto maxHitsPerRequest =
-                    confManager.get<std::size_t>(conf::key::INDEXER_CONNECTOR_MAX_HITS_PER_REQUEST);
+                    confManager.get<std::size_t>(conf::key::CMSYNC_INDEXER_CONNECTOR_SYNC_BATCH_SIZE);
```
Comment (jam300) [inline src/engine/source/main.cpp:405]: Is this the intended behavior? `analysisd.cmsync_indexer_connector_sync_batch_size` now seems to control `WIndexerConnector::maxHitsPerRequest` as well, and setting it to 0 breaks Indexer Connector initialization.

set analysisd.cmsync_indexer_connector_sync_batch_size=0 and restart 

```bash

(venv) ╭─root@wazuh5x-dev /workspaces/Wazuh_5x/wazuh ‹enhancement/35128-wazuh-engine-optimize-error-handling-geoip-locator●› 
╰─# service wazuh-manager start
Starting Wazuh v5.0.0...
Started wazuh-manager-apid...
Started wazuh-manager-authd...
Started wazuh-manager-db...
wazuh-manager-analysisd died during route check.
wazuh-manager-analysisd did not start correctly.

```

```console
2026/04/06 23:54:38 wazuh-manager-authd: INFO: Started (pid: 277784).
2026/04/06 23:54:38 wazuh-manager-db: INFO: Started (pid: 277793).
2026/04/06 23:54:38 wazuh-manager-analysisd: INFO: Store initialized.
2026/04/06 23:54:38 wazuh-manager-analysisd: INFO: Content Manager initialized.
2026/04/06 23:54:38 wazuh-manager-analysisd: INFO: KVDB initialized.
2026/04/06 23:54:41 wazuh-manager-analysisd: INFO: KVDB IOC initialized.
2026/04/06 23:54:41 wazuh-manager-analysisd: INFO: Geo initialized.
2026/04/06 23:54:41 wazuh-manager-analysisd: INFO: Schema initialized.
2026/04/06 23:54:41 wazuh-manager-analysisd: INFO: HLP initialized.
2026/04/06 23:54:41 wazuh-manager-analysisd: ERROR: An error occurred while initializing the modules: Could not initialize Indexer Connector: maxHitsPerRequest must be greater than zero.

```

File: src/engine/source/api/tester/src/handlers.cpp (hunk 1 above)
Comment (LucioDonda) [reply src/engine/source/api/tester/src/handlers.cpp]: Fixed!

File: src/engine/source/main.cpp (hunk 2 above)
Comment (LucioDonda) [reply src/engine/source/main.cpp:405]: max hits per request finally arrives to:

```cpp
    nlohmann::json search(const PointInTime& pit,
                          std::size_t size,
                          const nlohmann::json& query,
                          const nlohmann::json& sort,
                          const std::optional<nlohmann::json>& searchAfter,
                          const std::optional<nlohmann::json>& source,
                          const std::optional<nlohmann::json>& slice = std::nullopt)
```
from `src/shared_modules/indexer_connector/src/indexerConnectorAsyncImpl.hpp`

and the other sync batch sizes ends up in similar arguments:

this is from `IOC_INDEXER_CONNECTOR_SYNC_BATCH_SIZE` 

```cpp
        nlohmann::json hits =
            m_indexerConnectorAsync->search(pit, effectiveBatchSize, query, sort, searchAfter, source);
```

and because the idea is to unify the configs the change has sense. 

The 0 limit has sense, what I could do is unify the process to a fallback value like the other configs.

File: src/engine/source/geo/interface/geo/errorCodes.hpp [hunk 3]
```diff
@@ -0,0 +1,206 @@
...
+    }
+    /**
+     * @brief Convert to human-readable OptError string
+     *
+     * This converts the Result<T> to human-readable error messages.
+     */
+    std::string readableStr() const
+    {
+        return {std::string {getErrorDescription(error())}};
+    }
```
Comment (matigarciadev) [inline src/engine/source/geo/interface/geo/errorCodes.hpp:171]: `geo::Result<T>::readableStr()` is unsafe for successful results. It always calls `error()`, which does `std::get<ErrorCode>(m_value)`. For a success state this will throw `std::bad_variant_access`. Since `operator<<` unconditionally calls `readableStr()`, even logging/printing a successful `Result<T>` becomes unsafe.

File: src/engine/source/builder/src/builders/opmap/mmdb.cpp [hunk 4]
```diff
@@ -145,7 +129,10 @@ MapBuilder getMMDBGeoBuilder(const std::shared_ptr<geo::IManager>& geoManager)
         const std::string notFoundDBTrace {fmt::format("{} -> Failure: IP Not found in DB", name)};
         const std::string emptyDataTrace {fmt::format("{} -> Failure: Empty wcs data", name)};
 
-        return [=, locator = base::getResponse(resDB), srcRef = ipRef.jsonPath()](base::ConstEvent event) -> MapResult
+        auto resDB = geoManager->getLocator(geo::Type::CITY);
+        auto runstate = buildCtx->runState();
+
+        return [=, locator = resDB.value(), srcRef = ipRef.jsonPath()](base::ConstEvent event) -> MapResult
```
Comment (matigarciadev) [inline src/engine/source/builder/src/builders/opmap/mmdb.cpp:140]: This change removes the previous controlled failure path when `getLocator()` returns an error. Before, the builder returned a fail transform with a trace; now it captures `resDB.value()` unconditionally. That turns a recoverable/configuration error into a variant access failure / exception path. Also, the dependency tests that covered failing locators were removed, so this regression is no longer exercised.

File: src/engine/source/builder/src/builders/opmap/mmdb.cpp [hunk 5]
```diff
@@ -192,14 +179,9 @@ MapBuilder getMMDBASNBuilder(const std::shared_ptr<geo::IManager>& geoManager)
...
         auto resDB = geoManager->getLocator(geo::Type::ASN);
-        // TODO Temporary error handling, this should be mandatory
         auto runstate = buildCtx->runState();
-        if (base::isError(resDB))
-        {
-            return dumpFailTransform("Error getting geo asn locator: " + base::getError(resDB).message, runstate);
-        }
 
-        return [=, locator = base::getResponse(resDB), srcRef = ipRef.jsonPath()](base::ConstEvent event) -> MapResult
+        return [=, locator = resDB.value(), srcRef = ipRef.jsonPath()](base::ConstEvent event) -> MapResult
```
Comment (matigarciadev) [inline src/engine/source/builder/src/builders/opmap/mmdb.cpp:193]: This change removes the previous controlled failure path when `getLocator()` returns an error. Before, the builder returned a fail transform with a trace; now it captures `resDB.value()` unconditionally. That turns a recoverable/configuration error into a variant access failure / exception path. Also, the dependency tests that covered failing locators were removed, so this regression is no longer exercised.

File: src/engine/source/builder/src/builders/enrichment/geo.cpp [hunk 6]
```diff
@@ -325,18 +325,18 @@ std::pair<base::Expression, std::string> geoEnrichmentBuilder(const std::shared_
...
     {
-        throw std::runtime_error("Error getting geo asn locator: " + base::getError(as).message);
+        throw std::runtime_error("Error getting geo asn locator: " + std::to_string(static_cast<int>(as.error())));
     }
-    if (base::isError(city))
+    if (city.isError())
     {
-        throw std::runtime_error("Error getting geo city locator: " + base::getError(city).message);
+        throw std::runtime_error("Error getting geo city locator: " + std::to_string(static_cast<int>(city.error())));
     }
```
Comment (matigarciadev) [inline src/engine/source/builder/src/builders/enrichment/geo.cpp:353]: The refactor already introduces `getErrorDescription(ErrorCode)`, so throwing the numeric enum value here is a diagnostics regression. Please preserve a human-readable message at this layer.

File: src/engine/source/api/tester/src/handlers.cpp [hunk 7]
```diff
@@ -84,42 +84,26 @@ eTester::Result fromOutput(const ::router::test::Output& output)
...
-    {
-        return std::make_pair(json::Json("{}"), json::Json("{}"));
-    }
-
-    auto wazuhMetadataObject = metadata.getJson("/wazuh");
-    auto wazuhRootObjectOpt = wazuhMetadataObject ? wazuhMetadataObject->getJson() : std::nullopt;
-    if (!wazuhMetadataObject.has_value() || !wazuhMetadataObject->isObject())
-    {
-        return base::Error {"Metadata must be a non-empty object with 'wazuh' as root"};
-    }
```
Comment (matigarciadev) [inline src/engine/source/api/tester/src/handlers.cpp]: Before, `parseAndValidatePublicMetadata()` explicitly validated that the root `/wazuh` was an `object`. now only validates `has_value()`. Is this regression justified?

I don't see any tests that validate the error in cases like:
- {"wazuh":"abc"}
- {"wazuh":[]}
- {"wazuh":123}

File: src/engine/source/geo/interface/geo/errorCodes.hpp (hunk 3 above)
Comment (LucioDonda) [reply src/engine/source/geo/interface/geo/errorCodes.hpp:171]: Done

File: src/engine/source/builder/src/builders/opmap/mmdb.cpp (hunk 4 above)
Comment (LucioDonda) [reply src/engine/source/builder/src/builders/opmap/mmdb.cpp:140]: The dumpFailTransform removal was intended. The Throw now remains

File: src/engine/source/builder/src/builders/opmap/mmdb.cpp (hunk 5 above)
Comment (LucioDonda) [reply src/engine/source/builder/src/builders/opmap/mmdb.cpp:193]: Same as the other

File: src/engine/source/builder/src/builders/enrichment/geo.cpp (hunk 6 above)
Comment (LucioDonda) [reply src/engine/source/builder/src/builders/enrichment/geo.cpp:353]: Done!

File: src/engine/source/api/tester/src/handlers.cpp (hunk 7 above)
Comment (LucioDonda) [reply src/engine/source/api/tester/src/handlers.cpp]: done

Comment (LucioDonda) [reply src/engine/source/api/tester/src/handlers.cpp]: done

**Comment by jam300** [comment]
## LGTM


### Build & Install

```bash

General settings:
    TARGET:             manager
    V:                  
    DEBUG:              yes
    INSTALLDIR:         
    RESOURCES_URL:      https://packages.wazuh.com/deps/99-29585
    EXTERNAL_SRC_ONLY:  
    HTTP_REQUEST_BRANCH:ebf9d2f82533ff2f84c3304ab29db01fcfb6735e
User settings:
    WAZUH_GROUP:        wazuh-manager
    WAZUH_USER:         wazuh-manager
USE settings:
    USE_INOTIFY:        no
    USE_BIG_ENDIAN:     no
    USE_SELINUX:        no
    USE_AUDIT:          no
    IMAGE_TRUST_CHECKS: 1
    CA_NAME:            DigiCert Assured ID Root CA
Compiler:
    CC                gcc
    MAKE              /usr/bin/make
make[1]: Leaving directory '/workspaces/Wazuh_5x/wazuh/src'

Done building manager


╭─root@wazuh5x-dev /workspaces/Wazuh_5x/wazuh ‹enhancement/35128-wazuh-engine-optimize-error-handling-geoip-locator●› 
╰─# service wazuh-manager status
wazuh-manager-clusterd is running...
wazuh-manager-modulesd is running...
wazuh-manager-monitord is running...
wazuh-manager-remoted is running...
wazuh-manager-analysisd is running...
wazuh-manager-db is running...
wazuh-manager-authd is running...
wazuh-manager-apid is running...

```

```console

2026/04/13 15:22:16 wazuh-manager-analysisd: INFO: Archiver initialized.
2026/04/13 15:22:16 wazuh-manager-analysisd: INFO: Remote engine's server initialized and started.
2026/04/13 15:22:16 wazuh-manager-analysisd: INFO: Engine started and ready to process events.

```

``` bash

(venv) ╭─root@wazuh5x-dev /workspaces/Wazuh_5x/wazuh ‹enhancement/35128-wazuh-engine-optimize-error-handling-geoip-locator●› 
╰─# engine-private ns list
- cmsync_custom_a39f
- cmsync_standard_5d05

(venv) ╭─root@wazuh5x-dev /workspaces/Wazuh_5x/wazuh ‹enhancement/35128-wazuh-engine-optimize-error-handling-geoip-locator●› 
╰─# engine-router list
- entry_status: ENABLED
  name: cmsync_standard
  namespaceId: cmsync_standard_5d05
  priority: 1
  uptime: 169
- entry_status: ENABLED
  name: cmsync_custom
  namespaceId: cmsync_custom_a39f
  priority: 2
  uptime: 168


```

### Testing

``` bash

(venv) ╭─root@wazuh5x-dev /workspaces/Wazuh_5x/wazuh ‹enhancement/35128-wazuh-engine-optimize-error-handling-geoip-locator●› 
╰─# curl --unix-socket /var/wazuh-manager/queue/sockets/analysis \
  -H 'Content-Type: text/plain' \
  --data '{"queue":1,"location":"/tmp/pr35187.log","metadata":{},"event":"testing","trace_level":"NONE","space":"test"}' \
  http://localhost/logtest

{"status":"OK","result":{"output":{"@timestamp":"2026-04-13T15:32:57Z","wazuh":{"space":{"name":"standard"},"integration":{"category":"security","decoders":["decoder/core-wazuh-message/0","decoder/integrations/0"],"name":"wazuh-core"},"protocol":{"queue":1,"location":"/tmp/pr35187.log"}},"event":{"original":"testing"}},"asset_traces":[],"validation":{"valid":true,"errors":[]}}}#                                                                                 
(venv) ╭─root@wazuh5x-dev /workspaces/Wazuh_5x/wazuh ‹enhancement/35128-wazuh-engine-optimize-error-handling-geoip-locator●› 
╰─# curl --unix-socket /var/wazuh-manager/queue/sockets/analysis \
  -H 'Content-Type: text/plain' \
  --data '{"queue":1,"location":"/tmp/pr35187.log","metadata":{"badroot":{"x":"y"}},"event":"testing","trace_level":"NONE","space":"test"}' \
  http://localhost/logtest

{"status":"ERROR","error":"Metadata should contain 'wazuh' as root"}#            


(venv) ╭─root@wazuh5x-dev /workspaces/Wazuh_5x/wazuh ‹enhancement/35128-wazuh-engine-optimize-error-handling-geoip-locator●› 
╰─# curl --unix-socket /var/wazuh-manager/queue/sockets/analysis \
  -H 'Content-Type: text/plain' \
  --data '{"queue":1,"location":"/tmp/pr35187.log","metadata":{"wazuh":{}},"event":"testing","trace_level":"NONE","space":"test"}' \
  http://localhost/logtest

{"status":"OK","result":{"output":{"@timestamp":"2026-04-13T15:36:19Z","event":{"original":"testing"},"wazuh":{"integration":{"name":"wazuh-core","category":"security","decoders":["decoder/core-wazuh-message/0","decoder/integrations/0"]},"space":{"name":"standard"},"protocol":{"queue":1,"location":"/tmp/pr35187.log"}}},"asset_traces":[],"validation":{"valid":true,"errors":[]}}}#      


(venv) ╭─root@wazuh5x-dev /workspaces/Wazuh_5x/wazuh ‹enhancement/35128-wazuh-engine-optimize-error-handling-geoip-locator●› 
╰─# curl --unix-socket /var/wazuh-manager/queue/sockets/analysis \
  -H 'Content-Type: text/plain' \
  --data '{"queue":1,"location":"/tmp/pr35187.log","metadata":null,"event":"testing","trace_level":"NONE","space":"test"}' \
  http://localhost/logtest

{"status":"OK","result":{"output":{"event":{"original":"testing"},"wazuh":{"integration":{"category":"security","name":"wazuh-core","decoders":["decoder/core-wazuh-message/0","decoder/integrations/0"]},"protocol":{"queue":1,"location":"/tmp/pr35187.log"},"space":{"name":"standard"}},"@timestamp":"2026-04-13T15:36:39Z"},"asset_traces":[],"validation":{"valid":true,"errors":[]}}}#      


(venv) ╭─root@wazuh5x-dev /workspaces/Wazuh_5x/wazuh ‹enhancement/35128-wazuh-engine-optimize-error-handling-geoip-locator●› 
╰─# curl --unix-socket /var/wazuh-manager/queue/sockets/analysis \
  -H 'Content-Type: text/plain' \
  --data '{"queue":1,"location":"/tmp/pr35187.log","event":"testing","trace_level":"BAD_LEVEL","space":"test"}' \
  http://localhost/logtest

{"status":"ERROR","error":"Invalid trace level: BAD_LEVEL. Only support: NONE, ASSET_ONLY, ALL"}#    


(venv) ╭─root@wazuh5x-dev /workspaces/Wazuh_5x/wazuh ‹enhancement/35128-wazuh-engine-optimize-error-handling-geoip-locator●› 
╰─# engine-private geo list

- createdAt: '1776086532'
  hash: f506f9919c66c2a3829b5ed4591711b3
  name: GeoLite2-ASN.mmdb
  path: /var/wazuh-manager/data/mmdb/GeoLite2-ASN.mmdb
  type: asn
- createdAt: '1770030728'
  hash: 3f377dd93bc3f9a4a0bfb7d994a61b60
  name: GeoLite2-City.mmdb
  path: /var/wazuh-manager/data/mmdb/GeoLite2-City.mmdb
  type: city

(venv) ╭─root@wazuh5x-dev /workspaces/Wazuh_5x/wazuh ‹enhancement/35128-wazuh-engine-optimize-error-handling-geoip-locator●› 
╰─# engine-private geo get 1.2.3.4

{
  "as": {},
  "geo": {
    "registered_country": {
      "iso_code": "AU",
      "geoname_id": 2077456.0,
      "names": {
        "pt-BR": "Austr\u00e1lia",
        "ru": "\u0410\u0432\u0441\u0442\u0440\u0430\u043b\u0438\u044f",
        "en": "Australia",
        "de": "Australien",
        "es": "Australia",
        "ja": "\u30aa\u30fc\u30b9\u30c8\u30e9\u30ea\u30a2",
        "zh-CN": "\u6fb3\u5927\u5229\u4e9a",
        "fr": "Australie"
      }
    },
    "continent": {
      "names": {
        "pt-BR": "Oceania",
        "ru": "\u041e\u043a\u0435\u0430\u043d\u0438\u044f",
        "en": "Oceania",
        "ja": "\u30aa\u30bb\u30a2\u30cb\u30a2",
        "es": "Ocean\u00eda",
        "de": "Ozeanien",
        "zh-CN": "\u5927\u6d0b\u6d32",
        "fr": "Oc\u00e9anie"
      },
      "geoname_id": 6255151.0,
      "code": "OC"
    },
    "location": {
      "latitude": -33.494,
      "accuracy_radius": 1000.0,
      "time_zone": "Australia/Sydney",
      "longitude": 143.2104
    },
    "country": {
      "iso_code": "AU",
      "geoname_id": 2077456.0,
      "names": {
        "pt-BR": "Austr\u00e1lia",
        "ru": "\u0410\u0432\u0441\u0442\u0440\u0430\u043b\u0438\u044f",
        "en": "Australia",
        "ja": "\u30aa\u30fc\u30b9\u30c8\u30e9\u30ea\u30a2",
        "de": "Australien",
        "zh-CN": "\u6fb3\u5927\u5229\u4e9a",
        "es": "Australia",
        "fr": "Australie"
      }
    }
  }
}

(venv) ╭─root@wazuh5x-dev /workspaces/Wazuh_5x/wazuh ‹enhancement/35128-wazuh-engine-optimize-error-handling-geoip-locator●› 
╰─# engine-private geo get 127.0.0.1

{
  "as": {},
  "geo": {}
}

(venv) ╭─root@wazuh5x-dev /workspaces/Wazuh_5x/wazuh ‹enhancement/35128-wazuh-engine-optimize-error-handling-geoip-locator●› 
╰─# engine-private geo get ""

Error getting GeoIP database information: IP cannot be empty


(venv) ╭─root@wazuh5x-dev /workspaces/Wazuh_5x/wazuh ‹enhancement/35128-wazuh-engine-optimize-error-handling-geoip-locator●› 
╰─# engine-private geo get invalid_ip                                                                                                                 1 ↵

{
  "as": {},
  "geo": {}
}


```
