### PR TITLE
Let FIM add realtime directories if the limit is no longer reached

### LINKED ISSUE #8487: Windows realtime prevents adding directories after limit has been reached
|Wazuh version|Component|Install type|Platform|
|---|---|---|---|
| 3.12.0+ | Wazuh FIM | Agent | Windows |

Whenever a directory is added to be monitored in realtime in Windows, a counter variable gets incremented in order to check that no more than `max_fd_win_rt` directories are being monitored at the same time. However, this counter never gets decreased, meaning that deleting and creating the monitored directory could eventually put the counter over the top and no monitored directory will be added to realtime mode. The same would happen if `max_fd_win_rt` directories were to be added.

It's important to note that the counter only gets incremented when a directory configured in a `<directories>` stanza get deleted and readded, directories nested within do not increase the counter.

### Proposed solution

After a directory monitored in realtime on Windows systems is deleted, the counter should be decremented in order for the agent to know that a new directory could occupy its place.

### Extra info

This is the log entry that is written when the limit is reached:
```log
2021/04/30 14:15:10 wazuh-agent: ERROR: (6616): Unable to add directory to real time monitoring: 'c:\tmp\syscheck_test\directories' - Maximum size permitted.
```

Here is where the counter gets incremented:
https://github.com/wazuh/wazuh/blob/5f5c4fa1a4b1b3f6398d44850c74a65144a285b1/src/syscheckd/run_realtime.c#L570

And I believe here are the places I believe should be safe to decrement it:
https://github.com/wazuh/wazuh/blob/5f5c4fa1a4b1b3f6398d44850c74a65144a285b1/src/syscheckd/run_realtime.c#L393
https://github.com/wazuh/wazuh/blob/5f5c4fa1a4b1b3f6398d44850c74a65144a285b1/src/syscheckd/run_realtime.c#L608

### PR DESCRIPTION
**Pull request by antoniomanuelfr**
|Related issue|
|---|
|#8487|

## Description
Hi team! 
As described in issue #8487, if FIM has reached the limit set in `max_fd_win_rt`, it won't add any directory when this limit is no longer reached. This PR aims to fix this.

Closes #8487 

## Tests

- Compilation without warnings in every supported platform
  - [X] Windows
- [X] Source installation
- [X] Source upgrade

- Memory tests for Windows
  - [x] Scan-build report
  - [ ] Coverity

### CODE REVIEW

**Comment by antoniomanuelfr** [comment]
These are the results of the ITs. No failures.
[agent_centos_html_report_Test_integration_B4254_20210524155401.zip](https://github.com/wazuh/wazuh/files/6537458/agent_centos_html_report_Test_integration_B4254_20210524155401.zip)
[agent_ubuntu_html_report_Test_integration_B4254_20210524155401.zip](https://github.com/wazuh/wazuh/files/6537459/agent_ubuntu_html_report_Test_integration_B4254_20210524155401.zip)
[agent_windows_html_report_Test_integration_B4254_20210524155401.zip](https://github.com/wazuh/wazuh/files/6537460/agent_windows_html_report_Test_integration_B4254_20210524155401.zip)

**Review by Molter73 — CHANGES_REQUESTED** [review]
We should stop using `syscheck.realtime->fd` as a counter in Windows.

Linux properly uses it as a file descriptor, in Windows we should directly call `OSHash_Get_Elem_ex(syscheck.realtime->dirtb)` whenever we need to know the amount of entries currently being monitored in realtime.

File: src/syscheckd/run_check.c [hunk 1]
```diff
@@ -351,42 +351,24 @@ void start_daemon()
...
-
             if (syscheck.realtime != NULL) {
-                if (syscheck.realtime->queue_overflow) {
-                    realtime_sanitize_watch_map();
-                    syscheck.realtime->queue_overflow = false;
-                }
-                mdebug2(FIM_NUM_WATCHES, syscheck.realtime->dirtb->elements);
+                mdebug2(FIM_NUM_WATCHES, OSHash_Get_Elem_ex(syscheck.realtime->dirtb));
             }
         }
```
Comment (Molter73) [inline src/syscheckd/run_check.c:373]: Could we move this whole block outside of the `while` loop and get rid of `_base_line`?

File: src/unit_tests/syscheckd/test_run_check.c [hunk 2]
```diff
@@ -219,6 +225,42 @@ static int teardown_max_fps(void **state) {
...
+typedef struct _win32rtfim {
+    HANDLE h;
+    OVERLAPPED overlap;
+
+    char *dir;
+    TCHAR buffer[65536];
+    unsigned int watch_status;
+} win32rtfim;
+
+extern void free_win32rtfim_data(win32rtfim *data);
```
Comment (Molter73) [inline src/unit_tests/syscheckd/test_run_check.c:239]: Can we move this declaration to the top of the file where there are other declarations?

File: src/unit_tests/syscheckd/test_run_check.c [hunk 3]
```diff
@@ -219,6 +225,42 @@ static int teardown_max_fps(void **state) {
...
+
+static int setup_hash(void **state) {
+    directory_t *dir_it;
+    win32rtfim *rtlocald;
+    rtlocald = calloc(1, sizeof(win32rtfim));
+    foreach_array(dir_it, syscheck.directories) {
+        if (dir_it->options & REALTIME_ACTIVE) {
+            OSHash_Add_ex(syscheck.realtime->dirtb, strdup(dir_it->path), rtlocald);
```
Comment (Molter73) [inline src/unit_tests/syscheckd/test_run_check.c:247]: The key is hashed and therefore is not needed to be duplicated (this will actually be a leak in the test).
```suggestion
            OSHash_Add_ex(syscheck.realtime->dirtb, dir_it->path, rtlocald);
```

**Review by Molter73 — CHANGES_REQUESTED** [review]
The PR is looking good. Just some minor changes to remove some unnecessary local variables and some order in the UTs.

**Review by Molter73 — CHANGES_REQUESTED** [review]
Some more minor changes

**Review by Molter73 — APPROVED** [review]
LGTM!

**Review by Molter73 — CHANGES_REQUESTED** [review]

File: src/syscheckd/run_check.c [hunk 4]
```diff
@@ -350,28 +350,44 @@ void start_daemon()
...
+        dir_it = node_it->data;
+        if (dir_it->options & REALTIME_ACTIVE) {
+            realtime_adddir(dir_it->path, dir_it);
+        }
+    }
+    w_rwlock_unlock(&syscheck.directories_lock);
+
+    if (syscheck.realtime != NULL) {
+        mdebug2(FIM_NUM_WATCHES, get_realtime_watches());
+    }
```
[the remark this answers is not in the document]
Comment (Molter73) [reply src/syscheckd/run_check.c]: Solved in latest commit

File: src/syscheckd/run_realtime.c [hunk 5]
```diff
@@ -570,90 +572,72 @@ int realtime_adddir(const char *dir, directory_t *configuration) {
...
-            free_win32rtfim_data(rtlocald);
-            w_mutex_unlock(&syscheck.fim_realtime_mutex);
-            return 0;
-        }
+    /* Maximum limit for realtime on Windows */
+    if (get_realtime_watches() >= syscheck.max_fd_win_rt) {
+        merror(FIM_ERROR_REALTIME_MAXNUM_WATCHES, dir);
+        return 0;
+    }
+    w_mutex_lock(&syscheck.fim_realtime_mutex);
```
[the remark this answers is not in the document]
Comment (Molter73) [reply src/syscheckd/run_realtime.c]: Solved in latest commit

**Review by Molter73 — APPROVED** [review]
LGTM!
