### PR TITLE
7526 remove old records in agent update

### LINKED ISSUE #7526: Delete old rows in agent update.
## Description
This issue aims to guarantee the conditions to be able to correctly set the scan_id value.

**Issue:**
Entries in tables are duplicated, because of old scan_ids. (only in tables with scan id part of the key).

**Solution**
In wazuhdb instance, everything that does not have "checksum" field populated is cleaned (it would be with the algorithm less than 4.2)

**Solution effect:**
Cleaning old records

**Conditions to reproduce**
Manager 4.2
Agent upgrade any version to 4.2

Merge to branch dev-syscollector-tde

**_Test Scenarios_**

Test upgrade agent - manager off - OS Win, RH, DEB, MacOS
Test upgrade agent - manager on - OS Win, RH, DEB, MacOS

Test Vuln Detector.

## DoD
- [ ] Call clean rows on first call of deltas or rsync synchro.
- [ ] Modify unit tests.
- [ ] PR - CI PASS

### PR DESCRIPTION
**Pull request by konangc87**
|Related issue|
| #7526 |
| closes #7526 |

##Description
This PR aims to change the way old data in syscollector tables in the manager are removed when an agent is upgraded to the new syscollector imp.
Range checksum select will only retrieve entries with checksums different than empty string (default value after upgrading the manager) and "legacy" (default value for legacy agents connected to a manager with the new syscollector schema).
On the other hand, delete around will delete items not included in the range and items with checksum equal to empty string or "legacy" deleting old entries.

## DoD
- Manual tests
- [X] Legacy manager with legacy agents (win, ubuntu, macos sierra) upgrade to new syscollector imp manager.
- [X] Legacy Windows agent to new syscollector imp agent.
- [X] Legacy Ubuntu agent to new syscollector imp agent.
- [X] Legacy MacOs agent to new syscollector imp agent.

### CODE REVIEW

File: src/wazuh_db/wdb_syscollector.c [hunk 1]
```diff
@@ -1107,8 +1107,6 @@ int wdb_syscollector_processes_save2(wdb_t * wdb, const cJSON * attributes)
     const int tty = cJSON_GetObjectItem(attributes, "tty") ? cJSON_GetObjectItem(attributes, "tty")->valueint : 0;
     const int processor = cJSON_GetObjectItem(attributes, "processor") ? cJSON_GetObjectItem(attributes, "processor")->valueint : 0;
     const char * checksum = cJSON_GetStringValue(cJSON_GetObjectItem(attributes, "checksum"));
-    //this is needed to remove old entries in the db with a scan_id != 0: https://github.com/wazuh/wazuh/issues/7356
-    wdb_process_delete(wdb, scan_id);
```
Comment (tinachoB) [inline src/wazuh_db/wdb_syscollector.c:1111]: Shouldn't we need to remove the `wdb_process_delete` (declared in line 1051) since is not used anymore?

**Review by tinachoB — APPROVED** [review]
LGTM

File: src/wazuh_db/wdb_syscollector.c (hunk 1 above)
Comment (konangc87) [reply src/wazuh_db/wdb_syscollector.c:1111]: it's being used by legacy agents in wdb_parser.c

**Review by Dwordcito — APPROVED** [review]
