### PR TITLE
[7531] Unknown default value for all data providers

### LINKED ISSUE #7531: Change "unknown" value to empty value, in default values
## Description
This issue points to the perfect population of the data, when it is not assigned a value.

**Issue:**
No field with the value "unknown" should be populate.

**Solution**
Check string size in sysinfo data provider.

**Solution effect:**
There must be a " " as the default value. 
Additional tasl, replace hardcoded values ​​with constexpr from sharedDefs.h

**Conditions to reproduce**
Manager 4.2
Agent: 4.2

Merge to branch dev-syscollector-tde

## DoD
- [x] Modify data provider default values.
- [x] Modify unit tests.
- [x] PR - CI PASS

### PR DESCRIPTION
**Pull request by tinachoB**
|Related issue|
|---|
|Closes #7531 |

## **Description**
This issue points to the perfect population of the data, when it is not assigned a value.

## **Solution effect:**
There must be a " " as the default value. 
Additional tasl, replace hardcoded values ​​with constexpr from sharedDefs.h

## **Conditions to reproduce**
Manager 4.2
Agent: 4.2

Merge to branch dev-syscollector-tde

## **DoD**
- [X] Modify data provider default values.
- [X] Modify unit tests.
- [X] RTR in all affected modules

**data provider**
image

**utils**
image

**syscollector**
image

- [ ] PR - CI PASS

### CODE REVIEW

**Review by konangc87 — APPROVED** [review]

File: src/data_provider/src/network/networkLinuxWrapper.h [hunk 1]
```diff
@@ -190,10 +190,10 @@ class NetworkLinuxInterface final : public INetworkInterfaceWrapper
         }
         return retVal.get();
     }
- 
+
     static std::string getRedHatDHCPStatus(const std::vector<std::string>& fields)
     {
-        std::string retVal { UNKNOWN_VALUE };
+        std::string retVal { "enabled" };
```
Comment (Dwordcito) [inline src/data_provider/src/network/networkLinuxWrapper.h:196]: is correct this default value ?

**Review by Dwordcito — APPROVED** [review]

File: src/data_provider/src/network/networkLinuxWrapper.h (hunk 1 above)
Comment (tinachoB) [reply src/data_provider/src/network/networkLinuxWrapper.h:196]: Yes! This function is being called in the `dhcp()` one which initializes the retVal in "unknown"
