### PR TITLE
Content Manager - Improve robustness of CTI metadata fetching

### LINKED ISSUE #21931: Content Manager - Handling of undefined data from the API
|Component|
|---|
| [content_manager](https://github.com/wazuh/wazuh/tree/4.8.0/src/shared_modules/content_manager) |

## Description

During routine testing of the generated content, an error was encountered while processing the content hosted in the local CTI with the scanner [test tool](https://github.com/wazuh/wazuh/tree/4.8.0/src/wazuh_modules/vulnerability_scanner/testtool/scanner) . The error arises within the `content manager` module when certain data requested from the API lacks defined values.

Example:

```json
{
    "data":
    {
        "id": 1,
        "name": "cti-vulnerabilities",
        "context": "vulnerabilities",
        "operations": [ ],
        "inserted_at": "2024-02-15T16:02:33.411463Z",
        "updated_at": "2024-02-15T16:07:37.946481Z",
        "paths_filter": [ ],
        "last_offset": 3,
        "changes_url": "http://localhost:4041/api/v1/catalog/contexts/vulnerabilities/consumers/cti-vulnerabilities/changes",
        "last_snapshot_at": null,
        "last_snapshot_link": null,
        "last_snapshot_offset": null
    }
}
```

This issue aims to enhance the behavior of the "content manager" to gracefully handle scenarios where requested data from the API may be undefined.

## Steps to reproduce

Process the mocked content and process it with testtool.

## Expected behavior

Process content without errors

## Current behavior

```
wazuh-modulesd:content-updater:actionOrchestrator.hpp:61 ActionOrchestrator : Creating 'vulnerability_feed_manager' Content Updater orchestration
wazuh-modulesd:content-updater:executionContext.hpp:202 handleRequest : ExecutionContext - Starting process
wazuh-modulesd:content-updater:executionContext.hpp:179 createOutputFolder : Removing previous output folder 'queue/vd_updater/tmp'
wazuh-modulesd:content-updater:executionContext.hpp:184 createOutputFolder : Creating output folders at 'queue/vd_updater/tmp'
wazuh-modulesd:content-updater:factoryContentUpdater.hpp:44 create : FactoryContentUpdater - Starting process
wazuh-modulesd:content-updater:factoryDownloader.hpp:46 create : Creating 'cti-offset' downloader
wazuh-modulesd:content-updater:factoryDecompressor.hpp:73 create : Creating 'raw' decompressor
wazuh-modulesd:content-updater:factoryVersionUpdater.hpp:41 create : Creating 'false' version updater
wazuh-modulesd:content-updater:factoryCleaner.hpp:41 create : Content cleaner created
wazuh-modulesd:content-updater:actionOrchestrator.hpp:71 ActionOrchestrator : Content updater orchestration created
wazuh-modulesd:content-updater:action.hpp:128 runActionScheduled : Starting scheduled action for 'vulnerability_feed_manager'
wazuh-modulesd:content-updater:action.hpp:224 runAction : Action for 'vulnerability_feed_manager' started
wazuh-modulesd:content-updater:actionOrchestrator.hpp:158 runContentUpdate : Running 'vulnerability_feed_manager' content update
wazuh-modulesd:content-updater:actionOrchestrator.hpp:208 runFullContentDownload : Performing full-content download
wazuh-modulesd:content-updater:factoryContentUpdater.hpp:44 create : FactoryContentUpdater - Starting process
wazuh-modulesd:content-updater:factoryDownloader.hpp:46 create : Creating 'cti-snapshot' downloader
wazuh-modulesd:content-updater:factoryDecompressor.hpp:73 create : Creating 'zip' decompressor
wazuh-modulesd:content-updater:factoryVersionUpdater.hpp:41 create : Creating 'false' version updater
wazuh-modulesd:content-updater:factoryCleaner.hpp:41 create : Content cleaner created
wazuh-modulesd:content-updater:CtiDownloader.hpp:204 handleRequest : CtiSnapshotDownloader - Starting process
wazuh-modulesd:content-updater:action.hpp:232 runAction : Action for 'vulnerability_feed_manager' failed: Orchestration run failed: Error -1 from server: [json.exception.type_error.302] type must be string, but is null
wazuh-modulesd:content-updater:action.hpp:235 runAction : Action for 'vulnerability_feed_manager' finished

```

## DoD

- [x] Issue has been fixed.
- [x] Add new tests to verify that the described problem no longer occurs.
- [x] Add or Update Unit and Component.
- [ ] Compliance with:
  - [ ] [RTR](https://github.com/wazuh/wazuh/blob/dev-14153-vulndet-refactor/src/wazuh_modules/vulnerability_scanner/doc/rtr.md)
  - [ ] [GitHub Actions](https://github.com/wazuh/wazuh/actions/workflows/vulnerability-scanner-tests.yml)
- [ ] Add or Update any relevant documentation to reflect the changes made.

### PR DESCRIPTION
**Pull request by tsarquis88**
|Related issue|
|---|
| Closes #21931 |

# Description

This PR improves how the Content Manager parses the metadata from the CTI API (last offset and snapshot metadata). The idea is to make the module to be more robust in case of an error arrives.

# Results

## Manager execution with a local CTI API

The API returns an empty `last_snapshot_link` field.

Log with debug=2:
```bash
# cat /var/ossec/logs/ossec.log | grep updater
2024/02/22 15:32:36 wazuh-modulesd:content-updater[56889] actionOrchestrator.hpp:61 at ActionOrchestrator(): DEBUG: Creating 'vulnerability_feed_manager' Content Updater orchestration
2024/02/22 15:32:36 wazuh-modulesd:content-updater[56889] executionContext.hpp:202 at handleRequest(): DEBUG: ExecutionContext - Starting process
2024/02/22 15:32:36 wazuh-modulesd:content-updater[56889] executionContext.hpp:128 at createRocksDB(): DEBUG: Column 'current_offset' doesn't exist so it will be created
2024/02/22 15:32:36 wazuh-modulesd:content-updater[56889] executionContext.hpp:128 at createRocksDB(): DEBUG: Column 'downloaded_file_hash' doesn't exist so it will be created
2024/02/22 15:32:36 wazuh-modulesd:content-updater[56889] executionContext.hpp:184 at createOutputFolder(): DEBUG: Creating output folders at 'queue/vd_updater/tmp'
2024/02/22 15:32:36 wazuh-modulesd:content-updater[56889] factoryContentUpdater.hpp:44 at create(): DEBUG: FactoryContentUpdater - Starting process
2024/02/22 15:32:36 wazuh-modulesd:content-updater[56889] factoryDownloader.hpp:46 at create(): DEBUG: Creating 'cti-offset' downloader
2024/02/22 15:32:36 wazuh-modulesd:content-updater[56889] factoryDecompressor.hpp:73 at create(): DEBUG: Creating 'raw' decompressor
2024/02/22 15:32:36 wazuh-modulesd:content-updater[56889] factoryVersionUpdater.hpp:41 at create(): DEBUG: Creating 'false' version updater
2024/02/22 15:32:36 wazuh-modulesd:content-updater[56889] factoryCleaner.hpp:41 at create(): DEBUG: Content cleaner created
2024/02/22 15:32:36 wazuh-modulesd:content-updater[56889] actionOrchestrator.hpp:71 at ActionOrchestrator(): DEBUG: Content updater orchestration created
2024/02/22 15:32:36 wazuh-modulesd:content-updater[56889] action.hpp:128 at runActionScheduled(): INFO: Starting scheduled action for 'vulnerability_feed_manager'
2024/02/22 15:32:36 wazuh-modulesd:content-updater[56889] action.hpp:224 at runAction(): INFO: Action for 'vulnerability_feed_manager' started
2024/02/22 15:32:36 wazuh-modulesd:content-updater[56889] actionOrchestrator.hpp:158 at runContentUpdate(): DEBUG: Running 'vulnerability_feed_manager' content update
2024/02/22 15:32:36 wazuh-modulesd:content-updater[56889] actionOrchestrator.hpp:221 at runFullContentDownload(): DEBUG: Performing full-content download
2024/02/22 15:32:36 wazuh-modulesd:content-updater[56889] factoryContentUpdater.hpp:44 at create(): DEBUG: FactoryContentUpdater - Starting process
2024/02/22 15:32:36 wazuh-modulesd:content-updater[56889] factoryDownloader.hpp:46 at create(): DEBUG: Creating 'cti-snapshot' downloader
2024/02/22 15:32:36 wazuh-modulesd:content-updater[56889] factoryDecompressor.hpp:73 at create(): DEBUG: Creating 'zip' decompressor
2024/02/22 15:32:36 wazuh-modulesd:content-updater[56889] factoryVersionUpdater.hpp:41 at create(): DEBUG: Creating 'false' version updater
2024/02/22 15:32:36 wazuh-modulesd:content-updater[56889] factoryCleaner.hpp:41 at create(): DEBUG: Content cleaner created
2024/02/22 15:32:36 wazuh-modulesd:content-updater[56889] CtiDownloader.hpp:244 at handleRequest(): DEBUG: CtiSnapshotDownloader - Starting process
2024/02/22 15:32:36 wazuh-modulesd:content-updater[56889] CtiDownloader.hpp:94 at operator()(): DEBUG: CTI raw metadata: '{"data": {"last_offset": 1, "last_snapshot_link": "", "last_snapshot_offset": 0}}'
2024/02/22 15:32:36 wazuh-modulesd:content-updater[56889] CtiDownloader.hpp:132 at operator()(): WARNING: Null or empty CTI metadata value for key: last_snapshot_link
2024/02/22 15:32:36 wazuh-modulesd:content-updater[56889] actionOrchestrator.hpp:190 at runContentUpdate(): WARNING: Couldn't run full content download: Can't download snapshot due to missing CTI metadata
2024/02/22 15:32:36 wazuh-modulesd:content-updater[56889] CtiDownloader.hpp:244 at handleRequest(): DEBUG: CtiOffsetDownloader - Starting process
2024/02/22 15:32:36 wazuh-modulesd:content-updater[56889] CtiOffsetDownloader.hpp:42 at download(): DEBUG: Initial API offset: 0
2024/02/22 15:32:36 wazuh-modulesd:content-updater[56889] CtiDownloader.hpp:94 at operator()(): DEBUG: CTI raw metadata: '{"data": {"last_offset": 1, "last_snapshot_link": "", "last_snapshot_offset": 0}}'
2024/02/22 15:32:36 wazuh-modulesd:content-updater[56889] CtiDownloader.hpp:132 at operator()(): WARNING: Null or empty CTI metadata value for key: last_snapshot_link
2024/02/22 15:32:36 wazuh-modulesd:content-updater[56889] CtiOffsetDownloader.hpp:134 at downloadContent(): DEBUG: Downloading offsets from: 'http://localhost:4041//changes?from_offset=0&to_offset=1'
2024/02/22 15:32:36 wazuh-modulesd:content-updater[56889] skipStep.hpp:48 at handleRequest(): DEBUG: SkipStep - Starting process
2024/02/22 15:32:36 wazuh-modulesd:content-updater[56889] pubSubPublisher.hpp:61 at handleRequest(): DEBUG: PubSubPublisher - Starting process
2024/02/22 15:32:36 wazuh-modulesd:content-updater[56889] pubSubPublisher.hpp:42 at publish(): DEBUG: Data to be published: '{"offset":1,"paths":["queue/vd_updater/tmp/contents/1-api_file.json"],"stageStatus":[{"stage":"CtiOffsetDownloader","status":"ok"}],"type":"offsets"}'
2024/02/22 15:32:36 wazuh-modulesd:content-updater[56889] pubSubPublisher.hpp:45 at publish(): INFO: Data published
2024/02/22 15:32:36 wazuh-modulesd:content-updater[56889] skipStep.hpp:48 at handleRequest(): DEBUG: SkipStep - Starting process
2024/02/22 15:32:36 wazuh-modulesd:content-updater[56889] cleanUpContent.hpp:63 at handleRequest(): DEBUG: CleanUpContent - Starting process
2024/02/22 15:32:36 wazuh-modulesd:content-updater[56889] action.hpp:235 at runAction(): INFO: Action for 'vulnerability_feed_manager' finished
2024/02/22 15:32:36 wazuh-modulesd:vulnerability-scanner[56889] databaseFeedManager.hpp:126 at processMessage(): INFO: Processing file: queue/vd_updater/tmp/contents/1-api_file.json
2024/02/22 15:32:36 wazuh-modulesd:content-updater[56889] action.hpp:189 at runActionOnDemand(): INFO: Starting on-demand action for 'vulnerability_feed_manager'
2024/02/22 15:32:36 wazuh-modulesd:content-updater[56889] action.hpp:224 at runAction(): INFO: Action for 'vulnerability_feed_manager' started
2024/02/22 15:32:36 wazuh-modulesd:content-updater[56889] actionOrchestrator.hpp:138 at runOffsetUpdate(): DEBUG: Running 'vulnerability_feed_manager' offset update
2024/02/22 15:32:36 wazuh-modulesd:content-updater[56889] factoryOffsetUpdater.hpp:41 at create(): DEBUG: FactoryOffsetUpdater - Starting process
2024/02/22 15:32:36 wazuh-modulesd:content-updater[56889] updateCtiApiOffset.hpp:70 at handleRequest(): DEBUG: UpdateCtiApiOffset - Starting process
2024/02/22 15:32:36 wazuh-modulesd:content-updater[56889] updateCtiApiOffset.hpp:42 at update(): DEBUG: Updating offset with value: 1
2024/02/22 15:32:36 wazuh-modulesd:content-updater[56889] action.hpp:235 at runAction(): INFO: Action for 'vulnerability_feed_manager' finished
```

:green_circle: Snapshot download failed (with a user-friendly error message) and offset download performed correctly.

## Manager execution with default CTI API (remote)

Log with debug=2:
```bash
# cat /var/ossec/logs/ossec.log | grep updater
2024/02/22 15:13:01 wazuh-modulesd:content-updater[45390] actionOrchestrator.hpp:61 at ActionOrchestrator(): DEBUG: Creating 'vulnerability_feed_manager' Content Updater orchestration
2024/02/22 15:13:01 wazuh-modulesd:content-updater[45390] executionContext.hpp:202 at handleRequest(): DEBUG: ExecutionContext - Starting process
2024/02/22 15:13:01 wazuh-modulesd:content-updater[45390] executionContext.hpp:128 at createRocksDB(): DEBUG: Column 'current_offset' doesn't exist so it will be created
2024/02/22 15:13:01 wazuh-modulesd:content-updater[45390] executionContext.hpp:128 at createRocksDB(): DEBUG: Column 'downloaded_file_hash' doesn't exist so it will be created
2024/02/22 15:13:01 wazuh-modulesd:content-updater[45390] executionContext.hpp:184 at createOutputFolder(): DEBUG: Creating output folders at 'queue/vd_updater/tmp'
2024/02/22 15:13:01 wazuh-modulesd:content-updater[45390] factoryContentUpdater.hpp:44 at create(): DEBUG: FactoryContentUpdater - Starting process
2024/02/22 15:13:01 wazuh-modulesd:content-updater[45390] factoryDownloader.hpp:46 at create(): DEBUG: Creating 'cti-offset' downloader
2024/02/22 15:13:01 wazuh-modulesd:content-updater[45390] factoryDecompressor.hpp:73 at create(): DEBUG: Creating 'raw' decompressor
2024/02/22 15:13:01 wazuh-modulesd:content-updater[45390] factoryVersionUpdater.hpp:41 at create(): DEBUG: Creating 'false' version updater
2024/02/22 15:13:01 wazuh-modulesd:content-updater[45390] factoryCleaner.hpp:41 at create(): DEBUG: Content cleaner created
2024/02/22 15:13:01 wazuh-modulesd:content-updater[45390] actionOrchestrator.hpp:71 at ActionOrchestrator(): DEBUG: Content updater orchestration created
2024/02/22 15:13:01 wazuh-modulesd:content-updater[45390] action.hpp:128 at runActionScheduled(): INFO: Starting scheduled action for 'vulnerability_feed_manager'
2024/02/22 15:13:01 wazuh-modulesd:content-updater[45390] action.hpp:224 at runAction(): INFO: Action for 'vulnerability_feed_manager' started
2024/02/22 15:13:01 wazuh-modulesd:content-updater[45390] actionOrchestrator.hpp:158 at runContentUpdate(): DEBUG: Running 'vulnerability_feed_manager' content update
2024/02/22 15:13:01 wazuh-modulesd:content-updater[45390] actionOrchestrator.hpp:215 at runFullContentDownload(): DEBUG: Performing full-content download
2024/02/22 15:13:01 wazuh-modulesd:content-updater[45390] factoryContentUpdater.hpp:44 at create(): DEBUG: FactoryContentUpdater - Starting process
2024/02/22 15:13:01 wazuh-modulesd:content-updater[45390] factoryDownloader.hpp:46 at create(): DEBUG: Creating 'cti-snapshot' downloader
2024/02/22 15:13:01 wazuh-modulesd:content-updater[45390] factoryDecompressor.hpp:73 at create(): DEBUG: Creating 'zip' decompressor
2024/02/22 15:13:01 wazuh-modulesd:content-updater[45390] factoryVersionUpdater.hpp:41 at create(): DEBUG: Creating 'false' version updater
2024/02/22 15:13:01 wazuh-modulesd:content-updater[45390] factoryCleaner.hpp:41 at create(): DEBUG: Content cleaner created
2024/02/22 15:13:01 wazuh-modulesd:content-updater[45390] CtiDownloader.hpp:244 at handleRequest(): DEBUG: CtiSnapshotDownloader - Starting process
2024/02/22 15:13:03 wazuh-modulesd:content-updater[45390] CtiDownloader.hpp:94 at operator()(): DEBUG: CTI raw metadata: '{"data":{"id":4,"name":"vd_4.8.0","context":"vd_1.0.0","operations":null,"inserted_at":"2023-11-23T19:34:18.698495Z","updated_at":"2024-02-05T12:03:44.014816Z","paths_filter":null,"last_offset":239277,"changes_url":"cti.wazuh.com/api/v1/catalog/contexts/vd_1.0.0/consumers/vd_4.8.0/changes","last_snapshot_at":"2024-02-05T11:59:54.501799Z","last_snapshot_link":"https://s3.us-east-1.amazonaws.com/cti-snapshots-pro/store/contexts/vd_1.0.0/consumers/vd_4.8.0/239277_1707134394.zip","last_snapshot_offset":239277}}'
2024/02/22 15:13:03 wazuh-modulesd:content-updater[45390] CtiSnapshotDownloader.hpp:61 at download(): DEBUG: Downloading snapshot from 'https://s3.us-east-1.amazonaws.com/cti-snapshots-pro/store/contexts/vd_1.0.0/consumers/vd_4.8.0/239277_1707134394.zip'
2024/02/22 15:13:43 wazuh-modulesd:content-updater[45390] zipDecompressor.hpp:74 at handleRequest(): DEBUG: ZipDecompressor - Starting process
2024/02/22 15:13:43 wazuh-modulesd:content-updater[45390] zipDecompressor.hpp:49 at decompress(): DEBUG: Decompressing 'queue/vd_updater/tmp/downloads/239277_1707134394.zip' into 'queue/vd_updater/tmp/contents'
2024/02/22 15:13:58 wazuh-modulesd:content-updater[45390] pubSubPublisher.hpp:61 at handleRequest(): DEBUG: PubSubPublisher - Starting process
2024/02/22 15:13:58 wazuh-modulesd:content-updater[45390] pubSubPublisher.hpp:42 at publish(): DEBUG: Data to be published: '{"offset":239277,"paths":["queue/vd_updater/tmp/contents/vd_1.0.0_vd_4.8.0_239277_1707134394.json"],"stageStatus":[{"stage":"CtiSnapshotDownloader","status":"ok"},{"stage":"ZipDecompressor","status":"ok"}],"type":"raw"}'
2024/02/22 15:13:58 wazuh-modulesd:content-updater[45390] pubSubPublisher.hpp:45 at publish(): INFO: Data published
2024/02/22 15:13:58 wazuh-modulesd:content-updater[45390] skipStep.hpp:48 at handleRequest(): DEBUG: SkipStep - Starting process
2024/02/22 15:13:58 wazuh-modulesd:content-updater[45390] cleanUpContent.hpp:63 at handleRequest(): DEBUG: CleanUpContent - Starting process
2024/02/22 15:13:58 wazuh-modulesd:content-updater[45390] CtiDownloader.hpp:244 at handleRequest(): DEBUG: CtiOffsetDownloader - Starting process
2024/02/22 15:13:58 wazuh-modulesd:content-updater[45390] CtiOffsetDownloader.hpp:42 at download(): DEBUG: Initial API offset: 239277
2024/02/22 15:13:58 wazuh-modulesd:content-updater[45390] CtiDownloader.hpp:94 at operator()(): DEBUG: CTI raw metadata: '{"data":{"id":4,"name":"vd_4.8.0","context":"vd_1.0.0","operations":null,"inserted_at":"2023-11-23T19:34:18.698495Z","updated_at":"2024-02-05T12:03:44.014816Z","paths_filter":null,"last_offset":239277,"changes_url":"cti.wazuh.com/api/v1/catalog/contexts/vd_1.0.0/consumers/vd_4.8.0/changes","last_snapshot_at":"2024-02-05T11:59:54.501799Z","last_snapshot_link":"https://s3.us-east-1.amazonaws.com/cti-snapshots-pro/store/contexts/vd_1.0.0/consumers/vd_4.8.0/239277_1707134394.zip","last_snapshot_offset":239277}}'
2024/02/22 15:13:58 wazuh-modulesd:content-updater[45390] skipStep.hpp:48 at handleRequest(): DEBUG: SkipStep - Starting process
2024/02/22 15:13:58 wazuh-modulesd:content-updater[45390] pubSubPublisher.hpp:61 at handleRequest(): DEBUG: PubSubPublisher - Starting process
2024/02/22 15:13:58 wazuh-modulesd:content-updater[45390] pubSubPublisher.hpp:49 at publish(): DEBUG: No data to publish
2024/02/22 15:13:58 wazuh-modulesd:content-updater[45390] skipStep.hpp:48 at handleRequest(): DEBUG: SkipStep - Starting process
2024/02/22 15:13:58 wazuh-modulesd:content-updater[45390] cleanUpContent.hpp:63 at handleRequest(): DEBUG: CleanUpContent - Starting process
2024/02/22 15:13:58 wazuh-modulesd:content-updater[45390] action.hpp:235 at runAction(): INFO: Action for 'vulnerability_feed_manager' finished
2024/02/22 15:15:18 wazuh-modulesd:vulnerability-scanner[45390] databaseFeedManager.hpp:189 at processMessage(): INFO: Processing file: queue/vd_updater/tmp/contents/vd_1.0.0_vd_4.8.0_239277_1707134394.json
```

:green_circle: Manager working without errors, as expected

### CODE REVIEW

**Comment by tsarquis88** [comment]
The checks failing for macOS Ventura were fixed on https://github.com/wazuh/wazuh/issues/21830 for 4.8.1

File: src/shared_modules/content_manager/src/components/CtiDownloader.hpp [hunk 1]
```diff
@@ -85,22 +85,50 @@ class CtiDownloader : public AbstractHandler<std::shared_ptr<UpdaterContext>>
...
+        // Validate metadata.
+        for (const std::string& key : {"last_offset", "last_snapshot_link", "last_snapshot_offset"})
+        {
+            if (!rawMetadata.contains(key))
+            {
+                throw std::runtime_error {"Missing CTI metadata key: " + key};
+            }
+
+            const auto& data {rawMetadata.at(key)};
+            if (data.is_null() || (data.is_string() && data.empty()))
```
Comment (jftuduri) [inline src/shared_modules/content_manager/src/components/CtiDownloader.hpp:121]: This should be something like:
```suggestion
            if (data.is_null() || (data.is_string() && data.get_ref<const std::string&>().empty()))
```
`data.empty()`  is always `false` when `data` is a string, even if the string is empty. See [here](https://json.nlohmann.me/api/basic_json/empty/)

**Review by jftuduri — COMMENTED** [review]
Partial review. Just code review, pending functional review

File: src/shared_modules/content_manager/src/components/CtiDownloader.hpp [hunk 2]
```diff
@@ -85,22 +85,50 @@ class CtiDownloader : public AbstractHandler<std::shared_ptr<UpdaterContext>>
...
+                                  if (!nlohmann::json::accept(response))
+                                  {
+                                      throw std::runtime_error {"Invalid CTI metadata format"};
+                                  }
 
-                                  parameters.lastOffset = responseData.at("last_offset").get<int>();
-                                  parameters.lastSnapshotLink =
-                                      responseData.at("last_snapshot_link").get<std::string>();
-                                  parameters.lastSnapshotOffset = responseData.at("last_snapshot_offset").get<int>();
+                                  rawMetadata = nlohmann::json::parse(response).at("data");
```
Comment (matias-braida) [inline src/shared_modules/content_manager/src/components/CtiDownloader.hpp:100]: Maybe we could check that the response contains the "data" field and if not, throw a std::runtime_error {"Invalid CTI metadata format"} exception too.

Comment (matias-braida) [inline src/shared_modules/content_manager/src/components/CtiDownloader.hpp:100]: Maybe we could check that the response contains the "data" field and if not, throw a std::runtime_error {"Invalid CTI metadata format"} exception too.

File: src/shared_modules/content_manager/tests/unit/CtiDownloader_test.cpp
Comment (matias-braida) [inline src/shared_modules/content_manager/tests/unit/CtiDownloader_test.cpp:1]: A UT with the "data" field missing could be added.

**Review by matias-braida — COMMENTED** [review]
GJ

File: src/shared_modules/content_manager/src/components/CtiDownloader.hpp (hunk 1 above)
Comment (tsarquis88) [reply src/shared_modules/content_manager/src/components/CtiDownloader.hpp]: Good catch! I forgot to add a UT for this scenario...
Fixed and UT added.

**Review by matias-braida — DISMISSED** [review]
LGTM

File: src/shared_modules/content_manager/src/components/CtiDownloader.hpp [hunk 3]
```diff
@@ -85,22 +85,56 @@ class CtiDownloader : public AbstractHandler<std::shared_ptr<UpdaterContext>>
...
+        {
+            if (!rawMetadata.contains(key))
+            {
+                throw std::runtime_error {"Missing CTI metadata key: " + key};
+            }
+
+            const auto& data {rawMetadata.at(key)};
+            if (data.is_null() || (data.is_string() && data.get_ref<const std::string&>().empty()))
+            {
+                throw std::runtime_error {"Null or empty CTI metadata value for key: " + key};
```
Comment (Damian-Mangold) [inline src/shared_modules/content_manager/src/components/CtiDownloader.hpp:129]: This exception stops the execution of the orchestration and does not allow the offsets download stage to be executed. It may happen that a consumer only publishes offsets and not snapshot, so we must be able to process both contents separately.

Please make the necessary changes to allow offsets processing even if there are no snapshots created.

**Review by Damian-Mangold — CHANGES_REQUESTED** [review]

File: src/shared_modules/content_manager/src/components/CtiDownloader.hpp (hunk 3 above)
Comment (tsarquis88) [reply src/shared_modules/content_manager/src/components/CtiDownloader.hpp:129]: Good. I'll need one more day for implementing this.

**Review by matias-braida — DISMISSED** [review]

File: src/shared_modules/content_manager/tests/unit/CtiDownloader_test.cpp [hunk 4]
```diff
@@ -250,7 +224,205 @@ TEST_F(CtiDownloaderTest, BaseParametersDownloadInterrupted)
...
+    auto mockMetadata = R"(
+        {
+            "data":
+            {
+                "ignored_key": true,
+                "last_offset": 100,
+                "last_snapshot_link": "some_link"
+            }
+        }
+    )"_json.dump();
```
Comment (jftuduri) [inline src/shared_modules/content_manager/tests/unit/CtiDownloader_test.cpp:269]: This could be directly a string:
```suggestion
    std::string mockMetadata = R"(
        {
            "data":
            {
                "ignored_key": true,
                "last_offset": 100,
                "last_snapshot_link": "some_link"
            }
        }
    )";
```
Also on the other new tests.
(I used std::string instead of auto to keep it 'movable')

File: src/shared_modules/content_manager/src/components/CtiDownloader.hpp (hunk 3 above)
Comment (tsarquis88) [reply src/shared_modules/content_manager/src/components/CtiDownloader.hpp]: This is done!

File: src/shared_modules/content_manager/src/components/CtiDownloader.hpp [hunk 5]
```diff
@@ -85,26 +86,65 @@ class CtiDownloader : public AbstractHandler<std::shared_ptr<UpdaterContext>>
...
+
+        CtiBaseParameters parameters;
+        parameters.lastOffset =
+            isKeyValueValid("last_offset") ? std::optional(rawMetadata.at("last_offset").get<int>()) : std::nullopt;
+        parameters.lastSnapshotLink = isKeyValueValid("last_snapshot_link")
+                                          ? std::optional(rawMetadata.at("last_snapshot_link").get<std::string>())
+                                          : std::nullopt;
+        parameters.lastSnapshotOffset = isKeyValueValid("last_snapshot_offset")
+                                            ? std::optional(rawMetadata.at("last_snapshot_offset").get<int>())
+                                            : std::nullopt;
```
[the remark this answers is not in the document]
Comment (tsarquis88) [reply src/shared_modules/content_manager/src/components/CtiDownloader.hpp]: ... and done!

**Review by matias-braida — APPROVED** [review]

**Review by Damian-Mangold — APPROVED** [review]
## no offsets - no snapshot

```
damangold@damangold:~/Wazuh/dev/wazuh/src$ LD_PRELOAD=/lib/x86_64-linux-gnu/libasan.so.6 ./build/wazuh_modules/vulnerability_scanner/testtool/scanner/vd_scanner_testtool -c wazuh_modules/vulnerability_scanner/testtool/scanner/config.json -d
wazuh-modulesd:content-updater:actionOrchestrator.hpp:61 ActionOrchestrator : Creating 'vulnerability_feed_manager' Content Updater orchestration
wazuh-modulesd:content-updater:executionContext.hpp:202 handleRequest : ExecutionContext - Starting process
wazuh-modulesd:content-updater:executionContext.hpp:179 createOutputFolder : Removing previous output folder 'queue/vd_updater/tmp'
wazuh-modulesd:content-updater:executionContext.hpp:184 createOutputFolder : Creating output folders at 'queue/vd_updater/tmp'
wazuh-modulesd:content-updater:factoryContentUpdater.hpp:44 create : FactoryContentUpdater - Starting process
wazuh-modulesd:content-updater:factoryDownloader.hpp:46 create : Creating 'cti-offset' downloader
wazuh-modulesd:content-updater:factoryDecompressor.hpp:73 create : Creating 'raw' decompressor
wazuh-modulesd:content-updater:factoryVersionUpdater.hpp:41 create : Creating 'false' version updater
wazuh-modulesd:content-updater:factoryCleaner.hpp:41 create : Content cleaner created
wazuh-modulesd:content-updater:actionOrchestrator.hpp:71 ActionOrchestrator : Content updater orchestration created
wazuh-modulesd:content-updater:action.hpp:128 runActionScheduled : Starting scheduled action for 'vulnerability_feed_manager'
wazuh-modulesd:content-updater:action.hpp:224 runAction : Action for 'vulnerability_feed_manager' started
wazuh-modulesd:content-updater:actionOrchestrator.hpp:158 runContentUpdate : Running 'vulnerability_feed_manager' content update
wazuh-modulesd:content-updater:actionOrchestrator.hpp:221 runFullContentDownload : Performing full-content download
wazuh-modulesd:content-updater:factoryContentUpdater.hpp:44 create : FactoryContentUpdater - Starting process
wazuh-modulesd:content-updater:factoryDownloader.hpp:46 create : Creating 'cti-snapshot' downloader
wazuh-modulesd:content-updater:factoryDecompressor.hpp:73 create : Creating 'zip' decompressor
wazuh-modulesd:content-updater:factoryVersionUpdater.hpp:41 create : Creating 'false' version updater
wazuh-modulesd:content-updater:factoryCleaner.hpp:41 create : Content cleaner created
wazuh-modulesd:content-updater:CtiDownloader.hpp:244 handleRequest : CtiSnapshotDownloader - Starting process
wazuh-modulesd:content-updater:CtiDownloader.hpp:94 operator() : CTI raw metadata: '{"data":{"id":3,"name":"test","context":"vulnerabilities","operations":null,"inserted_at":"2024-02-22T18:14:50.273677Z","updated_at":"2024-02-22T18:14:50.273677Z","changes_url":"http://localhost:4041/api/v1/catalog/contexts/vulnerabilities/consumers/test/changes","last_offset":0,"last_snapshot_at":null,"last_snapshot_link":null,"last_snapshot_offset":null,"paths_filter":null}}'
wazuh-modulesd:content-updater:CtiDownloader.hpp:132 operator() : Null or empty CTI metadata value for key: last_snapshot_link
wazuh-modulesd:content-updater:CtiDownloader.hpp:132 operator() : Null or empty CTI metadata value for key: last_snapshot_offset
wazuh-modulesd:content-updater:actionOrchestrator.hpp:190 runContentUpdate : Couldn't run full content download: Can't download snapshot due to missing CTI metadata
wazuh-modulesd:content-updater:CtiDownloader.hpp:244 handleRequest : CtiOffsetDownloader - Starting process
wazuh-modulesd:content-updater:CtiOffsetDownloader.hpp:42 download : Initial API offset: 0
wazuh-modulesd:content-updater:CtiDownloader.hpp:94 operator() : CTI raw metadata: '{"data":{"id":3,"name":"test","context":"vulnerabilities","operations":null,"inserted_at":"2024-02-22T18:14:50.273677Z","updated_at":"2024-02-22T18:14:50.273677Z","changes_url":"http://localhost:4041/api/v1/catalog/contexts/vulnerabilities/consumers/test/changes","last_offset":0,"last_snapshot_at":null,"last_snapshot_link":null,"last_snapshot_offset":null,"paths_filter":null}}'
wazuh-modulesd:content-updater:CtiDownloader.hpp:132 operator() : Null or empty CTI metadata value for key: last_snapshot_link
wazuh-modulesd:content-updater:CtiDownloader.hpp:132 operator() : Null or empty CTI metadata value for key: last_snapshot_offset
wazuh-modulesd:content-updater:skipStep.hpp:48 handleRequest : SkipStep - Starting process
wazuh-modulesd:content-updater:pubSubPublisher.hpp:61 handleRequest : PubSubPublisher - Starting process
wazuh-modulesd:content-updater:pubSubPublisher.hpp:49 publish : No data to publish
wazuh-modulesd:content-updater:skipStep.hpp:48 handleRequest : SkipStep - Starting process
wazuh-modulesd:content-updater:cleanUpContent.hpp:63 handleRequest : CleanUpContent - Starting process
wazuh-modulesd:content-updater:action.hpp:235 runAction : Action for 'vulnerability_feed_manager' finished
```



## yes offsets - no snapshot

```
damangold@damangold:~/Wazuh/dev/wazuh/src$ LD_PRELOAD=/lib/x86_64-linux-gnu/libasan.so.6 ./build/wazuh_modules/vulnerability_scanner/testtool/scanner/vd_scanner_testtool -c wazuh_modules/vulnerability_scanner/testtool/scanner/config.json -d
wazuh-modulesd:content-updater:actionOrchestrator.hpp:61 ActionOrchestrator : Creating 'vulnerability_feed_manager' Content Updater orchestration
wazuh-modulesd:content-updater:executionContext.hpp:202 handleRequest : ExecutionContext - Starting process
wazuh-modulesd:content-updater:executionContext.hpp:179 createOutputFolder : Removing previous output folder 'queue/vd_updater/tmp'
wazuh-modulesd:content-updater:executionContext.hpp:184 createOutputFolder : Creating output folders at 'queue/vd_updater/tmp'
wazuh-modulesd:content-updater:factoryContentUpdater.hpp:44 create : FactoryContentUpdater - Starting process
wazuh-modulesd:content-updater:factoryDownloader.hpp:46 create : Creating 'cti-offset' downloader
wazuh-modulesd:content-updater:factoryDecompressor.hpp:73 create : Creating 'raw' decompressor
wazuh-modulesd:content-updater:factoryVersionUpdater.hpp:41 create : Creating 'false' version updater
wazuh-modulesd:content-updater:factoryCleaner.hpp:41 create : Content cleaner created
wazuh-modulesd:content-updater:actionOrchestrator.hpp:71 ActionOrchestrator : Content updater orchestration created
wazuh-modulesd:content-updater:action.hpp:128 runActionScheduled : Starting scheduled action for 'vulnerability_feed_manager'
wazuh-modulesd:content-updater:action.hpp:224 runAction : Action for 'vulnerability_feed_manager' started
wazuh-modulesd:content-updater:actionOrchestrator.hpp:158 runContentUpdate : Running 'vulnerability_feed_manager' content update
wazuh-modulesd:content-updater:actionOrchestrator.hpp:221 runFullContentDownload : Performing full-content download
wazuh-modulesd:content-updater:factoryContentUpdater.hpp:44 create : FactoryContentUpdater - Starting process
wazuh-modulesd:content-updater:factoryDownloader.hpp:46 create : Creating 'cti-snapshot' downloader
wazuh-modulesd:content-updater:factoryDecompressor.hpp:73 create : Creating 'zip' decompressor
wazuh-modulesd:content-updater:factoryVersionUpdater.hpp:41 create : Creating 'false' version updater
wazuh-modulesd:content-updater:factoryCleaner.hpp:41 create : Content cleaner created
wazuh-modulesd:content-updater:CtiDownloader.hpp:244 handleRequest : CtiSnapshotDownloader - Starting process
wazuh-modulesd:content-updater:CtiDownloader.hpp:94 operator() : CTI raw metadata: '{"data":{"id":3,"name":"test","context":"vulnerabilities","operations":null,"inserted_at":"2024-02-22T18:14:50.273677Z","updated_at":"2024-02-22T19:05:38.746425Z","changes_url":"http://localhost:4041/api/v1/catalog/contexts/vulnerabilities/consumers/test/changes","last_offset":237707,"last_snapshot_at":null,"last_snapshot_link":null,"last_snapshot_offset":null,"paths_filter":null}}'
wazuh-modulesd:content-updater:CtiDownloader.hpp:132 operator() : Null or empty CTI metadata value for key: last_snapshot_link
wazuh-modulesd:content-updater:CtiDownloader.hpp:132 operator() : Null or empty CTI metadata value for key: last_snapshot_offset
wazuh-modulesd:content-updater:actionOrchestrator.hpp:190 runContentUpdate : Couldn't run full content download: Can't download snapshot due to missing CTI metadata
wazuh-modulesd:content-updater:CtiDownloader.hpp:244 handleRequest : CtiOffsetDownloader - Starting process
wazuh-modulesd:content-updater:CtiOffsetDownloader.hpp:42 download : Initial API offset: 0
wazuh-modulesd:content-updater:CtiDownloader.hpp:94 operator() : CTI raw metadata: '{"data":{"id":3,"name":"test","context":"vulnerabilities","operations":null,"inserted_at":"2024-02-22T18:14:50.273677Z","updated_at":"2024-02-22T19:05:38.746425Z","changes_url":"http://localhost:4041/api/v1/catalog/contexts/vulnerabilities/consumers/test/changes","last_offset":237707,"last_snapshot_at":null,"last_snapshot_link":null,"last_snapshot_offset":null,"paths_filter":null}}'
wazuh-modulesd:content-updater:CtiDownloader.hpp:132 operator() : Null or empty CTI metadata value for key: last_snapshot_link
wazuh-modulesd:content-updater:CtiDownloader.hpp:132 operator() : Null or empty CTI metadata value for key: last_snapshot_offset
wazuh-modulesd:content-updater:CtiOffsetDownloader.hpp:134 downloadContent : Downloading offsets from: 'http://localhost:4041/api/v1/catalog/contexts/vulnerabilities/consumers/test/changes?from_offset=0&to_offset=1000'
wazuh-modulesd:vulnerability-scanner:vulnerabilityScannerFacade.cpp:496 start : Vulnerability scanner module started
wazuh-modulesd:content-updater:CtiOffsetDownloader.hpp:134 downloadContent : Downloading offsets from: 'http://localhost:4041/api/v1/catalog/contexts/vulnerabilities/consumers/test/changes?from_offset=1000&to_offset=2000'
wazuh-modulesd:content-updater:CtiOffsetDownloader.hpp:134 downloadContent : Downloading offsets from: 'http://localhost:4041/api/v1/catalog/contexts/vulnerabilities/consumers/test/changes?from_offset=2000&to_offset=3000'
wazuh-modulesd:content-updater:CtiOffsetDownloader.hpp:134 downloadContent : Downloading offsets from: 'http://localhost:4041/api/v1/catalog/contexts/vulnerabilities/consumers/test/changes?from_offset=3000&to_offset=4000'
wazuh-modulesd:content-updater:CtiOffsetDownloader.hpp:134 downloadContent : Downloading offsets from: 'http://localhost:4041/api/v1/catalog/contexts/vulnerabilities/consumers/test/changes?from_offset=4000&to_offset=5000'
wazuh-modulesd:content-updater:CtiOffsetDownloader.hpp:134 downloadContent : Downloading offsets from: 'http://localhost:4041/api/v1/catalog/contexts/vulnerabilities/consumers/test/changes?from_offset=5000&to_offset=6000'
wazuh-modulesd:content-updater:CtiOffsetDownloader.hpp:134 downloadContent : Downloading offsets from: 'http://localhost:4041/api/v1/catalog/contexts/vulnerabilities/consumers/test/changes?from_offset=6000&to_offset=7000'
wazuh-modulesd:content-updater:CtiOffsetDownloader.hpp:134 downloadContent : Downloading offsets from: 'http://localhost:4041/api/v1/catalog/contexts/vulnerabilities/consumers/test/changes?from_offset=7000&to_offset=8000'
wazuh-modulesd:content-updater:CtiOffsetDownloader.hpp:134 downloadContent : Downloading offsets from: 'http://localhost:4041/api/v1/catalog/contexts/vulnerabilities/consumers/test/changes?from_offset=8000&to_offset=9000'
wazuh-modulesd:content-updater:CtiOffsetDownloader.hpp:134 downloadContent : Downloading offsets from: 'http://localhost:4041/api/v1/catalog/contexts/vulnerabilities/consumers/test/changes?from_offset=9000&to_offset=10000'
wazuh-modulesd:content-updater:CtiOffsetDownloader.hpp:134 downloadContent : Downloading offsets from: 'http://localhost:4041/api/v1/catalog/contexts/vulnerabilities/consumers/test/changes?from_offset=10000&to_offset=11000'
wazuh-modulesd:content-updater:CtiOffsetDownloader.hpp:134 downloadContent : Downloading offsets from: 'http://localhost:4041/api/v1/catalog/contexts/vulnerabilities/consumers/test/changes?from_offset=11000&to_offset=12000'
wazuh-modulesd:content-updater:CtiOffsetDownloader.hpp:134 downloadContent : Downloading offsets from: 'http://localhost:4041/api/v1/catalog/contexts/vulnerabilities/consumers/test/changes?from_offset=12000&to_offset=13000'
wazuh-modulesd:content-updater:CtiOffsetDownloader.hpp:134 downloadContent : Downloading offsets from: 'http://localhost:4041/api/v1/catalog/contexts/vulnerabilities/consumers/test/changes?from_offset=13000&to_offset=14000'
wazuh-modulesd:content-updater:CtiOffsetDownloader.hpp:134 downloadContent : Downloading offsets from: 'http://localhost:4041/api/v1/catalog/contexts/vulnerabilities/consumers/test/changes?from_offset=14000&to_offset=15000'
wazuh-modulesd:content-updater:CtiOffsetDownloader.hpp:134 downloadContent : Downloading offsets from: 'http://localhost:4041/api/v1/catalog/contexts/vulnerabilities/consumers/test/changes?from_offset=15000&to_offset=16000'
wazuh-modulesd:content-updater:CtiOffsetDownloader.hpp:134 downloadContent : Downloading offsets from: 'http://localhost:4041/api/v1/catalog/contexts/vulnerabilities/consumers/test/changes?from_offset=16000&to_offset=17000'
wazuh-modulesd:content-updater:CtiOffsetDownloader.hpp:134 downloadContent : Downloading offsets from: 'http://localhost:4041/api/v1/catalog/contexts/vulnerabilities/consumers/test/changes?from_offset=17000&to_offset=18000'
wazuh-modulesd:content-updater:CtiOffsetDownloader.hpp:134 downloadContent : Downloading offsets from: 'http://localhost:4041/api/v1/catalog/contexts/vulnerabilities/consumers/test/changes?from_offset=18000&to_offset=19000'
wazuh-modulesd:content-updater:CtiOffsetDownloader.hpp:134 downloadContent : Downloading offsets from: 'http://localhost:4041/api/v1/catalog/contexts/vulnerabilities/consumers/test/changes?from_offset=19000&to_offset=20000'
wazuh-modulesd:content-updater:CtiOffsetDownloader.hpp:134 downloadContent : Downloading offsets from: 'http://localhost:4041/api/v1/catalog/contexts/vulnerabilities/consumers/test/changes?from_offset=20000&to_offset=21000'
wazuh-modulesd:content-updater:CtiOffsetDownloader.hpp:134 downloadContent : Downloading offsets from: 'http://localhost:4041/api/v1/catalog/contexts/vulnerabilities/consumers/test/changes?from_offset=21000&to_offset=22000'
wazuh-modulesd:content-updater:CtiOffsetDownloader.hpp:134 downloadContent : Downloading offsets from: 'http://localhost:4041/api/v1/catalog/contexts/vulnerabilities/consumers/test/changes?from_offset=22000&to_offset=23000'
wazuh-modulesd:content-updater:CtiOffsetDownloader.hpp:134 downloadContent : Downloading offsets from: 'http://localhost:4041/api/v1/catalog/contexts/vulnerabilities/consumers/test/changes?from_offset=23000&to_offset=24000'
wazuh-modulesd:content-updater:CtiOffsetDownloader.hpp:134 downloadContent : Downloading offsets from: 'http://localhost:4041/api/v1/catalog/contexts/vulnerabilities/consumers/test/changes?from_offset=24000&to_offset=25000'
wazuh-modulesd:content-updater:CtiOffsetDownloader.hpp:134 downloadContent : Downloading offsets from: 'http://localhost:4041/api/v1/catalog/contexts/vulnerabilities/consumers/test/changes?from_offset=25000&to_offset=26000'
wazuh-modulesd:content-updater:CtiOffsetDownloader.hpp:134 downloadContent : Downloading offsets from: 'http://localhost:4041/api/v1/catalog/contexts/vulnerabilities/consumers/test/changes?from_offset=26000&to_offset=27000'
wazuh-modulesd:content-updater:CtiOffsetDownloader.hpp:134 downloadContent : Downloading offsets from: 'http://localhost:4041/api/v1/catalog/contexts/vulnerabilities/consumers/test/changes?from_offset=27000&to_offset=28000'
wazuh-modulesd:content-updater:CtiOffsetDownloader.hpp:134 downloadContent : Downloading offsets from: 'http://localhost:4041/api/v1/catalog/contexts/vulnerabilities/consumers/test/changes?from_offset=28000&to_offset=29000'
wazuh-modulesd:content-updater:CtiOffsetDownloader.hpp:134 downloadContent : Downloading offsets from: 'http://localhost:4041/api/v1/catalog/contexts/vulnerabilities/consumers/test/changes?from_offset=29000&to_offset=30000'
wazuh-modulesd:content-updater:CtiOffsetDownloader.hpp:134 downloadContent : Downloading offsets from: 'http://localhost:4041/api/v1/catalog/contexts/vulnerabilities/consumers/test/changes?from_offset=30000&to_offset=31000'
wazuh-modulesd:content-updater:CtiOffsetDownloader.hpp:134 downloadContent : Downloading offsets from: 'http://localhost:4041/api/v1/catalog/contexts/vulnerabilities/consumers/test/changes?from_offset=31000&to_offset=32000'
wazuh-modulesd:content-updater:CtiOffsetDownloader.hpp:134 downloadContent : Downloading offsets from: 'http://localhost:4041/api/v1/catalog/contexts/vulnerabilities/consumers/test/changes?from_offset=32000&to_offset=33000'
wazuh-modulesd:content-updater:CtiOffsetDownloader.hpp:134 downloadContent : Downloading offsets from: 'http://localhost:4041/api/v1/catalog/contexts/vulnerabilities/consumers/test/changes?from_offset=33000&to_offset=34000'
wazuh-modulesd:content-updater:CtiOffsetDownloader.hpp:134 downloadContent : Downloading offsets from: 'http://localhost:4041/api/v1/catalog/contexts/vulnerabilities/consumers/test/changes?from_offset=34000&to_offset=35000'
```

**Review by jftuduri — APPROVED** [review]
LGTM
