### PR TITLE
Check first scan termination before sync start

### LINKED ISSUE #35426: Syscollector: validate initial scan completion and force synchronization after first scan
## Problem

During the first installation of a Wazuh agent, Syscollector may perform the initial synchronization before the first inventory scan has fully completed, or without explicitly triggering a synchronization immediately after that first scan finishes.

This can cause incomplete or inconsistent inventory data to be synchronized during the agent bootstrap process, especially when some collectors are still populating their state for the first time. As a result, the initial synchronization after installation may send partial information, and the inventory may only become consistent after a later scan or synchronization cycle.

## Steps to Reproduce
1. Perform a fresh installation of a Wazuh agent with Syscollector enabled.
2. Start the agent for the first time.
3. Allow Syscollector to begin collecting inventory data.
4. Observe the synchronization behavior during the initial startup after installation.
5. Verify whether the first synchronized inventory reflects the full completed scan or only a partial initial state.

## Expected Behavior
On the first installation of the agent, Syscollector should validate that the initial inventory scan has fully completed before considering the first synchronization finished.

Once the first scan is completed, the agent should explicitly force a synchronization so that the initial inventory state sent to the manager/indexer is complete and consistent.

## Current Behavior
During the first agent installation, synchronization may occur without guaranteeing that the initial Syscollector scan has fully completed.

As a result, the first synchronized inventory may be incomplete or inconsistent, and the system may only converge to the expected state after later scans or synchronization attempts.

## Additional Information
- This issue only applies to the first installation/startup of the agent.
- It is focused on the timing between the initial Syscollector scan and the first synchronization.
- The problem is not limited to a specific inventory table, since it affects the consistency of the initial synchronized state generated after installation.

## Impact
An incomplete synchronization during the first installation may cause:
- Partial inventory visibility in the manager/indexer.
- Delayed consistency of Syscollector data after agent deployment.
- Confusing behavior during validation and testing, since the first synchronized state may not match the final local state.
- The need to wait for an additional scan/synchronization cycle before the inventory becomes fully usable.

## Proposal
- Detect when the agent is running its first installation/startup flow.
- Track the completion status of the initial Syscollector scan for that first installation only.
- Validate that the first inventory collection has finished before completing the initial synchronization flow.
- Force a synchronization immediately after the first successful scan completes.
- Add debug logs to clearly indicate:
  - when the initial Syscollector scan starts,
  - when it finishes,
  - whether synchronization is being deferred waiting for scan completion,
  - and when the forced post-scan synchronization is triggered during first installation.

### PR DESCRIPTION
**Pull request by anromerom**
## Description

Closes #35426

On a fresh agent start, Syscollector's sync thread used `get_version` as a proxy to detect when the initial scan had finished. This was unreliable because `get_version` returns non-zero the moment the first collector writes a single row, while the scan is still running. The sync thread would conclude the scan was done, attempt to sync, find `is_scanning = true`, back off, and sleep for a full `sync_interval` with no wake-up signal when the scan actually finished. This caused the first inventory synchronisation to be delayed by up to `sync_interval` after the scan completed.

## Proposed Changes

- Persist a `first_scan_completed` key to the local database at the end of `scan()` in `syscollectorImp.cpp`, marking the true scan boundary.
- Add a `get_first_scan_completed` query handler so the sync thread can poll for this key instead of relying on `get_version`.
- Replace the `get_version` poll in `wm_sys_get_startup_action()` with `get_first_scan_completed`, so the sync thread waits for the real scan boundary before proceeding.
- Set a `skip_scanning_check` flag on the first immediate sync cycle so the `is_scanning` guard is bypassed.

### Results and Evidence

**Before:**

```
2026/04/14 16:28:48 wazuh-modulesd:syscollector[70481] logging_helper.c:37 at taggedLogFunction(): DEBUG: Syscollector get_version returned: 0
2026/04/14 16:28:48 wazuh-modulesd:syscollector[70481] logging_helper.c:31 at taggedLogFunction(): INFO: Starting evaluation.
2026/04/14 16:28:49 wazuh-modulesd:syscollector[70481] logging_helper.c:37 at taggedLogFunction(): DEBUG: Syscollector get_version returned: 1
2026/04/14 16:28:49 wazuh-modulesd:syscollector[70481] wm_syscollector.c:394 at wm_sys_get_startup_action(): DEBUG: Initial Inventory scan data is ready. Triggering first synchronization without startup delay.
2026/04/14 16:28:49 wazuh-modulesd:syscollector[70481] wm_syscollector.c:980 at wm_sync_module(): DEBUG: Scan in progress, skipping sync cycle
2026/04/14 16:28:55 wazuh-modulesd:syscollector[70481] logging_helper.c:31 at taggedLogFunction(): INFO: Evaluation finished.
2026/04/14 16:29:56 wazuh-modulesd:syscollector[70481] logging_helper.c:37 at taggedLogFunction(): DEBUG: Syscollector module is paused or stopping, skipping synchronization
2026/04/14 16:31:02 wazuh-modulesd:syscollector[70481] logging_helper.c:37 at taggedLogFunction(): DEBUG: Syscollector module is paused or stopping, skipping synchronization
```

`get_version` flipped to 1 at 16:28:49 while the scan was still running. The sync thread hit `is_scanning`, backed off for 60 s, and the first successful synchronisation never appeared in the capture window. Minimum delay from scan completion (16:28:55): **≥ 66 seconds**.

---

**After:**

```
2026/04/15 12:23:10 wazuh-modulesd:syscollector[13453] wm_syscollector.c:380 at wm_sys_get_startup_action(): DEBUG: Inventory initial scan data is not ready yet. First synchronization will wait for scan data.
2026/04/15 12:23:10 wazuh-modulesd:syscollector[13453] logging_helper.c:37 at taggedLogFunction(): DEBUG: Received query: {"command":"get_first_scan_completed"}
2026/04/15 12:23:10 wazuh-modulesd:syscollector[13453] wm_syscollector.c:398 at wm_sys_get_startup_action(): DEBUG: Synchronization deferred: waiting for first inventory scan to complete.
2026/04/15 12:23:10 wazuh-modulesd:syscollector[13453] logging_helper.c:31 at taggedLogFunction(): INFO: Starting evaluation.
2026/04/15 12:23:11 wazuh-modulesd:syscollector[13453] logging_helper.c:37 at taggedLogFunction(): DEBUG: Received query: {"command":"get_first_scan_completed"}
2026/04/15 12:23:11 wazuh-modulesd:syscollector[13453] wm_syscollector.c:398 at wm_sys_get_startup_action(): DEBUG: Synchronization deferred: waiting for first inventory scan to complete.
[... polled every second for the 10 s the scan runs ...]
2026/04/15 12:23:20 wazuh-modulesd:syscollector[13453] logging_helper.c:31 at taggedLogFunction(): INFO: Evaluation finished.
2026/04/15 12:23:20 wazuh-modulesd:syscollector[13453] logging_helper.c:37 at taggedLogFunction(): DEBUG: First inventory scan completed — marker persisted.
2026/04/15 12:23:21 wazuh-modulesd:syscollector[13453] wm_syscollector.c:394 at wm_sys_get_startup_action(): DEBUG: First inventory scan completed. Triggering first synchronization without startup delay.
2026/04/15 12:23:21 wazuh-modulesd:syscollector[13453] logging_helper.c:31 at taggedLogFunction(): INFO: Starting inventory synchronization.
2026/04/15 12:23:21 wazuh-modulesd:syscollector[13453] logging_helper.c:37 at taggedLogFunction(): DEBUG: StartAck received. Session: 6393652549476418162
```

`get_first_scan_completed` returned not-ready on every poll while the scan ran (10 s). The moment `Evaluation finished.` was logged, the marker was persisted and the sync fired. Delay from scan completion (12:23:20) to sync start (12:23:21): **1 second**. The `"Scan in progress, skipping sync cycle"` line is absent.

Additionally, we can validate that the marker is created and is consistent with the pre-existing first sync marker by checking the local database (`./queue/syscollector/db/local.db`):

```command
sqlite> select * from table_metadata;
first_scan_completed|1776395348|1
first_sync_completed|1776395714|1
dbsync_browser_extensions|1776395735|1
dbsync_groups|1776395735|1
dbsync_hwinfo|1776395735|1
dbsync_network_address|1776395735|1
dbsync_network_iface|1776395735|1
dbsync_network_protocol|1776395735|1
dbsync_osinfo|1776395735|1
dbsync_packages|1776395735|1
dbsync_ports|1776395735|1
dbsync_processes|1776395735|1
dbsync_services|1776395735|1
dbsync_users|1776395735|1
```

---

### Artifacts Affected

- `wazuh-modulesd/syscollector` (all platforms)

### Configuration Changes

- None.

### Documentation Updates

- None.

### Tests Introduced

- Unit tests added in `syscollectorImp_test.cpp` covering:
  - `first_scan_completed` marker is persisted at the end of `scan()`.
  - `get_first_scan_completed` query returns false before the scan runs and true after.
  - Sync thread defers correctly when the marker is absent.
  - Sync thread fires immediately (without `is_scanning` back-off) once the marker is present.

## Review Checklist

- [x] Code changes reviewed
- [x] Relevant evidence provided
- [x] Tests cover the new functionality
- [ ] Configuration changes documented
- [ ] Developer documentation reflects the changes
- [x] Meets requirements and/or definition of done
- [x] No unresolved dependencies with other issues

### CODE REVIEW

File: src/wazuh_modules/syscollector/src/syscollectorImp.cpp [hunk 1]
```diff
@@ -1872,6 +1882,14 @@ void Syscollector::scan()
     // This ensures deletions are committed to disk immediately
     deleteFailedItemsFromDB(failedItems);
 
+    if (isFirstScan)
+    {
+        m_scanning = false;
+        m_pauseCv.notify_all();
```
Comment (nbertoldo) [inline src/wazuh_modules/syscollector/src/syscollectorImp.cpp]: The `ScanGuard` RAII object at line 1826 already manages `m_scanning` lifecycle. Setting `m_scanning = false` here causes temporal inconsistency: the flag is cleared while `scan()` is still executing. This creates a race condition window where the sync thread might check `syscollector_is_scanning_ptr()` and get false before the marker is fully persisted. The ScanGuard destructor will set `m_scanning = false` and call `m_pauseCv.notify_all()` anyway when the function truly completes.

```suggestion
```

**Comment by anromerom** [comment]
Validated again after removing the explicit `m_scanning = false` and relying only on `ScanGuard` to clear the flag.

The fix still avoids the original behavior:
- Syscollector takes the `get_first_scan_completed` startup path and triggers the first sync immediately.
- There is no `Scan in progress, skipping sync cycle` message and no full `sync.interval` backoff after scan completion.
- In this run, the first forced sync attempt failed for a different reason: `agent-info` metadata was not ready yet. Once metadata became available, Syscollector synchronization completed successfully.

Reference logs:

```text
T+0 UTC: 2026-04-17T20:48:30.203Z

2026/04/17 20:48:36 wazuh-modulesd:syscollector[218] logging_helper.c:37 at taggedLogFunction(): DEBUG: Received query: {"command":"get_first_sync_completed"}
2026/04/17 20:48:36 wazuh-modulesd:syscollector[218] logging_helper.c:37 at taggedLogFunction(): DEBUG: Executing command: get_first_sync_completed
2026/04/17 20:48:36 wazuh-modulesd:syscollector[218] wm_syscollector.c:380 at wm_sys_get_startup_action(): DEBUG: Inventory initial scan data is not ready yet. First synchronization will wait for scan data.
2026/04/17 20:48:36 wazuh-modulesd:syscollector[218] logging_helper.c:37 at taggedLogFunction(): DEBUG: Received query: {"command":"get_first_scan_completed"}
2026/04/17 20:48:36 wazuh-modulesd:syscollector[218] logging_helper.c:37 at taggedLogFunction(): DEBUG: Executing command: get_first_scan_completed
2026/04/17 20:48:36 wazuh-modulesd:syscollector[218] wm_syscollector.c:394 at wm_sys_get_startup_action(): DEBUG: First inventory scan completed. Triggering first synchronization without startup delay.
2026/04/17 20:48:36 wazuh-modulesd:syscollector[218] wm_syscollector.c:993 at wm_sync_module(): DEBUG: Triggering forced post-first-scan synchronization.
2026/04/17 20:48:36 wazuh-modulesd:syscollector[218] logging_helper.c:31 at taggedLogFunction(): INFO: Starting inventory synchronization.
2026/04/17 20:48:36 wazuh-modulesd:syscollector[218] logging_helper.c:34 at taggedLogFunction(): WARNING: Metadata not available from provider. Agent-info may not be initialized yet. Cannot proceed with synchronization.
2026/04/17 20:48:36 wazuh-modulesd:syscollector[218] logging_helper.c:34 at taggedLogFunction(): WARNING: Syscollector synchronization process failed.
2026/04/17 20:48:36 wazuh-modulesd:syscollector[218] logging_helper.c:31 at taggedLogFunction(): INFO: Starting evaluation.
2026/04/17 20:48:36 wazuh-modulesd:syscollector[218] logging_helper.c:31 at taggedLogFunction(): INFO: Evaluation finished.

2026/04/17 20:48:41 wazuh-modulesd:agent-info[218] wm_agent_info.c:190 at agent_info_log_callback(): DEBUG: Successfully updated metadata provider
2026/04/17 20:48:41 wazuh-modulesd:agent-info[218] wm_agent_info.c:190 at agent_info_log_callback(): DEBUG: Agent metadata populated successfully
2026/04/17 20:48:41 wazuh-modulesd:agent-info[218] wm_agent_info.c:190 at agent_info_log_callback(): DEBUG: Agent groups populated successfully: 1 groups

2026/04/17 20:49:35 wazuh-modulesd:syscollector[218] logging_helper.c:31 at taggedLogFunction(): INFO: Starting inventory synchronization.
2026/04/17 20:49:35 wazuh-modulesd:syscollector[218] logging_helper.c:37 at taggedLogFunction(): DEBUG: Metadata available. Proceed with synchronization.
2026/04/17 20:49:37 wazuh-modulesd:syscollector[218] logging_helper.c:40 at taggedLogFunction(): DEBUG: Synchronization completed successfully.
2026/04/17 20:49:57 wazuh-modulesd:syscollector[218] logging_helper.c:31 at taggedLogFunction(): INFO: Syscollector synchronization process finished successfully.
```

**Review by cborla — APPROVED** [review]
LGTM
  The changes are well-tested with comprehensive unit tests covering the marker persistence.

- [x] Code changes reviewed
- [x] Relevant evidence provided
- [x] Tests cover the new functionality
- [ ] Configuration changes documented
- [ ] Developer documentation reflects the changes
- [x] Meets requirements and/or definition of done
- [x] No unresolved dependencies with other issues
