### PR TITLE
Remove manager-side agent logic and references from agent modules

### LINKED ISSUE #34205: Analyze and remove agent ID `000` assumptions in Agent daemons
## Description

This issue tracks the analysis and removal of all **agent ID `000` assumptions** within **Agent-side daemons** after the Agent/Manager separation.

Historically, some Agent runtime logic implicitly relied on the existence of a local or special agent identity (`000`). With agent `000` removed and Agent–Manager coexistence introduced, Agent daemons must operate without any local-agent or Manager-specific shortcuts.

This issue focuses exclusively on **Agent runtime behavior**, not Manager modules.

---

## Scope (Agent-side)

- Agent startup logic
- Agent daemon initialization and lifecycle
- Internal routing or execution paths relying on `agent_id == "000"`
- Implicit assumptions about local execution context

---

## Out of Scope

- Manager-side modules or workflows
- `wazuh-modulesd` Manager logic
- Packaging, installers, or CI workflows

---

## Key requirements / decisions

- Agent daemons must not branch on or depend on `agent_id == "000"`.
- Agent runtime behavior must be consistent regardless of Manager location.
- No Agent daemon should assume a local or privileged execution context.

---

## Detailed work items

1) **Audit Agent daemons**
   - Identify all references or conditionals using `agent_id == "000"`.
   - Review startup and initialization flows.

2) **Remove special cases**
   - Replace `000`-based logic with generic Agent-safe behavior.
   - Ensure no implicit local-agent shortcuts remain.

3) **Internal routing**
   - Validate Agent internal routing does not depend on `000`.
   - Ensure execution flow is consistent in co-hosted and remote setups.

4) **Tests update**
   - Update Agent tests that assume `agent_id == "000"`.
   - Add coverage for Agent behavior without special identities.

---

## Coordination / Related work

- Related: Remove agent `000` from `wazuh-modulesd` (manager scope)  
  https://github.com/wazuh/wazuh/issues/34168
---

## Testing

- Agent daemons start and run without `agent_id == "000"`.
- No regressions in Agent startup or runtime behavior.
- Agent-specific unit and integration tests pass.

---

## Definition of Done (DoD)

- [ ] No Agent daemon contains logic branching on `agent_id == "000"`.
- [ ] Agent startup and runtime logic is free of local-agent assumptions.
- [ ] Agent tests updated and passing.

### PR DESCRIPTION
**Pull request by anromerom**
## Description

Closes #34205

After the analysis on agent-side daemons, all references to agent ID `"000"` were confirmed to be either manager-only or only documentary. This PR removes the remaining agent-side references including the runtime `is_agent` flag pattern in `agent_info` and cleaning up a stale documentation reference.

## Proposed Changes

- **`wm_agent_info.c`**: Replaced the runtime `is_agent` flag logic with compile-time `#ifndef CLIENT` guard to skip module configuration on manager builds. Wrapped the agentd handshake query block with `#ifdef CLIENT` to prevent compilation in manager context.
- **`wm_agent_info.h`**: Removed the `is_agent` field from `wm_agent_info_t`, as the compile-time guard makes it unnecessary.
- **`metadata_provider.h`**: Removed the `"000" for server` reference from the `agent_id` field documentation comment.

### Results and Evidence

- N/A

### Artifacts Affected

- `wazuh-modulesd` module.

### Configuration Changes

- N/A

### Documentation Updates

- N/A. None of the documentation files found in `docs/ref/modules/agent_info` mention manager-side agent behavior, as this is used for internal logic only. There is no mention to a `000` agent id neither.

### Tests Introduced
- N/A

## Review Checklist

- [ ] Code changes reviewed
- [ ] Relevant evidence provided
- [ ] Tests cover the new functionality
- [ ] Configuration changes documented
- [ ] Developer documentation reflects the changes
- [ ] Meets requirements and/or definition of done
- [ ] No unresolved dependencies with other issues

### CODE REVIEW

File: src/wazuh_modules/wm_agent_info.c [hunk 1]
```diff
@@ -466,17 +466,11 @@ int wm_agent_info_read(__attribute__((unused)) const OS_XML* xml, xml_node** nod
     module->tag = strdup(module->context->name);
     module->data = agent_info;
 
-#ifdef CLIENT
-    agent_info->is_agent = true;
-#else
-    agent_info->is_agent = false;
+#ifndef CLIENT
+    mdebug2("Agent-info module is not supported on manager. Ignoring configuration.");
+    return 0;
```
Comment (nbertoldo) [inline src/wazuh_modules/wm_agent_info.c]: I agree with Copilot's suggestion. But I think you can add a guard `#ifdef CLIENT` in the function call https://github.com/wazuh/wazuh/blob/aa0cac72dfc718ee74bd1935131e0ab563e9b212/src/config/config.c#L145-L151

**Comment by anromerom** [comment]
> Please check the template and confirm whether documentation requires any updates.

Hi @vikman90 ,

The PR description has been updated based on the template and the documentation was explored with no mention to manager-side agent logic or `000` id references.

**Review by rjcausarano — APPROVED** [review]
LGTM

- [x] Code changes reviewed
- [ ] Relevant evidence provided
- [ ] Tests cover the new functionality
- [x] Configuration changes documented
- [x] Developer documentation reflects the changes
- [ ] Meets requirements and/or definition of done
- [x] No unresolved dependencies with other issues
