### PR TITLE
Fix agent reload race condition on centralized config update

### LINKED ISSUE #35169: Agent's automatic reload fails after receiving centralized configuration
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 5.0| wazuh-agentd / wazuh-modulesd (wm_agent_control)|Agent | Any | Ubuntu |

# Description

During https://github.com/wazuh/wazuh/issues/35136, it was found that agent's automatic reload fails after receiving centralized configuration

```console

2026/03/27 19:16:52 wazuh-modulesd[24] debug_op.c:116 at _log_function(): DEBUG: Logging module auto-initialized
2026/03/27 19:16:52 wazuh-modulesd[24] main.c:85 at main(): DEBUG: Wazuh home directory: /var/ossec
2026/03/27 19:16:52 wazuh-execd: INFO: Started (pid: 35).
2026/03/27 19:16:52 wazuh-agentd: INFO: Started (pid: 43).
2026/03/27 19:16:52 wazuh-agentd: INFO: Using AES as encryption method.
2026/03/27 19:16:52 wazuh-agentd: INFO: Trying to connect to server ([haproxy-lb]:1514/tcp).
2026/03/27 19:16:53 wazuh-modulesd[69] debug_op.c:116 at _log_function(): DEBUG: Logging module auto-initialized
2026/03/27 19:16:53 wazuh-modulesd[69] main.c:85 at main(): DEBUG: Wazuh home directory: /var/ossec
2026/03/27 19:16:53 wazuh-modulesd[69] main.c:106 at main(): INFO: Started (pid: 71).
2026/03/27 19:16:53 wazuh-modulesd[69] startup_gate_op.c:140 at startup_gate_wait_for_ready(): DEBUG: Startup hash gate is blocking 'wazuh-modulesd' (waiting for agentd startup gate status).
2026/03/27 19:17:05 wazuh-agentd: INFO: Closing connection to server ([haproxy-lb]:1514/tcp).
2026/03/27 19:17:05 wazuh-agentd: INFO: Trying to connect to server ([haproxy-lb]:1514/tcp).
2026/03/27 19:17:18 wazuh-agentd: INFO: Closing connection to server ([haproxy-lb]:1514/tcp).
2026/03/27 19:17:18 wazuh-agentd: INFO: Trying to connect to server ([haproxy-lb]:1514/tcp).
2026/03/27 19:17:18 wazuh-agentd: INFO: Module limits received from manager
2026/03/27 19:17:18 wazuh-agentd: INFO: Connected to cluster: wazuh
2026/03/27 19:17:18 wazuh-agentd: INFO: Connected to node: master-node
2026/03/27 19:17:18 wazuh-agentd: INFO: Agent groups: default,group2
2026/03/27 19:17:18 wazuh-agentd: INFO: (4102): Connected to the server ([haproxy-lb]:1514/tcp).
2026/03/27 19:17:18 wazuh-agentd: INFO: Agent is reloading due to shared configuration changes.
2026/03/27 19:17:18 wazuh-agentd: ERROR: At reloadAgent(): Could not connect to socket 'queue/sockets/control': No such file or directory (2).
```

Full log: [test_black_agent-agent2-ossec.log](https://github.com/user-attachments/files/26313454/test_black_agent-agent2-ossec.log)

Commit ref:  e81f9b3853f6a347b73c5f06b1b60b7ae9cb3bd4
OS (container)
```
root@wazuh-agent3:/# cat /etc/os-release 
PRETTY_NAME="Ubuntu 24.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.4 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
```

Probable related issue: https://github.com/wazuh/wazuh/pull/35023
Probable cause: agentd gets the shared configuration before even wazuh-modulesd control module starts

```
2026/03/27 19:17:18 wazuh-modulesd[69] main.c:120 at main(): DEBUG: Created new thread for the 'control' module.

```

### PR DESCRIPTION
**Pull request by lchico**
## Description

When a Wazuh agent receives centralized configuration from the manager, `agentd` calls `reloadAgent()` before `wazuh-modulesd`'s control thread has finished binding to `queue/sockets/control`, causing the reload to fail with `ENOENT`. This race occurs both at first startup and after every subsequent reload cycle, since both daemons restart together. Resolves #35169.

## Proposed Changes

- **`src/client-agent/src/reload_agent.c`**: Replaced the single-attempt socket connect in `reloadAgent()` with a retry loop (up to 10 attempts, 1 second apart) that retries on `ENOENT` and `ECONNREFUSED`, allowing time for `wazuh-modulesd`'s control thread to initialize and bind the socket. Other errno values fail immediately.

### Results and Evidence

<details><summary>After fix — Ubuntu 24.04 (DEB, systemd reload)</summary>

```bash
2026/03/30 13:05:49 wazuh-agentd: INFO: Agent is reloading due to shared configuration changes.
2026/03/30 13:05:49 wazuh-modulesd:control: INFO: Executing 'reload' on wazuh-agent using systemctl
2026/03/30 13:05:49 wazuh-logcollector: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2026/03/30 13:05:49 wazuh-syscheckd: INFO: (1756): Shutdown received. Releasing resources.
2026/03/30 13:05:49 wazuh-execd: INFO: (1314): Shutdown received. Deleting responses.
2026/03/30 13:05:49 wazuh-execd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2026/03/30 13:05:49 wazuh-syscheckd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2026/03/30 13:05:50 wazuh-modulesd:agent-info: INFO: AgentInfo module stopped.
2026/03/30 13:05:50 wazuh-modulesd:agent-info: INFO: AgentInfo destroyed.
2026/03/30 13:05:50 wazuh-modulesd:syscollector: INFO: Stop received for Syscollector.
2026/03/30 13:05:50 wazuh-modulesd:syscollector: INFO: Module finished.
2026/03/30 13:05:50 wazuh-modulesd:sca: INFO: SCA module stopped.
2026/03/30 13:05:50 wazuh-modulesd:sca: ERROR: Exceeded maximum retries for End message. Exiting...
2026/03/30 13:05:50 wazuh-modulesd:sca: ERROR: SCA flush failed
2026/03/30 13:05:52 wazuh-execd: INFO: Started (pid: 7828).
2026/03/30 13:05:53 wazuh-syscheckd: INFO: Started (pid: 7842).
2026/03/30 13:05:53 wazuh-rootcheck: INFO: Starting rootcheck scan.
2026/03/30 13:05:54 wazuh-syscheckd: INFO: (6009): File integrity monitoring scan ended.
2026/03/30 13:05:54 wazuh-logcollector: INFO: Started (pid: 7857).
2026/03/30 13:05:54 wazuh-modulesd: INFO: Started (pid: 7871).
2026/03/30 13:05:54 wazuh-modulesd:agent-upgrade: INFO: (8153): Module Agent Upgrade started.
2026/03/30 13:05:54 wazuh-modulesd:control: INFO: Starting control thread.
2026/03/30 13:05:54 wazuh-modulesd:agent-info: INFO: AgentInfo initialized.
2026/03/30 13:05:54 wazuh-modulesd:sca: INFO: SCA initialized.
2026/03/30 13:05:54 wazuh-modulesd:syscollector: INFO: Module started.
2026/03/30 13:05:54 wazuh-modulesd:sca: INFO: SCA module initialized successfully.
2026/03/30 13:05:54 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2026/03/30 13:05:54 wazuh-modulesd:sca: INFO: Started (pid: 7871).
2026/03/30 13:05:54 wazuh-modulesd:sca: INFO: SCA module already initialized.
2026/03/30 13:05:54 wazuh-modulesd:sca: INFO: SCA module running.
2026/03/30 13:05:54 wazuh-modulesd:sca: INFO: SCA module scan on start.
2026/03/30 13:05:55 wazuh-modulesd:sca: INFO: SCA scan started.
2026/03/30 13:05:56 wazuh-modulesd:sca: INFO: SCA scan ended.
2026/03/30 13:05:58 wazuh-modulesd:syscollector: INFO: Evaluation finished.
```

</details>

<details><summary>After fix — Ubuntu 24.04 agent status and process list</summary>

```bash
root@chkrstsystem:~# /var/ossec/bin/wazuh-control status
wazuh-modulesd is running...
wazuh-logcollector is running...
wazuh-syscheckd is running...
wazuh-agentd is running...
wazuh-execd is running...


root@chkrstsystem:~# ps aux |grep wazuh
wazuh       7120  0.0  0.0 352508 11624 ?        SNl  13:03   0:00 /var/ossec/bin/wazuh-agentd
root        7828  0.0  0.0  56408  6388 ?        SNl  13:05   0:00 /var/ossec/bin/wazuh-execd
root        7842  0.2  0.0 291944 14968 ?        SNl  13:05   0:01 /var/ossec/bin/wazuh-syscheckd
root        7857  0.0  0.0 510716 13760 ?        SNl  13:05   0:00 /var/ossec/bin/wazuh-logcollector
root        7871  0.0  0.0 597648 27596 ?        SNl  13:05   0:00 /var/ossec/bin/wazuh-modulesd
```

</details>

<details><summary>After fix — RPM SUSE (wazuh-control reload)</summary>

```bash
2026/03/30 14:28:31 wazuh-agentd: INFO: Agent is reloading due to shared configuration changes.
2026/03/30 14:28:31 wazuh-modulesd:control: INFO: Executing 'reload' on wazuh-agent using wazuh-control
2026/03/30 14:28:31 wazuh-agentd: WARNING: The <server> tag is deprecated, please use <manager> instead.
2026/03/30 14:28:31 wazuh-agentd: WARNING: Ignoring the 'protocol' option. Switching to TCP.
2026/03/30 14:28:31 wazuh-agentd: WARNING: Ignoring the 'crypto_method' option. Switching to AES.
2026/03/30 14:28:31 wazuh-syscheckd: WARNING: (1230): Invalid element in the configuration: 'scan_on_start'.
2026/03/30 14:28:31 wazuh-syscheckd: WARNING: Rootcheck option 'check_files' is no longer supported. Use the FIM module instead.
2026/03/30 14:28:31 wazuh-syscheckd: WARNING: Rootcheck option 'check_trojans' is no longer supported. Use the FIM module instead.
2026/03/30 14:28:31 wazuh-syscheckd: WARNING: (1230): Invalid element in the configuration: 'rootkit_files'.
2026/03/30 14:28:31 wazuh-syscheckd: WARNING: (1202): Configuration error at 'etc/ossec.conf'.
2026/03/30 14:28:31 wazuh-syscheckd: WARNING: (1207): wazuh-rootcheck remote configuration in 'etc/ossec.conf' is corrupted.
2026/03/30 14:28:31 wazuh-modulesd: ERROR: Unknown module 'cis-cat'
2026/03/30 14:28:31 wazuh-modulesd: ERROR: Unknown module 'osquery'
2026/03/30 14:28:31 wazuh-modulesd:sca: WARNING: Detected a deprecated configuration for SCA: 'skip_nfs' is no longer available.
2026/03/30 14:28:31 wazuh-logcollector: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2026/03/30 14:28:31 wazuh-syscheckd: INFO: (1756): Shutdown received. Releasing resources.
2026/03/30 14:28:31 wazuh-execd: INFO: (1314): Shutdown received. Deleting responses.
2026/03/30 14:28:31 wazuh-execd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2026/03/30 14:28:31 wazuh-modulesd:agent-info: INFO: Resuming paused module: fim
2026/03/30 14:28:31 wazuh-modulesd:agent-info: INFO: Resuming paused module: sca
2026/03/30 14:28:31 wazuh-modulesd:agent-info: INFO: Resuming paused module: syscollector
2026/03/30 14:28:31 wazuh-modulesd:syscollector: INFO: Resuming Syscollector module
2026/03/30 14:28:31 wazuh-modulesd:agent-info: INFO: Synchronization coordination completed successfully
2026/03/30 14:28:31 wazuh-modulesd:agent-info: INFO: Successfully coordinated agent_metadata
2026/03/30 14:28:32 wazuh-syscheckd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2026/03/30 14:28:32 wazuh-modulesd:agent-info: INFO: Starting module coordination process
2026/03/30 14:28:32 wazuh-modulesd:agent-info: INFO: Pausing sca module for synchronization coordination
2026/03/30 14:28:32 wazuh-modulesd:agent-info: INFO: Pausing syscollector module for synchronization coordination
2026/03/30 14:28:32 wazuh-modulesd:agent-info: INFO: Pausing fim module for synchronization coordination
2026/03/30 14:28:32 wazuh-modulesd: ERROR: WM_FIM_QUERY_JSON: Failed to connect to socket, errno=111
2026/03/30 14:28:32 wazuh-modulesd:agent-info: INFO: Waiting for sca module to complete synchronization
2026/03/30 14:28:32 wazuh-modulesd:agent-info: INFO: Waiting for syscollector module to complete synchronization
2026/03/30 14:28:32 wazuh-modulesd:syscollector: INFO: Syscollector flush requested - syncing pending messages
2026/03/30 14:28:32 wazuh-modulesd:syscollector: INFO: Syscollector flush completed successfully
2026/03/30 14:28:32 wazuh-modulesd:agent-info: INFO: AgentInfo module stopped.
2026/03/30 14:28:32 wazuh-modulesd:agent-info: INFO: AgentInfo destroyed.
2026/03/30 14:28:32 wazuh-modulesd:syscollector: INFO: Stop received for Syscollector.
2026/03/30 14:28:32 wazuh-modulesd:syscollector: INFO: Module finished.
2026/03/30 14:28:34 wazuh-execd: INFO: Started (pid: 14344).
```

</details>

<details><summary>After fix — RPM SUSE agent status and process list</summary>

```bash
test_restart:~ # /var/ossec/bin/wazuh-control status
wazuh-modulesd is running...
wazuh-logcollector is running...
wazuh-syscheckd is running...
wazuh-agentd is running...
wazuh-execd is running...


test_restart:~ # ps aux |grep wazuh
wazuh      13773  0.0  0.0 329784 10792 ?        SNl  14:27   0:00 /var/ossec/bin/wazuh-agentd
root       14344  0.0  0.0  33776  5228 ?        SNl  14:28   0:00 /var/ossec/bin/wazuh-execd
root       14357  0.3  0.0 199548 16292 ?        SNl  14:28   0:00 /var/ossec/bin/wazuh-syscheckd
root       14373  0.0  0.0 345352 11940 ?        SNl  14:28   0:00 /var/ossec/bin/wazuh-logcollector
root       14388  0.5  0.0 574636 27088 ?        SNl  14:28   0:00 /var/ossec/bin/wazuh-modulesd
```

</details>

<details><summary>After fix — Windows Server 2019 Datacenter</summary>

```bash
PS C:\Windows\system32> (Get-CimInstance Win32_OperatingSystem).Caption
Microsoft Windows Server 2019 Datacenter Evaluation
PS C:\Windows\system32> (Get-CimInstance Win32_OperatingSystem)

SystemDirectory     Organization BuildNumber RegisteredUser SerialNumber            Version
---------------     ------------ ----------- -------------- ------------            -------
C:\Windows\system32 Vagrant      17763                      00431-20000-00000-AA877 10.0.17763


2026/03/30 08:39:52 wazuh-agent: INFO: Agent is reloading due to shared configuration changes.
2026/03/30 08:39:52 wazuh-agent: INFO: Agent control: reload command received.
2026/03/30 08:39:52 wazuh-agent: INFO: Agent control: 'reload' command received, detached restart process spawned.
2026/03/30 08:39:53 wazuh-agent: INFO: Received exit signal. Starting exit process.
2026/03/30 08:39:53 wazuh-agent: INFO: Set pending exit signal.
2026/03/30 08:39:53 wazuh-modulesd:agent-info: INFO: AgentInfo module loop ended.
2026/03/30 08:39:53 wazuh-modulesd:agent-info: INFO: AgentInfo module stopped.
2026/03/30 08:39:53 wazuh-modulesd:agent-info: INFO: AgentInfo destroyed.
2026/03/30 08:39:53 wazuh-modulesd:sca: INFO: SCA module stopped.
2026/03/30 08:39:53 wazuh-modulesd:syscollector: INFO: Stop received for Syscollector.
2026/03/30 08:39:53 wazuh-modulesd:syscollector: INFO: Module finished.
2026/03/30 08:39:53 wazuh-modulesd:syscollector: ERROR: syscollector_vd: Exceeded maximum retries for End message. Exiting...
2026/03/30 08:39:53 wazuh-modulesd:syscollector: WARNING: Syscollector synchronization process failed.
2026/03/30 08:39:53 wazuh-agent: INFO: Exit completed successfully.
2026/03/30 08:39:53 wazuh-agent: INFO: (1314): Shutdown received. Deleting responses.
2026/03/30 08:39:54 wazuh-agent: WARNING: The <server> tag is deprecated, please use <manager> instead.
2026/03/30 08:39:54 wazuh-agent: WARNING: Ignoring the 'protocol' option. Switching to TCP.
2026/03/30 08:39:54 wazuh-agent: WARNING: Ignoring the 'crypto_method' option. Switching to AES.
2026/03/30 08:39:54 wazuh-agent: INFO: (1410): Reading authentication keys file.
2026/03/30 08:39:54 wazuh-agent: INFO: Using notify time: 20 and max time to reconnect: 60
2026/03/30 08:39:54 wazuh-agent: INFO: Started (pid: 4308).
2026/03/30 08:39:54 wazuh-modulesd:sca: WARNING: Detected a deprecated configuration for SCA: 'skip_nfs' is no longer available.
2026/03/30 08:39:54 wazuh-agent: ERROR: Unknown module 'cis-cat'
2026/03/30 08:39:54 wazuh-agent: ERROR: Unknown module 'osquery'
2026/03/30 08:39:54 wazuh-agent: INFO: (4102): Connected to the server ([192.168.56.1]:1514/tcp).
2026/03/30 08:39:55 wazuh-modulesd:agent-upgrade: INFO: (8153): Module Agent Upgrade started.
2026/03/30 08:39:55 wazuh-agent: INFO: (1951): Analyzing event log: 'Application'.
2026/03/30 08:39:55 wazuh-agent: WARNING: Rootcheck option 'windows_apps' is no longer supported. Use the SCA module instead.
2026/03/30 08:39:55 wazuh-agent: WARNING: Rootcheck option 'windows_malware' is no longer supported. Use the SCA module instead.
2026/03/30 08:39:55 wazuh-agent: INFO: (1951): Analyzing event log: 'Security'.
2026/03/30 08:39:55 wazuh-rootcheck: INFO: Started (pid: 4308).
2026/03/30 08:39:55 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Classes\batfile', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256 | type'
2026/03/30 08:39:55 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Classes\cmdfile', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256 | type'
2026/03/30 08:39:55 wazuh-agent: INFO: (1951): Analyzing event log: 'System'.
2026/03/30 08:39:55 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Classes\comfile', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256 | type'
2026/03/30 08:39:55 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Classes\exefile', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256 | type'
2026/03/30 08:39:55 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Classes\piffile', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256 | type'
2026/03/30 08:39:55 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Classes\AllFilesystemObjects', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256 | type'
2026/03/30 08:39:55 wazuh-modulesd:sca: INFO: SCA initialized.
2026/03/30 08:39:55 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Classes\Directory', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256 | type'
2026/03/30 08:39:55 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Classes\Folder', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256 | type'
2026/03/30 08:39:55 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Classes\Protocols [x64]', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256 | type'
2026/03/30 08:39:55 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Classes\Protocols', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256 | type'
2026/03/30 08:39:55 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Policies [x64]', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256 | type'
2026/03/30 08:39:55 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Policies', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256 | type'
2026/03/30 08:39:55 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Security', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256 | type'
2026/03/30 08:39:55 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Internet Explorer [x64]', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256 | type'
2026/03/30 08:39:55 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Internet Explorer', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256 | type'
2026/03/30 08:39:55 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256 | type'
2026/03/30 08:39:55 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Session Manager\KnownDLLs', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256 | type'
2026/03/30 08:39:55 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\SecurePipeServers\winreg', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256 | type'
2026/03/30 08:39:55 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Run [x64]', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256 | type'
2026/03/30 08:39:55 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Run', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256 | type'
2026/03/30 08:39:55 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\RunOnce [x64]', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256 | type'
2026/03/30 08:39:55 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\RunOnce', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256 | type'
2026/03/30 08:39:55 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\RunOnceEx', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256 | type'
2026/03/30 08:39:55 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\URL [x64]', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256 | type'
2026/03/30 08:39:55 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\URL', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256 | type'
2026/03/30 08:39:55 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies [x64]', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256 | type'
2026/03/30 08:39:55 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256 | type'
2026/03/30 08:39:55 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Windows [x64]', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256 | type'
2026/03/30 08:39:55 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Windows', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256 | type'
2026/03/30 08:39:55 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Winlogon [x64]', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256 | type'
2026/03/30 08:39:55 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Winlogon', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256 | type'
2026/03/30 08:39:55 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Active Setup\Installed Components [x64]', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256 | type'
2026/03/30 08:39:55 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Active Setup\Installed Components', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256 | type'
2026/03/30 08:39:55 wazuh-agent: INFO: Started (pid: 4308).
2026/03/30 08:39:55 wazuh-modulesd:sca: INFO: SCA module initialized successfully.
2026/03/30 08:39:55 wazuh-modulesd:sca: INFO: Started (pid: 4308).
2026/03/30 08:39:55 wazuh-modulesd:sca: INFO: SCA module already initialized.
2026/03/30 08:39:55 wazuh-modulesd:sca: INFO: SCA module running.
2026/03/30 08:39:55 wazuh-modulesd:sca: INFO: SCA module scan on start.
2026/03/30 08:39:55 wazuh-modulesd:syscollector: INFO: Module started.
2026/03/30 08:39:55 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2026/03/30 08:39:55 wazuh-modulesd:agent-info: INFO: AgentInfo initialized.
2026/03/30 08:39:55 wazuh-agent: INFO: Started (pid: 4308).
2026/03/30 08:39:55 wazuh-modulesd:syscollector: ERROR: Schema validation failed for Syscollector message (table: dbsync_network_protocol, index: wazuh-states-inventory-protocols). Errors:   - network.gateway: Invalid IP address format: fe80::2,10.0.2.2
2026/03/30 08:39:55 wazuh-modulesd:syscollector: ERROR: Raw event that failed validation: {"checksum":{"hash":{"sha1":"c57a611532f173fb922ac170483749c9cdd329c4"}},"interface":{"name":"Ethernet"},"network":{"dhcp":true,"gateway":"fe80::2,10.0.2.2","metric":25,"type":"ipv4"},"state":{"document_version":1,"modified_at":"2026-03-30T15:39:55.709Z"}}
2026/03/30 08:39:55 wazuh-modulesd:syscollector: ERROR: Discarding invalid Syscollector message (table: dbsync_network_protocol)
2026/03/30 08:39:55 wazuh-modulesd:syscollector: ERROR: Schema validation failed for Syscollector message (table: dbsync_network_protocol, index: wazuh-states-inventory-protocols). Errors:   - network.gateway: Invalid IP address format: fe80::2,10.0.2.2
2026/03/30 08:39:55 wazuh-modulesd:syscollector: ERROR: Raw event that failed validation: {"checksum":{"hash":{"sha1":"3bd9f4f2cc4db47d3f3b5e22c0281ed21951d517"}},"interface":{"name":"Ethernet"},"network":{"dhcp":true,"gateway":"fe80::2,10.0.2.2","metric":25,"type":"ipv4"},"state":{"document_version":1,"modified_at":"2026-03-30T15:39:55.709Z"}}
2026/03/30 08:39:55 wazuh-modulesd:syscollector: ERROR: Discarding invalid Syscollector message (table: dbsync_network_protocol)
2026/03/30 08:39:56 wazuh-rootcheck: INFO: Starting rootcheck scan.
2026/03/30 08:39:56 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2026/03/30 08:40:01 wazuh-rootcheck: INFO: Ending rootcheck scan.
2026/03/30 08:40:02 wazuh-modulesd:sca: INFO: SCA scan started.
2026/03/30 08:40:02 wazuh-agent: WARNING: Cannot run '%WINDIR%\SysNative\WindowsPowerShell\v1.0\powershell secedit /export /cfg $env:TEMP\secpol.cfg; Get-Content $env:TEMP\secpol.cfg | Select-String "MaximumPasswordAge"; Remove-Item $env:TEMP\secpol.cfg': The system cannot find the file specified. (2)
2026/03/30 08:40:02 wazuh-agent: WARNING: Cannot run '%WINDIR%\SysNative\WindowsPowerShell\v1.0\powershell secedit /export /cfg $env:TEMP\secpol.cfg; Get-Content $env:TEMP\secpol.cfg | Select-String "MaximumPasswordAge"; Remove-Item $env:TEMP\secpol.cfg': The system cannot find the file specified. (2)
2026/03/30 08:40:02 wazuh-agent: WARNING: Cannot run '%WINDIR%\SysNative\WindowsPowerShell\v1.0\powershell secedit /export /cfg $env:TEMP\secpol.cfg; Get-Content $env:TEMP\secpol.cfg | Select-String "MinimumPasswordAge"; Remove-Item $env:TEMP\secpol.cfg': The system cannot find the file specified. (2)
2026/03/30 08:40:02 wazuh-agent: WARNING: Cannot run '%WINDIR%\SysNative\WindowsPowerShell\v1.0\powershell secedit /export /cfg $env:TEMP\secpol.cfg; Get-Content $env:TEMP\secpol.cfg | Select-String "MinimumPasswordLength"; Remove-Item $env:TEMP\secpol.cfg': The system cannot find the file specified. (2)
2026/03/30 08:40:02 wazuh-agent: INFO: (6009): File integrity monitoring scan ended.
2026/03/30 08:40:02 wazuh-agent: INFO: Starting FIM synchronization.
2026/03/30 08:40:02 wazuh-agent: INFO: (6012): Real-time file integrity monitoring started.
2026/03/30 08:40:03 wazuh-agent: WARNING: Cannot run '%WINDIR%\SysNative\WindowsPowerShell\v1.0\powershell secedit /export /cfg $env:TEMP\secpol.cfg; Get-Content $env:TEMP\secpol.cfg | Select-String "LockoutDuration"; Remove-Item $env:TEMP\secpol.cfg': The system cannot find the file specified. (2)
2026/03/30 08:40:03 wazuh-agent: WARNING: Cannot run '%WINDIR%\SysNative\WindowsPowerShell\v1.0\powershell secedit /export /cfg $env:TEMP\secpol.cfg; Get-Content $env:TEMP\secpol.cfg | Select-String "LockoutBadCount"; Remove-Item $env:TEMP\secpol.cfg': The system cannot find the file specified. (2)
2026/03/30 08:40:03 wazuh-agent: WARNING: Cannot run '%WINDIR%\SysNative\WindowsPowerShell\v1.0\powershell secedit /export /cfg $env:TEMP\secpol.cfg; Get-Content $env:TEMP\secpol.cfg | Select-String "LockoutBadCount"; Remove-Item $env:TEMP\secpol.cfg': The system cannot find the file specified. (2)
2026/03/30 08:40:03 wazuh-agent: WARNING: Cannot run '%WINDIR%\SysNative\WindowsPowerShell\v1.0\powershell secedit /export /cfg $env:TEMP\secpol.cfg; Get-Content $env:TEMP\secpol.cfg | Select-String "ResetLockoutCount"; Remove-Item $env:TEMP\secpol.cfg': The system cannot find the file specified. (2)
2026/03/30 08:40:03 wazuh-agent: WARNING: Cannot run '%WINDIR%\SysNative\WindowsPowerShell\v1.0\powershell -NoProfile -Command "[bool](Get-CimInstance -Query 'SELECT * FROM Win32_UserAccount WHERE LocalAccount = TRUE AND SID LIKE ''S-1-5-21-%-501''' | Where-Object -Property Disabled)"': The system cannot find the file specified. (2)
2026/03/30 08:40:10 wazuh-modulesd:sca: INFO: SCA scan ended.
2026/03/30 08:40:10 wazuh-modulesd:sca: INFO: Starting SCA synchronization.
```

</details>

<details><summary>After fix — macOS (wazuh-control reload)</summary>

```bash
2026/03/30 09:46:02 wazuh-agentd: INFO: Agent is reloading due to shared configuration changes.
2026/03/30 09:46:02 wazuh-modulesd:control: INFO: Executing 'reload' on wazuh-agent using wazuh-control
2026/03/30 09:46:03 wazuh-logcollector: INFO: (1225): SIGNAL [(15)-(Terminated: 15)] Received. Exit Cleaning...
2026/03/30 09:46:03 wazuh-syscheckd: INFO: (1756): Shutdown received. Releasing resources.
2026/03/30 09:46:03 wazuh-syscheckd: INFO: (1225): SIGNAL [(15)-(Terminated: 15)] Received. Exit Cleaning...
2026/03/30 09:46:03 wazuh-execd: INFO: (1314): Shutdown received. Deleting responses.
2026/03/30 09:46:03 wazuh-execd: INFO: (1225): SIGNAL [(15)-(Terminated: 15)] Received. Exit Cleaning...
2026/03/30 09:46:04 wazuh-modulesd:agent-info: INFO: AgentInfo module loop ended.
2026/03/30 09:46:04 wazuh-modulesd:agent-info: INFO: AgentInfo module stopped.
2026/03/30 09:46:04 wazuh-modulesd:agent-info: INFO: AgentInfo destroyed.
2026/03/30 09:46:04 wazuh-modulesd:syscollector: INFO: Stop received for Syscollector.
2026/03/30 09:46:04 wazuh-modulesd:syscollector: INFO: Module finished.
2026/03/30 09:46:04 wazuh-modulesd:sca: INFO: SCA module stopped.
2026/03/30 09:46:05 wazuh-execd: INFO: Started (pid: 4231).
2026/03/30 09:46:05 wazuh-syscheckd: INFO: Started (pid: 4243).
2026/03/30 09:46:05 wazuh-rootcheck: INFO: Starting rootcheck scan.
2026/03/30 09:46:05 wazuh-logcollector: INFO: (1604): Monitoring macOS logs with: /usr/bin/log stream --style syslog --type activity --type log --type trace --level info --predicate (process == "sudo") or (process == "sessionlogoutd" and message contains "logout is complete.") or (process == "sshd") or (process == "tccd" and message contains "Update Access Record") or (message contains "SessionAgentNotificationCenter") or (process == "screensharingd" and message contains "Authentication") or (process == "securityd" and eventMessage contains "Session" and subsystem == "com.apple.securityd").
2026/03/30 09:46:05 wazuh-logcollector: INFO: Started (pid: 4251).
2026/03/30 09:46:06 wazuh-modulesd: INFO: Started (pid: 4271).
2026/03/30 09:46:06 wazuh-modulesd:agent-upgrade: INFO: (8153): Module Agent Upgrade started.
2026/03/30 09:46:06 wazuh-modulesd:control: INFO: Starting control thread.
2026/03/30 09:46:06 wazuh-modulesd:sca: INFO: SCA initialized.
2026/03/30 09:46:06 wazuh-modulesd:agent-info: INFO: AgentInfo initialized.
2026/03/30 09:46:06 wazuh-modulesd:sca: INFO: SCA module initialized successfully.
2026/03/30 09:46:06 wazuh-modulesd:sca: INFO: Started (pid: 4271).
2026/03/30 09:46:06 wazuh-modulesd:sca: INFO: SCA module already initialized.
2026/03/30 09:46:06 wazuh-modulesd:sca: INFO: SCA module running.
2026/03/30 09:46:06 wazuh-modulesd:sca: INFO: SCA module scan on start.
2026/03/30 09:46:06 wazuh-modulesd:syscollector: INFO: Module started.
2026/03/30 09:46:06 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2026/03/30 09:46:06 wazuh-modulesd:sca: INFO: SCA scan started.
2026/03/30 09:46:10 wazuh-modulesd:sca: INFO: SCA scan ended.
2026/03/30 09:46:10 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2026/03/30 09:46:12 wazuh-syscheckd: INFO: (6009): File integrity monitoring scan ended.
2026/03/30 09:46:25 wazuh-rootcheck: INFO: Ending rootcheck scan.
```

</details>

<details><summary>After fix — macOS agent status and process list</summary>

```bash
sh-3.2# /Library/Ossec/bin/wazuh-control status
wazuh-modulesd is running...
wazuh-logcollector is running...
wazuh-syscheckd is running...
wazuh-agentd is running...
wazuh-execd is running...


sh-3.2# ps aux |grep wazuh
root              4251   0.0  0.0 34201764   1864   ??  S     9:46AM   0:00.02 /Library/Ossec/bin/wazuh-logcollector
root              4243   0.0  0.1 34178184   6060   ??  SN    9:46AM   0:05.28 /Library/Ossec/bin/wazuh-syscheckd
root              4231   0.0  0.0 34152388   1032   ??  S     9:46AM   0:00.01 /Library/Ossec/bin/wazuh-execd
wazuh             3672   0.0  0.1 34185996   6136   ??  S     9:42AM   0:00.87 /Library/Ossec/bin/wazuh-agentd
root              4581   0.0  0.0 34121104    672 s002  S+    9:47AM   0:00.00 grep wazuh
root              4271   0.0  0.5 34220780  19856   ??  S     9:46AM   0:00.91 /Library/Ossec/bin/wazuh-modulesd
```

</details>

### Artifacts Affected

- `wazuh-agentd`

### Configuration Changes

_No configuration changes._

### Documentation Updates

_No documentation changes required._

### Tests Introduced

_No new tests introduced._

## Review Checklist

- [ ] Code changes reviewed
- [ ] Relevant evidence provided
- [ ] Tests cover the new functionality
- [ ] Configuration changes documented
- [ ] Developer documentation reflects the changes
- [ ] Meets requirements and/or definition of done
- [ ] No unresolved dependencies with other issues

### CODE REVIEW

File: src/client-agent/src/reload_agent.c [hunk 1]
```diff
@@ -33,18 +33,31 @@ void * reloadAgent() {
...
-			merror("Could not auto-reload agent. Could not connect to control socket '%s'.", sockname);
+	for (attempt = 0; attempt < max_retries; attempt++) {
+		sock = OS_ConnectUnixDomain(sockname, SOCK_STREAM, OS_MAXSTR);
+		if (sock >= 0) {
 			break;
+		}
 
-		default:
+		if (errno == ENOENT || errno == ECONNREFUSED) {
+			if (attempt == 0) {
```
Comment (cborla) [inline src/client-agent/src/reload_agent.c]: Why do we try to limit the message to the first attempt? If the message is for debugging, it's better to see the complete sequence in the debug output.
