### PR TITLE
Fix double file handle closing in Logcollector

### LINKED ISSUE #9066: Invalid file closing operation in Logcollector
|Wazuh version|Component|Install type|Platform|
|---|---|---|---|
| 1.0.0 | Logcollector | Agent | Windows |

Logcollector needs to open log files in a special way to allow other processes to write and delete those files. The implementation of function `fopen()` only allows shared write, but not delete.

That is why Logcollector calls these three operations to emulate `fopen()`:
1. [`CreateFile()`](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilea) to create a file handle.
2. [`_open_osfhandle()`](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/open-osfhandle?view=msvc-160) to get an UNIX-like file descriptor for that handle.
3. [`_fdopen()`](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/fdopen-wfdopen?view=msvc-160) to get a `FILE *` from that file descriptor.

The behavior is similar to our function ([`wfopen()`](https://github.com/wazuh/wazuh/blob/635a673a7fdd11962891a8de8196b7aafde4a80a/src/shared/file_op.c#L2694)). According to the documentation by Microsoft, we must not call `CloseHandle()` on the file descriptor returned by `CreateFile()` as `fclose()` implicitly calls it:
> If the file descriptor is owned by a `FILE *` stream, then a call to `fclose` closes both the file descriptor and the underlying handle. In this case, don't call `_close` on the file descriptor or `CloseHandle` on the original handle.

However, Logcollector is calling `CloseHandle()` on every file after closing them via `fclose()`, such in [logcollector.c](https://github.com/wazuh/wazuh/blob/c2531dd496a72824b14ded2f55b87654403d36ad/src/logcollector/logcollector.c#L540). We checked that the function returns `false` (error) in most executions, but there are a few where it returns `true` (done), which means that Logcollector may be closing a valid handle for another component.

## Proposed fix

1. Remove every call to `CloseHandle()` in logcollector.c.
2. Check that this change does not cause descriptor leaks.

### PR DESCRIPTION
**Pull request by vikman90**
|Related issue|
|---|
|Closes #9066|

This PR aims to remove every call to `CloseHandle()` on files closed by `fclose()` in Logcollector on Windows agents, as the underlying file handle is implicitly closed, as explained at #9066.

## Tests

- [X] Build agent on Windows.
- [ ] Stress test on the Windows agent.
- [ ] Check that this change won't cause handle leaks.
- [x] Run a Coverity scan on this branch.

### CODE REVIEW

File: src/logcollector/logcollector.c [hunk 1]
```diff
@@ -985,7 +969,6 @@ int handle_file(int i, int j, __attribute__((unused)) int do_fseek, int do_log)
     if (GetFileInformationByHandle(lf->h, &lpFileInformation) == 0) {
```
Comment (Dwordcito) [inline src/logcollector/logcollector.c:969]: Replace line 961 to _close(fd) based on [_open_osfhandle docs](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/open-osfhandle?view=msvc-160)

Comment (Dwordcito) [reply src/logcollector/logcollector.c:969]: Same comment for the reload_file function behavior

**Review by Dwordcito — CHANGES_REQUESTED** [review]
It would be a good practice to remove from the struct _logreader and remove all reference to the handle, this would avoid cleaning up everywhere the misuse due to the change of ownership of the handle with _open_osfhandle and _fdopen.

**Comment by vikman90** [comment]
@Dwordcito thanks for your review.

As discussed privately, Logcollector requires the current file handler ([`GetFileInformationByHandle`](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getfileinformationbyhandle)) to fetch its properties ([https://docs.microsoft.com/en-us/windows/win32/api/fileapi/ns-fileapi-by_handle_file_information`](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/ns-fileapi-by_handle_file_information)):

- `nFileIndexLow` and `nFileIndexHigh`
- `nFileSizeLow` and `nFileSizeHigh`

Should we remove the handler (`h`) from the structure `_logreader`, we would need to retrieve the file handler from the file pointer, like this:
```c
GetFileInformationByHandle(_get_osfhandle(_fileno(lf->fp)));
```

This way we would need to replace a value already obtained by a chain of calls, to which must be added the error check. This is why the simplest option is the current one.

**Review by Dwordcito — APPROVED** [review]
looks good!!!
