### PR TITLE
Fix permission error in JSON alert

### LINKED ISSUE #12073: Error adding permissions to json alert file in syscheck stress test 4.3.0-rc3
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.0-rc3 | wazuh-analysisd | Manager | Packages | Centos8 |

Analyzing the [Syscheck stress test result](https://github.com/wazuh/wazuh/issues/12007), I have found the following error in the manager log, which is repeated up to 92 times during the test:

```
wazuh-analysisd: ERROR: The new permissions could not be added to the JSON alert.
```

This error has been reported by @Phandora for 4.1.5 from a community and in this google groups thread: https://groups.google.com/g/wazuh/c/ZpNhlU0IDJg (4.1.2)

This bug was attempted to be fixed at https://github.com/wazuh/wazuh/issues/8312 in 4.2

### PR DESCRIPTION
**Pull request by FrancoRivero**
|Issue|
|---|
| Closes #12073  |

## Description

When `FIM` is run on Windows logs with a malformed permission, the `analysisd` module generates a log message and discards this permission. This PR is to add changes to this behavior, right now the module `analysisd` reads permissions and discard only malformed permissions.

## Logs/Alerts example
[Syscheck stress test result](https://github.com/wazuh/wazuh/issues/12007),

## Tests

- Compilation without warnings in every supported platform
  - [x] Linux
  - [x] Windows
  - [x] MAC OS X
- [x] Source installation
- [x] Package installation
- [x] Source upgrade
- [x] Package upgrade
- [x] Review logs syntax and correct language
- [x] Run stress test ([result](https://github.com/wazuh/wazuh/issues/12073#issuecomment-1165931629))
- [x] Add unit tests to new code

### CODE REVIEW

**Review by antoniomanuelfr — DISMISSED** [review]

**Review by jotacarma90 — DISMISSED** [review]
LGTM

**Review by MarcelKemp — DISMISSED** [review]

File: src/analysisd/format/to_json.c [hunk 1]
```diff
@@ -346,7 +346,7 @@ char* Eventinfo_to_jsonstr(const Eventinfo* lf, bool force_full_log, OSList * li
                 if (old_perm = win_perm_to_json(lf->fields[FIM_PERM_BEFORE].value), old_perm) {
                     cJSON_AddItemToObject(file_diff, "win_perm_before", old_perm);
                 } else {
-                    smerror(list_msg, "The old permissions could not be added to the JSON alert.");
+                    smwarn(list_msg, "The old permissions could not be added to the JSON alert.");
```
Comment (chemamartinez) [inline src/analysisd/format/to_json.c:349]:
```suggestion
                    smwarn(list_msg, "The old permissions of the Windows event could not be added to the JSON alert.");
```

It would be good to specify where the log comes from since this warning is triggered by Analysisd.

File: src/shared/syscheck_op.c [hunk 2]
```diff
@@ -1517,7 +1517,8 @@ cJSON *win_perm_to_json(char *perms) {
         char *username = perm_node;
         perm_node = strchr(perm_node, '(');
         if (!perm_node) {
-            goto error;
+            mdebug2("Uncontrolled condition when parsing a Windows permission from '%s'. Skip permission", username);
```
Comment (chemamartinez) [inline src/shared/syscheck_op.c:1520]:
```suggestion
            mdebug1("Uncontrolled condition when parsing the username from '%s'. Skipping permission.", username);
```

It is better to use debug1 since it is an unexpected situation.  In addition, let's be more specific in the info we are parsing to differenciate the errors.

File: src/shared/syscheck_op.c [hunk 3]
```diff
@@ -1531,7 +1532,8 @@ cJSON *win_perm_to_json(char *perms) {
         char *perm_type = perm_node;
         perm_node = strchr(perm_node, ')');
         if (!perm_node) {
-            goto error;
+            mdebug2("Uncontrolled condition when parsing a Windows permission from '%s'. Skip permission", perm_type);
```
Comment (chemamartinez) [inline src/shared/syscheck_op.c:1535]:
```suggestion
            mdebug1("Uncontrolled condition when parsing the permission type from '%s'. Skipping permission.", perm_type);
```

File: src/unit_tests/shared/test_syscheck_op.c [hunk 4]
```diff
@@ -3213,6 +3213,176 @@ static void test_win_perm_to_json_multiple_accounts(void **state) {
...
+
+    will_return(__wrap_cJSON_CreateArray, __real_cJSON_CreateArray());
+    will_return(__wrap_cJSON_CreateArray, __real_cJSON_CreateArray());
+    will_return(__wrap_cJSON_CreateArray, __real_cJSON_CreateArray());
+    will_return(__wrap_cJSON_CreateArray, __real_cJSON_CreateArray());
+    will_return(__wrap_cJSON_CreateArray, __real_cJSON_CreateArray());
+
+    will_return_always(__wrap_wstr_split, 1);  // use real wstr_split
+    expect_string(__wrap__mdebug2, formatted_msg,
+        "Uncontrolled condition when parsing a Windows permission from 'fourth '. Skip permission");
```
Comment (chemamartinez) [inline src/unit_tests/shared/test_syscheck_op.c:3238]: Adapt logs to the review in the code.

**Review by chemamartinez — CHANGES_REQUESTED** [review]

**Review by chemamartinez — DISMISSED** [review]
LGTM

**Review by chemamartinez — APPROVED** [review]

**Comment by chemamartinez** [comment]
[Test: AR IT - Tier 0 - windows_agent](https://github.com/wazuh/wazuh/pull/14019/checks) is failing with the following error:
```
============================== warnings summary ===============================
..\..\..\..\Python37\lib\site-packages\win32\lib\pywintypes.py:2
  C:\Python37\lib\site-packages\win32\lib\pywintypes.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp, sys, os
```

This is a dependency error in the test itself that is not related to this pull request. It is already addressed at https://github.com/wazuh/wazuh-qa/issues/2769, so please ignore it.

**Review by antoniomanuelfr — APPROVED** [review]

File: src/shared/syscheck_op.c [hunk 5]
```diff
@@ -1517,7 +1517,8 @@ cJSON *win_perm_to_json(char *perms) {
         char *username = perm_node;
         perm_node = strchr(perm_node, '(');
         if (!perm_node) {
-            goto error;
+            mdebug1("Uncontrolled condition when parsing the username from '%s'. Skipping permission.", username);
```
Comment (antoniomanuelfr) [inline src/shared/syscheck_op.c:1520]: I think that in this case, as the message is the same as in line 1535, we should define a constant here https://github.com/wazuh/wazuh/blob/master/src/error_messages/debug_messages.h instead of hardcoding the message.
Use this constant also in the UTs

**Review by antoniomanuelfr — CHANGES_REQUESTED** [review]

**Review by chemamartinez — APPROVED** [review]

**Review by antoniomanuelfr — DISMISSED** [review]

**Comment by jmv74211** [comment]
## QA review

- **Type**: Manual testing.
- **Status**: Approved  🟢 
- **Testing issue**: https://github.com/wazuh/wazuh-qa/issues/3133
- **Comments**: The QA team has not been able to reproduce the bug as such. The development team has created unit tests that test similar cases and it is tested in this way. QA has manually tested that the bug does not occur, and FIM regression tests have been launched.

**Review by chemamartinez — APPROVED** [review]

**Comment by dami-nicastro** [comment]
Hello @chemamartinez and team:
Could you tell me which Wazuh version will have the fix for this issue? Please, also let me know the approximated release date for it.
Thanks!
