### PR TITLE
Take short summary from dpkg description.

### LINKED ISSUE #7639: Packages description exceed the send limit
## Description

This issue aims to solve a problem found and reported by alvaro. In which the size limit of an established network message is exceeded.

Reproduction steps:
1-Install texlive
2-Run scan-synchro syscollector

Actual result: Message not are sent to manager service
Expected result: Message are sent to manager service

## DoD
- [x] Truncate messages with long description (65000b)
- [x] Add unit tests
- [x] PR - CI PASS

### PR DESCRIPTION
**Pull request by Dwordcito**
|Related issue|
|---|
|Closes #7639 |

## Description

This issue aims to solve a problem found and reported by alvaro. In which the size limit of an established network message is exceeded.

Reproduction steps:
1-Install texlive
2-Run scan-synchro syscollector

Actual result: Message not are sent to manager service
Expected result: Message are sent to manager service

## DoD
- [x] Truncate messages with long description (65000b)
- [x] Add unit tests
- [ ] PR - CI PASS

### CODE REVIEW

File: src/shared_modules/utils/tests/stringHelper_test.cpp [hunk 1]
```diff
@@ -170,4 +170,29 @@ TEST_F(StringUtilsTest, CheckMultiReplacement)
     const auto retVal { Utils::replaceAll(string_base, "  ", " ") };
     EXPECT_EQ(string_base, "hello world");
     EXPECT_TRUE(retVal);
+}
+
```
Comment (tinachoB) [inline src/shared_modules/utils/tests/stringHelper_test.cpp:174]: Maybe you should add a specific UT checking the "\n" case which is the one that, currently, is being used.

**Review by tinachoB — APPROVED** [review]
LGTM!

**Review by konangc87 — APPROVED** [review]
