### PR TITLE
Find before access, to avoid exceptions

### LINKED ISSUE #6647: OS Parser in Debian aarch64
## Description
commit f9034f7ff2edb62af09008e426813055d7a5ddc6
```
root@f7bcdcbdcb9d:/pkg/wazuh/src# gdb ./wazuh_modules/syscollector/build/bin/syscollector_test_tool 
GNU gdb (Debian 7.12-6) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "aarch64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./wazuh_modules/syscollector/build/bin/syscollector_test_tool...done.
(gdb) catch throw
Catchpoint 1 (throw)
(gdb) r
Starting program: /pkg/wazuh/src/wazuh_modules/syscollector/build/bin/syscollector_test_tool 
warning: Error disabling address space randomization: Operation not permitted
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/aarch64-linux-gnu/libthread_db.so.1".
warning: File "/usr/local/gcc-5.5.0/lib64/libstdc++.so.6.0.21-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
To enable execution of this file add
	add-auto-load-safe-path /usr/local/gcc-5.5.0/lib64/libstdc++.so.6.0.21-gdb.py
line to your configuration file "/root/.gdbinit".
To completely disable this security protection add
	set auto-load safe-path /
line to your configuration file "/root/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
	info "(gdb)Auto-loading safe path"
[New Thread 0xffff9b72a1b0 (LWP 13021)]
[New Thread 0xffff9af291b0 (LWP 13022)]
[New Thread 0xffff9a7281b0 (LWP 13023)]
[New Thread 0xffff99f271b0 (LWP 13024)]
[New Thread 0xffff997261b0 (LWP 13025)]

Thread 1 "syscollector_te" hit Catchpoint 1 (exception thrown), __cxxabiv1::__cxa_throw (obj=obj@entry=0x162e6f40, tinfo=0xffff9c424280 <typeinfo for std::out_of_range>, dest=0xffff9c326ee0 <std::out_of_range::~out_of_range()>)
    at ../../.././libstdc++-v3/libsupc++/eh_throw.cc:62
62	../../.././libstdc++-v3/libsupc++/eh_throw.cc: No such file or directory.
(gdb) bt
#0  __cxxabiv1::__cxa_throw (obj=obj@entry=0x162e6f40, tinfo=0xffff9c424280 <typeinfo for std::out_of_range>, dest=0xffff9c326ee0 <std::out_of_range::~out_of_range()>) at ../../.././libstdc++-v3/libsupc++/eh_throw.cc:62
#1  0x0000ffff9c330398 in std::__throw_out_of_range (__s=0xffff9c122e70 "map::at") at ../../../.././libstdc++-v3/src/c++11/functexcept.cc:90
#2  0x0000ffff9c067730 in std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::at (this=0xffffc5094508, __k=...)
    at /usr/local/gcc-5.5.0/include/c++/5.5.0/bits/stl_map.h:524
#3  0x0000ffff9c05caa8 in SysInfo::getCpuName[abi:cxx11]() const (this=0x162bfc30) at /pkg/wazuh/src/data_provider/src/sysInfoLinux.cpp:319
#4  0x0000ffff9c0783ac in SysInfo::hardware[abi:cxx11]() (this=0x162bfc30) at /pkg/wazuh/src/data_provider/src/sysInfo.cpp:18
#5  0x0000ffff9bc348cc in Syscollector::scanHardware (this=0x41e380 <Syscollector::instance()::s_instance>) at /pkg/wazuh/src/wazuh_modules/syscollector/src/syscollectorImp.cpp:386
#6  0x0000ffff9bc36760 in Syscollector::scan (this=0x41e380 <Syscollector::instance()::s_instance>) at /pkg/wazuh/src/wazuh_modules/syscollector/src/syscollectorImp.cpp:563
#7  0x0000ffff9bc367b8 in Syscollector::syncLoop (this=0x41e380 <Syscollector::instance()::s_instance>) at /pkg/wazuh/src/wazuh_modules/syscollector/src/syscollectorImp.cpp:575
#8  0x0000ffff9bc34758 in Syscollector::init(std::shared_ptr<ISysInfo> const&, std::function<void (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>, unsigned int, bool, bool, bool, bool, bool, bool, bool, bool, bool) (
    this=0x41e380 <Syscollector::instance()::s_instance>, spInfo=..., reportFunction=..., interval=15, scanOnStart=true, hardware=true, os=true, network=true, packages=true, ports=true, portsAll=true, processes=true, hotfixes=true)
    at /pkg/wazuh/src/wazuh_modules/syscollector/src/syscollectorImp.cpp:369
#9  0x0000000000407ad8 in main () at /pkg/wazuh/src/wazuh_modules/syscollector/testtool/main.cpp:62

```

Current: It is giving exception (controlled) for you cannot access by "at" during the population.
Expected: No exception, and try to recover the major information possible.
Steps to reproduce: Run syscollector test tool.

```
root@f7bcdcbdcb9d:/pkg/wazuh/src# cat /proc/cpuinfo 
processor	: 0
BogoMIPS	: 243.75
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x3
CPU part	: 0xd0c
CPU revision	: 1

processor	: 1
BogoMIPS	: 243.75
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x3
CPU part	: 0xd0c
CPU revision	: 1

processor	: 2
BogoMIPS	: 243.75
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x3
CPU part	: 0xd0c
CPU revision	: 1

processor	: 3
BogoMIPS	: 243.75
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x3
CPU part	: 0xd0c
CPU revision	: 1
```

```
root@f7bcdcbdcb9d:/pkg/wazuh/src# uname -a
Linux f7bcdcbdcb9d 4.14.193-149.317.amzn2.aarch64 #1 SMP Thu Sep 3 19:04:59 UTC 2020 aarch64 GNU/Linux
```

```
root@f7bcdcbdcb9d:/pkg/wazuh/src# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

```

### PR DESCRIPTION
**Pull request by Dwordcito**
|Related issue|
|---|
|Closes #6647|

# Evidence:

image

# RTR
image
image

### CODE REVIEW

File: src/data_provider/src/sysInfoLinux.cpp [hunk 1]
```diff
@@ -314,32 +314,67 @@ std::string SysInfo::getSerialNumber() const
...
+    if (it != systemInfo.end())
+    {
+        retVal = it->second;
+    }
+    return retVal;
 }
 
 int SysInfo::getCpuCores() const
 {
+    int retVal = 0;
```
Comment (tinachoB) [inline src/data_provider/src/sysInfoLinux.cpp:330]: Please, use {} initialization

File: src/data_provider/src/sysInfoLinux.cpp [hunk 2]
```diff
@@ -314,32 +314,67 @@ std::string SysInfo::getSerialNumber() const
...
+    {
+        retVal = std::stoi(it->second) + 1;
+    }
+
+    return retVal;
 }
 
 int SysInfo::getCpuMHz() const
 {
+    int retVal = 0;
```
Comment (tinachoB) [inline src/data_provider/src/sysInfoLinux.cpp:344]: Ditto

**Review by tinachoB — CHANGES_REQUESTED** [review]

**Review by konangc87 — APPROVED** [review]

**Review by tinachoB — APPROVED** [review]
LGTM!
