### PR TITLE
Fix bug in fim_db_remove_path

### LINKED ISSUE #11743: Fix bug on fim_db_remove_path function inside file.cpp interface
|Wazuh version|Component|
|---|---|
| 4.4.0+| Wazuh FIM |

### Description

I found a bug in **fim_db_remove_path** function when execute this function the test detect an exception with this message  `dbEngine: Invalid information provided for statement creation.`. Also I can collect the error message which is:

`<std::_Function_handler<void(modules_log_level_t, const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&), FIMDB::init(unsigned int, unsigned int, fim_sync_callback_t, logging_callback_t, std::shared_ptr<DBSync>, std::shared_ptr<RemoteSync>)::<lambda(modules_log_level_t, const string&)> >::_M_invoke(const std::_Any_data &, modules_log_level_t &&, const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > &)>:	endbr64)`

#### Steps to reproduce:

1. Compile wazuh with tests flag
2. Execute component tests

#### Actual behavior:
The TestFimDBRemovePath, TestFimDBGetCountFileInode and TestFimDBGetCountFileEntry test is failing

#### Expected behavior:
The TestFimDBRemovePath, TestFimDBGetCountFileInode and TestFimDBGetCountFileEntry   must pass

#### Tip:
This issue can be inside removeFromDB in `fimDBHelper.hpp` file

### PR DESCRIPTION
**Pull request by FrancoRivero**
|EPIC|Component|
|---|---|
| https://github.com/wazuh/wazuh/issues/9103 | FIM |

### Description

The bug was found how to build the json to delete a file from database. This was fixed in current pull-request.

## Tests

- Compilation without warnings in every supported platform
  - [x] Linux
  - [x] Windows
  - [x] MAC OS X
- [x] Unit tests passed
- [x] Review logs syntax and correct language

- Memory tests for Linux
  - [x] Scan-build report
  - [x] Valgrind (memcheck and descriptor leaks check)
  - [x] cppcheck (static code analysis)
  - [x] Coverage (unit tests coverage code)
  - [x] Sformat (code style)

Closes
#11743

### CODE REVIEW

File: src/syscheckd/db/src/file.cpp [hunk 1]
```diff
@@ -110,7 +110,8 @@ FIMDBErrorCode fim_db_remove_path(const char* path)
     {
         try
         {
-            const auto removeFileCondition { std::string("WHERE path=") + std::string(path) };
+            nlohmann::json removeFileCondition;
+            removeFileCondition["path"] = std::string(path);
```
Comment (Dwordcito) [inline src/syscheckd/db/src/file.cpp:114]: is std::string needed ?
```suggestion
            removeFileCondition["path"] = path;
```

Comment (FrancoRivero) [reply src/syscheckd/db/src/file.cpp:114]: You are right ! This is a redundancy, I am changing it

**Review by Dwordcito — APPROVED** [review]

**Review by Dwordcito — APPROVED** [review]
