### PR TITLE
Content Manager - Improve downloaded hash file update mechanism

### LINKED ISSUE #22526: CTI OfflineDownloader is unable to recover from bad state
## Description
While performing this investigation:
- https://github.com/wazuh/wazuh/issues/21663

It was found that when the offline downloader is stopped while the content is being processed, it will fail to re-process the same content, as it has identified that it was already processed (hash has been updated)

- Processing stopped while in progress
```
wazuh-modulesd:content-updater:offlineDownloader.hpp:183 handleRequest : OfflineDownloader - Starting process
wazuh-modulesd:content-updater:offlineDownloader.hpp:66 copyFile : Copying file from 'file:///home/sebas/Downloads/198737_1697810206.zip' into 'queue/vd_updater/tmp/downloads/198737_1697810206.zip'
wazuh-modulesd:content-updater:zipDecompressor.hpp:74 handleRequest : ZipDecompressor - Starting process
wazuh-modulesd:content-updater:zipDecompressor.hpp:49 decompress : Decompressing 'queue/vd_updater/tmp/downloads/198737_1697810206.zip' into 'queue/vd_updater/tmp/contents'
Error modifying FD from interface.
wazuh-modulesd:content-updater:pubSubPublisher.hpp:61 handleRequest : PubSubPublisher - Starting process
wazuh-modulesd:content-updater:pubSubPublisher.hpp:42 publish : Data to be published: '{"offset":0,"paths":["queue/vd_updater/tmp/contents/vulnerabilities_cti-wazuh-vulnerabilities_198737_1697810206.json"],"stageStatus":[{"stage":"OfflineDownloader","status":"ok"},{"stage":"ZipDecompressor","status":"ok"}],"type":"raw"}'
wazuh-modulesd:content-updater:pubSubPublisher.hpp:45 publish : Data published
wazuh-modulesd:content-updater:skipStep.hpp:48 handleRequest : SkipStep - Starting process
wazuh-modulesd:content-updater:cleanUpContent.hpp:63 handleRequest : CleanUpContent - Starting process
wazuh-modulesd:vulnerability-scanner:databaseFeedManager.hpp:330 operator() : Processing message
wazuh-modulesd:vulnerability-scanner:databaseFeedManager.hpp:210 processMessage : Processing file: queue/vd_updater/tmp/contents/vulnerabilities_cti-wazuh-vulnerabilities_198737_1697810206.json
wazuh-modulesd:content-updater:action.hpp:235 runAction : Action for 'vulnerability_feed_manager' finished
wazuh-modulesd:vulnerability-scanner:databaseFeedManager.hpp:232 processMessage : Processing line: 1
indexer-connector:indexerConnector.cpp:204 operator() : Error initializing IndexerConnector for index 'wazuh-states-vulnerabilities': Failed to initialize template for index 'wazuh-states-vulnerabilities'. Error: Failed to initialize template for index 'wazuh-states-vulnerabilities'. Error: Couldn't connect to server. Retrying in 4 seconds. Maximum wait time: 60 seconds.
wazuh-modulesd:vulnerability-scanner:databaseFeedManager.hpp:232 processMessage : Processing line: 1001
wazuh-modulesd:vulnerability-scanner:databaseFeedManager.hpp:232 processMessage : Processing line: 2001
wazuh-modulesd:vulnerability-scanner:databaseFeedManager.hpp:232 processMessage : Processing line: 3001
wazuh-modulesd:vulnerability-scanner:scanOrchestrator.hpp:117 TScanOrchestrator : Timeout waiting for DB response, Using the hostname by fallback.
wazuh-modulesd:vulnerability-scanner:databaseFeedManager.hpp:232 processMessage : Processing line: 4001
wazuh-modulesd:vulnerability-scanner:vulnerabilityScannerFacade.cpp:590 start : Vulnerability scanner module started
indexer-connector:indexerConnector.cpp:204 operator() : Error initializing IndexerConnector for index 'wazuh-states-vulnerabilities': Failed to initialize template for index 'wazuh-states-vulnerabilities'. Error: Failed to initialize template for index 'wazuh-states-vulnerabilities'. Error: Couldn't connect to server. Retrying in 8 seconds. Maximum wait time: 60 seconds.
wazuh-modulesd:vulnerability-scanner:databaseFeedManager.hpp:232 processMessage : Processing line: 5001
^C
```

- New execution doesn't process the file
```
wazuh-modulesd:content-updater:action.hpp:224 runAction : Action for 'vulnerability_feed_manager' started
wazuh-modulesd:content-updater:actionOrchestrator.hpp:158 runContentUpdate : Running 'vulnerability_feed_manager' content update
wazuh-modulesd:content-updater:offlineDownloader.hpp:183 handleRequest : OfflineDownloader - Starting process
wazuh-modulesd:content-updater:offlineDownloader.hpp:66 copyFile : Copying file from 'file:///home/sebas/Downloads/198737_1697810206.zip' into 'queue/vd_updater/tmp/downloads/198737_1697810206.zip'
wazuh-modulesd:content-updater:offlineDownloader.hpp:160 download : File 'queue/vd_updater/tmp/downloads/198737_1697810206.zip' didn't change from last download so it won't be published
wazuh-modulesd:content-updater:zipDecompressor.hpp:74 handleRequest : ZipDecompressor - Starting process
wazuh-modulesd:content-updater:pubSubPublisher.hpp:61 handleRequest : PubSubPublisher - Starting process
wazuh-modulesd:content-updater:pubSubPublisher.hpp:49 publish : No data to publish
wazuh-modulesd:content-updater:skipStep.hpp:48 handleRequest : SkipStep - Starting process
wazuh-modulesd:content-updater:cleanUpContent.hpp:63 handleRequest : CleanUpContent - Starting process
wazuh-modulesd:content-updater:action.hpp:235 runAction : Action for 'vulnerability_feed_manager' finished
Error modifying FD from interface.
indexer-connector:indexerConnector.cpp:204 operator() : Error initializing IndexerConnector for index 'wazuh-states-vulnerabilities': Failed to initialize template for index 'wazuh-states-vulnerabilities'. Error: Failed to initialize template for index 'wazuh-states-vulnerabilities'. Error: Couldn't connect to server. Retrying in 4 seconds. Maximum wait time: 60 seconds.
indexer-connector:indexerConnector.cpp:204 operator() : Error initializing IndexerConnector for index 'wazuh-states-vulnerabilities': Failed to initialize template for index 'wazuh-states-vulnerabilities'. Error: Failed to initialize template for index 'wazuh-states-vulnerabilities'. Error: Couldn't connect to server. Retrying in 8 seconds. Maximum wait time: 60 seconds.
wazuh-modulesd:vulnerability-scanner:scanOrchestrator.hpp:117 TScanOrchestrator : Timeout waiting for DB response, Using the hostname by fallback.
wazuh-modulesd:vulnerability-scanner:vulnerabilityScannerFacade.cpp:590 start : Vulnerability scanner module started
indexer-connector:indexerConnector.cpp:204 operator() : Error initializing IndexerConnector for index 'wazuh-states-vulnerabilities': Failed to initialize template for index 'wazuh-states-vulnerabilities'. Error: Failed to initialize template for index 'wazuh-states-vulnerabilities'. Error: Couldn't connect to server. Retrying in 16 seconds. Maximum wait time: 60 seconds.
indexer-connector:indexerConnector.cpp:204 operator() : Error initializing IndexerConnector for index 'wazuh-states-vulnerabilities': Failed to initialize template for index 'wazuh-states-vulnerabilities'. Error: Failed to initialize template for index 'wazuh-states-vulnerabilities'. Error: Couldn't connect to server. Retrying in 32 seconds. Maximum wait time: 60 seconds.
indexer-connector:indexerConnector.cpp:204 operator() : Error initializing IndexerConnector for index 'wazuh-states-vulnerabilities': No available server. Retrying in 60 seconds. Maximum wait time: 60 seconds.
```

## Expected behaviour
The same content is re-ingested when the processing fails at some point

## Step to reproduce
- Configure the scanner testtool to use the offline downloader
```json
{
  "vulnerability-detection": {
      "enabled": "yes",
      "index-status": "yes",
      "cti-url": "file:///home/sebas/Downloads/198737_1697810206.zip",
      "offline-url": "file:///home/sebas/Downloads/198737_1697810206.zip",
      "managerNodeName": "wazuh-manager",
      "managerDisabledScan": 1
  },
  "indexer": {
      "enabled": "yes",
      "hosts": [
          "https://0.0.0.0:9200"
      ],
      "username": "admin",
      "password": "admin",
      "ssl": {
          "certificate_authorities": [
              "/home/dwordcito/Development/wazuh/src/root-ca.pem"
          ],
          "certificate": "/home/dwordcito/Development/wazuh/src/node-1.pem",
          "key": "/home/dwordcito/Development/wazuh/src/node-1-key.pem"
        }
  }
}
```
- Run the testtool with the following command:
```
BINARY="./src/build/wazuh_modules/vulnerability_scanner/testtool/scanner/vd_scanner_testtool"
CONFIG="src/wazuh_modules/vulnerability_scanner/testtool/scanner/config.json"
TEMPLATE="src/wazuh_modules/vulnerability_scanner/indexer/template/legacy-template.json"

"${BINARY}" -d -c "${CONFIG}" -t "${TEMPLATE}
```
- Stop the tool while it's processing
- Re-run the testool

## DoD
- [x] Issue has been solved
- [x] Tests were added

### PR DESCRIPTION
**Pull request by tsarquis88**
|Related issue|
|---|
| Closes #22526 |

## Description

This PR improves how the Content Manager stores the last downloaded file hash, used to avoid redundant processing of files.

Change log:
- Modify file downloaders to not write the file hash in the context.
- Modify file action orchestrator to not write the file hash in the database on every execution.
- Create endpoint in the ondemand content manager to update the file hash on demand.
- Improve how the orchestration config is passed from the ondemand manager to the action orchestrator.
- Add/Adapt testing
- Modify the scanner to trigger the hash update.

#### Scanner testtool execution (happy path)

Config file:
```json
{
  "vulnerability-detection": {
      "enabled": "yes",
      "index-status": "yes",
      "cti-url": "file:///home/reduced_snapshot.zip",
      "offline-url": "file:///home/reduced_snapshot.zip",
      "managerNodeName": "wazuh-manager",
      "managerDisabledScan": 1
  },
  "indexer": {
      "enabled": "yes",
      "hosts": [
          "https://0.0.0.0:9200"
      ],
      "username": "admin",
      "password": "admin",
      "ssl": {
          "certificate_authorities": [
              "/home/dwordcito/Development/wazuh/src/root-ca.pem"
          ],
          "certificate": "/home/dwordcito/Development/wazuh/src/node-1.pem",
          "key": "/home/dwordcito/Development/wazuh/src/node-1-key.pem"
        }
  }
}
```
> Note: `reduced_snapshot.zip` is a zip file containing a snapshot with only 3500 lines.

Execution and output:
<details><summary>Output</summary>

```bash
# LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libasan.so.6 ./vd_scanner_testtool -c config.json -t /home/wazuh-dev-22526-content-manager-improve-hash-update-mechanism/src/wazuh_modules/vulnerability_scanner/indexer/template/index-template.json -d
Failed to set socket options
Failed to set socket options
Failed to set socket options
Failed to set socket options
Failed to set socket options
Failed to set socket options
Failed to set socket options
Failed to set socket options
Failed to set socket options
Failed to set socket options
indexer-connector:indexerConnector.cpp:93 IndexerConnector : No username and password found in the keystore, using default values.
indexer-connector:indexerConnector.cpp:204 operator() : Error initializing IndexerConnector for index 'wazuh-states-vulnerabilities': Failed to initialize template for index 'wazuh-states-vulnerabilities'. Error: Failed to initialize template for index 'wazuh-states-vulnerabilities'. Error: Couldn't connect to server. Retrying in 2 seconds. Maximum wait time: 60 seconds.
indexer-connector:indexerConnector.cpp:204 operator() : Error initializing IndexerConnector for index 'wazuh-states-vulnerabilities': Failed to initialize template for index 'wazuh-states-vulnerabilities'. Error: Failed to initialize template for index 'wazuh-states-vulnerabilities'. Error: Couldn't connect to server. Retrying in 4 seconds. Maximum wait time: 60 seconds.
indexer-connector:indexerConnector.cpp:204 operator() : Error initializing IndexerConnector for index 'wazuh-states-vulnerabilities': Failed to initialize template for index 'wazuh-states-vulnerabilities'. Error: Failed to initialize template for index 'wazuh-states-vulnerabilities'. Error: Couldn't connect to server. Retrying in 8 seconds. Maximum wait time: 60 seconds.
indexer-connector:indexerConnector.cpp:204 operator() : Error initializing IndexerConnector for index 'wazuh-states-vulnerabilities': Failed to initialize template for index 'wazuh-states-vulnerabilities'. Error: Failed to initialize template for index 'wazuh-states-vulnerabilities'. Error: Couldn't connect to server. Retrying in 16 seconds. Maximum wait time: 60 seconds.
indexer-connector:indexerConnector.cpp:204 operator() : Error initializing IndexerConnector for index 'wazuh-states-vulnerabilities': Failed to initialize template for index 'wazuh-states-vulnerabilities'. Error: Failed to initialize template for index 'wazuh-states-vulnerabilities'. Error: Couldn't connect to server. Retrying in 32 seconds. Maximum wait time: 60 seconds.
Failed to set socket options
Failed to set socket options
wazuh-modulesd:content-updater:actionOrchestrator.hpp:79 ActionOrchestrator : Creating 'vulnerability_feed_manager' Content Updater orchestration
wazuh-modulesd:content-updater:executionContext.hpp:202 handleRequest : ExecutionContext - Starting process
wazuh-modulesd:content-updater:executionContext.hpp:184 createOutputFolder : Creating output folders at 'queue/vd_updater/tmp'
wazuh-modulesd:content-updater:factoryContentUpdater.hpp:44 create : FactoryContentUpdater - Starting process
wazuh-modulesd:content-updater:factoryDownloader.hpp:46 create : Creating 'offline' downloader
wazuh-modulesd:content-updater:factoryDecompressor.hpp:73 create : Creating 'zip' decompressor
wazuh-modulesd:content-updater:factoryVersionUpdater.hpp:41 create : Creating 'false' version updater
wazuh-modulesd:content-updater:factoryCleaner.hpp:41 create : Content cleaner created
wazuh-modulesd:content-updater:actionOrchestrator.hpp:89 ActionOrchestrator : Content updater orchestration created
wazuh-modulesd:content-updater:action.hpp:126 runActionScheduled : Starting scheduled action for 'vulnerability_feed_manager'
wazuh-modulesd:content-updater:action.hpp:218 runAction : Action for 'vulnerability_feed_manager' started
wazuh-modulesd:content-updater:actionOrchestrator.hpp:207 runContentUpdate : Running 'vulnerability_feed_manager' content update
wazuh-modulesd:content-updater:offlineDownloader.hpp:181 handleRequest : OfflineDownloader - Starting process
wazuh-modulesd:content-updater:offlineDownloader.hpp:66 copyFile : Copying file from 'file:///home/reduced_snapshot.zip' into 'queue/vd_updater/tmp/downloads/reduced_snapshot.zip'
wazuh-modulesd:content-updater:zipDecompressor.hpp:74 handleRequest : ZipDecompressor - Starting process
wazuh-modulesd:content-updater:zipDecompressor.hpp:49 decompress : Decompressing 'queue/vd_updater/tmp/downloads/reduced_snapshot.zip' into 'queue/vd_updater/tmp/contents'
wazuh-modulesd:content-updater:pubSubPublisher.hpp:61 handleRequest : PubSubPublisher - Starting process
wazuh-modulesd:content-updater:pubSubPublisher.hpp:42 publish : Data to be published: '{"fileMetadata":{"hash":"8ae3941827f4e893e09c80b93b0d28ad18ed3011"},"offset":0,"paths":["queue/vd_updater/tmp/contents/reduced_snapshot.json"],"stageStatus":[{"stage":"OfflineDownloader","status":"ok"},{"stage":"ZipDecompressor","status":"ok"}],"type":"raw"}'
wazuh-modulesd:content-updater:pubSubPublisher.hpp:45 publish : Data published
wazuh-modulesd:content-updater:skipStep.hpp:48 handleRequest : SkipStep - Starting process
wazuh-modulesd:content-updater:cleanUpContent.hpp:63 handleRequest : CleanUpContent - Starting process
wazuh-modulesd:vulnerability-scanner:databaseFeedManager.hpp:337 operator() : Processing message
wazuh-modulesd:content-updater:action.hpp:229 runAction : Action for 'vulnerability_feed_manager' finished
Error modifying FD from interface.
wazuh-modulesd:vulnerability-scanner:scanOrchestrator.hpp:117 TScanOrchestrator : Timeout waiting for DB response, Using the hostname by fallback.
wazuh-modulesd:vulnerability-scanner:vulnerabilityScannerFacade.cpp:594 start : Vulnerability scanner module started
indexer-connector:indexerConnector.cpp:204 operator() : Error initializing IndexerConnector for index 'wazuh-states-vulnerabilities': No available server. Retrying in 60 seconds. Maximum wait time: 60 seconds.
wazuh-modulesd:vulnerability-scanner:databaseFeedManager.hpp:210 processMessage : Processing file: queue/vd_updater/tmp/contents/reduced_snapshot.json
wazuh-modulesd:vulnerability-scanner:databaseFeedManager.hpp:232 processMessage : Processing line: 1
wazuh-modulesd:vulnerability-scanner:databaseFeedManager.hpp:232 processMessage : Processing line: 1001
wazuh-modulesd:vulnerability-scanner:databaseFeedManager.hpp:232 processMessage : Processing line: 2001
wazuh-modulesd:vulnerability-scanner:databaseFeedManager.hpp:232 processMessage : Processing line: 3001
wazuh-modulesd:content-updater:action.hpp:185 runActionOnDemand : Starting on-demand action for 'vulnerability_feed_manager'
wazuh-modulesd:content-updater:action.hpp:218 runAction : Action for 'vulnerability_feed_manager' started
wazuh-modulesd:content-updater:actionOrchestrator.hpp:163 runOffsetUpdate : Running 'vulnerability_feed_manager' offset update
wazuh-modulesd:content-updater:factoryOffsetUpdater.hpp:41 create : FactoryOffsetUpdater - Starting process
wazuh-modulesd:content-updater:updateCtiApiOffset.hpp:70 handleRequest : UpdateCtiApiOffset - Starting process
wazuh-modulesd:content-updater:updateCtiApiOffset.hpp:42 update : Updating offset with value: 0
wazuh-modulesd:content-updater:action.hpp:229 runAction : Action for 'vulnerability_feed_manager' finished
wazuh-modulesd:content-updater:action.hpp:185 runActionOnDemand : Starting on-demand action for 'vulnerability_feed_manager'
wazuh-modulesd:content-updater:action.hpp:218 runAction : Action for 'vulnerability_feed_manager' started
wazuh-modulesd:content-updater:actionOrchestrator.hpp:183 runFileHashUpdate : Running 'vulnerability_feed_manager' file hash update
wazuh-modulesd:content-updater:action.hpp:229 runAction : Action for 'vulnerability_feed_manager' finished
wazuh-modulesd:vulnerability-scanner:databaseFeedManager.hpp:365 operator() : Error processing message: Vendor map can not be found in DB.
wazuh-modulesd:content-updater:action.hpp:185 runActionOnDemand : Starting on-demand action for 'vulnerability_feed_manager'
wazuh-modulesd:content-updater:action.hpp:218 runAction : Action for 'vulnerability_feed_manager' started
wazuh-modulesd:content-updater:actionOrchestrator.hpp:207 runContentUpdate : Running 'vulnerability_feed_manager' content update
wazuh-modulesd:content-updater:offlineDownloader.hpp:181 handleRequest : OfflineDownloader - Starting process
wazuh-modulesd:content-updater:offlineDownloader.hpp:66 copyFile : Copying file from 'file:///home/reduced_snapshot.zip' into 'queue/vd_updater/tmp/downloads/reduced_snapshot.zip'
wazuh-modulesd:content-updater:offlineDownloader.hpp:158 download : File 'queue/vd_updater/tmp/downloads/reduced_snapshot.zip' didn't change from last download so it won't be published
wazuh-modulesd:content-updater:zipDecompressor.hpp:74 handleRequest : ZipDecompressor - Starting process
wazuh-modulesd:content-updater:pubSubPublisher.hpp:61 handleRequest : PubSubPublisher - Starting process
wazuh-modulesd:content-updater:pubSubPublisher.hpp:49 publish : No data to publish
wazuh-modulesd:content-updater:skipStep.hpp:48 handleRequest : SkipStep - Starting process
wazuh-modulesd:content-updater:cleanUpContent.hpp:63 handleRequest : CleanUpContent - Starting process
wazuh-modulesd:content-updater:action.hpp:229 runAction : Action for 'vulnerability_feed_manager' finished
```
</details>

Key logs:
- First CM execution (snapshot content published)
```
wazuh-modulesd:content-updater:pubSubPublisher.hpp:42 publish : Data to be published: '{"fileMetadata":{"hash":"8ae3941827f4e893e09c80b93b0d28ad18ed3011"},"offset":0,"paths":["queue/vd_updater/tmp/contents/reduced_snapshot.json"],"stageStatus":[{"stage":"OfflineDownloader","status":"ok"},{"stage":"ZipDecompressor","status":"ok"}],"type":"raw"}'
```
- VD processing:
```
wazuh-modulesd:vulnerability-scanner:databaseFeedManager.hpp:210 processMessage : Processing file: queue/vd_updater/tmp/contents/reduced_snapshot.json
wazuh-modulesd:vulnerability-scanner:databaseFeedManager.hpp:232 processMessage : Processing line: 1
wazuh-modulesd:vulnerability-scanner:databaseFeedManager.hpp:232 processMessage : Processing line: 1001
wazuh-modulesd:vulnerability-scanner:databaseFeedManager.hpp:232 processMessage : Processing line: 2001
wazuh-modulesd:vulnerability-scanner:databaseFeedManager.hpp:232 processMessage : Processing line: 3001
```
- VD updating offset and hash:
```
wazuh-modulesd:content-updater:action.hpp:218 runAction : Action for 'vulnerability_feed_manager' started
wazuh-modulesd:content-updater:actionOrchestrator.hpp:163 runOffsetUpdate : Running 'vulnerability_feed_manager' offset update
wazuh-modulesd:content-updater:factoryOffsetUpdater.hpp:41 create : FactoryOffsetUpdater - Starting process
wazuh-modulesd:content-updater:updateCtiApiOffset.hpp:70 handleRequest : UpdateCtiApiOffset - Starting process
wazuh-modulesd:content-updater:updateCtiApiOffset.hpp:42 update : Updating offset with value: 0
wazuh-modulesd:content-updater:action.hpp:229 runAction : Action for 'vulnerability_feed_manager' finished
wazuh-modulesd:content-updater:action.hpp:185 runActionOnDemand : Starting on-demand action for 'vulnerability_feed_manager'
wazuh-modulesd:content-updater:action.hpp:218 runAction : Action for 'vulnerability_feed_manager' started
wazuh-modulesd:content-updater:actionOrchestrator.hpp:183 runFileHashUpdate : Running 'vulnerability_feed_manager' file hash update
wazuh-modulesd:content-updater:action.hpp:229 runAction : Action for 'vulnerability_feed_manager' finished
```
- Second CM execution (content is not published)
```
wazuh-modulesd:content-updater:offlineDownloader.hpp:158 download : File 'queue/vd_updater/tmp/downloads/reduced_snapshot.zip' didn't change from last download so it won't be published
```

#### Scanner testtool execution (error recovery)

A forced exception was inserted in the database feed manager when a line is to be processed (just once, in the second try, the content is processed without errors). On this way, we can see how the scanner recovers from this error and the content manager re-sends the content file.

Config: The same as above.

Execution and output:
<details><summary>Output</summary>

```bash
# LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libasan.so.6 ./vd_scanner_testtool -c config.json -t /home/wazuh-dev-22526-content-manager-improve-hash-update-mechanism/src/wazuh_modules/vulnerability_scanner/indexer/template/index-template.json -d
Failed to set socket options
Failed to set socket options
Failed to set socket options
Failed to set socket options
Failed to set socket options
Failed to set socket options
Failed to set socket options
Failed to set socket options
Failed to set socket options
Failed to set socket options
indexer-connector:indexerConnector.cpp:93 IndexerConnector : No username and password found in the keystore, using default values.
indexer-connector:indexerConnector.cpp:204 operator() : Error initializing IndexerConnector for index 'wazuh-states-vulnerabilities': Failed to initialize template for index 'wazuh-states-vulnerabilities'. Error: Failed to initialize template for index 'wazuh-states-vulnerabilities'. Error: Couldn't connect to server. Retrying in 2 seconds. Maximum wait time: 60 seconds.
indexer-connector:indexerConnector.cpp:204 operator() : Error initializing IndexerConnector for index 'wazuh-states-vulnerabilities': Failed to initialize template for index 'wazuh-states-vulnerabilities'. Error: Failed to initialize template for index 'wazuh-states-vulnerabilities'. Error: Couldn't connect to server. Retrying in 4 seconds. Maximum wait time: 60 seconds.
indexer-connector:indexerConnector.cpp:204 operator() : Error initializing IndexerConnector for index 'wazuh-states-vulnerabilities': Failed to initialize template for index 'wazuh-states-vulnerabilities'. Error: Failed to initialize template for index 'wazuh-states-vulnerabilities'. Error: Couldn't connect to server. Retrying in 8 seconds. Maximum wait time: 60 seconds.
indexer-connector:indexerConnector.cpp:204 operator() : Error initializing IndexerConnector for index 'wazuh-states-vulnerabilities': Failed to initialize template for index 'wazuh-states-vulnerabilities'. Error: Failed to initialize template for index 'wazuh-states-vulnerabilities'. Error: Couldn't connect to server. Retrying in 16 seconds. Maximum wait time: 60 seconds.
Failed to set socket options
Failed to set socket options
wazuh-modulesd:content-updater:actionOrchestrator.hpp:79 ActionOrchestrator : Creating 'vulnerability_feed_manager' Content Updater orchestration
wazuh-modulesd:content-updater:executionContext.hpp:202 handleRequest : ExecutionContext - Starting process
indexer-connector:indexerConnector.cpp:204 operator() : Error initializing IndexerConnector for index 'wazuh-states-vulnerabilities': Failed to initialize template for index 'wazuh-states-vulnerabilities'. Error: Failed to initialize template for index 'wazuh-states-vulnerabilities'. Error: Couldn't connect to server. Retrying in 32 seconds. Maximum wait time: 60 seconds.
wazuh-modulesd:content-updater:executionContext.hpp:184 createOutputFolder : Creating output folders at 'queue/vd_updater/tmp'
wazuh-modulesd:content-updater:factoryContentUpdater.hpp:44 create : FactoryContentUpdater - Starting process
wazuh-modulesd:content-updater:factoryDownloader.hpp:46 create : Creating 'offline' downloader
wazuh-modulesd:content-updater:factoryDecompressor.hpp:73 create : Creating 'zip' decompressor
wazuh-modulesd:content-updater:factoryVersionUpdater.hpp:41 create : Creating 'false' version updater
wazuh-modulesd:content-updater:factoryCleaner.hpp:41 create : Content cleaner created
wazuh-modulesd:content-updater:actionOrchestrator.hpp:89 ActionOrchestrator : Content updater orchestration created
wazuh-modulesd:content-updater:action.hpp:126 runActionScheduled : Starting scheduled action for 'vulnerability_feed_manager'
wazuh-modulesd:content-updater:action.hpp:218 runAction : Action for 'vulnerability_feed_manager' started
wazuh-modulesd:content-updater:actionOrchestrator.hpp:207 runContentUpdate : Running 'vulnerability_feed_manager' content update
wazuh-modulesd:content-updater:offlineDownloader.hpp:181 handleRequest : OfflineDownloader - Starting process
wazuh-modulesd:content-updater:offlineDownloader.hpp:66 copyFile : Copying file from 'file:///home/reduced_snapshot.zip' into 'queue/vd_updater/tmp/downloads/reduced_snapshot.zip'
wazuh-modulesd:content-updater:zipDecompressor.hpp:74 handleRequest : ZipDecompressor - Starting process
wazuh-modulesd:content-updater:zipDecompressor.hpp:49 decompress : Decompressing 'queue/vd_updater/tmp/downloads/reduced_snapshot.zip' into 'queue/vd_updater/tmp/contents'
wazuh-modulesd:content-updater:pubSubPublisher.hpp:61 handleRequest : PubSubPublisher - Starting process
wazuh-modulesd:content-updater:pubSubPublisher.hpp:42 publish : Data to be published: '{"fileMetadata":{"hash":"8ae3941827f4e893e09c80b93b0d28ad18ed3011"},"offset":0,"paths":["queue/vd_updater/tmp/contents/reduced_snapshot.json"],"stageStatus":[{"stage":"OfflineDownloader","status":"ok"},{"stage":"ZipDecompressor","status":"ok"}],"type":"raw"}'
wazuh-modulesd:content-updater:pubSubPublisher.hpp:45 publish : Data published
wazuh-modulesd:content-updater:skipStep.hpp:48 handleRequest : SkipStep - Starting process
wazuh-modulesd:content-updater:cleanUpContent.hpp:63 handleRequest : CleanUpContent - Starting process
wazuh-modulesd:vulnerability-scanner:databaseFeedManager.hpp:345 operator() : Processing message
wazuh-modulesd:content-updater:action.hpp:229 runAction : Action for 'vulnerability_feed_manager' finished
Error modifying FD from interface.
wazuh-modulesd:vulnerability-scanner:scanOrchestrator.hpp:117 TScanOrchestrator : Timeout waiting for DB response, Using the hostname by fallback.
wazuh-modulesd:vulnerability-scanner:vulnerabilityScannerFacade.cpp:594 start : Vulnerability scanner module started
indexer-connector:indexerConnector.cpp:204 operator() : Error initializing IndexerConnector for index 'wazuh-states-vulnerabilities': No available server. Retrying in 60 seconds. Maximum wait time: 60 seconds.
wazuh-modulesd:vulnerability-scanner:databaseFeedManager.hpp:212 processMessage : Processing file: queue/vd_updater/tmp/contents/reduced_snapshot.json
wazuh-modulesd:vulnerability-scanner:databaseFeedManager.hpp:234 processMessage : Processing line: 1
wazuh-modulesd:vulnerability-scanner:databaseFeedManager.hpp:373 operator() : Error processing message: Forced exception while processing line!
wazuh-modulesd:content-updater:action.hpp:185 runActionOnDemand : Starting on-demand action for 'vulnerability_feed_manager'
wazuh-modulesd:content-updater:action.hpp:218 runAction : Action for 'vulnerability_feed_manager' started
wazuh-modulesd:content-updater:actionOrchestrator.hpp:207 runContentUpdate : Running 'vulnerability_feed_manager' content update
wazuh-modulesd:content-updater:offlineDownloader.hpp:181 handleRequest : OfflineDownloader - Starting process
wazuh-modulesd:content-updater:offlineDownloader.hpp:66 copyFile : Copying file from 'file:///home/reduced_snapshot.zip' into 'queue/vd_updater/tmp/downloads/reduced_snapshot.zip'
wazuh-modulesd:content-updater:zipDecompressor.hpp:74 handleRequest : ZipDecompressor - Starting process
wazuh-modulesd:content-updater:zipDecompressor.hpp:49 decompress : Decompressing 'queue/vd_updater/tmp/downloads/reduced_snapshot.zip' into 'queue/vd_updater/tmp/contents'
wazuh-modulesd:content-updater:pubSubPublisher.hpp:61 handleRequest : PubSubPublisher - Starting process
wazuh-modulesd:content-updater:pubSubPublisher.hpp:42 publish : Data to be published: '{"fileMetadata":{"hash":"8ae3941827f4e893e09c80b93b0d28ad18ed3011"},"offset":0,"paths":["queue/vd_updater/tmp/contents/reduced_snapshot.json"],"stageStatus":[{"stage":"OfflineDownloader","status":"ok"},{"stage":"ZipDecompressor","status":"ok"}],"type":"raw"}'
wazuh-modulesd:content-updater:pubSubPublisher.hpp:45 publish : Data published
wazuh-modulesd:content-updater:skipStep.hpp:48 handleRequest : SkipStep - Starting process
wazuh-modulesd:content-updater:cleanUpContent.hpp:63 handleRequest : CleanUpContent - Starting process
wazuh-modulesd:content-updater:action.hpp:229 runAction : Action for 'vulnerability_feed_manager' finished

wazuh-modulesd:vulnerability-scanner:databaseFeedManager.hpp:345 operator() : Processing message
wazuh-modulesd:vulnerability-scanner:databaseFeedManager.hpp:212 processMessage : Processing file: queue/vd_updater/tmp/contents/reduced_snapshot.json
wazuh-modulesd:vulnerability-scanner:databaseFeedManager.hpp:234 processMessage : Processing line: 1
wazuh-modulesd:vulnerability-scanner:databaseFeedManager.hpp:234 processMessage : Processing line: 1001
wazuh-modulesd:vulnerability-scanner:databaseFeedManager.hpp:234 processMessage : Processing line: 2001
wazuh-modulesd:vulnerability-scanner:databaseFeedManager.hpp:234 processMessage : Processing line: 3001
wazuh-modulesd:content-updater:action.hpp:185 runActionOnDemand : Starting on-demand action for 'vulnerability_feed_manager'
wazuh-modulesd:content-updater:action.hpp:218 runAction : Action for 'vulnerability_feed_manager' started
wazuh-modulesd:content-updater:actionOrchestrator.hpp:163 runOffsetUpdate : Running 'vulnerability_feed_manager' offset update
wazuh-modulesd:content-updater:factoryOffsetUpdater.hpp:41 create : FactoryOffsetUpdater - Starting process
wazuh-modulesd:content-updater:updateCtiApiOffset.hpp:70 handleRequest : UpdateCtiApiOffset - Starting process
wazuh-modulesd:content-updater:updateCtiApiOffset.hpp:42 update : Updating offset with value: 0
wazuh-modulesd:content-updater:action.hpp:229 runAction : Action for 'vulnerability_feed_manager' finished
wazuh-modulesd:content-updater:action.hpp:185 runActionOnDemand : Starting on-demand action for 'vulnerability_feed_manager'
wazuh-modulesd:content-updater:action.hpp:218 runAction : Action for 'vulnerability_feed_manager' started
wazuh-modulesd:content-updater:actionOrchestrator.hpp:183 runFileHashUpdate : Running 'vulnerability_feed_manager' file hash update
wazuh-modulesd:content-updater:action.hpp:229 runAction : Action for 'vulnerability_feed_manager' finished
wazuh-modulesd:vulnerability-scanner:databaseFeedManager.hpp:373 operator() : Error processing message: Vendor map can not be found in DB.
wazuh-modulesd:content-updater:action.hpp:185 runActionOnDemand : Starting on-demand action for 'vulnerability_feed_manager'
wazuh-modulesd:content-updater:action.hpp:218 runAction : Action for 'vulnerability_feed_manager' started
wazuh-modulesd:content-updater:actionOrchestrator.hpp:207 runContentUpdate : Running 'vulnerability_feed_manager' content update
wazuh-modulesd:content-updater:offlineDownloader.hpp:181 handleRequest : OfflineDownloader - Starting process
wazuh-modulesd:content-updater:offlineDownloader.hpp:66 copyFile : Copying file from 'file:///home/reduced_snapshot.zip' into 'queue/vd_updater/tmp/downloads/reduced_snapshot.zip'
wazuh-modulesd:content-updater:offlineDownloader.hpp:158 download : File 'queue/vd_updater/tmp/downloads/reduced_snapshot.zip' didn't change from last download so it won't be published
wazuh-modulesd:content-updater:zipDecompressor.hpp:74 handleRequest : ZipDecompressor - Starting process
wazuh-modulesd:content-updater:pubSubPublisher.hpp:61 handleRequest : PubSubPublisher - Starting process
wazuh-modulesd:content-updater:pubSubPublisher.hpp:49 publish : No data to publish
wazuh-modulesd:content-updater:skipStep.hpp:48 handleRequest : SkipStep - Starting process
wazuh-modulesd:content-updater:cleanUpContent.hpp:63 handleRequest : CleanUpContent - Starting process
wazuh-modulesd:content-updater:action.hpp:229 runAction : Action for 'vulnerability_feed_manager' finished

wazuh-modulesd:content-updater:onDemandManager.cpp:177 stopServer : Server stopped
wazuh-modulesd:content-updater:action.hpp:146 stopActionScheduler : Scheduler stopped for 'vulnerability_feed_manager'
Error removing FD from interface.
```
</details>

Key logs:
- CM publishes for the first time
```
wazuh-modulesd:content-updater:pubSubPublisher.hpp:42 publish : Data to be published: '{"fileMetadata":{"hash":"8ae3941827f4e893e09c80b93b0d28ad18ed3011"},"offset":0,"paths":["queue/vd_updater/tmp/contents/reduced_snapshot.json"],"stageStatus":[{"stage":"OfflineDownloader","status":"ok"},{"stage":"ZipDecompressor","status":"ok"}],"type":"raw"}'
wazuh-modulesd:content-updater:pubSubPublisher.hpp:45 publish : Data published
```
- Scanner starts content processing and a forced exception is thrown
```
wazuh-modulesd:vulnerability-scanner:databaseFeedManager.hpp:210 processMessage : Processing file: queue/vd_updater/tmp/contents/reduced_snapshot.json
wazuh-modulesd:vulnerability-scanner:databaseFeedManager.hpp:232 processMessage : Processing line: 1
wazuh-modulesd:vulnerability-scanner:databaseFeedManager.hpp:367 operator() : Error processing message: Forced exception while processing line!
```
- The CM re-sends the content
- The Scanner process the full content without errors
```
wazuh-modulesd:vulnerability-scanner:databaseFeedManager.hpp:345 operator() : Processing message
wazuh-modulesd:vulnerability-scanner:databaseFeedManager.hpp:212 processMessage : Processing file: queue/vd_updater/tmp/contents/reduced_snapshot.json
wazuh-modulesd:vulnerability-scanner:databaseFeedManager.hpp:234 processMessage : Processing line: 1
wazuh-modulesd:vulnerability-scanner:databaseFeedManager.hpp:234 processMessage : Processing line: 1001
wazuh-modulesd:vulnerability-scanner:databaseFeedManager.hpp:234 processMessage : Processing line: 2001
wazuh-modulesd:vulnerability-scanner:databaseFeedManager.hpp:234 processMessage : Processing line: 3001
```
- Scanner triggers hash update
```
wazuh-modulesd:content-updater:action.hpp:218 runAction : Action for 'vulnerability_feed_manager' started
wazuh-modulesd:content-updater:actionOrchestrator.hpp:183 runFileHashUpdate : Running 'vulnerability_feed_manager' file hash update
wazuh-modulesd:content-updater:action.hpp:229 runAction : Action for 'vulnerability_feed_manager' finished
```
- CM realizes the file was already processed so is no longer published
```
wazuh-modulesd:content-updater:offlineDownloader.hpp:158 download : File 'queue/vd_updater/tmp/downloads/reduced_snapshot.zip' didn't change from last download so it won't be published
```

### CODE REVIEW

File: src/shared_modules/content_manager/src/actionOrchestrator.hpp [hunk 1]
```diff
@@ -36,7 +36,25 @@ class ActionOrchestrator final
...
+
+    /**
+     * @brief Struct containing the necessary members to execute the orchestrations.
+     *
+     */
+    struct UpdateData
+    {
+        UpdateType type = UpdateType::CONTENT; ///< Orchestration update type.
+        int offset = -1;                       ///< Offset value used in the update.
+        std::string fileHash;                  ///< Hash value used in the update.
```
Comment (jftuduri) [inline src/shared_modules/content_manager/src/actionOrchestrator.hpp:51]: I think the documentation could be improved with the valid values and what each one means (-1, 0, >0, etc)

File: src/shared_modules/content_manager/src/actionOrchestrator.hpp [hunk 2]
```diff
@@ -79,25 +97,32 @@ class ActionOrchestrator final
     /**
      * @brief Run the content updater orchestration.
      *
-     * @param offset Offset value from the on-demand request. If equals zero and \p type is CONTENT, the current
-     * offset will be reset to zero. If \p type is OFFSET, this value will be used to perform the offset update.
-     * @param type Type of update the orchestrator should perform.
+     * @param updateData Update orchestration data.
+     *
+     * @note If the \p updateData offset equals zero and the \p updateData type is CONTENT, the current offset will be
+     * reset to zero. If \p updateData type is OFFSET, this value will be used to perform the offset update.
```
Comment (jftuduri) [inline src/shared_modules/content_manager/src/actionOrchestrator.hpp:103]: I think this kind of documentation would fit better in the `UpdateData` definition

File: src/shared_modules/content_manager/src/actionOrchestrator.hpp [hunk 3]
```diff
@@ -36,7 +36,25 @@ class ActionOrchestrator final
...
+    };
+
+    /**
+     * @brief Struct containing the necessary members to execute the orchestrations.
+     *
+     */
+    struct UpdateData
+    {
+        UpdateType type = UpdateType::CONTENT; ///< Orchestration update type.
+        int offset = -1;                       ///< Offset value used in the update.
```
[the remark this answers is not in the document]
Comment (tsarquis88) [reply src/shared_modules/content_manager/src/actionOrchestrator.hpp]: Fixed!

File: src/shared_modules/content_manager/src/actionOrchestrator.hpp (hunk 1 above)
Comment (tsarquis88) [reply src/shared_modules/content_manager/src/actionOrchestrator.hpp]: Yes. Done.

File: src/shared_modules/content_manager/src/actionOrchestrator.hpp (hunk 2 above)
Comment (tsarquis88) [reply src/shared_modules/content_manager/src/actionOrchestrator.hpp]: Moved.

File: src/shared_modules/content_manager/src/actionOrchestrator.hpp [hunk 4]
```diff
@@ -36,7 +36,31 @@ class ActionOrchestrator final
...
+    {
+        UpdateType type {UpdateType::CONTENT}; ///< Orchestration update type.
+        int offset {1};                        ///< Offset value used in the update.
+        std::string fileHash;                  ///< Hash value used in the update.
+
+        /**
+         * @brief Struct empty constructor.
+         *
+         */
+        UpdateData() {};
```
Comment (matias-braida) [inline src/shared_modules/content_manager/src/actionOrchestrator.hpp:63]: If the members of the struct have default values, then I think that the empty default constructor does not make much sense.
It could be removed. Or take another approach and do not set default values to the member fields and create a constructor where they must be set explicitly.

File: src/shared_modules/content_manager/tests/unit/offlineDownloader_test.cpp [hunk 5]
```diff
@@ -132,52 +136,10 @@ TEST_F(OfflineDownloaderTest, SkipFileProcessing)
...
     ASSERT_NO_THROW(OfflineDownloader(HTTPRequest::instance()).handleRequest(m_spUpdaterContext));
     EXPECT_EQ(m_spUpdaterContext->data, expectedData);
 }
 
-/**
- * @brief Tests two downloads one after the other. The file from the second download is different from the prior so the
- * output file gets overrided.
- *
- */
-TEST_F(OfflineDownloaderTest, TwoFileDownloadsOverrideOutput)
```
Comment (Damian-Mangold) [inline src/shared_modules/content_manager/tests/unit/offlineDownloader_test.cpp:147]: question: This test needs to be removed, if there is a possibility to fix it instead of removing it it would be ideal, as the functionality should still work.

**Review by matias-braida — COMMENTED** [review]
GJ

File: src/shared_modules/content_manager/src/actionOrchestrator.hpp (hunk 4 above)
Comment (jftuduri) [reply src/shared_modules/content_manager/src/actionOrchestrator.hpp:63]: To help enforce all the conditions, how about:
- Make a private constructor with all the parameters
- Add one static function for each type of update, check that all the parameters are valid before calling the constructor and returning the UpdateData object:
For example:
```
static UpdateData createHashUpdate(const std::string& hash) {
        if(hash.empty()){
         throw...
        }
        return UpdateData(UpdateType::FileHash, hash, -1);
    }
```

File: src/shared_modules/content_manager/src/action.hpp [hunk 6]
```diff
@@ -217,15 +213,13 @@ class Action final
     std::shared_ptr<ConditionSync> m_stopActionCondition;
     std::unique_ptr<ActionOrchestrator> m_orchestration;
 
-    void runAction(const ActionID id,
-                   const int offset = -1,
-                   const ActionOrchestrator::UpdateType type = ActionOrchestrator::UpdateType::CONTENT)
+    void runAction(const ActionID id, const ActionOrchestrator::UpdateData& updateData)
```
[the remark this answers is not in the document]
Comment (tsarquis88) [reply src/shared_modules/content_manager/src/action.hpp]: Yes. I removed the whole ActionID stuff!

File: src/shared_modules/content_manager/src/actionOrchestrator.hpp (hunk 4 above)
Comment (tsarquis88) [reply src/shared_modules/content_manager/src/actionOrchestrator.hpp]: So, I've chosen @jftuduri 's approach. Seems more secure than creating the struct directly, avoiding so the introduction of unwanted values.

File: src/wazuh_modules/vulnerability_scanner/src/databaseFeedManager/databaseFeedManager.hpp [hunk 7]
```diff
@@ -688,6 +695,31 @@ class TDatabaseFeedManager final : public Observer<nlohmann::json&>
...
     }
 
+    /**
+     * @brief Makes the Content Manager to update the last parsed file hash value so that redundant processing is
+     * avoided.
+     *
+     * @param topicName Topic name.
+     * @param fileHash Value of the hash to be used in the update.
+     */
+    void contentManagerUpdateHash(const std::string& topicName, const std::string& fileHash)
```
[the remark this answers is not in the document]
Comment (tsarquis88) [reply src/wazuh_modules/vulnerability_scanner/src/databaseFeedManager/databaseFeedManager.hpp]: Fixed.

File: src/shared_modules/content_manager/tests/unit/offlineDownloader_test.cpp (hunk 5 above)
Comment (tsarquis88) [reply src/shared_modules/content_manager/tests/unit/offlineDownloader_test.cpp:147]: Reverted and adapted!

**Review by jftuduri — APPROVED** [review]
GJ!

**Review by Damian-Mangold — APPROVED** [review]
Two consecutive executions, it can be observed that in the first execution the content is processed and the hash is stored, in the second execution the content is not sent because the hash does not change.

image

---
In the first run the content processing is cancelled, in the second run it is processed correctly and the hash is stored.

image

---
In the first execution the file is not sent because it is the same, the file is modified, it is identified that the hash changed then it is sent.
image
