### PR TITLE
Dynamic index naming

### LINKED ISSUE #26779: Dynamic index naming bug in Indexer Connector module
### Description:
A bug has been identified in the Wazuh-Engine's Indexer Connector module, which currently uses a static `$(date)` placeholder for indexing events in OpenSearch. This placeholder is only replaced with the actual date upon instantiation of the indexer connector. Consequently, if the indexer remains active across date changes, it incorrectly continues using the initial date, leading to events being sent to an outdated index. This issue requires a fix to ensure accurate and dynamic index naming aligned with the actual date of event handling.

### Objective:
To resolve the bug by enabling dynamic index naming in the Indexer Connector. Two potential solutions are proposed: extending the interface to allow specifying the index name per event or updating the placeholder dynamically during each bulk send operation to OpenSearch.

### Proposed Solutions:
1. **Parameter Addition to Publish Method**:
   - Enhance the `publish` method to accept an additional parameter specifying the target index name. This change would allow flexibility for the calling function to determine the index name dynamically at runtime (Desirable solution).

2. **Dynamic Placeholder Update During Bulk Operations**:
   - Modify the indexing functionality to update the `$(date)` placeholder dynamically each time events are bulk sent to OpenSearch. This would ensure that the index name reflects the actual date at the time of sending.

### Expected Outcome:
Both proposed solutions aim to rectify the index naming issue, ensuring that data is routed to the correct OpenSearch index based on real-time operational context. The chosen solution should align with Wazuh's operational requirements and technical constraints.

### DoD (Definition of Done):
- [x] A decision is made on which solution to implement based on a detailed analysis of pros and cons.
- [x] The chosen solution is implemented ensuring that the indexer connector dynamically names indices correctly.
- [x] Comprehensive testing is conducted to confirm that the fix addresses the issue without introducing new bugs.
- [x] Documentation is updated to reflect any changes in the indexer connector's operation or API.

### Impact:
Implementing this fix will prevent data misplacement issues in OpenSearch and ensure that Wazuh-Engine's telemetry data is accurately indexed and retrievable based on the correct temporal context. This is crucial for maintaining the integrity and usability of stored data in security monitoring and analysis scenarios.

### PR DESCRIPTION
**Pull request by pereyra-m**
|Related issue|
|---|
|Closes #26779|

## Description

This PR gives to the `indexerConnector` the capacity of dynamically change the name of the index it's publishing the events to. There are two mechanisms:
- If the event contains the key `indexName`, it'll be used
- If it doesn't, then the name used during the configuration will be used instead. The `%(date)` placeholder is replaced in each bulk

UT added.

## Tests

The manual tests can be seen at   https://github.com/wazuh/wazuh/issues/26779#issuecomment-2475131196

- Compilation without warnings in every supported platform
  - [x] Linux

### CODE REVIEW

File: src/engine/source/indexerconnector/src/indexerConnector.cpp [hunk 1]
```diff
@@ -218,16 +219,20 @@ IndexerConnector::IndexerConnector(const IndexerConnectorOptions& indexerConnect
                     continue;
                 }
 
+                const auto& finalIndexName = parsedData.contains("indexName")
```
Comment (GabrielEValenzuela) [inline src/engine/source/indexerconnector/src/indexerConnector.cpp:222]: I believe this field is not part of the ECS. It is metadata and should not be used to decide where an event will be indexed.

File: src/engine/source/indexerconnector/test/component/indexerConnector_test.cpp [hunk 2]
```diff
@@ -717,3 +717,85 @@ TEST_F(IndexerConnectorTest, PublishDatePlaceholder)
...
+ */
+TEST_F(IndexerConnectorTest, PublishDatePlaceholderIndexNameInRequest)
+{
+    // We create an index with the current date as part of the name.
+    std::string baseIndexName = std::string(INDEXER_NAME) + "_$(date)";
+    // We'll create two indexes name, one will have the date replaced and the other will have a custom string.
+    std::string indexName1 = baseIndexName;
+    base::utils::string::replaceAll(indexName1, "$(date)", base::utils::time::getCurrentDate("."));
+    std::string indexName2 = baseIndexName;
+    base::utils::string::replaceAll(indexName2, "$(date)", "custom_string");
```
Comment (GabrielEValenzuela) [inline src/engine/source/indexerconnector/test/component/indexerConnector_test.cpp:734]: Tests should validate that the `$(date)` placeholder replacement format is applied correctly.

**Review by GabrielEValenzuela — CHANGES_REQUESTED** [review]
# Testing 🔴 

## Setps

- Install provided package
- Run docker compuse up with Opensearch and Dashboard
- Clone Wazuh repository and install Python tools in virtual environment
- Create `file.yml`

<details><summary>file.yml</summary>

```yml
name: output/indexer/0

metadata:
  title: Indexer output event
  description: Output integrations events to wazuh-indexer
  compatibility: >
    This decoder has been tested on Wazuh version 5.0
  author:
    name: Wazuh, Inc.
    date: 2024/12/01

check: not_exists($wazuh.noIndexing) OR $wazuh.noIndexing == false

outputs:
  - wazuh-indexer:
      index: alerts
```

</details>

- Run `engine` and run the following commands

```console
wazuh-engine catalog -n system create output < file.yml
wazuh-engine catalog -n system get output
- output/file-output-integrations
- output/file-output-wazuh-core
- output/indexer

wazuh-engine router get
- name: default
  policy: policy/wazuh/0
  filter: filter/allow-all/0
  priority: 254
  policy_sync: UPDATED
  entry_status: ENABLED
  uptime: 598

*Sent a reload default if it's necessary
```

- Run test 

```console
engine-test add -i test -f syslog
engine-test run test
```

- Pass event

```json
{"timestamp":"2018-10-04T09:35:00.250560+0000","flow_id":112424506237238,"in_iface":"enp0s3","event_type":"alert","src_ip":"192.168.1.146","src_port":52340,"dest_ip":"89.160.20.112","dest_port":80,"proto":"TCP","tx_id":4,"alert":{"action":"allowed","gid":1,"signature_id":2013504,"rev":5,"signature":"ET POLICY GNU\/Linux APT User-Agent Outbound likely related to package management","category":"Not Suspicious Traffic","severity":3},"http":{"hostname":"archive.ubuntu.com","url":"\/ubuntu\/dists\/bionic-updates\/universe\/source\/by-hash\/SHA256\/56cfd9cc2efa61dff7428dddf921c3cd6047ab8e6484a7f1888e4c3f7252f1ef","http_user_agent":"Debian APT-HTTP\/1.3 (1.6.3ubuntu0.1)","http_method":"GET","protocol":"HTTP\/1.1","status":200,"length":2688},"app_proto":"http","flow":{"pkts_toserver":159,"pkts_toclient":253,"bytes_toserver":11679,"bytes_toclient":376452,"start":"2018-10-04T09:34:58.926006+0000"}}
```

- Default index OK

image

- Send event with `indexName`

```json
{"timestamp":"2018-10-04T09:35:00.250560+0000","indexName": "test-index-event-log","flow_id":112424506237238,"in_iface":"enp0s3", "event_type":"alert","src_ip":"192.168.1.146","src_port":52340,"dest_ip":"89.160.20.112","dest_port":80,"proto":"TCP","tx_id":4,"alert":{"action":"allowed","gid":1,"signature_id":2013504,"rev":5,"signature":"ET POLICY GNU\/Linux APT User-Agent Outbound likely related to package management","category":"Not Suspicious Traffic","severity":3},"http":{"hostname":"archive.ubuntu.com","url":"\/ubuntu\/dists\/bionic-updates\/universe\/source\/by-hash\/SHA256\/56cfd9cc2efa61dff7428dddf921c3cd6047ab8e6484a7f1888e4c3f7252f1ef","http_user_agent":"Debian APT-HTTP\/1.3 (1.6.3ubuntu0.1)","http_method":"GET","protocol":"HTTP\/1.1","status":200,"length":2688},"app_proto":"http","flow":{"pkts_toserver":159,"pkts_toclient":253,"bytes_toserver":11679,"bytes_toclient":376452,"start":"2018-10-04T09:34:58.926006+0000"}}
```

- No index was created

```plaintext
debug: Response: {"took":469,"errors":false,"items":[{"index":{"_index":"test-basic-index","_id":"fvfyRZMBpuAcrOu7gmY4","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":10,"_primary_term":1,"status":201}},{"index":{"_index":"test-basic-index","_id":"f_fyRZMBpuAcrOu7gmY4","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":11,"_primary_term":1,"status":201}}]}
```

File: src/engine/source/indexerconnector/src/indexerConnector.cpp (hunk 1 above)
Comment (pereyra-m) [reply src/engine/source/indexerconnector/src/indexerConnector.cpp:222]: > I believe this field is not part of the ECS

I thought that we could use it internally.

>  It is metadata and should not be used to decide where an event will be indexed.

It could be a feature, to allow the user define the index and not depend on the time the indexer pushes the event.
But I'll remove it.

File: src/engine/source/indexerconnector/test/component/indexerConnector_test.cpp (hunk 2 above)
Comment (pereyra-m) [reply src/engine/source/indexerconnector/test/component/indexerConnector_test.cpp:734]: That is verified inside the lambda.
But the test will change now that I'll remove part of the feature

**Comment by pereyra-m** [comment]
## Testing

I've used the steps shared by @GabrielEValenzuela to generate indexed alerts and test the feature.
I'll discard the testing of the `indexName` because we've decided to remove it.

After installing the provided package, I've started the `wazuh-engine`

```bash
root@94f23205d71a:/home# WENGINE_ICONNECTOR_HOSTS=https://wazuh.indexer:9200 WENGINE_ICONNECTOR_USERNAME=admin WENGINE_ICONNECTOR_PASSWORD=SecretPassword WENGINE_ICONNECTOR_CA=/etc/filebeat/certs/root-ca.pem WENGINE_ICONNECTOR_CERT=/etc/filebeat/certs/wazuh.indexer.pem WENGINE_ICONNECTOR_KEY=/etc/filebeat/certs/wazuh.indexer-key.pem WENGINE_ICONNECTOR_INDEX='test_date_index_$(date)' wazuh-engine server start
```

Then I started a Wazuh Indexer instance with the Docker repository, and verified the indexation changing the PC date

File: src/engine/source/indexerconnector/test/component/indexerConnector_test.cpp (hunk 2 above)
Comment (pereyra-m) [reply src/engine/source/indexerconnector/test/component/indexerConnector_test.cpp]: The new approach doesn't contain test because:
- The basic feature is already tested in previous tests
- To verify the change in the date, there are two options (and I'm not sure about any): I can templetize the `IndexerConnector` class to mock the `std::time` call or I can change the host date during the test

File: src/engine/source/indexerconnector/src/indexerConnector.cpp (hunk 1 above)
Comment (pereyra-m) [reply src/engine/source/indexerconnector/src/indexerConnector.cpp]: Now, the date is replaced in each bulk.

Comment (GabrielEValenzuela) [reply src/engine/source/indexerconnector/src/indexerConnector.cpp]: Great!

File: src/engine/source/indexerconnector/test/component/indexerConnector_test.cpp (hunk 2 above)
Comment (GabrielEValenzuela) [reply src/engine/source/indexerconnector/test/component/indexerConnector_test.cpp]: Thanks!

**Review by GabrielEValenzuela — APPROVED** [review]
I followed the steps described [here](https://github.com/wazuh/wazuh/pull/26868#pullrequestreview-2446507482)

With the last changes, and using `timedatectl` to change the date and running with 

```
WENGINE_ICONNECTOR_INDEX='test_date_index_$(date)' wazuh-engine server start
```

**Review by sebasfalcone — APPROVED** [review]
# Testing

- Insert 6 elements
> image

- Change date
- Insert 3 elements
> image
