### PR TITLE
7275 syscollector disabled issue

### LINKED ISSUE #7275: Syscollector disabled option not working
## Description

It was found in manual / exploratory testing that the module was not being disabled when the configuration is off.

Static code analysis was done, and it was found that the functionality is not provided.

this is solved, adding a code that skips the dll / so load in the main of the syscollector wmodule.

Take this approach.
image

## DoD
- [x] Modify wm_syscollector.c to skip dll/so load when configuration is disabled.
- [x] Manual testing 
- [ ] Analyze pytest case ? Ask QA team
- [x] PR / CI PASS

### PR DESCRIPTION
**Pull request by Dwordcito**
|Related issue|
|---|
|Closes #7275 |

It was found in manual / exploratory testing that the module was not being disabled when the configuration is off.

Static code analysis was done, and it was found that the functionality is not provided.

this is solved, adding a code that skips the dll / so load in the main of the syscollector wmodule.

Take this approach.
image

### CODE REVIEW

File: src/wazuh_modules/wm_syscollector.c [hunk 1]
```diff
@@ -38,15 +38,29 @@ syscollector_sync_message_func syscollector_sync_message_ptr = NULL;
 
 
 int queue_fd = 0;                                   // Output queue file descriptor
+bool in_shutdown = false;
+static pthread_mutex_t shutdown_mutex;
 
 static void wm_sys_send_diff_message(const void* data) {
     const int eps = 1000000/wm_max_eps;
-    wm_sendmsg(eps,queue_fd, data, WM_SYS_LOCATION, SYSCOLLECTOR_MQ);
+    pthread_mutex_lock(&shutdown_mutex);
```
Comment (konangc87) [inline src/wazuh_modules/wm_syscollector.c:46]: move the lock, read of the booleand and the unlock to a small static function that returns the value.

File: src/wazuh_modules/wm_syscollector.c [hunk 2]
```diff
@@ -56,6 +70,11 @@ static void wm_sys_log_error(const char* log) {
 
 void* wm_sys_main(wm_sys_t *sys) 
 {
+    if (!sys->flags.enabled) {
```
Comment (konangc87) [inline src/wazuh_modules/wm_syscollector.c:73]: what will happen if the module is disabled and the destroy is called as part of the graceful shutdown? shutdown mutex will be used uninitialized.

**Review by konangc87 — CHANGES_REQUESTED** [review]

**Review by tinachoB — APPROVED** [review]
LGTM!

**Review by konangc87 — APPROVED** [review]
