### PR TITLE
Fix possible NULL dereference in wm_exec.c

### LINKED ISSUE #13923: Scan-build failure on `wm_exec.c`
Hi team!!

After executing scan-build on the master branch, a failure has been triggered.

The purpose of this issue is to address the failure and fix it.

I have been using scan-build 14 on a Fedora 36 environment.

# Scan-build report
image

[scan-build-2022-06-20-152856-36615-1.zip](https://github.com/wazuh/wazuh/files/8941009/scan-build-2022-06-20-152856-36615-1.zip)

### PR DESCRIPTION
**Pull request by antoniomanuelfr**
|Related issue|
|---|
| Closes #13923|

## Description
This PR aims to fix a possible NULL dereference in case `getenv` fails.

https://github.com/wazuh/wazuh/blob/a2158a34e844fdca545abdc5af0d0a477ab6db0c/src/wazuh_modules/wm_exec.c#L347-L350

## Configuration options
No errors are raised 

## Logs/Alerts example
No errors are raised using scan-build 14 after the fix:
```
make[1]: Leaving directory '/home/antoniomanuelfr/vagrant/share/wazuh/src'

Done building agent

scan-build: Analysis run complete.
scan-build: Removing directory '/tmp/scan-build-2022-06-20-153811-44255-1' because it contains no reports.
scan-build: No bugs found.
```

## Tests

- Compilation without warnings in every supported platform
  - [x] Linux

- Memory tests for Linux
  - [x] Scan-build report

### CODE REVIEW

File: src/wazuh_modules/wm_exec.c [hunk 1]
```diff
@@ -346,8 +346,10 @@ int wm_exec(char *command, char **output, int *exitcode, int secs, const char *
             }
 
             char *new_env = getenv("PATH");
-            mdebug1("New 'PATH' environment variable set: '%s'", new_env);
-            free(new_path);
+            if (new_env != NULL) {
+                mdebug1("New 'PATH' environment variable set: '%s'", new_env);
+                free(new_path);
```
Comment (chemamartinez) [inline src/wazuh_modules/wm_exec.c:351]: `new_path` must always be freed since it is allocated at the start of the function. In addition, do the same change in the Windows version of the function for consistency.

**Review by chemamartinez — CHANGES_REQUESTED** [review]

**Review by MarcelKemp — APPROVED** [review]

**Comment by jmv74211** [comment]
## QA review

- **Type**: Manual testing
- **Status**: Approved  🟢 
- **Testing issue**: https://github.com/wazuh/wazuh-qa/issues/3017
- **Comments**: Nothing to highlight. Everything seems to work properly.
