### PR TITLE
8703 wrong os name in syscollector scan

### LINKED ISSUE #8703: Incorrect os name in syscollector scan.
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.0-RC4 | Syscollector | Manager/Agent | Packages/Sources | rhel |

## Description

Issue found in TransUnion environment, the over-iteration in operating system files causes this, it should only be searched in the Linux common files and in the specializations, it should be escaped, after the first correct reading.

imagen

imagen

be careful with the order, possibly the best thing would be to add conditions in the parsers, so that only if there is a successful reading they are established (imagine the reverse case)

Steps to reproduce:
- Run docker of rhel 6.10
- touch /etc/lsb-release
- install wazuh.
- register wazuh
- Check dbsync_osinfo table in local.db file.

Actual result:
- Ubuntu 6.10

Expected result:
- Redhat 6.10 or similar.

## DoD
- [ ] Add test to reproduce this. this should fail before the change.
- [x] Add change to solve this (break cycle for in release specializations) 
- [ ] PR CI Pass.

### PR DESCRIPTION
**Pull request by konangc87**
|Related issue|
|---|
|Closes #8703|

## Description
This PR aims to fix the issue found in rhel 6 related to OS name scanning in new syscollector.

## Tests

- Compilation without warnings in every supported platform
  - [ ] Linux
  - [ ] Windows
  - [ ] MAC OS X
- [ ] Source installation
- [ ] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

- [ ] Retrocompatibility with older Wazuh versions
- [ ] Working on cluster environments
- [ ] Configuration on demand reports new parameters
- [ ] The data flow works as expected (agent-manager-api-app)
- [ ] Added unit tests (for new features)
- [ ] Stress test for affected components

### CODE REVIEW

**Review by tinachoB — APPROVED** [review]

File: src/data_provider/src/sysInfoLinux.cpp [hunk 1]
```diff
@@ -313,7 +313,11 @@ static bool getOsInfoFromFiles(nlohmann::json& info)
     {
```
Comment (Dwordcito) [inline src/data_provider/src/sysInfoLinux.cpp:313]: could you move line 284 to the last position of the vector?

Comment (konangc87) [reply src/data_provider/src/sysInfoLinux.cpp:313]: done
