### PR TITLE
[7546] Network gateway issue fix

### LINKED ISSUE #7546: Network gateway std::out of range
## Description

```
(gdb) bt
#0  0x00007ffff675770f in raise () from /lib64/libc.so.6
#1  0x00007ffff6741b25 in abort () from /lib64/libc.so.6
#2  0x00007fffecd2d9fe in __gnu_cxx::__verbose_terminate_handler() [clone .cold.1] () from /var/ossec/bin/../lib/libdbsync.so
#3  0x00007fffece3b6ac in __cxxabiv1::__terminate(void (*)()) () from /var/ossec/bin/../lib/libdbsync.so
#4  0x00007fffece3b707 in std::terminate() () from /var/ossec/bin/../lib/libdbsync.so
#5  0x00007fffece39ad8 in __cxa_throw () from /var/ossec/bin/../lib/libdbsync.so
#6  0x00007fffecd2d3e8 in std::__throw_out_of_range(char const*) [clone .cold.4] () from /var/ossec/bin/../lib/libdbsync.so
#7  0x00007fffecd811ef in __gnu_cxx::__stoa<long, int, char, int> (__convf=0x7ffff675bde0 <strtoq>, __name=0x7fffeceefa41 "stoi",
    __str=0x7fffc4001250 "A12BA8C0", __idx=0x0) at /usr/include/c++/8/ext/string_conversions.h:86
#8  0x00007fffecd802a5 in std::__cxx11::stoi (__str=..., __idx=0x0, __base=16) at /usr/include/c++/8/bits/basic_string.h:6411
#9  0x00007fffec236ce1 in NetworkLinuxInterface::NetworkLinuxInterface (this=0x7fffc40011a0, addrs=0x7fffc40023a0)
    at /root/wazuh/src/data_provider/src/network/networkLinuxWrapper.h:253
#10 0x00007fffec24c3dd in __gnu_cxx::new_allocator<NetworkLinuxInterface>::construct<NetworkLinuxInterface, ifaddrs*&> (
    this=0x7fffd9ffaadf, __p=0x7fffc40011a0) at /usr/include/c++/8/ext/new_allocator.h:136
#11 0x00007fffec24b450 in std::allocator_traits<std::allocator<NetworkLinuxInterface> >::construct<NetworkLinuxInterface, ifaddrs*&> (
    __a=..., __p=0x7fffc40011a0) at /usr/include/c++/8/bits/alloc_traits.h:475
#12 0x00007fffec249f77 in std::_Sp_counted_ptr_inplace<NetworkLinuxInterface, std::allocator<NetworkLinuxInterface>, (__gnu_cxx::_Lock_policy)2>::_Sp_counted_ptr_inplace<ifaddrs*&> (this=0x7fffc4001190, __a=...) at /usr/include/c++/8/bits/shared_ptr_base.h:545
#13 0x00007fffec248497 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<NetworkLinuxInterface, std::allocator<NetworkLinuxInterface>, ifaddrs*&> (this=0x7fffd9ffacc8, __p=@0x7fffd9ffacc0: 0x0, __a=...) at /usr/include/c++/8/bits/shared_ptr_base.h:677
#14 0x00007fffec2463c4 in std::__shared_ptr<NetworkLinuxInterface, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<NetworkLinuxInterface>, ifaddrs*&> (this=0x7fffd9ffacc0, __tag=...) at /usr/include/c++/8/bits/shared_ptr_base.h:1342
#15 0x00007fffec2431ef in std::shared_ptr<NetworkLinuxInterface>::shared_ptr<std::allocator<NetworkLinuxInterface>, ifaddrs*&> (
    this=0x7fffd9ffacc0, __tag=...) at /usr/include/c++/8/bits/shared_ptr.h:359
#16 0x00007fffec2403c9 in std::allocate_shared<NetworkLinuxInterface, std::allocator<NetworkLinuxInterface>, ifaddrs*&> (__a=...)
    at /usr/include/c++/8/bits/shared_ptr.h:706
#17 0x00007fffec23d6af in std::make_shared<NetworkLinuxInterface, ifaddrs*&> () at /usr/include/c++/8/bits/shared_ptr.h:722
#18 0x00007fffec234546 in SysInfo::getNetworks[abi:cxx11]() const (this=0x7fffd9ffad58)
    at /root/wazuh/src/data_provider/src/sysInfoLinux.cpp:378
#19 0x00007fffec24ee46 in SysInfo::networks[abi:cxx11]() (this=0x7fffd9ffad58) at /root/wazuh/src/data_provider/src/sysInfo.cpp:42
#20 0x00007fffec24f241 in sysinfo_networks (js_result=0x7fffd9ffadb8) at /root/wazuh/src/data_provider/src/sysInfo.cpp:80
#21 0x000000000045cf0e in getPrimaryIP () at wazuh_modules/wm_control.c:83
#22 0x000000000045d546 in send_ip () at wazuh_modules/wm_control.c:275
#23 0x000000000045d123 in wm_control_main () at wazuh_modules/wm_control.c:190
#24 0x00007ffff6aea2de in start_thread () from /lib64/libpthread.so.0
#25 0x00007ffff681be83 in clone () from /lib64/libc.so.6
```

Input data to reproduce this issue.
```
# cat /proc/net/route
Iface	Destination	Gateway 	Flags	RefCnt	Use	Metric	Mask		MTU	Window	IRTT
ens34	00000000	A12BA8C0	0003	0	0	100	00000000	0	0	0
ens34	002BA8C0	00000000	0001	0	0	100	00FFFFFF	0	0	0
```

Expected: No exception
Actual: std::stoi out of range exception

- Change to stol
imagen
- Add try-catch block in all c interface functions.

## DoD
- [x] Replace stoi to stol.
- [x] Add try catch blocks for sysinfo provider in c interface.
- [x] Add unit test to process /proc/net/route example in the botton.
- [x] PR - CI Pass.

### PR DESCRIPTION
**Pull request by tinachoB**
|Related issue|
|---|
|Closes #7546 |

## Description

```
(gdb) bt
#0  0x00007ffff675770f in raise () from /lib64/libc.so.6
#1  0x00007ffff6741b25 in abort () from /lib64/libc.so.6
#2  0x00007fffecd2d9fe in __gnu_cxx::__verbose_terminate_handler() [clone .cold.1] () from /var/ossec/bin/../lib/libdbsync.so
#3  0x00007fffece3b6ac in __cxxabiv1::__terminate(void (*)()) () from /var/ossec/bin/../lib/libdbsync.so
#4  0x00007fffece3b707 in std::terminate() () from /var/ossec/bin/../lib/libdbsync.so
#5  0x00007fffece39ad8 in __cxa_throw () from /var/ossec/bin/../lib/libdbsync.so
#6  0x00007fffecd2d3e8 in std::__throw_out_of_range(char const*) [clone .cold.4] () from /var/ossec/bin/../lib/libdbsync.so
#7  0x00007fffecd811ef in __gnu_cxx::__stoa<long, int, char, int> (__convf=0x7ffff675bde0 <strtoq>, __name=0x7fffeceefa41 "stoi",
    __str=0x7fffc4001250 "A12BA8C0", __idx=0x0) at /usr/include/c++/8/ext/string_conversions.h:86
#8  0x00007fffecd802a5 in std::__cxx11::stoi (__str=..., __idx=0x0, __base=16) at /usr/include/c++/8/bits/basic_string.h:6411
#9  0x00007fffec236ce1 in NetworkLinuxInterface::NetworkLinuxInterface (this=0x7fffc40011a0, addrs=0x7fffc40023a0)
    at /root/wazuh/src/data_provider/src/network/networkLinuxWrapper.h:253
#10 0x00007fffec24c3dd in __gnu_cxx::new_allocator<NetworkLinuxInterface>::construct<NetworkLinuxInterface, ifaddrs*&> (
    this=0x7fffd9ffaadf, __p=0x7fffc40011a0) at /usr/include/c++/8/ext/new_allocator.h:136
#11 0x00007fffec24b450 in std::allocator_traits<std::allocator<NetworkLinuxInterface> >::construct<NetworkLinuxInterface, ifaddrs*&> (
    __a=..., __p=0x7fffc40011a0) at /usr/include/c++/8/bits/alloc_traits.h:475
#12 0x00007fffec249f77 in std::_Sp_counted_ptr_inplace<NetworkLinuxInterface, std::allocator<NetworkLinuxInterface>, (__gnu_cxx::_Lock_policy)2>::_Sp_counted_ptr_inplace<ifaddrs*&> (this=0x7fffc4001190, __a=...) at /usr/include/c++/8/bits/shared_ptr_base.h:545
#13 0x00007fffec248497 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<NetworkLinuxInterface, std::allocator<NetworkLinuxInterface>, ifaddrs*&> (this=0x7fffd9ffacc8, __p=@0x7fffd9ffacc0: 0x0, __a=...) at /usr/include/c++/8/bits/shared_ptr_base.h:677
#14 0x00007fffec2463c4 in std::__shared_ptr<NetworkLinuxInterface, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<NetworkLinuxInterface>, ifaddrs*&> (this=0x7fffd9ffacc0, __tag=...) at /usr/include/c++/8/bits/shared_ptr_base.h:1342
#15 0x00007fffec2431ef in std::shared_ptr<NetworkLinuxInterface>::shared_ptr<std::allocator<NetworkLinuxInterface>, ifaddrs*&> (
    this=0x7fffd9ffacc0, __tag=...) at /usr/include/c++/8/bits/shared_ptr.h:359
#16 0x00007fffec2403c9 in std::allocate_shared<NetworkLinuxInterface, std::allocator<NetworkLinuxInterface>, ifaddrs*&> (__a=...)
    at /usr/include/c++/8/bits/shared_ptr.h:706
#17 0x00007fffec23d6af in std::make_shared<NetworkLinuxInterface, ifaddrs*&> () at /usr/include/c++/8/bits/shared_ptr.h:722
#18 0x00007fffec234546 in SysInfo::getNetworks[abi:cxx11]() const (this=0x7fffd9ffad58)
    at /root/wazuh/src/data_provider/src/sysInfoLinux.cpp:378
#19 0x00007fffec24ee46 in SysInfo::networks[abi:cxx11]() (this=0x7fffd9ffad58) at /root/wazuh/src/data_provider/src/sysInfo.cpp:42
#20 0x00007fffec24f241 in sysinfo_networks (js_result=0x7fffd9ffadb8) at /root/wazuh/src/data_provider/src/sysInfo.cpp:80
#21 0x000000000045cf0e in getPrimaryIP () at wazuh_modules/wm_control.c:83
#22 0x000000000045d546 in send_ip () at wazuh_modules/wm_control.c:275
#23 0x000000000045d123 in wm_control_main () at wazuh_modules/wm_control.c:190
#24 0x00007ffff6aea2de in start_thread () from /lib64/libpthread.so.0
#25 0x00007ffff681be83 in clone () from /lib64/libc.so.6
```

Input data to reproduce this issue.
```
# cat /proc/net/route
Iface	Destination	Gateway 	Flags	RefCnt	Use	Metric	Mask		MTU	Window	IRTT
ens34	00000000	A12BA8C0	0003	0	0	100	00000000	0	0	0
ens34	002BA8C0	00000000	0001	0	0	100	00FFFFFF	0	0	0
```

Expected: No exception
Actual: std::stoi out of range exception

- Change to stol
imagen
- Add try-catch block in all c interface functions.

## **DoD**
- [x] Replace stoi to stol.
- [x] Add try catch blocks for sysinfo provider in c interface.
- [x] Add unit test to process /proc/net/route example in the botton.
- [x] RTR
image

- [x] PR - CI Pass.

### CODE REVIEW

File: src/data_provider/src/packages/packagesLinuxParserHelper.h [hunk 1]
```diff
@@ -56,7 +56,7 @@ namespace PackageLinuxHelper
                 }
 
                 ret["name"]         = name;
-                ret["size"]         = size.empty() || size.compare(DEFAULT_VALUE) == 0 ? 0 : stoi(size);
+                ret["size"]         = size.empty() || size.compare(DEFAULT_VALUE) == 0 ? 0 : stol(size);
```
Comment (konangc87) [inline src/data_provider/src/packages/packagesLinuxParserHelper.h:59]: I think you forgot to update parseDpkg as well.

File: src/data_provider/src/sysInfo.cpp [hunk 2]
```diff
@@ -50,41 +50,101 @@ nlohmann::json SysInfo::ports()
...
 {
-    SysInfo info;
-    const auto& ports       {info.ports()};
-    *js_result = cJSON_Parse(ports.dump().c_str());
+    auto retVal { -1 };
+    try
+    {
+        SysInfo info;
+        const auto& ports       {info.ports()};
+        *js_result = cJSON_Parse(ports.dump().c_str());
```
Comment (konangc87) [inline src/data_provider/src/sysInfo.cpp:140]: Please add checks for the js_result pointers to avoid a crashes due to null ptr dereferencing.
Add a UT for the null ptr case.

File: src/wazuh_modules/wm_control.c [hunk 3]
```diff
@@ -80,32 +80,36 @@ char* getPrimaryIP(){
...
-                for (int i = 0; i < size_ids; i++){
-                    const cJSON *element = cJSON_GetArrayItem(iface, i);
-                    if(!element) {
-                        continue;
-                    }
-                    cJSON *gateway = cJSON_GetObjectItem(element, "gateway");
-                    if(gateway && cJSON_GetStringValue(gateway) && 0 != strcmp(gateway->valuestring,"unkwown")) {
-                        const cJSON *ipv4 = cJSON_GetObjectItem(element, "IPv4");
-                        if (!ipv4) {
+        if (sysinfo_network_ptr(&object) != -1) {
```
Comment (konangc87) [inline src/wazuh_modules/wm_control.c:83]: this should be == 0, if in the future we add several error codes for return this will be evaluated as success.

File: src/wazuh_modules/wm_control.c [hunk 4]
```diff
@@ -80,32 +80,36 @@ char* getPrimaryIP(){
...
+                            }
                         }
                     }
                 }
+                sysinfo_free_result_ptr(&object);
             }
-            sysinfo_free_result_ptr(&object);
+        }
+        else {
+            mterror(WM_CONTROL_LOGTAG, "Unable to get system network information (%d) %s.", errno, strerror(errno));
```
Comment (konangc87) [inline src/wazuh_modules/wm_control.c:112]: return code should be used here instead of errno

File: src/win32/win_utils.c [hunk 5]
```diff
@@ -356,32 +356,36 @@ char *get_agent_ip()
...
-                for (int i = 0; i < size_ids; i++){
-                    const cJSON *element = cJSON_GetArrayItem(iface, i);
-                    if(!element) {
-                        continue;
-                    }
-                    cJSON *gateway = cJSON_GetObjectItem(element, "gateway");
-                    if(gateway && cJSON_GetStringValue(gateway) && 0 != strcmp(gateway->valuestring,"unkwown")) {
-                        const cJSON *ipv4 = cJSON_GetObjectItem(element, "IPv4");
-                        if (!ipv4) {
+        if (sysinfo_network_ptr(&object) != -1) {
```
Comment (konangc87) [inline src/win32/win_utils.c:359]: ditto

File: src/win32/win_utils.c [hunk 6]
```diff
@@ -356,32 +356,36 @@ char *get_agent_ip()
...
+                            }
                         }
                     }
                 }
+                sysinfo_free_result_ptr(&object);
             }
-            sysinfo_free_result_ptr(&object);
+        }
+        else {
+            merror("Unable to get system network information.");
```
Comment (konangc87) [inline src/win32/win_utils.c:388]: ditto

File: src/data_provider/src/packages/packagesLinuxParserHelper.h (hunk 1 above)
Comment (tinachoB) [reply src/data_provider/src/packages/packagesLinuxParserHelper.h:59]: You're right. I'll do it in the next commit

File: src/data_provider/src/sysInfo.cpp (hunk 2 above)
Comment (tinachoB) [reply src/data_provider/src/sysInfo.cpp:140]: Will do

File: src/wazuh_modules/wm_control.c (hunk 3 above)
Comment (tinachoB) [reply src/wazuh_modules/wm_control.c:83]: Will do

File: src/wazuh_modules/wm_control.c (hunk 4 above)
Comment (tinachoB) [reply src/wazuh_modules/wm_control.c:112]: Will do

File: src/win32/win_utils.c (hunk 5 above)
Comment (tinachoB) [reply src/win32/win_utils.c:359]: Will do

File: src/win32/win_utils.c (hunk 6 above)
Comment (tinachoB) [reply src/win32/win_utils.c:388]: Will do

**Review by konangc87 — APPROVED** [review]

**Review by Dwordcito — APPROVED** [review]
