### PR TITLE
Fix to obtaining the version in openSUSE tumbleweed

### LINKED ISSUE #11206: Can't get the operating system version in openSUSE tumbleweed for global.db
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.0-rev | wazuh-agentd | Manager/Agent | Packages/Sources | openSUSE tumbleweed |

## Description
Can't get the operating system version in openSUSE tumbleweed for global.db

RCA
The "Version" field in the os-release is commented or does not exist in the rolling updates, therefore this case should be considered to be able to set it as version 0.0 and as "rolling" (build field) as Arch linux style.

image

Actual:

image

Expected
OS: openSUSE tumbleweed

## DoD
- [x] Add support for openSUSE rolling updates.
- [x] Add unit tests
- [x] PR CI checks.

### PR DESCRIPTION
**Pull request by Dwordcito**
|Related issue|
|---|
|Closes #11206 |

## Description

- Compilation without warnings in every supported platform
  - [x] Linux
  - [ ] Windows
  - [ ] MAC OS X
- [x] Source installation
- [x] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [x] Scan-build report
  - [x] Coverity
  - [x] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [x] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

- [ ] Retrocompatibility with older Wazuh versions
- [ ] Working on cluster environments
- [ ] Configuration on demand reports new parameters
- [ ] The data flow works as expected (agent-manager-api-app)
- [ ] Added unit tests (for new features)
- [ ] Stress test for affected components

- Decoder/Rule tests
  - [ ] Added unit testing files ".ini"
  - [ ] runtests.py executed without errors

### CODE REVIEW

**Review by jnasselle — APPROVED** [review]

File: src/shared/version_op.c [hunk 1]
```diff
@@ -442,34 +442,40 @@ os_info *get_unix_version()
...
+                regex_t regexCompiled;
+                regmatch_t match[2];
+                int match_size;
+                if (version_release = fopen("/etc/centos-release","r"), version_release){
+                    os_free(info->os_version);
+                    static const char *pattern = "([0-9][0-9]*\\.?[0-9]*)\\.*";
+                    if (regcomp(&regexCompiled, pattern, REG_EXTENDED)) {
+                        merror_exit("Cannot compile regular expression.");
                     }
+                    while (fgets(buff, sizeof(buff) - 1, version_release)) {
```
Comment (RamiroRD) [inline src/shared/version_op.c:456]: We should be able to just use `sizeof buff` here.
>  The fgets() function shall read bytes from stream into the array
       pointed to by s until n-1 bytes are read, or a <newline> is read
       and transferred to s, or an end-of-file condition is encountered.
       A null byte shall be written immediately after the last byte read
       into the array.

Comment (Dwordcito) [reply src/shared/version_op.c:456]: I understand the point, unfortunately this modification is not atomic, since this same use is made everywhere, it should be dealt with in another issue.

Comment (Dwordcito) [reply src/shared/version_op.c:456]: the modification of this segment is only a nesting to avoid the double condition.

**Review by RamiroRD — APPROVED** [review]

**Review by jnasselle — APPROVED** [review]
