### PR TITLE
Modification of fim_check_ignore function in case of negative regex

### LINKED ISSUE #22186: FIM setting ignore has different behaviors for scheduled, realtime and whodata modes
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.9.0 | wazuh-syscheckd | Manager/Agent | Packages/Sources | Linux |

## Description

During the [migration of fim integration test](https://github.com/wazuh/wazuh/issues/17881) a case was discovered in which for scheduled mode an event is not being generated, but it is being generated in realtime and whodata mode. According to the expected results the event should be generated for any fim mode.

Attached are the logs of the 3 cases executed consecutively and the testcases involved:

[ossec.log](https://github.com/wazuh/wazuh/files/14422007/logFimFail.log)

<details>
  <summary>Test cases</summary>

```
- name: not_ignore_with_negated_sregex_scheduled
  description: Check ignore with negated sregex triggers event because there is no match
  configuration_parameters:
    SYSCHECK:
        - frequency:
            value: 3
        - ignore:
            value: '!mytest'
            attributes:
            - type: 'sregex'
        - directories:
            value: '/testdir1,/testdir2'
            attributes:
            - check_all: 'yes'
            - whodata: 'no'
            - realtime: 'no'
  metadata:
    folder_to_monitor: !!python/object/apply:os.path.join [/testdir1]
    file_to_monitor: !!python/object/apply:os.path.join [/testdir1, mytest]
    content: 'test'
    triggers_event: !!python/object/apply:eval ['True']
    fim_mode: scheduled

- name: not_ignore_with_negated_sregex_realtime
  description: Check ignore with negated sregex triggers event because there is no match
  configuration_parameters:
    SYSCHECK:
        - ignore:
            value: '!mytest'
            attributes:
            - type: 'sregex'
        - directories:
            value: '/testdir1,/testdir2'
            attributes:
            - check_all: 'yes'
            - whodata: 'no'
            - realtime: 'yes'
  metadata:
    folder_to_monitor: !!python/object/apply:os.path.join [/testdir1]
    file_to_monitor: !!python/object/apply:os.path.join [/testdir1, mytest]
    content: 'test'
    triggers_event: !!python/object/apply:eval ['True']
    fim_mode: realtime

- name: not_ignore_with_negated_sregex_whodata
  description: Check ignore with negated sregex triggers event because there is no match
  configuration_parameters:
    SYSCHECK:
        - ignore:
            value: '!mytest'
            attributes:
            - type: 'sregex'
        - directories:
            value: '/testdir1,/testdir2'
            attributes:
            - check_all: 'yes'
            - whodata: 'yes'
            - realtime: 'no'
  metadata:
    folder_to_monitor: !!python/object/apply:os.path.join [/testdir1]
    file_to_monitor: !!python/object/apply:os.path.join [/testdir1, mytest]
    content: 'test'
    triggers_event: !!python/object/apply:eval ['True']
    fim_mode: whodata
``` 

</details>

<details>
  <summary>Test results</summary>

```
sudo python3 -m pytest -s -l tests/integration/test_fim/test_files/test_ignore/test_ignore_valid.py
====================================================================== test session starts ======================================================================
platform linux -- Python 3.10.12, pytest-7.1.2, pluggy-1.0.0
rootdir: /root/wazuh/tests/integration, configfile: pytest.ini
plugins: testinfra-5.0.0, metadata-2.0.4, html-3.1.1
collected 3 items                                                                                                                                               

Reading package lists... Donest_files/test_ignore/test_ignore_valid.py 
Building dependency tree... Done
Reading state information... Done
auditd is already the newest version (1:3.0.7-1build1).
0 upgraded, 0 newly installed, 0 to remove and 85 not upgraded.
F..

=========================================================================== FAILURES ============================================================================
______________________________________________ test_ignore_subdirectory[not_ignore_with_negated_sregex_scheduled] _______________________________________________

test_configuration = {'metadata': {'content': 'test', 'description': 'Check ignore with negated sregex triggers event because there is no m...check'}, {'attributes': [{'name': 'syscollector'}], 'elements': [{'disabled': {'value': 'yes'}}], 'section': 'wodle'}]}
test_metadata = {'binary_content': False, 'content': 'test', 'description': 'Check ignore with negated sregex triggers event because there is no match', 'file_to_monitor': '/testdir1/mytest', ...}
configure_local_internal_options = None, truncate_monitored_files = None, set_wazuh_configuration = None, folder_to_monitor = '/testdir1', daemons_handler = None
file_to_monitor = '/testdir1/mytest'

    @pytest.mark.parametrize('test_configuration, test_metadata', zip(test_configuration, test_metadata), ids=cases_ids)
    def test_ignore_subdirectory(test_configuration, test_metadata, configure_local_internal_options,
                                 truncate_monitored_files, set_wazuh_configuration, folder_to_monitor, daemons_handler,
                                 file_to_monitor):
        '''
        description: Check if the 'wazuh-syscheckd' daemon ignores the files that are in a monitored subdirectory
                     when using the 'ignore' option. It also ensures that events for files tha are not being ignored
                     are still detected. For this purpose, the test will monitor folders containing files to be ignored
                     using names or regular expressions. Then it will create these files and check if FIM events should
                     be generated. Finally, the test will verify that the generated FIM events correspond to the files
                     that must not be ignored.
    
        wazuh_min_version: 4.2.0
    
        tier: 2
    
        parameters:
            - folder:
                type: set
                brief: Path to the directory where the file is being created.
            - filename:
                type: set
                brief: Name of the file to be created.
            - content:
                type: set
                brief: Content to fill the new file.
            - triggers_event:
                type: set
                brief: Run test if matches with a configuration identifier, skip otherwise.
            - tags_to_apply:
                type: set
                brief: Run test if matches with a configuration identifier, skip otherwise.
            - checkers:
                type: dict
                brief: Check options to be used.
            - get_configuration:
                type: fixture
                brief: Get configurations from the module.
            - configure_environment:
                type: fixture
                brief: Configure a custom environment for testing.
            - restart_syscheckd:
                type: fixture
                brief: Clear the 'ossec.log' file and start a new monitor.
            - wait_for_fim_start:
                type: fixture
                brief: Wait for realtime start, whodata start, or end of initial FIM scan.
    
        assertions:
            - Verify that FIM 'ignore' events are generated for each ignored element.
            - Verify that FIM 'added' events are generated for files
              that do not match the value of the 'ignore' option.
    
        input_description: Different test cases are contained in external YAML files
                           (wazuh_conf.yaml or wazuh_conf_win32.yaml) which includes configuration settings for
                           the 'wazuh-syscheckd' daemon and, these are combined with the testing directories
                           to be monitored defined in the module.
    
        inputs:
            - 936 test cases including multiple regular expressions and names for testing files and directories.
    
        expected_output:
            - r'.*Sending FIM event: (.+)$' ('added' events)
            - r'.*Ignoring .* due to'
    
        tags:
            - scheduled
            - time_travel
        '''
    
        wazuh_log_monitor = FileMonitor(WAZUH_LOG_PATH)
    
        if test_metadata.setdefault('triggers_event', False) == True:
            wazuh_log_monitor.start(timeout=60, callback=generate_callback(EVENT_TYPE_ADDED))
            callback_result = wazuh_log_monitor.callback_result
>           assert callback_result
E           assert None

callback_result = None
configure_local_internal_options = None
daemons_handler = None
file_to_monitor = '/testdir1/mytest'
folder_to_monitor = '/testdir1'
set_wazuh_configuration = None
test_configuration = {'metadata': {'content': 'test', 'description': 'Check ignore with negated sregex triggers event because there is no m...check'}, {'attributes': [{'name': 'syscollector'}], 'elements': [{'disabled': {'value': 'yes'}}], 'section': 'wodle'}]}
test_metadata = {'binary_content': False, 'content': 'test', 'description': 'Check ignore with negated sregex triggers event because there is no match', 'file_to_monitor': '/testdir1/mytest', ...}
truncate_monitored_files = None
wazuh_log_monitor = <wazuh_testing.tools.monitors.file_monitor.FileMonitor object at 0x7f37c69b3760>

tests/integration/test_fim/test_files/test_ignore/test_ignore_valid.py:169: AssertionError
---------------------------------------------------------------------- Captured log setup -----------------------------------------------------------------------
DEBUG    wazuh_testing:conftest.py:231 Wazuh control set to True
DEBUG    wazuh_testing:conftest.py:243 Restarting wazuh using wazuh-control
--------------------------------------------------------------------- Captured log teardown ---------------------------------------------------------------------
DEBUG    wazuh_testing:conftest.py:263 Stopping wazuh using wazuh-control
==================================================================== short test summary info ====================================================================
FAILED tests/integration/test_fim/test_files/test_ignore/test_ignore_valid.py::test_ignore_subdirectory[not_ignore_with_negated_sregex_scheduled] - assert None
============================================================ 1 failed, 2 passed in 100.56s (0:01:40) ============================================================
``` 

</details>

### PR DESCRIPTION
**Pull request by jomafer97**
## Description

This pull request closes #22186 by adding some additional logic for negative regex cases.

## Proposed Changes

The function fim_check_ignore() now has and additional parameter, which indicates if the path is refering to a file or a directory. If the regex is negative, the program will wait for the full path for ignoring or not the files.

### Results and Evidence

- https://github.com/wazuh/wazuh/issues/22186#issuecomment-3112566857

### CODE REVIEW

File: src/syscheckd/include/syscheck.h [hunk 1]
```diff
@@ -710,7 +710,7 @@ int fim_whodata_initialize();
  * @param file_name The name of the file to check
  * @return 1 if it has been configured to be ignored, 0 if not
  */
```
Comment (lchico) [inline src/syscheckd/include/syscheck.h:714]: Could you please update the code documentation here?

File: src/syscheckd/src/create_db.c [hunk 2]
```diff
@@ -1673,11 +1674,16 @@ int fim_check_ignore (const char *file_name) {
 
     // Check in the regex entry
     if (syscheck.ignore_regex) {
+
```
Comment (lchico) [inline src/syscheckd/src/create_db.c]: Could you please remove this extra line.

File: src/unit_tests/syscheckd/test_create_db.c [hunk 3]
```diff
@@ -986,7 +986,7 @@ static void test_fim_check_ignore_strncasecmp(void **state) {
 
     expect_string(__wrap__mdebug2, formatted_msg, debug_msg);
 
-    ret = fim_check_ignore("/EtC/dumPDateS");
+    ret = fim_check_ignore("/EtC/dumPDateS",FIM_REGULAR);
```
Comment (lchico) [inline src/unit_tests/syscheckd/test_create_db.c]: Consider adding space after the comma for readability.  Please, also check the following instances.

**Comment by lchico** [comment]
> GJ! @jomafer97 I left some comments. PTAL

Also, please check the [unit-test](https://github.com/wazuh/wazuh/actions/runs/16496380044/job/46642997304?pr=31080#step:6:463); it looks like it needs to be updated.

File: src/syscheckd/src/create_db.c [hunk 4]
```diff
@@ -730,16 +730,17 @@ void fim_checker(const char *path,
         }
     }
 #endif
+    int file_or_directory = evt_data->statbuf.st_mode & S_IFMT;
```
Comment (jotacarma90) [inline src/syscheckd/src/create_db.c]: We should use mode_t variable type for the mask.
And maybe some more representative name for the variable, like path_type or mask_type.

**Comment by jotacarma90** [comment]
For me, the code is OK, test are completed.
Just to complete that 2 cases for UT mentioned by Luis, and ready to merge. For example:
- Add a new test case similar to this:
```
static void test_fim_check_ignore_regex(void **state) {
    int ret;
    char debug_msg[OS_MAXSTR];


#ifndef TEST_WINAGENT
    snprintf(debug_msg, OS_MAXSTR, FIM_IGNORE_SREGEX, "/test/files/test.swp", ".log$|.swp$");
    expect_string(__wrap__mdebug2, formatted_msg, debug_msg);
#else
    snprintf(debug_msg, OS_MAXSTR, FIM_IGNORE_SREGEX, "/test/files/test.swp", ".log$|.htm$|.jpg$|.png$|.chm$|.pnf$|.evtx$|.swp$");
     expect_string(__wrap__mdebug2, formatted_msg, debug_msg);
 #endif

     ret = fim_check_ignore("/test/files/test.swp", FIM_REGULAR);

     assert_int_equal(ret, 1);
 }
```
- Modifying parameters to allow a directory and FIM_DIRECTORY mask. And check expected behaviour.
- In this test file, configuration related to ignore list is made in this line:
`Read_Syscheck_Config("test_syscheck_top_level.conf");` (check that config file)


## Known issue
UT macOS PR check failing is due to:
https://github.com/wazuh/wazuh/issues/31099

**Review by jotacarma90 — DISMISSED** [review]
LGTM

File: src/syscheckd/src/create_db.c [hunk 5]
```diff
@@ -1710,12 +1711,16 @@ int fim_check_ignore (const char *file_name) {
     }
 
     // Check in the regex entry
-    if (syscheck.ignore_regex) {
+    if (syscheck.ignore_regex) {
```
Comment (MarcelKemp) [inline src/syscheckd/src/create_db.c]:
```suggestion
    if (syscheck.ignore_regex) {
```

File: src/syscheckd/src/create_db.c [hunk 6]
```diff
@@ -1710,12 +1711,16 @@ int fim_check_ignore (const char *file_name) {
...
         while (syscheck.ignore_regex[i] != NULL) {
             if (OSMatch_Execute(file_name, strlen(file_name), syscheck.ignore_regex[i])) {
-                mdebug2(FIM_IGNORE_SREGEX, file_name, syscheck.ignore_regex[i]->raw);
-                return 1;
+                if(path_type == FIM_DIRECTORY && syscheck.ignore_regex[i]->raw[0] == '!')
+                    return 0;
+                else{
+                    mdebug2(FIM_IGNORE_SREGEX, file_name, syscheck.ignore_regex[i]->raw);
+                    return 1;
+                }
```
Comment (MarcelKemp) [inline src/syscheckd/src/create_db.c]:
```suggestion
                if (path_type == FIM_DIRECTORY && syscheck.ignore_regex[i]->raw[0] == '!') {
                    return 0;
                } else {
                    mdebug2(FIM_IGNORE_SREGEX, file_name, syscheck.ignore_regex[i]->raw);
                    return 1;
                }
```

File: src/unit_tests/syscheckd/test_create_db.c [hunk 7]
```diff
@@ -271,6 +271,31 @@ static int setup_group(void **state) {
     return 0;
 }
 
+static int setup_fim_regex_group(void **state) {
+    if(setup_fim_data(state) != 0)
```
Comment (MarcelKemp) [inline src/unit_tests/syscheckd/test_create_db.c]:
```suggestion
    if (setup_fim_data(state) != 0)
```

**Review by MarcelKemp — CHANGES_REQUESTED** [review]
Please make minor changes to follow the code style convention:
- https://github.com/wazuh/wazuh/wiki/Coding-style-guide-(C)

**Review by MarcelKemp — APPROVED** [review]
