### PR TITLE
Fix graceful shutdown when agentd or analysisd is stopped.

### LINKED ISSUE #10240: Modulesd gets stuck on stopping
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.2-rc1 | Syscollector | Manager | Sources | Ubuntu 20.04 |

## How to reproduce

1- Start managers processes.
2- pkill -9 wazuh-analysisd
3- Wait syscollector sync.
4- pkill wazuh-modulesd

## Last log

```
2021/09/23 13:50:27 wazuh-modulesd:syscollector: INFO: Stop received for Syscollector.
```

### Thread summary

<details>
<summary>Threads</summary>

```
* 1    Thread 0x7f2449bf5f40 (LWP 10843) "wazuh-modulesd" __lll_lock_wait (
    futex=futex@entry=0x7f24443ba160 <Syscollector::instance()::s_instance+192>,
    private=0) at lowlevellock.c:52
  2    Thread 0x7f2449be0700 (LWP 10845) "wazuh-modulesd" 0x00007f2449d0f12b in __GI___select (nfds=8, readfds=0x7f2449bdfe20, writefds=0x0, exceptfds=0x0, timeout=0x0)
    at ../sysdeps/unix/sysv/linux/select.c:41
  3    Thread 0x7f24493df700 (LWP 10847) "wazuh-modulesd" 0x00007f2449d0f12b in __GI___select (nfds=17, readfds=0x7f24493dee30, writefds=0x0, exceptfds=0x0, timeout=0x0)
    at ../sysdeps/unix/sysv/linux/select.c:41
  4    Thread 0x7f2447bdc700 (LWP 10850) "wazuh-modulesd" 0x00007f2449cd73bf in __GI___clock_nanosleep (clock_id=clock_id@entry=0, flags=flags@entry=0,
    req=req@entry=0x7f2447bdb510, rem=rem@entry=0x7f2447bdb510)
    at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:78
  5    Thread 0x7f24473db700 (LWP 10851) "wazuh-modulesd" 0x00007f2449cd73bf in __GI___clock_nanosleep (clock_id=clock_id@entry=0, flags=flags@entry=0,
    req=req@entry=0x7f24473dac80, rem=rem@entry=0x7f24473dac80)
    at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:78
  6    Thread 0x7f2446bda700 (LWP 10853) "wazuh-modulesd" futex_wait_cancelable (
    private=<optimized out>, expected=0, futex_word=0x55bed630d94c <cond_pending+44>)
    at ../sysdeps/nptl/futex-internal.h:183
  7    Thread 0x7f24463d9700 (LWP 10854) "wazuh-modulesd" 0x00007f2449dfd49f in __libc_accept (fd=10, addr=..., len=0x0) at ../sysdeps/unix/sysv/linux/accept.c:26
  8    Thread 0x7f2445bd8700 (LWP 10855) "wazuh-modulesd" 0x00007f2449dfd6c2 in __libc_recvfrom (fd=11, buf=0x7f2414000b60, len=65535, flags=0, addr=..., addrlen=0x7f2445bd7e1c)
    at ../sysdeps/unix/sysv/linux/recvfrom.c:27
  9    Thread 0x7f24453d7700 (LWP 10856) "wazuh-modulesd" 0x00007f2449d0f12b in __GI___select (nfds=19, readfds=0x7f24453d6e20, writefds=0x0, exceptfds=0x0, timeout=0x0)
    at ../sysdeps/unix/sysv/linux/select.c:41
  10   Thread 0x7f2444bd6700 (LWP 10857) "wazuh-modulesd" futex_wait_cancelable (
    private=<optimized out>, expected=0, futex_word=0x7f2440001150)
    at ../sysdeps/nptl/futex-internal.h:183
  11   Thread 0x7f243f7fe700 (LWP 10858) "wazuh-modulesd" 0x00007f2449d0f12b in __GI___select (nfds=16, readfds=0x7f243f7fde30, writefds=0x0, exceptfds=0x0, timeout=0x0)
    at ../sysdeps/unix/sysv/linux/select.c:41
  12   Thread 0x7f243effd700 (LWP 10859) "wazuh-modulesd" 0x00007f2449d0f12b in __GI___select (nfds=0, readfds=0x0, writefds=0x0, exceptfds=0x0, timeout=0x7f243effce60)
    at ../sysdeps/unix/sysv/linux/select.c:41
  13   Thread 0x7f243e7fc700 (LWP 10860) "wazuh-modulesd" __libc_read (nbytes=272,
    buf=0x7f243e7fada0, fd=4) at ../sysdeps/unix/sysv/linux/read.c:26
  14   Thread 0x7f243d61a700 (LWP 10867) "wazuh-modulesd" futex_wait_cancelable (
    private=<optimized out>, expected=0, futex_word=0x7f243402c660)
    at ../sysdeps/nptl/futex-internal.h:183
  15   Thread 0x7f243ce19700 (LWP 10868) "wazuh-modulesd" futex_wait_cancelable (
    private=<optimized out>, expected=0, futex_word=0x7f243402c660)
    at ../sysdeps/nptl/futex-internal.h:183
  16   Thread 0x7f2423fff700 (LWP 10869) "wazuh-modulesd" futex_wait_cancelable (
    private=<optimized out>, expected=0, futex_word=0x7f243402c660)
    at ../sysdeps/nptl/futex-internal.h:183
  17   Thread 0x7f24237fe700 (LWP 10870) "wazuh-modulesd" futex_wait_cancelable (
    private=<optimized out>, expected=0, futex_word=0x7f243402c660)
    at ../sysdeps/nptl/futex-internal.h:183
  18   Thread 0x7f2422ffd700 (LWP 10871) "wazuh-modulesd" futex_wait_cancelable (
    private=<optimized out>, expected=0, futex_word=0x7f243402c660)
    at ../sysdeps/nptl/futex-internal.h:183
  19   Thread 0x7f24227fc700 (LWP 10872) "wazuh-modulesd" futex_wait_cancelable (
    private=<optimized out>, expected=0, futex_word=0x7f243402c660)
    at ../sysdeps/nptl/futex-internal.h:183
  20   Thread 0x7f2421ffb700 (LWP 10873) "wazuh-modulesd" futex_wait_cancelable (
    private=<optimized out>, expected=0, futex_word=0x7f243402c660)
    at ../sysdeps/nptl/futex-internal.h:183
  21   Thread 0x7f24217fa700 (LWP 10874) "wazuh-modulesd" futex_wait_cancelable (
    private=<optimized out>, expected=0, futex_word=0x7f243402c660)
    at ../sysdeps/nptl/futex-internal.h:183
  22   Thread 0x7f2420ff9700 (LWP 10875) "wazuh-modulesd" futex_wait_cancelable (
    private=<optimized out>, expected=0, futex_word=0x7f243402c660)
    private=<optimized out>, expected=0, futex_word=0x7f243402c660)
    at ../sysdeps/nptl/futex-internal.h:183
  21   Thread 0x7f24217fa700 (LWP 10874) "wazuh-modulesd" futex_wait_cancelable (
    private=<optimized out>, expected=0, futex_word=0x7f243402c660)
    at ../sysdeps/nptl/futex-internal.h:183
  22   Thread 0x7f2420ff9700 (LWP 10875) "wazuh-modulesd" futex_wait_cancelable (
    private=<optimized out>, expected=0, futex_word=0x7f243402c660)
    at ../sysdeps/nptl/futex-internal.h:183
  23   Thread 0x7f2413fff700 (LWP 10878) "wazuh-modulesd" futex_wait_cancelable (
    private=<optimized out>, expected=0, futex_word=0x7f243402c660)
    at ../sysdeps/nptl/futex-internal.h:183
  24   Thread 0x7f24137fe700 (LWP 10879) "wazuh-modulesd" futex_wait_cancelable (
    private=<optimized out>, expected=0, futex_word=0x7f243402c660)
    at ../sysdeps/nptl/futex-internal.h:183
  25   Thread 0x7f2412ffd700 (LWP 10880) "wazuh-modulesd" futex_wait_cancelable (
    private=<optimized out>, expected=0, futex_word=0x7f243402c660)
    at ../sysdeps/nptl/futex-internal.h:183
  26   Thread 0x7f24127fc700 (LWP 10881) "wazuh-modulesd" futex_wait_cancelable (
    private=<optimized out>, expected=0, futex_word=0x7f243402c660)
    at ../sysdeps/nptl/futex-internal.h:183
  27   Thread 0x7f2411ffb700 (LWP 10882) "wazuh-modulesd" futex_wait_cancelable (
    private=<optimized out>, expected=0, futex_word=0x7f243402c660)
    at ../sysdeps/nptl/futex-internal.h:183
  28   Thread 0x7f24117fa700 (LWP 10883) "wazuh-modulesd" futex_wait_cancelable (
    private=<optimized out>, expected=0, futex_word=0x7f243402c660)
    at ../sysdeps/nptl/futex-internal.h:183
  29   Thread 0x7f2410ff9700 (LWP 10884) "wazuh-modulesd" futex_wait_cancelable (
    private=<optimized out>, expected=0, futex_word=0x7f243402c660)
    at ../sysdeps/nptl/futex-internal.h:183
  30   Thread 0x7f243de1b700 (LWP 11273) "wazuh-modulesd" futex_wait_cancelable (
    private=<optimized out>, expected=0, futex_word=0x7f2430000fd0)
    at ../sysdeps/nptl/futex-internal.h:183
```

</details>

### Backtraces

<details>
<summary>Thread 1</summary>

```
#0  __lll_lock_wait (
    futex=futex@entry=0x7f24443ba160 <Syscollector::instance()::s_instance+192>,
    private=0) at lowlevellock.c:52
#1  0x00007f2449df50a3 in __GI___pthread_mutex_lock (
    mutex=0x7f24443ba160 <Syscollector::instance()::s_instance+192>)
    at ../nptl/pthread_mutex_lock.c:80
#2  0x00007f244435e38e in Syscollector::destroy() ()
   from /var/ossec/lib/libsyscollector.so
#3  0x000055bed626673b in wm_sys_stop ()
#4  0x000055bed6217455 in wm_handler ()
#5  <signal handler called>
#6  __pthread_clockjoin_ex (threadid=139793832740608, thread_return=0x0,
    clockid=<optimized out>, abstime=<optimized out>, block=<optimized out>)
    at pthread_join_common.c:145
#7  0x000055bed621700a in main ()
```

</details>

<details>
<summary>Thread 14 to 29</summary>

```
#0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7f243402c660)
    at ../sysdeps/nptl/futex-internal.h:183
183     ../sysdeps/nptl/futex-internal.h: No such file or directory.
(gdb) bt
#0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7f243402c660)
    at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x7f243402c610,
    cond=0x7f243402c638) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x7f243402c638, mutex=0x7f243402c610)
    at pthread_cond_wait.c:638
#3  0x00007f24440a8ba0 in std::condition_variable::wait(std::unique_lock<std::mutex>&) ()
   from /var/ossec/lib/librsync.so
#4  0x00007f244409eb55 in Utils::AsyncDispatcher<std::vector<unsigned char, std::allocator<unsigned char> >, std::function<void (std::vector<unsigned char, std::allocator<unsigned char> > const&)> >::dispatch() () from /var/ossec/lib/librsync.so
#5  0x00007f2444281e04 in ?? () from /var/ossec/lib/libdbsync.so
#6  0x00007f2449df2609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#7  0x00007f2449d19293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

</details>

### PR DESCRIPTION
**Pull request by Dwordcito**
|Related issue|
|---|
| Closes #10240|

## Description
Modulesd gets stuck on stopping.

## Tests

- Compilation without warnings in every supported platform
  - [X] Linux
  - [ ] Windows
  - [ ] MAC OS X
- [X] Source installation
- [ ] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [x] Scan-build report
  - [x] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

- [ ] Retrocompatibility with older Wazuh versions
- [ ] Working on cluster environments
- [ ] Configuration on demand reports new parameters
- [ ] The data flow works as expected (agent-manager-api-app)
- [ ] Added unit tests (for new features)
- [ ] Stress test for affected components

- Decoder/Rule tests
  - [ ] Added unit testing files ".ini"
  - [ ] runtests.py executed without errors

### CODE REVIEW

File: src/shared/mq_op.c [hunk 1]
```diff
@@ -50,6 +50,22 @@ int StartMQ(const char *path, short int type, short int n_attempts)
...
 }
 
+/* Reconnect to message queue */
+int MQReconnectPredicated(const char *path, bool (*fn_ptr)()) {
+    int rc = 0;
+    while ((rc = OS_ConnectUnixDomain(path, SOCK_DGRAM, OS_MAXSTR + 256)), rc < 0){
+        if ((*fn_ptr)()) {
+            return OS_INVALID;
+        }
+        merror("Can't connect to '%s': %s (%d).", path, strerror(errno), errno);
```
Comment (tinachoB) [inline src/shared/mq_op.c:60]: Unable to connecto to

File: src/shared/mq_op.c [hunk 2]
```diff
@@ -50,6 +50,22 @@ int StartMQ(const char *path, short int type, short int n_attempts)
...
+        sleep(5);
+    }
+
+    mdebug1("Connected succesfully to '%s'.", path);
```
Comment (tinachoB) [inline src/shared/mq_op.c:64]: Successfully connected to

**Review by HanesSciarrone — APPROVED** [review]

File: src/wazuh_modules/wm_syscollector.c [hunk 3]
```diff
@@ -44,29 +47,41 @@ syscollector_sync_message_func syscollector_sync_message_ptr = NULL;
...
 #else
             mterror(WM_SYS_LOGTAG, "Unable to send message to '%s' (wazuh-analysisd might be down). Attempting to reconnect.", DEFAULTQUEUE);
 #endif
-            if ((queue_fd = StartMQ(DEFAULTQUEUE, WRITE, INFINITE_OPENQ_ATTEMPTS)) < 0) {
-                mterror(WM_SYS_LOGTAG, "Unable to connect to '%s'", DEFAULTQUEUE);
-            } else {
-                mtinfo(WM_SYS_LOGTAG, "Successfully reconnected to '%s'", DEFAULTQUEUE);
-                if (wm_sendmsg(eps, queue_fd, data, WM_SYS_LOCATION, DBSYNC_MQ) < 0) {
-                    mterror(WM_SYS_LOGTAG, "Unable to send message to '%s' after a successfull reconnection...", DEFAULTQUEUE);
+            // This part of the code is mutually exclusive, since this call is made from multiple threads, and this
```
Comment (tinachoB) [inline src/wazuh_modules/wm_syscollector.c:72]: Since this method is being called by multiple threads it's necessary this particular portion of code to be mutually exclusive. When one thread is successfully reconnected, the other ones will make use of it.

File: src/shared/mq_op.c (hunk 1 above)
Comment (jnasselle) [reply src/shared/mq_op.c:60]: I think is more appropriate to add this message to error_messages.h, and also prepending a numerical id

**Review by jnasselle — DISMISSED** [review]

**Review by tinachoB — APPROVED** [review]
LGTM!

**Review by jnasselle — APPROVED** [review]

**Review by HanesSciarrone — DISMISSED** [review]

**Review by vikman90 — APPROVED** [review]
