### PR TITLE
Fix VD coverity error

### LINKED ISSUE #14365: New coverity defect found in Vulnerability Dectector
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.6 | VD | Manager | Packages/Sources | OS version |

While running the Coverity scan a new defect was found in the vulnerability detector. 
This issue aims to fix this error:
```
ew defect(s) Reported-by: Coverity Scan
Showing 1 of 1 defect(s)


** CID 1518942:    (FORWARD_NULL)
/wazuh_modules/vulnerability_detector/wm_vuln_detector.c: 4006 in wm_vuldet_oval_xml_parser()
/wazuh_modules/vulnerability_detector/wm_vuln_detector.c: 3924 in wm_vuldet_oval_xml_parser()


________________________________________________________________________________________________________
*** CID 1518942:    (FORWARD_NULL)
/wazuh_modules/vulnerability_detector/wm_vuln_detector.c: 4006 in wm_vuldet_oval_xml_parser()
4000                         }
4001                     }
4002                 }
4003             }
4004             else if ((dist == FEED_UBUNTU || dist == FEED_REDHAT) && !strcmp(node[i]->element, XML_CRITERION)) {
4005                 // To avoid a RHSA with no CVEs
>>>     CID 1518942:    (FORWARD_NULL)
>>>     Dereferencing null pointer "parsed_oval->vulnerabilities".
4006                 if (!parsed_oval->vulnerabilities->cve_id) {
4007                     goto end;
4008                 }
4009                 for (j = 0; node[i]->attributes[j]; j++) {
4010                     // Checks if the package isn't vulnerable
4011                     if (!strcmp(node[i]->attributes[j], XML_COMMENT)) {
/wazuh_modules/vulnerability_detector/wm_vuln_detector.c: 3924 in wm_vuldet_oval_xml_parser()
3918             else if (!strcmp(node[i]->element, XML_REFERENCE)) {
3919                 for (j = 0; node[i]->attributes[j]; j++) {
3920                     if (!strcmp(node[i]->attributes[j], XML_REF_ID) &&
3921                         strstr(node[i]->values[j], "CVE")) {
3922                         // Create new CVE structure when a new reference appears.
3923                         // Append the new CVE name to the already existing vulnerability.
>>>     CID 1518942:    (FORWARD_NULL)
>>>     Dereferencing null pointer "parsed_oval->vulnerabilities".
3924                         if (parsed_oval->vulnerabilities->cve_id) {
3925                             info_cve *new;
3926                             os_calloc(1, sizeof(info_cve), new);
3927                             new->prev = parsed_oval->info_cves->prev;
3928                             parsed_oval->info_cves->prev = new;
3929                             os_strdup(node[i]->values[j], new->cveid);


```

### PR DESCRIPTION
**Pull request by antoniomanuelfr**
|Related issue|
|---|
|Closes #14365|

## Description
This PR aims to fix a coverity error in the VD module,

## Tests

- Compilation without warnings in every supported platform
  - [x] Linux
- [x] Source installation
- [x] Source upgrade

- Memory tests for Linux
  - [x] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)

### CODE REVIEW

**Comment by antoniomanuelfr** [comment]
Scan-build only showed an error not related to this PR:


[scan-build.zip](https://github.com/wazuh/wazuh/files/9149117/scan-build.zip)
```
Done building server
scan-build: Analysis run complete.
scan-build: 1 bug found.
scan-build: Run 'scan-view /tmp/scan-build-2022-07-20-123339-42053-1' to examine bug reports.
```

File: src/wazuh_modules/vulnerability_detector/wm_vuln_detector.c [hunk 1]
```diff
@@ -4003,6 +4003,9 @@ int wm_vuldet_oval_xml_parser(OS_XML *xml, XML_NODE node, wm_vuldet_db *parsed_o
         }
         else if ((dist == FEED_UBUNTU || dist == FEED_REDHAT) && !strcmp(node[i]->element, XML_CRITERION)) {
             // To avoid a RHSA with no CVEs
+            if (parsed_oval->vulnerabilities == NULL) {
```
Comment (chemamartinez) [inline src/wazuh_modules/vulnerability_detector/wm_vuln_detector.c:4006]: Add the same in the `if/else` where reading the references, as coverity is complaining as well there.

**Review by chemamartinez — APPROVED** [review]

**Comment by jmv74211** [comment]
## QA review

- **Type**: Manual testing.
- **Status**: Approved  🟢 
- **Testing issue**: https://github.com/wazuh/wazuh-qa/issues/3120
- **Comments**: Nothing to highlight. Everything seems to work properly.
