### PR TITLE
Prevent invalid free of stack memory at osquery integration module

### LINKED ISSUE #17440: Legacy bad free Scan-build report.
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.6 | Wazuh-modules | Manager/Agent | Packages/Sources | Any |

# Description 

It was found that some PRs with the master branch as the target are failing due to the Scan-build report. 

image

The error appears after some changes (https://github.com/wazuh/wazuh/commit/dd01ecae89f792eab3966ab5a0f0d0211d2c4846) in the `wm_osquery_monitor.c`

- Full scan-build report from RTR for manager. 

`python3 build.py --scanbuild server`

[scan-build.zip](https://github.com/wazuh/wazuh/files/11667362/scan-build.zip)

### PR DESCRIPTION
**Pull request by vikman90**
|Related issue|
|---|
|Closes #17440|

This PR aims to fix a bug that mishandles logging data from osquery.

There is a 4 KB buffer allocated in the thread's stack that receives each log from the osquery output. The log parser may call `wm_osquery_already_running()` to match a message like:

> osqueryd (1000) is already running

This function should return a heap-allocated string containing either the process PID, `"unknown"`, or a null pointer (if the message did not match the pattern). However, a recent change let the function return the source string itself. As the caller assumes that the returned string is independent and heap-allocated, it tries to free it after, causing an invalid free hazard.

## Proposed fix

Let `wm_osquery_already_running()` return `NULL` if the input string matches no pattern.

### CODE REVIEW

File: src/wazuh_modules/wm_osquery_monitor.c [hunk 1]
```diff
@@ -427,7 +427,7 @@ char * wm_osquery_already_running(char * text) {
             os_strdup("unknown", text);
         }
```
Comment (thejbte) [inline src/wazuh_modules/wm_osquery_monitor.c:428]: This will work.
```suggestion
        } else {
            text = NULL;
        }
```

File: src/wazuh_modules/wm_osquery_monitor.c [hunk 2]
```diff
@@ -427,7 +427,7 @@ char * wm_osquery_already_running(char * text) {
...
     }
-    return text;
+    return NULL;
```
Comment (thejbte) [inline src/wazuh_modules/wm_osquery_monitor.c:430]:
```suggestion
    return text;
```

**Review by thejbte — CHANGES_REQUESTED** [review]

**Review by thejbte — DISMISSED** [review]

**Comment by Dwordcito** [comment]
@vikman90 is this PR blocked by this another one https://github.com/wazuh/wazuh/pull/17636 ? we may be deadlocked.
