### PR TITLE
wazuh-analysisd writes malformed alerts in alerts.log when <group> contains newline characters

### LINKED ISSUE #30538: `wazuh-analysisd` writes malformed alerts in `alerts.log` when `<group>` contains newline characters
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.x | Wazuh-analysisd | Manager | any | any |

## Description

`wazuh-analysisd` does **not sanitize the content of a `<group>` tag** when rules are loaded.  
If the tag contains embedded new-lines, those characters are copied verbatim into the alert header written to `alerts.log`.  
Any daemon that expects a single-line header then fails to parse the alert file.

### Step to reproduce

1. Add the following rule:

```xml
<rule id="100001" level="5">
    <if_sid>5716</if_sid>
    <srcip>1.1.1.1</srcip>
    <description>sshd: authentication failed from IP 1.1.1.1.</description>
    <group>
    Multiline,
    text,
    group,
    </group>
  </rule>
```

2. Restart the manager.
3. Send the log (syslog/localfile o push to the socket)

```bash
╰─# go run zz_temp/write_log.go -m  "Dec 10 01:02:02 host sshd[1234]: Failed none for root from 1.1.1.1 port 1066 ssh2"
Sended: 1:[123] (hostname123) any->/var/cosas:Dec 10 01:02:02 host sshd[1234]: Failed none for root from 1.1.1.1 port 1066 ssh2
```

4. Check the `alerts.log`

```
** Alert 1750877564.830881: - ossec,pci_dss_10.6.1,gpg13_10.1,gdpr_IV_35.7.d,hipaa_164.312.b,nist_800_53_AU.6,tsc_CC7.2,tsc_CC7.3,
2025 Jun 25 18:52:44 eeb1a4a06248->wazuh-monitord
Rule: 502 (level 3) -> 'Wazuh server started.'
ossec: Manager started.

** Alert 1750877583.831134: - local,syslog,sshd,
    Multiline,
    text,
    group,
    
2025 Jun 25 18:53:03 (hostname123) any->/var/cosas
Rule: 100001 (level 5) -> 'sshd: authentication failed from IP 1.1.1.1.'
Src IP: 1.1.1.1
Src Port: 1066
User: root
Dec 10 01:02:02 host sshd[1234]: Failed none for root from 1.1.1.1 port 1066 ssh2
```

5. Check it with reportd for example:

```bash
╰─# /var/ossec/bin/wazuh-reportd -d < /workspaces/wazuh-manager-4.x/zz_temp/crash_alert.log
2025/06/25 18:54:38 wazuh-reportd[36635] debug_op.c:116 at _log_function(): DEBUG: Logging module auto-initialized
2025/06/25 18:54:38 wazuh-reportd[36635] report.c:162 at main(): DEBUG: Wazuh home directory: /var/ossec
2025/06/25 18:54:38 wazuh-reportd[36635] report.c:192 at main(): DEBUG: Chrooted to directory: /var/ossec, using user: wazuh
2025/06/25 18:54:38 wazuh-reportd[36635] report.c:205 at main(): INFO: Started (pid: 36635).
2025/06/25 18:54:38 wazuh-reportd[36635] read-alert.c:211 at GetAlertData(): ERROR: date or location not NULL or p is NULL
2025/06/25 18:54:43 wazuh-reportd[36635] report_op.c:563 at os_ReportdStart(): INFO: Report completed and zero alerts post-filter.
```

`wazuh-reportd` (wazuh-monitord) can't parse the alert correctly and stops reading alerts, leaving the report incomplete.

### Expected
- wazuh-analysisd should sanitize or reject <group> strings containing newline whens load the rules

### PR DESCRIPTION
**Pull request by LucioDonda**
|Related issue|
|---|
|Closes #30538 |

## Description

`wazuh-analysisd` does **not sanitize the content of a `<group>` tag** when rules are loaded.  
If the tag contains embedded new-lines, those characters are copied verbatim into the alert header written to `alerts.log`.  
Any daemon that expects a single-line header then fails to parse the alert file.

## Proposed changes:

* Apply a cleaning process of the groups string replacing all the new lines ( "/n" ) with an empty string.

### Results and Evidence

* Alert generation:

```
╰─# go run write_log.go -m  "Dec 10 01:02:02 host sshd[1234]: Failed none for root from 1.1.1.1 port 1066 ssh2"
Sended: 1:[123] (hostname123) any->/var/cosas:Dec 10 01:02:02 host sshd[1234]: Failed none for root from 1.1.1.1 port 1066 ssh2
```

* alert.log:

```
** Alert 1751383890.3973: - local,syslog,sshd,    Multiline,    text,    group,    
2025 Jul 01 15:31:30 (hostname123) any->/var/cosas
Rule: 100001 (level 5) -> 'sshd: authentication failed from IP 1.1.1.1.'
Src IP: 1.1.1.1
Src Port: 1066
User: root
Dec 10 01:02:02 host sshd[1234]: Failed none for root from 1.1.1.1 port 1066 ssh2
```

* Reportd checking:

```
# /var/ossec/bin/wazuh-reportd -d < /tmp/randomAlert.log 
2025/07/01 15:40:28 wazuh-reportd[478939] debug_op.c:116 at _log_function(): DEBUG: Logging module auto-initialized
2025/07/01 15:40:28 wazuh-reportd[478939] report.c:162 at main(): DEBUG: Wazuh home directory: /var/ossec
2025/07/01 15:40:28 wazuh-reportd[478939] report.c:192 at main(): DEBUG: Chrooted to directory: /var/ossec, using user: wazuh
2025/07/01 15:40:28 wazuh-reportd[478939] report.c:205 at main(): INFO: Started (pid: 478939).
2025/07/01 15:40:33 wazuh-reportd[478939] report_op.c:574 at os_ReportdStart(): INFO: Report completed. Creating output...
 
Report completed. ==
------------------------------------------------
->Processed alerts: 1
->Post-filtering alerts: 1
->First alert: 2025 Jul 01 15:31:30
->Last alert: 2025 Jul 01 15:31:30
 
 
Top entries for 'Source ip':
------------------------------------------------
1.1.1.1                                                                       |1       |
 
 
Top entries for 'Username':
------------------------------------------------
root                                                                          |1       |
 
 
Top entries for 'Level':
------------------------------------------------
Severity 5                                                                    |1       |
 
 
Top entries for 'Group':
------------------------------------------------
Multiline                                                                     |1       |
group                                                                         |1       |
local                                                                         |1       |
sshd                                                                          |1       |
syslog                                                                        |1       |
text                                                                          |1       |
 
 
Top entries for 'Location':
------------------------------------------------
(hostname123) any->/var/cosas                                                 |1       |
 
 
Top entries for 'Rule':
------------------------------------------------
100001 - sshd: authentication failed from IP 1.1.1.1.                         |1       |

```

### Manual tests with their corresponding evidence

- Compilation without warnings on every supported platform
  - [x] Linux
- [ ] Log syntax and correct language review

- Memory tests for Linux
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [x] AddressSanitizer

- Decoder/Rule tests _(Wazuh v4.x)_
  - [ ] Added unit testing files ".ini"
  - [ ] `runtests.py` executed without errors

## Review Checklist

- [ ] Code changes reviewed
- [ ] Relevant evidence provided
- [ ] Tests cover the new functionality
- [ ] ~Configuration changes documented~
- [ ] ~Developer documentation reflects the changes~
- [ ] Meets requirements and/or definition of done
- [ ] No unresolved dependencies with other issues
- [ ] ...

### CODE REVIEW

**Comment by LucioDonda** [comment]
* Ctest:

```console
wazuh/src/build# ctest 
Test project /home/pm-vagrant/workspace/wazuh/src/build
      Start  1: utils_unit_test
 1/14 Test  #1: utils_unit_test .........................   Passed   66.86 sec
      Start  2: utils_benchmark_test
 2/14 Test  #2: utils_benchmark_test ....................   Passed    4.18 sec
      Start  3: router_component_tests
 3/14 Test  #3: router_component_tests ..................   Passed    0.08 sec
      Start  4: router_unit_tests
 4/14 Test  #4: router_unit_tests .......................   Passed    0.11 sec
      Start  5: content_manager_component_tests
 5/14 Test  #5: content_manager_component_tests .........   Passed   26.55 sec
      Start  6: content_manager_unit_tests
 6/14 Test  #6: content_manager_unit_tests ..............   Passed   11.43 sec
      Start  7: indexer_connector_unit_tests
 7/14 Test  #7: indexer_connector_unit_tests ............   Passed   10.81 sec
      Start  8: indexer_connector_component_tests
 8/14 Test  #8: indexer_connector_component_tests .......   Passed   95.14 sec
      Start  9: vulnerability_scanner_unit_tests
 9/14 Test  #9: vulnerability_scanner_unit_tests ........   Passed   25.29 sec
      Start 10: vulnerability_scanner_component_tests
10/14 Test #10: vulnerability_scanner_component_tests ...   Passed    0.04 sec
      Start 11: vulnerability_scanner_benchmark_tests
11/14 Test #11: vulnerability_scanner_benchmark_tests ...   Passed    2.52 sec
      Start 12: keystore_component_tests
12/14 Test #12: keystore_component_tests ................   Passed    0.68 sec
      Start 13: inventory_harvester_utest
13/14 Test #13: inventory_harvester_utest ...............   Passed    0.12 sec
      Start 14: inventory_harvester_ctest
14/14 Test #14: inventory_harvester_ctest ...............   Passed    0.01 sec

100% tests passed, 0 tests failed out of 14

Label Time Summary:
inventory_harvester_ctest    =   0.01 sec*proc (1 test)
inventory_harvester_utest    =   0.12 sec*proc (1 test)

Total Test time (real) = 243.83 sec
```

* Executed with ASAN result in:

`root@pm-ubuntu24-server:/var/ossec# ASAN_OPTIONS="log_path=asan_report" /var/ossec/bin/wazuh-analysisd -f -u root
`

```
root@pm-ubuntu24-server:/var/ossec# cat asan_report.1224320 

=================================================================
==1224320==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 258998 byte(s) in 2442 object(s) allocated from:
    #0 0x7ffff78fc778  (/lib/x86_64-linux-gnu/libasan.so.8+0xfc778) (BuildId: 23dfa6dbcac57919bae5fe1cac11feecc4fc26c7)
    #1 0x55555566f312 in loadmemory analysisd/rules.c:2048
    #2 0x55555565a88d in Rules_OP_ReadRules analysisd/rules.c:573
    #3 0x5555556940cd in main analysisd/analysisd.c:722
    #4 0x7ffff682a1c9  (/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9) (BuildId: 42c84c92e6f98126b3e2230ebfdead22c235b667)
    #5 0x7ffff682a28a  (/lib/x86_64-linux-gnu/libc.so.6+0x2a28a) (BuildId: 42c84c92e6f98126b3e2230ebfdead22c235b667)
    #6 0x555555620274 in _start (/var/ossec/bin/wazuh-analysisd+0xcc274) (BuildId: 65ba4c8d65c1f1692950490101ffe7eb61ab2ece)

Direct leak of 74 byte(s) in 1 object(s) allocated from:
    #0 0x7ffff78f74e8  (/lib/x86_64-linux-gnu/libasan.so.8+0xf74e8) (BuildId: 23dfa6dbcac57919bae5fe1cac11feecc4fc26c7)
    #1 0x55555571dcaf in Read_Global config/global-config.c:210
    #2 0x555555710aee in read_main_elements config/config.c:85
    #3 0x555555713232 in ReadConfig config/config.c:372
    #4 0x55555562acdd in GlobalConf analysisd/config.c:97
    #5 0x5555556925c8 in main analysisd/analysisd.c:408
    #6 0x7ffff682a1c9  (/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9) (BuildId: 42c84c92e6f98126b3e2230ebfdead22c235b667)
    #7 0x7ffff682a28a  (/lib/x86_64-linux-gnu/libc.so.6+0x2a28a) (BuildId: 42c84c92e6f98126b3e2230ebfdead22c235b667)
    #8 0x555555620274 in _start (/var/ossec/bin/wazuh-analysisd+0xcc274) (BuildId: 65ba4c8d65c1f1692950490101ffe7eb61ab2ece)

SUMMARY: AddressSanitizer: 259072 byte(s) leaked in 2443 allocation(s).
```

**Comment by LucioDonda** [comment]
* Fixed leak only left this already already known:

```console
# cat asan_report.1296195 

=================================================================
==1296195==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 74 byte(s) in 1 object(s) allocated from:
    #0 0x7ffff78f74e8  (/lib/x86_64-linux-gnu/libasan.so.8+0xf74e8) (BuildId: 23dfa6dbcac57919bae5fe1cac11feecc4fc26c7)
    #1 0x55555571dd03 in Read_Global config/global-config.c:210
    #2 0x555555710b42 in read_main_elements config/config.c:85
    #3 0x555555713286 in ReadConfig config/config.c:372
    #4 0x55555562acdd in GlobalConf analysisd/config.c:97
    #5 0x55555569261c in main analysisd/analysisd.c:408
    #6 0x7ffff682a1c9  (/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9) (BuildId: 42c84c92e6f98126b3e2230ebfdead22c235b667)
    #7 0x7ffff682a28a  (/lib/x86_64-linux-gnu/libc.so.6+0x2a28a) (BuildId: 42c84c92e6f98126b3e2230ebfdead22c235b667)
    #8 0x555555620274 in _start (/var/ossec/bin/wazuh-analysisd+0xcc274) (BuildId: fa857d8668968d5b3fda8862e8892605d7d40a60)

SUMMARY: AddressSanitizer: 74 byte(s) leaked in 1 allocation(s).
```

* Unit Test passed:

<details><summary>Details</summary>
<p>

```
root@pm-ubuntu24-server:/home/pm-vagrant/workspace/wazuh/src/unit_tests/build# ctest 
Test project /home/pm-vagrant/workspace/wazuh/src/unit_tests/build
        Start   1: test_analysisd_syscheck
  1/180 Test   #1: test_analysisd_syscheck .................................   Passed    0.04 sec
        Start   2: test_cleanevent
  2/180 Test   #2: test_cleanevent .........................................   Passed    0.03 sec
        Start   3: test_dbsync
  3/180 Test   #3: test_dbsync .............................................   Passed    0.03 sec
        Start   4: test_exec
  4/180 Test   #4: test_exec ...............................................   Passed    0.03 sec
        Start   5: test_log
  5/180 Test   #5: test_log ................................................   Passed    0.03 sec
        Start   6: test_labels
  6/180 Test   #6: test_labels .............................................   Passed    0.03 sec
        Start   7: test_mitre
  7/180 Test   #7: test_mitre ..............................................   Passed    0.01 sec
        Start   8: test_rules
  8/180 Test   #8: test_rules ..............................................   Passed    0.02 sec
        Start   9: test_same_different_loop
  9/180 Test   #9: test_same_different_loop ................................   Passed    0.03 sec
        Start  10: test_logtest
 10/180 Test  #10: test_logtest ............................................   Passed    0.02 sec
        Start  11: test_logtest-config
 11/180 Test  #11: test_logtest-config .....................................   Passed    0.01 sec
        Start  12: test_analysisd_hotreload
 12/180 Test  #12: test_analysisd_hotreload ................................   Passed    0.03 sec
        Start  13: test_decoder_list
 13/180 Test  #13: test_decoder_list .......................................   Passed    0.01 sec
        Start  14: test_decode-xml
 14/180 Test  #14: test_decode-xml .........................................   Passed    0.02 sec
        Start  15: test_lists_list
 15/180 Test  #15: test_lists_list .........................................   Passed    0.01 sec
        Start  16: test_rule_list
 16/180 Test  #16: test_rule_list ..........................................   Passed    0.01 sec
        Start  17: test_eventinfo_list
 17/180 Test  #17: test_eventinfo_list .....................................   Passed    0.01 sec
        Start  18: test_logmsg
 18/180 Test  #18: test_logmsg .............................................   Passed    0.01 sec
        Start  19: test_decoder_rootcheck
 19/180 Test  #19: test_decoder_rootcheck ..................................   Passed    0.03 sec
        Start  20: test_decoder_syscollector
 20/180 Test  #20: test_decoder_syscollector ...............................   Passed    0.03 sec
        Start  21: test_decoder_winevtchannel
 21/180 Test  #21: test_decoder_winevtchannel ..............................   Passed    0.03 sec
        Start  22: test_decoder_winevtchannel_input
 22/180 Test  #22: test_decoder_winevtchannel_input ........................   Passed    0.03 sec
        Start  23: test_analysis-state
 23/180 Test  #23: test_analysis-state .....................................   Passed    0.03 sec
        Start  24: test_asyscom
 24/180 Test  #24: test_asyscom ............................................   Passed    0.03 sec
        Start  25: test_limits
 25/180 Test  #25: test_limits .............................................   Passed    0.01 sec
        Start  26: test_manager
 26/180 Test  #26: test_manager ............................................   Passed    0.03 sec
        Start  27: test_secure
 27/180 Test  #27: test_secure .............................................   Passed    0.03 sec
        Start  28: test_save_ctrlmsg_thread
 28/180 Test  #28: test_save_ctrlmsg_thread ................................   Passed    0.02 sec
        Start  29: test_netbuffer
 29/180 Test  #29: test_netbuffer ..........................................   Passed    0.02 sec
        Start  30: test_sendmsg
 30/180 Test  #30: test_sendmsg ............................................   Passed    0.02 sec
        Start  31: test_remote-config
 31/180 Test  #31: test_remote-config ......................................   Passed    0.01 sec
        Start  32: test_syslogtcp
 32/180 Test  #32: test_syslogtcp ..........................................   Passed    0.02 sec
        Start  33: test_remote-state
 33/180 Test  #33: test_remote-state .......................................   Passed    0.02 sec
        Start  34: test_remcom
 34/180 Test  #34: test_remcom .............................................   Passed    0.02 sec
        Start  35: test_wdb_integrity
 35/180 Test  #35: test_wdb_integrity ......................................   Passed    0.02 sec
        Start  36: test_wdb_fim
 36/180 Test  #36: test_wdb_fim ............................................   Passed    0.02 sec
        Start  37: test_wdb_parser
 37/180 Test  #37: test_wdb_parser .........................................   Passed    0.02 sec
        Start  38: test_wdb_global_parser
 38/180 Test  #38: test_wdb_global_parser ..................................   Passed    0.03 sec
        Start  39: test_wdb_global
 39/180 Test  #39: test_wdb_global .........................................   Passed    0.04 sec
        Start  40: test_wdb_agents
 40/180 Test  #40: test_wdb_agents .........................................   Passed    0.01 sec
        Start  41: test_wdb_global_helpers
 41/180 Test  #41: test_wdb_global_helpers .................................   Passed    0.02 sec
        Start  42: test_wdb_agents_helpers
 42/180 Test  #42: test_wdb_agents_helpers .................................   Passed    0.02 sec
        Start  43: test_wdb
 43/180 Test  #43: test_wdb ................................................   Passed    0.02 sec
        Start  44: test_wdb_upgrade
 44/180 Test  #44: test_wdb_upgrade ........................................   Passed    0.02 sec
        Start  45: test_wdb_metadata
 45/180 Test  #45: test_wdb_metadata .......................................   Passed    0.01 sec
        Start  46: test_wdb_task_parser
 46/180 Test  #46: test_wdb_task_parser ....................................   Passed    0.01 sec
        Start  47: test_wdb_rootcheck
 47/180 Test  #47: test_wdb_rootcheck ......................................   Passed    0.01 sec
        Start  48: test_wdb_syscollector
 48/180 Test  #48: test_wdb_syscollector ...................................   Passed    0.03 sec
        Start  49: test_wdb_task
 49/180 Test  #49: test_wdb_task ...........................................   Passed    0.01 sec
        Start  50: test_wdb_delta_event
 50/180 Test  #50: test_wdb_delta_event ....................................   Passed    0.01 sec
        Start  51: test_wazuh_db-config
 51/180 Test  #51: test_wazuh_db-config ....................................   Passed    0.02 sec
        Start  52: test_wazuh_db_state
 52/180 Test  #52: test_wazuh_db_state .....................................   Passed    0.02 sec
        Start  53: test_wdb_com
 53/180 Test  #53: test_wdb_com ............................................   Passed    0.01 sec
        Start  54: test_wdb_pool
 54/180 Test  #54: test_wdb_pool ...........................................   Passed    0.01 sec
        Start  55: test_create_agent_db
 55/180 Test  #55: test_create_agent_db ....................................   Passed    0.02 sec
        Start  56: test_auth_parse
 56/180 Test  #56: test_auth_parse .........................................   Passed    0.01 sec
        Start  57: test_auth_validate
 57/180 Test  #57: test_auth_validate ......................................   Passed    0.02 sec
        Start  58: test_auth_add
 58/180 Test  #58: test_auth_add ...........................................   Passed    0.02 sec
        Start  59: test_ssl
 59/180 Test  #59: test_ssl ................................................   Passed    0.01 sec
        Start  60: test_auth_key_request
 60/180 Test  #60: test_auth_key_request ...................................   Passed    0.02 sec
        Start  61: test_auth
 61/180 Test  #61: test_auth ...............................................   Passed    0.01 sec
        Start  62: test_generate_cert
 62/180 Test  #62: test_generate_cert ......................................   Passed    1.36 sec
        Start  63: test_authd-config
 63/180 Test  #63: test_authd-config .......................................   Passed    0.01 sec
        Start  64: test_aes_op
 64/180 Test  #64: test_aes_op .............................................   Passed    0.01 sec
        Start  65: test_hmac_op
 65/180 Test  #65: test_hmac_op ............................................   Passed    0.01 sec
        Start  66: test_msgs
 66/180 Test  #66: test_msgs ...............................................   Passed    0.01 sec
        Start  67: test_keys
 67/180 Test  #67: test_keys ...............................................   Passed    0.01 sec
        Start  68: test_sha1_op
 68/180 Test  #68: test_sha1_op ............................................   Passed    0.01 sec
        Start  69: test_blowfish_op
 69/180 Test  #69: test_blowfish_op ........................................   Passed    0.01 sec
        Start  70: test_md5_op
 70/180 Test  #70: test_md5_op .............................................   Passed    0.01 sec
        Start  71: test_md5_sha1_op
 71/180 Test  #71: test_md5_sha1_op ........................................   Passed    0.01 sec
        Start  72: test_md5_sha1_sha256_op
 72/180 Test  #72: test_md5_sha1_sha256_op .................................   Passed    0.01 sec
        Start  73: test_sha256_op
 73/180 Test  #73: test_sha256_op ..........................................   Passed    0.01 sec
        Start  74: test_sha512_op
 74/180 Test  #74: test_sha512_op ..........................................   Passed    0.01 sec
        Start  75: test_wm_aws
 75/180 Test  #75: test_wm_aws .............................................   Passed    0.02 sec
        Start  76: test_wm_azure
 76/180 Test  #76: test_wm_azure ...........................................   Passed    0.02 sec
        Start  77: test_wm_ciscat
 77/180 Test  #77: test_wm_ciscat ..........................................   Passed    0.02 sec
        Start  78: test_wm_command
 78/180 Test  #78: test_wm_command .........................................   Passed    0.03 sec
        Start  79: test_wm_database
 79/180 Test  #79: test_wm_database ........................................   Passed    0.01 sec
        Start  80: test_wm_docker
 80/180 Test  #80: test_wm_docker ..........................................   Passed    0.02 sec
        Start  81: test_wm_gcp
 81/180 Test  #81: test_wm_gcp .............................................   Passed    0.06 sec
        Start  82: test_wmodules_gcp
 82/180 Test  #82: test_wmodules_gcp .......................................   Passed    0.03 sec
        Start  83: test_wm_oscap
 83/180 Test  #83: test_wm_oscap ...........................................   Passed    0.02 sec
        Start  84: test_wm_sca
 84/180 Test  #84: test_wm_sca .............................................   Passed    0.02 sec
        Start  85: test_wmodules_scheduling
 85/180 Test  #85: test_wmodules_scheduling ................................   Passed    0.01 sec
        Start  86: test_wm_vulnerability_detection
 86/180 Test  #86: test_wm_vulnerability_detection .........................   Passed    0.03 sec
        Start  87: test_wm_task_manager
 87/180 Test  #87: test_wm_task_manager ....................................   Passed    0.02 sec
        Start  88: test_wm_task_manager_parsing
 88/180 Test  #88: test_wm_task_manager_parsing ............................   Passed    0.01 sec
        Start  89: test_wm_task_manager_commands
 89/180 Test  #89: test_wm_task_manager_commands ...........................   Passed    0.01 sec
        Start  90: test_wm_agent_upgrade
 90/180 Test  #90: test_wm_agent_upgrade ...................................   Passed    0.01 sec
        Start  91: test_wm_agent_upgrade_manager
 91/180 Test  #91: test_wm_agent_upgrade_manager ...........................   Passed    0.02 sec
        Start  92: test_wm_agent_upgrade_parsing
 92/180 Test  #92: test_wm_agent_upgrade_parsing ...........................   Passed    0.02 sec
        Start  93: test_wm_agent_upgrade_validate
 93/180 Test  #93: test_wm_agent_upgrade_validate ..........................   Passed    0.01 sec
        Start  94: test_wm_agent_upgrade_tasks
 94/180 Test  #94: test_wm_agent_upgrade_tasks .............................   Passed    0.01 sec
        Start  95: test_wm_agent_upgrade_tasks_callbacks
 95/180 Test  #95: test_wm_agent_upgrade_tasks_callbacks ...................   Passed    0.02 sec
        Start  96: test_wm_agent_upgrade_commands
 96/180 Test  #96: test_wm_agent_upgrade_commands ..........................   Passed    0.02 sec
        Start  97: test_wm_agent_upgrade_upgrades
 97/180 Test  #97: test_wm_agent_upgrade_upgrades ..........................   Passed    0.03 sec
        Start  98: test_wmodules
 98/180 Test  #98: test_wmodules ...........................................   Passed    0.02 sec
        Start  99: test_wm_control
 99/180 Test  #99: test_wm_control .........................................   Passed    0.02 sec
        Start 100: test_wm_github
100/180 Test #100: test_wm_github ..........................................   Passed    0.03 sec
        Start 101: test_wm_office365
101/180 Test #101: test_wm_office365 .......................................   Passed    0.04 sec
        Start 102: test_wm_ms_graph
102/180 Test #102: test_wm_ms_graph ........................................   Passed    0.04 sec
        Start 103: test_wm_osquery_already_running
103/180 Test #103: test_wm_osquery_already_running .........................   Passed    0.02 sec
        Start 104: test_wm_exec
104/180 Test #104: test_wm_exec ............................................   Passed    0.02 sec
        Start 105: test_monitord
105/180 Test #105: test_monitord ...........................................   Passed    0.01 sec
        Start 106: test_monitor_actions
106/180 Test #106: test_monitor_actions ....................................   Passed    0.03 sec
        Start 107: test_logcollector
107/180 Test #107: test_logcollector .......................................   Passed    0.03 sec
        Start 108: test_read_multiline_regex
108/180 Test #108: test_read_multiline_regex ...............................   Passed    0.02 sec
        Start 109: test_localfile-config
109/180 Test #109: test_localfile-config ...................................   Passed    0.02 sec
        Start 110: test_state
110/180 Test #110: test_state ..............................................   Passed    0.01 sec
        Start 111: test_lccom
111/180 Test #111: test_lccom ..............................................   Passed    0.47 sec
        Start 112: test_macos_log
112/180 Test #112: test_macos_log ..........................................   Passed    0.01 sec
        Start 113: test_read_macos
113/180 Test #113: test_read_macos .........................................   Passed    0.03 sec
        Start 114: test_read_multiline
114/180 Test #114: test_read_multiline .....................................   Passed    0.02 sec
        Start 115: test_read_journal
115/180 Test #115: test_read_journal .......................................   Passed    0.03 sec
        Start 116: test_journal_log
116/180 Test #116: test_journal_log ........................................   Passed    0.03 sec
        Start 117: test_read_syslog
117/180 Test #117: test_read_syslog ........................................   Passed    0.02 sec
        Start 118: test_execd
118/180 Test #118: test_execd ..............................................   Passed    0.01 sec
        Start 119: test_get_command_by_name
119/180 Test #119: test_get_command_by_name ................................   Passed    0.01 sec
        Start 120: test_integrator
120/180 Test #120: test_integrator .........................................   Passed    0.01 sec
        Start 121: test_manage_keys
121/180 Test #121: test_manage_keys ........................................   Passed    0.01 sec
        Start 122: test_printtable
122/180 Test #122: test_printtable .........................................   Passed    0.01 sec
        Start 123: test_csyslogd
123/180 Test #123: test_csyslogd ...........................................   Passed    0.01 sec
        Start 124: test_syscom
124/180 Test #124: test_syscom .............................................   Passed    0.01 sec
        Start 125: test_fim_diff_changes
125/180 Test #125: test_fim_diff_changes ...................................   Passed    0.03 sec
        Start 126: test_run_realtime
126/180 Test #126: test_run_realtime .......................................   Passed    0.03 sec
        Start 127: test_config
127/180 Test #127: test_config .............................................   Passed    0.06 sec
        Start 128: test_syscheck
128/180 Test #128: test_syscheck ...........................................   Passed    0.05 sec
        Start 129: test_run_check
129/180 Test #129: test_run_check ..........................................   Passed    0.05 sec
        Start 130: test_create_db
130/180 Test #130: test_create_db ..........................................   Passed    0.05 sec
        Start 131: test_audit_healthcheck
131/180 Test #131: test_audit_healthcheck ..................................   Passed    0.02 sec
        Start 132: test_audit_rule_handling
132/180 Test #132: test_audit_rule_handling ................................   Passed    0.02 sec
        Start 133: test_syscheck_audit
133/180 Test #133: test_syscheck_audit .....................................   Passed    0.08 sec
        Start 134: test_audit_parse
134/180 Test #134: test_audit_parse ........................................   Passed    0.03 sec
        Start 135: test_syscheck_ebpf
135/180 Test #135: test_syscheck_ebpf ......................................   Passed    0.03 sec
        Start 136: test_list_op
136/180 Test #136: test_list_op ............................................   Passed    0.02 sec
        Start 137: test_file_op
137/180 Test #137: test_file_op ............................................   Passed    0.01 sec
        Start 138: test_integrity_op
138/180 Test #138: test_integrity_op .......................................   Passed    0.01 sec
        Start 139: test_rbtree_op
139/180 Test #139: test_rbtree_op ..........................................   Passed    0.01 sec
        Start 140: test_validate_op
140/180 Test #140: test_validate_op ........................................   Passed    0.01 sec
        Start 141: test_string_op
141/180 Test #141: test_string_op ..........................................   Passed    0.01 sec
        Start 142: test_expression
142/180 Test #142: test_expression .........................................   Passed    0.01 sec
        Start 143: test_version_op
143/180 Test #143: test_version_op .........................................   Passed    0.02 sec
        Start 144: test_queue_op
144/180 Test #144: test_queue_op ...........................................   Passed    0.01 sec
        Start 145: test_queue_linked_op
145/180 Test #145: test_queue_linked_op ....................................   Passed    0.01 sec
        Start 146: test_agent_op
146/180 Test #146: test_agent_op ...........................................   Passed    0.01 sec
        Start 147: test_enrollment_op
147/180 Test #147: test_enrollment_op ......................................   Passed    0.03 sec
        Start 148: test_time_op
148/180 Test #148: test_time_op ............................................   Passed    0.01 sec
        Start 149: test_buffer_op
149/180 Test #149: test_buffer_op ..........................................   Passed    0.01 sec
        Start 150: test_utf8_op
150/180 Test #150: test_utf8_op ............................................   Passed    0.01 sec
        Start 151: test_log_builder
151/180 Test #151: test_log_builder ........................................   Passed    0.01 sec
        Start 152: test_custom_output_search_replace
152/180 Test #152: test_custom_output_search_replace .......................   Passed    0.01 sec
        Start 153: test_binaries_op
153/180 Test #153: test_binaries_op ........................................   Passed    0.01 sec
        Start 154: test_bzip2_op
154/180 Test #154: test_bzip2_op ...........................................   Passed    0.01 sec
        Start 155: test_schedule_scan
155/180 Test #155: test_schedule_scan ......................................   Passed    0.01 sec
        Start 156: test_rootcheck_op
156/180 Test #156: test_rootcheck_op .......................................   Passed    0.01 sec
        Start 157: test_fs_op
157/180 Test #157: test_fs_op ..............................................   Passed    0.01 sec
        Start 158: test_wazuhdb_op
158/180 Test #158: test_wazuhdb_op .........................................   Passed    0.01 sec
        Start 159: test_syscheck_op
159/180 Test #159: test_syscheck_op ........................................   Passed    0.03 sec
        Start 160: test_json_op
160/180 Test #160: test_json_op ............................................   Passed    0.01 sec
        Start 161: test_audit_op
161/180 Test #161: test_audit_op ...........................................   Passed    0.01 sec
        Start 162: test_privsep_op
162/180 Test #162: test_privsep_op .........................................   Passed    0.01 sec
        Start 163: test_mq_op
163/180 Test #163: test_mq_op ..............................................   Passed    0.01 sec
        Start 164: test_remoted_op
164/180 Test #164: test_remoted_op .........................................   Passed    0.01 sec
        Start 165: test_json-queue
165/180 Test #165: test_json-queue .........................................   Passed    0.01 sec
        Start 166: test_bqueue
166/180 Test #166: test_bqueue .............................................   Passed    0.01 sec
        Start 167: test_atomic
167/180 Test #167: test_atomic .............................................   Passed    0.01 sec
        Start 168: test_url
168/180 Test #168: test_url ................................................   Passed    0.01 sec
        Start 169: test_sysinfo_utils
169/180 Test #169: test_sysinfo_utils ......................................   Passed    0.01 sec
        Start 170: test_rwlock_op
170/180 Test #170: test_rwlock_op ..........................................   Passed    0.02 sec
        Start 171: test_os_xml
171/180 Test #171: test_os_xml .............................................   Passed    0.03 sec
        Start 172: test_os_regex
172/180 Test #172: test_os_regex ...........................................   Passed    0.01 sec
        Start 173: test_os_regex_match
173/180 Test #173: test_os_regex_match .....................................   Passed    0.01 sec
        Start 174: test_os_regex_execute
174/180 Test #174: test_os_regex_execute ...................................   Passed    0.02 sec
        Start 175: test_os_zlib
175/180 Test #175: test_os_zlib ............................................   Passed    0.01 sec
        Start 176: test_client-config_validate_ipv6_link_local_interface
176/180 Test #176: test_client-config_validate_ipv6_link_local_interface ...   Passed    0.02 sec
        Start 177: test_indexer
177/180 Test #177: test_indexer ............................................   Passed    0.01 sec
        Start 178: test_os_net
178/180 Test #178: test_os_net .............................................   Passed    0.01 sec
        Start 179: test_fluentd_forwarder
179/180 Test #179: test_fluentd_forwarder ..................................   Passed    0.02 sec
        Start 180: test_active-response
180/180 Test #180: test_active-response ....................................   Passed    0.01 sec

100% tests passed, 0 tests failed out of 180

Total Test time (real) =   5.25 sec

``` 

</p>
</details>

File: src/analysisd/rules.c [hunk 1]
```diff
@@ -571,7 +571,13 @@ int Rules_OP_ReadRules(const char *rulefile, RuleNode **r_node, ListNode **l_nod
...
                     } else if (strcasecmp(rule_tmp_params.rule_arr_opt[k]->element, xml_group) == 0) {
                         config_ruleinfo->group = loadmemory(config_ruleinfo->group, rule_tmp_params.rule_arr_opt[k]->content, log_msg);
-
+                        char * aux_config_rule_group = config_ruleinfo->group;
+                        /* Avoid new lines in group name */
+                        aux_config_rule_group = wstr_replace(aux_config_rule_group, "\n", "");
+                        if (aux_config_rule_group) {
+                            memcpy(config_ruleinfo->group, aux_config_rule_group, strlen(aux_config_rule_group));
+                        }
+                        free(aux_config_rule_group);
```
Comment (juliancnn) [inline src/analysisd/rules.c]: - use `os_free`
- put the free inside de if
- memcpy not copy the `\0`, make sure it is written, only do this if the new string has a smaller size.

**Review by juliancnn — CHANGES_REQUESTED** [review]

File: src/analysisd/rules.c (hunk 1 above)
Comment (LucioDonda) [reply src/analysisd/rules.c]: done, `os_free` already checks if the ptr is not null:
`#define os_free(x) if(x){free(x);x=NULL;}` so it won't be moved.

**Review by NahuFigueroa97 — APPROVED** [review]
```
╭─root@ca37659e68c4 /workspaces/devContainer/wazuh ‹fix/30538-wazuh-analysisd-writes-malformed-alerts-in-alertslog-when-group-contains-newline-characters●› 
╰─# /var/ossec/bin/wazuh-control restart                               
2025/07/04 14:07:56 wazuh-modulesd:router: INFO: Loaded router module.
2025/07/04 14:07:56 wazuh-modulesd:content_manager: INFO: Loaded content_manager module.
2025/07/04 14:07:56 wazuh-modulesd:inventory-harvester: INFO: Loaded Inventory harvester module.
wazuh-clusterd not running...
Killing wazuh-modulesd...
Killing wazuh-monitord...
Killing wazuh-logcollector...
Killing wazuh-remoted...
Killing wazuh-syscheckd...
Killing wazuh-analysisd...
wazuh-maild not running...
Killing wazuh-execd...
Killing wazuh-db...
wazuh-authd not running...
wazuh-agentlessd not running...
wazuh-integratord not running...
wazuh-dbd not running...
wazuh-csyslogd not running...
Killing wazuh-apid...
Wazuh v4.14.0 Stopped
Starting Wazuh v4.14.0...
Started wazuh-apid...
Started wazuh-csyslogd...
Started wazuh-dbd...
2025/07/04 14:08:31 wazuh-integratord: INFO: Remote integrations not configured. Clean exit.
Started wazuh-integratord...
Started wazuh-agentlessd...
Started wazuh-db...
Started wazuh-execd...
Started wazuh-analysisd...
2025/07/04 14:08:32 wazuh-syscheckd: INFO: (6678): No directory provided for syscheck to monitor.
2025/07/04 14:08:32 wazuh-syscheckd: INFO: (6001): File integrity monitoring disabled.
2025/07/04 14:08:32 rootcheck: INFO: Rootcheck disabled.
Started wazuh-syscheckd...
Started wazuh-remoted...
Started wazuh-logcollector...
Started wazuh-monitord...
2025/07/04 14:08:34 wazuh-modulesd:router: INFO: Loaded router module.
2025/07/04 14:08:34 wazuh-modulesd:content_manager: INFO: Loaded content_manager module.
2025/07/04 14:08:34 wazuh-modulesd:inventory-harvester: INFO: Loaded Inventory harvester module.
Started wazuh-modulesd...
Completed.
╭─root@ca37659e68c4 /workspaces/devContainer/wazuh ‹fix/30538-wazuh-analysisd-writes-malformed-alerts-in-alertslog-when-group-contains-newline-characters●› 
╰─# go run ../write_log.go -m "Dec 10 01:02:02 host sshd[1234]: Failed none for root from 1.1.1.1 port 1066 ssh2"
Sended: 1:[123] (hostname123) any->/var/cosas:Dec 10 01:02:02 host sshd[1234]: Failed none for root from 1.1.1.1 port 1066 ssh2
╭─root@ca37659e68c4 /workspaces/devContainer/wazuh ‹fix/30538-wazuh-analysisd-writes-malformed-alerts-in-alertslog-when-group-contains-newline-characters●› 
╰─# /var/ossec/bin/wazuh-reportd -d < /var/ossec/logs/alerts/alerts.log                                          
2025/07/04 14:09:14 wazuh-reportd[25876] debug_op.c:116 at _log_function(): DEBUG: Logging module auto-initialized
2025/07/04 14:09:14 wazuh-reportd[25876] report.c:162 at main(): DEBUG: Wazuh home directory: /var/ossec
2025/07/04 14:09:14 wazuh-reportd[25876] report.c:192 at main(): DEBUG: Chrooted to directory: /var/ossec, using user: wazuh
2025/07/04 14:09:14 wazuh-reportd[25876] report.c:205 at main(): INFO: Started (pid: 25876).
2025/07/04 14:09:19 wazuh-reportd[25876] report_op.c:574 at os_ReportdStart(): INFO: Report completed. Creating output...
 
Report completed. ==
------------------------------------------------
->Processed alerts: 3
->Post-filtering alerts: 3
->First alert: 2025 Jul 04 14:08:35
->Last alert: 2025 Jul 04 14:09:05
 
 
Top entries for 'Source ip':
------------------------------------------------
1.1.1.1                                                                       |1       |
 
 
Top entries for 'Username':
------------------------------------------------
root                                                                          |1       |
 
 
Top entries for 'Level':
------------------------------------------------
Severity 3                                                                    |1       |
Severity 5                                                                    |1       |
Severity 7                                                                    |1       |
 
 
Top entries for 'Group':
------------------------------------------------
gdpr_IV_35.7.d                                                                |2       |
gpg13_10.1                                                                    |2       |
hipaa_164.312.b                                                               |2       |
nist_800_53_AU.6                                                              |2       |
ossec                                                                         |2       |
pci_dss_10.6.1                                                                |2       |
tsc_CC7.2                                                                     |2       |
tsc_CC7.3                                                                     |2       |
Multiline                                                                     |1       |
group                                                                         |1       |
local                                                                         |1       |
nist_800_53_AU.14                                                             |1       |
pci_dss_10.2.7                                                                |1       |
sshd                                                                          |1       |
syslog                                                                        |1       |
text                                                                          |1       |
tsc_CC6.8                                                                     |1       |
 
 
Top entries for 'Location':
------------------------------------------------
(hostname123) any->/var/cosas                                                 |1       |
ca37659e68c4->netstat listening ports                                         |1       |
ca37659e68c4->wazuh-monitord                                                  |1       |
 
 
Top entries for 'Rule':
------------------------------------------------
100001 - sshd: authentication failed from IP 1.1.1.1.                         |1       |
502 - Wazuh server started.                                                   |1       |
533 - Listened ports status (netstat) changed (new port opened or closed).    |1       |
 
```

**Review by juliancnn — APPROVED** [review]
LGTM


***Runtests***

```bash
╭─root@eeb1a4a06248 /workspaces/wazuh-manager-4.x/ruleset/testing ‹fix/30538-wazuh-analysisd-writes-malformed-alerts-in-alertslog-when-group-contains-newline-characters●› 
╰─# python2 ./runtests.py                                                                                                                                                                                                                                            1 ↵
- [ File = ./tests/apparmor.ini ] ---------
.....


- [ File = ./tests/squid_rules.ini ] ---------
..


- [ File = ./tests/pfsense.ini ] ---------
..


- [ File = ./tests/win-generic_rules.ini ] ---------
.


- [ File = ./tests/huawei_usg.ini ] ---------
...


- [ File = ./tests/test_osmatch_regex.ini ] ---------
......


- [ File = ./tests/fortiddos.ini ] ---------
...


- [ File = ./tests/f5_big_ip.ini ] ---------
................................................


- [ File = ./tests/cisco_ios.ini ] ---------
.................


- [ File = ./tests/systemd.ini ] ---------
..


- [ File = ./tests/macos.ini ] ---------
...........


- [ File = ./tests/amazon_sec_lake.ini ] ---------
....................


- [ File = ./tests/glpi.ini ] ---------
...


- [ File = ./tests/pix.ini ] ---------
......................


- [ File = ./tests/sysmon_eid_3.ini ] ---------
..........


- [ File = ./tests/cisco_asa.ini ] ---------
........................................................................................


- [ File = ./tests/sysmon_eid_20.ini ] ---------
..


- [ File = ./tests/firewalld.ini ] ---------
..


- [ File = ./tests/dovecot.ini ] ---------
...............


- [ File = ./tests/doas.ini ] ---------
....


- [ File = ./tests/test_static_filters.ini ] ---------
............................


- [ File = ./tests/cpanel.ini ] ---------
.......


- [ File = ./tests/office365.ini ] ---------
................................................................................................................................


- [ File = ./tests/web_appsec.ini ] ---------
...............................


- [ File = ./tests/cisco_ftd.ini ] ---------
..........................................


- [ File = ./tests/sophos_fw.ini ] ---------
..........


- [ File = ./tests/test_pcre2_regex.ini ] ---------
.................................


- [ File = ./tests/sysmon.ini ] ---------
.........................


- [ File = ./tests/fortiauth.ini ] ---------
....


- [ File = ./tests/web_rules.ini ] ---------
..........


- [ File = ./tests/win_application.ini ] ---------



- [ File = ./tests/win_security.ini ] ---------
.........


- [ File = ./tests/modsecurity.ini ] ---------
......


- [ File = ./tests/named.ini ] ---------
.....


- [ File = ./tests/malicious-ioc.ini ] ---------
..................


- [ File = ./tests/sysmon_eid_7.ini ] ---------
......


- [ File = ./tests/sudo.ini ] ---------
........


- [ File = ./tests/aws_security_hub.ini ] ---------
.........................


- [ File = ./tests/audit_scp.ini ] ---------
........


- [ File = ./tests/mailscanner.ini ] ---------
.


- [ File = ./tests/apache.ini ] ---------
............


- [ File = ./tests/vsftpd.ini ] ---------
....


- [ File = ./tests/rsh.ini ] ---------
..


- [ File = ./tests/overwrite.ini ] ---------
..........


- [ File = ./tests/sysmon_eid_10.ini ] ---------
....


- [ File = ./tests/gcp.ini ] ---------
...............................


- [ File = ./tests/unbound.ini ] ---------



- [ File = ./tests/proftpd.ini ] ---------
.......


- [ File = ./tests/checkpoint_smart1.ini ] ---------
..................


- [ File = ./tests/vuln_detector.ini ] ---------
..


- [ File = ./tests/test_features.ini ] ---------
.......


- [ File = ./tests/sysmon_eid_1.ini ] ---------
...............................................................


- [ File = ./tests/owlh.ini ] ---------
....


- [ File = ./tests/junos.ini ] ---------
...


- [ File = ./tests/github.ini ] ---------
....................................................................................................................................................................................................................................................................................................................................


- [ File = ./tests/samba.ini ] ---------
....


- [ File = ./tests/eset.ini ] ---------
........


- [ File = ./tests/ossec.ini ] ---------
.....


- [ File = ./tests/openldap.ini ] ---------
.........


- [ File = ./tests/cimserver.ini ] ---------
..


- [ File = ./tests/dropbear.ini ] ---------
...


- [ File = ./tests/opensmtpd.ini ] ---------
.......


- [ File = ./tests/windows_baseline_intrusion_detection.ini ] ---------
.............................


- [ File = ./tests/syslog.ini ] ---------
......


- [ File = ./tests/test_osregex_regex.ini ] ---------
............................


- [ File = ./tests/nextcloud.ini ] ---------
........


- [ File = ./tests/panda_paps.ini ] ---------
........


- [ File = ./tests/su.ini ] ---------
.....


- [ File = ./tests/sysmon_eid_8.ini ] ---------
....


- [ File = ./tests/SonicWall.ini ] ---------
...........


- [ File = ./tests/pam.ini ] ---------
.....


- [ File = ./tests/aws_s3_access.ini ] ---------
..........


- [ File = ./tests/fortigate.ini ] ---------
.............................................


- [ File = ./tests/powershell.ini ] ---------
................................


- [ File = ./tests/arbor.ini ] ---------
..


- [ File = ./tests/test_expr_negation.ini ] ---------
........................................................


- [ File = ./tests/api.ini ] ---------
.....................


- [ File = ./tests/fireeye.ini ] ---------
...


- [ File = ./tests/mcafee_epo.ini ] ---------
.


- [ File = ./tests/openvpn_ldap.ini ] ---------
..


- [ File = ./tests/oscap.ini ] ---------
................................


- [ File = ./tests/sysmon_eid_13.ini ] ---------
.........


- [ File = ./tests/php.ini ] ---------
..


- [ File = ./tests/fortimail.ini ] ---------
......


- [ File = ./tests/auditd.ini ] ---------
...............................


- [ File = ./tests/win_event_channel.ini ] ---------
........


- [ File = ./tests/sysmon_eid_11.ini ] ---------
............................


- [ File = ./tests/paloalto.ini ] ---------
................


- [ File = ./tests/cloudflare-waf.ini ] ---------
.............


- [ File = ./tests/postfix.ini ] ---------
..


- [ File = ./tests/freepbx.ini ] ---------
......


- [ File = ./tests/iptables.ini ] ---------
.........


- [ File = ./tests/kernel_usb.ini ] ---------
......


- [ File = ./tests/exim.ini ] ---------
.......


- [ File = ./tests/sophos.ini ] ---------
........


- [ File = ./tests/sshd.ini ] ---------
.................................................


- [ File = ./tests/nginx.ini ] ---------
............


- [ File = ./tests/gitlab.ini ] ---------
...........................


- [ File = ./tests/exchange.ini ] ---------
..


- [ File = ./tests/netscreen.ini ] ---------
....


|Component |  Tested  |  Total   | Coverage |
| -------- | -------- | -------- | -------- |
|  Rules   |   1460   |   4511   |  32.37%  |
| Decoders |   126    |   171    |  73.68%  |


|          File           |  Passed  |  Failed  |  Status  |
|        --------         | -------- | -------- | -------- |
|./tests/proftpd.ini      |    7     |    0     |   ✅    |
|./tests/exim.ini         |    7     |    0     |   ✅    |
|./tests/squid_rules.ini  |    2     |    0     |   ✅    |
|./tests/sysmon_eid_3.ini |    10    |    0     |   ✅    |
|./tests/amazon_sec_lake.ini|    20    |    0     |   ✅    |
|./tests/checkpoint_smart1.ini|    18    |    0     |   ✅    |
|./tests/iptables.ini     |    9     |    0     |   ✅    |
|./tests/sysmon_eid_10.ini|    4     |    0     |   ✅    |
|./tests/SonicWall.ini    |    11    |    0     |   ✅    |
|./tests/panda_paps.ini   |    8     |    0     |   ✅    |
|./tests/fortiauth.ini    |    4     |    0     |   ✅    |
|./tests/openldap.ini     |    9     |    0     |   ✅    |
|./tests/f5_big_ip.ini    |    48    |    0     |   ✅    |
|./tests/sophos.ini       |    8     |    0     |   ✅    |
|./tests/opensmtpd.ini    |    7     |    0     |   ✅    |
|./tests/netscreen.ini    |    4     |    0     |   ✅    |
|./tests/rsh.ini          |    2     |    0     |   ✅    |
|./tests/arbor.ini        |    2     |    0     |   ✅    |
|./tests/web_rules.ini    |    10    |    0     |   ✅    |
|./tests/exchange.ini     |    2     |    0     |   ✅    |
|./tests/vuln_detector.ini|    2     |    0     |   ✅    |
|./tests/win-generic_rules.ini|    1     |    0     |   ✅    |
|./tests/sysmon_eid_7.ini |    6     |    0     |   ✅    |
|./tests/macos.ini        |    11    |    0     |   ✅    |
|./tests/samba.ini        |    4     |    0     |   ✅    |
|./tests/apparmor.ini     |    5     |    0     |   ✅    |
|./tests/test_osmatch_regex.ini|    6     |    0     |   ✅    |
|./tests/test_features.ini|    7     |    0     |   ✅    |
|./tests/aws_security_hub.ini|    25    |    0     |   ✅    |
|./tests/pam.ini          |    5     |    0     |   ✅    |
|./tests/apache.ini       |    12    |    0     |   ✅    |
|./tests/fireeye.ini      |    3     |    0     |   ✅    |
|./tests/sysmon.ini       |    25    |    0     |   ✅    |
|./tests/dovecot.ini      |    15    |    0     |   ✅    |
|./tests/nginx.ini        |    12    |    0     |   ✅    |
|./tests/nextcloud.ini    |    8     |    0     |   ✅    |
|./tests/unbound.ini      |    0     |    0     |   ✅    |
|./tests/paloalto.ini     |    16    |    0     |   ✅    |
|./tests/sysmon_eid_13.ini|    9     |    0     |   ✅    |
|./tests/ossec.ini        |    5     |    0     |   ✅    |
|./tests/test_osregex_regex.ini|    28    |    0     |   ✅    |
|./tests/cisco_ftd.ini    |    42    |    0     |   ✅    |
|./tests/sysmon_eid_1.ini |    63    |    0     |   ✅    |
|./tests/github.ini       |   324    |    0     |   ✅    |
|./tests/gitlab.ini       |    27    |    0     |   ✅    |
|./tests/fortimail.ini    |    6     |    0     |   ✅    |
|./tests/named.ini        |    5     |    0     |   ✅    |
|./tests/powershell.ini   |    32    |    0     |   ✅    |
|./tests/openvpn_ldap.ini |    2     |    0     |   ✅    |
|./tests/sysmon_eid_8.ini |    4     |    0     |   ✅    |
|./tests/cloudflare-waf.ini|    13    |    0     |   ✅    |
|./tests/huawei_usg.ini   |    3     |    0     |   ✅    |
|./tests/eset.ini         |    8     |    0     |   ✅    |
|./tests/test_expr_negation.ini|    56    |    0     |   ✅    |
|./tests/gcp.ini          |    31    |    0     |   ✅    |
|./tests/cpanel.ini       |    7     |    0     |   ✅    |
|./tests/pfsense.ini      |    2     |    0     |   ✅    |
|./tests/cisco_asa.ini    |    88    |    0     |   ✅    |
|./tests/systemd.ini      |    2     |    0     |   ✅    |
|./tests/web_appsec.ini   |    31    |    0     |   ✅    |
|./tests/sysmon_eid_11.ini|    28    |    0     |   ✅    |
|./tests/cisco_ios.ini    |    17    |    0     |   ✅    |
|./tests/pix.ini          |    22    |    0     |   ✅    |
|./tests/php.ini          |    2     |    0     |   ✅    |
|./tests/office365.ini    |   128    |    0     |   ✅    |
|./tests/fortigate.ini    |    45    |    0     |   ✅    |
|./tests/postfix.ini      |    2     |    0     |   ✅    |
|./tests/audit_scp.ini    |    8     |    0     |   ✅    |
|./tests/win_application.ini|    0     |    0     |   ✅    |
|./tests/malicious-ioc.ini|    18    |    0     |   ✅    |
|./tests/fortiddos.ini    |    3     |    0     |   ✅    |
|./tests/cimserver.ini    |    2     |    0     |   ✅    |
|./tests/freepbx.ini      |    6     |    0     |   ✅    |
|./tests/overwrite.ini    |    10    |    0     |   ✅    |
|./tests/sshd.ini         |    49    |    0     |   ✅    |
|./tests/test_pcre2_regex.ini|    33    |    0     |   ✅    |
|./tests/windows_baseline_intrusion_detection.ini|    29    |    0     |   ✅    |
|./tests/glpi.ini         |    3     |    0     |   ✅    |
|./tests/api.ini          |    21    |    0     |   ✅    |
|./tests/dropbear.ini     |    3     |    0     |   ✅    |
|./tests/win_security.ini |    9     |    0     |   ✅    |
|./tests/firewalld.ini    |    2     |    0     |   ✅    |
|./tests/mailscanner.ini  |    1     |    0     |   ✅    |
|./tests/owlh.ini         |    4     |    0     |   ✅    |
|./tests/sysmon_eid_20.ini|    2     |    0     |   ✅    |
|./tests/auditd.ini       |    31    |    0     |   ✅    |
|./tests/mcafee_epo.ini   |    1     |    0     |   ✅    |
|./tests/doas.ini         |    4     |    0     |   ✅    |
|./tests/junos.ini        |    3     |    0     |   ✅    |
|./tests/sudo.ini         |    8     |    0     |   ✅    |
|./tests/syslog.ini       |    6     |    0     |   ✅    |
|./tests/sophos_fw.ini    |    10    |    0     |   ✅    |
|./tests/vsftpd.ini       |    4     |    0     |   ✅    |
|./tests/win_event_channel.ini|    8     |    0     |   ✅    |
|./tests/modsecurity.ini  |    6     |    0     |   ✅    |
|./tests/su.ini           |    5     |    0     |   ✅    |
|./tests/kernel_usb.ini   |    6     |    0     |   ✅    |
|./tests/aws_s3_access.ini|    10    |    0     |   ✅    |
|./tests/test_static_filters.ini|    28    |    0     |   ✅    |
|./tests/oscap.ini        |    32    |    0     |   ✅    |
```


***ASAN***

know leak
```
╰─# /var/ossec/bin/wazuh-analysisd -f -u root                                                                     1 ↵
2025/07/04 14:35:31 wazuh-analysisd: INFO: Total rules enabled: '7067'
2025/07/04 14:35:31 wazuh-analysisd: INFO: Started (pid: 81835).
2025/07/04 14:35:31 wazuh-analysisd: INFO: EPS limit disabled
2025/07/04 14:35:31 wazuh-analysisd: INFO: (7200): Logtest started
^C2025/07/04 14:36:32 wazuh-analysisd: INFO: (1225): SIGNAL [(2)-(Interrupt)] Received. Exit Cleaning...

=================================================================
==81835==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 74 byte(s) in 1 object(s) allocated from:
    #0 0x7f32d86c79a7  (/lib/x86_64-linux-gnu/libasan.so.6+0x5b9a7)
    #1 0x563e38bdd8cb in Read_Global config/global-config.c:210
    #2 0x563e38bd0739 in read_main_elements config/config.c:85
    #3 0x563e38bd2e7d in ReadConfig config/config.c:372
    #4 0x563e38ae9d91 in GlobalConf analysisd/config.c:97
    #5 0x563e38b51b15 in main analysisd/analysisd.c:408
    #6 0x7f32d7905d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)

SUMMARY: AddressSanitizer: 74 byte(s) leaked in 1 allocation(s).
```

Alert
```
** Alert 1751639733.830224: - local,syslog,sshd,    authentication_failed,pci_dss_10.2.4,pci_dss_10.2.5,
2025 Jul 04 14:35:33 (hostname123) any->/var/cosas
Rule: 100001 (level 5) -> 'sshd: authentication failed from IP 1.1.1.1.'
Src IP: 1.1.1.1
Src Port: 1066
User: root
Dec 10 01:02:02 host sshd[1234]: Failed none for root from 1.1.1.1 port 1066 ssh2
```

Rule
```xml
  <rule id="100001" level="5">
    <if_sid>5716</if_sid>
    <srcip>1.1.1.1</srcip>
    <description>sshd: authentication failed from IP 1.1.1.1.</description>
    <group>

    authentication_failed,pci_dss_10.2.4,pci_dss_10.2.5,</group>
  </rule>
```
