### PR TITLE
Remove WPK rollback code section

### LINKED ISSUE #9449: Remove rollback code section when upgrading with WPK
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2 | upgrade scripts | Agent | wpk | linux/windows |

Hi team!

When upgrading agents through the manager using WPKs, the rollback, that is performed in case of upgrade failure, has some errors due to agent versions mismatches. At the moment, it does not correctly restore the permissions; ownerships and/or services. This happens in Windows and Linux as well.

The fastest solution would be to disable the restoring operation, in order to avoid producing system errors, and try to start the agent in the state it is, even though the upgrade failed and the agent may not start.

Regards,
Julian

### PR DESCRIPTION
**Pull request by juliancnn**
|Related issue|
|---|
|Closes #9449 |

Hi team!,

This PR has 2 commits:
- The first commit removes the backup and rollback code section, which handles the case when upgrading with WPK fails.
- ~The second one is just for testing purposes, it forces the upgrade to fail.~

### Linux
- [x] Centos 6: Upgrade failure 3.13 -> 4.2
- [x] Centos 6: Upgrade failure 4.0 -> 4.2
- [x] Centos 6: Upgrade failure 4.2 -> 4.2
- [x] Centos 8: Upgrade failure 3.13 -> 4.2
- [x] Centos 8: Upgrade failure 4.1.5 -> 4.2
- [x] Centos 8: Upgrade failure 4.2 -> 4.2
- [x] Ubuntu: Upgrade failure 3.13 -> 4.2
- [x] Ubuntu: Upgrade failure 4.0 -> 4.2
- [x] Ubuntu: Upgrade failure 4.2 -> 4.2

### Windows:
- [x] Windows 10: Upgrade failure 3.13 -> 4.2
- [x] Windows 10: Upgrade failure 4.0 -> 4.2
- [x] Windows 10: Upgrade failure 4.2 -> 4.2
- [x] Windows Server 2008: Upgrade failure 3.13 -> 4.2
- [x] Windows Server 2008: Upgrade failure 4.2 -> 4.2
- [x] WIndows Server 2008: Upgrade failure 4.0 -> 4.2
- [x] Windows Server 2012r2: Upgrade failure 3.13 -> 4.2
- [x] Windows Server 2012r2: Upgrade failure 4.2 -> 4.2
- [x] WIndows Server 2012r2: Upgrade failure 4.0 -> 4.2

### CODE REVIEW

**Review by nmkoremblum — APPROVED** [review]
LGTM :)

**Review by JcabreraC — APPROVED** [review]
LGTM !

File: src/init/pkg_installer.sh [hunk 1]
```diff
@@ -8,21 +8,6 @@ WAZUH_VERSION=${2}
 # Generating Backup
 BDATE=$(date +"%m-%d-%Y_%H-%M-%S")
```
Comment (TomasTurina) [inline src/init/pkg_installer.sh:9]: Remove these two lines.

File: src/init/pkg_installer.sh [hunk 2]
```diff
@@ -48,22 +33,14 @@ if [ "$status" = "connected" -a $RESULT -eq 0  ]; then
...
+    echo "$(date +"%Y/%m/%d %H:%M:%S") - Upgrade failed..." >> ${WAZUH_HOME}/logs/upgrade.log
 
     CONTROL="$WAZUH_HOME/bin/wazuh-control"
     if [ ! -f $CONTROL ]; then
         CONTROL="$WAZUH_HOME/bin/ossec-control"
     fi
 
-    $CONTROL stop >> ${WAZUH_HOME}/logs/upgrade.log 2>&1
-    tar xzf ${WAZUH_HOME}/backup/backup_${WAZUH_VERSION}_[${BDATE}].tar.gz -C / >> ${WAZUH_HOME}/logs/upgrade.log 2>&1
+    $CONTROL start >> ${WAZUH_HOME}/logs/upgrade.log 2>&1
```
Comment (TomasTurina) [inline src/init/pkg_installer.sh:43]: I think that you can add a log to indicate that Wazuh will be started in the state it is at this point.

File: src/win32/do_upgrade.ps1 [hunk 3]
```diff
@@ -101,26 +81,10 @@ write-output "$(Get-Date -format u) - Reading status file: $($status)" >> .\upgr
 If ($status -eq $null)
 {
     write-output "2" | out-file ".\upgrade\upgrade_result" -encoding ascii
```
Comment (TomasTurina) [inline src/win32/do_upgrade.ps1:83]: You can add a log saying that the upgrade failed and Wazuh will stay in the state it is at this point.

File: src/win32/do_upgrade.ps1 [hunk 4]
```diff
@@ -101,26 +81,10 @@ write-output "$(Get-Date -format u) - Reading status file: $($status)" >> .\upgr
...
-    }
-    Start-Service -Name "Wazuh" -ErrorAction SilentlyContinue
 }
 Else
 {
     write-output "0" | out-file ".\upgrade\upgrade_result" -encoding ascii
-    Remove-Item .\backup -recurse -ErrorAction SilentlyContinue
     write-output "$(Get-Date -format u) - Upgrade finished successfully." >> .\upgrade\upgrade.log
     $new_version = (Get-Content VERSION)
     write-output "$(Get-Date -format u) - New version: $($new_version)" >> .\upgrade\upgrade.log
```
Comment (TomasTurina) [inline src/win32/do_upgrade.ps1:90]: Can we also remove the last line (https://github.com/wazuh/wazuh/pull/9450/files?file-filters%5B%5D=.ps1#diff-2228236c7340e8be4c74b7fcf34700405182ae35ded67c9fcf309de1a076d03aR93) or why do we need it?

File: src/init/pkg_installer.sh (hunk 2 above)
Comment (juliancnn) [reply src/init/pkg_installer.sh:41]: done

**Review by TomasTurina — APPROVED** [review]
LGTM!

**Review by nmkoremblum — APPROVED** [review]

**Review by JcabreraC — APPROVED** [review]

**Review by vikman90 — APPROVED** [review]
