### PR TITLE
wazuh-engine: Reinforce decoder field validation and optimize temporary field lifecycle cleanup

### LINKED ISSUE #34669: wazuh-engine: Restrict decoder field mapping to WCS Fields and Introduce ephemeral root variables (`_`)
## Description

Today, wazuh-engine allows decoders to map into **any field path**. If the target field exists in the schema (WCS), the engine validates types (runtime for references, build-time for literals). If the target field is **not** in the schema, validation is effectively skipped and decoders can write arbitrary data into custom fields.

We must change this behavior:

* Decoders must only map to **WCS fields**.
* Any non-WCS field used by decoders must be treated as a **temporary variable** and must start with `_`.
* Temporary variables must be **ephemeral**: they exist only during decoder execution and are removed from the event before leaving the decoder stage.

This also impacts decoder validation APIs and the external JSON schema used by other teams as a reference.

### 1) Field mapping restrictions

* Decoder mappings can target only:

  * **WCS fields**, or
  * **temporary variables** that:

    * start with `_`
    * are located at the **root** of the JSON event (no nested variables)

Examples:

* Allowed:

  * `event.severity`
  * `_tmp`
  * `_severity_string`
  * `_tmp.value` (nested)
* Not allowed:

  * `custom.foo`
  * `wazuh.custom.field` (unless WCS)
  * `host._tmp` (nested)

### 2) Temporary variable lifecycle

* Temporary variables are created when a decoder writes to a root field starting with `_`.
* All temporary variables must be **deleted from the event** right after exiting the decoder stage. 

### 3) Variable concept update

* The current “variable” concept must be removed or extended into this unified model:

  * Variables must start with `_`
  * Variables are ephemeral and auto-cleaned after decoder execution

## Objectives

* Enforce mapping restrictions during decoder compilation/validation.
* Implement ephemeral variable support and cleanup:

  * Track creation/use of root `_` fields
  * Remove them atomically before leaving decoders
* Update decoder validation endpoints:

  * Fail validation if a mapping targets a field that is:

    * not a WCS field, and
    * not a root `_` variable
* Update the reference JSON schema (used externally) to reflect these rules.

## Requirements

* Variables must be allowed **only at the JSON root**, not inside WCS objects.
* Error messages must be clear and actionable (include the invalid target field path).
* This behavior must apply consistently across:

  * `map` operations in decoders
  * any stage where decoders assign fields (`parse|*`, `normalize` mappings)

## Deliverables

* Engine changes enforcing “WCS-only or `_` root variable” mapping rules.
* Ephemeral `_` variable lifecycle implemented (auto-deletion before leaving decoders).
* Decoder validation endpoints updated to enforce the new rules.
* Updated JSON schema/reference docs describing:

  * allowed mapping targets
  * variable naming constraints
  * variable lifecycle

### PR DESCRIPTION
**Pull request by matigarciadev**
## Description

This pull request improves decoder temporary-field lifecycle handling and schema/target validation behavior in the Engine pipeline.

The main problem addressed is that temporary fields (`_*`) were being deleted too early (at decoder asset execution), which prevented parent decoder temporaries from being reused by child decoders. In addition, cleanup was generalized through a predicate-based API that is more expensive than needed for the specific post-decoder cleanup use case.

Closes #34669.

> [!WARNING]
> This change currently causes content synchronization errors  in the standard namespace due to two issues:
> - Temporary fields defined in decoders that do not contain an underscore (`_`).
> - Integration-specific WCS fields that are not yet integrated into WCS, such as `windows.*`, `aws.*`, and others.
> 
> ```
> 2026/03/06 17:11:19 wazuh-manager-analysisd[191631] cmsync.cpp:552 at synchronize(): ERROR: [CM::Sync] Failed to sync namespace in route for space 'standard': Failed to create new route 'cmsync_standard': Failed to create the route: Failed to create environment with policy 'cmsync_standard_25d8' and filter 'filter/allow-all/0': Error building decoder decoder/integrations/0 from integration 'wazuh-core': In stage 'normalize' builder for block 'map' failed with error: Failed to build operation 'tmp_json: parse_json($event.original)': Field 'tmp_json' is not defined in WCS schema and is not a temporary field (root must start with '_')
> ```

## Proposed Changes

- Moved temporary-field cleanup from per-decoder asset execution to the policy pre-enrichment stage, after decoder tree execution.
- Added a specialized JSON API `eraseRootKeysByPrefix(std::string_view prefix)` to optimize root-level temporary cleanup.
- Updated policy cleanup operation to use `eraseRootKeysByPrefix("_")`.
- Kept generic `eraseIfKey(...)` available for existing use cases.
- Updated builder/policy unit tests to reflect the new cleanup location and ordering.
- Added/updated component tests to verify:
  - parent decoder temporaries are accessible in child decoders,
  - temporary fields are removed at the end of the decoder pipeline.
- Added JSON unit tests for `eraseRootKeysByPrefix` behavior.
- Strict schema validator behavior for unknown fields:
  - unknown fields are rejected unless they are temporary fields rooted with `_`,
  - root target (`.`) remains allowed.

### Results and Evidence

- **Engine runtime behavior (manual run with sample namespace/policy):**
  - Decoder hierarchy successfully reused parent temporaries from child/grandchild decoders.
  - Root mapping with `.` (`kvdb_get_merge_recursive(...)`) executed successfully.
  - Final output did not include temporary fields (`_raw`, `_tmp_*`, etc.), confirming cleanup after decoders.

Evidence excerpt from `engine-test` run:

```text
[🟢] decoder/integration-parent/0 -> success
  ↳ .: kvdb_get_merge_recursive("event_defaults_by_code", $event.code) -> Success
[🟢] decoder/child-uses-parent-temporals/0 -> success
  ↳ [check: exists($_tmp_proto) AND exists($_tmp_host)] -> Success
[🟢] decoder/grandchild-multiple-temporals/0 -> success
  ↳ [check: ($_tmp_proto == http OR $_tmp_proto == dns OR $_tmp_proto == alert) AND exists($_tmp_url)] -> Success
```

Full log `engine-test` run:
```console
engine-test -c /workspaces/wazuh-5.x/engine-test.json run test -n testDecoderMapping -dd                                      

Enter any events [ENTER to send event, CTRL+C to finish]:

{"code":"http","proto":"HTTP","host":"web-01","src_ip":"10.0.0.10","dst_ip":"10.0.0.20","user":"Alice","url":"https://example.local/path?a=1&b=2","reason":"integration test","env":"dev","version":"1.2.3","msg":"test event"}


---
traces:
[🟢] decoder/core-root/0 -> success
  ↳ @timestamp: get_date -> Success
[🟢] decoder/integration-parent/0 -> success
  ↳ [check: exists($event.original)] -> Success
  ↳ _raw: parse_json($event.original) -> Success
  ↳ [_tmp_proto: downcase($_raw.proto)] -> Success
  ↳ _tmp_host: map($_raw.host) -> Success
  ↳ [_tmp_code: downcase($_raw.code)] -> Success
  ↳ _tmp_url: map($_raw.url) -> Success
  ↳ event.code: map($_tmp_code) -> Success
  ↳ source.ip: map($_raw.src_ip) -> Success
  ↳ destination.ip: map($_raw.dst_ip) -> Success
  ↳ host.name: map($_tmp_host) -> Success
  ↳ .: kvdb_get_merge_recursive("event_defaults_by_code", $event.code) -> Success
[🟢] decoder/child-uses-parent-temporals/0 -> success
  ↳ [check: exists($_tmp_proto) AND exists($_tmp_host)] -> Success
  ↳ [_tmp_user: downcase($_raw.user)] -> Success
  ↳ _tmp_tags: array_append($_tmp_proto, $_tmp_user) -> Success
  ↳ network.protocol: map($_tmp_proto) -> Success
  ↳ event.reason: map($_raw.reason) -> Success
  ↳ related.ip: array_append($source.ip, $destination.ip) -> Success
[🟢] decoder/grandchild-multiple-temporals/0 -> success
  ↳ [check: ($_tmp_proto == http OR $_tmp_proto == dns OR $_tmp_proto == alert) AND exists($_tmp_url)] -> Success
  ↳ _tmp_split_url: split($_tmp_url, "?") -> Success
  ↳ _tmp_meta.env: map($_raw.env) -> Success
  ↳ _tmp_meta.version: map($_raw.version) -> Success
  ↳ _tmp_arr: array_append($_tmp_proto, $_tmp_host, $_tmp_user) -> Success
  ↳ url.original: map($_tmp_url) -> Success
  ↳ url.path: map($_tmp_split_url.0) -> Success
  ↳ url.query: map($_tmp_split_url.1) -> Success
  ↳ message: map($_raw.msg) -> Success
  ↳ event.category: array_append("network") -> Success
[🟢] filter/UnclassifiedEvents -> success
  ↳ dropUnclassifiedEvent() -> Event is classified, allowing event
[🟢] filter/DiscardedEvents -> success
  ↳ Event will be indexed (index_discarded_events=true)

output:
  '@timestamp': '2026-03-06T15:02:04Z'
  destination:
    ip: 10.0.0.20
  event:
    category:
    - network
    - web
    - network
    code: http
    kind: event
    original: '{"code":"http","proto":"HTTP","host":"web-01","src_ip":"10.0.0.10","dst_ip":"10.0.0.20","user":"Alice","url":"https://example.local/path?a=1&b=2","reason":"integration
      test","env":"dev","version":"1.2.3","msg":"test event"}'
    reason: integration test
    type:
    - protocol
    - access
  host:
    name: web-01
  message: test event
  network:
    protocol: http
  related:
    ip:
    - 10.0.0.10
    - 10.0.0.20
  source:
    ip: 10.0.0.10
  url:
    original: https://example.local/path?a=1&b=2
    path: https://example.local/path
    query: a=1&b=2
  wazuh:
    integration:
      category: security
      decoders:
      - decoder/core-root/0
      - decoder/integration-parent/0
      - decoder/child-uses-parent-temporals/0
      - decoder/grandchild-multiple-temporals/0
      name: integration/test-temporals/0
    protocol:
      location: /tmp/json
      queue: 49
    space:
      name: UNDEFINED
```

- **Focused unit/component tests executed:**
  - `build/engine/source/base/base_utest --gtest_filter='JsonTest.eraseRootKeysByPrefix*'` → Passed (3/3).
  - `build/engine/source/builder/builder_ctest --gtest_filter='BuildPolicyAdvancedTest.ParentTemporaryVariableIsAvailableInChildDecoder:BuildPolicyAdvancedTest.DecoderTemporaryVariableIsRemovedAtPipelineEnd'` → Passed (2/2).

 **Currently, the standard namespace is showing errors when synchronizing content:**
 ```
 2026/03/06 17:11:19 wazuh-manager-analysisd[191631] cmsync.cpp:552 at synchronize(): ERROR: [CM::Sync] Failed to sync namespace in route for space 'standard': Failed to create new route 'cmsync_standard': Failed to create the route: Failed to create environment with policy 'cmsync_standard_25d8' and filter 'filter/allow-all/0': Error building decoder decoder/integrations/0 from integration 'wazuh-core': In stage 'normalize' builder for block 'map' failed with error: Failed to build operation 'tmp_json: parse_json($event.original)': Field 'tmp_json' is not defined in WCS schema and is not a temporary field (root must start with '_')
 ```

### Manual tests with their corresponding evidence

- Compilation without warnings on every supported platform
  - [X] Linux
  - [ ] Windows 
  - [ ] MAC OS X
- [ ] Log syntax and correct language review

- Memory tests for Linux
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [X] AddressSanitizer
- Memory tests for Windows
  - [ ] Coverity
  - [ ] UMDH
- Memory tests for macOS
  - [ ] Leaks
  - [ ] AddressSanitizer

- Decoder/Rule tests _(Wazuh v4.x)_
  - [ ] Added unit testing files ".ini"
  - [ ] `runtests.py` executed without errors

- Engine _(Wazuh v5.x and above)_
  - [ ] Test run in parallel
  - [X] ASAN for test (utest/ctest)
  - [ ] TSAN for test and wazuh-engine.

- Wazuh server API/Framework
  - [ ] Run API Integration Tests

### Artifacts Affected

- Engine base JSON utility (`base/json`):
  - New API: `eraseRootKeysByPrefix`.
- Engine builder policy pipeline:
  - Decoder temporary cleanup moved to pre-enrichment stage.
- Builder and base test binaries:
  - Updated `builder_ctest` and `base_utest` test coverage.

### Configuration Changes

- N/A.

### Tests Introduced

- **Base JSON unit tests** (`json_test.cpp`):
  - `eraseRootKeysByPrefixRemovesOnlyRootMatches`
  - `eraseRootKeysByPrefixNoMatchesReturnsFalse`
  - `eraseRootKeysByPrefixEmptyPrefixNoop`

- **Builder component tests** (`builder_test.cpp`):
  - `ParentTemporaryVariableIsAvailableInChildDecoder`
  - `DecoderTemporaryVariableIsRemovedAtPipelineEnd`

- **Builder policy/factory expectations** (`factory_test.cpp`):
  - Pre-enrichment order now includes `CleanupDecoderVariables` at the end.

## Review Checklist

- [ ] Code changes reviewed
- [ ] Relevant evidence provided
- [ ] Tests cover the new functionality
- [ ] Configuration changes documented
- [ ] Developer documentation reflects the changes
- [ ] Meets requirements and/or definition of done
- [ ] No unresolved dependencies with other issues
- [ ] ...

### CODE REVIEW

File: src/engine/source/logpar/include/logpar/logpar.hpp [hunk 1]
```diff
@@ -495,7 +495,7 @@ class Logpar
      * @throws std::runtime_error if errors occur while initializing
      */
     Logpar(const json::Json& fieldParserOverrides,
-           const std::shared_ptr<schemf::ISchema>& schema,
+           const std::shared_ptr<schemf::IValidator>& schema,
```
Comment (LucioDonda) [inline src/engine/source/logpar/include/logpar/logpar.hpp]: Shouldn't change the name of the variable to something like `schemaValidator` ?

File: src/engine/source/builder/src/policy/policy.cpp [hunk 2]
```diff
@@ -85,6 +85,18 @@ Policy::Policy(const cm::store::NamespaceId& namespaceId,
...
         }
 
+        // Cleanup decoder temporary variables
+        if (policyData.shouldCleanupDecoderVariables())
+        {
+            auto cleanupVars = base::Term<base::EngineOp>::create("CleanupDecoderVariables",
+                                                                  [](auto e)
+                                                                  {
+                                                                      e->eraseRootKeysByPrefix("_");
+                                                                      return base::result::makeSuccess(e, "");
```
Comment (NahuFigueroa97) [inline src/engine/source/builder/src/policy/policy.cpp]: Did you leave the trace empty for a reason? It would be good to know that the temporary variables were removed.

File: src/engine/source/builder/src/policy/policy.cpp [hunk 3]
```diff
@@ -85,6 +85,14 @@ Policy::Policy(const cm::store::NamespaceId& namespaceId,
             m_assets.insert(base::Name(traceable));
         }
 
+        // Cleanup decoder temporary variables (enabled/disabled according to policy)
+        {
```
Comment (jam300) [inline src/engine/source/builder/src/policy/policy.cpp:89]: Cleanup is still scheduled after `filter/UnclassifiedEvents` and `filter/DiscardedEvents`, so temporary `_ `fields remain in the event beyond the decoder tree. In a minimal repro, a decoder writes `_tmp.review_marker`, both filters run, and only then `cleanup/DecoderTemporaryVariables `removes it. With cleanup disabled, a later post-filter can still read `$_tmp.review_marker`, which suggests the lifetime of temporary fields is currently bounded by a later cleanup step instead of ending right after decoders.

Is this the expected behavior? Otherwise, I suggest moving this cleanup to the boundary immediately after the decoder tree, before any later filter/enrichment stage can observe temporary fields.

<details><summary>test 1</summary>
<p>

```yml

name: decoder/review-pr34778-cleanup-order/0
id: 11111111-1111-4111-8111-111111111111
enabled: true

metadata:
  module: review
  title: Cleanup order probe
  description: Minimal decoder to prove temporary cleanup ordering.
  compatibility: Review only
  versions:
    - Wazuh 5.*
  author:
    name: Codex
    date: 2026-03-12
  references:
    - https://github.com/wazuh/wazuh/pull/34778

normalize:
  - map:
      - _tmp.review_marker: visible_after_decoders
      - event.kind: event
      - event.category: array_append(process)
      - event.type: array_append(info)
      - message: cleanup-order-probe


```


```bash

(venv) ╭─root@wazuh5x-dev /workspaces/Wazuh_5x/wazuh ‹enhancement/34669-restrict-decoder-mappings●› 
╰─# engine-test run review_pr34778_case1 -n review_pr34778_case1 -dd

---
traces:
[🟢] decoder/review-pr34778-cleanup-order/0 -> success
  ↳ _tmp.review_marker: map("visible_after_decoders") -> Success
  ↳ event.kind: map("event") -> Success
  ↳ event.category: array_append("process") -> Success
  ↳ event.type: array_append("info") -> Success
  ↳ message: map("cleanup-order-probe") -> Success
[🟢] filter/UnclassifiedEvents -> success
  ↳ dropUnclassifiedEvent() -> Event is classified, allowing event
[🟢] filter/DiscardedEvents -> success
  ↳ Discard_event() -> Success: Event will be indexed (wazuh.space.event_discarded=false)
[🟢] cleanup/DecoderTemporaryVariables -> success
  ↳ cleanupDecoderTemporaryVariables() -> Success: Removed root keys prefixed with '_'

output:
  event:
    category:
    - process
    kind: event
    original: review_pr34778_case1
    type:
    - info
  message: cleanup-order-probe
  wazuh:
    integration:
      category: security
      decoders:
      - decoder/review-pr34778-cleanup-order/0
      name: integration/review-pr34778-case1/0
    protocol:
      location: '[001] (agent-ex) any->ReviewCase01'
      queue: 49
    space:
      name: review_pr34778

```

</p>
</details>


<details><summary>test 2</summary>
<p>

```yml

name: decoder/review-pr34778-temp-visible/0
id: 31111111-1111-4111-8111-111111111111
enabled: true

metadata:
  module: review
  title: Temporary visibility probe
  description: Minimal decoder to keep a temporary field for post-filter visibility checks.
  compatibility: Review only
  versions:
    - Wazuh 5.*
  author:
    name: Codex
    date: 2026-03-12
  references:
    - https://github.com/wazuh/wazuh/pull/34778

normalize:
  - map:
      - _tmp.review_marker: visible_after_decoders
      - event.kind: event
      - event.category: array_append(process)
      - event.type: array_append(info)
      - message: temp-visible-postfilter-probe



```


```bash

engine-test run review_pr34778_case1b -n review_pr34778_case1b -dd

---
traces:
[🟢] decoder/review-pr34778-temp-visible/0 -> success
  ↳ _tmp.review_marker: map("visible_after_decoders") -> Success
  ↳ event.kind: map("event") -> Success
  ↳ event.category: array_append("process") -> Success
  ↳ event.type: array_append("info") -> Success
  ↳ message: map("temp-visible-postfilter-probe") -> Success
[🟢] filter/UnclassifiedEvents -> success
  ↳ dropUnclassifiedEvent() -> Event is classified, allowing event
[🟢] filter/DiscardedEvents -> success
  ↳ Discard_event() -> Success: Event will be indexed (wazuh.space.event_discarded=false)
[🟢] cleanup/DecoderTemporaryVariables -> success
  ↳ cleanupDecoderTemporaryVariables() -> Skipped: Cleanup disabled by policy
[🟢] filter/review-pr34778-postfilter-visible/0 -> success
  ↳ [check: exists($_tmp.review_marker)] -> Success

output:
  _tmp:
    review_marker: visible_after_decoders
  event:
    category:
    - process
    kind: event
    original: review-pr34778-case1b
    type:
    - info
  message: temp-visible-postfilter-probe
  wazuh:
    integration:
      category: security
      decoders:
      - decoder/review-pr34778-temp-visible/0
      name: integration/review-pr34778-case1b/0
    protocol:
      location: '[001] (agent-ex) any->ReviewCase01B'
      queue: 49
    space:
      name: review_pr34778

```

</p>
</details>

File: src/engine/source/schemf/src/validator.cpp [hunk 4]
```diff
@@ -288,14 +301,39 @@ base::RespOrError<ValidationResult> Schema::Validator::validate(const DotPath& n
     return ValidationResult();
 }
 
-base::RespOrError<ValidationResult> Schema::Validator::validate(const DotPath& name, const ValidationToken& token) const
+base::RespOrError<TargetFieldKind> Schema::Validator::validateTargetField(const DotPath& name) const
```
Comment (jam300) [inline src/engine/source/schemf/src/validator.cpp:304]: This new target-field validation looks correct for direct assignments, but it does not appear to fully close object-merge paths. I reproduced a minimal case where a decoder writes `_tmp_payload.custom.foo `and then does `.: merge($_tmp_payload).` The merge succeeds and the final event contains custom.foo, so a non-WCS field can still be injected through object merge even though direct mapping to `custom.foo `is supposed to be rejected.

Is this the expected behavior? Otherwise, I suggest applying the same `WCS || root _ temporary` validation to every subfield introduced by merge operations as well.

<details><summary>test 1</summary>
<p>

```yml

name: decoder/review-pr34778-merge-bypass/0
id: 41111111-1111-4111-8111-111111111111
enabled: true

metadata:
  module: review
  title: Merge bypass probe
  description: Minimal decoder to test whether object merges can inject non-WCS fields.
  compatibility: Review only
  versions:
    - Wazuh 5.*
  author:
    name: Codex
    date: 2026-03-12
  references:
    - https://github.com/wazuh/wazuh/pull/34778

normalize:
  - map:
      - _tmp_payload.custom.foo: merged_non_wcs_value
      - event.kind: event
      - event.category: array_append(process)
      - event.type: array_append(info)
      - message: merge-bypass-probe
  - map:
      - .: merge($_tmp_payload)



```


```bash

(venv) ╭─root@wazuh5x-dev /workspaces/Wazuh_5x/wazuh ‹enhancement/34669-restrict-decoder-mappings●› 
╰─# engine-test run review_pr34778_case2 -n review_pr34778_case2 -dd


---
traces:
[🟢] decoder/review-pr34778-merge-bypass/0 -> success
  ↳ _tmp_payload.custom.foo: map("merged_non_wcs_value") -> Success
  ↳ event.kind: map("event") -> Success
  ↳ event.category: array_append("process") -> Success
  ↳ event.type: array_append("info") -> Success
  ↳ message: map("merge-bypass-probe") -> Success
  ↳ .: merge($_tmp_payload) -> Success
[🟢] filter/UnclassifiedEvents -> success
  ↳ dropUnclassifiedEvent() -> Event is classified, allowing event
[🟢] filter/DiscardedEvents -> success
  ↳ Discard_event() -> Success: Event will be indexed (wazuh.space.event_discarded=false)
[🟢] cleanup/DecoderTemporaryVariables -> success
  ↳ cleanupDecoderTemporaryVariables() -> Success: Removed root keys prefixed with '_'

output:
  custom:
    foo: merged_non_wcs_value
  event:
    category:
    - process
    kind: event
    original: review-pr34778-case2
    type:
    - info
  message: merge-bypass-probe
  wazuh:
    integration:
      category: security
      decoders:
      - decoder/review-pr34778-merge-bypass/0
      name: integration/review-pr34778-case2/0
    protocol:
      location: '[001] (agent-ex) any->ReviewCase02'
      queue: 49
    space:
      name: review_pr34778


```

</p>
</details>

File: src/engine/source/builder/src/policy/policy.cpp (hunk 3 above)
Comment (matigarciadev) [reply src/engine/source/builder/src/policy/policy.cpp:89]: This is expected. If any of the pre-enrichment operations fail, the entire pipeline fails and the event won't be indexed, so it's not a problem. This also avoids unnecessary work on events that were discarded by a pre-enrichment filter.

File: src/engine/source/schemf/src/validator.cpp (hunk 4 above)
Comment (matigarciadev) [reply src/engine/source/schemf/src/validator.cpp:304]: There is currently no runtime validation for fields resulting from a transform operation. This is a trade-off inherent in transform helper functions. This applies to the "." field as well as any other valid field that can be mapped to a decoder.

**Comment by jam300** [comment]
## LGTM


### Testing

<details><summary>test 1</summary>
<p>

```yml

name: decoder/review-pr34778-cleanup-order/0
id: 11111111-1111-4111-8111-111111111111
enabled: true

metadata:
  module: review
  title: Cleanup order probe
  description: Minimal decoder to prove temporary cleanup ordering.
  compatibility: Review only
  versions:
    - Wazuh 5.*
  author:
    name: Codex
    date: 2026-03-12
  references:
    - https://github.com/wazuh/wazuh/pull/34778

normalize:
  - map:
      - _tmp.review_marker: visible_after_decoders
      - event.kind: event
      - event.category: array_append(process)
      - event.type: array_append(info)
      - message: cleanup-order-probe


```


```bash

(venv) ╭─root@wazuh5x-dev /workspaces/Wazuh_5x/wazuh ‹enhancement/34669-restrict-decoder-mappings●› 
╰─# engine-test run review_pr34778_case1 -n review_pr34778_case1 -dd

---
traces:
[🟢] decoder/review-pr34778-cleanup-order/0 -> success
  ↳ _tmp.review_marker: map("visible_after_decoders") -> Success
  ↳ event.kind: map("event") -> Success
  ↳ event.category: array_append("process") -> Success
  ↳ event.type: array_append("info") -> Success
  ↳ message: map("cleanup-order-probe") -> Success
[🟢] filter/UnclassifiedEvents -> success
  ↳ dropUnclassifiedEvent() -> Event is classified, allowing event
[🟢] filter/DiscardedEvents -> success
  ↳ Discard_event() -> Success: Event will be indexed (wazuh.space.event_discarded=false)
[🟢] cleanup/DecoderTemporaryVariables -> success
  ↳ cleanupDecoderTemporaryVariables() -> Success: Removed root keys prefixed with '_'

output:
  event:
    category:
    - process
    kind: event
    original: review_pr34778_case1
    type:
    - info
  message: cleanup-order-probe
  wazuh:
    integration:
      category: security
      decoders:
      - decoder/review-pr34778-cleanup-order/0
      name: integration/review-pr34778-case1/0
    protocol:
      location: '[001] (agent-ex) any->ReviewCase01'
      queue: 49
    space:
      name: review_pr34778

```

</p>
</details>


<details><summary>test 2</summary>
<p>

```yml

name: decoder/review-pr34778-temp-visible/0
id: 31111111-1111-4111-8111-111111111111
enabled: true

metadata:
  module: review
  title: Temporary visibility probe
  description: Minimal decoder to keep a temporary field for post-filter visibility checks.
  compatibility: Review only
  versions:
    - Wazuh 5.*
  author:
    name: Codex
    date: 2026-03-12
  references:
    - https://github.com/wazuh/wazuh/pull/34778

normalize:
  - map:
      - _tmp.review_marker: visible_after_decoders
      - event.kind: event
      - event.category: array_append(process)
      - event.type: array_append(info)
      - message: temp-visible-postfilter-probe



```


```bash

engine-test run review_pr34778_case1b -n review_pr34778_case1b -dd

---
traces:
[🟢] decoder/review-pr34778-temp-visible/0 -> success
  ↳ _tmp.review_marker: map("visible_after_decoders") -> Success
  ↳ event.kind: map("event") -> Success
  ↳ event.category: array_append("process") -> Success
  ↳ event.type: array_append("info") -> Success
  ↳ message: map("temp-visible-postfilter-probe") -> Success
[🟢] filter/UnclassifiedEvents -> success
  ↳ dropUnclassifiedEvent() -> Event is classified, allowing event
[🟢] filter/DiscardedEvents -> success
  ↳ Discard_event() -> Success: Event will be indexed (wazuh.space.event_discarded=false)
[🟢] cleanup/DecoderTemporaryVariables -> success
  ↳ cleanupDecoderTemporaryVariables() -> Skipped: Cleanup disabled by policy
[🟢] filter/review-pr34778-postfilter-visible/0 -> success
  ↳ [check: exists($_tmp.review_marker)] -> Success

output:
  _tmp:
    review_marker: visible_after_decoders
  event:
    category:
    - process
    kind: event
    original: review-pr34778-case1b
    type:
    - info
  message: temp-visible-postfilter-probe
  wazuh:
    integration:
      category: security
      decoders:
      - decoder/review-pr34778-temp-visible/0
      name: integration/review-pr34778-case1b/0
    protocol:
      location: '[001] (agent-ex) any->ReviewCase01B'
      queue: 49
    space:
      name: review_pr34778

```

</p>
</details>


<details><summary>test 3</summary>
<p>

```yml


name: decoder/review-pr34778-merge-recursive-key-in-happy/0
id: 71111111-1111-4111-8111-111111111111
enabled: true

metadata:
  module: review
  title: Merge recursive key-in happy path
  description: Minimal decoder to validate merge_recursive_key_in with a valid WCS field.
  compatibility: Review only
  versions:
    - Wazuh 5.*
  author:
    name: Codex
    date: 2026-03-13
  references:
    - https://github.com/wazuh/wazuh/pull/34778

definitions:
  merge_map:
    dns:
      network:
        protocol: dns

normalize:
  - map:
      - _tmp_key: dns
      - network.transport: tcp
      - event.kind: event
      - event.category: array_append(process)
      - event.type: array_append(info)
      - message: merge-recursive-key-in-happy-path
  - map:
      - .: merge_recursive_key_in($merge_map, $_tmp_key)



```


```bash

(venv) ╭─root@wazuh5x-dev /workspaces/Wazuh_5x/wazuh ‹enhancement/34669-restrict-decoder-mappings●› 
╰─# engine-test -c /workspaces/Wazuh_5x/Reviews/PR-34778/case-02d-merge-recursive-key-in-happy-path/engine-test.conf run review_pr34778_case2d -n review_pr34778_case2d -dd < /workspaces/Wazuh_5x/Reviews/PR-34778/case-02d-merge-recursive-key-in-happy-path/event.txt

---
traces:
[🟢] decoder/review-pr34778-merge-recursive-key-in-happy/0 -> success
  ↳ _tmp_key: map("dns") -> Success
  ↳ network.transport: map("tcp") -> Success
  ↳ event.kind: map("event") -> Success
  ↳ event.category: array_append("process") -> Success
  ↳ event.type: array_append("info") -> Success
  ↳ message: map("merge-recursive-key-in-happy-path") -> Success
  ↳ .: merge_recursive_key_in({"dns":{"network":{"protocol":"dns"}}}, $_tmp_key) -> Success
[🟢] filter/UnclassifiedEvents -> success
  ↳ dropUnclassifiedEvent() -> Event is classified, allowing event
[🟢] filter/DiscardedEvents -> success
  ↳ Discard_event() -> Success: Event will be indexed (wazuh.space.event_discarded=false)
[🟢] cleanup/DecoderTemporaryVariables -> success
  ↳ cleanupDecoderTemporaryVariables() -> Success: Removed root keys prefixed with '_'

output:
  event:
    category:
    - process
    kind: event
    original: review-pr34778-case2d
    type:
    - info
  message: merge-recursive-key-in-happy-path
  network:
    protocol: dns
    transport: tcp
  wazuh:
    integration:
      category: security
      decoders:
      - decoder/review-pr34778-merge-recursive-key-in-happy/0
      name: integration/review-pr34778-case2d/0
    protocol:
      location: '[001] (agent-ex) any->ReviewCase02D'
      queue: 49
    space:
      name: review_pr34778

```

</p>
</details>
