### PR TITLE
Change to realtime when auditd is in immutable mode

### LINKED ISSUE #5400: Syscheck will not switch to realtime when whodata is enabled, Audit is set to immutable mode and wazuh_fim rule has not been written manually.
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.13.0-31306 | ossec-syscheckd | Agent | Packages | CentOS Linux 7  |

Hi team,

Enabling audit immutable mode is a security measure described here: https://secscan.acron.pl/centos7/4/1/18.

As the title of this issue states, `syscheck` will not switch to `realtime` mode when the following conditions are met:
-  `whodata` is enabled
- `audit` is set to `immutable` mode
- `wazuh_fim` rule has not been written manually.

These are the steps that I followed to configure whodata with immutable mode:

1. Disable `startup_healthcheck` in the syscheck configuration and monitor some directory with `whodata`:
```xml
<whodata>
  <startup_healthcheck>no</startup_healthcheck>
 </whodata>
 <directories check_attrs="yes" check_group="yes" check_inode="yes" check_mtime="yes" check_owner="yes" check_perm="yes" check_sha256sum="yes" check_size="yes" recursion_level="0" report_changes="yes" tags="appid=1234" whodata="yes">/test</directories>
```
2. Enable immutable mode and write the wazuh audit rule manually:
In `/etc/audit/rules.d/audit.rules`:
```
# This file contains the auditctl rules that are loaded
# whenever the audit daemon is started via the initscripts.
# The rules are simply the parameters that would be passed
# to auditctl.

# First rule - delete all
-D

# Increase the buffers to survive stress events.
# Make this bigger for busy systems
-b 320

#Wazuh ule
-w /test/ -p wa -k wazuh_fim

# Immutable mode
-e 2
```

3. Reload the rules file:
`auditctl -R /etc/audit/rules.d/audit.rules`

At this point, whodata should be working fine. Now, let's recreate the issue:

1. Comment the wazuh audit rule in `/etc/audit/rules.d/audit.rules`:
```
# This file contains the auditctl rules that are loaded
# whenever the audit daemon is started via the initscripts.
# The rules are simply the parameters that would be passed
# to auditctl.

# First rule - delete all
-D

# Increase the buffers to survive stress events.
# Make this bigger for busy systems
-b 320

#Wazuh ule
#-w /test/ -p wa -k wazuh_fim

# Immutable mode
-e 2
```

2. Reboot the system: `reboot`.
At this point, syscheck should have switched to `realtime` mode. Instead, `realtime` will not be working, but syscheck will run scheduled scans (according to the configured `frequency`).

# Logs with `syscheck.debug=2`:
[syschecklogs.txt](https://github.com/wazuh/wazuh/files/4870499/syschecklogs.txt)

The expected behavior for syscheck would be to switch to `realtime` mode when`whodata` is not working due to the absence of the audit rule.

Let me know if you need any further information.

Regards,
Sergio.

### PR DESCRIPTION
**Pull request by jesusjimsa**
| Related issue |
| ------------- |
| #5400         |

## Description

This pull request fixes the case where directories would not change to realtime when Auditd is in immutable mode. To do this, `check_auditd_enabled` has been rewritten to check the status of Auditd instead of getting its PID. when this function returns 2 (immutable), all directories which don't already have audit rules added to them will change to realtime.

Here, I also changed how the Auditd file descriptor is handled, opening it only once in `audit_init` instead of opening and closing it every time `add_audit_rules_syscheck` was called.

This pull request closes #5400.

## Tests

- Compilation without warnings in every supported platform
  - [x] Linux
- [x] Source installation
- [x] Package installation
- [x] Review logs syntax and correct language

- Memory tests for Linux
  - [x] Scan-build report
  - [x] Valgrind (memcheck and descriptor leaks check)

- [x] Added unit tests (for new features)

### CODE REVIEW

**Comment by jesusjimsa** [comment]
# scan-build
No new bugs were introduced in this pull request.
[scan-build.zip](https://github.com/wazuh/wazuh/files/5643556/scan-build.zip)

**Comment by jesusjimsa** [comment]
# Valgrind
No memory leaks found with valgrind.

**Review by Molter73 — CHANGES_REQUESTED** [review]
Having the audit netlink socket permanently open could bring compatibility issues with other processes, (such as `auditctl`), I recommend going back to opening and closing it whenever we need it.

I don't see any unit tests on `audit_no_rules_to_realtime`, we should add them to guarantee that configured directories are left in the desired state.

File: src/syscheckd/syscheck_audit.c [hunk 1]
```diff
@@ -89,27 +90,19 @@ static regex_t regexCompiled_dev;
...
 
-    while (proc_info = readproc(proc, NULL), proc_info != NULL) {
-        if(strcmp(proc_info->cmd,"auditd") == 0) {
-            auditd_pid = proc_info->tid;
-            freeproc(proc_info);
-            break;
-        }
-
-        freeproc(proc_info);
+    if (audit_get_reply(auditd_fd, &rep, GET_REPLY_BLOCKING, 0) <= 0) {
```
[the remark this answers is not in the document]
Comment (jesusjimsa) [reply src/syscheckd/syscheck_audit.c:100]: I have changed `GET_REPLY_BLOCKING` to `GET_REPLY_NONBLOCKING` and seems to be working. We may not have to user `kernel_get_reply` or something like that.

[the remark this answers is not in the document]
Comment (jesusjimsa) [reply src/syscheckd/syscheck_audit.c:100]: It seems that having `GET_REPLY_NONBLOCKING` with auditd in "normal" mode will cause `audit_get_reply` to fail.

File: src/syscheckd/syscheck.h [hunk 2]
```diff
@@ -495,10 +495,17 @@ void audit_set_db_consistency(void);
 /**
  * @brief Check if Auditd is installed and running
  *
- * @return The PID of Auditd
+ * @return -1 on error, 0 when Auditd is disabled, 1 when Auditd is enabled and 2 when it is enabled and
+ * in immutable mode
```
Comment (antoniomanuelfr) [inline src/syscheckd/syscheck.h:499]: We should discuss using an enum here (instead of returning 0 return AUDIT_DIS). This will help us improve code readability.

**Review by antoniomanuelfr — APPROVED** [review]
LGTM

File: src/syscheckd/syscheck_audit.c (hunk 1 above)
[the remark this answers is not in the document]
Comment (jesusjimsa) [reply src/syscheckd/syscheck_audit.c:100]: I have created `audit_get_mode`, a function that uses `GET_REPLY_NONBLOCKING` in `audit_get_reply` and will try to get the mode a number of times (40 attempts now). If `audit_get_reply` doesn't work correctly, `AUDIT_ERROR` (`-1`) will be returned.

File: src/syscheckd/syscheck.h [hunk 3]
```diff
@@ -493,12 +493,18 @@ void audit_read_events(int *audit_sock, int reading_mode);
 void audit_set_db_consistency(void);
 
 /**
- * @brief Check if Auditd is installed and running
+ * @brief Check if the Auditd daemon is installed and running
```
Comment (antoniomanuelfr) [inline src/syscheckd/syscheck.h:496]:
```suggestion
 * @brief Check if the Audit daemon is installed and running
```

**Review by antoniomanuelfr — CHANGES_REQUESTED** [review]

File: src/shared/audit_op.c [hunk 4]
```diff
@@ -124,6 +124,43 @@ void kernel_get_reply(int fd) {
...
+    for (i = 0; i < attempts; i++) {
+        reply_retval = audit_get_reply(auditd_fd, &rep, GET_REPLY_NONBLOCKING, 0);
+
+        if (reply_retval > 0) {
+            audit_close(auditd_fd);
+            return rep.status->enabled;
+        }
+
+        sleep(1);
+    }
```
Comment (Molter73) [inline src/shared/audit_op.c:154]: Instead of retrying constantly to get a value we should use `select` to either wait for a message or exit with an error if a response was not received in a given time.

File: src/syscheckd/syscheck_audit.c [hunk 5]
```diff
@@ -274,6 +273,24 @@ int add_audit_rules_syscheck(bool first_time) {
...
+        if (syscheck.opts[i] & WHODATA_ACTIVE) {
+            found = search_audit_rule(fim_get_real_path(i), "wa", AUDIT_KEY);
+
+            if (found == 0) {   // No rule found
+                mwarn(FIM_ERROR_WHODATA_ADD_DIRECTORY, fim_get_real_path(i));
+                syscheck.opts[i] &= ~WHODATA_ACTIVE;
+                syscheck.opts[i] |= REALTIME_ACTIVE;
+            }
+        }
+    }
```
Comment (Molter73) [inline src/syscheckd/syscheck_audit.c:290]: The content of this for loop could be rewritten so it has one less level of indentation by using a `continue` with the inverted condition of the first if, like this:
```c
    for (i = 0; syscheck.dir[i] != NULL; i++) {
        if ((syscheck.opts[i] & WHODATA_ACTIVE) == 0) {
            continue;
        }

        found = search_audit_rule(fim_get_real_path(i), "wa", AUDIT_KEY);

        if (found == 0) {   // No rule found
            mwarn(FIM_ERROR_WHODATA_ADD_DIRECTORY, fim_get_real_path(i));
            syscheck.opts[i] &= ~WHODATA_ACTIVE;
            syscheck.opts[i] |= REALTIME_ACTIVE;
        }
    }
```

File: src/syscheckd/syscheck_audit.c [hunk 6]
```diff
@@ -434,7 +451,9 @@ int audit_init(void) {
 
     // Check if auditd is installed and running.
     int aupid = check_auditd_enabled();
-    if (aupid <= 0) {
+    int audit_status = audit_get_mode();
+
+    if (aupid <= 0 || audit_status < 1) {
         mwarn(FIM_AUDIT_NORUNNING);
         return (-1);
     }
```
Comment (Molter73) [inline src/syscheckd/syscheck_audit.c:459]: The message printed by this `mwarn` states that auditd is not running, could it happen that auditd is running and audit is disabled? Does it make sense to use a different log message for this situation.

Also, `audit_get_mode` returns a value from the newly created `audit_status` but here it's being casted to an int, can we change the type of storage variable and change the if condition to properly reflect this?

File: src/syscheckd/syscheck_audit.c [hunk 7]
```diff
@@ -479,6 +498,12 @@ int audit_init(void) {
     audit_added_dirs = W_Vector_init(20);
 
     add_audit_rules_syscheck(true);
+
+    // Change to realtime directories that don't have any rules when Auditd is in immutable mode
+    if (audit_status == AUDIT_IMMUTABLE) {
```
Comment (Molter73) [inline src/syscheckd/syscheck_audit.c:503]: Related to the previous comment, `audit_status` is of type int but we are checking its value to `AUDIT_IMMUTABLE`, can we change its type?

File: src/shared/audit_op.c [hunk 8]
```diff
@@ -124,6 +124,43 @@ void kernel_get_reply(int fd) {
 }
 
 
+int audit_get_mode() {
```
Comment (Molter73) [inline src/shared/audit_op.c:127]: Shouldn't the return type of this function be of type `audit_status`?

**Review by Molter73 — CHANGES_REQUESTED** [review]

File: src/shared/audit_op.c (hunk 4 above)
Comment (jesusjimsa) [reply src/shared/audit_op.c:154]: I am going to delete this function after finding `audit_is_enabled`
https://github.com/linux-audit/audit-userspace/blob/master/lib/libaudit.c#L359-L415

**Comment by Molter73** [comment]
We've run integration tests on Centos and Ubuntu systems under realtime and whodata modes and no failures/errors were detected
[agent_centos_html_report_test_integration_B843_20201217124131.zip](https://github.com/wazuh/wazuh/files/5710284/agent_centos_html_report_test_integration_B843_20201217124131.zip)
[agent_ubuntu_html_report_test_integration_B843_20201217124131.zip](https://github.com/wazuh/wazuh/files/5710285/agent_ubuntu_html_report_test_integration_B843_20201217124131.zip)

**Review by Molter73 — APPROVED** [review]
LGTM!

**Review by vikman90 — APPROVED** [review]
