### PR TITLE
Adapt registry synchronization mechanism

### LINKED ISSUE #7836: The agent on Windows has crashed
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.1.2 | Agent service | Agent | Packages | Windows 8 |

## Crash report

<details>
  <summary>Report</summary>

```
Version=1
EventType=APPCRASH
EventTime=132598629568993331
ReportType=2
Consent=1
ReportIdentifier=82ca7860-81b3-11eb-b827-005056962179
IntegratorReportIdentifier=5df19b18-eac0-41ca-b40d-b40c83613a4f
WOW64=1
NsAppName=ossec-agent.exe
AppSessionGuid=000012f8-0000-002e-645c-463ebd15d701
TargetAppId=W:0000ba5cf28d3c7f3b889b0e166a9921ad7c00000904!000085adce91ca7c894ef9868557cd22e15deb2a93be!ossec-agent.exe
TargetAppVer=2021//03//05:13:47:00!1d8bac!ossec-agent.exe
BootId=4294967295
Response.type=4
Sig[0].Name=Application Name
Sig[0].Value=ossec-agent.exe
Sig[1].Name=Application Version
Sig[1].Value=0.0.0.0
Sig[2].Name=Application Timestamp
Sig[2].Value=60423654
Sig[3].Name=Fault Module Name
Sig[3].Value=ossec-agent.exe
Sig[4].Name=Fault Module Version
Sig[4].Value=0.0.0.0
Sig[5].Name=Fault Module Timestamp
Sig[5].Value=60423654
Sig[6].Name=Exception Code
Sig[6].Value=c0000005
Sig[7].Name=Exception Offset
Sig[7].Value=0000e6e5
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=10.0.14393.2.0.0.272.7
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=1033
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=6582
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=65827c5ac1cffbf1d2cbfbed3c201de5
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=c34d
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=c34d1c9a497c5d7acf9652a3d0565a36
UI[2]=C:\Program Files (x86)\ossec-agent\ossec-agent.exe
UI[5]=Check online for a solution (recommended)
UI[6]=Check for a solution later (recommended)
UI[7]=Close
UI[8]=ossec-agent.exe stopped working and was closed
UI[9]=A problem caused the application to stop working correctly. Windows will notify you if a solution is available.
UI[10]=&Close
LoadedModule[0]=C:\Program Files (x86)\ossec-agent\ossec-agent.exe
LoadedModule[1]=C:\Windows\SYSTEM32\ntd1l.dll
LoadedModule[2]=C:\Windows\System32\kern3l32.dll
LoadedModule[3]=C:\Windows\SYSTEM32\ntdll.dll
LoadedModule[4]=C:\Windows\System32\KERNEL32.DLL
LoadedModule[5]=C:\Windows\System32\KERNELBASE.dll
LoadedModule[6]=C:\Program Files\SentinelOne\Sentinel Agent 4.2.5.168\InProcessClient32.dll
LoadedModule[7]=C:\Windows\System32\ADVAPI32.dll
LoadedModule[8]=C:\Windows\System32\msvcrt.dll
LoadedModule[9]=C:\Windows\System32\sechost.dll
LoadedModule[10]=C:\Windows\System32\RPCRT4.dll
LoadedModule[11]=C:\Windows\System32\SspiCli.dll
LoadedModule[12]=C:\Windows\System32\CRYPTBASE.dll
LoadedModule[13]=C:\Windows\System32\bcryptPrimitives.dll
LoadedModule[14]=C:\Windows\System32\PSAPI.DLL
LoadedModule[15]=C:\Windows\System32\SHLWAPI.dll
LoadedModule[16]=C:\Windows\System32\combase.dll
LoadedModule[17]=C:\Program Files (x86)\ossec-agent\libwinpthread-1.dll
LoadedModule[18]=C:\Windows\System32\ucrtbase.dll
LoadedModule[19]=C:\Windows\SYSTEM32\IPHLPAPI.DLL
LoadedModule[20]=C:\Windows\System32\GDI32.dll
LoadedModule[21]=C:\Windows\System32\gdi32full.dll
LoadedModule[22]=C:\Windows\System32\USER32.dll
LoadedModule[23]=C:\Windows\System32\win32u.dll
LoadedModule[24]=C:\Windows\System32\WS2_32.dll
LoadedModule[25]=C:\Windows\SYSTEM32\wevtapi.dll
LoadedModule[26]=C:\Windows\SYSTEM32\WSOCK32.DLL
LoadedModule[27]=C:\Program Files (x86)\ossec-agent\libwazuhext.dll
LoadedModule[28]=C:\Windows\SYSTEM32\bcrypt.dll
LoadedModule[29]=C:\Windows\System32\CRYPT32.dll
LoadedModule[30]=C:\Windows\System32\MSASN1.dll
LoadedModule[31]=C:\Windows\SYSTEM32\VERSION.dll
LoadedModule[32]=C:\Windows\SYSTEM32\CRYPTSP.dll
LoadedModule[33]=C:\Windows\system32\rsaenh.dll
LoadedModule[34]=C:\Windows\System32\profapi.dll
LoadedModule[35]=C:\Windows\system32\mswsock.dll
LoadedModule[36]=C:\Windows\System32\NSI.dll
LoadedModule[37]=C:\Windows\SYSTEM32\dhcpcsvc6.DLL
LoadedModule[38]=C:\Windows\SYSTEM32\dhcpcsvc.DLL
LoadedModule[39]=C:\Program Files (x86)\ossec-agent\syscollector_win_ext.dll
LoadedModule[40]=C:\Windows\system32\napinsp.dll
LoadedModule[41]=C:\Windows\SYSTEM32\DNSAPI.dll
LoadedModule[42]=C:\Windows\System32\winrnr.dll
LoadedModule[43]=C:\Windows\system32\NLAapi.dll
LoadedModule[44]=C:\Windows\SYSTEM32\ntmarta.dll
FriendlyEventName=Stopped working
ConsentKey=APPCRASH
AppName=ossec-agent.exe
AppPath=C:\Program Files (x86)\ossec-agent\ossec-agent.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=62C8EE9F91BFFB63B51E5EE4E680E67A
MetadataHash=1351108878
```

</details>

## Log

<details>
  <summary>ossec.log</summary>

```
2021/03/10 09:54:17 ossec-agent: INFO: (6000): Starting daemon...
2021/03/10 09:54:17 rootcheck: INFO: Starting rootcheck scan.
2021/03/10 09:54:17 ossec-agent: INFO: (6010): File integrity monitoring scan frequency: 43200 seconds
2021/03/10 09:54:17 ossec-agent: INFO: (6008): File integrity monitoring scan started.
2021/03/10 09:54:17 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2021/03/10 09:54:20 sca: INFO: Evaluation finished for policy 'C:\Program Files (x86)\ossec-agent\ruleset\sca\sca_win_audit.yml'
2021/03/10 09:54:20 sca: INFO: Security Configuration Assessment scan finished. Duration: 4 seconds.
2021/03/10 09:54:20 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2021/03/10 09:54:22 rootcheck: INFO: Ending rootcheck scan.
2021/03/10 09:54:38 ossec-agent: INFO: (6009): File integrity monitoring scan ended.
2021/03/10 09:54:38 ossec-agent: INFO: (6012): Real-time file integrity monitoring started.
```

</details>

### PR DESCRIPTION
**Pull request by antoniomanuelfr**
|Related issue|
|---|
|#7836|

This PR aims to fix the sync mechanism between the windows agent and the manager when the values contained in a key start with `:`.  Now when a key or value contains a `:`, it's scaped and when the synchronization is performed, these values are unescaped again.

Closes #7836

## Configuration options
```xml
 <syscheck>

    <disabled>no</disabled>

    <!-- Frequency that syscheck is executed default every 12 hours -->
    <frequency>2</frequency>
    <windows_registry arch="both">HKEY_LOCAL_MACHINE\Software\random_key</windows_registry>

    <!-- Database synchronization settings -->
    <synchronization>
      <enabled>yes</enabled>
      <interval>1m</interval>
      <max_interval>1h</max_interval>
      <max_eps>10</max_eps>
    </synchronization>
  </syscheck>

```

## Logs/Alerts example
The synchronization messages now are correctly decoded: 

```
2021/04/07 13:44:22 wazuh-agent[848] run_check.c:82 at fim_send_sync_msg(): DEBUG: (6317): Sending integrity control message: {"component":"fim_registry","type":"state","data":{"path":"HKEY_LOCAL_MACHINE\\Software\\random_key","arch":"[x64]","timestamp":1617799462,"attributes":{"type":"registry_key","perm":"Usuarios (allowed): read_control|read_data|read_ea|write_ea, Usuarios (allowed): generic_read, Administradores (allowed): delete|read_control|write_dac|write_owner|read_data|write_data|append_data|read_ea|write_ea|execute, Administradores (allowed): generic_all, SYSTEM (allowed): delete|read_control|write_dac|write_owner|read_data|write_data|append_data|read_ea|write_ea|execute, SYSTEM (allowed): generic_all, CREATOR OWNER (allowed): generic_all","uid":"S-1-5-32-544","user_name":"Administradores","gid":"S-1-5-21-3527455827-79240758-596275861-513","group_name":"","mtime":1617722229,"checksum":"b31b92d3ab7006c014dd562b228f5859932c1027"},"version":"2.0"}}
2021/04/07 13:44:22 wazuh-agent[848] run_check.c:82 at fim_send_sync_msg(): DEBUG: (6317): Sending integrity control message: {"component":"fim_registry","type":"state","data":{"timestamp":1617799462,"path":"HKEY_LOCAL_MACHINE\\Software\\random_key","arch":"[x64]","value_name":":thisisatest","attributes":{"type":"registry_value","value_type":"REG_SZ","size":1,"hash_md5":"d41d8cd98f00b204e9800998ecf8427e","hash_sha1":"da39a3ee5e6b4b0d3255bfef95601890afd80709","hash_sha256":"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855","checksum":"4ca7b88b201728c31afb691707c41d35a984317d"},"version":"2.0"}}
2021/04/07 13:44:22 wazuh-agent[848] run_check.c:82 at fim_send_sync_msg(): DEBUG: (6317): Sending integrity control message: {"component":"fim_registry","type":"state","data":{"path":"HKEY_LOCAL_MACHINE\\Software\\random_key\\:newkey:","arch":"[x64]","timestamp":1617799462,"attributes":{"type":"registry_key","perm":"Usuarios (allowed): read_control|read_data|read_ea|write_ea, Usuarios (allowed): generic_read, Administradores (allowed): delete|read_control|write_dac|write_owner|read_data|write_data|append_data|read_ea|write_ea|execute, Administradores (allowed): generic_all, SYSTEM (allowed): delete|read_control|write_dac|write_owner|read_data|write_data|append_data|read_ea|write_ea|execute, SYSTEM (allowed): generic_all, CREATOR OWNER (allowed): generic_all","uid":"S-1-5-32-544","user_name":"Administradores","gid":"S-1-5-21-3527455827-79240758-596275861-513","group_name":"","mtime":1617797960,"checksum":"99db959b54481ab4ec2f0b5906edb703254c6958"},"version":"2.0"}}
2021/04/07 13:44:22 wazuh-agent[848] run_check.c:82 at fim_send_sync_msg(): DEBUG: (6317): Sending integrity control message: {"component":"fim_registry","type":"state","data":{"timestamp":1617799462,"path":"HKEY_LOCAL_MACHINE\\Software\\random_key\\:newkey:","arch":"[x64]","value_name":":sdaf","attributes":{"type":"registry_value","value_type":"REG_SZ","size":12,"hash_md5":"c31e41940cd12cf9b24b0e528ab955bc","hash_sha1":"2b487009fe43ee00158ba4c05b201d2702f30881","hash_sha256":"b897e454e5dac59345d6b879207383d6e196d01df9d09cb711671f7680a8b8c9","checksum":"85c2868e366cdd87bbb67daa95ad10f75a6f7e19"},"version":"2.0"}}
2021/04/07 13:44:22 wazuh-agent[848] run_check.c:82 at fim_send_sync_msg(): DEBUG: (6317): Sending integrity control message: {"component":"fim_registry","type":"state","data":{"timestamp":1617799462,"path":"HKEY_LOCAL_MACHINE\\Software\\random_key\\:newkey:","arch":"[x64]","value_name":"asdfasdfads","attributes":{"type":"registry_value","value_type":"REG_SZ","size":1,"hash_md5":"d41d8cd98f00b204e9800998ecf8427e","hash_sha1":"da39a3ee5e6b4b0d3255bfef95601890afd80709","hash_sha256":"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855","checksum":"4ca7b88b201728c31afb691707c41d35a984317d"},"version":"2.0"}}
2021/04/07 13:44:25 wazuh-agent[848] create_db.c:128 at fim_scan(): INFO: (6008): File integrity monitoring scan started.
```

And the manager database is updated correctly: 
```
root@ubuntumanager:/var/ossec/queue/db# sqlite3 015.db "select full_path from fim_entry"
[x64] HKEY_LOCAL_MACHINE\Software\random_key:
[x64] HKEY_LOCAL_MACHINE\Software\random_key:\:thisisatest
[x64] HKEY_LOCAL_MACHINE\Software\random_key\\:newkey\::
[x64] HKEY_LOCAL_MACHINE\Software\random_key\\:newkey\::\:sdaf
[x64] HKEY_LOCAL_MACHINE\Software\random_key\\:newkey\::asdfasdfads
root@ubuntumanager:/var/ossec/queue/db# 
```

## Tests

- Compilation without warnings in every supported platform
  - [x] Linux
  - [x] Windows
- [X] Source installation
- [X] Source upgrade

- Memory tests for Linux
  - [x] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [x] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory

### CODE REVIEW

**Review by jotacarma90 — APPROVED** [review]

**Comment by antoniomanuelfr** [comment]
These are  the result of the integration test executed in jenkins in CUW:

[agent_windows_html_report_test_integration_B1607_20210413085941.zip](https://github.com/wazuh/wazuh/files/6304377/agent_windows_html_report_test_integration_B1607_20210413085941.zip)
[agent_ubuntu_html_report_test_integration_B1607_20210413085941.zip](https://github.com/wazuh/wazuh/files/6304376/agent_ubuntu_html_report_test_integration_B1607_20210413085941.zip)
[agent_centos_html_report_test_integration_B1607_20210413085941.zip](https://github.com/wazuh/wazuh/files/6304375/agent_centos_html_report_test_integration_B1607_20210413085941.zip)

**Review by jotacarma90 — APPROVED** [review]

File: src/wazuh_db/wdb_fim.c [hunk 1]
```diff
@@ -515,6 +515,13 @@ int wdb_fim_insert_entry2(wdb_t * wdb, const cJSON * data) {
         return -1;
     }
 
+    item_version = cJSON_GetStringValue(cJSON_GetObjectItem(data, "version"));
+
+    if (item_version == NULL) {
+        merror("DB(%s) fim/save request with no version attribute.", wdb->id);
```
Comment (vikman90) [inline src/wazuh_db/wdb_fim.c:521]: Does this mean that we will have an error for each sync attempt from older agents?

File: src/shared/integrity_op.c [hunk 2]
```diff
@@ -40,6 +40,7 @@ char * dbsync_check_msg(const char * component, dbsync_msg msg, long id, const c
     cJSON * data = cJSON_CreateObject();
     cJSON_AddItemToObject(root, "data", data);
     cJSON_AddNumberToObject(data, "id", id);
+    cJSON_AddStringToObject(data, "version", "2.0");
```
Comment (vikman90) [inline src/shared/integrity_op.c:43]: Why don't we use a numeric version? It's much easier to handle when we need to compare.

**Review by vikman90 — CHANGES_REQUESTED** [review]

**Review by vikman90 — APPROVED** [review]
