### PR TITLE
FIM v2.0: Fix delete alerts for realtime and whodata modes

### LINKED ISSUE #4663: FIM v2.0: Deleted events being sent as scheduled instead of whodata
| Wazuh version | Component        | Install type          | Install method        |
|----------------|-----------------|-----------------|--------------------|
| 3.12                   | ossec-syscheck | Manager/Agent  | Packages/Sources |

## Bug description

When moving a folder with a file in it from a monitored directory to a non monitored directory or when moving a folder from a subfolder in a monitored directory to the monitored directory itself, the `deleted` event appears as `scheduled` instead of `whodata`, losing also the `audit` information.

## Alert example

```
** Alert 1582708903.12460: - ossec,syscheck,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,
2020 Feb 26 09:21:43 agentUbuntu19->syscheck
Rule: 553 (level 7) -> 'File deleted.'
File '/testdir2/subdir2/regular2' deleted
Mode: scheduled

Attributes:
 - Size: 0
 - Permissions: rw-r--r--
 - Date: Wed Feb 26 09:21:40 2020
 - Inode: 1029503
 - User: root (0)
 - Group: root (0)
 - MD5: d41d8cd98f00b204e9800998ecf8427e
 - SHA1: da39a3ee5e6b4b0d3255bfef95601890afd80709
 - SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
```

Mode should be `whodata` and it should include `Audit` information.

## Remediation

In `fim_db.c`, `deleted` events are hardcoded to be in `scheduled` mode:
https://github.com/wazuh/wazuh/blob/c7a2c86919bdb59949ced64987af1f85e2083dc5/src/syscheckd/fim_db.c#L1117-L1118  

This should be parametrized.

### PR DESCRIPTION
**Pull request by jesusjimsa**
| Related issue  |
|---------------|
| #4663             |

## Description

Modified callback functions' headers and parametrized the deletion of folders to check `FIM MODE` and `whodata information`.

Closes #4663.

## Tests

- Compilation without warnings in every supported platform
  - [x] Linux
  - [x] Windows
  - [x] MAC OS X
- [x] Source installation
- [x] Package installation
- [x] Source upgrade
- [ ] Package upgrade
- [x] Review logs syntax and correct language
- [x] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

### CODE REVIEW

File: src/syscheckd/fim_db.c [hunk 1]
```diff
@@ -1138,33 +1145,39 @@ void fim_db_remove_path(fdb_t *fim_sql, fim_entry *entry, pthread_mutex_t *mutex
...
         case FIM_SCHEDULED:
             if (!(syscheck.opts[conf_file] & SCHEDULED_ACTIVE)) {
+                fim_db_remove_path(fim_sql, entry, mutex, (void *) (int) false, (void *) mode, w_evt);
                 return;
             }
             break;
     }
 
-    fim_db_remove_path(fim_sql, entry, mutex, (void *) (int) 1);
+    fim_db_remove_path(fim_sql, entry, mutex, (void *) (int) true, (void *) mode, w_evt);
```
Comment (bah07) [inline src/syscheckd/fim_db.c]: Please define two constants to name that parameter as alert or non-alert.

File: src/syscheckd/create_db.c [hunk 2]
```diff
@@ -147,7 +147,8 @@ void fim_checker(char *path, fim_element *item, whodata_evt *w_evt, int report)
 
         if (saved_entry) {
             json_event = fim_json_event(path, NULL, saved_entry->data, item->index, FIM_DELETE, item->mode, w_evt);
-            fim_db_remove_path(syscheck.database, saved_entry, &syscheck.fim_entry_mutex, (void *) (int) 0);
+            fim_db_remove_path(syscheck.database, saved_entry, &syscheck.fim_entry_mutex, (void *) (int) false,
```
[the remark this answers is not in the document]
Comment (jesusjimsa) [reply src/syscheckd/create_db.c]: To make it clearer that it is not sending an alert.
That value is only checked here:  

https://github.com/wazuh/wazuh/blob/b1b4d075e27bf6e7a8227957f5d3c52e1b9e2e7c/src/syscheckd/fim_db.c#L1110

I thought it would be clearer since it works as a boolean.

File: src/syscheckd/fim_db.c (hunk 1 above)
Comment (jesusjimsa) [reply src/syscheckd/fim_db.c]: Fixed 6cd233d

File: src/syscheckd/fim_db.c [hunk 3]
```diff
@@ -528,27 +529,29 @@ int fim_db_exec_simple_wquery(fdb_t *fim_sql, const char *query) {
...
-            storage, (void *) (int) 0);
+    return fim_db_process_read_file(fim_sql, file, mutex, fim_db_callback_sync_path_range, storage,
+                                    (void *) (int) 0, (void *) (int) 0);
 }
 
 int fim_db_delete_not_scanned(fdb_t * fim_sql, fim_tmp_file *file, pthread_mutex_t *mutex, int storage) {
-    return fim_db_process_read_file(fim_sql, file, mutex, fim_db_remove_path,
-            storage, (void *) (int) 1);
+    return fim_db_process_read_file(fim_sql, file, mutex, fim_db_process_path, storage,
+                                    (void *) (int) FIM_SCHEDULED, (void *) (int) 0);
```
[the remark this answers is not in the document]
Comment (jesusjimsa) [reply src/syscheckd/fim_db.c]: Fixed 6cd233d

File: src/syscheckd/fim_db.c [hunk 4]
```diff
@@ -528,27 +531,34 @@ int fim_db_exec_simple_wquery(fdb_t *fim_sql, const char *query) {
...
+    return fim_db_process_read_file(fim_sql, file, mutex, fim_db_process_path, storage, (void *) (fim_event_mode) mode,
+                                    (void *) w_evt, NULL);
 }
 
+/* 
+    TODO:
+        - Move mode, w_evt and send_alert to an array to not send so many unused variables to
+        the functions that don't need them.
+ */
 int fim_db_process_read_file(fdb_t *fim_sql, fim_tmp_file *file, pthread_mutex_t *mutex,
```
Comment (0xN3utr0n) [inline src/syscheckd/fim_db.c]: For simplicity's sake, we should add all these optional parameters(`send_alert`, `wet` and `mode`) into an array. With this, the code would be much more readable and modular.

**Comment by wazuhci** [comment]
The stress test has been launched. The charts will be posted when they are ready.
I will use the following configuration:
### General
- Commit: 6d98392
- Packages: 
  - [manager 3.12.0 0.branch4663deletedeventsscheduledinsteadwhodata.commit6d98392 rpm](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/rpm/var/wazuh-manager-3.12.0-0.branch4663deletedeventsscheduledinsteadwhodata.commit6d98392.x86_64.rpm)
  - [agent 3.12.0 0.branch4663deletedeventsscheduledinsteadwhodata.commit6d98392 rpm](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/rpm/var/wazuh-agent-3.12.0-0.branch4663deletedeventsscheduledinsteadwhodata.commit6d98392.x86_64.rpm)
  - [manager 3.12.0 0.branch4663deletedeventsscheduledinsteadwhodata.commit6d98392 deb](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/deb/var/wazuh-manager_3.12.0-0.branch4663deletedeventsscheduledinsteadwhodata.commit6d98392_amd64.deb)
  - [agent 3.12.0 0.branch4663deletedeventsscheduledinsteadwhodata.commit6d98392 deb](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/deb/var/wazuh-agent_3.12.0-0.branch4663deletedeventsscheduledinsteadwhodata.commit6d98392_amd64.deb)
  - [agent 3.12.0 0.branch4663deletedeventsscheduledinsteadwhodata.commit6d98392 msi](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/windows/wazuh-agent-3.12.0-0.branch4663deletedeventsscheduledinsteadwhodata.commit6d98392.msi)

### Stress test parameters:
- Manager system: `centos`
- Launch CentOS agent: `true`
- Launch Ubuntu agent: `true`
- Launch Windows agent: `true`
- Test duration: `60`
- Scan frequency: `10`
- Modules to test: 
  - logcollector: `true`
  - syscheck: `true`
  - rootcheck: `true`
  - sca: `true`
  - osquery: `true`
  - syscollector: `true`
  - active-response: `true`
  - azure-logs: `true`
  - cis-cat: `true`
  - docker-listener: `true`
  - open-scap: `true`
  - vulnerability-detector: `false`
- FIM special test: `None`
- FIM sleep: `300`
- FIM max files: `25000`
- SCA sleep: `30`
- SCA max registers: `5000`
- Docker image name: `hello-world`
- Docker sleep: `5`
- Docker jobs: `10`
- Logcollector special test: `None`
- Logcollector max files: `50000`
- Logcollector creation sleep: `300`
- Logcollector write files: `1000`
- Logcollector write sleep: `10`
- Vuln sleep: `60`
- Authd port: `1515`
- Syscollector package: `imagemagick.app`
- Syscollector package version: `7.0.8.48`

Regards!.

File: src/syscheckd/fim_db.c (hunk 3 above)
[the remark this answers is not in the document]
Comment (jesusjimsa) [reply src/syscheckd/fim_db.c]: That 0 is not for `alert`, it's for `w_evt`

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind logcollector analysis:
**Commit:** 6d98392f9a6518d26fceb27d1e18aefe1d26ee18
**Parameters:** track-origins=yes leak-check=full keep-stacktraces=alloc-and-free track-fds=yes num-callers=20 show-leak-kinds=definite,indirect
**Coverage:** 

```json
Lines executed:30.68% of 1832

```
**Coverage report detail:** [here](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.0/B310/coverage-report-detail)
## Valgrind result:
```
==15342== Memcheck, a memory error detector
==15342== Copyright (C) 2002-2017, and GNU GPLd, by Julian Seward et al.
==15342== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==15342== Command: /var/ossec/bin/ossec-logcollector -f
==15342== Parent PID: 1
==15342== 
==15342== 
==15342== FILE DESCRIPTORS: 17 open at exit.
==15342== Open file descriptor 15: /var/log/duplicated_file.log
==15342==    at 0x6222D19: open (open64.c:47)
==15342==    by 0x619F589: _IO_file_open (fileops.c:189)
==15342==    by 0x619F589: _IO_file_fopen@@GLIBC_2.2.5 (fileops.c:281)
==15342==    by 0x6191EA9: __fopen_internal (iofopen.c:78)
==15342==    by 0x6191EA9: fopen@@GLIBC_2.2.5 (iofopen.c:89)
==15342==    by 0x176807: reload_file (logcollector.c:903)
==15342==    by 0x174FE3: LogCollectorStart (logcollector.c:380)
==15342==    by 0x17248A: main (main.c:187)
==15342== 
==15342== Open file descriptor 14: /var/log/target_file.log
==15342==    at 0x6222D19: open (open64.c:47)
==15342==    by 0x619F589: _IO_file_open (fileops.c:189)
==15342==    by 0x619F589: _IO_file_fopen@@GLIBC_2.2.5 (fileops.c:281)
==15342==    by 0x6191EA9: __fopen_internal (iofopen.c:78)
==15342==    by 0x6191EA9: fopen@@GLIBC_2.2.5 (iofopen.c:89)
==15342==    by 0x176807: reload_file (logcollector.c:903)
==15342==    by 0x174FE3: LogCollectorStart (logcollector.c:380)
==15342==    by 0x17248A: main (main.c:187)
==15342== 
==15342== Open file descriptor 13: /var/log/label_file.log
==15342==    at 0x6222D19: open (open64.c:47)
==15342==    by 0x619F589: _IO_file_open (fileops.c:189)
==15342==    by 0x619F589: _IO_file_fopen@@GLIBC_2.2.5 (fileops.c:281)
==15342==    by 0x6191EA9: __fopen_internal (iofopen.c:78)
==15342==    by 0x6191EA9: fopen@@GLIBC_2.2.5 (iofopen.c:89)
==15342==    by 0x176807: reload_file (logcollector.c:903)
==15342==    by 0x174FE3: LogCollectorStart (logcollector.c:380)
==15342==    by 0x17248A: main (main.c:187)
==15342== 
==15342== Open file descriptor 12: /var/log/json_file.log
==15342==    at 0x6222D19: open (open64.c:47)
==15342==    by 0x619F589: _IO_file_open (fileops.c:189)
==15342==    by 0x619F589: _IO_file_fopen@@GLIBC_2.2.5 (fileops.c:281)
==15342==    by 0x6191EA9: __fopen_internal (iofopen.c:78)
==15342==    by 0x6191EA9: fopen@@GLIBC_2.2.5 (iofopen.c:89)
==15342==    by 0x176807: reload_file (logcollector.c:903)
==15342==    by 0x174FE3: LogCollectorStart (logcollector.c:380)
==15342==    by 0x17248A: main (main.c:187)
==15342== 
==15342== Open file descriptor 11: /var/log/alias_file.log
==15342==    at 0x6222D19: open (open64.c:47)
==15342==    by 0x619F589: _IO_file_open (fileops.c:189)
==15342==    by 0x619F589: _IO_file_fopen@@GLIBC_2.2.5 (fileops.c:281)
==15342==    by 0x6191EA9: __fopen_internal (iofopen.c:78)
==15342==    by 0x6191EA9: fopen@@GLIBC_2.2.5 (iofopen.c:89)
==15342==    by 0x176807: reload_file (logcollector.c:903)
==15342==    by 0x174FE3: LogCollectorStart (logcollector.c:380)
==15342==    by 0x17248A: main (main.c:187)
==15342== 
==15342== Open file descriptor 10: /var/log/database_file.log-20-03-02.log
==15342==    at 0x6222D19: open (open64.c:47)
==15342==    by 0x619F589: _IO_file_open (fileops.c:189)
==15342==    by 0x619F589: _IO_file_fopen@@GLIBC_2.2.5 (fileops.c:281)
==15342==    by 0x6191EA9: __fopen_internal (iofopen.c:78)
==15342==    by 0x6191EA9: fopen@@GLIBC_2.2.5 (iofopen.c:89)
==15342==    by 0x176807: reload_file (logcollector.c:903)
==15342==    by 0x174FE3: LogCollectorStart (logcollector.c:380)
==15342==    by 0x17248A: main (main.c:187)
==15342== 
==15342== Open file descriptor 9: /var/log/remove_file.log
==15342==    at 0x6222D19: open (open64.c:47)
==15342==    by 0x619F589: _IO_file_open (fileops.c:189)
==15342==    by 0x619F589: _IO_file_fopen@@GLIBC_2.2.5 (fileops.c:281)
==15342==    by 0x6191EA9: __fopen_internal (iofopen.c:78)
==15342==    by 0x6191EA9: fopen@@GLIBC_2.2.5 (iofopen.c:89)
==15342==    by 0x176807: reload_file (logcollector.c:903)
==15342==    by 0x174FE3: LogCollectorStart (logcollector.c:380)
==15342==    by 0x17248A: main (main.c:187)
==15342== 
==15342== Open file descriptor 8: /var/log/single_file.log
==15342==    at 0x6222D19: open (open64.c:47)
==15342==    by 0x619F589: _IO_file_open (fileops.c:189)
==15342==    by 0x619F589: _IO_file_fopen@@GLIBC_2.2.5 (fileops.c:281)
==15342==    by 0x6191EA9: __fopen_internal (iofopen.c:78)
==15342==    by 0x6191EA9: fopen@@GLIBC_2.2.5 (iofopen.c:89)
==15342==    by 0x176807: reload_file (logcollector.c:903)
==15342==    by 0x174FE3: LogCollectorStart (logcollector.c:380)
==15342==    by 0x17248A: main (main.c:187)
==15342== 
==15342== Open file descriptor 7: /var/log/dpkg.log
==15342==    at 0x6222D19: open (open64.c:47)
==15342==    by 0x619F589: _IO_file_open (fileops.c:189)
==15342==    by 0x619F589: _IO_file_fopen@@GLIBC_2.2.5 (fileops.c:281)
==15342==    by 0x6191EA9: __fopen_internal (iofopen.c:78)
==15342==    by 0x6191EA9: fopen@@GLIBC_2.2.5 (iofopen.c:89)
==15342==    by 0x176807: reload_file (logcollector.c:903)
==15342==    by 0x174FE3: LogCollectorStart (logcollector.c:380)
==15342==    by 0x17248A: main (main.c:187)
==15342== 
==15342== Open file descriptor 6: /var/ossec/logs/active-responses.log
==15342==    at 0x6222D19: open (open64.c:47)
==15342==    by 0x619F589: _IO_file_open (fileops.c:189)
==15342==    by 0x619F589: _IO_file_fopen@@GLIBC_2.2.5 (fileops.c:281)
==15342==    by 0x6191EA9: __fopen_internal (iofopen.c:78)
==15342==    by 0x6191EA9: fopen@@GLIBC_2.2.5 (iofopen.c:89)
==15342==    by 0x176807: reload_file (logcollector.c:903)
==15342==    by 0x174FE3: LogCollectorStart (logcollector.c:380)
==15342==    by 0x17248A: main (main.c:187)
==15342== 
==15342== Open AF_UNIX socket 16: /var/ossec/queue/ossec/logcollector
==15342==    at 0x6235EC7: socket (syscall-template.S:78)
==15342==    by 0x2576A7: OS_BindUnixDomain (os_net.c:153)
==15342==    by 0x16F5A4: lccom_main (lccom.c:102)
==15342==    by 0x5EFB6DA: start_thread (pthread_create.c:463)
==15342==    by 0x623488E: clone (clone.S:95)
==15342== 
==15342== Open AF_UNIX socket 5: <unknown>
==15342==    at 0x6235EC7: socket (syscall-template.S:78)
==15342==    by 0x25796E: OS_ConnectUnixDomain (os_net.c:203)
==15342==    by 0x2492C3: StartMQ (mq_op.c:36)
==15342==    by 0x172438: main (main.c:182)
==15342== 
==15342== Open file descriptor 4: /dev/urandom
==15342==    at 0x5F05D2B: open (open64.c:47)
==15342==    by 0x253AD3: randombytes (randombytes.c:62)
==15342==    by 0x253C05: srandom_init (randombytes.c:82)
==15342==    by 0x171DC6: main (main.c:60)
==15342== 
==15342== Open file descriptor 3: /tmp/dest/Analysis_dynamic_valgrind-v3.12.0-4668.log
==15342==    <inherited from parent>
==15342== 
==15342== Open file descriptor 2:
==15342==    <inherited from parent>
==15342== 
==15342== Open file descriptor 1:
==15342==    <inherited from parent>
==15342== 
==15342== Open file descriptor 0: /dev/null
==15342==    <inherited from parent>
==15342== 
==15342== 
==15342== HEAP SUMMARY:
==15342==     in use at exit: 32,463 bytes in 132 blocks
==15342==   total heap usage: 7,841 allocs, 7,709 frees, 4,622,041 bytes allocated
==15342== 
==15342== LEAK SUMMARY:
==15342==    definitely lost: 0 bytes in 0 blocks
==15342==    indirectly lost: 0 bytes in 0 blocks
==15342==      possibly lost: 1,904 bytes in 7 blocks
==15342==    still reachable: 30,559 bytes in 125 blocks
==15342==         suppressed: 0 bytes in 0 blocks
==15342== Reachable blocks (those to which a pointer was found) are not shown.
==15342== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==15342== 
==15342== For counts of detected and suppressed errors, rerun with: -v
==15342== ERROR SUMMARY: 3 errors from 3 contexts (suppressed: 0 from 0)

```

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind syscheckd analysis:
**Commit:** 6d98392f9a6518d26fceb27d1e18aefe1d26ee18
**Parameters:** track-origins=yes leak-check=full keep-stacktraces=alloc-and-free track-fds=yes num-callers=20 show-leak-kinds=definite,indirect
**Coverage:** 

```json
Lines executed:25.79% of 3001

```
**Coverage report detail:** [here](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.0/B311/coverage-report-detail)
## Valgrind result:
```
==3403== Memcheck, a memory error detector
==3403== Copyright (C) 2002-2017, and GNU GPLd, by Julian Seward et al.
==3403== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==3403== Command: /var/ossec/bin/ossec-syscheckd -f
==3403== Parent PID: 16000
==3403== 

```

**Comment by wazuhci** [comment]
## Stress/Leaks test results
### Windows Agent ID0
- #### CPU
    [Windows Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B199/monitor-winagent-ID0_B199_Test_stress_windows_Agent-warehouse-pullrequests_CPU(%25).svg)
- #### File Descriptors
    [Windows Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B199/monitor-winagent-ID0_B199_Test_stress_windows_Agent-warehouse-pullrequests_FD.svg)
- #### Resident Set Size memory
    [Windows Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B199/monitor-winagent-ID0_B199_Test_stress_windows_Agent-warehouse-pullrequests_RSS(KB).svg)
### CentOS Manager ID0
- #### CPU
    [CentOS Manager](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B199/monitor-manager-ID0_B199_Test_stress_Manager-warehouse-pullrequests_CPU(%25).svg)
- #### File Descriptors
    [CentOS Manager](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B199/monitor-manager-ID0_B199_Test_stress_Manager-warehouse-pullrequests_FD.svg)
- #### Resident Set Size memory
    [CentOS Manager](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B199/monitor-manager-ID0_B199_Test_stress_Manager-warehouse-pullrequests_RSS(KB).svg)
### CentOS Agent ID1
- #### CPU
    [CentOS Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B199/monitor-agent-ID1_B199_Test_stress_centos_Agent-warehouse-pullrequests_CPU(%25).svg)
- #### File Descriptors
    [CentOS Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B199/monitor-agent-ID1_B199_Test_stress_centos_Agent-warehouse-pullrequests_FD.svg)
- #### Resident Set Size memory
    [CentOS Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B199/monitor-agent-ID1_B199_Test_stress_centos_Agent-warehouse-pullrequests_RSS(KB).svg)
### Ubuntu Agent ID0
- #### CPU
    [Ubuntu Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B199/monitor-agent-ID0_B199_Test_stress_ubuntu_Agent-warehouse-pullrequests_CPU(%25).svg)
- #### File Descriptors
    [Ubuntu Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B199/monitor-agent-ID0_B199_Test_stress_ubuntu_Agent-warehouse-pullrequests_FD.svg)
- #### Resident Set Size memory
    [Ubuntu Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B199/monitor-agent-ID0_B199_Test_stress_ubuntu_Agent-warehouse-pullrequests_RSS(KB).svg)

**Comment by wazuhci** [comment]
The stress test has been launched. The charts will be posted when they are ready.
I will use the following configuration:
### General
- Commit: 1234cfe
- Packages: 
  - [manager 3.12.0 0.branch4663deletedeventsscheduledinsteadwhodata.commit1234cfe rpm](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/rpm/var/wazuh-manager-3.12.0-0.branch4663deletedeventsscheduledinsteadwhodata.commit1234cfe.x86_64.rpm)
  - [agent 3.12.0 0.branch4663deletedeventsscheduledinsteadwhodata.commit1234cfe rpm](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/rpm/var/wazuh-agent-3.12.0-0.branch4663deletedeventsscheduledinsteadwhodata.commit1234cfe.x86_64.rpm)
  - [manager 3.12.0 0.branch4663deletedeventsscheduledinsteadwhodata.commit1234cfe deb](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/deb/var/wazuh-manager_3.12.0-0.branch4663deletedeventsscheduledinsteadwhodata.commit1234cfe_amd64.deb)
  - [agent 3.12.0 0.branch4663deletedeventsscheduledinsteadwhodata.commit1234cfe deb](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/deb/var/wazuh-agent_3.12.0-0.branch4663deletedeventsscheduledinsteadwhodata.commit1234cfe_amd64.deb)
  - [agent 3.12.0 0.branch4663deletedeventsscheduledinsteadwhodata.commit1234cfe msi](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/windows/wazuh-agent-3.12.0-0.branch4663deletedeventsscheduledinsteadwhodata.commit1234cfe.msi)

### Stress test parameters:
- Manager system: `centos`
- Launch CentOS agent: `true`
- Launch Ubuntu agent: `true`
- Launch Windows agent: `true`
- Test duration: `60`
- Scan frequency: `10`
- Modules to test: 
  - logcollector: `true`
  - syscheck: `true`
  - rootcheck: `true`
  - sca: `true`
  - osquery: `true`
  - syscollector: `true`
  - active-response: `true`
  - azure-logs: `true`
  - cis-cat: `true`
  - docker-listener: `true`
  - open-scap: `true`
  - vulnerability-detector: `false`
- FIM special test: `None`
- FIM sleep: `300`
- FIM max files: `25000`
- SCA sleep: `30`
- SCA max registers: `5000`
- Docker image name: `hello-world`
- Docker sleep: `5`
- Docker jobs: `10`
- Logcollector special test: `None`
- Logcollector max files: `50000`
- Logcollector creation sleep: `300`
- Logcollector write files: `1000`
- Logcollector write sleep: `10`
- Vuln sleep: `60`
- Authd port: `1515`
- Syscollector package: `imagemagick.app`
- Syscollector package version: `7.0.8.48`

Regards!.

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind logcollector analysis:
**Commit:** ac73bce810b4756d1eff06a92b519d140b00f942
**Parameters:** track-origins=yes leak-check=full keep-stacktraces=alloc-and-free track-fds=yes num-callers=20 show-leak-kinds=definite,indirect
**Coverage:** 

```json
Lines executed:30.68% of 1832

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.0/B324/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.12.0-4668.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.0/B324/Analysis_dynamic_valgrind-v3.12.0-4668.log)

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind syscheckd analysis:
**Commit:** ac73bce810b4756d1eff06a92b519d140b00f942
**Parameters:** track-origins=yes leak-check=full keep-stacktraces=alloc-and-free track-fds=yes num-callers=20 show-leak-kinds=definite,indirect
**Coverage:** 

```json
Lines executed:25.80% of 2988

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.0/B325/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.12.0-4668.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.0/B325/Analysis_dynamic_valgrind-v3.12.0-4668.log)

**Comment by wazuhci** [comment]
The stress test has been launched. The charts will be posted when they are ready.
I will use the following configuration:
### General
- Commit: ac73bce
- Packages: 
  - [manager 3.12.0 0.branch4663deletedeventsscheduledinsteadwhodata.commitac73bce rpm](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/rpm/var/wazuh-manager-3.12.0-0.branch4663deletedeventsscheduledinsteadwhodata.commitac73bce.x86_64.rpm)
  - [agent 3.12.0 0.branch4663deletedeventsscheduledinsteadwhodata.commitac73bce rpm](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/rpm/var/wazuh-agent-3.12.0-0.branch4663deletedeventsscheduledinsteadwhodata.commitac73bce.x86_64.rpm)
  - [manager 3.12.0 0.branch4663deletedeventsscheduledinsteadwhodata.commitac73bce deb](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/deb/var/wazuh-manager_3.12.0-0.branch4663deletedeventsscheduledinsteadwhodata.commitac73bce_amd64.deb)
  - [agent 3.12.0 0.branch4663deletedeventsscheduledinsteadwhodata.commitac73bce deb](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/deb/var/wazuh-agent_3.12.0-0.branch4663deletedeventsscheduledinsteadwhodata.commitac73bce_amd64.deb)
  - [agent 3.12.0 0.branch4663deletedeventsscheduledinsteadwhodata.commitac73bce msi](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/windows/wazuh-agent-3.12.0-0.branch4663deletedeventsscheduledinsteadwhodata.commitac73bce.msi)

### Stress test parameters:
- Manager system: `centos`
- Launch CentOS agent: `true`
- Launch Ubuntu agent: `true`
- Launch Windows agent: `true`
- Test duration: `60`
- Scan frequency: `10`
- Modules to test: 
  - logcollector: `true`
  - syscheck: `true`
  - rootcheck: `true`
  - sca: `true`
  - osquery: `true`
  - syscollector: `true`
  - active-response: `true`
  - azure-logs: `true`
  - cis-cat: `true`
  - docker-listener: `true`
  - open-scap: `true`
  - vulnerability-detector: `false`
- FIM special test: `None`
- FIM sleep: `300`
- FIM max files: `25000`
- SCA sleep: `30`
- SCA max registers: `5000`
- Docker image name: `hello-world`
- Docker sleep: `5`
- Docker jobs: `10`
- Logcollector special test: `None`
- Logcollector max files: `50000`
- Logcollector creation sleep: `300`
- Logcollector write files: `1000`
- Logcollector write sleep: `10`
- Vuln sleep: `60`
- Authd port: `1515`
- Syscollector package: `imagemagick.app`
- Syscollector package version: `7.0.8.48`

Regards!.

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind syscheckd analysis:
**Commit:** ac73bce810b4756d1eff06a92b519d140b00f942
**Parameters:** track-origins=yes leak-check=full keep-stacktraces=alloc-and-free track-fds=yes num-callers=20 show-leak-kinds=definite,indirect
**Coverage:** 

```json
Lines executed:25.90% of 2988

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.0/B326/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.12.0-4668.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.0/B326/Analysis_dynamic_valgrind-v3.12.0-4668.log)

**Comment by wazuhci** [comment]
## Stress/Leaks test results
### Windows Agent ID0
- #### CPU
    [Windows Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B205/monitor-winagent-ID0_B205_Test_stress_windows_Agent-warehouse-pullrequests_CPU(%25).svg)
- #### File Descriptors
    [Windows Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B205/monitor-winagent-ID0_B205_Test_stress_windows_Agent-warehouse-pullrequests_FD.svg)
- #### Resident Set Size memory
    [Windows Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B205/monitor-winagent-ID0_B205_Test_stress_windows_Agent-warehouse-pullrequests_RSS(KB).svg)
### CentOS Manager ID0
- #### CPU
    [CentOS Manager](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B205/monitor-manager-ID0_B205_Test_stress_Manager-warehouse-pullrequests_CPU(%25).svg)
- #### File Descriptors
    [CentOS Manager](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B205/monitor-manager-ID0_B205_Test_stress_Manager-warehouse-pullrequests_FD.svg)
- #### Resident Set Size memory
    [CentOS Manager](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B205/monitor-manager-ID0_B205_Test_stress_Manager-warehouse-pullrequests_RSS(KB).svg)
### CentOS Agent ID1
- #### CPU
    [CentOS Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B205/monitor-agent-ID1_B205_Test_stress_centos_Agent-warehouse-pullrequests_CPU(%25).svg)
- #### File Descriptors
    [CentOS Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B205/monitor-agent-ID1_B205_Test_stress_centos_Agent-warehouse-pullrequests_FD.svg)
- #### Resident Set Size memory
    [CentOS Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B205/monitor-agent-ID1_B205_Test_stress_centos_Agent-warehouse-pullrequests_RSS(KB).svg)
### Ubuntu Agent ID0
- #### CPU
    [Ubuntu Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B205/monitor-agent-ID0_B205_Test_stress_ubuntu_Agent-warehouse-pullrequests_CPU(%25).svg)
- #### File Descriptors
    [Ubuntu Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B205/monitor-agent-ID0_B205_Test_stress_ubuntu_Agent-warehouse-pullrequests_FD.svg)
- #### Resident Set Size memory
    [Ubuntu Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B205/monitor-agent-ID0_B205_Test_stress_ubuntu_Agent-warehouse-pullrequests_RSS(KB).svg)

**Comment by wazuhci** [comment]
## Stress/Leaks test results
### Windows Agent ID0
- #### CPU
    [Windows Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B206/monitor-winagent-ID0_B206_Test_stress_windows_Agent-warehouse-pullrequests_CPU(%25).svg)
- #### File Descriptors
    [Windows Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B206/monitor-winagent-ID0_B206_Test_stress_windows_Agent-warehouse-pullrequests_FD.svg)
- #### Resident Set Size memory
    [Windows Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B206/monitor-winagent-ID0_B206_Test_stress_windows_Agent-warehouse-pullrequests_RSS(KB).svg)
### CentOS Manager ID0
- #### CPU
    [CentOS Manager](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B206/monitor-manager-ID0_B206_Test_stress_Manager-warehouse-pullrequests_CPU(%25).svg)
- #### File Descriptors
    [CentOS Manager](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B206/monitor-manager-ID0_B206_Test_stress_Manager-warehouse-pullrequests_FD.svg)
- #### Resident Set Size memory
    [CentOS Manager](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B206/monitor-manager-ID0_B206_Test_stress_Manager-warehouse-pullrequests_RSS(KB).svg)
### CentOS Agent ID1
- #### CPU
    [CentOS Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B206/monitor-agent-ID1_B206_Test_stress_centos_Agent-warehouse-pullrequests_CPU(%25).svg)
- #### File Descriptors
    [CentOS Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B206/monitor-agent-ID1_B206_Test_stress_centos_Agent-warehouse-pullrequests_FD.svg)
- #### Resident Set Size memory
    [CentOS Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B206/monitor-agent-ID1_B206_Test_stress_centos_Agent-warehouse-pullrequests_RSS(KB).svg)
### Ubuntu Agent ID0
- #### CPU
    [Ubuntu Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B206/monitor-agent-ID0_B206_Test_stress_ubuntu_Agent-warehouse-pullrequests_CPU(%25).svg)
- #### File Descriptors
    [Ubuntu Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B206/monitor-agent-ID0_B206_Test_stress_ubuntu_Agent-warehouse-pullrequests_FD.svg)
- #### Resident Set Size memory
    [Ubuntu Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B206/monitor-agent-ID0_B206_Test_stress_ubuntu_Agent-warehouse-pullrequests_RSS(KB).svg)

**Comment by wazuhci** [comment]
The stress test has been launched. The charts will be posted when they are ready.
I will use the following configuration:
### General
- Commit: ac73bce
- Packages: 
  - [manager 3.12.0 0.branch4663deletedeventsscheduledinsteadwhodata.commitac73bce rpm](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/rpm/var/wazuh-manager-3.12.0-0.branch4663deletedeventsscheduledinsteadwhodata.commitac73bce.x86_64.rpm)
  - [agent 3.12.0 0.branch4663deletedeventsscheduledinsteadwhodata.commitac73bce rpm](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/rpm/var/wazuh-agent-3.12.0-0.branch4663deletedeventsscheduledinsteadwhodata.commitac73bce.x86_64.rpm)
  - [manager 3.12.0 0.branch4663deletedeventsscheduledinsteadwhodata.commitac73bce deb](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/deb/var/wazuh-manager_3.12.0-0.branch4663deletedeventsscheduledinsteadwhodata.commitac73bce_amd64.deb)
  - [agent 3.12.0 0.branch4663deletedeventsscheduledinsteadwhodata.commitac73bce deb](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/deb/var/wazuh-agent_3.12.0-0.branch4663deletedeventsscheduledinsteadwhodata.commitac73bce_amd64.deb)
  - [agent 3.12.0 0.branch4663deletedeventsscheduledinsteadwhodata.commitac73bce msi](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/windows/wazuh-agent-3.12.0-0.branch4663deletedeventsscheduledinsteadwhodata.commitac73bce.msi)

### Stress test parameters:
- Manager system: `centos`
- Launch CentOS agent: `true`
- Launch Ubuntu agent: `true`
- Launch Windows agent: `true`
- Test duration: `60`
- Scan frequency: `10`
- Modules to test: 
  - logcollector: `true`
  - syscheck: `true`
  - rootcheck: `true`
  - sca: `true`
  - osquery: `true`
  - syscollector: `true`
  - active-response: `true`
  - azure-logs: `true`
  - cis-cat: `true`
  - docker-listener: `true`
  - open-scap: `true`
  - vulnerability-detector: `false`
- FIM special test: `None`
- FIM sleep: `300`
- FIM max files: `25000`
- SCA sleep: `30`
- SCA max registers: `5000`
- Docker image name: `hello-world`
- Docker sleep: `5`
- Docker jobs: `10`
- Logcollector special test: `None`
- Logcollector max files: `50000`
- Logcollector creation sleep: `300`
- Logcollector write files: `1000`
- Logcollector write sleep: `10`
- Vuln sleep: `60`
- Authd port: `1515`
- Syscollector package: `imagemagick.app`
- Syscollector package version: `7.0.8.48`

Regards!.

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind logcollector analysis:
**Commit:** ac73bce810b4756d1eff06a92b519d140b00f942
**Parameters:** track-origins=yes leak-check=full keep-stacktraces=alloc-and-free track-fds=yes num-callers=20 show-leak-kinds=definite,indirect
**Coverage:** 

```json
Lines executed:30.68% of 1832

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.0/B333/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.12.0-4668.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.0/B333/Analysis_dynamic_valgrind-v3.12.0-4668.log)

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind syscheckd analysis:
**Commit:** ac73bce810b4756d1eff06a92b519d140b00f942
**Parameters:** track-origins=yes leak-check=full keep-stacktraces=alloc-and-free track-fds=yes num-callers=20 show-leak-kinds=definite,indirect
**Coverage:** 

```json
Lines executed:25.90% of 2988

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.0/B334/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.12.0-4668.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.0/B334/Analysis_dynamic_valgrind-v3.12.0-4668.log)

**Comment by wazuhci** [comment]
## Stress/Leaks test results
### Windows Agent ID0
- #### CPU
    [Windows Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B209/monitor-winagent-ID0_B209_Test_stress_windows_Agent-warehouse-pullrequests_CPU(%25).svg)
- #### File Descriptors
    [Windows Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B209/monitor-winagent-ID0_B209_Test_stress_windows_Agent-warehouse-pullrequests_FD.svg)
- #### Resident Set Size memory
    [Windows Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B209/monitor-winagent-ID0_B209_Test_stress_windows_Agent-warehouse-pullrequests_RSS(KB).svg)
### CentOS Manager ID0
- #### CPU
    [CentOS Manager](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B209/monitor-manager-ID0_B209_Test_stress_Manager-warehouse-pullrequests_CPU(%25).svg)
- #### File Descriptors
    [CentOS Manager](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B209/monitor-manager-ID0_B209_Test_stress_Manager-warehouse-pullrequests_FD.svg)
- #### Resident Set Size memory
    [CentOS Manager](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B209/monitor-manager-ID0_B209_Test_stress_Manager-warehouse-pullrequests_RSS(KB).svg)
### CentOS Agent ID1
- #### CPU
    [CentOS Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B209/monitor-agent-ID1_B209_Test_stress_centos_Agent-warehouse-pullrequests_CPU(%25).svg)
- #### File Descriptors
    [CentOS Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B209/monitor-agent-ID1_B209_Test_stress_centos_Agent-warehouse-pullrequests_FD.svg)
- #### Resident Set Size memory
    [CentOS Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B209/monitor-agent-ID1_B209_Test_stress_centos_Agent-warehouse-pullrequests_RSS(KB).svg)
### Ubuntu Agent ID0
- #### CPU
    [Ubuntu Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B209/monitor-agent-ID0_B209_Test_stress_ubuntu_Agent-warehouse-pullrequests_CPU(%25).svg)
- #### File Descriptors
    [Ubuntu Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B209/monitor-agent-ID0_B209_Test_stress_ubuntu_Agent-warehouse-pullrequests_FD.svg)
- #### Resident Set Size memory
    [Ubuntu Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B209/monitor-agent-ID0_B209_Test_stress_ubuntu_Agent-warehouse-pullrequests_RSS(KB).svg)

File: src/syscheckd/fim_db.c [hunk 5]
```diff
@@ -531,27 +532,34 @@ int fim_db_exec_simple_wquery(fdb_t *fim_sql, const char *query) {
...
 int fim_db_delete_range(fdb_t * fim_sql, fim_tmp_file *file, pthread_mutex_t *mutex, int storage) {
-    return fim_db_process_read_file(fim_sql, file, mutex, fim_db_remove_path,
-            storage, (void *) (int) 0);
+    return fim_db_process_read_file(fim_sql, file, mutex, fim_db_remove_path, storage,
+                                    (void *) false, (void *) FIM_SCHEDULED, NULL);
 }
 
-int fim_db_process_missing_entry(fdb_t *fim_sql, fim_tmp_file *file, pthread_mutex_t *mutex, int storage, fim_event_mode mode) {
-    return fim_db_process_read_file(fim_sql, file, mutex, fim_db_process_path, storage, (void *) (fim_event_mode) mode);
+int fim_db_process_missing_entry(fdb_t *fim_sql, fim_tmp_file *file, pthread_mutex_t *mutex, int storage, fim_event_mode mode, whodata_evt * w_evt) {
```
Comment (TomasTurina) [inline src/syscheckd/fim_db.c]: Isn't it possible to merge the functions `fim_db_delete_not_scanned`, `fim_db_delete_range` and `fim_db_process_missing_entry` into a single one by adding an `alert` parameter?

Comment (bah07) [reply src/syscheckd/fim_db.c]: Thanks @TomasTurina , 

We have decided to name the wrapper functions differently because they perform different operations, so we can easily identify the action performed by each one of them.
