### PR TITLE
[FIM] New option to set a file_limit

### LINKED ISSUE #4687: [FIM] Implement an option to set the maximum number of files to monitor
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| fim-rework-sqlite | FIM | Manager/Agent | Packages/Sources | All |

Hello team,

In systems with limited resources, a wrong configuration of `syscheck` can lead to monitoring hundreds of thousands of files, which could be a serious problem if we think about system performance. That's why it is necessary to implement a global option to set the maximum number of files to monitor.

This option should be as follows:

```xml
<syscheck>
    <file_limit>100000</file_limit>
</syscheck>
```

- Only positive values are allowed.
- The default value is 100000.
- If set to 0, there will be no limit (as it currently works).

### PR DESCRIPTION
**Pull request by TomasTurina**
| Related issue  | Wazuh-QA PR                | Documentation PR                                |
|---------------|------------------------|--------------------------------------|
| #4687             | wazuh/wazuh-qa#647  | wazuh/wazuh-documentation#2378  |

## Description

In systems with limited resources, a wrong configuration of syscheck can lead to monitoring hundreds of thousands of files, which could be a serious problem if we think about system performance. That's why it is necessary to implement a global option to set the maximum number of files to monitor.

This is the proposed solution:

- The new configuration option `file_limit` was added to the configuration file inside the `syscheck` block. Its default value is 100000.

```xml
<syscheck>
    <file_limit>100000</file_limit>
</syscheck>
```

- A function to organize the directory folders alphabetically was added. Its name is `organize_syscheck_dirs` and it receives the `syscheck` configuration block as a parameter.

- The double scan mechanism was implemented inside the `fim_scan` function. At the end of the first scan, the `file_limit` is checked. If its value is 0, it continues the execution as usual. If not, it continue as follows:

  - If the number of entries in the DB is lower than the `file_limit`, it continues the execution as usual.

  - If not, a second scan is performed. This scan has the particularity that it will stop the directory iteration when the DB changes its state to full, so it could iterate all the directories or just the necessaries to fill the DB.

- An alert is generated in the following cases:

  - When the DB reaches its 80% of capacity, a message is sent to the manager and an alert of `level` 7 is generated.

  - When the DB reaches its 90% of capacity, a message is sent to the manager and an alert of `level` 9 is generated.

  - When the DB gets full, a message is sent to the manager and an alert of `level` 12 is generated.

  - When the DB returns to its normal state (<80%),  a message is sent to the manager and an alert of `level` 3 is generated.

- When an alert of a kind is displayed, it won't display again unless the DB changes its state. All these changes are managed in the new function `fim_check_db_state`.

This issue closes #4687.

### CODE REVIEW

**Comment by wazuhci** [comment]
The stress test has been launched. The charts will be posted when they are ready.
I will use the following configuration:
### General
- Commit: 5b813ff
- Packages: 
  - [manager 3.12.0 0.branch4687syscheckfilelimit.commit5b813ff rpm](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/rpm/var/wazuh-manager-3.12.0-0.branch4687syscheckfilelimit.commit5b813ff.x86_64.rpm)
  - [agent 3.12.0 0.branch4687syscheckfilelimit.commit5b813ff rpm](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/rpm/var/wazuh-agent-3.12.0-0.branch4687syscheckfilelimit.commit5b813ff.x86_64.rpm)
  - [manager 3.12.0 0.branch4687syscheckfilelimit.commit5b813ff deb](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/deb/var/wazuh-manager_3.12.0-0.branch4687syscheckfilelimit.commit5b813ff_amd64.deb)
  - [agent 3.12.0 0.branch4687syscheckfilelimit.commit5b813ff deb](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/deb/var/wazuh-agent_3.12.0-0.branch4687syscheckfilelimit.commit5b813ff_amd64.deb)
  - [agent 3.12.0 0.branch4687syscheckfilelimit.commit5b813ff msi](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/windows/wazuh-agent-3.12.0-0.branch4687syscheckfilelimit.commit5b813ff.msi)

### Stress test parameters:
- Manager system: `centos`
- Launch CentOS agent: `true`
- Launch Ubuntu agent: `true`
- Launch Windows agent: `true`
- Test duration: `60`
- Scan frequency: `10`
- Modules to test: 
  - logcollector: `true`
  - syscheck: `true`
  - rootcheck: `true`
  - sca: `true`
  - osquery: `true`
  - syscollector: `true`
  - active-response: `true`
  - azure-logs: `true`
  - cis-cat: `true`
  - docker-listener: `true`
  - open-scap: `true`
  - vulnerability-detector: `false`
- FIM special test: `None`
- FIM sleep: `300`
- FIM max files: `25000`
- SCA sleep: `30`
- SCA max registers: `5000`
- Docker image name: `hello-world`
- Docker sleep: `5`
- Docker jobs: `10`
- Logcollector special test: `None`
- Logcollector max files: `50000`
- Logcollector creation sleep: `300`
- Logcollector write files: `1000`
- Logcollector write sleep: `10`
- Vuln sleep: `60`
- Authd port: `1515`
- Syscollector package: `imagemagick.app`
- Syscollector package version: `7.0.8.48`

Regards!.

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind logcollector analysis:
**Commit:** 5b813ff3ae3792a486f1374501d7ce1b35170eef
**Parameters:** track-origins=yes leak-check=full keep-stacktraces=alloc-and-free track-fds=yes num-callers=20 show-leak-kinds=definite,indirect
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.0/B687/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.0/B687/ossec.log)
**Coverage:** 

```json
Lines executed:30.68% of 1832

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.0/B687/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.12.0-B687.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.0/B687/Analysis_dynamic_valgrind-v3.12.0-B687.log)

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind syscheckd analysis:
**Commit:** 5b813ff3ae3792a486f1374501d7ce1b35170eef
**Parameters:** track-origins=yes leak-check=full keep-stacktraces=alloc-and-free track-fds=yes num-callers=20 show-leak-kinds=definite,indirect
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.0/B688/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.0/B688/ossec.log)
**Coverage:** 

```json
Lines executed:26.36% of 3092

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.0/B688/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.12.0-B688.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.0/B688/Analysis_dynamic_valgrind-v3.12.0-B688.log)

**Comment by wazuhci** [comment]
## Stress/Leaks test results
### Windows Agent ID0
- #### CPU
    [Windows Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B366/monitor-winagent-ID0_B366_Test_stress_windows_Agent-warehouse-pullrequests_CPU(%25).svg)
- #### File Descriptors
    [Windows Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B366/monitor-winagent-ID0_B366_Test_stress_windows_Agent-warehouse-pullrequests_FD.svg)
- #### Resident Set Size memory
    [Windows Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B366/monitor-winagent-ID0_B366_Test_stress_windows_Agent-warehouse-pullrequests_RSS(KB).svg)
### CentOS Manager ID0
- #### CPU
    [CentOS Manager](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B366/monitor-manager-ID0_B366_Test_stress_Manager-warehouse-pullrequests_CPU(%25).svg)
- #### File Descriptors
    [CentOS Manager](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B366/monitor-manager-ID0_B366_Test_stress_Manager-warehouse-pullrequests_FD.svg)
- #### Resident Set Size memory
    [CentOS Manager](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B366/monitor-manager-ID0_B366_Test_stress_Manager-warehouse-pullrequests_RSS(KB).svg)
### CentOS Agent ID1
- #### CPU
    [CentOS Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B366/monitor-agent-ID1_B366_Test_stress_centos_Agent-warehouse-pullrequests_CPU(%25).svg)
- #### File Descriptors
    [CentOS Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B366/monitor-agent-ID1_B366_Test_stress_centos_Agent-warehouse-pullrequests_FD.svg)
- #### Resident Set Size memory
    [CentOS Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B366/monitor-agent-ID1_B366_Test_stress_centos_Agent-warehouse-pullrequests_RSS(KB).svg)
### Ubuntu Agent ID0
- #### CPU
    [Ubuntu Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B366/monitor-agent-ID0_B366_Test_stress_ubuntu_Agent-warehouse-pullrequests_CPU(%25).svg)
- #### File Descriptors
    [Ubuntu Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B366/monitor-agent-ID0_B366_Test_stress_ubuntu_Agent-warehouse-pullrequests_FD.svg)
- #### Resident Set Size memory
    [Ubuntu Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B366/monitor-agent-ID0_B366_Test_stress_ubuntu_Agent-warehouse-pullrequests_RSS(KB).svg)

**Comment by wazuhci** [comment]
The stress test has been launched. The charts will be posted when they are ready.
I will use the following configuration:
### General
- Commit: bd07409
- Packages: 
  - [manager 3.12.0 0.branch4687syscheckfilelimit.commitbd07409 rpm](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/rpm/var/wazuh-manager-3.12.0-0.branch4687syscheckfilelimit.commitbd07409.x86_64.rpm)
  - [agent 3.12.0 0.branch4687syscheckfilelimit.commitbd07409 rpm](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/rpm/var/wazuh-agent-3.12.0-0.branch4687syscheckfilelimit.commitbd07409.x86_64.rpm)
  - [manager 3.12.0 0.branch4687syscheckfilelimit.commitbd07409 deb](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/deb/var/wazuh-manager_3.12.0-0.branch4687syscheckfilelimit.commitbd07409_amd64.deb)
  - [agent 3.12.0 0.branch4687syscheckfilelimit.commitbd07409 deb](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/deb/var/wazuh-agent_3.12.0-0.branch4687syscheckfilelimit.commitbd07409_amd64.deb)
  - [agent 3.12.0 0.branch4687syscheckfilelimit.commitbd07409 msi](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/windows/wazuh-agent-3.12.0-0.branch4687syscheckfilelimit.commitbd07409.msi)

### Stress test parameters:
- Manager system: `centos`
- Launch CentOS agent: `true`
- Launch Ubuntu agent: `true`
- Launch Windows agent: `true`
- Test duration: `60`
- Scan frequency: `10`
- Modules to test: 
  - logcollector: `true`
  - syscheck: `true`
  - rootcheck: `true`
  - sca: `true`
  - osquery: `true`
  - syscollector: `true`
  - active-response: `true`
  - azure-logs: `true`
  - cis-cat: `true`
  - docker-listener: `true`
  - open-scap: `true`
  - vulnerability-detector: `false`
- FIM special test: `None`
- FIM sleep: `300`
- FIM max files: `25000`
- SCA sleep: `30`
- SCA max registers: `5000`
- Docker image name: `hello-world`
- Docker sleep: `5`
- Docker jobs: `10`
- Logcollector special test: `None`
- Logcollector max files: `50000`
- Logcollector creation sleep: `300`
- Logcollector write files: `1000`
- Logcollector write sleep: `10`
- Vuln sleep: `60`
- Authd port: `1515`
- Syscollector package: `imagemagick.app`
- Syscollector package version: `7.0.8.48`

Regards!.

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind logcollector analysis:
**Commit:** bd07409378ebd4b52a082272985eecf8dfc173e6
**Parameters:** track-origins=yes leak-check=full keep-stacktraces=alloc-and-free track-fds=yes num-callers=20 show-leak-kinds=definite,indirect
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.0/B705/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.0/B705/ossec.log)
**Coverage:** 

```json
Lines executed:30.68% of 1832

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.0/B705/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.12.0-B705.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.0/B705/Analysis_dynamic_valgrind-v3.12.0-B705.log)

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind syscheckd analysis:
**Commit:** bd07409378ebd4b52a082272985eecf8dfc173e6
**Parameters:** track-origins=yes leak-check=full keep-stacktraces=alloc-and-free track-fds=yes num-callers=20 show-leak-kinds=definite,indirect
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.0/B706/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.0/B706/ossec.log)
**Coverage:** 

```json
Lines executed:26.43% of 3103

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.0/B706/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.12.0-B706.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.0/B706/Analysis_dynamic_valgrind-v3.12.0-B706.log)

**Comment by wazuhci** [comment]
## Stress/Leaks test results
### Windows Agent ID0
- #### CPU
    [Windows Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B375/monitor-winagent-ID0_B375_Test_stress_windows_Agent-warehouse-pullrequests_CPU(%25).svg)
- #### File Descriptors
    [Windows Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B375/monitor-winagent-ID0_B375_Test_stress_windows_Agent-warehouse-pullrequests_FD.svg)
- #### Resident Set Size memory
    [Windows Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B375/monitor-winagent-ID0_B375_Test_stress_windows_Agent-warehouse-pullrequests_RSS(KB).svg)
### CentOS Manager ID0
- #### CPU
    [CentOS Manager](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B375/monitor-manager-ID0_B375_Test_stress_Manager-warehouse-pullrequests_CPU(%25).svg)
- #### File Descriptors
    [CentOS Manager](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B375/monitor-manager-ID0_B375_Test_stress_Manager-warehouse-pullrequests_FD.svg)
- #### Resident Set Size memory
    [CentOS Manager](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B375/monitor-manager-ID0_B375_Test_stress_Manager-warehouse-pullrequests_RSS(KB).svg)
### CentOS Agent ID1
- #### CPU
    [CentOS Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B375/monitor-agent-ID1_B375_Test_stress_centos_Agent-warehouse-pullrequests_CPU(%25).svg)
- #### File Descriptors
    [CentOS Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B375/monitor-agent-ID1_B375_Test_stress_centos_Agent-warehouse-pullrequests_FD.svg)
- #### Resident Set Size memory
    [CentOS Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B375/monitor-agent-ID1_B375_Test_stress_centos_Agent-warehouse-pullrequests_RSS(KB).svg)
### Ubuntu Agent ID0
- #### CPU
    [Ubuntu Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B375/monitor-agent-ID0_B375_Test_stress_ubuntu_Agent-warehouse-pullrequests_CPU(%25).svg)
- #### File Descriptors
    [Ubuntu Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B375/monitor-agent-ID0_B375_Test_stress_ubuntu_Agent-warehouse-pullrequests_FD.svg)
- #### Resident Set Size memory
    [Ubuntu Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B375/monitor-agent-ID0_B375_Test_stress_ubuntu_Agent-warehouse-pullrequests_RSS(KB).svg)

**Comment by wazuhci** [comment]
The stress test has been launched. The charts will be posted when they are ready.
I will use the following configuration:
### General
- Commit: 6d816ec
- Packages: 
  - [manager 3.12.0 0.commit6d816ec rpm](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/rpm/var/wazuh-manager-3.12.0-0.commit6d816ec.x86_64.rpm)
  - [agent 3.12.0 0.commit6d816ec rpm](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/rpm/var/wazuh-agent-3.12.0-0.commit6d816ec.x86_64.rpm)
  - [manager 3.12.0 0.commit6d816ec deb](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/deb/var/wazuh-manager_3.12.0-0.commit6d816ec_amd64.deb)
  - [agent 3.12.0 0.commit6d816ec deb](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/deb/var/wazuh-agent_3.12.0-0.commit6d816ec_amd64.deb)
  - [agent 3.12.0 0.commit6d816ec msi](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/windows/wazuh-agent-3.12.0-0.commit6d816ec.msi)

### Stress test parameters:
- Manager system: `centos`
- Launch CentOS agent: `true`
- Launch Ubuntu agent: `true`
- Launch Windows agent: `true`
- Test duration: `60`
- Scan frequency: `10`
- Modules to test: 
  - logcollector: `true`
  - syscheck: `true`
  - rootcheck: `true`
  - sca: `true`
  - osquery: `true`
  - syscollector: `true`
  - active-response: `true`
  - azure-logs: `true`
  - cis-cat: `true`
  - docker-listener: `true`
  - open-scap: `true`
  - vulnerability-detector: `false`
- FIM special test: `None`
- FIM sleep: `300`
- FIM max files: `25000`
- SCA sleep: `30`
- SCA max registers: `5000`
- Docker image name: `hello-world`
- Docker sleep: `5`
- Docker jobs: `10`
- Logcollector special test: `None`
- Logcollector max files: `50000`
- Logcollector creation sleep: `300`
- Logcollector write files: `1000`
- Logcollector write sleep: `10`
- Vuln sleep: `60`
- Authd port: `1515`
- Syscollector package: `imagemagick.app`
- Syscollector package version: `7.0.8.48`

Regards!.

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind logcollector analysis:
**Commit:** 6d816ec138c0d3ed9e7ef924acb7148de8bac1e5
**Parameters:** track-origins=yes leak-check=full keep-stacktraces=alloc-and-free track-fds=yes num-callers=20 show-leak-kinds=definite,indirect
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.0/B937/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.0/B937/ossec.log)
**Coverage:** 

```json
Lines executed:31.40% of 1860

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.0/B937/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.12.0-B937.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.0/B937/Analysis_dynamic_valgrind-v3.12.0-B937.log)

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind syscheckd analysis:
**Commit:** 6d816ec138c0d3ed9e7ef924acb7148de8bac1e5
**Parameters:** track-origins=yes leak-check=full keep-stacktraces=alloc-and-free track-fds=yes num-callers=20 show-leak-kinds=definite,indirect
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.0/B938/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.0/B938/ossec.log)
**Coverage:** 

```json
Lines executed:26.43% of 3103

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.0/B938/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.12.0-B938.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.0/B938/Analysis_dynamic_valgrind-v3.12.0-B938.log)

**Comment by wazuhci** [comment]
The stress test has been launched. The charts will be posted when they are ready.
I will use the following configuration:
### General
- Commit: 6d816ec
- Packages: 
  - [manager 3.12.0 0.commit6d816ec rpm](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/rpm/var/wazuh-manager-3.12.0-0.commit6d816ec.x86_64.rpm)
  - [agent 3.12.0 0.commit6d816ec rpm](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/rpm/var/wazuh-agent-3.12.0-0.commit6d816ec.x86_64.rpm)
  - [manager 3.12.0 0.commit6d816ec deb](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/deb/var/wazuh-manager_3.12.0-0.commit6d816ec_amd64.deb)
  - [agent 3.12.0 0.commit6d816ec deb](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/deb/var/wazuh-agent_3.12.0-0.commit6d816ec_amd64.deb)
  - [agent 3.12.0 0.commit6d816ec msi](https://packages-dev.wazuh.com/warehouse/pullrequests/3.12/windows/wazuh-agent-3.12.0-0.commit6d816ec.msi)

### Stress test parameters:
- Manager system: `centos`
- Launch CentOS agent: `true`
- Launch Ubuntu agent: `true`
- Launch Windows agent: `true`
- Test duration: `60`
- Scan frequency: `10`
- Modules to test: 
  - logcollector: `true`
  - syscheck: `true`
  - rootcheck: `true`
  - sca: `true`
  - osquery: `true`
  - syscollector: `true`
  - active-response: `true`
  - azure-logs: `true`
  - cis-cat: `true`
  - docker-listener: `true`
  - open-scap: `true`
  - vulnerability-detector: `false`
- FIM special test: `None`
- FIM sleep: `300`
- FIM max files: `25000`
- SCA sleep: `30`
- SCA max registers: `5000`
- Docker image name: `hello-world`
- Docker sleep: `5`
- Docker jobs: `10`
- Logcollector special test: `None`
- Logcollector max files: `50000`
- Logcollector creation sleep: `300`
- Logcollector write files: `1000`
- Logcollector write sleep: `10`
- Vuln sleep: `60`
- Authd port: `1515`
- Syscollector package: `imagemagick.app`
- Syscollector package version: `7.0.8.48`

Regards!.

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind logcollector analysis:
**Commit:** 6d816ec138c0d3ed9e7ef924acb7148de8bac1e5
**Parameters:** track-origins=yes leak-check=full keep-stacktraces=alloc-and-free track-fds=yes num-callers=20 show-leak-kinds=definite,indirect
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.0/B965/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.0/B965/ossec.log)
**Coverage:** 

```json
Lines executed:31.40% of 1860

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.0/B965/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.12.0-B965.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.0/B965/Analysis_dynamic_valgrind-v3.12.0-B965.log)

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind syscheckd analysis:
**Commit:** 6d816ec138c0d3ed9e7ef924acb7148de8bac1e5
**Parameters:** track-origins=yes leak-check=full keep-stacktraces=alloc-and-free track-fds=yes num-callers=20 show-leak-kinds=definite,indirect
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.0/B966/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.0/B966/ossec.log)
**Coverage:** 

```json
Lines executed:26.43% of 3103

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.0/B966/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.12.0-B966.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.12.0/B966/Analysis_dynamic_valgrind-v3.12.0-B966.log)

**Comment by wazuhci** [comment]
## Stress/Leaks test results
### Windows Agent ID0
- #### CPU
    [Windows Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B523/monitor-winagent-ID0_B523_Test_stress_windows_Agent-warehouse-pullrequests_CPU(%25).svg)
- #### File Descriptors
    [Windows Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B523/monitor-winagent-ID0_B523_Test_stress_windows_Agent-warehouse-pullrequests_FD.svg)
- #### Resident Set Size memory
    [Windows Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B523/monitor-winagent-ID0_B523_Test_stress_windows_Agent-warehouse-pullrequests_RSS(KB).svg)
### CentOS Manager ID0
- #### CPU
    [CentOS Manager](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B523/monitor-manager-ID0_B523_Test_stress_Manager-warehouse-pullrequests_CPU(%25).svg)
- #### File Descriptors
    [CentOS Manager](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B523/monitor-manager-ID0_B523_Test_stress_Manager-warehouse-pullrequests_FD.svg)
- #### Resident Set Size memory
    [CentOS Manager](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B523/monitor-manager-ID0_B523_Test_stress_Manager-warehouse-pullrequests_RSS(KB).svg)
### CentOS Agent ID1
- #### CPU
    [CentOS Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B523/monitor-agent-ID1_B523_Test_stress_centos_Agent-warehouse-pullrequests_CPU(%25).svg)
- #### File Descriptors
    [CentOS Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B523/monitor-agent-ID1_B523_Test_stress_centos_Agent-warehouse-pullrequests_FD.svg)
- #### Resident Set Size memory
    [CentOS Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B523/monitor-agent-ID1_B523_Test_stress_centos_Agent-warehouse-pullrequests_RSS(KB).svg)
### Ubuntu Agent ID0
- #### CPU
    [Ubuntu Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B523/monitor-agent-ID0_B523_Test_stress_ubuntu_Agent-warehouse-pullrequests_CPU(%25).svg)
- #### File Descriptors
    [Ubuntu Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B523/monitor-agent-ID0_B523_Test_stress_ubuntu_Agent-warehouse-pullrequests_FD.svg)
- #### Resident Set Size memory
    [Ubuntu Agent](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/3.12.0/B523/monitor-agent-ID0_B523_Test_stress_ubuntu_Agent-warehouse-pullrequests_RSS(KB).svg)

File: src/config/syscheck-config.c [hunk 1]
```diff
@@ -1066,6 +1159,15 @@ int Read_Syscheck(const OS_XML *xml, XML_NODE node, void *configp, __attribute__
             }
         }
 
+        /* Get file limit */
+        else if (strcmp(node[i]->element, xml_file_limit) == 0) {
+            if (!OS_StrIsNum(node[i]->content)) {
+                merror(XML_VALUEERR, node[i]->element, node[i]->content);
+                return (OS_INVALID);
+            }
+            syscheck->file_limit = atoi(node[i]->content);
```
Comment (jesusjimsa) [inline src/config/syscheck-config.c:1168]: Please, add a _debug_ message telling the value of `file_limit`.

Comment (jesusjimsa) [reply src/config/syscheck-config.c:1169]: Solved cf4a5a2

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind logcollector analysis:
**Commit:** be24688343c538e8c4a7f25ab6fd47044e49c54c
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1572/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1572/ossec.log)
**Coverage:** 

```json
Lines executed:31.41% of 1859

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1572/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B1572.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1572/Analysis_dynamic_valgrind-v3.13.0-B1572.log)

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind syscheckd analysis:
**Commit:** be24688343c538e8c4a7f25ab6fd47044e49c54c
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1573/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1573/ossec.log)
**Coverage:** 

```json
Lines executed:27.00% of 3159

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1573/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B1573.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1573/Analysis_dynamic_valgrind-v3.13.0-B1573.log)

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind logcollector analysis:
**Commit:** 9fa70a00598b05833a40b6d31428744150f9156f
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1700/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1700/ossec.log)
**Coverage:** 

```json
Lines executed:31.41% of 1859

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1700/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B1700.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1700/Analysis_dynamic_valgrind-v3.13.0-B1700.log)

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind syscheckd analysis:
**Commit:** 9fa70a00598b05833a40b6d31428744150f9156f
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1701/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1701/ossec.log)
**Coverage:** 

```json
Lines executed:26.97% of 3159

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1701/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B1701.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1701/Analysis_dynamic_valgrind-v3.13.0-B1701.log)

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind logcollector analysis:
**Commit:** 9fa70a00598b05833a40b6d31428744150f9156f
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1710/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1710/ossec.log)
**Coverage:** 

```json
Lines executed:31.41% of 1859

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1710/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B1710.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1710/Analysis_dynamic_valgrind-v3.13.0-B1710.log)

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind syscheckd analysis:
**Commit:** 9fa70a00598b05833a40b6d31428744150f9156f
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1711/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1711/ossec.log)
**Coverage:** 

```json
Lines executed:27.00% of 3159

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1711/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B1711.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1711/Analysis_dynamic_valgrind-v3.13.0-B1711.log)

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind logcollector analysis:
**Commit:** 9fa70a00598b05833a40b6d31428744150f9156f
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1720/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1720/ossec.log)
**Coverage:** 

```json
Lines executed:31.41% of 1859

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1720/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B1720.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1720/Analysis_dynamic_valgrind-v3.13.0-B1720.log)

**Comment by wazuhci** [comment]
## Analysis_dynamic_valgrind syscheckd analysis:
**Commit:** 9fa70a00598b05833a40b6d31428744150f9156f
**Parameters:** track-origins="yes" leak-check="full" keep-stacktraces="alloc-and-free" track-fds="yes" num-callers="20" show-leak-kinds="definite,indirect"
**Agent config:** [ossec.conf](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1721/ossec.conf)
**Agent logs:** [ossec.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1721/ossec.log)
**Coverage:** 

```json
Lines executed:26.97% of 3159

```
**Coverage report detail:** [coverage-report-summary](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1721/coverage-report-detail)
**Valgrind result:** [Analysis_dynamic_valgrind-v3.13.0-B1721.log](https://ci.wazuh.com/data/Analysis_dynamic_valgrind/v3.13.0/B1721/Analysis_dynamic_valgrind-v3.13.0-B1721.log)
