### PR TITLE
Unify and standarize new API responses format

### LINKED ISSUE #5345: Unify and standardize error response for HTTP code 400 in the new API
Hello team,

As part of the development to get new Wazuh API 4.0 ready for production use we should ensure the response structure for the HTTP code 400 follows an unified standard structure.

Actually, the error response varies depending on whether it is generated by Connexion at the spec level, the API/framework or the cluster in another node. 

Connexion example:
```json
{
  "type": "about:blank",
  "title": "Bad Request",
  "detail": "'{\\n  \"arguments\": sr\\n}' is not of type 'object'",
  "status": 400
}
```
Framework example:
```json
{
    "type": "about:blank",
    "title": "Wazuh Error",
    "detail": "Body is empty",
    "status": 400,
    "remediation": "Please, check the content of the file to be uploaded",
    "code": 1912,
    "dapi_errors": {}
}
```
Each one of these error responses should follow the same structure. We can include an exception handler for `connexion` raised exceptions.

Best regards,

David J. Iglesias

### PR DESCRIPTION
**Pull request by CarlosRS9**
Hello Team,

This PR closes #5345.

It unifies the format of our new API responses. Currently, the error response varies depending on whether it is generated by Connexion at the spec level, the API/framework or the cluster in another node. Different responses contain different fields like `status`. A new middleware and additional changes were made to be able to apply post-processing to the responses, removing or adding fields if needed.

With the new format the responses will no longer have the following fields: `type` and `status`. Optional fields like code will be available only for certain error responses. This format is used in every response, whether is raised from API/Framework or not.

As the response format changed some tests needed modification to expect this new format. Unit and integration tests were updated and fixed. Additional changes such changing the Wazuh installation method from packages to sources for our wazuh Agents were also made.

## Response examples
- 500 - Wazuh Internal Error
```json
{
  "title": "Wazuh Internal Error",
  "detail": "Error trying to load the JWT secret",
  "remediation": "Make sure you have the right permissions: WAZUH_PATH/api/configuration/security/jwt_secret",
  "code": 6003
}
```

- 400 - Bad request from spec (malformed body)
```json
{
  "title": "Bad Request",
  "detail": "'\"invalid\": \"invalid\"' is not of type 'object'"
}
```

- 400 - Bad request from framework (wrong fields in body)
```json
{
  "title": "Bad Request",
  "detail": "Invalid field found {'invalid'}"
}
```

- 403 - Permission denied
```json
{
  "title": "Permission Denied",
  "detail": "Permission denied: Resource type: agent:id",
  "remediation": "Please, make sure you have permissions to execute the current request. For more information on how to set up permissions, please visit https://documentation.wazuh.com/current/user-manual/api/rbac/configuration.html",
  "code": 4000,
  "dapi_errors": {
    "unknown-node": {
      "error": "Permission denied: Resource type: agent:id"
    }
  }
}
```

- 404 - Resource not found
```json
{
  "title": "Resource Not Found",
  "detail": "The group does not exist",
  "remediation": "Please, use `GET /agents/groups` to find all available groups",
  "code": 1710,
  "dapi_errors": {
    "master-node": {
      "error": "The group does not exist"
    }
  }
}
```

# Test results

Unit and integration tests were executed to ensure everything is working as expected.

### CODE REVIEW

File: api/test/integration/env/configurations/experimental/agent/ciscat.sh [hunk 1]
```diff
@@ -5,4 +5,4 @@ cp -rf /configuration_files/test.keys /var/ossec/etc/test.keys
 cp -rf /configuration_files/ciscat /var/ossec/wodles/
 chown -R ossec:ossec /var/ossec/wodles/ciscat
 cd /var/ossec/wodles/ciscat && if [ -e CIS-CAT.sh ]; then chmod +x CIS-CAT.sh ; fi
-/var/ossec/bin/ossec_control restart
+#/var/ossec/bin/ossec_control restart
```
Comment (davidjiglesias) [inline api/test/integration/env/configurations/experimental/agent/ciscat.sh:8]: ???

Comment (CarlosRS9) [reply api/test/integration/env/configurations/experimental/agent/ciscat.sh]: Removed
