### PR TITLE
Fix populated values of syscollector delta when it contains null elements

### LINKED ISSUE #10695: Syscollector delta alerts have invalid field values
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|  dev-syscollector-deltas | wazuh-analysisd | Manager | Any | Any |

## Description
Hi team!

During  #7269 exploratory session (#8811), multiples wrong alerts (invalid values) related to INSERTED, MODIFIED and DELETED syscollector deltas were found.

### Steps to reproduce
1. Add next rules into `local_rules.xml` to trigger rules related to processes deltas
```xml
<group name="syscollector,">

    <rule id="100221" level="3" >
        <if_sid>221</if_sid>
        <description>Syscollector event.</description>
    </rule>
    <!-- processes -->
    <rule id="100300" level="0" >
        <if_sid>100221</if_sid>
        <field name="type">dbsync_processes</field>
        <description>Syscollector process event.</description>
    </rule>
    <rule id="100301" level="3" >
        <if_sid>100300</if_sid>
        <field name="operation_type">INSERTED</field>
        <description>Syscollector process creation event.</description>
    </rule>
    <rule id="100302" level="3" >
        <if_sid>100300</if_sid>
        <field name="operation_type">MODIFIED</field>
        <description>Syscollector process modification event.</description>
    </rule>
    <rule id="100303" level="3" >
        <if_sid>100300</if_sid>
        <field name="operation_type">DELETED</field>
        <description>Syscollector process deletion event.</description>
    </rule>
</group>
```
2. Reset the Manager
3. As a test, run the next command simulating an agent's INSERTED delta
```
echo 'd:[001] (myhostname) any->syscollector:{"data":{"checksum":"fff729165d88226792489aabc4cf304fb712f319","cmd":"wmplayer.exe","name":"wmplayer.exe","nlwp":27,"pid":"3548","ppid":2352,"priority":8,"scan_time":"2021/10/29 14:26:24","session":1,"size":16703488,"stime":0,"utime":0,"vm_size":49065984},"operation":"INSERTED","type":"dbsync_processes"}' | nc -w 0 -Uu /var/ossec/queue/sockets/queue
```
4. As a test, run the next command simulating an agent's MODIFIED delta
```
echo 'd:[001] (myhostname) any->syscollector:{"data":{"checksum":"a83ef7ea5f256a79da4ae83884adc8e08b4f42e1","nlwp":19,"pid":"3548","scan_time":"2021/10/29 14:27:35","size":17813504,"vm_size":51060736},"operation":"MODIFIED","type":"dbsync_processes"}' | nc -w 0 -Uu /var/ossec/queue/sockets/queue
```
### Expected result
4. The modified process delta rule (100302) displays all fields, regardless of whether or not changes have been made.
### Current result
4. Command's output is OK, but the alerts are still with invalid data.
```
ok 2021/10/29 14:27:35|3548|wmplayer.exe||2352|0|0|C:\Program Files\Windows Media Player\wmplayer.exe|||||||||8|0|17813504|51060736|0|0|0|0|1|19|0|0|0|a83ef7ea5f256a79da4ae83884adc8e08b4f42e1|# 
```
The modified process delta rule (100302) displays wrong fields values, like they have some kind of offset (see ppid true value shown as `state`)
```json
{
   "timestamp":"2021-10-29T14:27:41.488+0000",
   "rule":{
      "level":3,
      "description":"Syscollector process modification event.",
      "id":"100302",
      "firedtimes":77,
      "mail":false,
      "groups":[
         "syscollector"
      ]
   },
   "agent":{
      "id":"003",
      "name":"VANILLA-WIN7-32BIT",
      "ip":"10.0.2.15"
   },
   "manager":{
      "name":"ubuntu-bionic"
   },
   "id":"1635517661.1226977",
   "full_log":"{\"data\":{\"checksum\":\"a83ef7ea5f256a79da4ae83884adc8e08b4f42e1\",\"nlwp\":19,\"pid\":\"3548\",\"scan_time\":\"2021/10/29 14:27:35\",\"size\":17813504,\"vm_size\":51060736},\"operation\":\"MODIFIED\",\"type\":\"dbsync_processes\"}",
   "decoder":{
      "name":"syscollector"
   },
   "data":{
      "type":"dbsync_processes",
      "process":{
         "pid":"3548",
         "name":"wmplayer.exe",
         "state":"2352",
         "ppid":"0",
         "utime":"0",
         "stime":"C:\\Program Files\\Windows Media Player\\wmplayer.exe",
         "cmd":"8",
         "args":"0",
         "euser":"17813504",
         "ruser":"51060736",
         "suser":"0",
         "egroup":"0",
         "rgroup":"0",
         "sgroup":"0",
         "fgroup":"1",
         "priority":"19",
         "nice":"0",
         "size":"0",
         "vm_size":"0",
         "resident":"a83ef7ea5f256a79da4ae83884adc8e08b4f42e1"
      },
      "operation_type":"MODIFIED"
   },
   "location":"syscollector"
}
```

## DoD
- [x] Modify implementation of fill_alert_data to strchr approach -> examples on wdb_delta_event.c:57
- [x] Add unit tests.
- [x] Add case on wazuh-qa.
- [x] Request manual test to another team member. -> @HanesSciarrone 

Regards,
Nico

### LINKED ISSUE #10758: Syscollector INSERTED delta alerts are wrongly showing missing fields as NULL
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|  dev-syscollector-deltas | wazuh-analysisd | Manager | Any | Any |

## Description
Hi team!

During  #7269 exploratory session (#8811), we found that INSERTED syscollector deltas that do not contain all fields are wrongly populated. showing "NULL" strings.

### Steps to reproduce
1. Add next rules into `local_rules.xml` to trigger rules related to processes deltas
```xml
<group name="syscollector,">

    <rule id="100221" level="3" >
        <if_sid>221</if_sid>
        <description>Syscollector event.</description>
    </rule>
    <!-- processes -->
    <rule id="100300" level="0" >
        <if_sid>100221</if_sid>
        <field name="type">dbsync_processes</field>
        <description>Syscollector process event.</description>
    </rule>
    <rule id="100301" level="3" >
        <if_sid>100300</if_sid>
        <field name="operation_type">INSERTED</field>
        <description>Syscollector process creation event.</description>
    </rule>
    <rule id="100302" level="3" >
        <if_sid>100300</if_sid>
        <field name="operation_type">MODIFIED</field>
        <description>Syscollector process modification event.</description>
    </rule>
    <rule id="100303" level="3" >
        <if_sid>100300</if_sid>
        <field name="operation_type">DELETED</field>
        <description>Syscollector process deletion event.</description>
    </rule>
</group>
```
2. Reset the Manager
3. As a test, run the next command simulating an agent's INSERTED delta
```
echo 'd:[001] (myhostname) any->syscollector:{"data":{"architecture":"x86_64","checksum":"8952036097db5efbbdeeaf2fff1ae1b71fba237c","format":"win","install_time":null,"item_id":"e05f71535f00627e8b75765a3c4e97a50c0aa72d","location":"C:\\Program Files\\7-Zip\\","name":"7-Zip 19.00","scan_time":"2021/10/29 21:06:39","vendor":"Igor Pavlov","version":"19.00"},"operation":"INSERTED","type":"dbsync_packages"}' | nc -w 0 -Uu /var/ossec/queue/sockets/queue
```
### Expected result
3. The inserted process delta alert(rule 100302) display only fields that does have defined values.
### Current result
3. The inserted process delta alert(rule 100302) display fields that are missing in the json delta, showing `NULL` for those that meant to be skipped.

```json
{
   "timestamp":"2021-10-29T21:06:40.747+0000",
   "rule":{
      "level":3,
      "description":"Syscollector packages creation event.",
      "id":"100341",
      "firedtimes":1,
      "mail":false,
      "groups":[
         "syscollector"
      ]
   },
   "agent":{
      "id":"001",
      "name":"vagrant",
      "ip":"192.168.100.17"
   },
   "manager":{
      "name":"ubuntu-bionic"
   },
   "id":"1635541600.1316543",
   "full_log":"{\"data\":{\"architecture\":\"x86_64\",\"checksum\":\"8952036097db5efbbdeeaf2fff1ae1b71fba237c\",\"format\":\"win\",\"install_time\":null,\"item_id\":\"e05f71535f00627e8b75765a3c4e97a50c0aa72d\",\"location\":\"C:\\\\Program Files\\\\7-Zip\\\\\",\"name\":\"7-Zip 19.00\",\"scan_time\":\"2021/10/29 21:06:39\",\"vendor\":\"Igor Pavlov\",\"version\":\"19.00\"},\"operation\":\"INSERTED\",\"type\":\"dbsync_packages\"}",
   "decoder":{
      "name":"syscollector"
   },
   "data":{
      "type":"dbsync_packages",
      "program":{
         "format":"win",
         "name":"7-Zip 19.00",
         "priority":"NULL",
         "size":"NULL",
         "vendor":"Igor Pavlov",
         "version":"19.00",
         "architecture":"x86_64",
         "multiarch":"NULL",
         "source":"NULL",
         "description":"NULL",
         "location":"C:\\Program Files\\7-Zip\\"
      },
      "operation_type":"INSERTED"
   },
   "location":"syscollector"
}
```

## DoD
- [ ] Modify implementation of decode_dbsync function (src/analysisd/decoders/syscollector.c) to remove remove NULL before calling fill_event_alert 
- [ ] Add unit tests.
- [ ] Add case on wazuh-qa.
- [ ] Request manual test to another team member. -> @HanesSciarrone 

Regards,
Nico

### PR DESCRIPTION
**Pull request by jnasselle**
|Related issue|
|---|
|Closes #10695|
|Closes #10758|

## Description

Hi team!

This PR aims to fix #10695 issue by checking pipe-separated delta information (directly from INSERTED delta or response for MODIFIED/DELETED response from wazuh-db) and filling event information structure with the proper dynamic fields and ther values

- Before fix:
```json
{
   "timestamp":"2021-11-01T17:38:35.243+0000",
   "rule":{
      "level":3,
      "description":"Syscollector port creation event.",
      "id":"100311",
      "firedtimes":11,
      "mail":false,
      "groups":[
         "syscollector"
      ]
   },
   "agent":{
      "id":"006",
      "name":"archlinux",
      "ip":"10.0.2.15"
   },
   "manager":{
      "name":"ubuntu-bionic"
   },
   "id":"1635788315.3958700",
   "full_log":"{\"data\":{\"checksum\":\"944fb6182222660aeca5b27bcd14a579db60b58c\",\"inode\":30905,\"item_id\":\"31ec8d41b06cc6dea02d9f088067d379d761732d\",\"local_ip\":\"192.168.100.90\",\"local_port\":53462,\"pid\":0,\"process\":null,\"protocol\":\"tcp\",\"remote_ip\":\"192.168.100.200\",\"remote_port\":10000,\"rx_queue\":0,\"scan_time\":\"2021/11/01 17:38:40\",\"state\":\"established\",\"tx_queue\":0},\"operation\":\"INSERTED\",\"type\":\"dbsync_ports\"}",
   "decoder":{
      "name":"syscollector"
   },
   "data":{
      "type":"dbsync_ports",
      "port":{
         "protocol":"tcp",
         "local_ip":"192.168.100.90",
         "local_port":"53462",
         "remote_ip":"192.168.100.200",
         "remote_port":"10000",
         "tx_queue":"0",
         "rx_queue":"0",
         "inode":"30905",
         "state":"established",
         "pid":"0",
         "process":"944fb6182222660aeca5b27bcd14a579db60b58c"
      },
      "operation_type":"INSERTED"
   },
   "location":"syscollector"
}
```
- After fix:
```json
{
   "timestamp":"2021-11-03T12:41:32.307+0000",
   "rule":{
      "level":3,
      "description":"Syscollector port creation event.",
      "id":"100311",
      "firedtimes":2,
      "mail":false,
      "groups":[
         "syscollector"
      ]
   },
   "agent":{
      "id":"001",
      "name":"archlinux",
      "ip":"10.0.2.15"
   },
   "manager":{
      "name":"wazuh-dev"
   },
   "id":"1635943292.229132",
   "full_log":"{\"data\":{\"checksum\":\"f84788699004511b97f1f6aa1f11104f26a51c3c\",\"inode\":18119,\"item_id\":\"4873c24cf79381407277f27dd9bb80d1c4606de9\",\"local_ip\":\"192.168.100.90\",\"local_port\":60672,\"pid\":0,\"process\":null,\"protocol\":\"tcp\",\"remote_ip\":\"192.168.100.60\",\"remote_port\":10000,\"rx_queue\":0,\"scan_time\":\"2021/11/03 12:41:31\",\"state\":\"established\",\"tx_queue\":0},\"operation\":\"INSERTED\",\"type\":\"dbsync_ports\"}",
   "decoder":{
      "name":"syscollector"
   },
   "data":{
      "type":"dbsync_ports",
      "port":{
         "protocol":"tcp",
         "local_ip":"192.168.100.90",
         "local_port":"60672",
         "remote_ip":"192.168.100.60",
         "remote_port":"10000",
         "tx_queue":"0",
         "rx_queue":"0",
         "inode":"18119",
         "state":"established",
         "pid":"0"
      },
      "operation_type":"INSERTED"
   },
   "location":"syscollector"
}
```

- After fix that solve INSERTED:
```json
{
   "timestamp":"2021-11-05T19:00:44.647+0000",
   "rule":{
      "level":3,
      "description":"Syscollector process creation event.",
      "id":"100301",
      "firedtimes":1,
      "mail":false,
      "groups":[
         "syscollector"
      ]
   },
   "agent":{
      "id":"000",
      "name":"myhostname"
   },
   "manager":{
      "name":"wazuh-dev"
   },
   "id":"1636138844.803348",
   "full_log":"{\"data\":{\"checksum\":\"fff729165d88226792489aabc4cf304fb712f319\",\"cmd\":\"wmplayer.exe\",\"name\":\"wmplayer.exe\",\"nlwp\":27,\"pid\":\"3548\",\"ppid\":2352,\"priority\":8,\"scan_time\":\"2021/10/29 14:26:24\",\"session\":null,\"size\":null,\"stime\":null,\"utime\":0,\"vm_size\":49065984},\"operation\":\"INSERTED\",\"type\":\"dbsync_processes\"}\n",
   "decoder":{
      "name":"syscollector"
   },
   "data":{
      "type":"dbsync_processes",
      "process":{
         "pid":"3548",
         "name":"wmplayer.exe",
         "ppid":"2352",
         "utime":"0",
         "cmd":"wmplayer.exe",
         "priority":"8",
         "vm_size":"49065984",
         "nlwp":"27"
      },
      "operation_type":"INSERTED"
   },
   "location":"syscollector"
}
```

## Tests

- Compilation without warnings in every supported platform
  - [x] Linux
  - [ ] Windows
  - [ ] MAC OS X
- [ ] Source installation
- [ ] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [x] Scan-build report
  - [ ] Coverity
  - [x] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

- [ ] Retrocompatibility with older Wazuh versions
- [ ] Working on cluster environments
- [ ] Configuration on demand reports new parameters
- [ ] The data flow works as expected (agent-manager-api-app)
- [ ] Added unit tests (for new features)
- [ ] Stress test for affected components

- Decoder/Rule tests
  - [ ] Added unit testing files ".ini"
  - [ ] runtests.py executed without errors

### CODE REVIEW

**Comment by HanesSciarrone** [comment]
I attach evidence that the solution working fine. The following agents were tested

## Ubuntu 20.04

### INSERTED

<details>
<summary>Package</summary>

Alerts.json
```json
{
  "timestamp":"2021-11-04T19:15:52.288+0000",
  "rule":{
    "level":3,
    "description":"Syscollector packages creation event.",
    "id":"100341",
    "firedtimes":1,
    "mail":false,
    "groups":[
      "syscollector"
    ]
  },
  "agent":{
    "id":"002",
    "name":"hanes-VirtualBox",
    "ip":"192.168.1.24"
  },
  "manager":{
    "name":"localhost.localdomain"
  },
  "id":"1636053352.317760",
  "full_log":"{\"data\":{\"architecture\":\"amd64\",\"checksum\":\"e429647b7165a37caccf9980480774507f7bae59\",\"description\":\"NET-3 networking toolkit\",\"format\":\"deb\",\"groups\":\"net\",\"item_id\":\"337652975e2eed1d1056af45f79e1aaa47a65df0\",\"multiarch\":\"foreign\",\"name\":\"net-tools\",\"priority\":\"important\",\"scan_time\":\"2021/11/04 19:15:52\",\"size\":844,\"source\":null,\"vendor\":\"Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>\",\"version\":\"1.60+git20180626.aebd88e-1ubuntu1\"},\"operation\":\"INSERTED\",\"type\":\"dbsync_packages\"}",
  "decoder":{
    "name":"syscollector"
  },
  "data":{
    "type":"dbsync_packages",
    "program":{
      "format":"deb",
      "name":"net-tools",
      "priority":"important",
      "size":"844",
      "vendor":"Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>",
      "install_time":"NULL",
      "version":"1.60+git20180626.aebd88e-1ubuntu1",
      "architecture":"amd64",
      "multiarch":"foreign",
      "description":"NET-3 networking toolkit",
      "location":"NULL"
    },
    "operation_type":"INSERTED"
  },
  "location":"syscollector"
}
```

Delta
```
2021/11/04 19:15:52 wazuh-db[6486] wdb_parser.c:257 at wdb_parse(): DEBUG: Agent 002 query: dbsync packages INSERTED 2021/11/04 19:15:52|deb|net-tools|important|net|844|Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>|NULL|1.60+git20180626.aebd88e-1ubuntu1|amd64|foreign||NET-3 networking toolkit|NULL|NULL|NULL|NULL|e429647b7165a37caccf9980480774507f7bae59|337652975e2eed1d1056af45f79e1aaa47a65df0|
```

Database

```
scan_id|scan_time|format|name|priority|section|size|vendor|install_time|version|architecture|multiarch|source|description|location|triaged|cpe|msu_name|checksum|item_id

0|2021/11/04 19:15:52|deb|net-tools|important|net|844|Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>||1.60+git20180626.aebd88e-1ubuntu1|amd64|foreign||NET-3 networking toolkit||0|||e429647b7165a37caccf9980480774507f7bae59|337652975e2eed1d1056af45f79e1aaa47a65df0
```

</details>


<details>
<summary>Ports</summary>

Alerts.json
```json
{
  "timestamp":"2021-11-04T18:08:14.940+0000",
  "rule":{
    "level":3,
    "description":"Syscollector port creation event.",
    "id":"100311",
    "firedtimes":2,
    "mail":false,
    "groups":[
      "syscollector"
    ]
  },
  "agent":{
    "id":"002",
    "name":"hanes-VirtualBox",
    "ip":"192.168.1.24"
  },
  "manager":{
    "name":"localhost.localdomain"
  },
  "id":"1636049294.265551",
  "full_log":"{\"data\":{\"checksum\":\"1f1350dc9ba7981eab6e35844136cdbf978da250\",\"inode\":40994,\"item_id\":\"d7bf866f714bc086db57ca47fcec52ee818098a9\",\"local_ip\":\"0.0.0.0\",\"local_port\":3434,\"pid\":0,\"process\":null,\"protocol\":\"tcp\",\"remote_ip\":\"0.0.0.0\",\"remote_port\":0,\"rx_queue\":0,\"scan_time\":\"2021/11/04 18:08:14\",\"state\":\"listening\",\"tx_queue\":0},\"operation\":\"INSERTED\",\"type\":\"dbsync_ports\"}",
  "decoder":{
    "name":"syscollector"
  },
  "data":{
    "type":"dbsync_ports",
    "port":{
      "protocol":"tcp",
      "local_ip":"0.0.0.0",
      "local_port":"3434",
      "remote_ip":"0.0.0.0",
      "remote_port":"0",
      "tx_queue":"0",
      "rx_queue":"0",
      "inode":"40994",
      "state":"listening",
      "pid":"0"
    },
    "operation_type":"INSERTED"
  },
  "location":"syscollector"
}
```

Delta
```
2021/11/04 18:08:14 wazuh-db[6256] wdb_parser.c:257 at wdb_parse(): DEBUG: Agent 002 query: dbsync ports INSERTED 2021/11/04 18:08:14|tcp|0.0.0.0|3434|0.0.0.0|0|0|0|40994|listening|0||1f1350dc9ba7981eab6e35844136cdbf978da250|d7bf866f714bc086db57ca47fcec52ee818098a9
```

Database

```
scan_id|scan_time|protocol|local_ip|local_port|remote_ip|remote_port|tx_queue|rx_queue|inode|state|PID|process|checksum|item_id
0|2021/11/04 18:08:14|tcp|0.0.0.0|3434|0.0.0.0|0|0|0|40994|listening|0||1f1350dc9ba7981eab6e35844136cdbf978da250|d7bf866f714bc086db57ca47fcec52ee818098a9
```

</details>


<details>
<summary>Porcesses</summary>

Alerts.json
```json
{
  "timestamp":"2021-11-04T21:57:11.863+0000",
  "rule":{
    "level":3,
    "description":"Syscollector process creation event.",
    "id":"100301",
    "firedtimes":4,
    "mail":false,
    "groups":[
      "syscollector"
    ]
  },
  "agent":{
    "id":"002",
    "name":"hanes-VirtualBox",
    "ip":"192.168.1.24"
  },
  "manager":{
    "name":"localhost.localdomain"
  },
  "id":"1636063031.434626",
  "full_log":"{\"data\":{\"argvs\":\"-contentproc -childID 3 -isForBrowser -prefsLen 5626 -prefMapSize 239842 -jsInit 278680 -parentBuildID 20211028161635 -appdir /usr/lib/firefox/browser 6999 true tab\",\"checksum\":\"40bbfbd54ddb8094e828c2f453eed73d63d6a012\",\"cmd\":\"/usr/lib/firefox/firefox\",\"egroup\":\"hanes\",\"euser\":\"hanes\",\"fgroup\":\"hanes\",\"name\":\"Web Content\",\"nice\":0,\"nlwp\":11,\"pgrp\":1730,\"pid\":\"7175\",\"ppid\":6999,\"priority\":20,\"processor\":1,\"resident\":18101,\"rgroup\":\"hanes\",\"ruser\":\"hanes\",\"scan_time\":\"2021/11/04 21:57:07\",\"session\":1730,\"sgroup\":\"hanes\",\"share\":15425,\"size\":595070,\"start_time\":1383725,\"state\":\"S\",\"stime\":3,\"suser\":\"hanes\",\"tgid\":7175,\"tty\":0,\"utime\":6,\"vm_size\":2380280},\"operation\":\"INSERTED\",\"type\":\"dbsync_processes\"}",
  "decoder":{
    "name":"syscollector"
  },
  "data":{
    "type":"dbsync_processes",
    "process":{
      "pid":"7175",
      "name":"Web Content",
      "state":"S",
      "ppid":"6999",
      "utime":"6",
      "stime":"3",
      "cmd":"/usr/lib/firefox/firefox",
      "args":"-contentproc -childID 3 -isForBrowser -prefsLen 5626 -prefMapSize 239842 -jsInit 278680 -parentBuildID 20211028161635 -appdir /usr/lib/firefox/browser 6999 true tab",
      "euser":"hanes",
      "ruser":"hanes",
      "suser":"hanes",
      "egroup":"hanes",
      "rgroup":"hanes",
      "sgroup":"hanes",
      "fgroup":"hanes",
      "priority":"20",
      "nice":"0",
      "size":"595070",
      "vm_size":"2380280",
      "resident":"18101",
      "share":"15425",
      "start_time":"1383725",
      "pgrp":"1730",
      "session":"1730",
      "nlwp":"11",
      "tgid":"7175",
      "tty":"0",
      "processor":"1"
    },
    "operation_type":"INSERTED"
  },
  "location":"syscollector"
}
```

Delta
```
2021/11/04 21:57:11 wazuh-db[6804] wdb_parser.c:257 at wdb_parse(): DEBUG: Agent 002 query: dbsync processes INSERTED 2021/11/04 21:57:07|7175|Web Content|S|6999|6|3|/usr/lib/firefox/firefox|-contentproc -childID 3 -isForBrowser -prefsLen 5626 -prefMapSize 239842 -jsInit 278680 -parentBuildID 20211028161635 -appdir /usr/lib/firefox/browser 6999 true tab|hanes|hanes|hanes|hanes|hanes|hanes|hanes|20|0|595070|2380280|18101|15425|1383725|1730|1730|11|7175|0|1|40bbfbd54ddb8094e828c2f453eed73d63d6a012|

```

Data base

```
scan_id|scan_time|pid|name|state|ppid|utime|stime|cmd|argvs|euser|ruser|suser|egroup|rgroup|sgroup|fgroup|priority|nice|size|vm_size|resident|share|start_time|pgrp|session|nlwp|tgid|tty|processor|checksum

0|2021/11/04 21:57:07|7175|Web Content|S|6999|6|3|/usr/lib/firefox/firefox|-contentproc -childID 3 -isForBrowser -prefsLen 5626 -prefMapSize 239842 -jsInit 278680 -parentBuildID 20211028161635 -appdir /usr/lib/firefox/browser 6999 true tab|hanes|hanes|hanes|hanes|hanes|hanes|hanes|20|0|595070|2380280|18101|15425|1383725|1730|1730|11|7175|0|1|40bbfbd54ddb8094e828c2f453eed73d63d6a012
```

</details>

### MODIFIED

<details>
<summary>Ports</summary>

Alerts.json
```json
{
  "timestamp":"2021-11-04T18:14:17.351+0000",
  "rule":{
    "level":3,
    "description":"Syscollector port modification event.",
    "id":"100312",
    "firedtimes":1,
    "mail":false,
    "groups":[
      "syscollector"
    ]
  },
  "agent":{
    "id":"002",
    "name":"hanes-VirtualBox",
    "ip":"192.168.1.24"
  },
  "manager":{
    "name":"localhost.localdomain"
  },
  "id":"1636049657.268339",
  "full_log":"{\"data\":{\"checksum\":\"eae3ed8b34520e38c6f6f3b045b91961cd03e1af\",\"inode\":40995,\"local_ip\":\"192.168.1.24\",\"local_port\":3434,\"protocol\":\"tcp\",\"rx_queue\":1,\"scan_time\":\"2021/11/04 18:14:17\",\"state\":\"close_wait\"},\"operation\":\"MODIFIED\",\"type\":\"dbsync_ports\"}",
  "decoder":{
    "name":"syscollector"
  },
  "data":{
    "type":"dbsync_ports",
    "port":{
      "protocol":"tcp",
      "local_ip":"192.168.1.24",
      "local_port":"3434",
      "remote_ip":"192.168.1.60",
      "remote_port":"49691",
      "tx_queue":"0",
      "rx_queue":"1",
      "inode":"40995",
      "state":"close_wait",
      "pid":"0"
    },
    "operation_type":"MODIFIED"
  },
  "location":"syscollector"
}
```

Delta
```
2021/11/04 18:14:17 wazuh-db[6304] wdb_parser.c:257 at wdb_parse(): DEBUG: Agent 002 query: dbsync ports MODIFIED 2021/11/04 18:14:17|tcp|192.168.1.24|3434|NULL|NULL|NULL|1|40995|close_wait|NULL|NULL|eae3ed8b34520e38c6f6f3b045b91961cd03e1af|NULL|
```

Database

```
scan_id|scan_time|protocol|local_ip|local_port|remote_ip|remote_port|tx_queue|rx_queue|inode|state|PID|process|checksum|item_id
0|2021/11/04 18:14:17|tcp|192.168.1.24|3434|192.168.1.60|49691|0|1|40995|close_wait|0||eae3ed8b34520e38c6f6f3b045b91961cd03e1af|a3148d36dd314346342916123a1f47ee51789535
```

</details>


<details>
<summary>Porcesses</summary>

Alerts.json
```json
{
  "timestamp":"2021-11-04T22:09:04.052+0000",
  "rule":{
    "level":3,
    "description":"Syscollector process modification event.",
    "id":"100302",
    "firedtimes":117,
    "mail":false,
    "groups":[
      "syscollector"
    ]
  },
  "agent":{
    "id":"002",
    "name":"hanes-VirtualBox",
    "ip":"192.168.1.24"
  },
  "manager":{
    "name":"localhost.localdomain"
  },
  "id":"1636063744.563454",
  "full_log":"{\"data\":{\"checksum\":\"cbdba87e45f328c0411f04ceb8304bd23b34bf26\",\"nlwp\":12,\"pid\":\"7925\",\"processor\":1,\"scan_time\":\"2021/11/04 22:09:01\",\"size\":595074,\"stime\":3,\"utime\":6,\"vm_size\":2380296},\"operation\":\"MODIFIED\",\"type\":\"dbsync_processes\"}",
  "decoder":{
    "name":"syscollector"
  },
  "data":{
    "type":"dbsync_processes",
    "process":{
      "pid":"7925",
      "name":"Web Content",
      "state":"S",
      "ppid":"6999",
      "utime":"6",
      "stime":"3",
      "cmd":"/usr/lib/firefox/firefox",
      "args":"-contentproc -childID 4 -isForBrowser -prefsLen 9533 -prefMapSize 239842 -jsInit 278680 -parentBuildID 20211028161635 -appdir /usr/lib/firefox/browser 6999 true tab",
      "euser":"hanes",
      "ruser":"hanes",
      "suser":"hanes",
      "egroup":"hanes",
      "rgroup":"hanes",
      "sgroup":"hanes",
      "fgroup":"hanes",
      "priority":"20",
      "nice":"0",
      "size":"595074",
      "vm_size":"2380296",
      "resident":"18001",
      "share":"15365",
      "start_time":"1458240",
      "pgrp":"1730",
      "session":"1730",
      "nlwp":"12",
      "tgid":"7925",
      "tty":"0",
      "processor":"1"
    },
    "operation_type":"MODIFIED"
  },
  "location":"syscollector"
}

```

Delta
```
2021/11/04 22:09:04 wazuh-db[6862] wdb_parser.c:257 at wdb_parse(): DEBUG: Agent 002 query: dbsync processes MODIFIED 2021/11/04 22:09:01|7925|NULL|NULL|NULL|6|3|NULL|NULL|NULL|NULL|NULL|NULL|NULL|NULL|NULL|NULL|NULL|595074|2380296|NULL|NULL|NULL|NULL|NULL|12|NULL|NULL|1|cbdba87e45f328c0411f04ceb8304bd23b34bf26|
```

Database

```
scan_id|scan_time|pid|name|state|ppid|utime|stime|cmd|argvs|euser|ruser|suser|egroup|rgroup|sgroup|fgroup|priority|nice|size|vm_size|resident|share|start_time|pgrp|session|nlwp|tgid|tty|processor|checksum

0|2021/11/04 22:09:01|7925|Web Content|S|6999|6|3|/usr/lib/firefox/firefox|-contentproc -childID 4 -isForBrowser -prefsLen 9533 -prefMapSize 239842 -jsInit 278680 -parentBuildID 20211028161635 -appdir /usr/lib/firefox/browser 6999 true tab|hanes|hanes|hanes|hanes|hanes|hanes|hanes|20|0|595074|2380296|18001|15365|1458240|1730|1730|12|7925|0|1|cbdba87e45f328c0411f04ceb8304bd23b34bf26
```

</details>

### DELETED

<details>
<summary>Package</summary>

Alerts.json
```json
{
  "timestamp":"2021-11-04T18:27:45.149+0000",
  "rule":{
    "level":3,
    "description":"Syscollector packages deletion event.",
    "id":"100343",
    "firedtimes":1,
    "mail":false,
    "groups":[
      "syscollector"
    ]
  },
  "agent":{
    "id":"002",
    "name":"hanes-VirtualBox",
    "ip":"192.168.1.24"
  },
  "manager":{
    "name":"localhost.localdomain"
  },
  "id":"1636050465.287726",
  "full_log":"{\"data\":{\"architecture\":\"amd64\",\"name\":\"net-tools\",\"scan_time\":\"2021/11/04 18:27:43\",\"version\":\"1.60+git20180626.aebd88e-1ubuntu1\"},\"operation\":\"DELETED\",\"type\":\"dbsync_packages\"}",
  "decoder":{
    "name":"syscollector"
  },
  "data":{
    "type":"dbsync_packages",
    "program":{
      "format":"deb",
      "name":"net-tools",
      "priority":"important",
      "size":"844",
      "vendor":"Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>",
      "install_time":"(null)",
      "version":"1.60+git20180626.aebd88e-1ubuntu1",
      "architecture":"amd64",
      "multiarch":"foreign",
      "source":"(null)",
      "description":"NET-3 networking toolkit",
      "location":"(null)"
    },
    "operation_type":"DELETED"
  },
  "location":"syscollector"
}
```

Delta
```
2021/11/04 18:27:45 wazuh-db[6346] wdb_parser.c:257 at wdb_parse(): DEBUG: Agent 002 query: dbsync packages DELETED 2021/11/04 18:27:43|NULL|net-tools|NULL|NULL|NULL|NULL|NULL|1.60+git20180626.aebd88e-1ubuntu1|amd64|NULL|NULL|NULL|NULL|NULL|NULL|NULL|NULL|NULL|
```

</details>


<details>
<summary>Ports</summary>

Alerts.json
```json
{
  "timestamp":"2021-11-04T18:17:00.333+0000",
  "rule":{
    "level":3,
    "description":"Syscollector ports event.",
    "id":"100310",
    "firedtimes":2,
    "mail":false,
    "groups":[
      "syscollector"
    ]
  },
  "agent":{
    "id":"002",
    "name":"hanes-VirtualBox",
    "ip":"192.168.1.24"
  },
  "manager":{
    "name":"localhost.localdomain"
  },
  "id":"1636049820.269014",
  "full_log":"{\"data\":{\"inode\":42776,\"local_ip\":\"192.168.1.24\",\"local_port\":53836,\"protocol\":\"tcp\",\"scan_time\":\"2021/11/04 18:17:00\"},\"operation\":\"DELETED\",\"type\":\"dbsync_ports\"}",
  "decoder":{
    "name":"syscollector"
  },
  "data":{
    "type":"dbsync_ports"
  },
  "location":"syscollector"
}
```

Delta
```
2021/11/04 18:17:00 wazuh-db[6322] wdb_parser.c:257 at wdb_parse(): DEBUG: Agent 002 query: dbsync ports DELETED 2021/11/04 18:17:00|tcp|192.168.1.24|53836|NULL|NULL|NULL|NULL|42776|NULL|NULL|NULL|NULL|NULL|
```

</details>


<details>
<summary>Porcesses</summary>

Alerts.json
```json
{
  "timestamp":"2021-11-04T21:48:56.602+0000",
  "rule":{
    "level":3,
    "description":"Syscollector process deletion event.",
    "id":"100303",
    "firedtimes":5,
    "mail":false,
    "groups":[
      "syscollector"
    ]
  },
  "agent":{
    "id":"002",
    "name":"hanes-VirtualBox",
    "ip":"192.168.1.24"
  },
  "manager":{
    "name":"localhost.localdomain"
  },
  "id":"1636062536.362151",
  "full_log":"{\"data\":{\"pid\":\"6938\",\"scan_time\":\"2021/11/04 21:48:51\"},\"operation\":\"DELETED\",\"type\":\"dbsync_processes\"}",
  "decoder":{
    "name":"syscollector"
  },
  "data":{
    "type":"dbsync_processes",
    "process":{
      "pid":"6938",
      "name":"sleep",
      "state":"S",
      "ppid":"6864",
      "utime":"0",
      "stime":"0",
      "cmd":"sleep",
      "args":"1",
      "euser":"root",
      "ruser":"root",
      "suser":"root",
      "egroup":"root",
      "rgroup":"root",
      "sgroup":"root",
      "fgroup":"root",
      "priority":"20",
      "nice":"0",
      "size":"4179",
      "vm_size":"16716",
      "resident":"129",
      "share":"114",
      "start_time":"1332805",
      "pgrp":"6864",
      "session":"6864",
      "nlwp":"1",
      "tgid":"6938",
      "tty":"0",
      "processor":"0"
    },
    "operation_type":"DELETED"
  },
  "location":"syscollector"
}
```

Delta
```
2021/11/04 21:48:56 wazuh-db[6765] wdb_parser.c:257 at wdb_parse(): DEBUG: Agent 002 query: dbsync processes DELETED 2021/11/04 21:48:51|6938|NULL|NULL|NULL|NULL|NULL|NULL|NULL|NULL|NULL|NULL|NULL|NULL|NULL|NULL|NULL|NULL|NULL|NULL|NULL|NULL|NULL|NULL|NULL|NULL|NULL|NULL|NULL|NULL|
```

</details>

## CentOS 8

<details>
<summary>Package</summary>

Alerts.json
```json

```

Delta
```

```

Database

```

```

</details>


<details>
<summary>Ports</summary>

Alerts.json
```json

```

Delta
```

```

Database

```

```

</details>


<details>
<summary>Porcesses</summary>

Alerts.json
```json

```

Delta
```

```

Data base

```

```

</details>

**Review by HanesSciarrone — APPROVED** [review]
Excellent job @jnasselle .

File: src/analysisd/decoders/syscollector.c [hunk 1]
```diff
@@ -2039,14 +2068,16 @@ int decode_dbsync( Eventinfo * lf, char *msg_type, cJSON *logJSON, int *socket)
 
                     buffer_t *msg = buffer_initialize(OS_SIZE_6144);
                     buffer_push(msg, header, header_size);
-                    fill_data_dbsync(data, field_list, msg);
+
+                    const bool is_inserted_operation = strcmp(operation, "INSERTED") == 0 ? true : false;
```
Comment (Dwordcito) [inline src/analysisd/decoders/syscollector.c:2072]: true : false is trivial, remove it.
