### PR TITLE
Specify when getFile failed due to no entries in the DB.

### LINKED ISSUE #12476: FIM printing ERROR `There are more or 0 rows`
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| [9103-replace-fim-db-dbsync](https://github.com/wazuh/wazuh/tree/9103-replace-fim-db-dbsync) | FIM |Agent | Packages/Sources | All|

Hi team!

At this moment, there are certain situations where FIM is printing this error:
- First scan in Windows monitoring wildcards.
- Some remove events in realtime/whodata

```
2022/02/25 09:10:58 wazuh-agent[4596] run_check.c:258 at start_daemon(): INFO: (6010): File integrity monitoring scan frequency: 2 seconds
 (6010): File integrity monitoring scan frequency: 2 seconds
2022/02/25 09:10:58 wazuh-agent[4596] create_db.c:394 at fim_scan(): INFO: (6008): File integrity monitoring scan started.
2022/02/25 09:10:58 wazuh-agent[4596] run_check.c:117 at send_syscheck_msg(): DEBUG: (6321): Sending FIM event: {"type":"scan_start","data":{"timestamp":1645780258}}
2022/02/25 09:10:58 wazuh-agent[4596] create_db.c:406 at fim_scan(): DEBUG: (6348): Size of 'queue/diff' folder: 0.00000 KB.
2022/02/25 09:10:58 wazuh-agent[4596] create_db.c:1611 at update_wildcards_config(): DEBUG: (6361): Starting configuration wildcards update.
2022/02/25 09:10:58 wazuh-agent[4596] logging_helper.c:50 at loggingFunction(): ERROR: There are more or 0 rows
2022/02/25 09:10:58 wazuh-agent[4596] create_db.c:1686 at update_wildcards_config(): DEBUG: (6362): Removing entry 'c:\users\Public\downloads' due to it has not been expanded by the wildcards
2022/02/25 09:10:58 wazuh-agent[4596] logging_helper.c:50 at loggingFunction(): ERROR: There are more or 0 rows
2022/02/25 09:10:58 wazuh-agent[4596] create_db.c:1686 at update_wildcards_config(): DEBUG: (6362): Removing entry 'c:\users\Default\downloads' due to it has not been expanded by the wildcards
2022/02/25 09:10:58 wazuh-agent[4596] logging_helper.c:50 at loggingFunction(): ERROR: There are more or 0 rows
2022/02/25 09:10:58 wazuh-agent[4596] create_db.c:1686 at update_wildcards_config(): DEBUG: (6362): Removing entry 'c:\users\Administrator\downloads' due to it has not been expanded by the wildcards
2022/02/25 09:10:58 wazuh-agent[4596] create_db.c:1690 at update_wildcards_config(): DEBUG: (6363): Configuration wildcards update finalize.
2022/02/25 09:10:58 wazuh-agent[4596] registry.c:1048 at fim_registry_scan(): DEBUG: (6031): Registry integrity monitoring scan started
2022/02/25 09:10:58 wazuh-agent[4596] registry.c:1058 at fim_registry_scan(): DEBUG: (6207): Attempt to read: '[x64] HKEY_LOCAL_MACHINE\software\test'
2022/02/25 09:10:58 wazuh-agent[4596] registry.c:1058 at fim_registry_scan(): DEBUG: (6207): Attempt to read: '[x32] HKEY_LOCAL_MACHINE\software\tes
```

This error occurs when FIM is querying FIMDB if there is an entry with a specific path inside the DB. In some cases, this is not an error.

- [x] Analyze if there are some cases that can trigger the event other than the specified above.
- [x] Silence the error (maybe change it to a debug message) in case there is not any more cases.

### PR DESCRIPTION
**Pull request by antoniomanuelfr**
|Related issue|
|---|
|#12476|

## Description
Hi team!!

In order to fix the error `There are more or 0 rows` getFile will throw the `no_entry_found` exception and it will be caught by the caller, suppressing the error and printing a new debug message

#Closes #12476

## Configuration options

```xml
<syscheck>
    <disabled>no</disabled>

    <!-- Frequency that syscheck is executed default every 12 hours -->
    <frequency>900</frequency>

    <!-- Directories to check  (perform all possible verifications) -->
    <directories realtime="no" whodata="yes">/home/vagrant/test*</directories>

    <db_entry_limit>
      <files>90</files>
    </db_entry_limit>
```

## Logs/Alerts example

```
2022/03/02 10:40:01 wazuh-syscheckd[16623] audit_parse.c:504 at audit_parse(): INFO: (6027): Monitored directory '/home/vagrant/test' was removed: Audit rule removed.
2022/03/02 10:40:01 wazuh-syscheckd[16623] audit_parse.c:779 at audit_parse(): DEBUG: (6247): audit_event: uid=root, auid=vagrant, euid=root, gid=root, pid=17207, ppid=11466, inode=271160, path=/home/vagrant/test, pname=/usr/bin/rm
2022/03/02 10:40:01 wazuh-syscheckd[16623] audit_parse.c:789 at audit_parse(): DEBUG: (6213): Cannot get the real path of the link '/home/vagrant/test'
2022/03/02 10:40:01 wazuh-syscheckd[16623] logging_helper.c:65 at loggingFunction(): DEBUG: No entry found for /home/vagrant/test
2022/03/02 10:40:01 wazuh-syscheckd[16623] run_check.c:117 at send_syscheck_msg(): DEBUG: (6321): Sending FIM event: {"type":"event","data":{"path":"/home/vagrant/test/a","version":2,"mode":"whodata","type":"deleted","timestamp":1646217424,"attributes":{"type":"file","size":22,"perm":"rw-r--r--","uid":"0","gid":"0","user_name":"root","group_name":"root","inode":271774,"mtime":1646217424,"hash_md5":"43f5b1b65499d0e6816532b4550377cd","hash_sha1":"d3929e2733ca5edd2a638293a23602bd8d71e936","hash_sha256":"1ca31deb6f04dfe7963e9b1622e91a831f95bb420e4ebcdeb5dbbdd5620c76ad","checksum":"1e63b2cfbb94070e121214447b4ad0de9872ba7f"},"audit":{"user_id":"0","user_name":"root","process_name":"/usr/bin/rm","process_id":17207,"cwd":"/home/vagrant","group_id":"0","group_name":"root","audit_uid":"1000","audit_name":"vagrant","effective_uid":"0","effective_name":"root","parent_name":"/usr/bin/bash","parent_cwd":"/home/vagrant","ppid":11466}}}
2022/03/02 10:40:12 wazuh-syscheckd[16623] audit_rule_handling.c:158 at fim_audit_reload_rules(): DEBUG: (6275): Reloading Audit rules.
2022/03/02 10:40:12 wazuh-syscheckd[16623] audit_op.c:264 at audit_manage_rules(): DEBUG: (6222): Stat() function failed on: '/home/vagrant/test' due to [(2)-(No such file or directory)]

```

## Tests

- Compilation without warnings in every supported platform
  - [X] Linux
  - [x] Windows
  - [ ] MAC OS X
- [X] Source installation
- [X] Source upgrade

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory

### CODE REVIEW

File: src/syscheckd/src/db/src/file.cpp [hunk 1]
```diff
@@ -495,6 +495,10 @@ FIMDBErrorCode fim_db_get_path(const char* file_path, callback_context_t callbac
             });
             retVal = FIMDB_OK;
         }
+        catch (const no_entry_found& err)
+        {
+            FIMDB::instance().logFunction(LOG_DEBUG_VERBOSE, err.what());
```
Comment (FrancoRivero) [inline src/syscheckd/src/db/src/file.cpp:500]: why do you use LOG_DEBUG_VERBOSE instead LOG_ERROR?

**Review by chemamartinez — APPROVED** [review]

File: src/syscheckd/src/db/src/file.cpp (hunk 1 above)
Comment (antoniomanuelfr) [reply src/syscheckd/src/db/src/file.cpp:500]: The error `There are more or 0 rows` was printed when the `GetFile` was successfully executed, but there wasn't any entry in the DB with that PK. This is shouldn't print an error, as there are some parts of FIM that will check if there is an entry, and handle properly the case that there is not an entry in the DB. 
Nevertheless, we are going to leave a verbose log to help the debugging process.

**Review by jotacarma90 — APPROVED** [review]
LGTM
