### PR TITLE
Fix hang during shutdown.

### LINKED ISSUE #13314: Windows agent hangs during graceful shutdown due FIMDB changes
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| [9103-replace-fim-db-dbsync](https://github.com/wazuh/wazuh/tree/9103-replace-fim-db-dbsync) | FIM |Windows | Sources | All|

## Description
It seems to be that Windows agent hangs during graceful shutdown due FIMDB changes.

## DoD
- [ ] Reproduce the error
- [ ] RCA

### PR DESCRIPTION
**Pull request by Dwordcito**
|Related issue|
|---|
|Closes #13314 |

## Description
It seems to be that agent hangs during graceful shutdown due FIMDB changes.

**How to reproduce:** 
1- Install and register agent.
2- Stop agent during the initial synchronization.

**Expected:**
It doesn't hang on gracefull shutdown

### CODE REVIEW

File: src/shared_modules/rsync/src/registrationController.hpp [hunk 1]
```diff
@@ -0,0 +1,68 @@
...
+            while (it != m_componentStatus.end())
+            {
+                if (it->second == handle)
+                {
+                    it = m_componentStatus.erase(it);
+                }
+                else
+                {
+                    ++it;
+                }
```
Comment (jnasselle) [inline src/shared_modules/rsync/src/registrationController.hpp:56]: There's a scenario whether multiples components share the rsync handler?
If the answer is yes, this LGTM. Otherwise, the next code could be improved to
```suggestion
                if (it->second == handle)
                {
                    m_componentStatus.erase(it);
                    break;
                }          
                ++it;
```

File: src/shared_modules/rsync/src/rsyncImplementation.cpp [hunk 2]
```diff
@@ -399,7 +407,16 @@ void RSyncImplementation::sendAllData(const std::shared_ptr<DBSyncWrapper>& spDB
...
-            messageCreator->send(callbackWrapper, jsonSyncConfiguration, resultJSON);
+            const auto component { jsonSyncConfiguration.at("component").get_ref<const std::string&>() };
+
+            if (RSyncImplementation::instance().isComponentRegistered(component))
+            {
+                messageCreator->send(callbackWrapper, jsonSyncConfiguration, resultJSON);
+            }
+            else
+            {
+                throw std::runtime_error("Synchronization cancelled, component inactivated");
```
Comment (jnasselle) [inline src/shared_modules/rsync/src/rsyncImplementation.cpp:418]: This will create an ERROR message. From the user side, the concept of `component` is unrelated to inner implementation semantics.
I suggest to change this messages for a kindest one.

File: src/shared_modules/rsync/src/registrationController.hpp [hunk 3]
```diff
@@ -0,0 +1,68 @@
+/*
+ * Wazuh RSYNC
+ * Copyright (C) 2015, Wazuh Inc.
+ * May 26, 2022.
```
Comment (jnasselle) [inline src/shared_modules/rsync/src/registrationController.hpp:4]: @Dwordcito McFly :rofl:

File: src/shared_modules/rsync/src/registrationController.hpp (hunk 1 above)
Comment (Dwordcito) [reply src/shared_modules/rsync/src/registrationController.hpp:56]: > There's a scenario whether multiples components share the rsync handler?

Yes sir.

File: src/shared_modules/rsync/src/rsyncImplementation.cpp (hunk 2 above)
Comment (Dwordcito) [reply src/shared_modules/rsync/src/rsyncImplementation.cpp:418]: This message is printed to stderr, via the component registration try-catch, it is not intended for users.

File: src/shared_modules/rsync/src/registrationController.hpp (hunk 3 above)
Comment (Dwordcito) [reply src/shared_modules/rsync/src/registrationController.hpp:4]:
```suggestion
 * July 4, 2022.
```

**Review by HanesSciarrone — APPROVED** [review]

**Review by jftuduri — APPROVED** [review]
LGTM! 
Only comment is that the PR description is incomplete.

**Review by pereyra-m — APPROVED** [review]

**Review by HanesSciarrone — APPROVED** [review]

**Comment by jmv74211** [comment]
## QA review

- **Type**: Manual testing
- **Status**: Approved  🟢 
- **Testing issue**: https://github.com/wazuh/wazuh-qa/issues/3066
- **Comments**: Nothing to highlight. Everything seems to work properly
