### PR TITLE
[7618] HF format issue fix

### LINKED ISSUE #7618: Incorrect KB number parsing.
## Description

This issue was discovered by the @chemamartinez  team, and it is basically from the windows hotfix parser, which extracts the information by going through the windows registry.

in the DoD is the proposed fix.

```
sqlite> select * from sys_hotfixes;
0|2021/02/24 11:48:48|KB2534111.MSU\8847D77D|3c5b9261d91b60b7e27daa90a1afec9e6b727cf8
0|2021/02/24 11:48:48|KB976902\KB976932\SUPPORT\SSU\SAND\5A42A8EB|d63f10ff77489c780fe46ccb48a5d7d8e2e324bf
0|2021/02/24 11:48:48|KB976932\SAND\87C8A3D4|df00f66825258c45b161a48d086a9de27f4c0d31
```
imagen

Actual result: Incorrect KB Number.
Expected result: Correct KB number without exclusion.
Related PR: https://github.com/wazuh/wazuh/pull/6706
This issue is only reproducible in windows 7.

Destination branch: dev-syscollector-tde

Example code: https://godbolt.org/z/K4W38j

## DoD
- [x] Add regex to get KB number
- [x] Add unit test
- [x] PR - CI Pass

### PR DESCRIPTION
**Pull request by tinachoB**
|Related issue|
|---|
|Closes #7618 |

## **Description**

This issue was discovered by the @chemamartinez  team, and it is basically from the windows hotfix parser, which extracts the information by going through the windows registry.

in the DoD is the proposed fix.

```
sqlite> select * from sys_hotfixes;
0|2021/02/24 11:48:48|KB2534111.MSU\8847D77D|3c5b9261d91b60b7e27daa90a1afec9e6b727cf8
0|2021/02/24 11:48:48|KB976902\KB976932\SUPPORT\SSU\SAND\5A42A8EB|d63f10ff77489c780fe46ccb48a5d7d8e2e324bf
0|2021/02/24 11:48:48|KB976932\SAND\87C8A3D4|df00f66825258c45b161a48d086a9de27f4c0d31
```
imagen

Actual result: Incorrect KB Number.
Expected result: Correct KB number without exclusion.
Related PR: https://github.com/wazuh/wazuh/pull/6706
This issue is only reproducible in windows 7.

Destination branch: dev-syscollector-tde

## **DoD**
- [X] Add regex to get KB number
- [X] Add unit test
- [X] Manual Tests
image
image

- [x] PR - CI Pass

### CODE REVIEW

**Review by Dwordcito — APPROVED** [review]

File: src/data_provider/src/packages/packagesWindowsParserHelper.h [hunk 1]
```diff
@@ -0,0 +1,105 @@
...
+            std::set<std::string> hotfixes;
+            Utils::Registry root{key, subKey, KEY_WOW64_64KEY | KEY_ENUMERATE_SUB_KEYS | KEY_READ};
+            const auto packages{root.enumerate()};
+            for (const auto& package : packages)
+            {
+                auto value{Utils::toUpperCase(package)};
+                if (Utils::startsWith(value, KB_PREFIX))
+                {
+                    value = value.substr(KB_PREFIX_SIZE);
+                    value = Utils::trim(value.substr(0, value.find_first_not_of("1234567890")));
```
Comment (konangc87) [inline src/data_provider/src/packages/packagesWindowsParserHelper.h:90]: should we use the same extractHFValue function here?

**Review by konangc87 — CHANGES_REQUESTED** [review]

File: src/data_provider/src/packages/packagesWindowsParserHelper.h (hunk 1 above)
Comment (tinachoB) [reply src/data_provider/src/packages/packagesWindowsParserHelper.h:90]: You're correct. Adding this in my next commit

**Review by konangc87 — APPROVED** [review]
