### PR TITLE
Resolve manager address by Agentd after creating the PIDfile

### LINKED ISSUE #12703: Agentd causes service startup timeout when it fails to resolve the manager hostname
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| ≤ 4.0 | Agentd | Agent | Packages | Ubuntu |

If we set a wrong manager address, like:
```xml
<ossec_config>
  <client>
    <server>
      <address>unknown</address>
    </server>
  </client>
</ossec_config>
```

The service fails to startup:

```sh
# wazuh-control start
Starting Wazuh v4.4.0...
Started wazuh-execd...
wazuh-agentd did not start
```

Indeed, Agentd is running, but there is no PID-file:

```sh
# pgrep wazuh-agentd
8017

# ls /var/ossec/var/run/wazuh-agentd*
ls: cannot access '/var/ossec/var/run/wazuh-agentd*': No such file or directory
```

Agentd is taking 38 seconds to start:

```
2022/03/14 10:32:05 wazuh-agentd[8017] agentd.c:57 at AgentdStart(): INFO: (1410): Reading authentication keys file.

2022/03/14 10:32:43 wazuh-agentd[8017] agentd.c:72 at AgentdStart(): INFO: Using notify time: 10 and max time to reconnect: 60
2022/03/14 10:32:43 wazuh-agentd[8017] agentd.c:80 at AgentdStart(): INFO: Version detected -> Linux |bfe8fd630f6d |5.10.16.3-microsoft-standard-WSL2 |#1 SMP Fri Apr 2 22:23:49 UTC 2021 |x86_64 [Ubuntu|ubuntu: 20.04.4 LTS (Focal Fossa)] - Wazuh v4.4.0
2022/03/14 10:32:43 wazuh-agentd[8017] agentd.c:108 at AgentdStart(): INFO: Started (pid: 8017).
```

## Cause

Agentd is getting stuck at `resolve_hostname()`,  which runs before creating Agentd's PID and state files.

## Fix

Delay the manager hostname resolution until Agentd has created its files and its server socket.

### PR DESCRIPTION
**Pull request by vikman90**
|Related issue|
|---|
|Closes #12703|

This change delays the manager hostname resolution until Agentd performs these tasks at less:
- Create the PID-file: _var/run/wazuh-agent-*.pid_.
- Create the state file: _var/run/wazuh-agentd.state_.
- Create the agent's queue: _queue/sockets/queue_.

In addition, we've changed UNIX and Windows agent to log the result of the hostname resolution, as we will see in the logs.

### Linux

- Valid hostname:
```
2022/03/14 17:50:36 wazuh-agentd: INFO: (1410): Reading authentication keys file.
2022/03/14 17:50:36 wazuh-agentd: INFO: Started (pid: 59114).
2022/03/14 17:50:36 wazuh-agentd: INFO: Server hostname resolved: groovy/192.168.33.22
```
- Unknown hostname:
```
2022/03/14 17:50:23 wazuh-agentd: INFO: (1410): Reading authentication keys file.
2022/03/14 17:50:23 wazuh-agentd: INFO: Started (pid: 59104).

2022/03/14 17:50:29 wazuh-agentd: WARNING: Could not resolve server hostname: unknown
```
- IP address:
```
2022/03/14 17:56:21 wazuh-agentd: INFO: (1410): Reading authentication keys file.
2022/03/14 17:56:21 wazuh-agentd: INFO: Started (pid: 62642).
2022/03/14 17:56:21 wazuh-agentd: INFO: Server IP Address: 172.26.150.45
```

### Windows
- Valid hostname:
```
2022/03/14 17:58:55 wazuh-agent: INFO: (1410): Reading authentication keys file.
2022/03/14 17:58:55 wazuh-agent: INFO: Started (pid: 2112).
2022/03/14 17:58:55 wazuh-agent: INFO: Server hostname resolved: groovy/192.168.33.22
```
- Unknown hostname:
```
2022/03/14 17:44:33 wazuh-agent: INFO: (1410): Reading authentication keys file.
2022/03/14 17:44:33 wazuh-agent: INFO: Started (pid: 23284).

2022/03/14 17:44:53 wazuh-agent: WARNING: Could not resolve server hostname: unknown
```
- IP address:
```
2022/03/14 17:58:36 wazuh-agent: INFO: (1410): Reading authentication keys file.
2022/03/14 17:58:36 wazuh-agent: INFO: Started (pid: 20164).
2022/03/14 17:58:36 wazuh-agent: INFO: Server IP Address: 172.26.150.45
```

## Tests

- [x] Agentd creates the state files immediately on start, even with an unknown server hostname.
- [x] Valgrind
- [x] Cppcheck
- [x] Coverity

### CODE REVIEW

File: src/client-agent/agentd.c [hunk 1]
```diff
@@ -154,6 +134,26 @@ void AgentdStart(int uid, int gid, const char *user, const char *group)
...
+            resolve_hostname(&agt->server[rc].rip, 5);
+            int rip_l = strlen(agt->server[rc].rip);
+            mdebug2("Server hostname resolved: %.*s", agt->server[rc].rip[rip_l - 1] == '/' ? rip_l - 1 : rip_l, agt->server[rc].rip);
+        }
+        rc++;
+    }
+
+    /* Connect remote */
+    rc = 0;
+    while (rc < agt->server_count) {
```
Comment (palaciosjeremias) [inline src/client-agent/agentd.c:151]: This loop only has the functionality of logging the list of addresses "**Server IP Address:**". I think it will be more clear if we just print it together with the debug message "**Server hostname resolved:**" above.
We can also merge these two messages. into one

**Review by palaciosjeremias — APPROVED** [review]
LGTM

File: src/win32/win_utils.c [hunk 2]
```diff
@@ -113,17 +113,6 @@ int local_start()
                w_seconds_to_time_value(agt->force_reconnect_interval), w_seconds_to_time_unit(agt->force_reconnect_interval, TRUE));
     }
 
-    // Resolve hostnames
-    rc = 0;
```
Comment (palaciosjeremias) [inline src/win32/win_utils.c:117]: Ww should remove **rc** declaration as it isn´t used anymore.

File: src/client-agent/start_agent.c [hunk 3]
```diff
@@ -132,6 +132,7 @@ bool connect_server(int server_id, bool verbose)
 /* Send synchronization message to the server and wait for the ack */
 void start_agent(int is_startup)
 {
+    agent_setup_hostnames();
```
Comment (palaciosjeremias) [inline src/client-agent/start_agent.c:135]: I think we should move this into the is_startup condition to only try to solve the hostnames once.

File: src/client-agent/start_agent.c [hunk 4]
```diff
@@ -402,3 +403,24 @@ void send_agent_stopped_message() {
...
+ */
+void agent_setup_hostnames() {
+    for (int rc = 0; rc < agt->server_count; rc++) {
+        if (OS_IsValidIP(agt->server[rc].rip, NULL) != 1) {
+            mdebug2("Resolving server hostname: %s", agt->server[rc].rip);
+            resolve_hostname(&agt->server[rc].rip, 5);
+            int rip_l = strlen(agt->server[rc].rip);
+
+            if (agt->server[rc].rip[rip_l - 1] == '/') {
+                mwarn("Could not resolve server hostname: %.*s", rip_l - 1, agt->server[rc].rip);
```
[the remark this answers is not in the document]
Comment (vikman90) [reply src/client-agent/start_agent.c:418]: @palaciosjeremias thank you for all your comments.

In this case, as privately told, I prefer the user to get a warning because the most common cause of this log is a typo in the manager address. These alternatives seem weird to me:

```
INFO: Could not resolve server hostname: unknown
INFO: Server hostname resolved: unknown/
```

**Review by palaciosjeremias — APPROVED** [review]

**Comment by vikman90** [comment]
## Coverity scan

```
478 C/C++ compilation units (100%) are ready for analysis
The cov-build utility completed successfully.
Version: v4.3.0-r40306
Branch: 12703-fix-agentd-timeout (d29df1115eb06998c2595fd75a8fc8c265ef9a3a)
Project: wazuh%2Fossec-wazuh (3sQ--QTA0tHNvZNG5FH3IQ)
Target: server
```

### Result

```
    Build ID: 443613

    Analysis Summary:
       New defects found: 1
       Defects eliminated: 2
```

### New defects

- **CID 240133:**  Insecure data handling  (TAINTED_SCALAR)
  - Unrelated to this code.
