### PR TITLE
Fix Rootcheck scan trying to read deleted files

### LINKED ISSUE #8309: Error when opening Rootcheck files on Windows
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.0 | Rootcheck | Agent | All | Windows Server 2019 |

### Description

This is a bug reported by the @wazuh/qa team in the unstable version 4.2.

Sometimes, when the Windows agent is installed and started for the first time, its first Rootcheck scan is not able to find the benchmarks located at `$INSTALLDIR\ossec-agent\shared`, showing the following errors:

image

The steps to reproduce it are:

- Install Wazuh 4.2.0 in a Windows Server 2019
- Connect it to a manager
- Wait until the first Rootcheck scan

### PR DESCRIPTION
**Pull request by mateocervilla**
|Related issue|
|---|
|Closes #8309|

## Description

This PR aims to fix a Rootcheck scan issue that occurs because before unmerging the merged.mg file, the files in the shared folder are removed and during that time, Rootcheck might try to read them.

### Previous behavior

The client-agent receiver deletes all files in the shared folder, then unmerges the merged.mg and creates the new files.

### Proposed behavior

The client-agent receiver unmerges the merged.mg and creates the new files with temp names, then renames these files with their original names and add them to the exclude list. After this, all files in the shared folder that are not in the exclude list are deleted.

## Tests

- Compilation without warnings in every supported platform
  - [x] Linux
  - [x] Windows
- [x] Source installation
- [x] Source upgrade
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [x] Scan-build report
  - [ ] Coverity
  - [x] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [x] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory

- [ ] Added unit tests (for new features)
- [x] Stress test for affected components

- Create files in the manager that are not on the agent and vice versa.
- Create heavy files in the manager that are not on the agent and vice versa.
- Delete and create files in the manager and check that the same remain in the agent.
- Set a sleep() function on the code before the files are renamed to check the temp files are created and renamed correctly.

### CODE REVIEW

File: src/client-agent/receiver.c [hunk 1]
```diff
@@ -300,6 +301,11 @@ int receive_msg()
                                         }
                                     }
                                 }
+                                int j = 0;
+                                while (*(IGNORE_LIST + j)) {
+                                    free(*(IGNORE_LIST + j++));
+                                }
```
Comment (MarcelKemp) [inline src/client-agent/receiver.c:307]: To improve these lines of code, let's use the `w_FreeArray` macro with the `IGNORE_LIST` array:
- `w_FreeArray(IGNORE_LIST);`

**Review by MarcelKemp — CHANGES_REQUESTED** [review]

**Review by MarcelKemp — DISMISSED** [review]

**Review by MarcelKemp — APPROVED** [review]

**Review by jmv74211 — APPROVED** [review]
## QA review

- **Type**: Manual testing.
- **Status**: Approved  🟢 
- **Testing issue**: https://github.com/wazuh/wazuh-qa/issues/3694
- **Comments**:  https://github.com/wazuh/wazuh-qa/issues/3694#issuecomment-1419407718

**Review by MarcelKemp — APPROVED** [review]

**Review by MarcelKemp — APPROVED** [review]

**Review by vikman90 — DISMISSED** [review]

**Review by MarcelKemp — APPROVED** [review]
