### PR TITLE
Adapt wazuh-maild to RFC5322 standard (fixed mutiple email)

### LINKED ISSUE #30676: Bug Report: Multiple <email_to> Tags Not Working in Wazuh.
## Bug Report: Multiple `<email_to>` Tags Not Working in Wazuh 4.12.0

| Wazuh version | Component     | Module |
|---------------|---------------|--------|
| 4.12.0        | Wazuh Manager | wazuh-maild |

---

### 📝 Issue

Email alerts are not being sent to multiple recipients when configuring more than one `<email_to>` tag in the Wazuh `ossec.conf` file.

---

### 🔁 Steps to Reproduce

1. Followed this Wazuh documentation for configuring Postfix with Gmail:  
   https://documentation.wazuh.com/current/user-manual/manager/alert-management.html#smtp-server-with-authentication

2. After completing all the steps, alerts are successfully forwarded via email **only when one recipient is configured**. Configuration looks like this:

```xml
<global>
  <jsonout_output>yes</jsonout_output>
  <alerts_log>yes</alerts_log>
  <logall>no</logall>
  <logall_json>yes</logall_json>
  <email_notification>yes</email_notification>
  <smtp_server>localhost</smtp_server>
  <email_from>sender@gmail.com</email_from>
  <email_to>receiver1@gmail.com</email_to>
  <email_maxperhour>12</email_maxperhour>
  <email_log_source>alerts.log</email_log_source>
  <agents_disconnection_time>15s</agents_disconnection_time>
  <agents_disconnection_alert_time>0</agents_disconnection_alert_time>
  <update_check>yes</update_check>
  <max_output_size>1M</max_output_size>
</global>

<alerts>
  <log_alert_level>3</log_alert_level>
  <email_alert_level>7</email_alert_level>
</alerts>
```

3. This works as expected and sends alerts with rule level 7 and above to `receiver1@gmail.com`.

4. However, to send alerts to multiple recipients, the following configuration was used:

```xml
<email_alerts>
  <email_to>recipient1@gmail.com</email_to>
  <email_to>recipient2@gmail.com</email_to>
  <level>12</level>
  <group>sshd,</group>
  <do_not_delay/>
</email_alerts>
```

> Referenced documentation:  
> https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/email-alerts.html#example-of-configuration

5. Expected behavior: emails should be sent to both `recipient1@gmail.com` and `recipient2@gmail.com` when an alert with rule level 12 in the `sshd` group is triggered.

6. Actual behavior: the alert is **not delivered to both recipients**. Instead, the sender (`sender@gmail.com`) receives an "Undelivered Mail Returned to Sender" bounce email.

7. Screenshot samples from bounce message:

Undelivered Mail Screenshot 1  
Undelivered Mail Screenshot 2

---

### ✅ Expected Behavior

In previous versions of Wazuh (likely 4.4 or 4.6 not sure about the version), configuring multiple `<email_to>` tags worked properly, and alerts were successfully delivered to all specified recipients.

---

### 📎 Related Issues

- https://github.com/wazuh/community/issues/52403  
- https://github.com/wazuh/wazuh/issues/25732  
- https://github.com/wazuh/wazuh/issues/14824  

---

Let us know if additional logs or configuration samples are required.

### PR DESCRIPTION
**Pull request by NahuFigueroa97**
## Description

This PR introduces an improvement to the maild daemon by complying with the RFC5322 standard, which prevents duplicate headers. This prevented emails from being sent to more than one recipient, as they bounced back to the sender, reporting the standard error https://support.google.com/a/answer/13567860?hl=en.
Closes #30676

## Proposed Changes

- Features added: An enhancement was added to comply with RFC 5322
- Bugs fixed: Repeated headers were being sent, which Google interprets as spam.
- Any relevant technical details: The change was introduced for emails with FULL, DEFAULT and SMS formats.

### Results and Evidence

<details>
  <summary>Ossec.conf for full event</summary>

  ```xml
  <global>
    <jsonout_output>yes</jsonout_output>
    <alerts_log>yes</alerts_log>
    <logall>no</logall>
    <logall_json>no</logall_json>
    <email_notification>yes</email_notification>
    <smtp_server>localhost</smtp_server>
    <email_from>sender@gmail.com</email_from>
    <email_to>secret@hotmail.com</email_to>
    <email_maxperhour>120</email_maxperhour>
    <email_log_source>alerts.log</email_log_source>
    <agents_disconnection_time>10m</agents_disconnection_time>
    <agents_disconnection_alert_time>0</agents_disconnection_alert_time>
  </global>

  <alerts>
    <log_alert_level>3</log_alert_level>
    <email_alert_level>7</email_alert_level>
  </alerts>

  <email_alerts>
    <email_to>coxole7585@bulmp3.com</email_to>
    <email_to>filtikelti@gufum.com</email_to>
    <level>7</level>
    <do_not_delay/>
  </email_alerts>
 ```

</details> 

<details>
  <summary>Ossec.conf for SMS</summary>

  ```xml
  <global>
    <jsonout_output>yes</jsonout_output>
    <alerts_log>yes</alerts_log>
    <logall>no</logall>
    <logall_json>no</logall_json>
    <email_notification>yes</email_notification>
    <smtp_server>localhost</smtp_server>
    <email_from>sender@gmail.com</email_from>
    <email_to>secret@hotmail.com</email_to>
    <email_maxperhour>120</email_maxperhour>
    <email_log_source>alerts.log</email_log_source>
    <agents_disconnection_time>10m</agents_disconnection_time>
    <agents_disconnection_alert_time>0</agents_disconnection_alert_time>
  </global>

  <alerts>
    <log_alert_level>3</log_alert_level>
    <email_alert_level>7</email_alert_level>
  </alerts>

  <email_alerts>
    <email_to>coxole7585@bulmp3.com</email_to>
    <email_to>filtikelti@gufum.com</email_to>
    <format>sms</format>
    <level>7</level>
    <do_not_delay/>
  </email_alerts>
 ```

</details> 

### Manual tests with their corresponding evidence

After installation, the proc was set up to perform the analysis with ASAN. Tests were performed using the wazuh-maild daemon, manually running alerts in the alerts.log file, and then running all the dameons and receiving alerts compiled by the manager.

<details>
  <summary>ASAN in maild for 4.14.0</summary>

  ```
=================================================================
==50468==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 148 byte(s) in 2 object(s) allocated from:
    #0 0x7ffff76279a7  (/lib/x86_64-linux-gnu/libasan.so.6+0x5b9a7)
    #1 0x5555555febad in Read_Global config/global-config.c:210
    #2 0x5555555f1a1b in read_main_elements config/config.c:85
    #3 0x5555555f415f in ReadConfig config/config.c:372
    #4 0x5555555e1781 in MailConf os_maild/config.c:54
    #5 0x5555555e48c7 in main os_maild/maild.c:129
    #6 0x7ffff6865d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)

Direct leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x7ffff7680c38  (/lib/x86_64-linux-gnu/libasan.so.6+0xb4c38)
    #1 0x555555602b67 in Read_Global config/global-config.c:498
    #2 0x5555555f1a1b in read_main_elements config/config.c:85
    #3 0x5555555f415f in ReadConfig config/config.c:372
    #4 0x5555555e1781 in MailConf os_maild/config.c:54
    #5 0x5555555e48c7 in main os_maild/maild.c:129
    #6 0x7ffff6865d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)

Direct leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7ffff7680c38  (/lib/x86_64-linux-gnu/libasan.so.6+0xb4c38)
    #1 0x555555603000 in Read_Global config/global-config.c:518
    #2 0x5555555f1a1b in read_main_elements config/config.c:85
    #3 0x5555555f415f in ReadConfig config/config.c:372
    #4 0x5555555e1781 in MailConf os_maild/config.c:54
    #5 0x5555555e48c7 in main os_maild/maild.c:129
    #6 0x7ffff6865d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)

Indirect leak of 94 byte(s) in 2 object(s) allocated from:
    #0 0x7ffff7680a57  (/lib/x86_64-linux-gnu/libasan.so.6+0xb4a57)
    #1 0x5555557356e5 in OS_IsValidIP shared/validate_op.c:412
    #2 0x555555602ef5 in Read_Global config/global-config.c:507
    #3 0x5555555f1a1b in read_main_elements config/config.c:85
    #4 0x5555555f415f in ReadConfig config/config.c:372
    #5 0x5555555e1781 in MailConf os_maild/config.c:54
    #6 0x5555555e48c7 in main os_maild/maild.c:129
    #7 0x7ffff6865d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)

Indirect leak of 48 byte(s) in 2 object(s) allocated from:
    #0 0x7ffff7680a57  (/lib/x86_64-linux-gnu/libasan.so.6+0xb4a57)
    #1 0x555555602cdb in Read_Global config/global-config.c:504
    #2 0x5555555f1a1b in read_main_elements config/config.c:85
    #3 0x5555555f415f in ReadConfig config/config.c:372
    #4 0x5555555e1781 in MailConf os_maild/config.c:54
    #5 0x5555555e48c7 in main os_maild/maild.c:129
    #6 0x7ffff6865d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)

Indirect leak of 48 byte(s) in 1 object(s) allocated from:
    #0 0x7ffff7680a57  (/lib/x86_64-linux-gnu/libasan.so.6+0xb4a57)
    #1 0x555555603174 in Read_Global config/global-config.c:525
    #2 0x5555555f1a1b in read_main_elements config/config.c:85
    #3 0x5555555f415f in ReadConfig config/config.c:372
    #4 0x5555555e1781 in MailConf os_maild/config.c:54
    #5 0x5555555e48c7 in main os_maild/maild.c:129
    #6 0x7ffff6865d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)

Indirect leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x7ffff76279a7  (/lib/x86_64-linux-gnu/libasan.so.6+0x5b9a7)
    #1 0x55555574bfb2 in OSMatch_Compile os_regex/os_match_compile.c:55
    #2 0x555555603393 in Read_Global config/global-config.c:530
    #3 0x5555555f1a1b in read_main_elements config/config.c:85
    #4 0x5555555f415f in ReadConfig config/config.c:372
    #5 0x5555555e1781 in MailConf os_maild/config.c:54
    #6 0x5555555e48c7 in main os_maild/maild.c:129
    #7 0x7ffff6865d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)

Indirect leak of 23 byte(s) in 1 object(s) allocated from:
    #0 0x7ffff76279a7  (/lib/x86_64-linux-gnu/libasan.so.6+0x5b9a7)
    #1 0x55555574c634 in OSMatch_Compile os_regex/os_match_compile.c:131
    #2 0x555555603393 in Read_Global config/global-config.c:530
    #3 0x5555555f1a1b in read_main_elements config/config.c:85
    #4 0x5555555f415f in ReadConfig config/config.c:372
    #5 0x5555555e1781 in MailConf os_maild/config.c:54
    #6 0x5555555e48c7 in main os_maild/maild.c:129
    #7 0x7ffff6865d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)

Indirect leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7ffff7680a57  (/lib/x86_64-linux-gnu/libasan.so.6+0xb4a57)
    #1 0x55555574c26c in OSMatch_Compile os_regex/os_match_compile.c:99
    #2 0x555555603393 in Read_Global config/global-config.c:530
    #3 0x5555555f1a1b in read_main_elements config/config.c:85
    #4 0x5555555f415f in ReadConfig config/config.c:372
    #5 0x5555555e1781 in MailConf os_maild/config.c:54
    #6 0x5555555e48c7 in main os_maild/maild.c:129
    #7 0x7ffff6865d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)

Indirect leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7ffff7680a57  (/lib/x86_64-linux-gnu/libasan.so.6+0xb4a57)
    #1 0x55555574c2f6 in OSMatch_Compile os_regex/os_match_compile.c:101
    #2 0x555555603393 in Read_Global config/global-config.c:530
    #3 0x5555555f1a1b in read_main_elements config/config.c:85
    #4 0x5555555f415f in ReadConfig config/config.c:372
    #5 0x5555555e1781 in MailConf os_maild/config.c:54
    #6 0x5555555e48c7 in main os_maild/maild.c:129
    #7 0x7ffff6865d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)

Indirect leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7ffff7680a57  (/lib/x86_64-linux-gnu/libasan.so.6+0xb4a57)
    #1 0x55555574c2b1 in OSMatch_Compile os_regex/os_match_compile.c:100
    #2 0x555555603393 in Read_Global config/global-config.c:530
    #3 0x5555555f1a1b in read_main_elements config/config.c:85
    #4 0x5555555f415f in ReadConfig config/config.c:372
    #5 0x5555555e1781 in MailConf os_maild/config.c:54
    #6 0x5555555e48c7 in main os_maild/maild.c:129
    #7 0x7ffff6865d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)

Indirect leak of 16 byte(s) in 2 object(s) allocated from:
    #0 0x7ffff7680a57  (/lib/x86_64-linux-gnu/libasan.so.6+0xb4a57)
    #1 0x555555736109 in OS_IsValidIP shared/validate_op.c:490
    #2 0x555555602ef5 in Read_Global config/global-config.c:507
    #3 0x5555555f1a1b in read_main_elements config/config.c:85
    #4 0x5555555f415f in ReadConfig config/config.c:372
    #5 0x5555555e1781 in MailConf os_maild/config.c:54
    #6 0x5555555e48c7 in main os_maild/maild.c:129
    #7 0x7ffff6865d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)

SUMMARY: AddressSanitizer: 489 byte(s) leaked in 16 allocation(s).
 ```

</details> 

<details>
  <summary>ASAN in maild for enhancemnet branch</summary>

  ```
=================================================================
==48199==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 148 byte(s) in 2 object(s) allocated from:
    #0 0x7ffff76279a7  (/lib/x86_64-linux-gnu/libasan.so.6+0x5b9a7)
    #1 0x5555555fefb2 in Read_Global config/global-config.c:210
    #2 0x5555555f1e20 in read_main_elements config/config.c:85
    #3 0x5555555f4564 in ReadConfig config/config.c:372
    #4 0x5555555e1781 in MailConf os_maild/config.c:54
    #5 0x5555555e48c7 in main os_maild/maild.c:129
    #6 0x7ffff6865d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)

Direct leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x7ffff7680c38  (/lib/x86_64-linux-gnu/libasan.so.6+0xb4c38)
    #1 0x555555602f6c in Read_Global config/global-config.c:498
    #2 0x5555555f1e20 in read_main_elements config/config.c:85
    #3 0x5555555f4564 in ReadConfig config/config.c:372
    #4 0x5555555e1781 in MailConf os_maild/config.c:54
    #5 0x5555555e48c7 in main os_maild/maild.c:129
    #6 0x7ffff6865d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)

Direct leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7ffff7680c38  (/lib/x86_64-linux-gnu/libasan.so.6+0xb4c38)
    #1 0x555555603405 in Read_Global config/global-config.c:518
    #2 0x5555555f1e20 in read_main_elements config/config.c:85
    #3 0x5555555f4564 in ReadConfig config/config.c:372
    #4 0x5555555e1781 in MailConf os_maild/config.c:54
    #5 0x5555555e48c7 in main os_maild/maild.c:129
    #6 0x7ffff6865d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)

Indirect leak of 94 byte(s) in 2 object(s) allocated from:
    #0 0x7ffff7680a57  (/lib/x86_64-linux-gnu/libasan.so.6+0xb4a57)
    #1 0x555555735aea in OS_IsValidIP shared/validate_op.c:412
    #2 0x5555556032fa in Read_Global config/global-config.c:507
    #3 0x5555555f1e20 in read_main_elements config/config.c:85
    #4 0x5555555f4564 in ReadConfig config/config.c:372
    #5 0x5555555e1781 in MailConf os_maild/config.c:54
    #6 0x5555555e48c7 in main os_maild/maild.c:129
    #7 0x7ffff6865d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)

Indirect leak of 48 byte(s) in 2 object(s) allocated from:
    #0 0x7ffff7680a57  (/lib/x86_64-linux-gnu/libasan.so.6+0xb4a57)
    #1 0x5555556030e0 in Read_Global config/global-config.c:504
    #2 0x5555555f1e20 in read_main_elements config/config.c:85
    #3 0x5555555f4564 in ReadConfig config/config.c:372
    #4 0x5555555e1781 in MailConf os_maild/config.c:54
    #5 0x5555555e48c7 in main os_maild/maild.c:129
    #6 0x7ffff6865d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)

Indirect leak of 48 byte(s) in 1 object(s) allocated from:
    #0 0x7ffff7680a57  (/lib/x86_64-linux-gnu/libasan.so.6+0xb4a57)
    #1 0x555555603579 in Read_Global config/global-config.c:525
    #2 0x5555555f1e20 in read_main_elements config/config.c:85
    #3 0x5555555f4564 in ReadConfig config/config.c:372
    #4 0x5555555e1781 in MailConf os_maild/config.c:54
    #5 0x5555555e48c7 in main os_maild/maild.c:129
    #6 0x7ffff6865d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)

Indirect leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x7ffff76279a7  (/lib/x86_64-linux-gnu/libasan.so.6+0x5b9a7)
    #1 0x55555574c3b7 in OSMatch_Compile os_regex/os_match_compile.c:55
    #2 0x555555603798 in Read_Global config/global-config.c:530
    #3 0x5555555f1e20 in read_main_elements config/config.c:85
    #4 0x5555555f4564 in ReadConfig config/config.c:372
    #5 0x5555555e1781 in MailConf os_maild/config.c:54
    #6 0x5555555e48c7 in main os_maild/maild.c:129
    #7 0x7ffff6865d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)

Indirect leak of 23 byte(s) in 1 object(s) allocated from:
    #0 0x7ffff76279a7  (/lib/x86_64-linux-gnu/libasan.so.6+0x5b9a7)
    #1 0x55555574ca39 in OSMatch_Compile os_regex/os_match_compile.c:131
    #2 0x555555603798 in Read_Global config/global-config.c:530
    #3 0x5555555f1e20 in read_main_elements config/config.c:85
    #4 0x5555555f4564 in ReadConfig config/config.c:372
    #5 0x5555555e1781 in MailConf os_maild/config.c:54
    #6 0x5555555e48c7 in main os_maild/maild.c:129
    #7 0x7ffff6865d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)

Indirect leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7ffff7680a57  (/lib/x86_64-linux-gnu/libasan.so.6+0xb4a57)
    #1 0x55555574c671 in OSMatch_Compile os_regex/os_match_compile.c:99
    #2 0x555555603798 in Read_Global config/global-config.c:530
    #3 0x5555555f1e20 in read_main_elements config/config.c:85
    #4 0x5555555f4564 in ReadConfig config/config.c:372
    #5 0x5555555e1781 in MailConf os_maild/config.c:54
    #6 0x5555555e48c7 in main os_maild/maild.c:129
    #7 0x7ffff6865d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)

Indirect leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7ffff7680a57  (/lib/x86_64-linux-gnu/libasan.so.6+0xb4a57)
    #1 0x55555574c6fb in OSMatch_Compile os_regex/os_match_compile.c:101
    #2 0x555555603798 in Read_Global config/global-config.c:530
    #3 0x5555555f1e20 in read_main_elements config/config.c:85
    #4 0x5555555f4564 in ReadConfig config/config.c:372
    #5 0x5555555e1781 in MailConf os_maild/config.c:54
    #6 0x5555555e48c7 in main os_maild/maild.c:129
    #7 0x7ffff6865d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)

Indirect leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7ffff7680a57  (/lib/x86_64-linux-gnu/libasan.so.6+0xb4a57)
    #1 0x55555574c6b6 in OSMatch_Compile os_regex/os_match_compile.c:100
    #2 0x555555603798 in Read_Global config/global-config.c:530
    #3 0x5555555f1e20 in read_main_elements config/config.c:85
    #4 0x5555555f4564 in ReadConfig config/config.c:372
    #5 0x5555555e1781 in MailConf os_maild/config.c:54
    #6 0x5555555e48c7 in main os_maild/maild.c:129
    #7 0x7ffff6865d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)

Indirect leak of 16 byte(s) in 2 object(s) allocated from:
    #0 0x7ffff7680a57  (/lib/x86_64-linux-gnu/libasan.so.6+0xb4a57)
    #1 0x55555573650e in OS_IsValidIP shared/validate_op.c:490
    #2 0x5555556032fa in Read_Global config/global-config.c:507
    #3 0x5555555f1e20 in read_main_elements config/config.c:85
    #4 0x5555555f4564 in ReadConfig config/config.c:372
    #5 0x5555555e1781 in MailConf os_maild/config.c:54
    #6 0x5555555e48c7 in main os_maild/maild.c:129
    #7 0x7ffff6865d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)

SUMMARY: AddressSanitizer: 489 byte(s) leaked in 16 allocation(s).
 ```

</details> 

## Review Checklist

- [ ] Code changes reviewed
- [ ] Relevant evidence provided
- [ ] Tests cover the new functionality
- [ ] Configuration changes documented
- [ ] Developer documentation reflects the changes
- [ ] Meets requirements and/or definition of done
- [ ] No unresolved dependencies with other issues
- [ ] ...

### CODE REVIEW

File: src/os_maild/sendmail.c [hunk 1]
```diff
@@ -505,49 +503,52 @@ int OS_Sendmail(MailConfig *mail, struct tm *p)
...
+        } else {
+            char hdr[1080];
+            int hl = snprintf(hdr, sizeof(hdr), TO, to_list);
+            if (hl > 0 && (size_t)hl < sizeof(hdr)) {
+            OS_SendTCP(socket, hdr);
             }
-
-            i++;
-            continue;
+        }
```
Comment (LucioDonda) [inline src/os_maild/sendmail.c]: can we keep the tabs inside each group?
like this:
```c
        if (p != to_list) {
            if (sendmail) {
                fprintf(sendmail->file_in, TO, to_list);
            } else {
                char hdr[1080];
                int hl = snprintf(hdr, sizeof(hdr), TO, to_list);
                if (hl > 0 && (size_t)hl < sizeof(hdr)) {
                    OS_SendTCP(socket, hdr);
                }
            }
```

there are several cases in the same file

**Review by LucioDonda — DISMISSED** [review]
Review Checklist

- [x] Code changes reviewed
- [x] Relevant evidence provided
- [x] Configuration changes documented
- [x] Developer documentation reflects the changes
- [x] Meets requirements and/or definition of done
- [x] No unresolved dependencies with other issues

Built, installed and UTs checked.

<details><summary>Installing</summary>
<p>

```console
Done building server

Wait for success...
success
Removing old SCA policies...
Installing SCA policies...
Installing additional SCA policies...
Makefile:2710: warning: overriding recipe for target 'win32/ui_resource.o'
Makefile:2650: warning: ignoring old recipe for target 'win32/ui_resource.o'
Makefile:2713: warning: overriding recipe for target 'win32/auth_resource.o'
Makefile:2653: warning: ignoring old recipe for target 'win32/auth_resource.o'
mkdir -p /var/ossec/framework/python
cp external/cpython.tar.gz /var/ossec/framework/python/cpython.tar.gz && tar -xf /var/ossec/framework/python/cpython.tar.gz -C /var/ossec/framework/python && rm -rf /var/ossec/framework/python/cpython.tar.gz
find /var/ossec/framework/python -name "*libpython3.10.so.1.0" -exec ln -f {} /var/ossec/lib/libpython3.10.so.1.0 \;
cd ../framework && /var/ossec/framework/python/bin/python3 -m pip install . --use-pep517 --prefix=/var/ossec/framework/python && rm -rf build/
Processing /home/pm-vagrant/workspace/wazuh/framework
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: wazuh
  Building wheel for wazuh (pyproject.toml) ... done
  Created wheel for wazuh: filename=wazuh-4.14.0-py3-none-any.whl size=317612 sha256=be0b35e11b108b9ad34651824fab32c868774f6dac5e855492abccae81806dd2
  Stored in directory: /tmp/pip-ephem-wheel-cache-ulgi5r4a/wheels/3a/40/80/254175537fb4b2938bbe74368606f5970c5cb94a450e4a2343
Successfully built wazuh
Installing collected packages: wazuh
Successfully installed wazuh-4.14.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 23.3.2 -> 25.1.1
[notice] To update, run: /var/ossec/framework/python/bin/python3 -m pip install --upgrade pip
chown -R root:wazuh /var/ossec/framework/python
chmod -R o=- /var/ossec/framework/python
cd ../api && /var/ossec/framework/python/bin/python3 -m pip install . --use-pep517 --prefix=/var/ossec/framework/python && rm -rf build/
Processing /home/pm-vagrant/workspace/wazuh/api
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: api
  Building wheel for api (pyproject.toml) ... done
  Created wheel for api: filename=api-4.14.0-py3-none-any.whl size=164080 sha256=b4f3e2c642f6ce1d500394320edf529d91fa824f9628e9713e143355fa9a8ab0
  Stored in directory: /tmp/pip-ephem-wheel-cache-pcqbb5qe/wheels/e6/ef/5a/f7c6dde57fd068d903edd6e868c35e1db02842e04d4c9631a4
Successfully built api
Installing collected packages: api
Successfully installed api-4.14.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 23.3.2 -> 25.1.1
[notice] To update, run: /var/ossec/framework/python/bin/python3 -m pip install --upgrade pip
cd ../tools/mitre && /var/ossec/framework/python/bin/python3 mitredb.py -d /var/ossec/var/db/mitre.db
Generating self-signed certificate for wazuh-authd...


Created symlink /etc/systemd/system/multi-user.target.wants/wazuh-manager.service → /etc/systemd/system/wazuh-manager.service.
Starting Wazuh...
server

 - Configuration finished properly.

 - To start Wazuh:
      /var/ossec/bin/wazuh-control start

 - To stop Wazuh:
      /var/ossec/bin/wazuh-control stop

 - The configuration can be viewed or modified at /var/ossec/etc/ossec.conf


   Thanks for using Wazuh.
   Please don't hesitate to contact us if you need help or find
   any bugs.

   Use our public Mailing List at:
          https://groups.google.com/forum/#!forum/wazuh

   More information can be found at:
          - http://www.wazuh.com

    ---  Press ENTER to finish (maybe more information below). ---


 - In order to connect agent and server, you need to add each agent to the server.

   More information at: 
   https://documentation.wazuh.com/

root@pm-ubuntu24-server:/home/pm-vagrant/workspace/wazuh# /var/ossec/bin/wazuh-control status
wazuh-clusterd not running...
wazuh-modulesd is running...
wazuh-monitord is running...
wazuh-logcollector is running...
wazuh-remoted is running...
wazuh-syscheckd is running...
wazuh-analysisd is running...
wazuh-maild not running...
wazuh-execd is running...
wazuh-db is running...
wazuh-authd is running...
wazuh-agentlessd not running...
wazuh-integratord not running...
wazuh-dbd not running...
wazuh-csyslogd not running...
wazuh-apid is running...
root@pm-ubuntu24-server:/home/pm-vag
```

</p>
</details> 

<details><summary>Building</summary>
<p>

```console

General settings:
    TARGET:             server
    V:                  
    DEBUG:              1
    DEBUGAD             
    INSTALLDIR:         
    DATABASE:           
    ONEWAY:             no
    CLEANFULL:          no
    RESOURCES_URL:      https://packages.wazuh.com/deps/46
    EXTERNAL_SRC_ONLY:  
    HTTP_REQUEST_BRANCH:75384783d339a817b8d8f13f778051a878d642a6
User settings:
    WAZUH_GROUP:        wazuh
    WAZUH_USER:         wazuh
USE settings:
    USE_ZEROMQ:         no
    USE_GEOIP:          no
    USE_PRELUDE:        no
    USE_INOTIFY:        no
    USE_BIG_ENDIAN:     no
    USE_SELINUX:        no
    USE_AUDIT:          yes
    DISABLE_SYSC:       no
    DISABLE_CISCAT:     no
    IMAGE_TRUST_CHECKS: 1
    CA_NAME:            DigiCert Assured ID Root CA
Mysql settings:
    includes:           
    libs:               
Pgsql settings:
    includes:           
    libs:               
Defines:
    -DOSSECHIDS -DUSER="wazuh" -DGROUPGLOBAL="wazuh" -DLinux -DINOTIFY_ENABLED -D_XOPEN_SOURCE=600 -D_GNU_SOURCE -DIMAGE_TRUST_CHECKS=1 -DCA_NAME='DigiCert Assured ID Root CA' -DENABLE_SYSC -DENABLE_CISCAT -DENABLE_AUDIT
Compiler:
    CFLAGS            -pthread -Iexternal/pacman/lib/libalpm/ -Iexternal/libarchive/libarchive -Wl,--start-group -Iexternal/audit-userspace/lib -g  -DOSSECHIDS -DUSER="wazuh" -DGROUPGLOBAL="wazuh" -DLinux -DINOTIFY_ENABLED -D_XOPEN_SOURCE=600 -D_GNU_SOURCE -DIMAGE_TRUST_CHECKS=1 -DCA_NAME='DigiCert Assured ID Root CA' -DENABLE_SYSC -DENABLE_CISCAT -DENABLE_AUDIT -pipe -Wall -Wextra -std=gnu99 -I./ -I./headers/ -Iexternal/openssl/include -Iexternal/cJSON/ -Iexternal/libyaml/include -Iexternal/curl/include -Iexternal/msgpack/include -Iexternal/bzip2/ -Ishared_modules/common -Ishared_modules/dbsync/include -Ishared_modules/rsync/include -Iwazuh_modules/syscollector/include  -Idata_provider/include  -Iexternal/libpcre2/include -Iexternal/rpm//builddir/output/include -Isyscheckd/include -Ishared_modules/router/include -Ishared_modules/content_manager/include -Iwazuh_modules/vulnerability_scanner/include -Iwazuh_modules/inventory_harvester/include -I./shared_modules/ -include stdint.h -g -O0 --coverage -DWAZUH_UNIT_TESTING -fsanitize=address -fsanitize=undefined
    LDFLAGS           '-Wl,-rpath,/../lib' -pthread -lrt -ldl  -Lshared_modules/dbsync/build/lib -Lshared_modules/rsync/build/lib  -Lwazuh_modules/syscollector/build/lib -Ldata_provider/build/lib -Lsyscheckd/build/lib -g -O0 --coverage -DWAZUH_UNIT_TESTING -fsanitize=address -fsanitize=undefined
    LIBS              -lrt -ldl -lm  -lcmocka
    CC                gcc
    MAKE              make
make[1]: Leaving directory '/home/pm-vagrant/workspace/wazuh/src'

Done building server

```

</p>
</details> 

<details><summary>Unit Tests</summary>
<p>

```console
# ctest 
Test project /home/pm-vagrant/workspace/wazuh/src/unit_tests/build
        Start   1: test_analysisd_syscheck
  1/180 Test   #1: test_analysisd_syscheck .................................   Passed    0.05 sec
        Start   2: test_cleanevent
  2/180 Test   #2: test_cleanevent .........................................   Passed    0.03 sec
        Start   3: test_dbsync
  3/180 Test   #3: test_dbsync .............................................   Passed    0.03 sec
        Start   4: test_exec
  4/180 Test   #4: test_exec ...............................................   Passed    0.03 sec
        Start   5: test_log
  5/180 Test   #5: test_log ................................................   Passed    0.03 sec
        Start   6: test_labels
  6/180 Test   #6: test_labels .............................................   Passed    0.02 sec
        Start   7: test_mitre
  7/180 Test   #7: test_mitre ..............................................   Passed    0.01 sec
        Start   8: test_rules
  8/180 Test   #8: test_rules ..............................................   Passed    0.02 sec
        Start   9: test_same_different_loop
  9/180 Test   #9: test_same_different_loop ................................   Passed    0.02 sec
        Start  10: test_logtest
 10/180 Test  #10: test_logtest ............................................   Passed    0.02 sec
        Start  11: test_logtest-config
 11/180 Test  #11: test_logtest-config .....................................   Passed    0.01 sec
        Start  12: test_analysisd_hotreload
 12/180 Test  #12: test_analysisd_hotreload ................................   Passed    0.02 sec
        Start  13: test_decoder_list
 13/180 Test  #13: test_decoder_list .......................................   Passed    0.01 sec
        Start  14: test_decode-xml
 14/180 Test  #14: test_decode-xml .........................................   Passed    0.02 sec
        Start  15: test_lists_list
 15/180 Test  #15: test_lists_list .........................................   Passed    0.01 sec
        Start  16: test_rule_list
 16/180 Test  #16: test_rule_list ..........................................   Passed    0.01 sec
        Start  17: test_eventinfo_list
 17/180 Test  #17: test_eventinfo_list .....................................   Passed    0.01 sec
        Start  18: test_logmsg
 18/180 Test  #18: test_logmsg .............................................   Passed    0.01 sec
        Start  19: test_decoder_rootcheck
 19/180 Test  #19: test_decoder_rootcheck ..................................   Passed    0.02 sec
        Start  20: test_decoder_syscollector
 20/180 Test  #20: test_decoder_syscollector ...............................   Passed    0.04 sec
        Start  21: test_decoder_winevtchannel
 21/180 Test  #21: test_decoder_winevtchannel ..............................   Passed    0.03 sec
        Start  22: test_decoder_winevtchannel_input
 22/180 Test  #22: test_decoder_winevtchannel_input ........................   Passed    0.03 sec
        Start  23: test_analysis-state
 23/180 Test  #23: test_analysis-state .....................................   Passed    0.03 sec
        Start  24: test_asyscom
 24/180 Test  #24: test_asyscom ............................................   Passed    0.03 sec
        Start  25: test_limits
 25/180 Test  #25: test_limits .............................................   Passed    0.01 sec
        Start  26: test_manager
 26/180 Test  #26: test_manager ............................................   Passed    0.03 sec
        Start  27: test_secure
 27/180 Test  #27: test_secure .............................................   Passed    0.03 sec
        Start  28: test_save_ctrlmsg_thread
 28/180 Test  #28: test_save_ctrlmsg_thread ................................   Passed    0.02 sec
        Start  29: test_netbuffer
 29/180 Test  #29: test_netbuffer ..........................................   Passed    0.02 sec
        Start  30: test_sendmsg
 30/180 Test  #30: test_sendmsg ............................................   Passed    0.02 sec
        Start  31: test_remote-config
 31/180 Test  #31: test_remote-config ......................................   Passed    0.01 sec
        Start  32: test_syslogtcp
 32/180 Test  #32: test_syslogtcp ..........................................   Passed    0.02 sec
        Start  33: test_remote-state
 33/180 Test  #33: test_remote-state .......................................   Passed    0.02 sec
        Start  34: test_remcom
 34/180 Test  #34: test_remcom .............................................   Passed    0.02 sec
        Start  35: test_wdb_integrity
 35/180 Test  #35: test_wdb_integrity ......................................   Passed    0.02 sec
        Start  36: test_wdb_fim
 36/180 Test  #36: test_wdb_fim ............................................   Passed    0.01 sec
        Start  37: test_wdb_parser
 37/180 Test  #37: test_wdb_parser .........................................   Passed    0.02 sec
        Start  38: test_wdb_global_parser
 38/180 Test  #38: test_wdb_global_parser ..................................   Passed    0.03 sec
        Start  39: test_wdb_global
 39/180 Test  #39: test_wdb_global .........................................   Passed    0.04 sec
        Start  40: test_wdb_agents
 40/180 Test  #40: test_wdb_agents .........................................   Passed    0.01 sec
        Start  41: test_wdb_global_helpers
 41/180 Test  #41: test_wdb_global_helpers .................................   Passed    0.02 sec
        Start  42: test_wdb_agents_helpers
 42/180 Test  #42: test_wdb_agents_helpers .................................   Passed    0.01 sec
        Start  43: test_wdb
 43/180 Test  #43: test_wdb ................................................   Passed    0.02 sec
        Start  44: test_wdb_upgrade
 44/180 Test  #44: test_wdb_upgrade ........................................   Passed    0.02 sec
        Start  45: test_wdb_metadata
 45/180 Test  #45: test_wdb_metadata .......................................   Passed    0.01 sec
        Start  46: test_wdb_task_parser
 46/180 Test  #46: test_wdb_task_parser ....................................   Passed    0.01 sec
        Start  47: test_wdb_rootcheck
 47/180 Test  #47: test_wdb_rootcheck ......................................   Passed    0.01 sec
        Start  48: test_wdb_syscollector
 48/180 Test  #48: test_wdb_syscollector ...................................   Passed    0.02 sec
        Start  49: test_wdb_task
 49/180 Test  #49: test_wdb_task ...........................................   Passed    0.01 sec
        Start  50: test_wdb_delta_event
 50/180 Test  #50: test_wdb_delta_event ....................................   Passed    0.01 sec
        Start  51: test_wazuh_db-config
 51/180 Test  #51: test_wazuh_db-config ....................................   Passed    0.02 sec
        Start  52: test_wazuh_db_state
 52/180 Test  #52: test_wazuh_db_state .....................................   Passed    0.01 sec
        Start  53: test_wdb_com
 53/180 Test  #53: test_wdb_com ............................................   Passed    0.01 sec
        Start  54: test_wdb_pool
 54/180 Test  #54: test_wdb_pool ...........................................   Passed    0.01 sec
        Start  55: test_create_agent_db
 55/180 Test  #55: test_create_agent_db ....................................   Passed    0.01 sec
        Start  56: test_auth_parse
 56/180 Test  #56: test_auth_parse .........................................   Passed    0.01 sec
        Start  57: test_auth_validate
 57/180 Test  #57: test_auth_validate ......................................   Passed    0.01 sec
        Start  58: test_auth_add
 58/180 Test  #58: test_auth_add ...........................................   Passed    0.01 sec
        Start  59: test_ssl
 59/180 Test  #59: test_ssl ................................................   Passed    0.01 sec
        Start  60: test_auth_key_request
 60/180 Test  #60: test_auth_key_request ...................................   Passed    0.02 sec
        Start  61: test_auth
 61/180 Test  #61: test_auth ...............................................   Passed    0.01 sec
        Start  62: test_generate_cert
 62/180 Test  #62: test_generate_cert ......................................   Passed    1.75 sec
        Start  63: test_authd-config
 63/180 Test  #63: test_authd-config .......................................   Passed    0.01 sec
        Start  64: test_aes_op
 64/180 Test  #64: test_aes_op .............................................   Passed    0.01 sec
        Start  65: test_hmac_op
 65/180 Test  #65: test_hmac_op ............................................   Passed    0.01 sec
        Start  66: test_msgs
 66/180 Test  #66: test_msgs ...............................................   Passed    0.01 sec
        Start  67: test_keys
 67/180 Test  #67: test_keys ...............................................   Passed    0.01 sec
        Start  68: test_sha1_op
 68/180 Test  #68: test_sha1_op ............................................   Passed    0.01 sec
        Start  69: test_blowfish_op
 69/180 Test  #69: test_blowfish_op ........................................   Passed    0.01 sec
        Start  70: test_md5_op
 70/180 Test  #70: test_md5_op .............................................   Passed    0.01 sec
        Start  71: test_md5_sha1_op
 71/180 Test  #71: test_md5_sha1_op ........................................   Passed    0.01 sec
        Start  72: test_md5_sha1_sha256_op
 72/180 Test  #72: test_md5_sha1_sha256_op .................................   Passed    0.01 sec
        Start  73: test_sha256_op
 73/180 Test  #73: test_sha256_op ..........................................   Passed    0.01 sec
        Start  74: test_sha512_op
 74/180 Test  #74: test_sha512_op ..........................................   Passed    0.01 sec
        Start  75: test_wm_aws
 75/180 Test  #75: test_wm_aws .............................................   Passed    0.02 sec
        Start  76: test_wm_azure
 76/180 Test  #76: test_wm_azure ...........................................   Passed    0.02 sec
        Start  77: test_wm_ciscat
 77/180 Test  #77: test_wm_ciscat ..........................................   Passed    0.02 sec
        Start  78: test_wm_command
 78/180 Test  #78: test_wm_command .........................................   Passed    0.03 sec
        Start  79: test_wm_database
 79/180 Test  #79: test_wm_database ........................................   Passed    0.01 sec
        Start  80: test_wm_docker
 80/180 Test  #80: test_wm_docker ..........................................   Passed    0.02 sec
        Start  81: test_wm_gcp
 81/180 Test  #81: test_wm_gcp .............................................   Passed    0.06 sec
        Start  82: test_wmodules_gcp
 82/180 Test  #82: test_wmodules_gcp .......................................   Passed    0.03 sec
        Start  83: test_wm_oscap
 83/180 Test  #83: test_wm_oscap ...........................................   Passed    0.02 sec
        Start  84: test_wm_sca
 84/180 Test  #84: test_wm_sca .............................................   Passed    0.02 sec
        Start  85: test_wmodules_scheduling
 85/180 Test  #85: test_wmodules_scheduling ................................   Passed    0.01 sec
        Start  86: test_wm_vulnerability_detection
 86/180 Test  #86: test_wm_vulnerability_detection .........................   Passed    0.03 sec
        Start  87: test_wm_task_manager
 87/180 Test  #87: test_wm_task_manager ....................................   Passed    0.02 sec
        Start  88: test_wm_task_manager_parsing
 88/180 Test  #88: test_wm_task_manager_parsing ............................   Passed    0.01 sec
        Start  89: test_wm_task_manager_commands
 89/180 Test  #89: test_wm_task_manager_commands ...........................   Passed    0.01 sec
        Start  90: test_wm_agent_upgrade
 90/180 Test  #90: test_wm_agent_upgrade ...................................   Passed    0.01 sec
        Start  91: test_wm_agent_upgrade_manager
 91/180 Test  #91: test_wm_agent_upgrade_manager ...........................   Passed    0.02 sec
        Start  92: test_wm_agent_upgrade_parsing
 92/180 Test  #92: test_wm_agent_upgrade_parsing ...........................   Passed    0.02 sec
        Start  93: test_wm_agent_upgrade_validate
 93/180 Test  #93: test_wm_agent_upgrade_validate ..........................   Passed    0.01 sec
        Start  94: test_wm_agent_upgrade_tasks
 94/180 Test  #94: test_wm_agent_upgrade_tasks .............................   Passed    0.01 sec
        Start  95: test_wm_agent_upgrade_tasks_callbacks
 95/180 Test  #95: test_wm_agent_upgrade_tasks_callbacks ...................   Passed    0.02 sec
        Start  96: test_wm_agent_upgrade_commands
 96/180 Test  #96: test_wm_agent_upgrade_commands ..........................   Passed    0.02 sec
        Start  97: test_wm_agent_upgrade_upgrades
 97/180 Test  #97: test_wm_agent_upgrade_upgrades ..........................   Passed    0.03 sec
        Start  98: test_wmodules
 98/180 Test  #98: test_wmodules ...........................................   Passed    0.02 sec
        Start  99: test_wm_control
 99/180 Test  #99: test_wm_control .........................................   Passed    0.02 sec
        Start 100: test_wm_github
100/180 Test #100: test_wm_github ..........................................   Passed    0.03 sec
        Start 101: test_wm_office365
101/180 Test #101: test_wm_office365 .......................................   Passed    0.04 sec
        Start 102: test_wm_ms_graph
102/180 Test #102: test_wm_ms_graph ........................................   Passed    0.04 sec
        Start 103: test_wm_osquery_already_running
103/180 Test #103: test_wm_osquery_already_running .........................   Passed    0.02 sec
        Start 104: test_wm_exec
104/180 Test #104: test_wm_exec ............................................   Passed    0.02 sec
        Start 105: test_monitord
105/180 Test #105: test_monitord ...........................................   Passed    0.01 sec
        Start 106: test_monitor_actions
106/180 Test #106: test_monitor_actions ....................................   Passed    0.02 sec
        Start 107: test_logcollector
107/180 Test #107: test_logcollector .......................................   Passed    0.03 sec
        Start 108: test_read_multiline_regex
108/180 Test #108: test_read_multiline_regex ...............................   Passed    0.03 sec
        Start 109: test_localfile-config
109/180 Test #109: test_localfile-config ...................................   Passed    0.02 sec
        Start 110: test_state
110/180 Test #110: test_state ..............................................   Passed    0.01 sec
        Start 111: test_lccom
111/180 Test #111: test_lccom ..............................................   Passed    0.49 sec
        Start 112: test_macos_log
112/180 Test #112: test_macos_log ..........................................   Passed    0.01 sec
        Start 113: test_read_macos
113/180 Test #113: test_read_macos .........................................   Passed    0.03 sec
        Start 114: test_read_multiline
114/180 Test #114: test_read_multiline .....................................   Passed    0.02 sec
        Start 115: test_read_journal
115/180 Test #115: test_read_journal .......................................   Passed    0.02 sec
        Start 116: test_journal_log
116/180 Test #116: test_journal_log ........................................   Passed    0.03 sec
        Start 117: test_read_syslog
117/180 Test #117: test_read_syslog ........................................   Passed    0.02 sec
        Start 118: test_execd
118/180 Test #118: test_execd ..............................................   Passed    0.01 sec
        Start 119: test_get_command_by_name
119/180 Test #119: test_get_command_by_name ................................   Passed    0.01 sec
        Start 120: test_integrator
120/180 Test #120: test_integrator .........................................   Passed    0.01 sec
        Start 121: test_manage_keys
121/180 Test #121: test_manage_keys ........................................   Passed    0.01 sec
        Start 122: test_printtable
122/180 Test #122: test_printtable .........................................   Passed    0.01 sec
        Start 123: test_csyslogd
123/180 Test #123: test_csyslogd ...........................................   Passed    0.01 sec
        Start 124: test_syscom
124/180 Test #124: test_syscom .............................................   Passed    0.01 sec
        Start 125: test_fim_diff_changes
125/180 Test #125: test_fim_diff_changes ...................................   Passed    0.03 sec
        Start 126: test_run_realtime
126/180 Test #126: test_run_realtime .......................................   Passed    0.03 sec
        Start 127: test_config
127/180 Test #127: test_config .............................................   Passed    0.04 sec
        Start 128: test_syscheck
128/180 Test #128: test_syscheck ...........................................   Passed    0.02 sec
        Start 129: test_run_check
129/180 Test #129: test_run_check ..........................................   Passed    0.03 sec
        Start 130: test_create_db
130/180 Test #130: test_create_db ..........................................   Passed    0.04 sec
        Start 131: test_audit_healthcheck
131/180 Test #131: test_audit_healthcheck ..................................   Passed    0.02 sec
        Start 132: test_audit_rule_handling
132/180 Test #132: test_audit_rule_handling ................................   Passed    0.02 sec
        Start 133: test_syscheck_audit
133/180 Test #133: test_syscheck_audit .....................................   Passed    0.08 sec
        Start 134: test_audit_parse
134/180 Test #134: test_audit_parse ........................................   Passed    0.03 sec
        Start 135: test_syscheck_ebpf
135/180 Test #135: test_syscheck_ebpf ......................................   Passed    0.03 sec
        Start 136: test_list_op
136/180 Test #136: test_list_op ............................................   Passed    0.02 sec
        Start 137: test_file_op
137/180 Test #137: test_file_op ............................................   Passed    0.01 sec
        Start 138: test_integrity_op
138/180 Test #138: test_integrity_op .......................................   Passed    0.01 sec
        Start 139: test_rbtree_op
139/180 Test #139: test_rbtree_op ..........................................   Passed    0.01 sec
        Start 140: test_validate_op
140/180 Test #140: test_validate_op ........................................   Passed    0.01 sec
        Start 141: test_string_op
141/180 Test #141: test_string_op ..........................................   Passed    0.01 sec
        Start 142: test_expression
142/180 Test #142: test_expression .........................................   Passed    0.01 sec
        Start 143: test_version_op
143/180 Test #143: test_version_op .........................................   Passed    0.02 sec
        Start 144: test_queue_op
144/180 Test #144: test_queue_op ...........................................   Passed    0.01 sec
        Start 145: test_queue_linked_op
145/180 Test #145: test_queue_linked_op ....................................   Passed    0.01 sec
        Start 146: test_agent_op
146/180 Test #146: test_agent_op ...........................................   Passed    0.01 sec
        Start 147: test_enrollment_op
147/180 Test #147: test_enrollment_op ......................................   Passed    0.02 sec
        Start 148: test_time_op
148/180 Test #148: test_time_op ............................................   Passed    0.01 sec
        Start 149: test_buffer_op
149/180 Test #149: test_buffer_op ..........................................   Passed    0.01 sec
        Start 150: test_utf8_op
150/180 Test #150: test_utf8_op ............................................   Passed    0.01 sec
        Start 151: test_log_builder
151/180 Test #151: test_log_builder ........................................   Passed    0.01 sec
        Start 152: test_custom_output_search_replace
152/180 Test #152: test_custom_output_search_replace .......................   Passed    0.01 sec
        Start 153: test_binaries_op
153/180 Test #153: test_binaries_op ........................................   Passed    0.01 sec
        Start 154: test_bzip2_op
154/180 Test #154: test_bzip2_op ...........................................   Passed    0.01 sec
        Start 155: test_schedule_scan
155/180 Test #155: test_schedule_scan ......................................   Passed    0.01 sec
        Start 156: test_rootcheck_op
156/180 Test #156: test_rootcheck_op .......................................   Passed    0.01 sec
        Start 157: test_fs_op
157/180 Test #157: test_fs_op ..............................................   Passed    0.01 sec
        Start 158: test_wazuhdb_op
158/180 Test #158: test_wazuhdb_op .........................................   Passed    0.01 sec
        Start 159: test_syscheck_op
159/180 Test #159: test_syscheck_op ........................................   Passed    0.03 sec
        Start 160: test_json_op
160/180 Test #160: test_json_op ............................................   Passed    0.01 sec
        Start 161: test_audit_op
161/180 Test #161: test_audit_op ...........................................   Passed    0.01 sec
        Start 162: test_privsep_op
162/180 Test #162: test_privsep_op .........................................   Passed    0.01 sec
        Start 163: test_mq_op
163/180 Test #163: test_mq_op ..............................................   Passed    0.01 sec
        Start 164: test_remoted_op
164/180 Test #164: test_remoted_op .........................................   Passed    0.01 sec
        Start 165: test_json-queue
165/180 Test #165: test_json-queue .........................................   Passed    0.01 sec
        Start 166: test_bqueue
166/180 Test #166: test_bqueue .............................................   Passed    0.01 sec
        Start 167: test_atomic
167/180 Test #167: test_atomic .............................................   Passed    0.01 sec
        Start 168: test_url
168/180 Test #168: test_url ................................................   Passed    0.01 sec
        Start 169: test_sysinfo_utils
169/180 Test #169: test_sysinfo_utils ......................................   Passed    0.01 sec
        Start 170: test_rwlock_op
170/180 Test #170: test_rwlock_op ..........................................   Passed    0.02 sec
        Start 171: test_os_xml
171/180 Test #171: test_os_xml .............................................   Passed    0.03 sec
        Start 172: test_os_regex
172/180 Test #172: test_os_regex ...........................................   Passed    0.01 sec
        Start 173: test_os_regex_match
173/180 Test #173: test_os_regex_match .....................................   Passed    0.01 sec
        Start 174: test_os_regex_execute
174/180 Test #174: test_os_regex_execute ...................................   Passed    0.02 sec
        Start 175: test_os_zlib
175/180 Test #175: test_os_zlib ............................................   Passed    0.01 sec
        Start 176: test_client-config_validate_ipv6_link_local_interface
176/180 Test #176: test_client-config_validate_ipv6_link_local_interface ...   Passed    0.02 sec
        Start 177: test_indexer
177/180 Test #177: test_indexer ............................................   Passed    0.01 sec
        Start 178: test_os_net
178/180 Test #178: test_os_net .............................................   Passed    0.01 sec
        Start 179: test_fluentd_forwarder
179/180 Test #179: test_fluentd_forwarder ..................................   Passed    0.02 sec
        Start 180: test_active-response
180/180 Test #180: test_active-response ....................................   Passed    0.01 sec

100% tests passed, 0 tests failed out of 180

Total Test time (real) =   5.49 sec

```

</p>
</details> 

<details><summary> Specific feature test: </summary>
<p>

* Config
```xml
<ossec_config>
  <global>
    <jsonout_output>yes</jsonout_output>
    <alerts_log>yes</alerts_log>
    <logall>no</logall>
    <logall_json>no</logall_json>
    <email_notification>yes</email_notification>
    <smtp_server>localhost</smtp_server>
    <email_from>sender@gmail.com</email_from>
    <email_to>kiwoxim259@fenexy.com</email_to>
    <email_maxperhour>120</email_maxperhour>
    <email_log_source>alerts.log</email_log_source>
    <agents_disconnection_time>10m</agents_disconnection_time>
    <agents_disconnection_alert_time>0</agents_disconnection_alert_time>
    <update_check>yes</update_check>
  </global>

  <alerts>
    <log_alert_level>3</log_alert_level>
    <email_alert_level>7</email_alert_level>
  </alerts>

<email_alerts>
  <email_to>coxole7585@bulmp3.com</email_to>
  <email_to>pm-vagrant@localhost</email_to>
  <format>sms</format>
  <level>7</level>
  <do_not_delay/>
</email_alerts>
```


* maild:
```console
# /var/ossec/bin/wazuh-maild -dd -f
2025/07/10 16:29:07 wazuh-maild[609620] debug_op.c:116 at _log_function(): DEBUG: Logging module auto-initialized
2025/07/10 16:29:07 wazuh-maild[609620] maild.c:196 at main(): DEBUG: Chrooted to directory: /var/ossec, using user: wazuh
2025/07/10 16:29:07 wazuh-maild[609620] maild.c:204 at main(): DEBUG: Chrooted to directory: /var/ossec, using user: wazuh
2025/07/10 16:29:07 wazuh-maild[609620] pthreads_op.c:45 at CreateThreadJoinable(): DEBUG: Thread stack size set to: 8192 KiB
2025/07/10 16:29:07 wazuh-maild[609620] maild.c:219 at main(): INFO: Started (pid: 609620).
2025/07/10 16:29:07 wazuh-maild[609620] maild.c:258 at OS_Run(): INFO: Getting alerts in log format.
2025/07/10 16:29:07 wazuh-maild[609620] mailcom.c:102 at mailcom_main(): DEBUG: Local requests thread ready
2025/07/10 16:29:27 wazuh-maild[609620] os_maild_client.c:218 at OS_RecvMailQ(): DEBUG: OS_RecvMailQ: mail->body[
Wazuh Notification.
2025 Jul 10 16:29:25

Received From: pm-ubuntu24-server->journald
Rule: 2502 fired (level 10) -> "syslog: User missed the password more than one time"
Src IP: 192.168.0.127
User: root
Portion of the log(s):

Jul 10 16:29:25 pm-ubuntu24-server sshd[609628]: PAM 2 more authentication failures; logname= uid=0 euid=0 tty=ssh ruser= rhost=192.168.0.127  user=root




 --END OF NOTIFICATION


]
^C2025/07/10 16:38:48 wazuh-maild[609620] sig_op.c:49 at HandleSIG(): INFO: (1225): SIGNAL [(2)-(Interrupt)] Received. Exit Cleaning...

```

* email_to general:
Screenshot From 2025-07-10 13-41-28
Screenshot From 2025-07-10 13-40-31
Screenshot From 2025-07-10 13-36-43


* email_to granular:

```console
~$ mail
"/var/mail/pm-vagrant": 2 messages 2 new
>N   1 Wazuh              Thu Jul 10 16:28  16/656   Wazuh 7 - 533 - Listened ports status (netstat) changed (new port opened or closed).
 N   2 Wazuh              Thu Jul 10 16:29  13/644   Wazuh 10 - 2502 - syslog: User missed the password more than one time

? 1
Return-Path: <sender@gmail.com>
X-Original-To: pm-vagrant@localhost
Delivered-To: pm-vagrant@localhost
Received: from notify.ossec.net (localhost [127.0.0.1])
  by pm-ubuntu24-server (Postfix) with SMTP id 660C1ABD2F;
  Thu, 10 Jul 2025 16:28:06 +0000 (UTC)
To: <coxole7585@bulmp3.com>, <pm-vagrant@localhost>
From: Wazuh <sender@gmail.com>
Date: Thu, 10 Jul 2025 16:28:06 +0000
Subject: Wazuh 7 - 533 - Listened ports status (netstat) changed (new port opened or closed).
Message-Id: <20250710162806.660C1ABD2F@pm-ubuntu24-server>

ossec: output: 'netstat listening ports':
tcp6 :::22 :::* 1/init
tcp 127.0.0.1:25 0.0.0.0:* 605855/master
tcp6 ::1:25 :::* 6

? 2
Return-Path: <sender@gmail.com>
X-Original-To: pm-vagrant@localhost
Delivered-To: pm-vagrant@localhost
Received: from notify.ossec.net (localhost [127.0.0.1])
  by pm-ubuntu24-server (Postfix) with SMTP id F340AABD2F;
  Thu, 10 Jul 2025 16:29:27 +0000 (UTC)
To: <coxole7585@bulmp3.com>, <pm-vagrant@localhost>
From: Wazuh <sender@gmail.com>
Date: Thu, 10 Jul 2025 16:29:27 +0000
Subject: Wazuh 10 - 2502 - syslog: User missed the password more than one time
Message-Id: <20250710162927.F340AABD2F@pm-ubuntu24-server>

Jul 10 16:29:25 pm-ubuntu24-server sshd[609628]: PAM 2 more authentication failures; logname= uid=0 euid=0 tty=ssh ruser= rhost

? 
```

</p>
</details> 


LGTM!

File: src/os_maild/sendmail.c [hunk 2]
```diff
@@ -505,49 +503,52 @@ int OS_Sendmail(MailConfig *mail, struct tm *p)
...
+        #undef APPEND
 
+        /* Send single TO: if there is at least one */
+        if (p != to_list) {
             if (sendmail) {
-                fprintf(sendmail->file_in, "%s", snd_msg);
+                fprintf(sendmail->file_in, TO, to_list);
             } else {
-                OS_SendTCP(socket, snd_msg);
+                char hdr[1080];
```
Comment (juliancnn) [inline src/os_maild/sendmail.c]: change the magic number to dine

File: src/os_maild/sendmail.c [hunk 3]
```diff
@@ -153,36 +153,42 @@ int OS_Sendsms(MailConfig *mail, struct tm *p, MailMsg *sms_msg)
...
-                if ((msg == NULL) || (!OS_Match(VALIDMAIL, msg))) {
+                if (!msg || !OS_Match(VALIDMAIL, msg)) {
                     merror(TO_ERROR, mail->gran_to[i]);
-                    if (msg) {
-                        free(msg);
-                    }
+                    free(msg);
                     close(socket);
-                    return (OS_INVALID);
+                    return OS_INVALID;
```
[the remark this answers is not in the document]
Comment (juliancnn) [reply src/os_maild/sendmail.c:197]: THe socket is closed before return

**Review by juliancnn — CHANGES_REQUESTED** [review]

**Review by LucioDonda — APPROVED** [review]
LGTM!

* Maild

```console
root@pm-ubuntu24-server:/home/pm-vagrant/workspace/wazuh# /var/ossec/bin/wazuh-maild -f -dd
2025/07/11 20:00:41 wazuh-maild[30157] debug_op.c:116 at _log_function(): DEBUG: Logging module auto-initialized
2025/07/11 20:00:41 wazuh-maild[30157] maild.c:196 at main(): DEBUG: Chrooted to directory: /var/ossec, using user: wazuh
2025/07/11 20:00:41 wazuh-maild[30157] maild.c:204 at main(): DEBUG: Chrooted to directory: /var/ossec, using user: wazuh
2025/07/11 20:00:41 wazuh-maild[30157] pthreads_op.c:45 at CreateThreadJoinable(): DEBUG: Thread stack size set to: 8192 KiB
2025/07/11 20:00:41 wazuh-maild[30157] maild.c:219 at main(): INFO: Started (pid: 30157).
2025/07/11 20:00:41 wazuh-maild[30157] maild.c:258 at OS_Run(): INFO: Getting alerts in log format.
2025/07/11 20:00:41 wazuh-maild[30157] mailcom.c:102 at mailcom_main(): DEBUG: Local requests thread ready
2025/07/11 20:01:01 wazuh-maild[30157] os_maild_client.c:218 at OS_RecvMailQ(): DEBUG: OS_RecvMailQ: mail->body[
Wazuh Notification.
2025 Jul 11 20:00:59

Received From: pm-ubuntu24-server->journald
Rule: 2502 fired (level 10) -> "syslog: User missed the password more than one time"
Src IP: 192.168.0.84
User: pm-vagrant
Portion of the log(s):

Jul 11 20:00:59 pm-ubuntu24-server sshd[30159]: PAM 2 more authentication failures; logname= uid=0 euid=0 tty=ssh ruser= rhost=192.168.0.84  user=pm-vagrant




 --END OF NOTIFICATION


]


```

* ossec.conf:

```xml
# cat /var/ossec/etc/ossec.conf 
<!--
  Wazuh - Manager - Default configuration for ubuntu 24.04
  More info at: https://documentation.wazuh.com
  Mailing list: https://groups.google.com/forum/#!forum/wazuh
-->

<ossec_config>
  <global>
    <jsonout_output>yes</jsonout_output>
    <alerts_log>yes</alerts_log>
    <logall>no</logall>
    <logall_json>no</logall_json>
    <email_notification>yes</email_notification>
    <smtp_server>localhost</smtp_server>
    <email_from>senderGlobal@gmail.com</email_from>
    <email_to>lopik45196@mytaemin.com</email_to>
    <email_maxperhour>1200</email_maxperhour>
    <email_log_source>alerts.log</email_log_source>
    <agents_disconnection_time>10m</agents_disconnection_time>
    <agents_disconnection_alert_time>0</agents_disconnection_alert_time>
    <update_check>yes</update_check>
  </global>

  <alerts>
    <log_alert_level>3</log_alert_level>
    <email_alert_level>7</email_alert_level>
  </alerts>

 <email_alerts>
   <email_to>coknibipsa@gufum.com</email_to>
   <email_to>pm-vagrant@localhost</email_to>
   <format>sms</format>
   <level>7</level>
   <do_not_delay/>
  </email_alerts>


```

Mail result

<details><summary>Details</summary>
<p>

Screenshot From 2025-07-11 17-02-24
Screenshot From 2025-07-11 17-02-12
Screenshot From 2025-07-11 17-01-56
Screenshot From 2025-07-11 17-01-40

local:

```console

```
</p>
</details>
