### PR TITLE
Fix FIM data races 

### LINKED ISSUE #6708: Data races reported by ThreadSanitizer in FIM
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.0.2 | FIM | Manager/Agent | Sources | Linux |

The following data races have been reported by ThreadSanitizer when running some stress tests on FIM, we must take a closer look at them and attempt to fix them ASAP.

Most of the messages are printed as soon as FIM is started, the last 4 errors are reported when realtime events start to be generated.

```
==================
WARNING: ThreadSanitizer: data race (pid=15444)
  Read of size 4 at 0x560a0e5455ec by main thread:
    #0 audit_health_check syscheckd/syscheck_audit.c:1479 (ossec-syscheckd+0x1fe05)
    #1 audit_init syscheckd/syscheck_audit.c:469 (ossec-syscheckd+0x20296)
    #2 main syscheckd/main.c:260 (ossec-syscheckd+0xd7ed)

  Previous write of size 4 at 0x560a0e5455ec by thread T2:
    #0 audit_parse syscheckd/syscheck_audit.c:1109 (ossec-syscheckd+0x1cb9f)
    #1 audit_read_events syscheckd/syscheck_audit.c:1376 (ossec-syscheckd+0x1f460)
    #2 audit_healthcheck_thread syscheckd/syscheck_audit.c:1160 (ossec-syscheckd+0x1f73d)
    #3 <null> <null> (libtsan.so.0+0x296ad)

  As if synchronized via sleep:
    #0 sleep <null> (libtsan.so.0+0x4d77b)
    #1 audit_health_check syscheckd/syscheck_audit.c:1478 (ossec-syscheckd+0x1fdf9)
    #2 audit_init syscheckd/syscheck_audit.c:469 (ossec-syscheckd+0x20296)
    #3 main syscheckd/main.c:260 (ossec-syscheckd+0xd7ed)

  Location is global 'audit_health_check_creation' of size 4 at 0x560a0e5455ec (ossec-syscheckd+0x0000003635ec)

  Thread T2 (tid=15447, running) created by main thread at:
    #0 pthread_create <null> (libtsan.so.0+0x2bcee)
    #1 CreateThreadJoinable shared/pthreads_op.c:47 (ossec-syscheckd+0xcef38)
    #2 CreateThread shared/pthreads_op.c:62 (ossec-syscheckd+0xcf078)
    #3 audit_health_check syscheckd/syscheck_audit.c:1461 (ossec-syscheckd+0x1fd63)
    #4 audit_init syscheckd/syscheck_audit.c:469 (ossec-syscheckd+0x20296)
    #5 main syscheckd/main.c:260 (ossec-syscheckd+0xd7ed)

SUMMARY: ThreadSanitizer: data race syscheckd/syscheck_audit.c:1479 in audit_health_check
==================
==================
WARNING: ThreadSanitizer: data race (pid=15444)
  Write of size 4 at 0x560a0e5455e8 by main thread:
    #0 audit_health_check syscheckd/syscheck_audit.c:1495 (ossec-syscheckd+0x1feb5)
    #1 audit_init syscheckd/syscheck_audit.c:469 (ossec-syscheckd+0x20296)
    #2 main syscheckd/main.c:260 (ossec-syscheckd+0xd7ed)

  Previous read of size 4 at 0x560a0e5455e8 by thread T2:
    #0 audit_read_events syscheckd/syscheck_audit.c:1267 (ossec-syscheckd+0x1f012)
    #1 audit_healthcheck_thread syscheckd/syscheck_audit.c:1160 (ossec-syscheckd+0x1f73d)
    #2 <null> <null> (libtsan.so.0+0x296ad)

  As if synchronized via sleep:
    #0 sleep <null> (libtsan.so.0+0x4d77b)
    #1 audit_health_check syscheckd/syscheck_audit.c:1478 (ossec-syscheckd+0x1fdf9)
    #2 audit_init syscheckd/syscheck_audit.c:469 (ossec-syscheckd+0x20296)
    #3 main syscheckd/main.c:260 (ossec-syscheckd+0xd7ed)

  Location is global 'hc_thread_active' of size 4 at 0x560a0e5455e8 (ossec-syscheckd+0x0000003635e8)

  Thread T2 (tid=15447, running) created by main thread at:
    #0 pthread_create <null> (libtsan.so.0+0x2bcee)
    #1 CreateThreadJoinable shared/pthreads_op.c:47 (ossec-syscheckd+0xcef38)
    #2 CreateThread shared/pthreads_op.c:62 (ossec-syscheckd+0xcf078)
    #3 audit_health_check syscheckd/syscheck_audit.c:1461 (ossec-syscheckd+0x1fd63)
    #4 audit_init syscheckd/syscheck_audit.c:469 (ossec-syscheckd+0x20296)
    #5 main syscheckd/main.c:260 (ossec-syscheckd+0xd7ed)

SUMMARY: ThreadSanitizer: data race syscheckd/syscheck_audit.c:1495 in audit_health_check
==================
==================
WARNING: ThreadSanitizer: data race (pid=15444)
  Write of size 4 at 0x560a0e544ca0 by thread T3:
    #0 audit_main syscheckd/syscheck_audit.c:1171 (ossec-syscheckd+0x1f810)
    #1 <null> <null> (libtsan.so.0+0x296ad)

  Previous write of size 4 at 0x560a0e544ca0 by thread T2:
    #0 audit_read_events syscheckd/syscheck_audit.c:1259 (ossec-syscheckd+0x1ef13)
    #1 audit_healthcheck_thread syscheckd/syscheck_audit.c:1160 (ossec-syscheckd+0x1f73d)
    #2 <null> <null> (libtsan.so.0+0x296ad)

  Location is global 'count_reload_retries' of size 4 at 0x560a0e544ca0 (ossec-syscheckd+0x000000362ca0)

  Thread T3 (tid=15449, running) created by main thread at:
    #0 pthread_create <null> (libtsan.so.0+0x2bcee)
    #1 CreateThreadJoinable shared/pthreads_op.c:47 (ossec-syscheckd+0xcef38)
    #2 CreateThread shared/pthreads_op.c:62 (ossec-syscheckd+0xcf078)
    #3 audit_init syscheckd/syscheck_audit.c:488 (ossec-syscheckd+0x201bb)
    #4 main syscheckd/main.c:260 (ossec-syscheckd+0xd7ed)

  Thread T2 (tid=15447, finished) created by main thread at:
    #0 pthread_create <null> (libtsan.so.0+0x2bcee)
    #1 CreateThreadJoinable shared/pthreads_op.c:47 (ossec-syscheckd+0xcef38)
    #2 CreateThread shared/pthreads_op.c:62 (ossec-syscheckd+0xcf078)
    #3 audit_health_check syscheckd/syscheck_audit.c:1461 (ossec-syscheckd+0x1fd63)
    #4 audit_init syscheckd/syscheck_audit.c:469 (ossec-syscheckd+0x20296)
    #5 main syscheckd/main.c:260 (ossec-syscheckd+0xd7ed)

SUMMARY: ThreadSanitizer: data race syscheckd/syscheck_audit.c:1171 in audit_main
==================
==================
WARNING: ThreadSanitizer: data race (pid=15444)
  Read of size 1 at 0x560a0e5452b0 by main thread:
    #0 os_check_restart_syscheck shared/agent_op.c:52 (ossec-syscheckd+0xd8b16)
    #1 start_daemon syscheckd/run_check.c:259 (ossec-syscheckd+0x19487)
    #2 main syscheckd/main.c:279 (ossec-syscheckd+0xd135)

  Previous write of size 1 at 0x560a0e5452b0 by thread T4:
    #0 os_check_restart_rootcheck shared/agent_op.c:63 (ossec-syscheckd+0xd8b69)
    #1 w_rootcheck_thread rootcheck/run_rk_check.c:313 (ossec-syscheckd+0x27305)
    #2 <null> <null> (libtsan.so.0+0x296ad)

  Location is global 'os_restart' of size 4 at 0x560a0e5452b0 (ossec-syscheckd+0x0000003632b0)

  Thread T4 (tid=15450, running) created by main thread at:
    #0 pthread_create <null> (libtsan.so.0+0x2bcee)
    #1 CreateThreadJoinable shared/pthreads_op.c:47 (ossec-syscheckd+0xcef38)
    #2 CreateThread shared/pthreads_op.c:62 (ossec-syscheckd+0xcf078)
    #3 start_daemon syscheckd/run_check.c:160 (ossec-syscheckd+0x19058)
    #4 main syscheckd/main.c:279 (ossec-syscheckd+0xd135)

SUMMARY: ThreadSanitizer: data race shared/agent_op.c:52 in os_check_restart_syscheck
==================
==================
WARNING: ThreadSanitizer: data race (pid=15444)
  Write of size 4 at 0x560a0e5452d0 by main thread (mutexes: write M20):
    #0 os_wait shared/wait_op.c:105 (ossec-syscheckd+0x10a864)
    #1 SendMSG shared/mq_op.c:63 (ossec-syscheckd+0xc7b46)
    #2 fim_send_msg syscheckd/run_check.c:64 (ossec-syscheckd+0x18b78)
    #3 send_syscheck_msg syscheckd/run_check.c:99 (ossec-syscheckd+0x18d43)
    #4 fim_file syscheckd/create_db.c:401 (ossec-syscheckd+0x12f12)
    #5 fim_checker syscheckd/create_db.c:277 (ossec-syscheckd+0x1343e)
    #6 fim_directory syscheckd/create_db.c:341 (ossec-syscheckd+0x136f6)
    #7 fim_checker syscheckd/create_db.c:292 (ossec-syscheckd+0x133d1)
    #8 fim_scan syscheckd/create_db.c:79 (ossec-syscheckd+0x13f36)
    #9 start_daemon syscheckd/run_check.c:302 (ossec-syscheckd+0x1956c)
    #10 main syscheckd/main.c:279 (ossec-syscheckd+0xd135)

  Previous write of size 4 at 0x560a0e5452d0 by thread T5:
    #0 os_wait shared/wait_op.c:105 (ossec-syscheckd+0x10a864)
    #1 SendMSG shared/mq_op.c:63 (ossec-syscheckd+0xc7b46)
    #2 fim_send_msg syscheckd/run_check.c:64 (ossec-syscheckd+0x18b78)
    #3 send_syscheck_msg syscheckd/run_check.c:99 (ossec-syscheckd+0x18d43)
    #4 fim_file syscheckd/create_db.c:401 (ossec-syscheckd+0x12f12)
    #5 fim_checker syscheckd/create_db.c:277 (ossec-syscheckd+0x1343e)
    #6 fim_realtime_event syscheckd/create_db.c:425 (ossec-syscheckd+0x14781)
    #7 realtime_process syscheckd/run_realtime.c:212 (ossec-syscheckd+0xf617)
    #8 fim_run_realtime syscheckd/run_check.c:379 (ossec-syscheckd+0x19ab4)
    #9 <null> <null> (libtsan.so.0+0x296ad)

  Location is global 'just_unlocked.29190' of size 4 at 0x560a0e5452d0 (ossec-syscheckd+0x0000003632d0)

  Mutex M20 (0x560a0e5454e8) created at:
    #0 pthread_mutex_init <null> (libtsan.so.0+0x2c5ad)
    #1 fim_initialize syscheckd/syscheck.c:89 (ossec-syscheckd+0x14be0)
    #2 main syscheckd/main.c:255 (ossec-syscheckd+0xd101)

  Thread T5 (tid=15451, running) created by main thread at:
    #0 pthread_create <null> (libtsan.so.0+0x2bcee)
    #1 CreateThreadJoinable shared/pthreads_op.c:47 (ossec-syscheckd+0xcef38)
    #2 CreateThread shared/pthreads_op.c:62 (ossec-syscheckd+0xcf078)
    #3 start_daemon syscheckd/run_check.c:193 (ossec-syscheckd+0x191a6)
    #4 main syscheckd/main.c:279 (ossec-syscheckd+0xd135)

SUMMARY: ThreadSanitizer: data race shared/wait_op.c:105 in os_wait
==================
==================
WARNING: ThreadSanitizer: data race (pid=15444)
  Read of size 4 at 0x560a0e5445f0 by main thread (mutexes: write M20):
    #0 send_syscheck_msg syscheckd/run_check.c:107 (ossec-syscheckd+0x18d65)
    #1 fim_file syscheckd/create_db.c:401 (ossec-syscheckd+0x12f12)
    #2 fim_checker syscheckd/create_db.c:277 (ossec-syscheckd+0x1343e)
    #3 fim_directory syscheckd/create_db.c:341 (ossec-syscheckd+0x136f6)
    #4 fim_checker syscheckd/create_db.c:292 (ossec-syscheckd+0x133d1)
    #5 fim_scan syscheckd/create_db.c:79 (ossec-syscheckd+0x13f36)
    #6 start_daemon syscheckd/run_check.c:302 (ossec-syscheckd+0x1956c)
    #7 main syscheckd/main.c:279 (ossec-syscheckd+0xd135)

  Previous write of size 4 at 0x560a0e5445f0 by thread T5:
    #0 send_syscheck_msg syscheckd/run_check.c:107 (ossec-syscheckd+0x18d7a)
    #1 fim_file syscheckd/create_db.c:401 (ossec-syscheckd+0x12f12)
    #2 fim_checker syscheckd/create_db.c:277 (ossec-syscheckd+0x1343e)
    #3 fim_realtime_event syscheckd/create_db.c:425 (ossec-syscheckd+0x14781)
    #4 realtime_process syscheckd/run_realtime.c:212 (ossec-syscheckd+0xf617)
    #5 fim_run_realtime syscheckd/run_check.c:379 (ossec-syscheckd+0x19ab4)
    #6 <null> <null> (libtsan.so.0+0x296ad)

  Location is global 'n_msg_sent.31002' of size 4 at 0x560a0e5445f0 (ossec-syscheckd+0x0000003625f0)

  Mutex M20 (0x560a0e5454e8) created at:
    #0 pthread_mutex_init <null> (libtsan.so.0+0x2c5ad)
    #1 fim_initialize syscheckd/syscheck.c:89 (ossec-syscheckd+0x14be0)
    #2 main syscheckd/main.c:255 (ossec-syscheckd+0xd101)

  Thread T5 (tid=15451, running) created by main thread at:
    #0 pthread_create <null> (libtsan.so.0+0x2bcee)
    #1 CreateThreadJoinable shared/pthreads_op.c:47 (ossec-syscheckd+0xcef38)
    #2 CreateThread shared/pthreads_op.c:62 (ossec-syscheckd+0xcf078)
    #3 start_daemon syscheckd/run_check.c:193 (ossec-syscheckd+0x191a6)
    #4 main syscheckd/main.c:279 (ossec-syscheckd+0xd135)

SUMMARY: ThreadSanitizer: data race syscheckd/run_check.c:107 in send_syscheck_msg
==================
==================
WARNING: ThreadSanitizer: data race (pid=15444)
  Read of size 1 at 0x7b0400002874 by main thread:
    #0 fim_scan syscheckd/create_db.c:156 (ossec-syscheckd+0x14244)
    #1 start_daemon syscheckd/run_check.c:302 (ossec-syscheckd+0x1956c)
    #2 main syscheckd/main.c:279 (ossec-syscheckd+0xd135)

  Previous write of size 1 at 0x7b0400002874 by thread T5:
    #0 realtime_process syscheckd/run_realtime.c:155 (ossec-syscheckd+0xf6ed)
    #1 fim_run_realtime syscheckd/run_check.c:379 (ossec-syscheckd+0x19ab4)
    #2 <null> <null> (libtsan.so.0+0x296ad)

  Location is heap block of size 16 at 0x7b0400002870 allocated by main thread:
    #0 calloc <null> (libtsan.so.0+0x2afc3)
    #1 realtime_start syscheckd/run_realtime.c:41 (ossec-syscheckd+0xe51e)
    #2 realtime_adddir syscheckd/run_realtime.c:75 (ossec-syscheckd+0xe9a4)
    #3 fim_checker syscheckd/create_db.c:289 (ossec-syscheckd+0x134ae)
    #4 fim_scan syscheckd/create_db.c:79 (ossec-syscheckd+0x13f36)
    #5 start_daemon syscheckd/run_check.c:190 (ossec-syscheckd+0x19193)
    #6 main syscheckd/main.c:279 (ossec-syscheckd+0xd135)

  Thread T5 (tid=15451, running) created by main thread at:
    #0 pthread_create <null> (libtsan.so.0+0x2bcee)
    #1 CreateThreadJoinable shared/pthreads_op.c:47 (ossec-syscheckd+0xcef38)
    #2 CreateThread shared/pthreads_op.c:62 (ossec-syscheckd+0xcf078)
    #3 start_daemon syscheckd/run_check.c:193 (ossec-syscheckd+0x191a6)
    #4 main syscheckd/main.c:279 (ossec-syscheckd+0xd135)

SUMMARY: ThreadSanitizer: data race syscheckd/create_db.c:156 in fim_scan
==================
```

### PR DESCRIPTION
**Pull request by antoniomanuelfr**
|Related issue|
|---|
|#6708|

## Description

This PR aims to fix the data races reported in issue #6708.
A new shared library has been added in order to handle atomic operations.

Closes #6708

### scheduled, realtime and whodata
***configuration***
```xml
    <directories realtime="yes">/testdir1</directories>
    <directories>/testdir2</directories>
    <directories whodata="yes">/testdir3</directories>
```
***helgrind output***
```
e monitoring: '/testdir3'
2021/03/17 07:27:40 wazuh-syscheckd[7351] audit_rule_handling.c:249 at clean_rules(): DEBUG: (6250): Deleting Audit rules.
==7351== 
==7351== Use --history-level=approx or =none to gain increased speed, at
==7351== the cost of reduced accuracy of conflicting-access information
==7351== For lists of detected and suppressed errors, rerun with: -s
==7351== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 4119 from 602)
root@ubuntuagent:/var/ossec# 
```

### Whodata
***configuration***
```xml
    <directories whodata="yes">/testdir3</directories>
```
***helgrind output***
```
2021/03/17 07:30:02 wazuh-syscheckd[7381] audit_rule_handling.c:249 at clean_rules(): DEBUG: (6250): Deleting Audit rules.
==7381== 
==7381== Use --history-level=approx or =none to gain increased speed, at
==7381== the cost of reduced accuracy of conflicting-access information
==7381== For lists of detected and suppressed errors, rerun with: -s
==7381== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 3464 from 302)
root@ubuntuagent:/var/ossec# 

```

- Compilation without warnings in every supported platform
  - [x] Linux
  - [x] Windows
  - [ ] MAC OS X
- [x] Source installation
- [x] Source upgrade
- [ ] Package upgrade

- Memory tests for Linux
  - [x] Scan-build report
  - [ ] Coverity
  - [x] ThreadSanitizer
  - [x] Helgrind
- Memory tests for Windows
  - [ ] Scan-build report

### CODE REVIEW

**Comment by antoniomanuelfr** [comment]
These are the integration test in CentOS, Ubuntu and Windows
[agent_centos_html_report_test_integration_B1482_20210319134802.zip](https://github.com/wazuh/wazuh/files/6172559/agent_centos_html_report_test_integration_B1482_20210319134802.zip)
[agent_ubuntu_html_report_test_integration_B1482_20210319134802.zip](https://github.com/wazuh/wazuh/files/6172561/agent_ubuntu_html_report_test_integration_B1482_20210319134802.zip)
[agent_windows_html_report_test_integration_B1482_20210319134802.zip](https://github.com/wazuh/wazuh/files/6172562/agent_windows_html_report_test_integration_B1482_20210319134802.zip)

File: src/syscheckd/run_check.c [hunk 1]
```diff
@@ -830,10 +848,6 @@ STATIC void fim_link_reload_broken_link(char *path, int index) {
 #endif
 #ifdef WIN_WHODATA
 void set_whodata_mode_changes() {
-    if (!syscheck.realtime) {
-        realtime_start();
```
Comment (Molter73) [inline src/syscheckd/run_check.c:834]: Are we certain we don't need to initialize realtime here? It looks to me that it could be possible to attempt to change whodata directories to realtime when no other directory is in this moda and could cause some trouble.

File: src/syscheckd/syscheck.h [hunk 2]
```diff
@@ -447,9 +447,9 @@ void remove_audit_rule_syscheck(const char *path);
  * @brief Read an audit event from socket
  *
  * @param [out] audit_sock The audit socket to read the events from
- * @param [in] reading_mode READING_MODE or HEALTHCHECK_MODE
+ * @param [in] running atomic_int that checks to check the running status of the thread.
```
Comment (Molter73) [inline src/syscheckd/syscheck.h:450]:
```suggestion
 * @param [in] running atomic_int that holds the status of the running thread.
```

File: src/syscheckd/whodata/audit_healthcheck.c [hunk 3]
```diff
@@ -74,25 +77,35 @@ int audit_health_check(int audit_socket) {
...
         mdebug1(FIM_HEALTHCHECK_CHECK_RULE); // LCOV_EXCL_LINE
     }
-    hc_thread_active = 0;
+    atomic_int_set(&hc_thread_active, 0);
+
+    // Lock this thread (with 5 seconds timeout) until the healthcheck thread has ended.
+    w_mutex_lock(&audit_hc_mutex);
+    gettime(&wait_time);
+    wait_time.tv_sec += 5;
+    pthread_cond_timedwait(&audit_hc_started, &audit_hc_mutex, &wait_time);
```
Comment (Molter73) [inline src/syscheckd/whodata/audit_healthcheck.c:86]: `audit_hc_started` should be renamed to better reflect what it is used for, it no longer serves as the condition variable to wait for the healthcheck thread to start, it is also used to wait for that same thread to stop. Maybe we could rename it to something like `audit_hc_cond`

File: src/syscheckd/whodata/audit_healthcheck.c [hunk 4]
```diff
@@ -74,25 +77,35 @@ int audit_health_check(int audit_socket) {
...
 
     mdebug2(FIM_HEALTHCHECK_THREAD_ACTIVE);
 
-    audit_read_events(audit_sock, HEALTHCHECK_MODE);
+    audit_read_events(audit_sock, &hc_thread_active);
 
     mdebug2(FIM_HEALTHCHECK_THREAD_FINISHED);
 
+    w_mutex_lock(&audit_hc_mutex);
+    w_cond_broadcast(&audit_hc_started);
```
Comment (Molter73) [inline src/syscheckd/whodata/audit_healthcheck.c:106]: I think a `w_cond_signal` makes more sense here, I believe there will be only one thread at most waiting for the condition variable.

File: src/unit_tests/shared/test_atomic.c [hunk 5]
```diff
@@ -0,0 +1,86 @@
...
+    atomic_int_set(&test_variable, 1231);
+    return 0;
+}
+
+static int teardown_variable(void **state) {
+    expect_function_call(__wrap_pthread_mutex_lock);
+    expect_function_call(__wrap_pthread_mutex_unlock);
+    atomic_int_set(&test_variable, 0);
+    return 0;
+}
```
Comment (Molter73) [inline src/unit_tests/shared/test_atomic.c:37]: These setup and teardown functions don't make much sense, they look the same as a test with no asserts.

I thinks a better approach would be to directly create the variable under test locally to each test and initialize it with the desired value directly.

File: src/unit_tests/shared/test_atomic.c [hunk 6]
```diff
@@ -0,0 +1,86 @@
...
+
+
+static void test_atomic_int_get(void **state) {
+    expect_function_call(__wrap_pthread_mutex_lock);
+    expect_function_call(__wrap_pthread_mutex_unlock);
+    int ret = atomic_int_get(&test_variable);
+
+    assert_int_equal(ret, 1231);
+    assert_int_equal(test_variable.data, 1231);
```
Comment (Molter73) [inline src/unit_tests/shared/test_atomic.c:46]: Testing the value saved inside `test_variable` doesn't make much sense IMO, we are testing the `atomic_int_get` interface, we know the value we expect from the created variable and what we expect as a result of calling `atomic_int_get` on it, we don't care what inner changes are made to `test_variable` as long as the result we get is the one we know to be correct.

File: src/unit_tests/wrappers/wazuh/shared/atomic_wrappers.c [hunk 7]
```diff
@@ -0,0 +1,34 @@
+/* Copyright (C) 2015-2020, Wazuh Inc.
```
Comment (Molter73) [inline src/unit_tests/wrappers/wazuh/shared/atomic_wrappers.c:1]:
```suggestion
/* Copyright (C) 2015-2021, Wazuh Inc.
```

**Review by Molter73 — APPROVED** [review]
LGTM!

**Review by Molter73 — APPROVED** [review]
LGTM!
