### PR TITLE
Fix reading of values from RocksDB during agent re-scan

### LINKED ISSUE #24546: Vulnerability Scanner error processing delayed event in VD performance Tests
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.1-rc2 | Vulnerability Detection | Manager | Packages | Ubuntu 22 |

### Description

Multiple unexpected vulnerability scanner errors occurred during the  [Release 4.8.1 - RC 2 - Vulnerability Detection performance test](https://github.com/wazuh/wazuh/issues/24504) on the master node
```
2024/07/09 13:51:08 wazuh-modulesd:vulnerability-scanner: ERROR: Error processing delayed event: [json.exception.parse_error.101] parse error at line 1, column 73: syntax error while parsing value - invalid literal; last read: '"no-index":true}<U+0004>'; expected end of input
...
```

Despite these errors, vulnerabilities were correctly generated in the environment and included in the vulnerability index.

> [!NOTE]
> These errors did not appear in [v4.8.0](https://github.com/wazuh/wazuh/issues/23982#issuecomment-2160540345)

### Overview

Performance tests are planned to detect any regression in the Vulnerability Detection module. In order to generate multiple vulnerability detection events, used Agent [Simulator QA tool](https://github.com/wazuh/wazuh-qa/blob/master/deps/wazuh_testing/wazuh_testing/tools/agent_simulator.py). 
This warning could be related to the usage of the agent simulator, although it's necessary to a thorough research to determine the causes of this issue.

More information can be found in [this comment](https://github.com/wazuh/wazuh/issues/24504#issuecomment-2222791472) 

**Artifacts**:
- [Artifact1.zip](https://github.com/user-attachments/files/16176888/Artifact1.zip)
- [Artifact2.zip](https://github.com/user-attachments/files/16176900/Artifact2.zip)
- [Artifact3.zip](https://github.com/user-attachments/files/16176907/Artifact3.zip)

### PR DESCRIPTION
**Pull request by pereyra-m**
|Related issue|
|---|
|Closes #24546|

## Description

This PR fixes the JSON parse of the values read from the DBs adding the corresponding size.
I've also added the capability of reading message buffer flatbuffers to the internal `rocks_db_test_tool` to make the future debugging easier.

## Tests

Here I have the ASAN errors for the added test without the fix

<details><summary>Details</summary>
<p>

```

==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from ScanOrchestratorTest
[ RUN      ] ScanOrchestratorTest.TestRunScannerTypeJSON
=================================================================
==384983==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x519000044180 at pc 0x7f4a1e23f96f bp 0x7ffe932203a0 sp 0x7ffe9321fb48
READ of size 57 at 0x519000044180 thread T0
    #0 0x7f4a1e23f96e in strlen ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:391
    #1 0x562f5d91a6cf in nlohmann::json_abi_v3_11_2::detail::iterator_input_adapter<char const*> nlohmann::json_abi_v3_11_2::detail::input_adapter<signed char const*, 0>(signed char const*) /workspaces/wazuh.worktrees/bug/24546-vd-error-processing-delayed-event/src/external/nlohmann/json.hpp:6520
    #2 0x562f5d907786 in nlohmann::json_abi_v3_11_2::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_2::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > > nlohmann::json_abi_v3_11_2::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_2::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > >::parse<signed char const*>(signed char const*&&, std::function<bool (int, nlohmann::json_abi_v3_11_2::detail::parse_event_t, nlohmann::json_abi_v3_11_2::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_2::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > >&)>, bool, bool) /workspaces/wazuh.worktrees/bug/24546-vd-error-processing-delayed-event/src/external/nlohmann/json.hpp:23192
    #3 0x562f5d8eef3e in TScanOrchestrator<TrampolineTScanContext, TrampolineFactoryOrchestrator, MockAbstractHandler<std::shared_ptr<TrampolineTScanContext> >, MockIndexerConnector, MockDatabaseFeedManager, OSPrimitives, TrampolineSocketDBWrapper, 60>::processEvent(rocksdb::PinnableSlice const&, bool) const /workspaces/wazuh.worktrees/bug/24546-vd-error-processing-delayed-event/src/wazuh_modules/vulnerability_scanner/src/databaseFeedManager/../scanOrchestrator/scanOrchestrator.hpp:226
    #4 0x562f5d8a7679 in ScanOrchestratorTest_TestRunScannerTypeJSON_Test::TestBody() /workspaces/wazuh.worktrees/bug/24546-vd-error-processing-delayed-event/src/wazuh_modules/vulnerability_scanner/tests/unit/scanOrchestrator_test.cpp:1259
    #5 0x562f5de08efc in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /workspaces/wazuh.worktrees/bug/24546-vd-error-processing-delayed-event/src/external/googletest/googletest/src/gtest.cc:2607
    #6 0x562f5de015da in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /workspaces/wazuh.worktrees/bug/24546-vd-error-processing-delayed-event/src/external/googletest/googletest/src/gtest.cc:2643
    #7 0x562f5ddd45e9 in testing::Test::Run() /workspaces/wazuh.worktrees/bug/24546-vd-error-processing-delayed-event/src/external/googletest/googletest/src/gtest.cc:2682
    #8 0x562f5ddd5109 in testing::TestInfo::Run() /workspaces/wazuh.worktrees/bug/24546-vd-error-processing-delayed-event/src/external/googletest/googletest/src/gtest.cc:2861
    #9 0x562f5ddd5a74 in testing::TestSuite::Run() /workspaces/wazuh.worktrees/bug/24546-vd-error-processing-delayed-event/src/external/googletest/googletest/src/gtest.cc:3015
    #10 0x562f5dde6533 in testing::internal::UnitTestImpl::RunAllTests() /workspaces/wazuh.worktrees/bug/24546-vd-error-processing-delayed-event/src/external/googletest/googletest/src/gtest.cc:5855
    #11 0x562f5de09f44 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /workspaces/wazuh.worktrees/bug/24546-vd-error-processing-delayed-event/src/external/googletest/googletest/src/gtest.cc:2607
    #12 0x562f5de028d2 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /workspaces/wazuh.worktrees/bug/24546-vd-error-processing-delayed-event/src/external/googletest/googletest/src/gtest.cc:2643
    #13 0x562f5dde4ac4 in testing::UnitTest::Run() /workspaces/wazuh.worktrees/bug/24546-vd-error-processing-delayed-event/src/external/googletest/googletest/src/gtest.cc:5438
    #14 0x562f5d23102b in RUN_ALL_TESTS() /workspaces/wazuh.worktrees/bug/24546-vd-error-processing-delayed-event/src/external/googletest/googletest/include/gtest/gtest.h:2490
    #15 0x562f5d230de6 in main /workspaces/wazuh.worktrees/bug/24546-vd-error-processing-delayed-event/src/wazuh_modules/vulnerability_scanner/tests/unit/main.cpp:17
    #16 0x7f4a19e021c9 in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #17 0x7f4a19e0228a in __libc_start_main_impl ../csu/libc-start.c:360
    #18 0x562f5be80624 in _start (/workspaces/wazuh.worktrees/bug/24546-vd-error-processing-delayed-event/src/build/wazuh_modules/vulnerability_scanner/tests/unit/vulnerability_scanner_unit_tests+0xc41d624) (BuildId: ce6071d19b630d984be6111a1e5e622a9a7c9585)

0x519000044180 is located 0 bytes after 1024-byte region [0x519000043d80,0x519000044180)
allocated by thread T0 here:
    #0 0x7f4a1e2c06c8 in operator new[](unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:98
    #1 0x562f5becfc57 in flatbuffers::DefaultAllocator::allocate(unsigned long) /workspaces/wazuh.worktrees/bug/24546-vd-error-processing-delayed-event/src/external/flatbuffers/include/flatbuffers/default_allocator.h:29
    #2 0x562f5c7eaecf in flatbuffers::Allocate(flatbuffers::Allocator*, unsigned long) /workspaces/wazuh.worktrees/bug/24546-vd-error-processing-delayed-event/src/external/flatbuffers/include/flatbuffers/default_allocator.h:43
    #3 0x562f5c933569 in flatbuffers::vector_downward<unsigned int>::reallocate(unsigned long) /workspaces/wazuh.worktrees/bug/24546-vd-error-processing-delayed-event/src/external/flatbuffers/include/flatbuffers/vector_downward.h:280
    #4 0x562f5c8e5380 in flatbuffers::vector_downward<unsigned int>::ensure_space(unsigned long) /workspaces/wazuh.worktrees/bug/24546-vd-error-processing-delayed-event/src/external/flatbuffers/include/flatbuffers/vector_downward.h:145
    #5 0x562f5c8e4b06 in flatbuffers::vector_downward<unsigned int>::make_space(unsigned long) /workspaces/wazuh.worktrees/bug/24546-vd-error-processing-delayed-event/src/external/flatbuffers/include/flatbuffers/vector_downward.h:152
    #6 0x562f5c933f2c in flatbuffers::vector_downward<unsigned int>::push(unsigned char const*, unsigned long) /workspaces/wazuh.worktrees/bug/24546-vd-error-processing-delayed-event/src/external/flatbuffers/include/flatbuffers/vector_downward.h:196
    #7 0x562f5c8e71c0 in flatbuffers::FlatBufferBuilderImpl<false>::PushBytes(unsigned char const*, unsigned long) /workspaces/wazuh.worktrees/bug/24546-vd-error-processing-delayed-event/src/external/flatbuffers/include/flatbuffers/flatbuffer_builder.h:303
    #8 0x562f5d8f8967 in flatbuffers::Offset<flatbuffers::Vector<signed char> > flatbuffers::FlatBufferBuilderImpl<false>::CreateVector<signed char, flatbuffers::Offset, flatbuffers::Vector>(signed char const*, unsigned long) /workspaces/wazuh.worktrees/bug/24546-vd-error-processing-delayed-event/src/external/flatbuffers/include/flatbuffers/flatbuffer_builder.h:738
    #9 0x562f5d8df9fc in flatbuffers::Offset<flatbuffers::Vector<signed char, unsigned int> > flatbuffers::FlatBufferBuilderImpl<false>::CreateVector<signed char, std::allocator<signed char> >(std::vector<signed char, std::allocator<signed char> > const&) /workspaces/wazuh.worktrees/bug/24546-vd-error-processing-delayed-event/src/external/flatbuffers/include/flatbuffers/flatbuffer_builder.h:789
    #10 0x562f5d8d962c in CreateMessageBufferDirect(flatbuffers::FlatBufferBuilderImpl<false>&, std::vector<signed char, std::allocator<signed char> > const*, BufferType, unsigned long) /workspaces/wazuh.worktrees/bug/24546-vd-error-processing-delayed-event/src/wazuh_modules/vulnerability_scanner/include/messageBuffer_generated.h:122
    #11 0x562f5d8a724a in ScanOrchestratorTest_TestRunScannerTypeJSON_Test::TestBody() /workspaces/wazuh.worktrees/bug/24546-vd-error-processing-delayed-event/src/wazuh_modules/vulnerability_scanner/tests/unit/scanOrchestrator_test.cpp:1248
    #12 0x562f5de08efc in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /workspaces/wazuh.worktrees/bug/24546-vd-error-processing-delayed-event/src/external/googletest/googletest/src/gtest.cc:2607
    #13 0x562f5de015da in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /workspaces/wazuh.worktrees/bug/24546-vd-error-processing-delayed-event/src/external/googletest/googletest/src/gtest.cc:2643
    #14 0x562f5ddd45e9 in testing::Test::Run() /workspaces/wazuh.worktrees/bug/24546-vd-error-processing-delayed-event/src/external/googletest/googletest/src/gtest.cc:2682
    #15 0x562f5ddd5109 in testing::TestInfo::Run() /workspaces/wazuh.worktrees/bug/24546-vd-error-processing-delayed-event/src/external/googletest/googletest/src/gtest.cc:2861
    #16 0x562f5ddd5a74 in testing::TestSuite::Run() /workspaces/wazuh.worktrees/bug/24546-vd-error-processing-delayed-event/src/external/googletest/googletest/src/gtest.cc:3015
    #17 0x562f5dde6533 in testing::internal::UnitTestImpl::RunAllTests() /workspaces/wazuh.worktrees/bug/24546-vd-error-processing-delayed-event/src/external/googletest/googletest/src/gtest.cc:5855
    #18 0x562f5de09f44 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /workspaces/wazuh.worktrees/bug/24546-vd-error-processing-delayed-event/src/external/googletest/googletest/src/gtest.cc:2607
    #19 0x562f5de028d2 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /workspaces/wazuh.worktrees/bug/24546-vd-error-processing-delayed-event/src/external/googletest/googletest/src/gtest.cc:2643
    #20 0x562f5dde4ac4 in testing::UnitTest::Run() /workspaces/wazuh.worktrees/bug/24546-vd-error-processing-delayed-event/src/external/googletest/googletest/src/gtest.cc:5438
    #21 0x562f5d23102b in RUN_ALL_TESTS() /workspaces/wazuh.worktrees/bug/24546-vd-error-processing-delayed-event/src/external/googletest/googletest/include/gtest/gtest.h:2490
    #22 0x562f5d230de6 in main /workspaces/wazuh.worktrees/bug/24546-vd-error-processing-delayed-event/src/wazuh_modules/vulnerability_scanner/tests/unit/main.cpp:17
    #23 0x7f4a19e021c9 in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #24 0x7f4a19e0228a in __libc_start_main_impl ../csu/libc-start.c:360
    #25 0x562f5be80624 in _start (/workspaces/wazuh.worktrees/bug/24546-vd-error-processing-delayed-event/src/build/wazuh_modules/vulnerability_scanner/tests/unit/vulnerability_scanner_unit_tests+0xc41d624) (BuildId: ce6071d19b630d984be6111a1e5e622a9a7c9585)

SUMMARY: AddressSanitizer: heap-buffer-overflow ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:391 in strlen
Shadow bytes around the buggy address:
  0x519000043f00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x519000043f80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x519000044000: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x519000044080: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x519000044100: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x519000044180:[fa]fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x519000044200: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x519000044280: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x519000044300: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x519000044380: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x519000044400: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==384983==ABORTING

```

</p>
</details> 

- Compilation without warnings in every supported platform
  - [x] Linux
- [x] Source installation

- [x] Added unit tests (for new features)

### CODE REVIEW

File: src/wazuh_modules/vulnerability_scanner/testtool/rocksDBQuery/main.cpp [hunk 1]
```diff
@@ -34,35 +37,86 @@ int main(const int argc, const char** argv)
...
+            if (isMessageBuffer.empty())
             {
-                std::string strData;
-                flatbuffers::GenText(parser, reinterpret_cast<const uint8_t*>(slice.data()), &strData);
-                std::cout << key << " ==> " << strData << std::endl;
+                if (!fbs.empty())
+                {
+                    std::string strData;
+                    flatbuffers::GenText(fbParser, reinterpret_cast<const uint8_t*>(slice.data()), &strData);
+                    std::cout << key << " ==> " << strData << std::endl;
```
Comment (MiguelazoDS) [inline src/wazuh_modules/vulnerability_scanner/testtool/rocksDBQuery/main.cpp:78]: Shouldn't be this output more readable in a JSON format?

**Review by MiguelazoDS — APPROVED** [review]

File: src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/scanOrchestrator.hpp [hunk 2]
```diff
@@ -223,7 +223,19 @@ class TScanOrchestrator final : public TOSPrimitives
...
+                jsonData =
+                    nlohmann::json::parse(message->data()->data(), message->data()->data() + message->data()->size());
+            }
+            catch (const nlohmann::json::parse_error& e)
+            {
+                std::string jsonMessage {message->data()->data(), message->data()->data() + message->data()->size()};
+                logDebug2(WM_VULNSCAN_LOGTAG, "Error parsing JSON: %s", jsonMessage.c_str());
+                throw;
+            }
+
```
Comment (Dwordcito) [inline src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/scanOrchestrator.hpp:238]:
```suggestion
            nlohmann::json jsonData = nlohmann::json::parse(message->data()->data(), message->data()->data() + message->data()->size());
```

I think the try-catch is not necessary and this propagates to the error handling already available.

Both in the initEventDelayedDispatcher lambda, as well as in the initEventDispatcher, In both places the exception is caught, the event dropped/not processed and a log is printed.

Comment (pereyra-m) [reply src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/scanOrchestrator.hpp:238]: Hi.

The idea here was to obtain more information, because the current log doesn't show the full JSON message

```
ERROR: Error processing delayed event: [json.exception.parse_error.101] parse error at line 1, column 73: syntax error while parsing value - invalid literal; last read: '"no-index":true}<U+0004>'; expected end of input
```

So I catch and re-throw but log in the middle.
Another option is to use 


```c++

nlohmann::json jsonData = nlohmann::json::parse(message->data()->data(), message->data()->data() + message->data()->size(), nullptr, false);
```

Then we check if it has been discarded

```c++
if(jsonData.is_discarded()) {
```

And finally we log and throw.
This approach generates a more user friendly message and it keeps showing more context to the developer. 
The current one isn't enough in case of errors for the user to understand what is happening and for us to debug the problem.

Comment (Dwordcito) [reply src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/scanOrchestrator.hpp:238]: If you want to have an additional log, let's do it where appropriate.
what was said, extend in initEventDelayedDispatcher and in initEventDispatcher.

Let's not use the function that does not throw exceptions, nor let's catch exceptions elsewhere.

Comment (pereyra-m) [reply src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/scanOrchestrator.hpp:238]: Now I understand.
I'll move it to the right place and I'll add a catch for `nlohmann::json::exception` in the `initEventDelayedDispatcher`.
Thank you.

Comment (pereyra-m) [reply src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/scanOrchestrator.hpp:238]: Now I understand.
I'll move it to the right place and I'll add a catch for `nlohmann::json::exception` in the `initEventDelayedDispatcher`.
Thank you.

Comment (pereyra-m) [reply src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/scanOrchestrator.hpp]: Changes uploaded.

**Review by Dwordcito — APPROVED** [review]
