### PR TITLE
Fix memory leak in analysisd when parsing a disabled AR.

### LINKED ISSUE #10201: Memory leak in Analysisd when parsing a disabled Active Response stanza
|Wazuh version|Component|Install type
|---|---|---|
| 1.0.0 | Analysisd | Manager|

## Configuration

```xml
  <command>
    <name>test_AR_windows</name>
    <executable>AR_script.cmd</executable>
  </command>

  <active-response>
    <disabled>yes</disabled>
    <command>test_AR_windows</command>
    <location>local</location>
    <rules_id>100002</rules_id>
    <location>defined-agent</location>
    <agent_id>001</agent_id>
    <rules_group>syslog</rules_group>
  </active-response>
```

## Valgrind report

```
==4320==
==4320== HEAP SUMMARY:
==4320==     in use at exit: 10,085,775 bytes in 57,840 blocks
==4320==   total heap usage: 389,511 allocs, 331,671 frees, 1,094,932,058 bytes allocated
==4320==
==4320== 4 bytes in 1 blocks are definitely lost in loss record 5 of 354
==4320==    at 0x483B7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==4320==    by 0x506E50E: strdup (strdup.c:42)
==4320==    by 0x17FFBD: ReadActiveResponses (active-response.c:123)
==4320==    by 0x17CEAA: read_main_elements (config.c:139)
==4320==    by 0x17D98D: ReadConfig (config.c:282)
==4320==    by 0x11EF9A: AR_ReadConfig (active-response.c:76)
==4320==    by 0x145555: main (analysisd.c:394)
==4320==
==4320== 7 bytes in 1 blocks are definitely lost in loss record 15 of 354
==4320==    at 0x483B7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==4320==    by 0x506E50E: strdup (strdup.c:42)
==4320==    by 0x18002A: ReadActiveResponses (active-response.c:125)
==4320==    by 0x17CEAA: read_main_elements (config.c:139)
==4320==    by 0x17D98D: ReadConfig (config.c:282)
==4320==    by 0x11EF9A: AR_ReadConfig (active-response.c:76)
==4320==    by 0x145555: main (analysisd.c:394)
==4320==
==4320== 7 bytes in 1 blocks are definitely lost in loss record 16 of 354
==4320==    at 0x483B7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==4320==    by 0x506E50E: strdup (strdup.c:42)
==4320==    by 0x180097: ReadActiveResponses (active-response.c:127)
==4320==    by 0x17CEAA: read_main_elements (config.c:139)
==4320==    by 0x17D98D: ReadConfig (config.c:282)
==4320==    by 0x11EF9A: AR_ReadConfig (active-response.c:76)
==4320==    by 0x145555: main (analysisd.c:394)
==4320==
==4320== LEAK SUMMARY:
==4320==    definitely lost: 18 bytes in 3 blocks
==4320==    indirectly lost: 0 bytes in 0 blocks
==4320==      possibly lost: 0 bytes in 0 blocks
==4320==    still reachable: 10,085,757 bytes in 57,837 blocks
==4320==         suppressed: 0 bytes in 0 blocks
```

### PR DESCRIPTION
**Pull request by antoniomanuelfr**
|Related issue|
|---|
|#10201|

## Description
This PR fixes a memory leak when parsing a disabled AR stanza.

Closes  #10201

## Configuration options
```xml
  <command>
    <name>test_AR_windows</name>
    <executable>AR_script.cmd</executable>
  </command>

  <active-response>
    <disabled>yes</disabled>
    <command>test_AR_windows</command>
    <location>local</location>
    <rules_id>100002</rules_id>
    <location>defined-agent</location>
    <agent_id>001</agent_id>
    <rules_group>syslog</rules_group>
  </active-response>
```

## Logs/Alerts example
```
/05/09 08:24:21 wazuh-analysisd[10449] pthreads_op.c:45 at CreateThreadJoinable(): DEBUG: Thread stack size set to: 8192 KiB
2022/05/09 08:24:21 wazuh-analysisd[10449] analysisd.c:1052 at OS_ReadMSG(): DEBUG: Startup completed. Waiting for new messages..
2022/05/09 08:24:21 wazuh-analysisd[10449] state.c:86 at w_analysisd_state_main(): DEBUG: State file updating thread started.
2022/05/09 08:24:21 wazuh-analysisd[10449] state.c:106 at w_analysisd_write_state(): DEBUG: Updating state file.
^C2022/05/09 08:24:25 wazuh-analysisd[10449] sig_op.c:49 at HandleSIG(): INFO: (1225): SIGNAL [(2)-(Interrupt)] Received. Exit Cleaning...
==10449== 
==10449== HEAP SUMMARY:
==10449==     in use at exit: 21,548,506 bytes in 117,582 blocks
==10449==   total heap usage: 823,541 allocs, 705,959 frees, 2,561,225,988 bytes allocated
==10449== 
==10449== 288 bytes in 1 blocks are possibly lost in loss record 221 of 473
==10449==    at 0x483DD99: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==10449==    by 0x40149CA: allocate_dtv (dl-tls.c:286)
==10449==    by 0x40149CA: _dl_allocate_tls (dl-tls.c:532)
==10449==    by 0x517A322: allocate_stack (allocatestack.c:622)
==10449==    by 0x517A322: pthread_create@@GLIBC_2.2.5 (pthread_create.c:660)
==10449==    by 0x24DF84: CreateThreadJoinable (pthreads_op.c:47)
==10449==    by 0x24E02C: CreateThread (pthreads_op.c:62)
==10449==    by 0x148E08: main (analysisd.c:814)
==10449== 
==10449== 288 bytes in 1 blocks are possibly lost in loss record 222 of 473
==10449==    at 0x483DD99: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==10449==    by 0x40149CA: allocate_dtv (dl-tls.c:286)
==10449==    by 0x40149CA: _dl_allocate_tls (dl-tls.c:532)
==10449==    by 0x517A322: allocate_stack (allocatestack.c:622)
==10449==    by 0x517A322: pthread_create@@GLIBC_2.2.5 (pthread_create.c:660)
==10449==    by 0x24DF84: CreateThreadJoinable (pthreads_op.c:47)
==10449==    by 0x24E02C: CreateThread (pthreads_op.c:62)
==10449==    by 0x148E4E: main (analysisd.c:820)
==10449== 
==10449== 288 bytes in 1 blocks are possibly lost in loss record 223 of 473
==10449==    at 0x483DD99: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==10449==    by 0x40149CA: allocate_dtv (dl-tls.c:286)
==10449==    by 0x40149CA: _dl_allocate_tls (dl-tls.c:532)
==10449==    by 0x517A322: allocate_stack (allocatestack.c:622)
==10449==    by 0x517A322: pthread_create@@GLIBC_2.2.5 (pthread_create.c:660)
==10449==    by 0x24DF84: CreateThreadJoinable (pthreads_op.c:47)
==10449==    by 0x24E02C: CreateThread (pthreads_op.c:62)
==10449==    by 0x140FE3: w_logtest_init (logtest.c:65)
==10449==    by 0x5179608: start_thread (pthread_create.c:477)
==10449==    by 0x52B3162: clone (clone.S:95)
==10449== 
==10449== 288 bytes in 1 blocks are possibly lost in loss record 224 of 473
==10449==    at 0x483DD99: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==10449==    by 0x40149CA: allocate_dtv (dl-tls.c:286)
==10449==    by 0x40149CA: _dl_allocate_tls (dl-tls.c:532)
==10449==    by 0x517A322: allocate_stack (allocatestack.c:622)
==10449==    by 0x517A322: pthread_create@@GLIBC_2.2.5 (pthread_create.c:660)
==10449==    by 0x24DF84: CreateThreadJoinable (pthreads_op.c:47)
==10449==    by 0x24E02C: CreateThread (pthreads_op.c:62)
==10449==    by 0x1739D2: SecurityConfigurationAssessmentInit (security_configuration_assessment.c:82)
==10449==    by 0x148EEB: OS_ReadMSG (analysisd.c:862)
==10449==    by 0x148E83: main (analysisd.c:823)
==10449== 
==10449== 288 bytes in 1 blocks are possibly lost in loss record 225 of 473
==10449==    at 0x483DD99: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==10449==    by 0x40149CA: allocate_dtv (dl-tls.c:286)
==10449==    by 0x40149CA: _dl_allocate_tls (dl-tls.c:532)
==10449==    by 0x517A322: allocate_stack (allocatestack.c:622)
==10449==    by 0x517A322: pthread_create@@GLIBC_2.2.5 (pthread_create.c:660)
==10449==    by 0x24DF84: CreateThreadJoinable (pthreads_op.c:47)
==10449==    by 0x24E02C: CreateThread (pthreads_op.c:62)
==10449==    by 0x1494C4: OS_ReadMSG (analysisd.c:981)
==10449==    by 0x148E83: main (analysisd.c:823)
==10449== 
==10449== 288 bytes in 1 blocks are possibly lost in loss record 226 of 473
==10449==    at 0x483DD99: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==10449==    by 0x40149CA: allocate_dtv (dl-tls.c:286)
==10449==    by 0x40149CA: _dl_allocate_tls (dl-tls.c:532)
==10449==    by 0x517A322: allocate_stack (allocatestack.c:622)
==10449==    by 0x517A322: pthread_create@@GLIBC_2.2.5 (pthread_create.c:660)
==10449==    by 0x24DF84: CreateThreadJoinable (pthreads_op.c:47)
==10449==    by 0x24E02C: CreateThread (pthreads_op.c:62)
==10449==    by 0x1494FD: OS_ReadMSG (analysisd.c:984)
==10449==    by 0x148E83: main (analysisd.c:823)
==10449== 
==10449== 288 bytes in 1 blocks are possibly lost in loss record 227 of 473
==10449==    at 0x483DD99: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==10449==    by 0x40149CA: allocate_dtv (dl-tls.c:286)
==10449==    by 0x40149CA: _dl_allocate_tls (dl-tls.c:532)
==10449==    by 0x517A322: allocate_stack (allocatestack.c:622)
==10449==    by 0x517A322: pthread_create@@GLIBC_2.2.5 (pthread_create.c:660)
==10449==    by 0x24DF84: CreateThreadJoinable (pthreads_op.c:47)
==10449==    by 0x24E02C: CreateThread (pthreads_op.c:62)
==10449==    by 0x149536: OS_ReadMSG (analysisd.c:987)
==10449==    by 0x148E83: main (analysisd.c:823)
==10449== 
==10449== 288 bytes in 1 blocks are possibly lost in loss record 228 of 473
==10449==    at 0x483DD99: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==10449==    by 0x40149CA: allocate_dtv (dl-tls.c:286)
==10449==    by 0x40149CA: _dl_allocate_tls (dl-tls.c:532)
==10449==    by 0x517A322: allocate_stack (allocatestack.c:622)
==10449==    by 0x517A322: pthread_create@@GLIBC_2.2.5 (pthread_create.c:660)
==10449==    by 0x24DF84: CreateThreadJoinable (pthreads_op.c:47)
==10449==    by 0x24E02C: CreateThread (pthreads_op.c:62)
==10449==    by 0x14956F: OS_ReadMSG (analysisd.c:990)
==10449==    by 0x148E83: main (analysisd.c:823)
==10449== 
==10449== 288 bytes in 1 blocks are possibly lost in loss record 229 of 473
==10449==    at 0x483DD99: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==10449==    by 0x40149CA: allocate_dtv (dl-tls.c:286)
==10449==    by 0x40149CA: _dl_allocate_tls (dl-tls.c:532)
==10449==    by 0x517A322: allocate_stack (allocatestack.c:622)
==10449==    by 0x517A322: pthread_create@@GLIBC_2.2.5 (pthread_create.c:660)
==10449==    by 0x24DF84: CreateThreadJoinable (pthreads_op.c:47)
==10449==    by 0x24E02C: CreateThread (pthreads_op.c:62)
==10449==    by 0x1495A8: OS_ReadMSG (analysisd.c:993)
==10449==    by 0x148E83: main (analysisd.c:823)
==10449== 
==10449== 288 bytes in 1 blocks are possibly lost in loss record 230 of 473
==10449==    at 0x483DD99: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==10449==    by 0x40149CA: allocate_dtv (dl-tls.c:286)
==10449==    by 0x40149CA: _dl_allocate_tls (dl-tls.c:532)
==10449==    by 0x517A322: allocate_stack (allocatestack.c:622)
==10449==    by 0x517A322: pthread_create@@GLIBC_2.2.5 (pthread_create.c:660)
==10449==    by 0x24DF84: CreateThreadJoinable (pthreads_op.c:47)
==10449==    by 0x24E02C: CreateThread (pthreads_op.c:62)
==10449==    by 0x1495E1: OS_ReadMSG (analysisd.c:996)
==10449==    by 0x148E83: main (analysisd.c:823)
==10449== 
==10449== 288 bytes in 1 blocks are possibly lost in loss record 231 of 473
==10449==    at 0x483DD99: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==10449==    by 0x40149CA: allocate_dtv (dl-tls.c:286)
==10449==    by 0x40149CA: _dl_allocate_tls (dl-tls.c:532)
==10449==    by 0x517A322: allocate_stack (allocatestack.c:622)
==10449==    by 0x517A322: pthread_create@@GLIBC_2.2.5 (pthread_create.c:660)
==10449==    by 0x24DF84: CreateThreadJoinable (pthreads_op.c:47)
==10449==    by 0x24E02C: CreateThread (pthreads_op.c:62)
==10449==    by 0x14961A: OS_ReadMSG (analysisd.c:999)
==10449==    by 0x148E83: main (analysisd.c:823)
==10449== 
==10449== 288 bytes in 1 blocks are possibly lost in loss record 232 of 473
==10449==    at 0x483DD99: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==10449==    by 0x40149CA: allocate_dtv (dl-tls.c:286)
==10449==    by 0x40149CA: _dl_allocate_tls (dl-tls.c:532)
==10449==    by 0x517A322: allocate_stack (allocatestack.c:622)
==10449==    by 0x517A322: pthread_create@@GLIBC_2.2.5 (pthread_create.c:660)
==10449==    by 0x24DF84: CreateThreadJoinable (pthreads_op.c:47)
==10449==    by 0x24E02C: CreateThread (pthreads_op.c:62)
==10449==    by 0x149917: OS_ReadMSG (analysisd.c:1047)
==10449==    by 0x148E83: main (analysisd.c:823)
==10449== 
==10449== 288 bytes in 1 blocks are possibly lost in loss record 233 of 473
==10449==    at 0x483DD99: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==10449==    by 0x40149CA: allocate_dtv (dl-tls.c:286)
==10449==    by 0x40149CA: _dl_allocate_tls (dl-tls.c:532)
==10449==    by 0x517A322: allocate_stack (allocatestack.c:622)
==10449==    by 0x517A322: pthread_create@@GLIBC_2.2.5 (pthread_create.c:660)
==10449==    by 0x24DF84: CreateThreadJoinable (pthreads_op.c:47)
==10449==    by 0x24E02C: CreateThread (pthreads_op.c:62)
==10449==    by 0x149953: OS_ReadMSG (analysisd.c:1050)
==10449==    by 0x148E83: main (analysisd.c:823)
==10449== 
==10449== 1,152 bytes in 4 blocks are possibly lost in loss record 287 of 473
==10449==    at 0x483DD99: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==10449==    by 0x40149CA: allocate_dtv (dl-tls.c:286)
==10449==    by 0x40149CA: _dl_allocate_tls (dl-tls.c:532)
==10449==    by 0x517A322: allocate_stack (allocatestack.c:622)
==10449==    by 0x517A322: pthread_create@@GLIBC_2.2.5 (pthread_create.c:660)
==10449==    by 0x24DF84: CreateThreadJoinable (pthreads_op.c:47)
==10449==    by 0x24E02C: CreateThread (pthreads_op.c:62)
==10449==    by 0x14965C: OS_ReadMSG (analysisd.c:1003)
==10449==    by 0x148E83: main (analysisd.c:823)
==10449== 
==10449== 1,152 bytes in 4 blocks are possibly lost in loss record 288 of 473
==10449==    at 0x483DD99: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==10449==    by 0x40149CA: allocate_dtv (dl-tls.c:286)
==10449==    by 0x40149CA: _dl_allocate_tls (dl-tls.c:532)
==10449==    by 0x517A322: allocate_stack (allocatestack.c:622)
==10449==    by 0x517A322: pthread_create@@GLIBC_2.2.5 (pthread_create.c:660)
==10449==    by 0x24DF84: CreateThreadJoinable (pthreads_op.c:47)
==10449==    by 0x24E02C: CreateThread (pthreads_op.c:62)
==10449==    by 0x1496AA: OS_ReadMSG (analysisd.c:1008)
==10449==    by 0x148E83: main (analysisd.c:823)
==10449== 
==10449== 1,152 bytes in 4 blocks are possibly lost in loss record 289 of 473
==10449==    at 0x483DD99: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==10449==    by 0x40149CA: allocate_dtv (dl-tls.c:286)
==10449==    by 0x40149CA: _dl_allocate_tls (dl-tls.c:532)
==10449==    by 0x517A322: allocate_stack (allocatestack.c:622)
==10449==    by 0x517A322: pthread_create@@GLIBC_2.2.5 (pthread_create.c:660)
==10449==    by 0x24DF84: CreateThreadJoinable (pthreads_op.c:47)
==10449==    by 0x24E02C: CreateThread (pthreads_op.c:62)
==10449==    by 0x1496F8: OS_ReadMSG (analysisd.c:1013)
==10449==    by 0x148E83: main (analysisd.c:823)
==10449== 
==10449== 1,152 bytes in 4 blocks are possibly lost in loss record 290 of 473
==10449==    at 0x483DD99: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==10449==    by 0x40149CA: allocate_dtv (dl-tls.c:286)
==10449==    by 0x40149CA: _dl_allocate_tls (dl-tls.c:532)
==10449==    by 0x517A322: allocate_stack (allocatestack.c:622)
==10449==    by 0x517A322: pthread_create@@GLIBC_2.2.5 (pthread_create.c:660)
==10449==    by 0x24DF84: CreateThreadJoinable (pthreads_op.c:47)
==10449==    by 0x24E02C: CreateThread (pthreads_op.c:62)
==10449==    by 0x149746: OS_ReadMSG (analysisd.c:1018)
==10449==    by 0x148E83: main (analysisd.c:823)
==10449== 
==10449== 1,152 bytes in 4 blocks are possibly lost in loss record 291 of 473
==10449==    at 0x483DD99: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==10449==    by 0x40149CA: allocate_dtv (dl-tls.c:286)
==10449==    by 0x40149CA: _dl_allocate_tls (dl-tls.c:532)
==10449==    by 0x517A322: allocate_stack (allocatestack.c:622)
==10449==    by 0x517A322: pthread_create@@GLIBC_2.2.5 (pthread_create.c:660)
==10449==    by 0x24DF84: CreateThreadJoinable (pthreads_op.c:47)
==10449==    by 0x24E02C: CreateThread (pthreads_op.c:62)
==10449==    by 0x149794: OS_ReadMSG (analysisd.c:1023)
==10449==    by 0x148E83: main (analysisd.c:823)
==10449== 
==10449== 1,152 bytes in 4 blocks are possibly lost in loss record 292 of 473
==10449==    at 0x483DD99: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==10449==    by 0x40149CA: allocate_dtv (dl-tls.c:286)
==10449==    by 0x40149CA: _dl_allocate_tls (dl-tls.c:532)
==10449==    by 0x517A322: allocate_stack (allocatestack.c:622)
==10449==    by 0x517A322: pthread_create@@GLIBC_2.2.5 (pthread_create.c:660)
==10449==    by 0x24DF84: CreateThreadJoinable (pthreads_op.c:47)
==10449==    by 0x24E02C: CreateThread (pthreads_op.c:62)
==10449==    by 0x1497E2: OS_ReadMSG (analysisd.c:1028)
==10449==    by 0x148E83: main (analysisd.c:823)
==10449== 
==10449== 1,152 bytes in 4 blocks are possibly lost in loss record 293 of 473
==10449==    at 0x483DD99: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==10449==    by 0x40149CA: allocate_dtv (dl-tls.c:286)
==10449==    by 0x40149CA: _dl_allocate_tls (dl-tls.c:532)
==10449==    by 0x517A322: allocate_stack (allocatestack.c:622)
==10449==    by 0x517A322: pthread_create@@GLIBC_2.2.5 (pthread_create.c:660)
==10449==    by 0x24DF84: CreateThreadJoinable (pthreads_op.c:47)
==10449==    by 0x24E02C: CreateThread (pthreads_op.c:62)
==10449==    by 0x149833: OS_ReadMSG (analysisd.c:1033)
==10449==    by 0x148E83: main (analysisd.c:823)
==10449== 
==10449== 1,152 bytes in 4 blocks are possibly lost in loss record 294 of 473
==10449==    at 0x483DD99: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==10449==    by 0x40149CA: allocate_dtv (dl-tls.c:286)
==10449==    by 0x40149CA: _dl_allocate_tls (dl-tls.c:532)
==10449==    by 0x517A322: allocate_stack (allocatestack.c:622)
==10449==    by 0x517A322: pthread_create@@GLIBC_2.2.5 (pthread_create.c:660)
==10449==    by 0x24DF84: CreateThreadJoinable (pthreads_op.c:47)
==10449==    by 0x24E02C: CreateThread (pthreads_op.c:62)
==10449==    by 0x149884: OS_ReadMSG (analysisd.c:1038)
==10449==    by 0x148E83: main (analysisd.c:823)
==10449== 
==10449== 1,152 bytes in 4 blocks are possibly lost in loss record 295 of 473
==10449==    at 0x483DD99: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==10449==    by 0x40149CA: allocate_dtv (dl-tls.c:286)
==10449==    by 0x40149CA: _dl_allocate_tls (dl-tls.c:532)
==10449==    by 0x517A322: allocate_stack (allocatestack.c:622)
==10449==    by 0x517A322: pthread_create@@GLIBC_2.2.5 (pthread_create.c:660)
==10449==    by 0x24DF84: CreateThreadJoinable (pthreads_op.c:47)
==10449==    by 0x24E02C: CreateThread (pthreads_op.c:62)
==10449==    by 0x1498D2: OS_ReadMSG (analysisd.c:1043)
==10449==    by 0x148E83: main (analysisd.c:823)
==10449== 
==10449== LEAK SUMMARY:
==10449==    definitely lost: 0 bytes in 0 blocks
==10449==    indirectly lost: 0 bytes in 0 blocks
==10449==      possibly lost: 14,112 bytes in 49 blocks
==10449==    still reachable: 21,534,394 bytes in 117,533 blocks
==10449==         suppressed: 0 bytes in 0 blocks
==10449== Reachable blocks (those to which a pointer was found) are not shown.
==10449== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==10449== 
==10449== For lists of detected and suppressed errors, rerun with: -s
==10449== ERROR SUMMARY: 22 errors from 22 contexts (suppressed: 0 from 0)
==10449== could not unlink /tmp/vgdb-pipe-from-vgdb-to-10449-by-root-on-???
==10449== could not unlink /tmp/vgdb-pipe-to-vgdb-from-10449-by-root-on-???
==10449== could not unlink /tmp/vgdb-pipe-shared-mem-vgdb-10449-by-root-on-???
root@ubuntumanager:/home/vagrant/wazuh# 

```

## Tests

- Compilation without warnings in every supported platform
  - [X] Linux
- [x] Source installation
- [x] Source upgrade

- Memory tests for Linux
  - [x] Scan-build report
  - [ ] Coverity
  - [X] Valgrind (memcheck and descriptor leaks check)
  - [ ] AddressSanitizer

### CODE REVIEW

**Comment by antoniomanuelfr** [comment]
Scan-build reported no errors:
```

Done building server

scan-build: Analysis run complete.
scan-build: Removing directory '/tmp/scan-build-2022-05-09-103159-17461-1' because it contains no reports.
scan-build: No bugs found.
➜  src git:(10201-fix-disabled-ar-leak) 
```

File: src/config/active-response.c [hunk 1]
```diff
@@ -320,19 +281,17 @@ int ReadActiveResponses(XML_NODE node, void *d1, void *d2)
         ar_flag |= LOCAL_AR;
     }
 
-    /* Close shared file for active response */
+end:
```
Comment (chemamartinez) [inline src/config/active-response.c:284]: Be careful here because the old version didn't free any field of `tmp_ar` since it has to keep available in the active response list.

The resources should be freed only if the insertion didn't happen.

**Review by chemamartinez — CHANGES_REQUESTED** [review]

**Review by chemamartinez — COMMENTED** [review]
Let's fix the function below `ReadActiveCommands` where we are only freeing the structure `tmp_command` but not its members.

**Review by chemamartinez — APPROVED** [review]
LGTM!
