### PR TITLE
Fix handling syscollector insertion deltas

### LINKED ISSUE #12550: Syscollector insertion deltas are treating empty fields as empty string rather than NULL
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| master branch (v4.4.0) | Syscollector | Manager | Any | GNU/Linux |

# Description

Hi team,

@wazuh/framework team found a discrepancy between v4.2.x/v4.3 and v4.4.0 (master branch) regarding syscollector processes API requests. 

While v4.4 returns fields with empty string values, v4.2.x/v4.3 does no.
- v4.2.x/v4.3 : `['ok', '[{"pid":"2051","state":"Z"}]']`
- v4.4: `['ok', '[{"cmd":"","pid":"9365","state":"Z"}]']`

After a RCA it was found that Syscollector insertion deltas are treating empty fields as empty string rather than NULL.

It is desirable to still treat them as NULL values and store them in that way.

# Current behavior
Insertion deltas that contain empty fields are stored into the agent inventory database as empty fields
# Expected behavior
Insertion deltas that contain empty fields are stored into the agent inventory database as NULL values

Regards,
Nico

### PR DESCRIPTION
**Pull request by jnasselle**
|Related issue|
|---|
|#12550|

## Description

This PR aims to fix/change some aspects regarding syscollector deltas handling

### Storing fields as db's null when their value is an empty string

Some syscollector fields could have empty strings as their values. Before this PR, these fields were stored as it in the inventory db, changing the behavior compared to versions without deltas.

Steps to reproduce:
- Create a delta event to analysisd queue containing an empty field (see argvs and cmd)
```
2022/05/30 08:24:20 wazuh-modulesd:syscollector[5435] wm_syscollector.c:107 at wm_sys_log(): DEBUG: Delta sent: {"data":{"argvs":null,"checksum":"e817194ac47e2b09ee1ee66f48351f62c69b6c62","cmd":null,"egroup":"root","euser":"root","fgroup":"root","name":"kworker/u16:2-e","nice":0,"nlwp":1,"pgrp":0,"pid":"6868","ppid":2,"priority":20,"processor":6,"resident":0,"rgroup":"root","ruser":"root","scan_time":"2022/05/30 08:24:15","session":0,"sgroup":"root","share":0,"size":0,"start_time":1653899041,"state":"I","stime":0,"suser":"root","tgid":6868,"tty":0,"utime":0,"vm_size":0},"operation":"INSERTED","type":"dbsync_processes"}
```

Before change behavior
- Query to inventory database shows an empty string

Expected behavior
- Stored field contains null element

Current behavior
- Stored field contains null element
```
sqlite> select * from sys_processes where PID="6868" and argvs is null;
   scan_id = 0
 scan_time = 2022/05/30 08:28:38
       pid = 6868
      name = kworker/u16:2-e
     state = I
      ppid = 2
     utime = 0
     stime = 4
       cmd = 
     argvs = 
     euser = root
     ruser = root
     suser = root
    egroup = root
    rgroup = root
    sgroup = root
    fgroup = root
  priority = 20
      nice = 0
      size = 0
   vm_size = 0
  resident = 0
     share = 0
start_time = 1653899041
      pgrp = 0
   session = 0
      nlwp = 1
      tgid = 6868
       tty = 0
 processor = 5
  checksum = da70921d54176004350fb508c33b1920c8a9e495
```
```
curl -sSk -X GET "https://localhost:55000/syscollector/000/processes?pid=6868" -H "Authorization: Bearer $TOKEN"                                             130 ↵
{"data": {"affected_items": [{"scan": {"id": 0, "time": "2022-05-30T08:30:51+00:00"}, "state": "I", "session": 0, "name": "kworker/u16:2-e", "pid": "6868", "egroup": "root", "tty": 0, "share": 0, "utime": 0, "sgroup": "root", "ppid": 2, "nice": 0, "rgroup": "root", "start_time": 1653899041, "ruser": "root", "suser": "root", "processor": 4, "euser": "root", "priority": 20, "vm_size": 0, "stime": 7, "tgid": 6868, "fgroup": "root", "nlwp": 1, "resident": 0, "pgrp": 0, "size": 0, "agent_id": "000"}], "total_affected_items": 1, "total_failed_items": 0, "failed_items": []}, "message": "All specified syscollector information was returned", "error": 0}
```
### Avoid showing null values on syscollector alerts

Steps to reproduce:
### Storing fields as db's null when their value is an empty string
```
2022/05/30 08:36:01 wazuh-modulesd:syscollector[9339] wm_syscollector.c:107 at wm_sys_log(): DEBUG: Delta sent: {"data":{"checksum":"346a833071b479864c524a5f9ce80b4f0e7590a9","inode":326471,"item_id":"99860bca303f4696fe08400de9a3f841937453eb","local_ip":"0.0.0.0","local_port":55000,"pid":0,"process":null,"protocol":"tcp","remote_ip":"0.0.0.0","remote_port":0,"rx_queue":0,"scan_time":"2022/05/30 08:36:00","state":"listening","tx_queue":0},"operation":"INSERTED","type":"dbsync_ports"}
```
Before change behavior
- Alert contains "NULL" value

Expected behavior
 - Field was not shown in the alert

Current behavior
 - Field was not shown in the alert
```
sqlite> select * from sys_ports where local_port=55000 and process is null;
0|2022/05/30 08:36:00|tcp|0.0.0.0|55000|0.0.0.0|0|0|0|326471|listening|0||346a833071b479864c524a5f9ce80b4f0e7590a9|99860bca303f4696fe08400de9a3f841937453eb
```
```json
{
  "timestamp": "2022-05-30T08:36:01.447+0000",
  "rule": {
    "level": 3,
    "description": "Syscollector port creation event.",
    "id": "100311",
    "firedtimes": 1,
    "mail": false,
    "groups": [
      "syscollector"
    ]
  },
  "agent": {
    "id": "000",
    "name": "wazuh-dev"
  },
  "manager": {
    "name": "wazuh-dev"
  },
  "id": "1653899761.344919",
  "full_log": "{\"data\":{\"checksum\":\"346a833071b479864c524a5f9ce80b4f0e7590a9\",\"inode\":326471,\"item_id\":\"99860bca303f4696fe08400de9a3f841937453eb\",\"local_ip\":\"0.0.0.0\",\"local_port\":55000,\"pid\":0,\"process\":null,\"protocol\":\"tcp\",\"remote_ip\":\"0.0.0.0\",\"remote_port\":0,\"rx_queue\":0,\"scan_time\":\"2022/05/30 08:36:00\",\"state\":\"listening\",\"tx_queue\":0},\"operation\":\"INSERTED\",\"type\":\"dbsync_ports\"}",
  "decoder": {
    "name": "syscollector"
  },
  "data": {
    "type": "dbsync_ports",
    "port": {
      "protocol": "tcp",
      "local_ip": "0.0.0.0",
      "local_port": "55000",
      "remote_ip": "0.0.0.0",
      "remote_port": "0",
      "tx_queue": "0",
      "rx_queue": "0",
      "inode": "326471",
      "state": "listening",
      "pid": "0"
    },
    "operation_type": "INSERTED"
  },
  "location": "syscollector"
}
```
### Other fixes
Some UT with warnings were fixed
<details>
    <summary>Warnings</summary>

```    
    /root/repos/wazuh/src/unit_tests/wazuh_db/test_wdb_syscollector.c:2203:9: warning: ‘wdb_osinfo_insert’ accessing 41 bytes in a region of size 10 [-Wstringop-overflow=]
     2203 |         wdb_osinfo_insert(data, "scan_id", "scan_time", "hostname", "architecture", "os_name", "os_version",
          |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     2204 |                           "os_codename", "os_major", "os_minor", "os_patch", "os_build", "os_platform", "sysname",
          |                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     2205 |                           "release", "version", "os_release", "os_display_version", "checksum", false, "hexdigest", 1);
          |                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /root/repos/wazuh/src/unit_tests/wazuh_db/test_wdb_syscollector.c:2203:9: note: referencing argument 21 of type ‘char *’
    In file included from /root/repos/wazuh/src/unit_tests/wazuh_db/test_wdb_syscollector.c:10:
    /root/repos/wazuh/src/wazuh_db/wdb.h:751:5: note: in a call to function ‘wdb_osinfo_insert’
      751 | int wdb_osinfo_insert(wdb_t * wdb, const char * scan_id, const char * scan_time, const char * hostname, const char * architecture, const char * os_name, const char * os_version, const char * os_codename, const char * os_major, const char * os_minor, const char * os_patch, const char * os_build, const char * os_platform, const char * sysname, const char * release, const char * version, const char * os_release, const char * os_display_version, const char * checksum, const bool replace, os_sha1 hexdigest, int triaged);
          |     ^~~~~~~~~~~~~~~~~
    /root/repos/wazuh/src/unit_tests/wazuh_db/test_wdb_syscollector.c: In function ‘test_wdb_osinfo_insert_sql_fail’:
    /root/repos/wazuh/src/unit_tests/wazuh_db/test_wdb_syscollector.c:2280:9: warning: ‘wdb_osinfo_insert’ accessing 41 bytes in a region of size 10 [-Wstringop-overflow=]
     2280 |         wdb_osinfo_insert(data, "scan_id", "scan_time", "hostname", "architecture", "os_name", "os_version",
          |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     2281 |                           "os_codename", "os_major", "os_minor", "os_patch", "os_build", "os_platform", "sysname",
          |                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     2282 |                           "release", "version", "os_release", "os_display_version", "checksum", false, "hexdigest", 1);
          |                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /root/repos/wazuh/src/unit_tests/wazuh_db/test_wdb_syscollector.c:2280:9: note: referencing argument 21 of type ‘char *’
    In file included from /root/repos/wazuh/src/unit_tests/wazuh_db/test_wdb_syscollector.c:10:
    /root/repos/wazuh/src/wazuh_db/wdb.h:751:5: note: in a call to function ‘wdb_osinfo_insert’
      751 | int wdb_osinfo_insert(wdb_t * wdb, const char * scan_id, const char * scan_time, const char * hostname, const char * architecture, const char * os_name, const char * os_version, const char * os_codename, const char * os_major, const char * os_minor, const char * os_patch, const char * os_build, const char * os_platform, const char * sysname, const char * release, const char * version, const char * os_release, const char * os_display_version, const char * checksum, const bool replace, os_sha1 hexdigest, int triaged);
          |     ^~~~~~~~~~~~~~~~~
    Scanning dependencies of target test_logtest-config
    Scanning dependencies of target test_log
    /root/repos/wazuh/src/unit_tests/wazuh_db/test_wdb_syscollector.c: In function ‘test_wdb_osinfo_insert_success’:
    /root/repos/wazuh/src/unit_tests/wazuh_db/test_wdb_syscollector.c:2354:9: warning: ‘wdb_osinfo_insert’ accessing 41 bytes in a region of size 10 [-Wstringop-overflow=]
     2354 |         wdb_osinfo_insert(data, "scan_id", "scan_time", "hostname", "architecture", "os_name", "os_version",
          |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     2355 |                           "os_codename", "os_major", "os_minor", "os_patch", "os_build", "os_platform", "sysname",
          |                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     2356 |                           "release", "version", "os_release", "os_display_version", "checksum", false, "hexdigest", 1);
          |                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /root/repos/wazuh/src/unit_tests/wazuh_db/test_wdb_syscollector.c:2354:9: note: referencing argument 21 of type ‘char *’
    In file included from /root/repos/wazuh/src/unit_tests/wazuh_db/test_wdb_syscollector.c:10:
    /root/repos/wazuh/src/wazuh_db/wdb.h:751:5: note: in a call to function ‘wdb_osinfo_insert’
      751 | int wdb_osinfo_insert(wdb_t * wdb, const char * scan_id, const char * scan_time, const char * hostname, const char * architecture, const char * os_name, const char * os_version, const char * os_codename, const char * os_major, const char * os_minor, const char * os_patch, const char * os_build, const char * os_platform, const char * sysname, const char * release, const char * version, const char * os_release, const char * os_display_version, const char * checksum, const bool replace, os_sha1 hexdigest, int triaged);
      
      
      In file included from /root/repos/wazuh/src/unit_tests/wazuh_db/test_wdb_integrity.c:13:
    /root/repos/wazuh/src/unit_tests/wazuh_db/test_wdb_integrity.c: In function ‘test_wdbi_checksum_range_wbs_null’:
    /root/repos/wazuh/src/unit_tests/wazuh_db/test_wdb_integrity.c:183:27: warning: ‘wdbi_checksum_range’ accessing 41 bytes in a region of size 1 [-Wstringop-overflow=]
      183 |     expect_assert_failure(wdbi_checksum_range(NULL, 0, "test_begin", "test_end", ""));
          |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /root/repos/wazuh/src/unit_tests/wazuh_db/test_wdb_integrity.c:183:27: note: referencing argument 5 of type ‘char *’
    In file included from /root/repos/wazuh/src/unit_tests/wazuh_db/test_wdb_integrity.c:17:
    /root/repos/wazuh/src/headers/../wazuh_db/wdb.h:1462:5: note: in a call to function ‘wdbi_checksum_range’
     1462 | int wdbi_checksum_range(wdb_t * wdb, wdb_component_t component, const char * begin, const char * end, os_sha1 hexdigest);
     
     In file included from /root/repos/wazuh/src/unit_tests/wazuh_db/test_wdb_integrity.c:13:
    /root/repos/wazuh/src/unit_tests/wazuh_db/test_wdb_integrity.c: In function ‘test_wdbi_checksum_wbs_null’:
    /root/repos/wazuh/src/unit_tests/wazuh_db/test_wdb_integrity.c:129:27: warning: ‘wdbi_checksum’ accessing 41 bytes in a region of size 1 [-Wstringop-overflow=]
      129 |     expect_assert_failure(wdbi_checksum(NULL, 0, ""));
          |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~
    /root/repos/wazuh/src/unit_tests/wazuh_db/test_wdb_integrity.c:129:27: note: referencing argument 3 of type ‘char *’
    In file included from /root/repos/wazuh/src/unit_tests/wazuh_db/test_wdb_integrity.c:17:
    /root/repos/wazuh/src/headers/../wazuh_db/wdb.h:1460:5: note: in a call to function ‘wdbi_checksum’
     1460 | int wdbi_checksum(wdb_t * wdb, wdb_component_t component, os_sha1 hexdigest);
     
     
      21%] Building C object analysisd/CMakeFiles/test_mitre.dir/test_mitre.c.o
    /root/repos/wazuh/src/unit_tests/wazuh_db/test_wdb_syscollector.c:2203:9: warning: ‘wdb_osinfo_insert’ accessing 41 bytes in a region of size 10 [-Wstringop-overflow=]
     2203 |         wdb_osinfo_insert(data, "scan_id", "scan_time", "hostname", "architecture", "os_name", "os_version",
          |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     2204 |                           "os_codename", "os_major", "os_minor", "os_patch", "os_build", "os_platform", "sysname",
          |                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     2205 |                           "release", "version", "os_release", "os_display_version", "checksum", false, "hexdigest", 1);
          |                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /root/repos/wazuh/src/unit_tests/wazuh_db/test_wdb_syscollector.c:2203:9: note: referencing argument 21 of type ‘char *’
    In file included from /root/repos/wazuh/src/unit_tests/wazuh_db/test_wdb_syscollector.c:10:
    /root/repos/wazuh/src/wazuh_db/wdb.h:751:5: note: in a call to function ‘wdb_osinfo_insert’
      751 | int wdb_osinfo_insert(wdb_t * wdb, const char * scan_id, const char * scan_time, const char * hostname, const char * architecture, const char * os_name, const char * os_version, const char * os_codename, const char * os_major, const char * os_minor, const char * os_patch, const char * os_build, const char * os_platform, const char * sysname, const char * release, const char * version, const char * os_release, const char * os_display_version, const char * checksum, const bool replace, os_sha1 hexdigest, int triaged);
          |     ^~~~~~~~~~~~~~~~~
    /root/repos/wazuh/src/unit_tests/wazuh_db/test_wdb_syscollector.c: In function ‘test_wdb_osinfo_insert_sql_fail’:
    /root/repos/wazuh/src/unit_tests/wazuh_db/test_wdb_syscollector.c:2280:9: warning: ‘wdb_osinfo_insert’ accessing 41 bytes in a region of size 10 [-Wstringop-overflow=]
     2280 |         wdb_osinfo_insert(data, "scan_id", "scan_time", "hostname", "architecture", "os_name", "os_version",
          |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     2281 |                           "os_codename", "os_major", "os_minor", "os_patch", "os_build", "os_platform", "sysname",
          |                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     2282 |                           "release", "version", "os_release", "os_display_version", "checksum", false, "hexdigest", 1);
          |                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /root/repos/wazuh/src/unit_tests/wazuh_db/test_wdb_syscollector.c:2280:9: note: referencing argument 21 of type ‘char *’
    In file included from /root/repos/wazuh/src/unit_tests/wazuh_db/test_wdb_syscollector.c:10:
    /root/repos/wazuh/src/wazuh_db/wdb.h:751:5: note: in a call to function ‘wdb_osinfo_insert’
      751 | int wdb_osinfo_insert(wdb_t * wdb, const char * scan_id, const char * scan_time, const char * hostname, const char * architecture, const char * os_name, const char * os_version, const char * os_codename, const char * os_major, const char * os_minor, const char * os_patch, const char * os_build, const char * os_platform, const char * sysname, const char * release, const char * version, const char * os_release, const char * os_display_version, const char * checksum, const bool replace, os_sha1 hexdigest, int triaged);
          |     ^~~~~~~~~~~~~~~~~
    Scanning dependencies of target test_logtest-config
    Scanning dependencies of target test_log
    /root/repos/wazuh/src/unit_tests/wazuh_db/test_wdb_syscollector.c: In function ‘test_wdb_osinfo_insert_success’:
    /root/repos/wazuh/src/unit_tests/wazuh_db/test_wdb_syscollector.c:2354:9: warning: ‘wdb_osinfo_insert’ accessing 41 bytes in a region of size 10 [-Wstringop-overflow=]
     2354 |         wdb_osinfo_insert(data, "scan_id", "scan_time", "hostname", "architecture", "os_name", "os_version",
          |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     2355 |                           "os_codename", "os_major", "os_minor", "os_patch", "os_build", "os_platform", "sysname",
          |                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     2356 |                           "release", "version", "os_release", "os_display_version", "checksum", false, "hexdigest", 1);
          |                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /root/repos/wazuh/src/unit_tests/wazuh_db/test_wdb_syscollector.c:2354:9: note: referencing argument 21 of type ‘char *’
    In file included from /root/repos/wazuh/src/unit_tests/wazuh_db/test_wdb_syscollector.c:10:
    /root/repos/wazuh/src/wazuh_db/wdb.h:751:5: note: in a call to function ‘wdb_osinfo_insert’
      751 | int wdb_osinfo_insert(wdb_t * wdb, const char * scan_id, const char * scan_time, const char * hostname, const char * architecture, const char * os_name, const char * os_version, const char * os_codename, const char * os_major, const char * os_minor, const char * os_patch, const char * os_build, const char * os_platform, const char * sysname, const char * release, const char * version, const char * os_release, const char * os_display_version, const char * checksum, const bool replace, os_sha1 hexdigest, int triaged);
      
      /root/repos/wazuh/src/unit_tests/wazuh_db/test_wdb_global.c:886:16: warning: ‘wdb_global_get_groups_integrity’ accessing 41 bytes in a region of size 1 [-Wstringop-overflow=]
      886 |     j_result = wdb_global_get_groups_integrity(data->wdb, "");
          |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /root/repos/wazuh/src/unit_tests/wazuh_db/test_wdb_global.c:886:16: note: referencing argument 2 of type ‘char *’
    In file included from /root/repos/wazuh/src/unit_tests/wazuh_db/test_wdb_global.c:9:
    /root/repos/wazuh/src/wazuh_db/wdb.h:2036:8: note: in a call to function ‘wdb_global_get_groups_integrity’
     2036 | cJSON* wdb_global_get_groups_integrity(wdb_t *wdb, os_sha1 hash);
          |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /root/repos/wazuh/src/unit_tests/wazuh_db/test_wdb_global.c: In function ‘test_wdb_global_get_groups_integrity_synced’:
    /root/repos/wazuh/src/unit_tests/wazuh_db/test_wdb_global.c:906:16: warning: ‘wdb_global_get_groups_integrity’ accessing 41 bytes in a region of size 1 [-Wstringop-overflow=]
      906 |     j_result = wdb_global_get_groups_integrity(data->wdb, "");
          |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /root/repos/wazuh/src/unit_tests/wazuh_db/test_wdb_global.c:906:16: note: referencing argument 2 of type ‘char *’
    In file included from /root/repos/wazuh/src/unit_tests/wazuh_db/test_wdb_global.c:9:
    /root/repos/wazuh/src/wazuh_db/wdb.h:2036:8: note: in a call to function ‘wdb_global_get_groups_integrity’
     2036 | cJSON* wdb_global_get_groups_integrity(wdb_t *wdb, os_sha1 hash);
          |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
</details>

## Tests

- Compilation without warnings in every supported platform
  - [ ] Linux
  - [ ] Windows
  - [ ] MAC OS X
- [ ] Source installation
- [ ] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [x] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

- [ ] Retrocompatibility with older Wazuh versions
- [ ] Working on cluster environments
- [ ] Configuration on demand reports new parameters
- [ ] The data flow works as expected (agent-manager-api-app)
- [ ] Added unit tests (for new features)
- [ ] Stress test for affected components

- Decoder/Rule tests
  - [ ] Added unit testing files ".ini"
  - [ ] runtests.py executed without errors

### CODE REVIEW

File: src/wazuh_db/wdb_delta_event.c [hunk 1]
```diff
@@ -86,6 +88,7 @@ bool wdb_insert_dbsync(wdb_t * wdb, struct kv const *kv_value, const char *data)
 
 bool wdb_modify_dbsync(wdb_t * wdb, struct kv const *kv_value, const char *data)
 {
+    const char * treat_as_null[] = {"", NULL};
```
Comment (HanesSciarrone) [inline src/wazuh_db/wdb_delta_event.c:91]: Is there a possibility that this variable has to be assigned with the same values as L35?

Comment (jnasselle) [reply src/wazuh_db/wdb_delta_event.c:91]: Nope. L35 cause that "NULL" or "" will be replaced to db's null elements during insertions. Modified events use "NULL" as mask (meaning the field was unchanged), but "" will indicate that a field was changed for some value to empty, and this need to be replaced by a db null

**Comment by jnasselle** [comment]
Active Response IT on Windows Agent are failing with the next message
```
============================= test session starts =============================
platform win32 -- Python 3.7.4, pytest-6.2.2, py-1.10.0, pluggy-0.13.0 -- C:\Python37\python.exe
cachedir: .pytest_cache
metadata: {'Python': '3.7.4', 'Platform': 'Windows-10-10.0.14393-SP0', 'Packages': {'pytest': '6.2.2', 'py': '1.10.0', 'pluggy': '0.13.0'}, 'Plugins': {'html': '3.1.1', 'metadata': '1.8.0', 'testinfra
': '5.0.0'}}
rootdir: C:\tmp\Test_integration_B28170_20220628015800\tests\integration, configfile: pytest.ini
plugins: html-3.1.1, metadata-1.8.0, testinfra-5.0.0
collecting ... collected 10 items / 8 deselected / 2 selected

test_active_response/test_execd/test_execd_restart.py::test_execd_restart[get_configuration0] FAILED [ 50%]
test_active_response/test_execd/test_execd_restart.py::test_execd_restart[get_configuration1] PASSED [100%]

================================== FAILURES ===================================
___________________ test_execd_restart[get_configuration0] ____________________
test_active_response\test_execd\test_execd_restart.py:248: in test_execd_restart
    ossec_log_monitor.start(timeout=60, callback=wait_shutdown_message_line)
C:\Python37\lib\site-packages\wazuh_testing-4.3.0-py3.7.egg\wazuh_testing\tools\monitoring.py:203: in start
    error_message=error_message).result()
C:\Python37\lib\site-packages\wazuh_testing-4.3.0-py3.7.egg\wazuh_testing\tools\monitoring.py:469: in start
    raise TimeoutError(error_message)
E   TimeoutError
---------------------------- Captured stdout setup ----------------------------


The Wazuh service was started successfully.



---------------------------- Captured stderr setup ----------------------------
2022/06/28 01:15:40 agent-auth: INFO: Started (pid: 3308).


2022/06/28 01:15:40 agent-auth: INFO: Requesting a key from server: 127.0.0.1


2022/06/28 01:15:40 agent-auth: INFO: No authentication password provided


2022/06/28 01:15:40 agent-auth: INFO: Using agent name as: EC2AMAZ-NRK2S46


2022/06/28 01:15:40 agent-auth: INFO: Waiting for server reply


2022/06/28 01:15:40 agent-auth: INFO: Valid key received


============================== warnings summary ===============================
..\..\..\..\Python37\lib\site-packages\win32\lib\pywintypes.py:2
  C:\Python37\lib\site-packages\win32\lib\pywintypes.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp, sys, os

-- Docs: https://docs.pytest.org/en/stable/warnings.html
- generated html file: file://C:\tmp\Test_integration_B28170_20220628015800\report.html -
=========================== short test summary info ===========================
FAILED test_active_response/test_execd/test_execd_restart.py::test_execd_restart[get_configuration0]
======= 1 failed, 1 passed, 8 deselected, 1 warning in 82.41s (0:01:22) =======
```
Related issue https://github.com/wazuh/wazuh-qa/issues/2769

**Review by Dwordcito — APPROVED** [review]
