### PR TITLE
Fix for rolling OS versions on WPK upgrade

### LINKED ISSUE #12301: Failed to upgrade openSUSE agent v4.3 to v4.3 via WPK upgrade
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.0-rc4 | WPK upgrade | Agent | WPK | openSUSE Tumbleweed |

## Description

Hi team,

On a Wazuh agent version 4.3.0, when an `Agent's upgrade is performed via WPK upgrade`, the manager always fails to run the WPK file and try to upgrade the agent. This always happens at the start of the run and only when trying to upgrade from version **4.3 to** the same version **4.3** via _WPK_.

The **_error_** that appears after failing is the following:

```python
Agent information not found in database
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/concurrent/futures/process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.0-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 242, in run_local
    data = f(**f_kwargs)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.0-py3.9.egg/wazuh/rbac/decorators.py", line 420, in wrapper
    result = func(*args, **kwargs) if not skip_execution else None
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.0-py3.9.egg/wazuh/agent.py", line 982, in upgrade_agents
    raise WazuhInternalError(error_code, cmd_error=True, extra_message=agent_result['message'])
wazuh.core.exception.WazuhInternalError: Error 1816 - Agent information not found in database
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.0-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 287, in execute_local_request
    data = await asyncio.wait_for(task, timeout=timeout)
  File "/var/ossec/framework/python/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
    return await fut
wazuh.core.exception.WazuhInternalError: Error 1816 - Agent information not found in database
Internal error: 
Traceback (most recent call last):
  File "/var/ossec/framework/scripts/agent_upgrade.py", line 220, in <module>
    main()
  File "/var/ossec/framework/scripts/agent_upgrade.py", line 186, in main
    result = send_command(function=upgrade_agents, command=create_command())
  File "/var/ossec/framework/scripts/agent_upgrade.py", line 115, in send_command
    return raise_if_exc(pool.submit(run, dapi.distribute_function()).result())
  File "/var/ossec/framework/python/lib/python3.9/site-packages/api-4.3.0-py3.9.egg/api/util.py", line 293, in raise_if_exc
    _create_problem(obj)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/api-4.3.0-py3.9.egg/api/util.py", line 263, in _create_problem
    raise ProblemException(status=500 if not code else code, type=exc.type, title=exc.title, detail=exc.message,
connexion.exceptions.ProblemException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/ossec/framework/scripts/agent_upgrade.py", line 227, in <module>
    if args.debug:
AttributeError: 'Namespace' object has no attribute 'debug'
```

Upgrades in other versions work fine (https://github.com/wazuh/wazuh/issues/12210#issuecomment-1039356061), so it seems to be due to a recent change that only affects openSUSE agents.

Best regards,
Marcel

### PR DESCRIPTION
**Pull request by MarcelKemp**
|Related issue|
|---|
|Closes #12301|

## Description

After the changes made in https://github.com/wazuh/wazuh/pull/11207 to correctly display the `OS name` and `version`, _`NULL`_ was assigned to the version of the OS that was type `rolling`, causing the failure when trying to obtain it in the following condition:
https://github.com/wazuh/wazuh/blob/700b0c9bcff6346f1afb4ca86eb304868ea43e61/src/wazuh_modules/agent_upgrade/manager/wm_agent_upgrade_validate.c#L58

To fix this problem, a whitelist with OSs with a `rolling` version, such as **_openSUSE tumbleweed_** and **_Arch Linux_**, has been added so that it no longer causes any failure when trying to upgrade the agent via WPK.

## Logs/Alerts example

```
# /var/ossec/bin/agent_upgrade -a 003 -f wazuh_agent_v4.3.0_linux_x86_64.wpk -x upgrade.sh

Upgrading...

Upgraded agents:
	Agent 003 upgraded: Wazuh v4.3.0 -> Wazuh v4.3.0
```

## Tests

- Compilation without warnings in every supported platform
  - [x] Linux
- [x] Source installation
- [x] Package installation
- [x] Source upgrade
- [x] Package upgrade
- [x] Review logs syntax and correct language

- Memory tests for Linux
  - [x] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] AddressSanitizer

- [x] The data flow works as expected (agent-manager-api-app)
- [x] Added unit tests (for `wm_agent_upgrade_validate_system`)
 - `100% tests passed, 0 tests failed out of 138` and 100% coverage
- [ ] Stress test for affected components

---
# TEST: openSUSE Tumbleweed

### :green_circle: UPGRADE FAIL  

- [x] The wazuh home backup is restored correctly (no traces of the installation, but only the `.tar.gz` backup and the logs).
- [x] The permissions and owners of the following directories did NOT change:
      - `/`
      - `/var`
      - `/usr`, `/usr/lib/`, `/usr/lib/systemd/`, `/usr/lib/systemd/system/`
      - `/etc`, `/etc/systemd/`, `/etc/systemd/system/`, `/etc/rc.d`, `/etc/initd.d/`, `/etc/initd.d/rc.d/`
- [x] ~Wazuh service runs wazuh-control (`systemctl cat wazuh-agent.service`)~
- [x] Wazuh service runs ossec-control (`systemctl cat wazuh-agent.service`)
- [x] The service was enabled (`systemctl is-enabled wazuh-agent.service`)
- [x] ~Init file runs wazuh-control (`cat /etc/rc.d/init.d/wazuh-agent`)~
- [x] Init file runs ossec-control (`cat /etc/rc.d/init.d/wazuh-agent`)
- [x] ~Wazuh as service is enabled `chkconfig --list`~ 
- [x] Wazuh starts and connects when the backup is restored (`cat /var/ossec/var/run/ossec-agentd.state`)
- [x] Wazuh starts and connects automatically when the system is rebooted.
- [x] Restore SELinux policies (`semodule -l | grep -i wazuh`) (DISABLED)

### :green_circle: UPGRADE OK

- [x] Upgrade is performed successfully (agent connects to the manager after upgrading)
- [x] Service starts automatically after rebooting
- [x] Agent connects to the manager after rebooting

[Download report 4.3](https://github.com/wazuh/wazuh/files/8118461/4.3.zip)

### CODE REVIEW

File: src/wazuh_modules/agent_upgrade/manager/wm_agent_upgrade_validate.c [hunk 1]
```diff
@@ -51,16 +56,18 @@ int wm_agent_upgrade_validate_status(const char* connection_status) {
...
 
     if (platform) {
         if (!strcmp(platform, "windows") || (os_major && arch && (strcmp(platform, "ubuntu") || os_minor))) {
             return_code = WM_UPGRADE_SUCCESS;
-            invalid_platforms_len = sizeof(invalid_platforms) / sizeof(invalid_platforms[0]);
 
-            for(invalid_platforms_it = 0; invalid_platforms_it < invalid_platforms_len; ++invalid_platforms_it) {
-                if(!strcmp(invalid_platforms[invalid_platforms_it], platform)) {
+            // Blacklist for invalid OS platforms
+            invalid_platforms_len = sizeof(invalid_platforms) / sizeof(invalid_platforms[0]);
```
Comment (chemamartinez) [inline src/wazuh_modules/agent_upgrade/manager/wm_agent_upgrade_validate.c:68]: Here you can use https://github.com/wazuh/wazuh/blob/959fe420af99e26b30d03bb5b1a7b9bed5815670/src/headers/shared.h#L206

File: src/wazuh_modules/agent_upgrade/manager/wm_agent_upgrade_validate.c [hunk 2]
```diff
@@ -74,6 +81,15 @@ int wm_agent_upgrade_validate_system(const char *platform, const char *os_major,
                 }
             }
         }
+
+        // Whitelist for OS platforms with 'rolling' version
+        rolling_platforms_len = sizeof(rolling_platforms) / sizeof(rolling_platforms[0]);
```
Comment (chemamartinez) [inline src/wazuh_modules/agent_upgrade/manager/wm_agent_upgrade_validate.c:86]: Same

**Review by chemamartinez — APPROVED** [review]

**Review by vikman90 — APPROVED** [review]
