### PR TITLE
vulnerability scanner module dump function fixed

### LINKED ISSUE #20002: Response error from socket /var/ossec/queue/sockets/wmodules
# Description

During the development of #18284 working with the branch [dev-14153-vulndet-refactor](https://github.com/wazuh/wazuh/tree/dev-14153-vulndet-refactor), we found an error communicating with the socket `/var/ossec/queue/sockets/wmodules` using the API endpoint `/cluster/master-node/configuration/wmodules/wmodules`.

When the server started the first time and we tried a request we got 

```
➜  ~ curl -k --silent -H  "Authorization: Bearer $TOKEN" https://localhost:55050/cluster/master-node/configuration/wmodules/wmodules | jq
{
  "title": "Wazuh Internal Error",
  "detail": "Could not request component configuration: Data could not be received",
  "dapi_errors": {
    "master-node": {
      "error": "Could not request component configuration: Data could not be received",
      "logfile": "WAZUH_HOME/logs/api.log"
    }
  },
  "error": 1118
}
```

But, in a second request, the socket doesn't respond anymore causing a timeout in API.

```
➜  ~ curl -k --silent -H  "Authorization: Bearer $TOKEN" https://localhost:55050/cluster/master-node/configuration/wmodules/wmodules | jq
{
  "title": "Wazuh Internal Error",
  "detail": "Timeout executing API request",
  "dapi_errors": {
    "master-node": {
      "error": "Timeout executing API request",
      "logfile": "WAZUH_HOME/logs/api.log"
    }
  },
  "error": 3021
}
```

Also, the socket is only returning one part of the message, the `ok`. Causing an error in

https://github.com/wazuh/wazuh/blob/9ff5c6f80e3da0d04b68cf19fec8e6f6043f9adf/framework/wazuh/core/configuration.py#L1159

Which expects two parts.

I we send the message (`getconfig wmodules`) directly to the socket we got

```
root@wazuh-master:/var/ossec# ./get_active_config.py 000 wmodules wmodules
Sending "getconfig wmodules" command to "/var/ossec/queue/sockets/wmodules" socket.

Response:
['ok']
```

### PR DESCRIPTION
**Pull request by matias-braida**
|Related issue|
|---|
|Closes #20002|

## Description

This PR fixes the JSON returned by the function "wm_vulnerability_scanner_dump".
Also, the configuration JSON was modified to fix this bug.

## Tests

API request was successfully done:
image

- Compilation without warnings in every supported platform
  - [x] Linux
- [x] run API request successfully

### CODE REVIEW

**Review by MiguelazoDS — COMMENTED** [review]
GJ!
On the target branch, the request does not provide a response


On the development branch, the request succeeds. 
image

File: src/wazuh_modules/wm_vulnerability_scanner.c [hunk 1]
```diff
@@ -57,7 +57,16 @@ void* wm_vulnerability_scanner_main(wm_vulnerability_scanner_t * data)
 
         if (vulnerability_scanner_start_ptr)
         {
-            cJSON * config_json = wm_vulnerability_scanner_dump(data);
+            cJSON *config_json = cJSON_CreateObject();
+            cJSON_AddItemToObject(config_json, "vulnerability-detection", cJSON_Duplicate(data->vulnerability_detection, TRUE));
```
Comment (MiguelazoDS) [inline src/wazuh_modules/wm_vulnerability_scanner.c:61]: Couldn't we do this? 
`cJSON *config_json = wm_vulnerability_scanner_dump(data);`

Comment (Dwordcito) [reply src/wazuh_modules/wm_vulnerability_scanner.c:61]: @matias-braida  ping pring

Comment (matias-braida) [reply src/wazuh_modules/wm_vulnerability_scanner.c:61]: I did this way to keep building the cJSON config_json object explicitly

**Review by MiguelazoDS — APPROVED** [review]
