### PR TITLE
Fix verify-agent-conf for MacOS ULS

### LINKED ISSUE #12903: Verify-agent-conf tool considers macOS logformat as invalid
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.0-40307 | verify-agent-conf | Manager| Packages/Sources | Ubuntu 18.04 |

The localfile option `macos` introduced in Wazuh 4.3 should be considered valid. Details: 

```
root@agentUbuntu18:/home/vagrant# cat /var/ossec/etc/shared/default/agent.conf 
<agent_config>

  <!-- Shared agent configuration here -->
<localfile>
  <location>macos</location>
  <log_format>macos</log_format>
  <query type="activity,trace" level="info">process == "sshd" OR message CONTAINS "invalid"</query>
</localfile>

</agent_config>
root@agentUbuntu18:/home/vagrant# /var/ossec/bin/verify-agent-conf 

verify-agent-conf: Verifying [etc/shared/default/agent.conf]
2022/03/29 12:29:22 verify-agent-conf: ERROR: (1235): Invalid value for element 'log_format': macos.
2022/03/29 12:29:22 verify-agent-conf: ERROR: (1202): Configuration error at 'etc/shared/default/agent.conf'.
2022/03/29 12:29:22 verify-agent-conf: ERROR: (1207): Localfile remote configuration in 'etc/shared/default/agent.conf' is corrupted.
```
Regards,
Elwali

### LINKED ISSUE #12904: Precedence/Multigroup it is not applied for macos localfile configuration
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.0-40307 | Wazuh-logcollector & Wazuh-agentd | Agent | Packages/Sources | macOS 10.4 |

Wazuh agent reports more than one `macos` Localfile configuration as an error where it should be considered as valid and applies the precedence. 

- **Scenario 1** (high probable): users tend to use multiple groups and adding the configuration in various groups will trigger the error: 

image
image

-  **Scenario 2**: the user would add the configuration to the `ossec.conf` and push it as well through a group: 

image

Please note that the respective documentation does not mention that only one block should be used. however, keeping only a warning message about the duplicated (although one of them has a query) and applying the precedence would be the expected behavior. 

Regards,
Elwali

### PR DESCRIPTION
**Pull request by juliancnn**
|Related issue|
|---|
|Closes #12903|
|Closes #12904|
|Closes https://github.com/wazuh/wazuh-kibana-app/issues/3921|

# Description

Currently, Logcollector's `localfile` blocks with `macos` as log_format were ONLY allowed in macOS systems because is an OS-dependant feature.

```
<localfile>
  <location>macos</location>
  <log_format>macos</log_format>
  <query type="activity,trace" level="info">process == "sshd" OR message CONTAINS "invalid"</query>
</localfile>
```

The problem appears during Centralized Configuration deployment, validating those `localfile`s blocks in the Manager (Linux) before sharing it to configured agents, failing due previously mentioned OS restriction. `verify-agent-conf` tool shows the next error 
```
# /var/ossec/bin/verify-agent-conf 

verify-agent-conf: Verifying [etc/shared/default/agent.conf]
2022/03/29 12:29:22 verify-agent-conf: ERROR: (1235): Invalid value for element 'log_format': macos.
2022/03/29 12:29:22 verify-agent-conf: ERROR: (1202): Configuration error at 'etc/shared/default/agent.conf'.
2022/03/29 12:29:22 verify-agent-conf: ERROR: (1207): Localfile remote configuration in 'etc/shared/default/agent.conf' is corrupted
```
# Proposal

To solve this the configuration is accepted during the load configuration step but ignored during operation step. The same approach was taken with Evenchannel and Eventlog localfiles, 

As with eventchannel, it will be accepted in the configuration and will be returned by the API.

## Manager:

```xml
# cat /var/ossec/etc/shared/default/agent.conf
<agent_config>

  <!-- Shared agent configuration here -->
    <localfile>
    <location>macos</location>
    <log_format>macos</log_format>
    <query type="activity,trace" level="info">process == "sshd" OR message CONTAINS "third"</query>
    </localfile>

</agent_config>
```

#### verify-agent-conf
```
# /var/ossec/bin/verify-agent-conf

verify-agent-conf: Verifying [etc/shared/default/agent.conf]
verify-agent-conf: OK
```

## Agent config

```xml
<localfile>
    <log_format>syslog</log_format>
    <location>/var/log/kern.log</location>
</localfile>

<localfile>
  <location>macos</location>
  <log_format>macos</log_format>
  <query type="activity,trace" level="info">process == "sshd" OR message CONTAINS "first"</query>
</localfile>

<localfile>
  <location>macos</location>
  <log_format>macos</log_format>
  <query type="activity,trace" level="info">process == "sshd" OR message CONTAINS "second"</query>
</localfile>

<localfile>
    <location>Microsoft-Windows-PrintService/Operational</location>
    <log_format>eventchannel</log_format>
</localfile>

```
#### Logcollector logs:
```
# /var/ossec/bin/wazuh-logcollector -f
2022/04/05 14:46:04 wazuh-logcollector: INFO: (9201): 'macos' log_format is only supported in macOS.
2022/04/05 14:46:05 wazuh-logcollector: INFO: (9201): 'macos' log_format is only supported in macOS.
2022/04/05 14:46:05 wazuh-logcollector: INFO: (1950): Analyzing file: '/var/log/kern.log'.
2022/04/05 14:46:05 wazuh-logcollector: WARNING: (1958): Log file 'macos' is duplicated.
2022/04/05 14:46:05 wazuh-logcollector: WARNING: (1958): Log file 'macos' is duplicated.
2022/04/05 14:46:05 wazuh-logcollector: INFO: Started (pid: 192005).

```

#### API response:

```json
╰─# go run /_shared/go_scripts/wazuh_sock.go -f /var/ossec/queue/sockets/logcollector -m "getconfig localfile"
Response: ok {
    "localfile": [
        {
            "file": "/var/log/kern.log",
            "logformat": "syslog",
            "ignore_binaries": "no",
            "only-future-events": "yes",
            "target": [
                "agent"
            ]
        },
        {
            "logformat": "eventchannel",
            "ignore_binaries": "no",
            "only-future-events": "yes",
            "target": [
                "agent"
            ],
            "reconnect_time": 5
        },
        {
            "logformat": "macos",
            "query": {
                "value": "process == \"sshd\" OR message CONTAINS \"third\"",
                "level": "info",
                "type": [
                    "activity",
                    "trace"
                ]
            },
            "ignore_binaries": "no",
            "only-future-events": "yes",
            "target": [
                "agent"
            ]
        }
    ]
}
```

#### API response:
```json
# go run /_shared/go_scripts/wazuh_sock.go -f /var/ossec/queue/sockets/request  -m "005 logcollector getconfig localfile"
Response: ok {
    "localfile": [
        {
            "channel": "Application",
            "logformat": "eventchannel",
            "ignore_binaries": "no",
            "only-future-events": "yes",
            "target": [
                "agent"
            ],
            "reconnect_time": 5
        },
        {
            "channel": "Security",
            "logformat": "eventchannel",
            "query": {
                "value": "Event/System[EventID != 5145 and EventID != 5156 and EventID != 5447 and\n      EventID != 4656 and EventID != 4658 and EventID != 4663 and EventID != 4660 and\n      EventID != 4670 and EventID != 4690 and EventID != 4703 and EventID != 4907 and\n      EventID != 5152 and EventID != 5157]"
            },
            "ignore_binaries": "no",
            "only-future-events": "yes",
            "target": [
                "agent"
            ],
            "reconnect_time": 5
        },
        {
            "channel": "System",
            "logformat": "eventchannel",
            "ignore_binaries": "no",
            "only-future-events": "yes",
            "target": [
                "agent"
            ],
            "reconnect_time": 5
        },
        {
            "file": "active-response\\active-responses.log",
            "logformat": "syslog",
            "ignore_binaries": "no",
            "only-future-events": "yes",
            "target": [
                "agent"
            ]
        },
        {
            "logformat": "macos",
            "query": {
                "value": "process == \"sshd\" OR message CONTAINS \"thrid\"",
                "level": "info",
                "type": [
                    "activity",
                    "trace"
                ]
            },
            "ignore_binaries": "no",
            "only-future-events": "yes",
            "target": [
                "agent"
            ]
        }
    ]
}
```

#### Logs:
```
...
2022/04/05 22:56:31 wazuh-agent: INFO: (9201): 'macos' log_format is only supported in macOS.
2022/04/05 22:56:31 wazuh-agent: INFO: (9201): 'macos' log_format is only supported in macOS.
....
2022/04/05 22:56:31 wazuh-agent: WARNING: (1958): Log file 'macos' is duplicated.
```

#### API response:
```json
# go run /_shared/go_scripts/wazuh_sock.go -f /var/ossec/queue/sockets/request  -m "007 logcollector getconfig localfile"                            Response: ok {
    "localfile": [
        {
            "logformat": "full_command",
            "command": "netstat -an | grep -e \"tcp\" -e \"udp\" | sed -E 's/([[:alnum:]]*)\\ *[[:digit:]]*\\ *[[:digit:]]*\\ *(.*)\\.([0-9\\*]*)\\ +([0-9\\.\\*]+).+/\\1 \\2 == \\3 == \\4/' | sort -k 4 -g | sed 's/ == \\(.*\\) ==/.\\1/'| uniq",
            "alias": "netstat listening ports",
            "ignore_binaries": "no",
            "target": [
                "agent"
            ],
            "frequency": 360
        },
        {
            "logformat": "macos",
            "query": {
                "value": "process == \"sshd\" OR message CONTAINS \"thrid\"",
                "level": "info",
                "type": [
                    "activity",
                    "trace"
                ]
            },
            "ignore_binaries": "no",
            "only-future-events": "yes",
            "target": [
                "agent"
            ]
        }
    ]
}
```

#### Logcollector logs
```
sh-3.2# tail -f /Library/Ossec/logs/ossec.log | grep logcollector
2022/04/05 16:23:58 wazuh-logcollector: INFO: (1225): SIGNAL [(15)-(Terminated: 15)] Received. Exit Cleaning...
2022/04/05 16:24:02 wazuh-logcollector: INFO: Monitoring full output of command(360): netstat -an | grep -e "tcp" -e "udp" | sed -E 's/([[:alnum:]]*)\ *[[:digit:]]*\ *[[:digit:]]*\ *(.*)\.([0-9\*]*)\ +([0-9\.\*]+).+/\1 \2 == \3 == \4/' | sort -k 4 -g | sed 's/ == \(.*\) ==/.\1/'| uniq
2022/04/05 16:24:02 wazuh-logcollector: WARNING: (1958): Log file 'macos' is duplicated.
2022/04/05 16:24:02 wazuh-logcollector: WARNING: (1958): Log file 'macos' is duplicated.
2022/04/05 16:24:02 wazuh-logcollector: INFO: (1604): Monitoring macOS logs with: /usr/bin/log stream --style syslog --type activity --type trace --level info --predicate process == "sshd" OR message CONTAINS "thrid".
2022/04/05 16:24:02 wazuh-logcollector: INFO: Started (pid: 11082).

```

#### Linux
[Scanbuild report](https://github.com/wazuh/wazuh/files/8421926/scan-build-2022-04-05-211333-91472-1.zip)
[Valgrind report](https://github.com/wazuh/wazuh/files/8421927/ValgrindPRs.log)
#### Macos

- Compilation without warnings in every supported platform
  - [x] Linux
  - [x] Windows
  - [x] MAC OS X
- [x] Source installation
- [x] Package installation
- [x] Source upgrade
- [x] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [x] Scan-build report
  - [x] Coverity
  - [x] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

- [x] Retrocompatibility with older Wazuh versions
- [ ] Working on cluster environments
- [x] Configuration on demand reports new parameters
- [ ] The data flow works as expected (agent-manager-api-app)
- [ ] Added unit tests (for new features)
- [ ] Stress test for affected components

- Decoder/Rule tests
  - [ ] Added unit testing files ".ini"
  - [ ] runtests.py executed without errors

### CODE REVIEW

**Review by JcabreraC — APPROVED** [review]
LGTM !

**Comment by juliancnn** [comment]
LGTM! :rocket: :rocket: :rocket:

File: src/error_messages/information_messages.h [hunk 1]
```diff
@@ -71,5 +71,6 @@
 
 /* Logcollector info messages */
 #define LOGCOLLECTOR_INVALID_HANDLE_VALUE   "(9200): File '%s' can not be handled."
+#define LOGCOLLECTOR_ONLY_MACOS             "(9201): 'macos' log_format is only supported in macOS."
```
Comment (vikman90) [inline src/error_messages/information_messages.h:74]:
```suggestion
#define LOGCOLLECTOR_ONLY_MACOS             "(9201): 'macos' log format is only supported on macOS."
```

**Review by vikman90 — CHANGES_REQUESTED** [review]
GJ @juliancnn!

In addition to the suggestion above, I wonder if we should let every platform accept the configuration. I mean remove the `#ifdef` guard at _localfile-config.c_ so that every version of the agent applies the `localfile` stanza and log that the log format will be discarded (except on macOS, of course).

**Comment by juliancnn** [comment]
> GJ @juliancnn!
> 
> In addition to the suggestion below, I wonder if we should let every platform accept the configuration. I mean remove the `#ifdef` guard at _localfile-config.c_ so that every version of the agent applies the `localfile` stanza and log that the log format will be discarded (except on macOS, of course).

Thank you vik!

The mesagges "(9201): 'macos' log format is only supported on macOS" message is logged by all non-MacOS platforms and is defined in the `else` here:

https://github.com/wazuh/wazuh/blob/455dd82625e735e47fe2cd7e59bbac42253d85aa/src/logcollector/logcollector.c#L352-L370

**Review by vikman90 — APPROVED** [review]
