### PR TITLE
Fix FIM ID hash

### LINKED ISSUE #29500: No entry appears in the index when modifying a file monitored by FIM
## Description

During the development of the Global Queries tests at https://github.com/wazuh/wazuh-qa-automation/issues/1441, it was found that no entry is stored in the index after modifying a file monitored by FIM.

The flow of the test in question is as follows: a new file is created on the system (`/etc/test_file.txt`) and waits to be scanned and indexed in the index. Then, the file is modified by renaming it (`/etc/modified_test_file.txt`) and waiting for it to be scanned again, and the change to be reflected in the index. After waiting long enough, this file does not appear in the index.

It should be noted that the modified file is found in the database, but not in the index.

This occurs on Centos 7 x86_64, Centos 7 arm64, Ubuntu 22 x86_64, and Ubuntu 22 arm64.

The tests have been executed using packages updated on 2025-04-30 from the `dev/fim-syscollector-global-queries` branch.

### Steps to reproduce

1. Create a new file in a monitored directory by FIM.
2. Wait until the next regular scan is executed and the new file is indexed in the `wazuh-states-files-wazuh` index.
3. Rename the monitored file.
4. Wait for the next regular scan and for the renaming to be reflected in the index.

### Current result

The change is not reflected in the index, and no entry appears, neither for the old file nor for the new one (the renamed one).

### Expected result

The renamed file should appear in the index.

### Evidences

Test result: [Report.zip](https://github.com/user-attachments/files/20038787/ReportRegistriesConsistency.zip)

In this report it can be seen how the `modify_file` test fails because the index does not match the expected result. In the evidence `files_expected_vs_found` it can be seen how the index is expected to contain the entry `/etc/modifed_test_test_file.txt` but this is not in the index, in the agents with the operating systems commented before.

The tests have been executed with the syscheck debug mode activated. The logs can also be found in the evidences.

### PR DESCRIPTION
**Pull request by pereyra-m**
|Related issue|
|---|
|Closes #29500 |

## Description

This PR modifies the `fimContext` to hash the path for files instead of the index.

## Tests

The tests were re-run with the last changes.

### Linux agent manual test

I connected a Wazuh v4.11.2 Ubuntu agent to a manager with the development branch installed by sources, and configured the `indexer-connector` to a Wazuh Indexer deployed with Docker.

#### DBSync :green_circle: 

I set a low interval for the `syscheck` scan and performed the following actions:
- Create a file: `nano /home/ubuntu/test/the_file`
- Change the name of the file: `mv /home/ubuntu/test/the_file /home/ubuntu/test/modify_the_file`

In both cases waited for the scan to complete.
First file:

<details><summary>Details</summary>
<p>

```
2025/05/07 00:07:08 logger-helper[221485] upsertElement.hpp:59 at handleRequest(): DEBUG: UpsertFimElement::build: {"id":"001_a98ae5d4fd888146c051733d4459431dadd3019f5e38c1468960d28de413534d","operation":"INSERTED","data":{"file":{"path":"/home/ubuntu/test/the_file","gid":"0","group":"root","mtime":"2025-05-07T00:06:59.000Z","size":0,"uid":"0","owner":"root","hash":{"md5":"d41d8cd98f00b204e9800998ecf8427e","sha1":"da39a3ee5e6b4b0d3255bfef95601890afd80709","sha256":"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"}},"agent":{"id":"001","name":"fe94358f3c04","version":"v4.11.2"},"wazuh":{"schema":{"version":"1.0"}}}}
```

image

</p>
</details> 

Modified file:

<details><summary>Details</summary>
<p>

```
2025/05/07 00:08:49 logger-helper[221485] upsertElement.hpp:59 at handleRequest(): DEBUG: UpsertFimElement::build: {"id":"001_ba7a65c2482acc8bc2ca7d7a08f7c130b631b7b6b14b1783d77858c017b855ba","operation":"INSERTED","data":{"file":{"path":"/home/ubuntu/test/modify_the_file","gid":"0","group":"root","mtime":"2025-05-07T00:06:59.000Z","size":0,"uid":"0","owner":"root","hash":{"md5":"d41d8cd98f00b204e9800998ecf8427e","sha1":"da39a3ee5e6b4b0d3255bfef95601890afd80709","sha256":"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"}},"agent":{"id":"001","name":"fe94358f3c04","version":"v4.11.2"},"wazuh":{"schema":{"version":"1.0"}}}}

2025/05/07 00:08:50 logger-helper[221485] deleteElement.hpp:58 at handleRequest(): DEBUG: DeleteFimElement::build: {"id":"001_a98ae5d4fd888146c051733d4459431dadd3019f5e38c1468960d28de413534d","operation":"DELETED"}
```

image

</p>
</details> 

Then, after this test I removed the file to start again.

#### RSync :red_circle: 

Related issue:
- https://github.com/wazuh/wazuh/issues/29527

I set a lower scan frequency and perform a restart for every change. This forces RSync to pair the DBs instead of using deltas.

I've added some temporary WARNING messages

<details><summary>Details</summary>
<p>

```
2025/05/07 00:12:20 wazuh-remoted: WARNING: Message forwarded: '{"agent_info":{"agent_id":"001","agent_ip":"any","agent_name":"fe94358f3c04","agent_version":"v4.11.2"},"data_type":"state","data":{"attributes_type":"fim_file","attributes":{"attributes":"","checksum":"c3dd77a0b9d01bb729ea98950ffb17e6c8581ab3","gid":"0","group_name":"root","hash_md5":"d41d8cd98f00b204e9800998ecf8427e","hash_sha1":"da39a3ee5e6b4b0d3255bfef95601890afd80709","hash_sha256":"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855","inode":40239713,"mtime":1746576732,"perm":"rw-r--r--","size":0,"type":"file","uid":"0","user_name":"root"},"index":"/home/ubuntu/test/the_file","timestamp":1746576738}}'

2025/05/07 00:12:20 logger-helper[221485] upsertElement.hpp:59 at handleRequest(): DEBUG: UpsertFimElement::build: {"id":"001_a98ae5d4fd888146c051733d4459431dadd3019f5e38c1468960d28de413534d","operation":"INSERTED","data":{"file":{"path":"/home/ubuntu/test/the_file","gid":"0","group":"root","mtime":"2025-05-07T00:12:12.000Z","size":0,"uid":"0","owner":"root","hash":{"md5":"d41d8cd98f00b204e9800998ecf8427e","sha1":"da39a3ee5e6b4b0d3255bfef95601890afd80709","sha256":"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"}},"agent":{"id":"001","name":"fe94358f3c04","version":"v4.11.2"},"wazuh":{"schema":{"version":"1.0"}}}}
```

image

</p>
</details> 

Now, I stop the agent, change the file and restart.
I see the `integrity_check_global` message, but the RSync mechanism doesn't work

<details><summary>Details</summary>
<p>

```
2025/05/07 00:15:27 wazuh-db[221135] wdb_parser.c:263 at wdb_parse(): DEBUG: Agent 001 query: fim_file integrity_check_global {"begin":"/bin","checksum":"83b2591774d77adf3c49e0500dd1815240c0b228","end":"/usr/sbin/zramctl","id":1746576927}
2025/05/07 00:15:27 wazuh-db[221135] wdb_integrity.c:610 at wdbi_query_checksum(): DEBUG: Agent '001' fim_file range checksum: Time: 0.308 ms.
2025/05/07 00:15:27 wazuh-remoted: WARNING: Message forwarded: '{"agent_info":{"agent_id":"001","agent_ip":"any","agent_name":"fe94358f3c04","agent_version":"v4.11.2"},"data_type":"integrity_check_global","data":{"attributes_type":"fim_file","begin":"/bin","checksum":"83b2591774d77adf3c49e0500dd1815240c0b228","end":"/usr/sbin/zramctl","id":1746576927}}'
2025/05/07 00:15:27 logger-helper[221485] fimInventoryOrchestrator.hpp:41 at run(): DEBUG: FimInventoryOrchestrator::run for agent: '001', operation: '4', component: '0'
```

The manager DB doesn't have the new value

```
root@f8d4e01554db:/var/ossec# python3 /home/ubuntu/wdb-query.py 
agent 001 sql SELECT * FROM fim_entry WHERE full_path like '%the_file%'
[
    {
        "full_path": "/home/ubuntu/test/the_file",
        "file": "/home/ubuntu/test/the_file",
        "type": "file",
        "date": 1746576738,
        "changes": 1,
        "size": 0,
        "perm": "rw-r--r--",
        "uid": "0",
        "gid": "0",
        "md5": "d41d8cd98f00b204e9800998ecf8427e",
        "sha1": "da39a3ee5e6b4b0d3255bfef95601890afd80709",
        "uname": "root",
        "gname": "root",
        "mtime": 1746576732,
        "inode": 40239713,
        "sha256": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
        "attributes": "",
        "checksum": "c3dd77a0b9d01bb729ea98950ffb17e6c8581ab3"
    }
]
```

But the agent has the new file

```
root@fe94358f3c04:/var/ossec# sqlite3 queue/fim/db/fim.db
SQLite version 3.31.1 2020-01-27 19:55:54
Enter ".help" for usage hints.
sqlite> .mode line
sqlite> SELECT * FROM file_entry  WHERE path like '%the_file%';
              path = /home/ubuntu/test/modify_the_file
              mode = 0
        last_event = 1746576927
           scanned = 1
           options = 131583
          checksum = c3dd77a0b9d01bb729ea98950ffb17e6c8581ab3
               dev = 67
             inode = 40239713
              size = 0
              perm = rw-r--r--
        attributes = 
               uid = 0
               gid = 0
         user_name = root
        group_name = root
          hash_md5 = d41d8cd98f00b204e9800998ecf8427e
         hash_sha1 = da39a3ee5e6b4b0d3255bfef95601890afd80709
       hash_sha256 = e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
             mtime = 1746576732
db_status_field_dm = 1
```

If I restart the agent, we find that the checksum check doesn't fail, so the sync will never occur

```
2025/05/07 00:18:35 wazuh-db[221135] wdb_parser.c:263 at wdb_parse(): DEBUG: Agent 001 query: fim_file integrity_check_global {"begin":"/bin","checksum":"83b2591774d77adf3c49e0500dd1815240c0b228","end":"/usr/sbin/zramctl","id":1746577115}
2025/05/07 00:18:35 wazuh-db[221135] wdb_integrity.c:591 at wdbi_query_checksum(): DEBUG: Agent '001' fim_file range checksum avoided.
2025/05/07 00:18:35 wazuh-remoted: WARNING: Message forwarded: '{"agent_info":{"agent_id":"001","agent_ip":"any","agent_name":"fe94358f3c04","agent_version":"v4.11.2"},"data_type":"integrity_check_global","data":{"attributes_type":"fim_file","begin":"/bin","checksum":"83b2591774d77adf3c49e0500dd1815240c0b228","end":"/usr/sbin/zramctl","id":1746577115}}'
```

</p>
</details> 

This isn't a problem of the harvester and it should be fixed in another issue. It's related to the use of RSync, FIM and the manager's checksum cache

https://github.com/wazuh/wazuh/blob/0a0279a9ddf6706458273a0ebadd94efa82e98c4/src/wazuh_db/wdb_integrity.c#L588-L594

### Windows agent manual test :green_circle: : 

With the same setup, I connect a Windows agent.

I've run the same test described here

https://github.com/wazuh/wazuh/issues/29168#issuecomment-2814540089

The output of the script confirms that all entries are indexed

```
root@f8d4e01554db:/workspaces/wazuh.worktrees/4.13.0/src# python3 script.py 
INFO:__main__:Agent ID: 002
...
INFO:__main__:Data length match for agent ID: 002, endpoint: /syscheck/002/
```

### CODE REVIEW

File: src/wazuh_modules/inventory_harvester/src/fimInventory/fimContext.hpp [hunk 1]
```diff
@@ -704,7 +704,7 @@ struct FimContext final
     {
         if (m_pathHashed.empty())
         {
-            auto pathRawStr = index();
+            auto pathRawStr = pathRaw();
```
Comment (GabrielEValenzuela) [inline src/wazuh_modules/inventory_harvester/src/fimInventory/fimContext.hpp:707]: Good catch!
