### PR TITLE
Fix cluster error message

### LINKED ISSUE #1854: Error when starting without cluster configuration
## Bug report

**OS**
_CentOS 6_

**Wazuh version**
_3.7.1-3720_

**Log sample**

```
[root@centos6-agent src]# 2018/11/12 10:37:19 ossec-remoted: ERROR: Cannot read cluster config Success
```

Bug description
----------------

Wazuh gives an error (twice) if it starts without the cluster block. Although it is included in the template, if you use an old ossec.conf this message will appear from 3.7.0.

I think that, for esthetic reasons, our message should be separated from the error message.

Now:
https://github.com/wazuh/wazuh/blob/8df254c7e9cc2775b79f86fe14b1f6dfc05ff51e/src/remoted/main.c#L139

Proposal:
```c 
merror("Cannot read cluster config: %s (%d).", strerror(errno), errno);
```

### PR DESCRIPTION
**Pull request by DaveVG1**
This pull request fixes #1854 
The error message that was displaying when cluster configuration is disabled or non-existent is no longer displayed.
The cluster error message will only appear when a bad node type is configured in the cluster configuration (different from client/worker/master).

### CODE REVIEW

File: src/remoted/main.c [hunk 1]
```diff
@@ -136,7 +136,7 @@ int main(int argc, char **argv)
 
     switch (is_worker){
         case -1:
-            merror("Cannot read cluster config %s", strerror(errno));
+            merror("Cluster node type is not valid [client/worker/master]. Cluster not configured. %s (%d)", strerror(errno), errno);
```
Comment (crolopez) [inline src/remoted/main.c]: The word client to refer to the worker is accepted by retrocompatibility. With this message seems that there are 3 node types.

File: src/shared/cluster_utils.c [hunk 2]
```diff
@@ -49,11 +49,11 @@ int w_is_worker(void) {
                     free(cl_type);
                 }
             } else if (strcmp(cl_status, "yes")){
-                is_worker = -1;
+                is_worker = 2;
```
Comment (vikman90) [inline src/shared/cluster_utils.c]: I think that this value should be `0`, meaning that this node is not a worker (`false`).

Comment (DaveVG1) [reply src/shared/cluster_utils.c]: Should the other case (cluster configuration not found) have also a value of 0? This could also mean that this node is not a worker (or that the user unintentionally erased the cluster config)

File: src/shared/cluster_utils.c [hunk 3]
```diff
@@ -34,26 +35,34 @@ int w_is_worker(void) {
...
-                    }
+                    char * cl_status = OS_GetOneContentforElement(&xml, xmlf3);
+                    if(cl_status && cl_status[0] != '\0'){
+                	    if (!strcmp(cl_status, "no")) {
+                            if (!strcmp(cl_type, "client") || !strcmp(cl_type, "worker")) {
+                                is_worker = 1;
+                            } else {
+                                is_worker = 0;
+                            }
+                		} else {
```
Comment (vikman90) [inline src/shared/cluster_utils.c]: Please avoid mixing whitespaces and tabulations.

Comment (vikman90) [reply src/shared/cluster_utils.c]: Please add also a changelog entry.

Thanks!

**Comment by vikman90** [comment]
LGTM!
