### PR TITLE
Fix detection of OS version for Linux Alpine

### LINKED ISSUE #15697: OS version is not properly parsed for Alpine Linux system
## Description

With the main goal of including the Alpine Linux system to be scanned by Vulnerability detector, a spike was done to gather information about the package data on those systems (https://github.com/wazuh/wazuh/issues/13703) it was found that the OS inventory information does not populate the `os_version` data which will affect the vulnerability scan. 

```json
{
  "os": {
    "architecture": "x86_64",
    "hostname": "alpine38.localdomain",
    "os_name": "Alpine Linux",
    "os_platform": "alpine",
    "release": "4.14.167-0-virt",
    "sysname": "Linux",
    "version": "#1-Alpine SMP Thu Jan 23 10:58:18 UTC 2020"
  }
}
```

Consider take a look at 

https://github.com/wazuh/wazuh/blob/ed299a322189f95e087c7aebc10b8cfe1e04ae5f/src/data_provider/src/sysInfoLinux.cpp#L281

### PR DESCRIPTION
**Pull request by matias-braida**
|Related issue|
|---|
|Closes #15697 |

## Description

With the aim of fixing the OS version detection of different distributions, this PR fix the detection on Linux Alpine.

Linux Alpine distribution information is in files "/etc/os-release" and "/etc/alpine-release". The content of these files is the following:
```
19d8de004a95:/etc# cat os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.17.1
PRETTY_NAME="Alpine Linux v3.17"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://gitlab.alpinelinux.org/alpine/aports/-/issues"
```
```
19d8de004a95:/etc# cat alpine-release 
3.17.1
```

# Before this fix:
The result of executing tool "sysinfo_test_tool" was:
```
{
  "os": {
    "architecture": "x86_64",
    "hostname": "19d8de004a95",
    "os_name": "Alpine Linux",
    "os_platform": "alpine",
    "release": "5.15.0-58-generic",
    "sysname": "Linux",
    "version": "#64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023"
  }
}
```

# After this fix:
The result of executing tool "sysinfo_test_tool" now is:
```
{
  "os": {
    "architecture": "x86_64",
    "hostname": "19d8de004a95",
    "os_major": "3",
    "os_minor": "17",
    "os_name": "Alpine Linux",
    "os_patch": "1",
    "os_platform": "alpine",
    "os_version": "3.17.1",
    "release": "5.15.0-58-generic",
    "sysname": "Linux",
    "version": "#64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023"
  }
}
```

## Tests
2 new unit tests were created to cover this new parser: "SysInfoParsersTest.UnixAlpine" and "SysInfoParsersTest.Alpine".

```
matias@matias-X580VD:~/Proyectos_Wazuh/wazuh/src/data_provider/build/bin$ ./sysinfo_unit_test
[==========] Running 48 tests from 3 test suites.
[----------] Global test environment set-up.
[----------] 26 tests from SysInfoParsersTest
[ RUN      ] SysInfoParsersTest.BaseClass
[       OK ] SysInfoParsersTest.BaseClass (0 ms)
[ RUN      ] SysInfoParsersTest.UnixLinux
[       OK ] SysInfoParsersTest.UnixLinux (1 ms)
[ RUN      ] SysInfoParsersTest.UnixCentos
[       OK ] SysInfoParsersTest.UnixCentos (0 ms)
[ RUN      ] SysInfoParsersTest.UnixArch
[       OK ] SysInfoParsersTest.UnixArch (0 ms)
[ RUN      ] SysInfoParsersTest.UnixAlpine
[       OK ] SysInfoParsersTest.UnixAlpine (1 ms)
[ RUN      ] SysInfoParsersTest.Ubuntu
[       OK ] SysInfoParsersTest.Ubuntu (1 ms)
[ RUN      ] SysInfoParsersTest.Centos
[       OK ] SysInfoParsersTest.Centos (1 ms)
[ RUN      ] SysInfoParsersTest.BSDFreeBSD
[       OK ] SysInfoParsersTest.BSDFreeBSD (1 ms)
[ RUN      ] SysInfoParsersTest.BSDOpenBSD
[       OK ] SysInfoParsersTest.BSDOpenBSD (1 ms)
[ RUN      ] SysInfoParsersTest.RedHatCentos
[       OK ] SysInfoParsersTest.RedHatCentos (0 ms)
[ RUN      ] SysInfoParsersTest.RedHatFedora
[       OK ] SysInfoParsersTest.RedHatFedora (0 ms)
[ RUN      ] SysInfoParsersTest.RedHatServer
[       OK ] SysInfoParsersTest.RedHatServer (0 ms)
[ RUN      ] SysInfoParsersTest.RedHatLinux
[       OK ] SysInfoParsersTest.RedHatLinux (0 ms)
[ RUN      ] SysInfoParsersTest.Debian
[       OK ] SysInfoParsersTest.Debian (1 ms)
[ RUN      ] SysInfoParsersTest.Arch
[       OK ] SysInfoParsersTest.Arch (2 ms)
[ RUN      ] SysInfoParsersTest.Slackware
[       OK ] SysInfoParsersTest.Slackware (2 ms)
[ RUN      ] SysInfoParsersTest.Gentoo
[       OK ] SysInfoParsersTest.Gentoo (2 ms)
[ RUN      ] SysInfoParsersTest.SuSE
[       OK ] SysInfoParsersTest.SuSE (1 ms)
[ RUN      ] SysInfoParsersTest.Fedora
[       OK ] SysInfoParsersTest.Fedora (1 ms)
[ RUN      ] SysInfoParsersTest.Solaris
[       OK ] SysInfoParsersTest.Solaris (0 ms)
[ RUN      ] SysInfoParsersTest.Solaris1
[       OK ] SysInfoParsersTest.Solaris1 (0 ms)
[ RUN      ] SysInfoParsersTest.HPUX
[       OK ] SysInfoParsersTest.HPUX (1 ms)
[ RUN      ] SysInfoParsersTest.Alpine
[       OK ] SysInfoParsersTest.Alpine (2 ms)
[ RUN      ] SysInfoParsersTest.UknownPlatform
[       OK ] SysInfoParsersTest.UknownPlatform (0 ms)
[ RUN      ] SysInfoParsersTest.MacOS
[       OK ] SysInfoParsersTest.MacOS (2 ms)
[ RUN      ] SysInfoParsersTest.MacOSOsDefaultName
[       OK ] SysInfoParsersTest.MacOSOsDefaultName (1 ms)
[----------] 26 tests from SysInfoParsersTest (30 ms total)

[----------] 21 tests from SysInfoTest
[ RUN      ] SysInfoTest.hardware
[       OK ] SysInfoTest.hardware (0 ms)
[ RUN      ] SysInfoTest.packages_cb
[       OK ] SysInfoTest.packages_cb (0 ms)
[ RUN      ] SysInfoTest.packages
[       OK ] SysInfoTest.packages (0 ms)
[ RUN      ] SysInfoTest.processes_cb
[       OK ] SysInfoTest.processes_cb (0 ms)
[ RUN      ] SysInfoTest.processes
[       OK ] SysInfoTest.processes (0 ms)
[ RUN      ] SysInfoTest.network
[       OK ] SysInfoTest.network (0 ms)
[ RUN      ] SysInfoTest.ports
[       OK ] SysInfoTest.ports (0 ms)
[ RUN      ] SysInfoTest.os
[       OK ] SysInfoTest.os (0 ms)
[ RUN      ] SysInfoTest.hotfixes
[       OK ] SysInfoTest.hotfixes (0 ms)
[ RUN      ] SysInfoTest.hardware_c_interface
[       OK ] SysInfoTest.hardware_c_interface (0 ms)
[ RUN      ] SysInfoTest.packages_c_interface
[       OK ] SysInfoTest.packages_c_interface (0 ms)
[ RUN      ] SysInfoTest.packages_cb_c_interface
[       OK ] SysInfoTest.packages_cb_c_interface (0 ms)
[ RUN      ] SysInfoTest.packages_cb_c_interface_test_empty_callback
[       OK ] SysInfoTest.packages_cb_c_interface_test_empty_callback (0 ms)
[ RUN      ] SysInfoTest.processes_c_interface
[       OK ] SysInfoTest.processes_c_interface (0 ms)
[ RUN      ] SysInfoTest.processes_cb_c_interface
[       OK ] SysInfoTest.processes_cb_c_interface (0 ms)
[ RUN      ] SysInfoTest.processes_cb_c_interface_test_empty_callback
[       OK ] SysInfoTest.processes_cb_c_interface_test_empty_callback (0 ms)
[ RUN      ] SysInfoTest.network_c_interface
[       OK ] SysInfoTest.network_c_interface (0 ms)
[ RUN      ] SysInfoTest.ports_c_interface
[       OK ] SysInfoTest.ports_c_interface (0 ms)
[ RUN      ] SysInfoTest.os_c_interface
[       OK ] SysInfoTest.os_c_interface (0 ms)
[ RUN      ] SysInfoTest.hotfixes_c_interface
[       OK ] SysInfoTest.hotfixes_c_interface (0 ms)
[ RUN      ] SysInfoTest.c_interfaces_bad_params
[       OK ] SysInfoTest.c_interfaces_bad_params (0 ms)
[----------] 21 tests from SysInfoTest (2 ms total)

[----------] 1 test from SysOsInfoTest
[ RUN      ] SysOsInfoTest.setOsInfoSchema
[       OK ] SysOsInfoTest.setOsInfoSchema (0 ms)
[----------] 1 test from SysOsInfoTest (0 ms total)

[----------] Global test environment tear-down
[==========] 48 tests from 3 test suites ran. (33 ms total)
[  PASSED  ] 48 tests.

```

### CODE REVIEW

File: src/data_provider/src/osinfo/sysOsParsers.cpp [hunk 1]
```diff
@@ -137,15 +137,30 @@ static bool findVersionInStream(std::istream& in,
...
-    const auto ret {parseUnixFile(KEY_MAP, SEPARATOR, in, info)};
+        static const std::map<std::string, std::string> KEY_MAP
+        {
+            {"NAME",             "os_name"},
+            {"VERSION",          "os_version"},
+            {"ID",               "os_platform"},
+            {"BUILD_ID",         "os_build"},
+            {"VERSION_CODENAME", "os_codename"}
+        };
+        ret |= parseUnixFile(KEY_MAP, SEPARATOR, in, info);
```
Comment (tdrauncieal) [inline src/data_provider/src/osinfo/sysOsParsers.cpp:151]: Unnecessary OR-EQUAL operator assignment.

File: src/data_provider/src/osinfo/sysOsParsers.cpp [hunk 2]
```diff
@@ -137,15 +137,30 @@ static bool findVersionInStream(std::istream& in,
 bool UnixOsParser::parseFile(std::istream& in, nlohmann::json& info)
 {
     constexpr auto SEPARATOR{'='};
-    static const std::map<std::string, std::string> KEY_MAP
+    bool ret = false;
+
     {
```
Comment (tdrauncieal) [inline src/data_provider/src/osinfo/sysOsParsers.cpp:142]: Question: why this grouping?

Comment (matias-braida) [reply src/data_provider/src/osinfo/sysOsParsers.cpp:142]: This local scope is defined here in order to allow a redefinition of local variable name "KEY_MAP" in the following lines (also defined as a local scope).

File: src/data_provider/src/osinfo/sysOsParsers.cpp (hunk 1 above)
Comment (matias-braida) [reply src/data_provider/src/osinfo/sysOsParsers.cpp:151]: I will fix it.

File: src/data_provider/src/osinfo/sysOsParsers.cpp (hunk 2 above)
Comment (tdrauncieal) [reply src/data_provider/src/osinfo/sysOsParsers.cpp:142]: Ok, I see below, but maybe it seems excessive, consider just another variable name

Comment (matias-braida) [reply src/data_provider/src/osinfo/sysOsParsers.cpp:142]: Ok, I change it

File: src/data_provider/src/osinfo/sysOsParsers.cpp [hunk 3]
```diff
@@ -137,15 +137,28 @@ static bool findVersionInStream(std::istream& in,
 bool UnixOsParser::parseFile(std::istream& in, nlohmann::json& info)
 {
     constexpr auto SEPARATOR{'='};
-    static const std::map<std::string, std::string> KEY_MAP
+    bool ret;
```
Comment (Dwordcito) [inline src/data_provider/src/osinfo/sysOsParsers.cpp:140]: remove this line.

File: src/data_provider/src/osinfo/sysOsParsers.cpp [hunk 4]
```diff
@@ -137,15 +137,28 @@ static bool findVersionInStream(std::istream& in,
...
+    static const std::map<std::string, std::string> KEY_MAP1
     {
         {"NAME",             "os_name"},
         {"VERSION",          "os_version"},
         {"ID",               "os_platform"},
         {"BUILD_ID",         "os_build"},
         {"VERSION_CODENAME", "os_codename"}
     };
-    const auto ret {parseUnixFile(KEY_MAP, SEPARATOR, in, info)};
+    ret = parseUnixFile(KEY_MAP1, SEPARATOR, in, info);
```
Comment (Dwordcito) [inline src/data_provider/src/osinfo/sysOsParsers.cpp:150]:
```suggestion
    const auto ret { parseUnixFile(KEY_MAP1, SEPARATOR, in, info) };
```

File: src/data_provider/src/osinfo/sysOsParsers.cpp [hunk 5]
```diff
@@ -137,15 +137,28 @@ static bool findVersionInStream(std::istream& in,
...
+    if (info.find("os_version") == info.end())
+    {
+        static const std::map<std::string, std::string> KEY_MAP2
+        {
+            {"VERSION_ID",       "os_version"},
+        };
+        in.clear();
+        in.seekg(0);
+        ret |= parseUnixFile(KEY_MAP2, SEPARATOR, in, info);
+    }
```
Comment (Dwordcito) [inline src/data_provider/src/osinfo/sysOsParsers.cpp:161]: This change is unnecesary if you add new key(VERSION_ID) in the previous static map.

File: src/data_provider/src/osinfo/sysOsParsers.cpp [hunk 6]
```diff
@@ -137,15 +137,28 @@ static bool findVersionInStream(std::istream& in,
...
+    bool ret;
+
+    static const std::map<std::string, std::string> KEY_MAP1
     {
         {"NAME",             "os_name"},
         {"VERSION",          "os_version"},
         {"ID",               "os_platform"},
         {"BUILD_ID",         "os_build"},
         {"VERSION_CODENAME", "os_codename"}
     };
```
Comment (Dwordcito) [inline src/data_provider/src/osinfo/sysOsParsers.cpp:149]:
```suggestion
    static const std::map<std::string, std::string> KEY_MAP1
    {
        {"NAME",             "os_name"},
        {"VERSION_ID",       "os_version"},
        {"VERSION",          "os_version"},
        {"ID",               "os_platform"},
        {"BUILD_ID",         "os_build"},
        {"VERSION_CODENAME", "os_codename"}
    };
```

**Review by Dwordcito — CHANGES_REQUESTED** [review]

File: src/data_provider/src/osinfo/sysOsParsers.cpp (hunk 6 above)
Comment (matias-braida) [reply src/data_provider/src/osinfo/sysOsParsers.cpp:149]: The issue with this solution is that tags "VERSION_ID" and "VERSION" have no priority in case both are present in file os-release.
For example in Ubuntu both tags are present:

```
matias@matias-X580VD:~/Proyectos_Wazuh/wazuh/src$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```
Despite function "parseUnixFile" always takes the last tag ocurrence (in case of ubuntu would be "VERSION") and it would works. But in case that these tags were inverted (for example in other OS, I dont know), the current behaviour of the parser would be altered.
Thats why I choose to find in first place for tag "VERSION" and in case it not exists, then find for tag "VERSION_ID".

File: src/data_provider/src/osinfo/sysOsParsers.cpp [hunk 7]
```diff
@@ -137,15 +137,28 @@ static bool findVersionInStream(std::istream& in,
...
+
+    if (info.find("os_version") == info.end())
+    {
+        static const std::map<std::string, std::string> KEY_MAP2
+        {
+            {"VERSION_ID",       "os_version"},
+        };
+        in.clear();
+        in.seekg(0);
+        ret |= parseUnixFile(KEY_MAP2, SEPARATOR, in, info);
```
Comment (MiguelazoDS) [inline src/data_provider/src/osinfo/sysOsParsers.cpp:160]: What is the purpose of bitwise operations in boolean? couldn't this lead to unexpected behavior?

Comment (matias-braida) [reply src/data_provider/src/osinfo/sysOsParsers.cpp:160]: Just to avoid a conditional statement to set variable ret=true in case function parseUnixFile returns true.
In C++ boolean variables are guaranteed to be false=0 and true=1 in case of integer promotion.
image

File: src/data_provider/src/osinfo/sysOsParsers.cpp (hunk 6 above)
Comment (matias-braida) [reply src/data_provider/src/osinfo/sysOsParsers.cpp:149]: As we agreed in the stand up, this implementation is going to be modified doing a rework of function parseUnixFile.

File: src/shared_modules/utils/stringHelper.h [hunk 8]
```diff
@@ -147,6 +176,29 @@ namespace Utils
         return ret;
     }
 
+    static void splitMapKeyValue(const std::string& str,
```
Comment (pereyra-m) [inline src/shared_modules/utils/stringHelper.h:179]: We should add UT for this new method.

**Review by pereyra-m — COMMENTED** [review]
GJ!
Just one comment

**Review by pereyra-m — APPROVED** [review]

**Review by pereyra-m — APPROVED** [review]

File: src/data_provider/src/osinfo/sysOsParsers.cpp (hunk 5 above)
Comment (matias-braida) [reply src/data_provider/src/osinfo/sysOsParsers.cpp]: done

**Review by pereyra-m — DISMISSED** [review]

**Review by pereyra-m — APPROVED** [review]

**Review by MiguelazoDS — APPROVED** [review]

File: src/data_provider/src/osinfo/sysOsParsers.cpp [hunk 9]
```diff
@@ -371,17 +359,25 @@ bool HpUxOsParser::parseUname(const std::string& in, nlohmann::json& output)
...
+    output["os_name"] = "Alpine Linux";
+    output["os_platform"] = "alpine";
+    return findVersionInStream(in, output, PATTERN_MATCH);
+}
+
 bool MacOsParser::parseSwVersion(const std::string& in, nlohmann::json& output)
 {
     constexpr auto SEPARATOR{':'};
-    static const std::map<std::string, std::string> KEY_MAP
+    static const std::vector<std::pair<std::string, std::string>> KEY_MAPPING
```
Comment (tdrauncieal) [inline src/data_provider/src/osinfo/sysOsParsers.cpp:373]: The changes made to this function, while elementary, exceed the original scope of the issue.

File: src/data_provider/src/osinfo/sysOsParsers.cpp [hunk 10]
```diff
@@ -394,13 +390,13 @@ bool MacOsParser::parseSwVersion(const std::string& in, nlohmann::json& output)
 bool MacOsParser::parseSystemProfiler(const std::string& in, nlohmann::json& output)
 {
     constexpr auto SEPARATOR{':'};
-    static const std::map<std::string, std::string> KEY_MAP
+    static const std::vector<std::pair<std::string, std::string>> KEY_MAPPING
```
Comment (tdrauncieal) [inline src/data_provider/src/osinfo/sysOsParsers.cpp:393]: The changes made to this function, while elementary, exceed the original scope of the issue

File: src/data_provider/src/osinfo/sysOsParsers.cpp [hunk 11]
```diff
@@ -290,14 +278,14 @@ bool GentooOsParser::parseFile(std::istream& in, nlohmann::json& output)
 bool SuSEOsParser::parseFile(std::istream& in, nlohmann::json& output)
 {
     constexpr auto SEPARATOR{'='};
-    static const std::map<std::string, std::string> KEY_MAP
+    static const std::vector<std::pair<std::string, std::string>> KEY_MAPPING
```
Comment (tdrauncieal) [inline src/data_provider/src/osinfo/sysOsParsers.cpp:281]: The changes made to this function, while elementary, exceed the original scope of the issue

File: src/data_provider/src/osinfo/sysOsParsers.cpp [hunk 12]
```diff
@@ -137,15 +124,16 @@ static bool findVersionInStream(std::istream& in,
 bool UnixOsParser::parseFile(std::istream& in, nlohmann::json& info)
 {
     constexpr auto SEPARATOR{'='};
-    static const std::map<std::string, std::string> KEY_MAP
+    static const std::vector<std::pair<std::string, std::string>> KEY_MAPPING
```
Comment (tdrauncieal) [inline src/data_provider/src/osinfo/sysOsParsers.cpp:127]: The changes made to this function, while elementary, exceed the original scope of the issue

**Review by Dwordcito — APPROVED** [review]
