### PR TITLE
Fix special characters in `reflectiveJson`

### LINKED ISSUE #29142: Error indexing files with special characters in global-queries
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.13.0-alpha0| Wazuh component | Manager | Packages | Any |

Performing tests of the functionality under development I find that:

In ossec.log:
```
2025/04/09 10:14:16 indexer-connector: WARNING: Failed to parse event data: {"id":"001_/etc/ssl/certs/NetLock_Arany_=Class_Gold=_FHcH��E1�H)��f��v�Nf��t�<uf��wE1�L����AVAUL�ATI��USH�GH��H����tanAWE��AVI��AUATI��H���AUATI��UH��0�?uH�H�H�sAWE��AVI��AUATI��H���h�tvAWE��AVI��AUATI��H���AWAVAUATI��UH�oSH��ny.pem","operation":"INSERTED","data":{"file":{"path":"/etc/ssl/certs/NetLock_Arany_=Class_Gold=_FHcH��E1�H)��f��v�Nf��t�<uf��wE1�L����AVAUL�ATI��USH�GH��H����tanAWE��AVI��AUATI��H���AUATI��UH��0�?uH�H�H�sAWE��AVI��AUATI��H���h�tvAWE��AVI��AUATI��H���AWAVAUATI��UH�oSH��ny.pem","gid":"0","group":"root","mtime":"2021-04-30T23:18:02.000Z","size":83,"uid":"0","owner":"root","hash":{"md5":"d41d8cd98f00b204e9800998ecf8427e","sha1":"da39a3ee5e6b4b0d3255bfef95601890afd80709","sha256":"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"}},"agent":{"id":"001","name":"agent3","version":"v4.13.0"},"wazuh":{"cluster":{"name":"wazuh","node":"master"},"schema":{"version":"1.0"}}}}
```

I also see that in the list of files obtained through global-queries
This file is not present in the indexes while it is present in the database.

```
'/etc/ssl/certs/NetLock_Arany_=Class_Gold=_Főtanúsítvány.pem'
```

It's very likely that there's some kind of encoding issue with the special characters.
Further analysis and eventual repair will be required.

## Steps to reproduce
1. Create the infrastructure with manager, filebeat, agents, and agent using packages found in packages.dev in the wqa1198 directory.
2. Once the core components are connected, run the keystore inclusion.
3. Obtain indexed files using sqlite3 in the WazuhDB table, fim_entry column, file.
4. Check for the appearance of files with special characters like the one mentioned (found in the Ubuntu agent).
5. Perform GQ using the query:
curl -k -u <indexer_user>:<indexer_pass> https://<indexer_ip>:9200/wazuh-states-files-wazuh/_search?size=10000
6. Verify that the file found does not exist in the DB.
7. Check the error message in Ossec.log.

### PR DESCRIPTION
**Pull request by GabrielEValenzuela**
|Related issue|
|---|
|Closes #29142 |

# Objective

Ensure proper escaping of UTF-8 encoded input characters in JSON serialization routines by explicitly casting characters to `unsigned char` prior to indexing into the `ESCAPE_TABLE`.

## Description

This change addresses a subtle but critical correctness issue in the `needEscape()` and `escapeJSONString()` functions, where each character from a `std::string_view` was previously used as an index into `ESCAPE_TABLE` without casting. In C++, `char` may be signed or unsigned depending on the implementation, and on most systems using GCC < 11.1 with `-O3` optimizations, signed characters with negative values can result in **undefined behavior** when used as array indices.

By explicitly casting each character to `unsigned char`, we ensure that values fall in the valid range of 0–255 before being used to index `ESCAPE_TABLE`. 

This issue is particularly critical when processing UTF-8 encoded input that contains extended byte sequences (e.g., multi-byte characters such as `ő`, `ü`, or emoji), which encode values above 127. On compilers such as GCC 9.4 or earlier with `-O3`, these could be miscompiled due to the assumption of signed `char`, leading to incorrect or unsafe memory access.

##### Before change

image

##### After change

image

### Key changes

- Explicitly cast characters to `unsigned char` in `needEscape()` and `escapeJSONString()` to guarantee safe indexing into the 256-entry `ESCAPE_TABLE`.
- Prevents undefined behavior and ensures correctness of UTF-8 escaping logic on GCC versions prior to 11.1, especially under aggressive optimization (`-O3`).
- Ensures that escaping logic remains robust and safe for all valid UTF-8 input, regardless of platform default `char` signedness.

### CODE REVIEW

File: src/shared_modules/utils/reflectiveJson.hpp [hunk 1]
```diff
@@ -62,9 +62,9 @@ static std::array<const char*, CHAR_SIZE> ESCAPE_TABLE = []
 
 inline bool needEscape(std::string_view input)
 {
-    for (auto c : input)
+    for (unsigned char chr : input)
```
Comment (pereyra-m) [inline src/shared_modules/utils/reflectiveJson.hpp:65]: Great finding !

File: src/shared_modules/utils/reflectiveJson.hpp
Comment (pereyra-m) [inline src/shared_modules/utils/reflectiveJson.hpp:1]: I know that the tests won't run with GCC 9.4, but I still would add UT related to the special characters.

File: src/shared_modules/utils/reflectiveJson.hpp (hunk 1 above)
Comment (pereyra-m) [reply src/shared_modules/utils/reflectiveJson.hpp:65]: This deserves a comment.

**Review by pereyra-m — COMMENTED** [review]
Great job!

File: src/shared_modules/utils/reflectiveJson.hpp (hunk 1 above)
Comment (GabrielEValenzuela) [reply src/shared_modules/utils/reflectiveJson.hpp:65]: Adding!

File: src/shared_modules/utils/reflectiveJson.hpp
Comment (GabrielEValenzuela) [reply src/shared_modules/utils/reflectiveJson.hpp:1]: I add it

**Review by MiguelazoDS — APPROVED** [review]

**Review by pereyra-m — APPROVED** [review]
