### PR TITLE
Fix to process unknown registry value types in FIM sync

### LINKED ISSUE #12835: fimDB unrecognized error in Windows synchronization
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| [9103-replace-fim-db-dbsync](https://github.com/wazuh/wazuh/tree/9103-replace-fim-db-dbsync) | FIM |Windows | Sources | All|

## Description
Hello team, while running the syscheck stress tests, we have found a problem related to Windows synchronization:

`ERROR: Unrecognized error.`

To reproduce it you just need to use the same configuration used in the stress test, which has several monitored logs, and wait for the synchronization.
After analyzing the problem, it seems to be a failure to access a map field (map::at).
There are reasons to think that it may be related to some value names that come empty, corresponding to the default values that some keys come with.

### PR DESCRIPTION
**Pull request by jotacarma90**
|Related issue|
|---|
|https://github.com/wazuh/wazuh/issues/12835|

## Description

This PR fixes the problem related to an unrecognized error that we were getting in the FIM synchronization. 
It was produced in the register sync, that after the investigation we have seen that it was due to some types of values that were not mapped. Added REG_UNKNOWN to value types.

Closes #12835

## Configuration options

    <windows_registry arch="64bit">HKEY_LOCAL_MACHINE\Security\SAM\Domains\Builtin\Aliases\Names\Duplicadores</windows_registry>

## Logs/Alerts example

`2022/02/26 20:13:16 wazuh-agent[4496] run_check.c:117 at send_syscheck_msg(): DEBUG: (6321): Sending FIM event: {"type":"event","data":{"path":"HKEY_LOCAL_MACHINE\\Security\\SAM\\Domains\\Builtin\\Aliases\\Names\\Duplicadores","version":2,"mode":"scheduled","type":"modified","arch":"[x64]","value_name":"","timestamp":1645902796,"attributes":{"type":"registry_value","value_type":"REG_UNKNOWN","size":1,"hash_md5":"d3d9446802a44259755d38e6d163e820","hash_sha1":"b1d5781111d84f7b3fe45a0852e59758cd7a87e5","hash_sha256":"4a44dc15364204a80fe80e9039455cc1608281820fe2b24f1e5233ade6af1dd5","checksum":"d41d520aa518fdf21dc41330881660dc62c3f5a7"},"old_attributes":{"type":"registry_value","size":0,"value_type":"REG_UNKNOWN","hash_md5":"d41d8cd98f00b204e9800998ecf8427e","hash_sha1":"da39a3ee5e6b4b0d3255bfef95601890afd80709","hash_sha256":"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"},"changed_attributes":["size","md5","sha1","sha256"]}}`

## Tests

- Compilation without warnings in every supported platform
  - [x] Linux
  - [x] Windows
- [x] Source installation

- Memory tests for Linux
  - [ ] Scan-build report
- Memory tests for Windows
  - [ ] Scan-build report

### CODE REVIEW

**Review by FrancoRivero — APPROVED** [review]
LGTM

File: src/syscheckd/include/syscheck.h [hunk 1]
```diff
@@ -112,6 +112,7 @@ typedef struct fim_txn_context_s {
 /* Flags to know if a directory/file's watcher has been removed */
 #define FIM_RT_HANDLE_CLOSED 0
 #define FIM_RT_HANDLE_OPEN 1
+#define REG_UNKNOWN 0x0000000C
```
Comment (chemamartinez) [inline src/syscheckd/include/syscheck.h:115]: It would be good to include here a small comment about the need of `REG_UNKNOWN` and its value

**Review by chemamartinez — APPROVED** [review]
