### PR TITLE
[7507] Incorrect scan time fix

### LINKED ISSUE #7507: Incorrect scan_time format
## Description
This issue was discovered in the api framework tests, apparently the format is incorrect since when the units are not greater than 10, the leading zero is not being concatenated.

Expected
scan_time:  `2021/02/16 14:00:21`

Actual:
scan_time:  `2021/2/16 14:0:21`

## DoD
- [x] Modify get time helper tod common and fixed string format.  YYYY/MM/DD hh:mm:ss
- [x] Modify unit tests
- [x] RTR
- [x] PR

### PR DESCRIPTION
**Pull request by tinachoB**
|Related issue|
|---|
|Closes #7507 |

## **Description**

This issue was discovered in the api framework tests, apparently the format is incorrect since when the units are not greater than 10, the leading zero is not being concatenated.

Expected
scan_time:  `2021/02/16 14:00:21`

Actual:
scan_time:  `2021/2/16 14:0:21`

## **DoD**
- [X] RC/Fix
- [X] Update UTs
- [X] RTR PASSED in all affected modules

**Data Provider**
image

**Utils**
image

**Syscollector**
image

- [x] CI PASS

### CODE REVIEW

File: src/shared_modules/utils/timeHelper.h [hunk 1]
```diff
@@ -22,21 +22,24 @@ namespace Utils
...
-        timestamp += std::to_string(localTime->tm_min);
-        timestamp += ":";
-        timestamp += std::to_string(localTime->tm_sec);
-        return timestamp;
+        std::stringstream ss;
+        // gmtime: result expressed as a UTC time
+        tm* localTime { gmtime(&time) };
+        // Final timestamp: "YYYY/MM/DD hh:mm:ss"
+        // Date
+        ss << std::hex << std::setfill('0') << std::setw(4) << std::to_string(localTime->tm_year + 1900);
```
Comment (Dwordcito) [inline src/shared_modules/utils/timeHelper.h:30]: is necessary the std::hex here ?

Comment (tinachoB) [reply src/shared_modules/utils/timeHelper.h]: It is not. Removed in latest commit. Good catch

**Review by Dwordcito — APPROVED** [review]

**Review by konangc87 — APPROVED** [review]
