### PR TITLE
wazuh-engine: Improve cocurrent queue engine

### LINKED ISSUE #31623: Simplify `queue/queue` API (no sleeps/retries, no overflow-to-file) and refactor call sites
## Summary

The `wazuh-engine` queue module (`engine/src/queue/queue`) must be simplified to a fail-fast API. Remove legacy behaviors that hide contention (sleep/retry loops and overflow-to-file). Provide a clear, minimal interface with well-documented semantics for capacity, memory reservation, and contention.

## Goals

- **Remove overflow-to-file fallback** when the queue is full.
- **Eliminate all sleeps** inside the queue implementation. Methods may fail, but must **never sleep**.
- **Remove internal retry loops** in enqueue paths.
- Define **two enqueue methods** with lvalue/rvalue overloads:
    ```cpp
    bool push(const T& item) noexcept;
    bool push(T&& item) noexcept;
    bool tryPush(const T& item) noexcept;
    bool tryPush(T&& item) noexcept;
    ````

* **Doxygen**: Document precisely
  * when and how memory is reserved (e.g., capacity fixed at construction; no dynamic growth),
  * behavior under contention

## Tasks

1. **Implementation**

   * Remove file-flood/overflow code paths and any related configuration flags.
   * Strip out all `sleep`/`usleep`/`nanosleep` (or equivalents) and internal retry loops.
   * Implement `push` and `tryPush` with `const T&` and `T&&` overloads.

2. **Documentation**

   * Add/refresh Doxygen for the public API and internal design notes (capacity, allocations, contention, thread-safety).

3. **Refactor call sites**

   * Audit all usages of `queue/queue` across the codebase.
   * Update call sites to use `push`  or `tryPush` if is necesary.
   * Remove any caller-side logic relying on overflow-to-file semantics.

4. **Testing**

   * Unit tests for `push`/`tryPush` (value/move), full-queue behavior, exception/noexcept guarantees.
   * Concurrency stress tests under contention (no sleeping, no hidden retries).
   * Ensure no filesystem writes occur on overflow.

### PR DESCRIPTION
**Pull request by juliancnn**
## Description

Closes #31623 

This PR introduces the new `fastqueue` module, a high-performance templated concurrent queue implementation that replaces the legacy `queue` module. The module provides two distinct implementations optimized for different use cases:

- **CQueue**: Lock-free implementation based on `moodycamel::BlockingConcurrentQueue`
- **StdQueue**: Mutex-based implementation using `std::queue` with `std::mutex` and `std::condition_variable`

Both implementations feature:
- **Rate limiting** capability via token bucket algorithm for backpressure control
- Minimum capacity enforcement (8,192 elements) for optimal performance
- Bulk dequeue operations (`tryPopBulk`)
- Comprehensive unit tests (76 total: 38 per implementation)
- Performance benchmarks comparing both implementations across multiple scenarios

**Key improvements over legacy queue module:**
- Bug-free implementation with proper memory management
- Flexible choice between lock-free and mutex-based synchronization
- Built-in rate limiting without external dependencies
- 2-4x performance improvement in asymmetric patterns (MPSC/SPMC)
- Exact capacity control option (StdQueue)

## Proposed Changes

- FastQueue module, free of bug of module queue
### Performance Benchmark Results (Release Build)

Benchmarks executed on 32-core system (5.6 GHz) with Release optimization:

#### Summary Table

| Scenario | CQueue | StdQueue | Winner | Advantage |
|----------|--------|----------|--------|-----------|
| **SPSC (1 producer, 1 consumer)** | 40.6 M/s | 46.3 M/s | StdQueue | **+14%** |
| **MPSC (8 producers, 1 consumer)** | 9.03 M/s | 3.71 M/s | **CQueue** | **+143%** |
| **SPMC (1 producer, 8 consumers)** | 2.81 M/s | 749 k/s | **CQueue** | **+275%** |
| **MPMC (4x4 balanced)** | 23.6 M/s | 23.0 M/s | CQueue | +3% |
| **Bulk operations (size 10)** | 25.9 M/s | 21.4 M/s | **CQueue** | **+21%** |
| **Rate limiting (10K/s)** | 833 k/s | 1002 k/s | **StdQueue** | **+20%** |
| **High contention (16 threads)** | 214 M/s | 188 M/s | **CQueue** | **+14%** |

#### Key Performance Insights

**CQueue (lock-free) excels at:**
- **SPMC patterns**: 3.75x faster with multiple consumers (best case)
- **MPSC patterns**: 2.43x faster with multiple producers  
- Bulk operations: 21% faster for batch processing
- High contention: 14% better throughput with 16+ threads
- Predictable performance under load

**StdQueue (mutex-based) excels at:**
- **Simple SPSC**: 14% faster when contention is minimal
- **Rate limiting**: 20% faster due to `condition_variable` integration
- Exact capacity control (no overshoot)
- Simpler debugging and maintenance

#### Recommendations

**Use CQueue when:**
- Multiple producers → single consumer (MPSC) - log aggregation, event collection
- Single producer → multiple consumers (SPMC) - work distribution, fan-out patterns
- Balanced MPMC with high throughput requirements
- Lock-free guarantees are required
- Bulk operations are frequent

**Use StdQueue when:**
- Rate limiting is critical (20% faster)
- Simple SPSC pattern (14% faster)
- Exact capacity control is required
- Simpler debugging is preferred
- Low thread contention expected (1-2 threads)

<details>
<summary><b>📊 Full Benchmark Results (Click to expand)</b></summary>

```
Run on (32 X 5600 MHz CPU s)
CPU Caches:
  L1 Data 48 KiB (x16)
  L1 Instruction 32 KiB (x16)
  L2 Unified 2048 KiB (x16)
  L3 Unified 36864 KiB (x1)

SPSC (Single Producer, Single Consumer):
  BM_Compare_SPSC_CQueue/1000        49.0 us    40.85 M/s
  BM_Compare_SPSC_StdQueue/1000      43.2 us    46.29 M/s  ✓ 14% faster
  
MPSC (Multiple Producers, Single Consumer):
  BM_Compare_MPSC_CQueue/8           886 us     9.03 M/s   ✓ 143% faster
  BM_Compare_MPSC_StdQueue/8        2158 us     3.71 M/s
  
SPMC (Single Producer, Multiple Consumers):
  BM_Compare_SPMC_CQueue/8          3561 us     2.81 M/s   ✓ 275% faster
  BM_Compare_SPMC_StdQueue/8       13354 us     749 k/s
  
MPMC (Multiple Producers, Multiple Consumers):
  BM_Compare_MPMC_CQueue             169 us    23.62 M/s   ✓ 3% faster
  BM_Compare_MPMC_StdQueue           174 us    23.02 M/s
  
Bulk Operations:
  BM_Compare_Bulk_CQueue/10          386 us    25.94 M/s   ✓ 21% faster
  BM_Compare_Bulk_StdQueue/10        467 us    21.41 M/s
  
Rate Limiting (10K elements/sec):
  BM_Compare_RateLimit_CQueue       120 us     833 k/s
  BM_Compare_RateLimit_StdQueue     100 us    1002 k/s     ✓ 20% faster
  
High Contention (16 threads):
  BM_Compare_HighContention_CQueue  375 us    213.6 M/s    ✓ 14% faster
  BM_Compare_HighContention_StdQueue 425 us   188.0 M/s
```

</details>

### Tests Introduced

**Unit Tests (76 total):**
- Basic operations: push/pop/tryPush/tryPop/waitPop
- Capacity management: empty/size/aproxFreeSlots
- Bulk operations: tryPopBulk with various sizes
- Edge cases: full queue, empty queue, timeout scenarios
- Rate limiting: token bucket accuracy, throttling verification
- Thread safety: concurrent push/pop operations

**Benchmark Tests:**
- SPSC: 1 producer, 1 consumer (baseline)
- MPSC: 2/4/8 producers, 1 consumer (fan-in)
- SPMC: 1 producer, 2/4/8 consumers (fan-out)
- MPMC: Balanced producers/consumers (4x4, 8x8)
- Bulk: Batch operations with sizes 1/10/100
- Rate limiting: 1K and 10K elements/second
- High contention: 4/8/16 threads mixed operations

### Manual tests with their corresponding evidence

- Compilation without warnings on every supported platform
  - [x] Linux
  - [ ] Windows 
  - [ ] MAC OS X
- [ ] Log syntax and correct language review

- Memory tests for Linux
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Coverity
  - [ ] UMDH
- Memory tests for macOS
  - [ ] Leaks
  - [ ] AddressSanitizer

- Decoder/Rule tests _(Wazuh v4.x)_
  - [ ] Added unit testing files ".ini"
  - [ ] `runtests.py` executed without errors

- Engine _(Wazuh v5.x and above)_
  - [ ] Test run in parallel
  - [ ] ASAN for test (utest/ctest)
  - [ ] TSAN for test and wazuh-engine.

- Wazuh server API/Framework
  - [ ] Run API Integration Tests

### CODE REVIEW

File: src/engine/source/fastqueue/include/fastqueue/cqueue.hpp [hunk 1]
```diff
@@ -0,0 +1,228 @@
...
+     * @note If rate limiting is enabled, this method will return false if the rate limit is exceeded.
+     */
+    inline bool tryPop(T& element) override
+    {
+        if (m_rateLimiter && !m_rateLimiter->tryAcquire(1))
+        {
+            return false;
+        }
+        return m_queue.try_dequeue(element);
+    }
```
Comment (jam300) [inline src/engine/source/fastqueue/include/fastqueue/cqueue.hpp:184]: Observation: possible token leak, `tryAcquire()` consumes a token before `try_dequeue` confirms an element exists. If the queue is empty, the token is lost — real elements pushed later become unreachable until the bucket refills.

<details><summary>unit test</summary>
<p>

```c++

TEST_F(CQueueTest, PoC_TokenLeakWhenTryPopOnEmptyQueue)
{
    // rate=1/sec, burst=5 — no significant refill during this test
    CQueue<std::shared_ptr<Dummy>> cq(MIN_QUEUE_CAPACITY, 1.0, 5.0);

    std::shared_ptr<Dummy> value;
    for (int i = 0; i < 5; ++i)
        ASSERT_FALSE(cq.tryPop(value)); // empty queue, drains 5 tokens if leak exists

    for (int i = 0; i < 5; ++i)
        ASSERT_TRUE(cq.push(std::make_shared<Dummy>(i)));

    int popped = 0;
    for (int i = 0; i < 5; ++i)
        if (cq.tryPop(value)) popped++;

    // Fails if tokens were consumed on empty dequeue: popped == 0
    EXPECT_EQ(popped, 5) << "Token leak: tryPop on empty queue consumed tokens. "
                         << "Elements present but unreachable. Popped: " << popped;
}

```
### Result


```bash
 RUN      ] CQueueTest.PoC_TokenLeakWhenTryPopOnEmptyQueue
/workspaces/Wazuh_5x/wazuh/src/engine/source/fastqueue/test/src/component/cqueue_test.cpp:905: Failure
Expected equality of these values:
  popped
    Which is: 0
  5
Token leak: tryPop on empty queue consumed tokens. Elements present but unreachable. Popped: 0
[  FAILED  ] CQueueTest.PoC_TokenLeakWhenTryPopOnEmptyQueue (0 ms)
```

</p>
</details>

File: src/engine/source/fastqueue/include/fastqueue/cqueue.hpp [hunk 2]
```diff
@@ -0,0 +1,228 @@
...
+     *       or return 0 if insufficient tokens are available. This maintains the atomicity of bulk operations.
+     */
+    inline std::size_t tryPopBulk(T* elements, std::size_t max) override
+    {
+        if (m_rateLimiter && !m_rateLimiter->tryAcquire(max))
+        {
+            return 0;
+        }
+        return m_queue.try_dequeue_bulk(elements, max);
+    }
```
Comment (jam300) [inline src/engine/source/fastqueue/include/fastqueue/cqueue.hpp:223]: **Observation**: Possible token leak, `tryAcquire(max) `acquires tokens for the full requested amount, but `try_dequeue_bulk` may return fewer elements. The difference (`max - actual`) tokens is silently lost.

<details><summary>unit test</summary>
<p>

```c++

TEST_F(CQueueTest, PoC_TokenLeakWhenBulkDequeuePartial)
{
    // burst=20, only 10 elements — bulk will request more than available
    CQueue<std::shared_ptr<Dummy>> cq(MIN_QUEUE_CAPACITY, 1.0, 20.0);

    for (int i = 0; i < 10; ++i)
        ASSERT_TRUE(cq.push(std::make_shared<Dummy>(i)));

    std::shared_ptr<Dummy> buf1[20];
    size_t got1 = cq.tryPopBulk(buf1, 20); // acquires 20 tokens, dequeues 10
    ASSERT_EQ(got1, 10);                    // 10 tokens wasted (20 acquired - 10 used)

    for (int i = 0; i < 10; ++i)
        ASSERT_TRUE(cq.push(std::make_shared<Dummy>(100 + i)));

    std::shared_ptr<Dummy> buf2[10];
    size_t got2 = cq.tryPopBulk(buf2, 10);

    // Fails if token leak occurred: got2 == 0 despite 10 elements in queue
    EXPECT_EQ(got2, 10) << "Token leak: tryPopBulk(20) wasted " << (20 - got1)
                        << " tokens on non-existent elements. "
                        << "tryPopBulk(10) returned: " << got2;
}

```
### Result


```bash

[ RUN      ] CQueueTest.PoC_TokenLeakWhenBulkDequeuePartial
/workspaces/Wazuh_5x/wazuh/src/engine/source/fastqueue/test/src/component/cqueue_test.cpp:933: Failure
Expected equality of these values:
  got2
    Which is: 0
  10
Token leak: tryPopBulk(20) wasted 10 tokens on non-existent elements. tryPopBulk(10) returned: 0
[  FAILED  ] CQueueTest.PoC_TokenLeakWhenBulkDequeuePartial (0 ms)

```

</p>
</details>

**Comment by jam300** [comment]
### LGTM

File: src/engine/source/fastqueue/test/mocks/queue/mockQueue.hpp [hunk 3]
```diff
@@ -0,0 +1,26 @@
+#ifndef _MOCK_QUEUE_HPP
+#define _MOCK_QUEUE_HPP
+
+#include <gmock/gmock.h>
+#include <queue/iqueue.hpp>
+
+using namespace base::queue;
+
+namespace queue::mocks
+{
```
Comment (matigarciadev) [inline src/engine/source/fastqueue/test/mocks/queue/mockQueue.hpp:10]: The `fastqueue` mock file is using the include and namespace of the `queue` module.  This file includes `queue/iqueue.hpp` and does not exist in this module.  It should be `fastqueue/iqueue.hpp`, and it uses the namespace `base::queue` and inherits from `iQueue<T>`; here the interface is `fastqueue::IQueue<T>`
