### PR TITLE
Egine update vagrant to v4.8

### LINKED ISSUE #24120: Engine - Update Vagrant environment to Wazuh 4.8.0
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 5.0.0 | Engine | Manager | Packages/Sources | OS version |

## Description:
Currently, the engine is running with Wazuh version 4.7.5.We need to update  to Wazuh version 4.8.0 and verify that all internal decoders continue to function correctly.

## Tasks:
Tasks:
1. Upgrade to Wazuh 4.8.0:
   - Update the environment to use Wazuh version 4.8.0.

2. Engine Compatibility Testing:
   - Conduct a full suite of tests to confirm the engine's compatibility and performance with Wazuh 4.8.0.
   - Document any issues or discrepancies that arise during testing.

3. Internal Decoders Validation:
   - Test all internal decoders in Wazuh to ensure they are functioning correctly with version 4.8.0.
   - Verify that there are no changes or regressions in decoder functionality.

4. Reporting:
   - Compile a detailed report of the testing process, findings, and any identified issues.
   - Provide recommendations for addressing any compatibility or functionality issues discovered.

## Expected Outcome:
- The engine should operate seamlessly with Wazuh version 4.8.0.
- All internal decoders in Wazuh should continue to function correctly.
- Comprehensive documentation of the testing results and any necessary corrective actions.

### PR DESCRIPTION
**Pull request by juliancnn**
|Related issue|
|---|
| closes #24120 |

Some issues have been identified and fixed in this PR:
- [x] Concat helper function, now concatenates json objects and numbers to a string, allowing to generate wdb queries directly with json objects as parameters
- [x] The dbsync decoders have been modified, now the wazuh-db and active response queries are stored in the output of alerts.json.

### CODE REVIEW

File: src/engine/source/builder/src/builders/opmap/opBuilderHelperMap.cpp [hunk 1]
```diff
@@ -613,8 +631,16 @@ MapBuilder opBuilderHelperStringConcat(bool atleastOne)
                 }
                 else
                 {
-                    const auto& value = std::static_pointer_cast<Value>(arg)->value().getString().value();
-                    result.append(value);
+                    if (std::static_pointer_cast<Value>(arg)->value().isString())
+                    {
+                        const auto value = std::static_pointer_cast<Value>(arg)->value().getString().value();
+                        result.append(value);
```
Comment (NahuFigueroa97) [inline src/engine/source/builder/src/builders/opmap/opBuilderHelperMap.cpp:637]: nitpick: this append is repeated. should go outside the conditional sentence

File: src/engine/source/builder/src/builders/opmap/opBuilderHelperMap.cpp [hunk 2]
```diff
@@ -550,13 +550,19 @@ MapBuilder opBuilderHelperStringConcat(bool atleastOne)
...
                 {
                     auto jtype = buildCtx->validator().getJsonType(ref->dotPath());
-                    if (jtype != json::Json::Type::String)
-                    {
-                        throw std::runtime_error(
-                            fmt::format("Expected 'string' reference but got reference '{}' of type '{}'",
-                                        ref->dotPath(),
-                                        json::Json::typeToStr(jtype)));
-                    }
+                       switch (jtype)
```
Comment (NahuFigueroa97) [inline src/engine/source/builder/src/builders/opmap/opBuilderHelperMap.cpp:553]: nitpick: It doesn't seem necessary to use switch here. Isn't an if-else clearer?
```
if (jtype != json::Json::Type::String && 
    jtype != json::Json::Type::Number && 
    jtype != json::Json::Type::Object) 
{
    throw std::runtime_error(fmt::format(
        "Expected 'string/number/object' reference but got reference '{}' of type '{}'",
        ref->dotPath(),
        json::Json::typeToStr(jtype))); // Assuming json::Json::typeToStr is a valid function in the json namespace
}
```

File: src/engine/ruleset/wazuh-core/decoders/dbsync/dbsync.yml [hunk 3]
```diff
@@ -25,28 +25,37 @@ parse|event.original:
...
 
 normalize:
+  - map:
+    - wazuh.decoders: array_append(dbsync)
+
+  # Integrity check
   - check:
       - json_event.type: starts_with(integrity_check_)
     map:
       - _query: concat(agent, ' ', $agent.id, ' ', $json_event.component, ' ', $json_event.type, ' ', $json_event.data)
```
Comment (NahuFigueroa97) [inline src/engine/ruleset/wazuh-core/decoders/dbsync/dbsync.yml:35]: nitpick: I think it would be good to know how the query was set up.

File: src/engine/ruleset/wazuh-core/decoders/dbsync/dbsync.yml [hunk 4]
```diff
@@ -25,28 +25,37 @@ parse|event.original:
...
-      - _query_response: wdb_query($_query)
+      - query_icheck_result: wdb_query($_query)
+
   - check:
-      - _query_response: exists()
+      - query_icheck_result: exists()
     map:
-      - _ar_query: concat('(msg_to_agent) [] N!S ', $agent.id, ' ', $json_event.component, ' ', dbsync, ' ', $_query_response, ' ', $json_event.data)
-      - _ar_result: active_response_send($_ar_query)
+      - ar_query: concat('(msg_to_agent) [] N!S ', $agent.id, ' ', $json_event.component, ' ', dbsync, ' ', $query_icheck_result, ' ', $json_event.data)
```
Comment (NahuFigueroa97) [inline src/engine/ruleset/wazuh-core/decoders/dbsync/dbsync.yml:41]: here he did not put it as a temporary variable

**Review by NahuFigueroa97 — COMMENTED** [review]
LGTM only small observations

File: src/engine/source/builder/src/builders/opmap/opBuilderHelperMap.cpp [hunk 5]
```diff
@@ -613,8 +631,16 @@ MapBuilder opBuilderHelperStringConcat(bool atleastOne)
...
+                    {
+                        const auto value = std::static_pointer_cast<Value>(arg)->value().getString().value();
+                        result.append(value);
+                    }
+                    else
+                    {
+                        const auto value = std::static_pointer_cast<Value>(arg)->value().str();
+                        result.append(value);
+                    }
                 }
```
Comment (juliancnn) [inline src/engine/source/builder/src/builders/opmap/opBuilderHelperMap.cpp:644]: done

**Review by NahuFigueroa97 — APPROVED** [review]
LGTM!

**Review by JcabreraC — APPROVED** [review]
LGTM !
