### PR TITLE
Read logcollector files from BOF during non-startup cycles

### LINKED ISSUE #33382: Logcollector file tailing behavior: review and adjust initial read strategy
## Description

Logcollector currently favors seeking to the end of files when it starts monitoring them, to avoid reporting already-ingested content:

- On startup, when Logcollector begins to monitor an existing file, it performs an `fseek` to the end and starts reading from there.
- When a file appears after the agent is already running (e.g., via a wildcard match or newly created file), Logcollector also seeks to the end before starting to read.
- Exceptionally, Logcollector reads the entire file from the beginning if it detects a rotation or a date change (e.g., files named with a date pattern).

This behavior is designed to prevent duplicate content, but in many real-world scenarios it has the opposite effect: Logcollector misses the initial content of some files (for example, short-lived logs, one-shot logs, or files created and written before Logcollector notices them).

The goal is to:

1. Enumerate all code paths and situations where Logcollector opens a file.
2. Document the current behavior in each case (seek to end vs. read entire file).
3. Decide the desired behavior per case.
4. Implement a consistent strategy, likely restricting “seek to end” behavior to agent startup and only for files that were not previously opened/processed.
5. Assess whether configuration options and documentation changes are needed to clarify and control this behavior.

### Analysis

- [ ] Identify all Logcollector file-opening paths:
  - Startup monitoring of explicitly configured files.
  - Startup monitoring of wildcard-matched files.
  - Files discovered while the agent is already running (wildcards, new files).
  - Files reopened due to rotation (including date-based filenames).
  - Any other special cases (e.g., remote logs, Windows event log wrappers, or platform-specific behaviors if applicable).
- [ ] For each path, document:
  - When and how `fseek` is called (end of file vs. beginning).
  - When a full read from the beginning is performed.

### Design

- [ ] Propose a clear behavior matrix per scenario:
  - Startup with existing files (previously unseen): whether to start at end or beginning.
  - Newly created/matched files while running: whether to start at end or beginning.
  - Rotated files and date-based files: when to re-read fully vs. tail from current/last known offset.
  - Handling of very small or one-shot files (if any special rules are needed).
- [ ] Evaluate options to avoid duplicates while minimizing data loss:
  - Confirm whether we should only seek to end during initial startup, and only for files with no prior state.
  - Define how persisted state (if any) interacts with the new behavior (e.g., offsets or checkpoints).
- [ ] Decide whether a configuration option is required/desired, for example:
  - A mode flag like `read_from_start=true|false`.
  - More granular options (e.g., separate settings for startup vs. runtime-discovered files).
- [ ] Review implications for performance and storage (e.g., cost of reading large existing files from the beginning).

### Implementation

- [ ] Implement the chosen behavior in Logcollector:
  - Adjust all relevant file-open paths to follow the agreed behavior matrix.
  - Ensure rotation handling and date-based naming logic are consistent with the new rules.
- [ ] Add or update configuration options (if approved):
  - Introduce new settings, defaults, and input validation.
  - Ensure backward compatible defaults where possible.
- [ ] Add or update internal documentation describing:
  - When Logcollector seeks to end vs. reads from start.
  - How rotation and date changes are detected and handled.

## Testing

- [ ] Add or extend automated tests (unit/integration) covering:
  - Startup with existing files (previously unseen) of different sizes.
  - Files created while Logcollector is running (wildcard-based and explicit paths).
  - Rotation scenarios (including logrotate-like patterns and date-based filenames).
  - Behavior when configuration options are toggled (if introduced).
- [ ] Perform manual validation scenarios:
  - Confirm that initial lines are not lost for newly created or short-lived files.
  - Confirm that content is not duplicated across rotations.
  - Validate behavior on supported platforms (Linux/Unix, Windows, etc., as applicable).

## Documentation

Update user-facing documentation to describe:
- How Logcollector decides where to start reading a file (startup vs. runtime, rotation, date-based naming).
- Any new/updated configuration options and their defaults.
- Best practices to avoid both duplicates and dropped initial content (e.g., recommendations for log rotation and naming).

## Definition of Done

- [ ] All file-opening scenarios in Logcollector are identified and documented with their previous behavior.
- [ ] A consistent behavior strategy is defined and approved, including handling of:
  - Startup vs. runtime-discovered files.
  - Rotated and date-based log files.
- [ ] Code changes implementing the new behavior are merged, including:
  - Adjustments to `fseek` / initial offset logic.
  - Handling of rotations and date-based changes.
  - New configuration options (if decided) with sane, backward-compatible defaults.
- [ ] Automated tests cover all major scenarios, and test suites pass.
- [ ] Manual validation confirms:
  - Initial content is no longer systematically lost for new or short-lived files.
  - No regressions in duplicate event reporting across rotations.
- [ ] Documentation and changelog are updated to reflect the new behavior and configuration.

### PR DESCRIPTION
**Pull request by anromerom**
## Description

Closes #33382

Currently, Logcollector scans permanently loses all content written to runtime-discovered files from between their creation and discovery. This happens because when `check_pattern_expand()` finds a new file matching a wildcard, `handle_file()` always seeks to EOF (`SEEK_END`), discarding any pre-existing content. This affects all wildcard-monitored log files regardless of the `only-future-events` setting.

## Proposed Changes

- Added a `_startup_completed` flag in `logcollector.c` that distinguishes initial file scanning (startup) from runtime file discovery. The flag is set to `1` immediately after the first full scan loop completes in `LogCollectorStart()`.
- Modified `handle_file()` on the Linux path (and 3 equivalent Windows `#ifdef WIN32` paths) to route runtime-discovered files through `w_set_to_last_line_read()` instead of unconditional `SEEK_END`, even when `only-future-events=yes` (the default).
- Modified `w_set_to_last_line_read()` so that when no saved bookmark exists and `_startup_completed == 1`, the file is read from the beginning (`SEEK_SET`) instead of being skipped to the end (`SEEK_END`). Startup behavior (seek to end for pre-existing files) is preserved.
- Added 3 new CMocka unit tests covering the runtime no-bookmark, runtime hash-error, and startup hash-error scenarios.

### Results and Evidence

A test was executed where a new file was created during runtime (after startup) with 10 lines written. The logs show that the file is being detected and all the existing content at the moment of detection is read and processed as expected.
```
logcollector.c:1362 at check_pattern_expand(): INFO: (1957): New file that matches the
  '/var/log/test/wildcard/*.log' pattern: '/var/log/test/wildcard/deploy-test-1771965028.log'.

logcollector.c:2810 at w_set_to_last_line_read(): DEBUG: New file
  '/var/log/test/wildcard/deploy-test-1771965028.log' discovered at runtime with no bookmark.
  Reading from beginning.

read_syslog.c:104: Reading syslog message: '2026-02-24 20:30:28 MARKER_RUNTIME Deploy started'
read_syslog.c:104: Reading syslog message: '2026-02-24 20:30:28 MARKER_RUNTIME Pulling image'
read_syslog.c:104: Reading syslog message: '2026-02-24 20:30:28 MARKER_RUNTIME Image pulled'
read_syslog.c:104: Reading syslog message: '2026-02-24 20:30:28 MARKER_RUNTIME Container started'
read_syslog.c:104: Reading syslog message: '2026-02-24 20:30:28 MARKER_RUNTIME Health check passed'
read_syslog.c:104: Reading syslog message: '2026-02-24 20:30:28 MARKER_RUNTIME Deploy finished'
read_syslog.c:104: Reading syslog message: '2026-02-24 20:30:28 MARKER_RUNTIME Seven lines total'

read_syslog.c:152: Read 7 lines from /var/log/test/wildcard/deploy-test-1771965028.log
```

Before the fix, 0 of 7 lines would have been read (all skipped by `SEEK_END`).

### Artifacts Affected

- `wazuh-logcollector` (Linux, Windows)

### Configuration Changes

- N/A. No new configuration parameters. Existing `only-future-events` behavior is preserved for files discovered at startup. The change only affects files discovered at runtime (after the initial scan).

### Documentation Updates

- N/A

### Tests Introduced

- `test_w_set_to_last_line_read_no_bookmark_runtime` — Verifies that a file discovered at runtime with no saved bookmark is read from the beginning (`SEEK_SET` with offset 0).
- `test_w_set_to_last_line_read_no_bookmark_runtime_hash_error` — Verifies runtime discovery behavior when the hash table update fails (error path).
- `test_w_set_to_last_line_read_no_bookmark_startup_hash_error` — Verifies that startup behavior is preserved (`SEEK_END`) when the hash table update fails.

## Review Checklist

- [x] Code changes reviewed
- [x] Relevant evidence provided
- [x] Tests cover the new functionality
- [x] Configuration changes documented
- [ ] Developer documentation reflects the changes
- [x] Meets requirements and/or definition of done
- [x] No unresolved dependencies with other issues

### CODE REVIEW

File: src/logcollector/src/logcollector.c [hunk 1]
```diff
@@ -134,6 +134,8 @@ static rwlock_t files_update_rwlock;
 static OSHash *excluded_files = NULL;
 static OSHash *excluded_binaries = NULL;
 
+STATIC volatile int _startup_completed = 0;
```
Comment (cborla) [inline src/logcollector/src/logcollector.c]: In this case, it is best for us to use the atomic type.

**Review by cborla — APPROVED** [review]
LGTM
