### PR TITLE
Persist VD first-sync state in table_metadata

### LINKED ISSUE #35582: Move VD first sync state from flag file to metadata database
## Problem

The Vulnerability Detector first synchronization state is currently persisted using a flag file (`queue/syscollector/db/.vd_first_sync_done`).

At the moment, the code determines whether the first VD synchronization has already been completed by checking if that file exists, and then uses that result to decide whether to run `VDFIRST` or `VDSYNC`. After the first successful VD synchronization, the module creates the flag file to persist that state.

This introduces a file-based persistence mechanism for internal synchronization state, while Syscollector already has a metadata persistence model in `table_metadata` used for other state markers such as `first_sync_completed` and `first_scan_completed`.

Additionally, the current file-based approach only represents a boolean-like state (file exists / does not exist), but it does not persist the actual completion timestamp of the first VD synchronization. That timestamp would be more useful for consistency, observability, debugging, and future extensions.

## Steps to Reproduce
1. Start an agent with Syscollector and Vulnerability Detector synchronization enabled.
2. Allow the first VD synchronization to complete successfully.
3. Observe that the module creates the file `queue/syscollector/db/.vd_first_sync_done`.
4. Verify that the state of the first VD sync is persisted through file existence instead of `table_metadata`.
5. Verify that no timestamp for the first completed VD synchronization is stored in metadata.

## Expected Behavior
The completion of the first VD synchronization should be persisted in the metadata database instead of being represented by a standalone flag file.

Once the first VD synchronization completes successfully, the agent should store a metadata value with the completion timestamp. That metadata value should be the source of truth to determine whether the module must use `VDFIRST` or `VDSYNC`.

## Current Behavior
The module checks whether the first VD synchronization has already completed by validating the existence of the file `.vd_first_sync_done`.

If the first VD synchronization succeeds, the module creates that file and uses its existence in subsequent runs to switch from `VDFIRST` to `VDSYNC`.

As a result:
- the first VD sync state is persisted outside `table_metadata`,
- the persistence model differs from the rest of Syscollector state tracking,
- and the actual first-sync completion timestamp is not stored.

## Additional Information
- The current logic uses `isVDFirstSyncDone()` to check file existence.
- The VD first-sync state affects synchronization behavior, because it decides whether to use `Option::VDFIRST` or `Option::VDSYNC`.
- The same state is also relevant for post-sync behavior such as VD DataContext processing, which is skipped until the first VD sync is considered completed.
- Syscollector already has reusable metadata helpers (`getMetadataValue()` / `updateMetadataValue()`) and a persistent metadata table for similar state markers.

## Impact
Keeping this state in a flag file may cause:
- Inconsistent persistence behavior compared to the rest of Syscollector metadata.
- Loss of the actual first VD sync completion timestamp.
- More fragile behavior if the file is removed, not migrated, or affected by path/permission issues.
- Reduced observability when debugging synchronization flow.
- Extra maintenance complexity due to mixing metadata-based and file-based state tracking.

## Proposal
- Replace the file-based persistence of `vd_first_sync_done` with a metadata entry in `table_metadata`.
- Store the first VD synchronization completion as a timestamp value, for example through a metadata key such as `vd_first_sync_completed`.
- Use that metadata value as the source of truth to determine whether VD must run with `VDFIRST` or `VDSYNC`.
- Consider `value > 0` as "first VD sync already completed".
- Update the current logic so that:
  - before the first successful VD sync, the module uses `VDFIRST`,
  - after the first successful VD sync, the module writes the metadata timestamp,
  - and subsequent runs use `VDSYNC` based on the metadata value instead of file existence.
- Update the logic that currently checks `isVDFirstSyncDone()` so it reads from metadata rather than from the filesystem.
- Define backward compatibility behavior for agents that may already have the legacy `.vd_first_sync_done` file:
  - detect the legacy file,
  - migrate the state once into metadata,
  - and stop relying on the file afterward.
- Add debug logs to clearly indicate:
  - when the first VD synchronization starts,
  - when it completes successfully,
  - when the metadata timestamp is written,
  - when the first-sync state is read from metadata,
  - and when legacy file-based state is detected and migrated.

### PR DESCRIPTION
**Pull request by anromerom**
## Description

Closes #35582

Syscollector was persisting the VD first-sync state in a flag file (`queue/syscollector/db/.vd_first_sync_done`) that stored only a boolean `"1"` value, while all other synchronization markers already lived in the `table_metadata` database with epoch-second timestamps. This PR replaces the flag-file mechanism with a metadata row (`vd_first_sync_completed`),
aligns VD state persistence with the existing `first_sync_completed` / `first_scan_completed` pattern, and adds a one-shot cleanup of any orphan flag file from a pre-fix 5.0 beta install.

## Proposed Changes

- Add `SYSCOLLECTOR_VD_FIRST_SYNC_COMPLETED_METADATA_KEY` (`"vd_first_sync_completed"`) constant in `syscollectorImp.cpp`.
- Replace `isVDFirstSyncDone()` file-existence check with `getMetadataValue("vd_first_sync_completed", v) && v > 0`, making `table_metadata` the single source of truth for the `VDFIRST` / `VDSYNC` decision.
- After a successful `VDFIRST` run, call `updateMetadataValue(SYSCOLLECTOR_VD_FIRST_SYNC_COMPLETED_METADATA_KEY, Utils::getSecondsFromEpoch())` to persist the exact completion timestamp instead of creating a boolean flag file.
- Add `get_vd_first_sync_completed` query command for external callers (parity with `get_first_scan_completed` / `get_first_sync_completed`).

### Results and Evidence

**Before**

```log
2026/04/20 20:54:40 syscollector: DEBUG: VD first sync successful, attempting to create flag file: queue/syscollector/db/.vd_first_sync_done
2026/04/20 20:54:40 syscollector: INFO: VD first sync completed, flag file created
```

1. The flag file `.vd_first_sync_done` exists after initialization. 

```console
$ ls -la /var/ossec/queue/syscollector/db/.vd_first_sync_done
-rw-r--r-- 1 root wazuh 1 Apr 20 20:54 /var/ossec/queue/syscollector/db/.vd_first_sync_done
$ cat /var/ossec/queue/syscollector/db/.vd_first_sync_done
1
```

2. The `first_scan_completed` and `first_sync_completed` marks are present, but no mark for VD.

```sql
# sqlite> select * from table_metadata;
first_scan_completed|1776778793|1
first_sync_completed|1776778802|1
dbsync_browser_extensions|1776778822|1
dbsync_groups|1776778822|1
dbsync_hwinfo|1776778822|1
dbsync_network_address|1776778822|1
dbsync_network_iface|1776778822|1
dbsync_network_protocol|1776778822|1
dbsync_osinfo|1776778822|1
dbsync_packages|1776778822|1
dbsync_ports|1776778822|1
dbsync_processes|1776778822|1
dbsync_services|1776778822|1
dbsync_users|1776778822|1
```

---

**After:**

```log
2026/04/20 19:45:40 syscollector: INFO: VD first sync completed, metadata marker persisted.
```

1. The flag file `.vd_first_sync_done` does not exist. 

```console
$ ls /var/ossec/queue/syscollector/db/.vd_first_sync_done
ls: cannot access '/var/ossec/queue/syscollector/db/.vd_first_sync_done': No such file or directory
```

2. `vd_first_sync_completed` marker present with epoch timestamp, matching the log exactly.

```sql
# sqlite> select * from table_metadata;
first_scan_completed|1776792655|1
first_sync_completed|1776792663|1
vd_first_sync_completed|1776792683|1
dbsync_browser_extensions|1776792683|1
dbsync_groups|1776792683|1
dbsync_hwinfo|1776792683|1
dbsync_network_address|1776792683|1
dbsync_network_iface|1776792683|1
dbsync_network_protocol|1776792683|1
dbsync_osinfo|1776792683|1
dbsync_packages|1776792683|1
dbsync_ports|1776792683|1
dbsync_processes|1776792683|1
dbsync_services|1776792683|1
dbsync_users|1776792683|1
```

### Artifacts Affected

- `syscollector`

### Configuration Changes

- N/A

### Documentation Updates

- N/A

### Tests Introduced

- New unit tests in `syscollectorImp_test.cpp`:

| Test | Scope |
|---|---|
| `queryCommandGetVDFirstSyncCompletedDefaultsToFalse` | `get_vd_first_sync_completed` returns `0` when no marker exists |
| `queryCommandGetVDFirstSyncCompletedReturnsTrueWhenMetadataExists` | returns `1` when a positive timestamp is present in `table_metadata` |
| `queryCommandGetVDFirstSyncCompletedIgnoresZeroTimestamp` | returns `0` when the stored timestamp is `0` (incomplete run) |

## Review Checklist

- [x] Code changes reviewed
- [x] Relevant evidence provided
- [x] Tests cover the new functionality
- [ ] Configuration changes documented
- [ ] Developer documentation reflects the changes
- [x] Meets requirements and/or definition of done
- [x] No unresolved dependencies with other issues

### CODE REVIEW

File: src/wazuh_modules/syscollector/src/syscollectorImp.cpp [hunk 1]
```diff
@@ -2287,7 +2283,28 @@ bool Syscollector::syncModule(Mode mode)
...
+        {
+            if (updateMetadataValue(SYSCOLLECTOR_VD_FIRST_SYNC_COMPLETED_METADATA_KEY, Utils::getSecondsFromEpoch()))
+            {
+                m_logFunction(LOG_INFO, "VD first sync completed, metadata marker persisted.");
+            }
+            else
+            {
+                m_logFunction(LOG_ERROR, "Failed to persist VD first sync metadata marker.");
+            }
+        }
```
Comment (rjcausarano) [inline src/wazuh_modules/syscollector/src/syscollectorImp.cpp]: These same sequence of instructions are used in the executeFlushSync() function.
Can you try to fit the logic in a different function and call it from here and from executeFlushSync()?

**Review by rjcausarano — CHANGES_REQUESTED** [review]

File: src/wazuh_modules/syscollector/tests/sysCollectorImp/syscollectorImp_test.cpp [hunk 2]
```diff
@@ -5722,3 +5753,132 @@ TEST_F(SyscollectorImpTest, destroyWaitsForOngoingFlush)
 
     EXPECT_TRUE(destroyDone);
 }
+
+// ── vd_first_sync_completed marker and query (issue #35582) ──────────────────
```
Comment (rjcausarano) [inline src/wazuh_modules/syscollector/tests/sysCollectorImp/syscollectorImp_test.cpp]: Can you remove this comment?

**Review by rjcausarano — CHANGES_REQUESTED** [review]

File: src/wazuh_modules/syscollector/src/syscollectorImp.cpp [hunk 3]
```diff
@@ -2511,51 +2507,36 @@ std::vector<std::string> Syscollector::getDataContextTables(Operation operation,
...
-bool Syscollector::isVDFirstSyncDone() const
+bool Syscollector::isVDFirstSyncDone()
 {
-    std::ifstream flagCheck(VD_FIRST_SYNC_FLAG_FILE);
-    bool firstSyncDone = flagCheck.good();
-    flagCheck.close();
-    return firstSyncDone;
+    int64_t vdFirstSyncCompleted = 0;
+    return getMetadataValue(SYSCOLLECTOR_VD_FIRST_SYNC_COMPLETED_METADATA_KEY, vdFirstSyncCompleted)
+           && vdFirstSyncCompleted > 0;
```
[the remark this answers is not in the document]
Comment (anromerom) [reply src/wazuh_modules/syscollector/src/syscollectorImp.cpp:2514]: It has been ruled out a backward compatibility with the previous file-based method, as it was introduced on v5.0.

**Comment by anromerom** [comment]
# Validation after rebase

The current code has been tested and confirmed OK after the recent rebase.

1. The flag file is no longer found.

```console
$ ls -la /var/ossec/queue/syscollector/db/
total 3696
drwxr-x--- 1 wazuh wazuh    4096 Apr 22 17:37 .
drwxr-x--- 1 wazuh wazuh    4096 Apr 22 17:37 ..
-rw-r----- 1 root  wazuh  118784 Apr 22 17:39 local.db
-rw-r----- 1 root  wazuh       0 Apr 22 17:39 local.db-journal
-rw-r----- 1 root  wazuh   12288 Apr 22 17:37 syscollector_sync.db
-rw-r----- 1 root  wazuh   32768 Apr 22 17:38 syscollector_sync.db-shm
-rw-r----- 1 root  wazuh 1965272 Apr 22 17:39 syscollector_sync.db-wal
-rw-r----- 1 root  wazuh   12288 Apr 22 17:37 syscollector_vd_sync.db
-rw-r----- 1 root  wazuh   32768 Apr 22 17:39 syscollector_vd_sync.db-shm
-rw-r----- 1 root  wazuh 1594472 Apr 22 17:39 syscollector_vd_sync.db-wal

$ ls -la /var/ossec/queue/syscollector/db/.vd_first_sync_done
ls: cannot access '/var/ossec/queue/syscollector/db/.vd_first_sync_done': No such file or directory
```

2. The related logs are updated
```text
2026/04/22 17:37:59 syscollector: INFO: Starting inventory synchronization.
2026/04/22 17:38:00 syscollector: DEBUG: VD sync was not successful, metadata marker not persisted.
2026/04/22 17:38:00 syscollector: WARNING: Syscollector synchronization process failed.
2026/04/22 17:38:57 syscollector: INFO: Starting inventory synchronization.
2026/04/22 17:39:22 syscollector: INFO: VD first sync completed, metadata marker persisted.
2026/04/22 17:39:22 syscollector: INFO: Syscollector synchronization process finished successfully.
```


3. `table_metadata` row exists and matches logs

```console
$ sqlite3 /var/ossec/queue/syscollector/db/local.db \
      "SELECT table_name, last_sync_time FROM table_metadata
        ORDER BY table_name;"
        
dbsync_browser_extensions|1776879562
dbsync_groups|1776879562
dbsync_hwinfo|1776879562
dbsync_network_address|1776879562
dbsync_network_iface|1776879562
dbsync_network_protocol|1776879562
dbsync_osinfo|1776879562
dbsync_packages|1776879562
dbsync_ports|1776879562
dbsync_processes|1776879562
dbsync_services|1776879562
dbsync_users|1776879562
first_scan_completed|1776879479
first_sync_completed|1776879542
vd_first_sync_completed|1776879562
```

**Review by cborla — APPROVED** [review]
LGTM
- [x] Code changes reviewed
- [x] Relevant evidence provided
- [x] Tests cover the new functionality
- [ ] Configuration changes documented
- [ ] Developer documentation reflects the changes
- [x] Meets requirements and/or definition of done
- [x] No unresolved dependencies with other issues

**Review by rjcausarano — APPROVED** [review]
LGTM

## Review Checklist

- [x] Code changes reviewed
- [x] Relevant evidence provided
- [x] Tests cover the new functionality
- [ ] Configuration changes documented
- [ ] Developer documentation reflects the changes
- [x] Meets requirements and/or definition of done
- [x] No unresolved dependencies with other issues
