### PR TITLE
Pre-installation Architecture Check for Wazuh Agent Packages

### LINKED ISSUE #26455: Upgrade with AMD64 WPK package macOS modifies ARM64 agent and generates a failure in its operation.
| Version | Revision | Production/Development | Component | Install type |
|:--:|:--:|:--:|:--:|:--:|
|  v4.10.0  |  1  | Development   | macOS Agent   | Download/Repository/Sources/Assistant | 

## Description 

During the tests performed at https://github.com/wazuh/wazuh/issues/26434, the test macOS Ventura ARM WPK upgrade failed. I
The test consists of forcing a macOS ARM 4.9.1 Agent using WPK for AMD to upgrade to 4.10.0.

### Environment

- AMI v4.10.0-alpha2 (AWS)
- macOS ARM64 Ventura 13 Agent (Deployed via Allocation module) (Mac Mini)

### Steps to reproduce

- Install and register a 4.9.1 Agent to a 4.10.0 Manager.
- The Agent must be macOS ARM64 Ventura 13.
- After that, download the WPK package for macOS AMD64 and run the upgrade.

### Current result

The process is blocked for an unlimited time.
When performing a manual stop, it is observed that the Agent is disconnected.
The Agent, on the other hand, has done the update (which it shouldn't) and it doesn't work.
It has errors in the log

```console
[root@wazuh-server wazuh-user]# /var/ossec/bin/agent_upgrade -a 014 -f /home/wazuh-user/wazuh_agent_v4.10.0_macos_intel64.pkg.wpk 

Upgrading...
^Z
[2]+  Stopped                 /var/ossec/bin/agent_upgrade -a 014 -f /home/wazuh-user/wazuh_agent_v4.10.0_macos_intel64.pkg.wpk
[root@wazuh-server wazuh-user]# /var/ossec/bin/agent_control -l

Wazuh agent_control. List of available agents:
   ID: 000, Name: wazuh-server (server), IP: 127.0.0.1, Active/Local
   ID: 014, Name: macos-13, IP: any, Disconnected

List of agentless devices:
```

```console
sh-3.2# /Library/Ossec/bin/wazuh-control info
WAZUH_VERSION="v4.10.0"
WAZUH_REVISION="41003"
WAZUH_TYPE="agent"

sh-3.2# /Library/Ossec/bin/wazuh-control restart
/Library/Ossec/bin/wazuh-control: line 120: /Library/Ossec/bin/wazuh-execd: Bad CPU type in executable
wazuh-execd: Configuration error. Exiting

```

- Check error in `/Library/Ossec/logs/upgrade.log`

```console
sh-3.2# cat /Library/Ossec/logs/upgrade.log
2024/10/21 06:36:37 - Upgrade started.
2024/10/21 06:36:37 - Checking execution path.
installer: Package name is wazuh-agent-4.10.0-1.intel64
installer: Upgrading at base path /
installer: The upgrade failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while running scripts from the package “wazuh-agent-4.10.0-1.intel64.pkg”.)
2024/10/21 06:36:40 - Installation result = 1
2024/10/21 06:36:40 - Checking for Wazuh Agent control script.
2024/10/21 06:36:40 - Restarting Wazuh Agent.
./bin/wazuh-control: line 120: /Library/Ossec/bin/wazuh-execd: Bad CPU type in executable
wazuh-execd: Configuration error. Exiting
./var/upgrade/pkg_installer.sh: line 124: ./var/run/wazuh-agentd.state: No such file or directory
2024/10/21 06:36:41 - Waiting connection... Remaining attempts: 30.
2024/10/21 06:36:42 - Status = pending. 
./var/upgrade/pkg_installer.sh: line 124: ./var/run/wazuh-agentd.state: No such file or directory
2024/10/21 06:36:42 - Waiting connection... Remaining attempts: 29.
2024/10/21 06:36:43 - Status = pending. 
./var/upgrade/pkg_installer.sh: line 124: ./var/run/wazuh-agentd.state: No such file or directory
2024/10/21 06:36:43 - Waiting connection... Remaining attempts: 28.
2024/10/21 06:36:44 - Status = pending. 
./var/upgrade/pkg_installer.sh: line 124: ./var/run/wazuh-agentd.state: No such file or directory
2024/10/21 06:36:44 - Waiting connection... Remaining attempts: 27.
2024/10/21 06:36:45 - Status = pending. 
./var/upgrade/pkg_installer.sh: line 124: ./var/run/wazuh-agentd.state: No such file or directory
2024/10/21 06:36:45 - Waiting connection... Remaining attempts: 26.
2024/10/21 06:36:46 - Status = pending. 
./var/upgrade/pkg_installer.sh: line 124: ./var/run/wazuh-agentd.state: No such file or directory
2024/10/21 06:36:46 - Waiting connection... Remaining attempts: 25.
2024/10/21 06:36:47 - Status = pending. 
./var/upgrade/pkg_installer.sh: line 124: ./var/run/wazuh-agentd.state: No such file or directory
2024/10/21 06:36:47 - Waiting connection... Remaining attempts: 24.
2024/10/21 06:36:48 - Status = pending. 
./var/upgrade/pkg_installer.sh: line 124: ./var/run/wazuh-agentd.state: No such file or directory
2024/10/21 06:36:48 - Waiting connection... Remaining attempts: 23.
2024/10/21 06:36:49 - Status = pending. 
./var/upgrade/pkg_installer.sh: line 124: ./var/run/wazuh-agentd.state: No such file or directory
2024/10/21 06:36:49 - Waiting connection... Remaining attempts: 22.
2024/10/21 06:36:50 - Status = pending. 
./var/upgrade/pkg_installer.sh: line 124: ./var/run/wazuh-agentd.state: No such file or directory
2024/10/21 06:36:50 - Waiting connection... Remaining attempts: 21.
2024/10/21 06:36:51 - Status = pending. 
./var/upgrade/pkg_installer.sh: line 124: ./var/run/wazuh-agentd.state: No such file or directory
2024/10/21 06:36:51 - Waiting connection... Remaining attempts: 20.
2024/10/21 06:36:52 - Status = pending. 
./var/upgrade/pkg_installer.sh: line 124: ./var/run/wazuh-agentd.state: No such file or directory
2024/10/21 06:36:52 - Waiting connection... Remaining attempts: 19.
2024/10/21 06:36:53 - Status = pending. 
./var/upgrade/pkg_installer.sh: line 124: ./var/run/wazuh-agentd.state: No such file or directory
2024/10/21 06:36:53 - Waiting connection... Remaining attempts: 18.
2024/10/21 06:36:54 - Status = pending. 
./var/upgrade/pkg_installer.sh: line 124: ./var/run/wazuh-agentd.state: No such file or directory
2024/10/21 06:36:54 - Waiting connection... Remaining attempts: 17.
2024/10/21 06:36:55 - Status = pending. 
./var/upgrade/pkg_installer.sh: line 124: ./var/run/wazuh-agentd.state: No such file or directory
2024/10/21 06:36:55 - Waiting connection... Remaining attempts: 16.
2024/10/21 06:36:56 - Status = pending. 
./var/upgrade/pkg_installer.sh: line 124: ./var/run/wazuh-agentd.state: No such file or directory
2024/10/21 06:36:56 - Waiting connection... Remaining attempts: 15.
2024/10/21 06:36:57 - Status = pending. 
./var/upgrade/pkg_installer.sh: line 124: ./var/run/wazuh-agentd.state: No such file or directory
2024/10/21 06:36:57 - Waiting connection... Remaining attempts: 14.
2024/10/21 06:36:58 - Status = pending. 
./var/upgrade/pkg_installer.sh: line 124: ./var/run/wazuh-agentd.state: No such file or directory
2024/10/21 06:36:59 - Waiting connection... Remaining attempts: 13.
2024/10/21 06:37:00 - Status = pending. 
./var/upgrade/pkg_installer.sh: line 124: ./var/run/wazuh-agentd.state: No such file or directory
2024/10/21 06:37:00 - Waiting connection... Remaining attempts: 12.
2024/10/21 06:37:01 - Status = pending. 
./var/upgrade/pkg_installer.sh: line 124: ./var/run/wazuh-agentd.state: No such file or directory
2024/10/21 06:37:01 - Waiting connection... Remaining attempts: 11.
2024/10/21 06:37:02 - Status = pending. 
./var/upgrade/pkg_installer.sh: line 124: ./var/run/wazuh-agentd.state: No such file or directory
2024/10/21 06:37:02 - Waiting connection... Remaining attempts: 10.
2024/10/21 06:37:03 - Status = pending. 
./var/upgrade/pkg_installer.sh: line 124: ./var/run/wazuh-agentd.state: No such file or directory
2024/10/21 06:37:03 - Waiting connection... Remaining attempts: 9.
2024/10/21 06:37:04 - Status = pending. 
./var/upgrade/pkg_installer.sh: line 124: ./var/run/wazuh-agentd.state: No such file or directory
2024/10/21 06:37:04 - Waiting connection... Remaining attempts: 8.
2024/10/21 06:37:05 - Status = pending. 
./var/upgrade/pkg_installer.sh: line 124: ./var/run/wazuh-agentd.state: No such file or directory
2024/10/21 06:37:05 - Waiting connection... Remaining attempts: 7.
2024/10/21 06:37:06 - Status = pending. 
./var/upgrade/pkg_installer.sh: line 124: ./var/run/wazuh-agentd.state: No such file or directory
2024/10/21 06:37:06 - Waiting connection... Remaining attempts: 6.
2024/10/21 06:37:07 - Status = pending. 
./var/upgrade/pkg_installer.sh: line 124: ./var/run/wazuh-agentd.state: No such file or directory
2024/10/21 06:37:07 - Waiting connection... Remaining attempts: 5.
2024/10/21 06:37:08 - Status = pending. 
./var/upgrade/pkg_installer.sh: line 124: ./var/run/wazuh-agentd.state: No such file or directory
2024/10/21 06:37:08 - Waiting connection... Remaining attempts: 4.
2024/10/21 06:37:09 - Status = pending. 
./var/upgrade/pkg_installer.sh: line 124: ./var/run/wazuh-agentd.state: No such file or directory
2024/10/21 06:37:09 - Waiting connection... Remaining attempts: 3.
2024/10/21 06:37:10 - Status = pending. 
./var/upgrade/pkg_installer.sh: line 124: ./var/run/wazuh-agentd.state: No such file or directory
2024/10/21 06:37:10 - Waiting connection... Remaining attempts: 2.
2024/10/21 06:37:11 - Status = pending. 
./var/upgrade/pkg_installer.sh: line 124: ./var/run/wazuh-agentd.state: No such file or directory
2024/10/21 06:37:11 - Waiting connection... Remaining attempts: 1.
2024/10/21 06:37:12 - Status = pending. 
2024/10/21 06:37:12 - Upgrade failed...
```

```console
sh-3.2# ps aux | grep wazuh 
root             32147   0,0  0,0 408626848   1232 s000  R+    6:51AM   0:00.01 grep wazuh
```

### Expected result
The agent should not update and a message should appear stating that it cannot.

### PR DESCRIPTION
**Pull request by vikman90**
|Related issue|
|---|
|Closes #26455|

## Description

This PR introduces a pre-installation architecture check to ensure compatibility between the system architecture and the Wazuh agent package being installed. The pre-installation script now includes a constant `ARCH`, which is set during the package generation process (either `intel64` or `arm64`), and performs the following checks:

- **Intel64 Package on ARM (Apple Silicon) Systems**:  
  The script checks if Rosetta is installed and active. If Rosetta is not operational, the installation will fail, ensuring that Intel64 packages are not installed without proper Rosetta support.

- **ARM64 Package on Intel Systems**:  
  If an ARM64 package is being installed on an Intel-based system, the installation will fail, preventing the installation of an incompatible package.

## Changes

- Added the `ARCH` constant to the pre-installation script, populated during package generation.
- Implemented system architecture checks in the pre-installation script to ensure compatibility.
- Added logic to check for Rosetta on Apple Silicon when installing Intel64 packages.

## Testing

- [x] Verified the behavior on macOS ARM64 systems (Apple Silicon) for ARM64 packages.
> installer: Package name is wazuh-agent_4.10.0-0_arm64_d64ecc998
installer: Installing at base path /
installer: The install was successful.
- [x] Confirmed that the installation fails if Rosetta is not installed for Intel64 packages on Apple Silicon.
> ./preinstall: ERROR: Rosetta is not installed. Please install it and try again.
- [x] Confirmed that the Intel64 package works on Apple Silicon if Rosetta is installed.
> installer: Package name is wazuh-agent_4.10.0-0_intel64
installer: Installing at base path /
installer: The install was successful.
- [x] Verified that installation fails when attempting to install ARM64 packages on Intel-based macOS systems.

### CODE REVIEW

**Comment by mjcr99** [comment]
Hello team, the third test required has been performed following the next steps:
* Try to install the arm64 package in a intel64 host:
```
vagrant@macos-14 ~ % sudo installer -pkg wazuh-agent_4.10.0-0_arm64_d64ecc998.pkg -target /  
installer: Package name is wazuh-agent_4.10.0-0_arm64_d64ecc998
installer: Upgrading at base path /
installer: The upgrade failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while running scripts from the package “wazuh-agent_4.10.0-0_arm64_d64ecc998.pkg”.)
```
The installation does fail.

* Check the `/var/log/install.log` file looking for fail logs:
```
vagrant@macos-14 ~ % cat /var/log/install.log | grep "ERROR"
2024-10-23 04:46:25-07 macos-14 package_script_service[2299]: ./preinstall: ERROR: Incompatible architecture. Please use the ARM64 package on this system.                                         
```

File: packages/macos/package_files/preinstall.sh [hunk 1]
```diff
@@ -20,6 +21,23 @@ function check_errm
...
+{
+    local system_arch=$(uname -m)
+
+    if [ "$ARCH" = "intel64" ] && [ "$system_arch" = "arm64" ]; then
+        if ! arch -x86-64 zsh -c '' &> /dev/null; then
+            echo "ERROR: Rosetta is not installed. Please install it and try again."
+            exit 1
+        fi
+    elif [ "$ARCH" = "arm64" ] && [ "$system_arch" = "x86_64" ]; then
+        echo "ERROR: Incompatible architecture. Please use the ARM64 package on this system."
```
Comment (mjcr99) [inline packages/macos/package_files/preinstall.sh:34]: If `$system_arch` is `x86_64` we should request to install the `intel64` package instead of the `ARM64`

**Review by mjcr99 — CHANGES_REQUESTED** [review]

**Review by mjcr99 — DISMISSED** [review]
LGTM!

**Review by mjcr99 — APPROVED** [review]
