### PR TITLE
7474 network name encoding exception

### LINKED ISSUE #7474: Exception on network name field with different encoding.
## Description

This issue aims to solve a problem in the json format from a particular encoding, and it is reproducible with a accent in some vowel in the name of the network adapter.

Actual result:
imagen
Expected: No throw exception.

##DoD
- [x] RCA
- [x] Modify widestring to string conversion.
- [x] Add unit test.
- [x] PR CI PASS

### PR DESCRIPTION
**Pull request by konangc87**
|Related issue|
| Closes #7474  |

## Description
This PR aims to fix the issue found in network adapters name resolution on Windows-ES.

## DoD
- [X] Implementation
- [X] Manual tests
image

### CODE REVIEW

File: src/shared_modules/utils/windowsHelper.h [hunk 1]
```diff
@@ -216,7 +216,11 @@ namespace Utils
             const std::wstring wfriendlyName(adapterName);
             if (!wfriendlyName.empty())
             {
-                retVal.assign(wfriendlyName.begin(), wfriendlyName.end());
+                const auto wSize{static_cast<int>(wfriendlyName.size())};
+                const auto sizeNeeded {WideCharToMultiByte(CP_UTF8, 0, wfriendlyName.data(), wSize, nullptr, 0, nullptr, nullptr)};
+                const auto buffer{std::make_unique<char[]>(sizeNeeded)};
+                WideCharToMultiByte(CP_UTF8, 0, wfriendlyName.data(), wSize, buffer.get(), sizeNeeded, nullptr, nullptr);
```
Comment (tinachoB) [inline src/shared_modules/utils/windowsHelper.h:222]: I think we should check the `WideCharToMultiByte` return value to avoid unexpected behaviors (and static tool analysis reports)

**Review by Dwordcito — APPROVED** [review]

**Review by tinachoB — APPROVED** [review]
LGTM!
