### PR TITLE
Fix logging C++ mechanism to avoid heap allocations

### LINKED ISSUE #31914: Avoid unnecessary `std::string` allocation in `loggerHelper.h`
## Description  

In `loggerHelper.h`, the `const char* msg` parameter (3rd argument) is currently converted into a `std::string` during the call to `GLOBAL_LOG_FUNCTION`.  

This conversion can trigger **unnecessary memory allocations** when the message size exceeds the **SSO (Small String Optimization)** threshold (~16–21 bytes, depending on the standard library implementation).  

The impact is threefold:  
- **Performance** → frequent log calls with long messages cause repeated heap allocations.  
- **Memory** → increased memory churn due to temporary allocations.  
- **Scalability** → degraded efficiency in high-throughput logging scenarios.  

---

## Proposed Solution  

- Backport the fix already introduced in **5.0**:  
  - [PR #31232](https://github.com/wazuh/wazuh/pull/31232)  -- Commit https://github.com/wazuh/wazuh/commit/7db9c79cc8ff43c1d282f2c37db36672cdce5cb6

---

## Definition of Done  

- [x] Apply the fix.  
- [x] Provide test results or profiling evidence comparing behavior before and after the change.

### PR DESCRIPTION
**Pull request by GabrielEValenzuela**
# Description  
Closes #31914   

This PR refactors the logger logic to improve performance, memory and scalability. 

---

## Proposed Changes  

Change the `const char* msg` parameter (3rd argument) is not longer converted into a `std::string` during the call to `GLOBAL_LOG_FUNCTION`.  

This conversion can trigger **unnecessary memory allocations** when the message size exceeds the **SSO (Small String Optimization)** threshold (~16–21 bytes, depending on the standard library implementation)

---

## Results and Evidence  
- Benchmarking

```console
Running ./src/build/shared_modules/utils/benchmark/utils_benchmark_test
Run on (16 X 4700 MHz CPU s)
CPU Caches:
  L1 Data 48 KiB (x8)
  L1 Instruction 32 KiB (x8)
  L2 Unified 1280 KiB (x8)
  L3 Unified 24576 KiB (x1)
Load Average: 3.18, 2.85, 2.23
***WARNING*** CPU scaling is enabled, the benchmark real time measurements may be noisy and will incur extra overhead.
***WARNING*** Library was built as DEBUG. Timings may be affected.
---------------------------------------------------------
Benchmark               Time             CPU   Iterations
---------------------------------------------------------
BM_Log_CString       45.7 ns         44.8 ns     13584149
BM_Log_String         160 ns          160 ns      4234197
```

---

### Automated Tests  
- [ ] Unit tests updated/added where necessary.  
- [ ] Integration tests reviewed for feature disablement.  

### Manual Tests  
- [x] Compilation without warnings (Linux).  
- [x] Memory checks (Valgrind / ASAN).  

---

## Artifacts Affected  
- [ ] Configurations.  
- [ ] Documentation.  

---

## Review Checklist  
- [ ] Code reviewed (correctness, clarity).  
- [ ] Security implications reviewed.  
- [ ] Performance validated.  
- [ ] Documentation updated (marking feature disabled).  
- [ ] CI/CD pipeline green.

### CODE REVIEW

File: src/shared_modules/content_manager/src/contentModuleFacade.cpp [hunk 1]
```diff
@@ -12,10 +12,9 @@
...
 namespace Log
 {
-    std::function<void(
-        const int, const std::string&, const std::string&, const int, const std::string&, const std::string&, va_list)>
+    std::function<void(const int, const char*, const char*, const int, const char*, const char*, va_list)>
         GLOBAL_LOG_FUNCTION;
-};
+}; // namespace Log
 
 void ContentModuleFacade::start(
```
Comment (JcabreraC) [inline src/shared_modules/content_manager/src/contentModuleFacade.cpp:19]: The function `start()` has not been changed:
```
void ContentModuleFacade::start(
    const std::function<void(const int, const char*, const char*, const int, const char*, const char*, va_list)>&

        logFunction)
{
    Log::assignLogFunction(logFunction);
}
```
The header `contentModuleFacade.hpp` is also outdated.

Comment (GabrielEValenzuela) [reply src/shared_modules/content_manager/src/contentModuleFacade.cpp:19]: Fixed!

**Review by MiguelazoDS — COMMENTED** [review]
Could it be possible that we need to update the content manager testtool, inventory harvester testtool, vulnerability scanner testtool?

**Comment by GabrielEValenzuela** [comment]
I think the testtool are rarely used, but we can add the requested change :)

**Review by MiguelazoDS — APPROVED** [review]
I don't find any issue in logging for some of the affected modules (vulnerability scanner, indexer connector, content-updater) 

[logs.log](https://github.com/user-attachments/files/22640900/logs.log)

- Full log
[ossec.log](https://github.com/user-attachments/files/22640906/ossec.log)
